### ISSUE TITLE
encoding issue for both Tmail and OpenPaaS

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#1007]
![image](https://user-images.githubusercontent.com/6462404/192514254-73217b72-9a5e-499f-88f0-231e6e35a330.png)

> I download the .eml from OpenPaas and i can read it in my terminal, file command indicates it is UTF8 and reading the email headers I can read it indicate is UTF8

> Note: This only happened to me with this emails, in the past all emails in french where properly showed.

**Comment by chibenwa** [comment]
Likely issue with Freddy MUA.

We also fixed some encoding issue lately, on backend side.

Please re-open if this happens again
