### ISSUE TITLE
Error when deleting mailbox

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#1008]
### Description

```
Given mailbox `a`
And mailbox `a/b`

When I delete mailbox `b` in OpenPaaS
And then I delete mailbox `a` in TMail

Then Deletion fails in TMail
```

### Expected result

TMail should handle `Mailbox/set` destroy **notFound** response code. If it's not found, it no longer exist and we thus don't need to delete it. It's not a failure and we can continue the deletion chain by deleting `a`...

### Current behavior

https://user-images.githubusercontent.com/6928740/192670271-a3f1531f-121b-44bc-bcbf-0ced229b0ca4.mp4

**Comment by dab246** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Tmail-Flutter-60d039db6ef62a0013432c14/issues/linagora/tmail-flutter/1008?planning-poker) with Zenhub @hoangdat @ManhNTX @sherlockvn

**Comment by dab246** [comment]
1 HD

**Comment by hoangdat** [comment]
1 HD

**Comment by dab246** [comment]
1 HD
