### ISSUE TITLE
cache email is not up-to-date when this is update from IMAP client

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#1009]
https://user-images.githubusercontent.com/6462404/192684679-e9e614c1-c716-44d9-84d0-109226828460.mov

### Diagnose
- Missing push notification to update cache
- Should have a workaround solution with current status

**Comment by dab246** [comment]
@hoangdat I checked on ThunderBird. It works well. I'm checking in on AppleMail


https://user-images.githubusercontent.com/80730648/192734047-3b4d70fc-0336-48af-9ecd-7e73e6bc52b3.mov

**Comment by dab246** [comment]
2 HD

**Comment by dab246** [comment]
2 HD

**Comment by dab246** [comment]
2 HD
