### ISSUE TITLE
[Delete draft mail] deleted draft mails from mobile app are still visible on web browser and vice versa

### ISSUE THREAD

**Issue by haftus98** [linagora/tmail-flutter#1010]
Delete mail from web
[Untitled_ Sep 28,2022 12_11 AM.webm](https://user-images.githubusercontent.com/97084773/192692916-c01509af-6f15-4a10-9564-15d82984608a.webm)

reload from app

https://user-images.githubusercontent.com/97084773/192693097-d0f80cdc-943d-4b74-a1f7-73fcd3386006.mp4

**Comment by chibenwa** [comment]
Yes they should disappear when you refresh the view.

Opening a deleted email should lead to a clear error. Can you open an issue for this too @haftus98 ?

**Comment by hoangdat** [comment]
Hi @haftus98 , please dont test on the out date version. Please test on https://app.bitrise.io/app/65a09a1adc0a6afa/build/cea28d87-39c0-4aaa-9481-090621ce1838/artifact/745ba0d0d01e600d/p/03c69d18b6fa915c771912ebc20f5dde during the time we waiting for resolve releasing problem

**Comment by haftus98** [comment]
I was checking on version of 0.3.15, was it the correct one to check the issue? @hoangdat

**Comment by haftus98** [comment]
https://user-images.githubusercontent.com/97084773/192723958-297aaab3-52a3-466c-b6ac-50ef862e2b80.mp4

**Comment by hoangdat** [comment]
yes, that is

**Comment by dab246** [comment]
2 HD
