### ISSUE TITLE
[EPIC] Quotas

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#1012]
Docs: #33

**Comment by hoangdat** [comment]
@dieptran88 please update the related story with this epic. Thanks

**Comment by hoangdat** [comment]
Hi @chibenwa, @Arsnael. I ask about the typo in Quota/get: 
- this definition for `datatypes` in docs:
<img width="711" alt="image" src="https://user-images.githubusercontent.com/6462404/201616811-afda5c83-780b-424c-9bff-d830e86d0009.png">

- this is what we get from teammail-backend:
![signal-2022-11-14-155425_002](https://user-images.githubusercontent.com/6462404/201617514-c5698e0a-afac-42dd-8213-00f5ea499339.jpeg)

which is right, I ask because of interoperability

**Comment by Arsnael** [comment]
What you get from Tmail backend is a lucky mistake, as I've been asked to change it in my draft from datatypes to dataTypes

So what returns our api is correct, and note that it's been fixed in the latest draft push of jmap quota too
