### ISSUE TITLE
[Dev] Show quota at the bottom of mailbox

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#1014]
### Story
- #1025 

### Desc: 
- Check capability in session.
- Update the view at the bottom of mailbox
- Highlight the limit in the view

### References
- Design: https://www.figma.com/file/rRVxJpCu1G22D0jqyvK7I9/TeamMail?node-id=2%3A17

**Comment by dab246** [comment]
#33

**Comment by dab246** [comment]
2 HD

**Comment by dab246** [comment]
2 HD

**Comment by dab246** [comment]
2 HD

**Comment by haftus98** [comment]
![image.png](https://images.zenhubusercontent.com/632aca085051fb7959dab94b/60a0883d-3726-46d4-a553-e2f6df32f038)

v0.4.3 production no quota showed

**Comment by hoangdat** [comment]
Quota right now support in Preprod env? Am I right? @ManhNTX

**Comment by chibenwa** [comment]
Not an issue: no quota are set on prod. That is the expected behaviour IMO
