### ISSUE TITLE
Scroll up to top button

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#1017]
### Desc
When user scroll down to many many messages, user need a way to top

**Comment by hoangdat** [comment]
Design: https://www.figma.com/file/rRVxJpCu1G22D0jqyvK7I9/TeamMail?node-id=7687%3A329607&t=djEs7exy8CcUSlqE-4

**Comment by chibenwa** [comment]
Done in 0.10.1 ?

**Comment by chibenwa** [comment]
Including web?
