### ISSUE TITLE
[Story] As a user, I can see the application menu on top right of screen in web browser 

### ISSUE THREAD

**Issue by dieptran88** [linagora/tmail-flutter#1018]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC

* TODO: {link}

## Definition

- Given that I am a TMail user 
- I logged in to Tmail web successfully
- On the top right of screen, I can see a dashboard icon
- When I click on this icon, I can see the list of application icons: Calendar, Contact, LinShare, Twake 
- When I click on one application, It will be opened in a new tab
- This application menu can be enabled/disabled in system configuration, depending on product package: When it is disabled, I cannot see the dashboard icon on the top right of screen.

[Back to Summary](#summary)

## Screenshots

![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/8c0d8533-23d9-425d-9768-31c21bfc42a8)

## Design ticket

https://ci.linagora.com/linagora/lgs/design/-/issues/292

[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

**Comment by chibenwa** [comment]
This is only for **web**. Drop the mobile part, it do not make sense.

**Comment by dab246** [comment]
1 HD

**Comment by dab246** [comment]
2 HD
