### ISSUE TITLE
[Reload page] page went blank when reloading page without clearing cache

### ISSUE THREAD

**Issue by haftus98** [linagora/tmail-flutter#1021]
[Untitled_ Sep 29,2022 4_33 PM.webm](https://user-images.githubusercontent.com/97084773/192996700-0299f11b-4a37-4d9d-acbe-c01dcdbcb2d3.webm)

I tested on Chrome Version 106.0.5249.62

**Comment by ManhNTX** [comment]
I've tested it on Windows and it working fine. 
https://images.zenhubusercontent.com/378835363/9541f024-d85d-4b3c-b41c-fd508e8e4f73/bandicam_2022_10_06_10_42_11_779.mp4

**Comment by haftus98** [comment]
[log_reload_f5_tmail_error.txt](https://github.com/linagora/tmail-flutter/files/9733058/log_reload_f5_tmail_error.txt)

Step 1: normal reload tmail with F5 returns blank page
Step2: clear cache + hard reload, tmail loads successfully
