### ISSUE TITLE
[Mobile/Vacation] enabled message didn't show from Android

### ISSUE THREAD

**Issue by haftus98** [linagora/tmail-flutter#1031]
https://user-images.githubusercontent.com/97084773/193255261-6af14d7b-dacb-4766-99be-8e663011ae34.mp4

**Current BH**
I was on vacation mode, on web browser and IOS, the message showed I was on vacation. However, from Android, the message didnt appear not until I opened the vacation settings (like in video)

samsung galaxy a51 , Tmail V 0.3.15

**Comment by dab246** [comment]
Fixed at #1024
