### ISSUE TITLE
Apply new rich text toolbox for Tablet

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#1034]

**Comment by dab246** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Tmail-Flutter-60d039db6ef62a0013432c14/issues/linagora/tmail-flutter/1034?planning-poker) with Zenhub @hoangdat @ManhNTX

**Comment by dab246** [comment]
2 HD

**Comment by dab246** [comment]
2 HD

**Comment by dab246** [comment]
Test again `#1064->#1066`

**Comment by dab246** [comment]
2 HD

**Comment by dab246** [comment]
2 HD

**Comment by dab246** [comment]
2 HD

**Comment by dab246** [comment]
1 HD
