### ISSUE TITLE
[Composer] I clicked on the [+] button but nothing happened

### ISSUE THREAD

**Issue by haftus98** [linagora/tmail-flutter#1038]
[Untitled_ Oct 03,2022 9_48 PM.webm](https://user-images.githubusercontent.com/97084773/193607168-1b6bf053-e47a-45fa-9708-03b74667a221.webm)

**Current BH**
I clicked the + button but nothing happened.

**Comment by dab246** [comment]
Oh, we're not doing anything for this action right now. IMO, we should remove this button. What do you see? @hoangdat

**Comment by chibenwa** [comment]
> Oh, we're not doing anything for this action right now. IMO, we should remove this button. What do you see? @hoangdat

Agreee

**Comment by hoangdat** [comment]
let me check with designer, this button come from Dmitri :))))

**Comment by hoangdat** [comment]
### DoD:
- because of auto complete, remove this redundant button
