### ISSUE TITLE
[Unread mail number] Tmail doesn't show the correct number when I read mail from Thunderbird

### ISSUE THREAD

**Issue by haftus98** [linagora/tmail-flutter#1039]
[Untitled_ Oct 03,2022 9_36 PM.webm](https://user-images.githubusercontent.com/97084773/193605534-780da069-b1be-4d01-9884-ae74e14b50fa.webm)

**Descriptions**
My folder showed 1 unread mail. I read the unread mail from Thunderbird then got back to Tmail to reload and check the unread number. The unread number is still 1.

**Expected**
Count the correct number.

**Comment by chibenwa** [comment]
We do not have real time for updates in TMail just yet.

**Comment by haftus98** [comment]
@chibenwa I did reload the page from Tmail to see the updated unread mail number. it wasn't realtime I was talking about

**Comment by hoangdat** [comment]
https://user-images.githubusercontent.com/6462404/194236473-690e9540-3648-49a1-b1d7-14ca11e8098d.mov

will be release in v0.3.16

**Comment by hoangdat** [comment]
### fixed:
- Synchronized the changes when refresh
