### ISSUE TITLE
[Feedback] Connection pop up never be disappear

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#1042]

**Comment by hoangdat** [comment]
can not reproduce

**Comment by dab246** [comment]
### DoD
- Create `NetworkConnnectionController` to handle store variable check  state `show/hide` notification 
- Apply new design https://www.figma.com/file/rRVxJpCu1G22D0jqyvK7I9/TeamMail?node-id=6501%3A286595
