### ISSUE TITLE
[Advanced search] removing filter by attachment doesn't return the  correct number

### ISSUE THREAD

**Issue by haftus98** [linagora/tmail-flutter#1043]
[Untitled_ Oct 04,2022 5_52 PM.webm](https://user-images.githubusercontent.com/97084773/193801554-83103dee-02df-474d-95a5-06c035873bba.webm)

**Step to reproduce:**
1. Filter attachment mails
2. Remove the check but don't click search
3. reopen the advance search bar, now click search
4. Now it's supposed to return the list of all mail, but from the video it returned 1 mail with attachment

**Comment by dab246** [comment]
1 HD

**Comment by haftus98** [comment]
[Untitled_ Nov 21,2022 10_48 PM.webm](https://user-images.githubusercontent.com/97084773/203098457-c844de51-0cac-4e32-9a3d-8c581767d054.webm)

**Description**
I loaded all mails and then searched with advanced search (had attachment/all time), Tmail returned only 1 mail. Then I removed the advanced search then clicked search, Tmail returned only 20 mails. 

**Environment** 
v0.4.2 google chrome

**Comment by hoangdat** [comment]
hard to understand your reproduce steps. please update it @haftus98

**Comment by dab246** [comment]
I have followed the steps as described, but no errors appear. In my opinion this bug has been fixed from previous PRs.

**Comment by chibenwa** [comment]
@QuangHoang1210 ?

**Comment by QuangHoang1210** [comment]
1, I used to reproduce this issue but I didn't see issue which responde 1 email at email listing. -- So this ticket should be closed.

2, I found other issue relate to this advance search function. Please following bellow ticket.
https://github.com/linagora/tmail-flutter/issues/1477

@chibenwa @dab246 @hoangdat
