### ISSUE TITLE
[Forwarding] I didn't receive forwarded mails

### ISSUE THREAD

**Issue by haftus98** [linagora/tmail-flutter#1047]
[Untitled_ Oct 05,2022 4_25 PM.webm](https://user-images.githubusercontent.com/97084773/194027720-8e51028e-cc27-4704-b768-1fc5dee5feb1.webm)

**Description:**
I added email A to the forwarding recipient list of email B, then I sent an email to email B. Email A didn't receive anymail

**Comment by dab246** [comment]
I tried again on the latest version `0.3.17` and it works fine. @haftus98 Try to check again. I think it may be because the server has a problem while you test.

**Comment by dab246** [comment]
Not test with Gmail @haftus98 . Please check again on server jmap.linagora.com
