### ISSUE TITLE
[Automail] I didn't receive automail from Tmail but Outlook and Openpaas

### ISSUE THREAD

**Issue by haftus98** [linagora/tmail-flutter#1051]
**Description**
I received automail from Outlook and Openpaas, but the Tmail'

![image](https://user-images.githubusercontent.com/97084773/194217525-ce7e571c-ffa2-456f-af0f-11ea16e563cd.png)

**Reproduce**
1. Sent mail from Tmail to left mail: qhta@linagora.com
2. Check the mail from Outlook and Tmail.

**Comment by hoangdat** [comment]
https://user-images.githubusercontent.com/6462404/194244264-02120765-6f58-4034-9f9c-5ef7a18ac1f6.mov

### DoD:
- Synchronize the changes

Please test in v0.3.16
