### ISSUE TITLE
[Mark as read] can't click mark button during the search

### ISSUE THREAD

**Issue by haftus98** [linagora/tmail-flutter#1063]

**Comment by chibenwa** [comment]
What is the environment?

I cannot reproduce on tmail.linagora.com...

A video could be nice here too...

**Comment by haftus98** [comment]
[Untitled_ Oct 13,2022 4_24 PM.webm](https://user-images.githubusercontent.com/97084773/195558295-888bd0d5-8957-4265-a0fc-0a20bcc6ebc1.webm)
