### ISSUE TITLE
[Feedback] Store the recent jmap URL to avoid user to input again and again

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#1068]
### Desc:

- User have some difficult to remember the Configuration (JMAP server) when using mobile app
- User have some difficult to re-input the username(email) when using mobile app
- Any advance configuration to enable Autofill in mobile app for password

### DoD:
- [ ] Make recent list for input of URL
- [ ] Make recent list for input of email
- [ ] Any advance configuration to enable Autofill in mobile app for password

**Comment by dab246** [comment]
1 HD

**Comment by dab246** [comment]
1 HD

**Comment by chibenwa** [comment]
Also maybe we could cache the user login while we are at it?

**Comment by dab246** [comment]
1 HD

**Comment by dab246** [comment]
1 HD

**Comment by dab246** [comment]
1 HD
