### ISSUE TITLE
[Story] As a user, I want to select some mailboxes to delegate for another user 

### ISSUE THREAD

**Issue by dieptran88** [linagora/tmail-flutter#1073]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC

* TODO: {link}

## Definition

**UC1 As a user, I can select mailboxes in adding delegate screen**

* Given that I am a Tmail user. 
* After logged in successfully, When I click on my avatar and select  'Mange account' there will be a new tab : Delegates 
* I can see the list of my current delegates 
* I click button "Add delegate"
* A popup will be displayed, there will be 2 fields:
   * Name or email address:  allowing me to search and  to choose the user from suggestion list to delegate the account to
   * Select mailbox: A drop-down list of my current mailboxes and I can select some mailboxes to delegate. 
   * Default selection is All mailboxes. 
* After choosing a user to delegate my account and select mailboxes, I click button to Add, the system displays successful notification.
* Now I can see the new added delegate in the list.

[Back to Summary](#summary)

## Screenshots

![New Wireframe 1 (52).png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/d19c48c4-edb7-4729-89a3-5a4f162be67f)

[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

**Comment by chibenwa** [comment]
No, delegation should be all, or nothing. Let's not make our life needlessly complicated.

**Comment by hoangdat** [comment]
okie close it
