### ISSUE TITLE
[Account] Signout then load a new link, the account is still visible

### ISSUE THREAD

**Issue by haftus98** [linagora/tmail-flutter#1074]
[Untitled_ Oct 13,2022 11_03 AM.webm](https://user-images.githubusercontent.com/97084773/195499469-0f859e2e-6fa8-41b1-8c9b-3d25773308b4.webm)

**Reproduce**
Step 1: Logout from the current account
Step 2: Load a new link. For ex: https://tmail.linagora.com/#/mailboxDashBoard

**Expected**
The loaded link directs user to the signin page

**Comment by dab246** [comment]
-  Check path url `domain/####` exist => call reload on web.
-  Refactor path url flutter web

**Comment by dab246** [comment]
1 HD

**Comment by dab246** [comment]
2 HD

**Comment by dab246** [comment]
2 HD
