### ISSUE TITLE
[Dev] Support `quotas` in `jmap-dart-client`

### ISSUE THREAD

**Issue by dab246** [linagora/tmail-flutter#1078]
### DoD 
- Add capability `urn:ietf:params:jmap:quota` 
- Add object `Scope`, `ResourceType ` and `Quota`
- Implement `method/response` for `Quota/get`
- Write unit-test for `method/response`

### References
- Docs: https://jmap.io/spec-quotas.html
- https://github.com/linagora/tmail-flutter/issues/33#issuecomment-1258949595

**Comment by dab246** [comment]
@hoangdat  @chibenwa Please help me.

When I execute get `Quota` via `Quota/get` method I get such an error

![Screen Shot 2022-10-14 at 16.58.38.png](https://images.zenhubusercontent.com/605059df174a357c7888640f/4ccb9003-b68c-40cb-b912-0cf5c6e0b808)chi

**Comment by hoangdat** [comment]
@dab246 please use `urn:ietf:params:jmap:quota`

**Comment by dab246** [comment]
> @dab246 please use urn:ietf:params:jmap:quota

Session does not have this capability so it will return an error.

![Screen Shot 2022-10-14 at 16.44.02.png](https://images.zenhubusercontent.com/605059df174a357c7888640f/549b9ec9-9c5c-4bbc-9535-38f0da8c307b)

**Comment by dab246** [comment]
@Arsnael Please check help me.

**Comment by hoangdat** [comment]
hi @Arsnael please help us on that. `quota` was implemented on what environment

**Comment by chibenwa** [comment]
`Quota/get` is currently in development.

Wait a few days ;-)

**Comment by hoangdat** [comment]
Ahhh, okie

**Comment by dab246** [comment]
2 HD
