### ISSUE TITLE
[Folder] I can't  delete many folders at the same time

### ISSUE THREAD

**Issue by haftus98** [linagora/tmail-flutter#1080]
![image](https://user-images.githubusercontent.com/97084773/195820620-c8bfa4a8-c7b7-4c88-8c2e-80eb0f9e7f4c.png)

**Description**
For now, from mobile when I want to select many folders to delete, the button gets disable and I can't do so

**Expected**
I can select many folders to delete. And there should be a warning when I select a folder in which there are existing mails to perform the deleting action.

**Comment by dab246** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Tmail-Flutter-60d039db6ef62a0013432c14/issues/linagora/tmail-flutter/1080?planning-poker) with Zenhub @hoangdat @ManhNTX @sherlockvn

**Comment by dab246** [comment]
1 HD
