### ISSUE TITLE
s/TMail/Team-Mail/g

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#1090]
![Screenshot from 2022-10-18 15-16-58](https://user-images.githubusercontent.com/6928740/196375895-f83c235c-6fde-46b9-a6c8-8166c9b6d9f4.png)

**Comment by hoangdat** [comment]
@dieptran88 please create design ticket to request the update for design team in:
- [ ] icon, 
- [ ] store kit, 
- [ ] splash screen

Thanks

**Comment by chibenwa** [comment]
Don't forget

 - [ ] README

**Comment by hoangdat** [comment]
duplicated #1169
