### ISSUE TITLE
[UI] Email is not aligned in the middle

### ISSUE THREAD

**Issue by haftus98** [linagora/tmail-flutter#1091]
![image](https://user-images.githubusercontent.com/97084773/196592082-ad8d0ec0-1dd8-47c9-8446-9e3b74000d6c.png)

1. Double email
2. wrong alignment

**Comment by chibenwa** [comment]
> Double email

Likely not a problem... The auto-complete is screwed so far on op.lng, we use email address for "emailAddress" and "Display Name". => Ignore this.

**Comment by chibenwa** [comment]
![Screenshot from 2022-10-19 11-48-00](https://user-images.githubusercontent.com/6928740/196600236-2a1a5d47-a6aa-40d9-8ff2-5fc8652e8330.png)

![Screenshot from 2022-10-19 11-48-25](https://user-images.githubusercontent.com/6928740/196600244-c9834e40-95ca-47d8-a4dd-76106d495a2d.png)

You should not have the duplicate address on newly sent email now ^^
