### ISSUE TITLE
[forward mail] Forward multiple mails at a time function

### ISSUE THREAD

**Issue by haftus98** [linagora/tmail-flutter#1092]
For now, from email list of inbox, I can't click anywhere to forward email so I have to open that mail and forward it, which leads to the fact that I can't forward many mails at a time

**Comment by hoangdat** [comment]
not a good suggestion? any comparation?

**Comment by chibenwa** [comment]
Still you would want to input dedicated infos for each email forwarded.

Minor gains, complex UX.

IMO let's keep the UX simple!
