### ISSUE TITLE
[Compose mail] can't compose multiple mails at a time when selecting button "compose mail"

### ISSUE THREAD

**Issue by haftus98** [linagora/tmail-flutter#1101]
[Untitled_ Oct 21,2022 3_00 PM.webm](https://user-images.githubusercontent.com/97084773/197145976-47c15881-b52a-4579-9848-902f9a70a1c7.webm)

**Reproduce:**
Step 1: Compose mail, input an email
Step2: Select an mail, click compose email

**Expected** 
Add email to the composing process

**Comment by chibenwa** [comment]
Full story https://github.com/linagora/tmail-flutter/issues/1192

Closing as this is a duplicate
