### ISSUE TITLE
[Story] As a user, I can leave a  team-mailbox

### ISSUE THREAD

**Issue by dieptran88** [linagora/tmail-flutter#1104]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC

* TODO: {link}

## Definition

- Given that I am a Tmail user
- After log-in successfully, I can see the list of my team-mailbox list in left panel
- When I click on three-dot button of a tea-mailboxes, there will be a popup with options: Mark as read, Hide team-mailbox, Leave Team-mailbox
- When I select option Leave Team-mailbox , there will be a confirmation popup" You are about to leave this team-mailbox. After leaving, you are no longer a member of this team-mailbox. Are you sure?". If I choose Yes, the team-mailbox will be removed from the folder list and now I am no longer a member of this team-mailbox. 

[Back to Summary](#summary)

## Screenshots

![New Wireframe 1 copy (20).png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/19c2b902-d428-4380-849e-763b4fee4d7c)

[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

**Comment by dieptran88** [comment]
Design ticket:
https://ci.linagora.com/linagora/lgs/design/-/issues/311

**Comment by chibenwa** [comment]
I think i would prefer not to have this "manage my team mbxs" and rather have hide/show option for all mailboxes, not just for team mbx. Wdyt?

**Comment by hoangdat** [comment]
@chibenwa how to leave a team mailbox?

**Comment by chibenwa** [comment]
Not implemented yet on backend side.
