### ISSUE TITLE
[Story] As a user, I want to see the teammailboxes under my primary mailbox

### ISSUE THREAD

**Issue by dieptran88** [linagora/tmail-flutter#1105]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC

* TODO: {link}

## Definition
**UC1. View the list of my mailboxes under my primary mailbox**
- Given that I am a TMail user
- Given that I am added to a team-mailbox as a member
- When I log-in to my Tmail account, I can see list of team-mailboxes under my primary mailbox in the left panel
- I can expand/collapse the team-mailbox's name 
- Each team-mailbox includes 5 folders: Inbox. Drafts, Outbox, Sent , Trash

**UC2. Hide/Show team-mailbox**

- When administrator added me to a team-mailbox, the team-mailbox will be automatically displayed under my primary inbox 
- When I click three-dot button of the team-mailbox, I see option:"Hide"
- I select this option, there will be a confirmation message:"You are about to hide this mailbox, are you sure?". If I choose Yes, the mailbox will be hidden
- When I click on my avatar in top right, I select Manage account
- On Manage account screen, I select : "Team mailboxes"  on left menu, then I can see the list of my current team-mailboxes
- On each team-mailbox, there will be a toggle: 
   - If the toggle is switch-off, the mailbox is not shown under my primary mailbox
   - If the toggle is switch-on, the team-mailbox is being shown under my primary mailbox
- When I enable the toggle, there will be a message :" This team-mailbox will be shown under your primary mailbox". If I choose Yes, I am redirected to the thread-view and I can see that team-mailbox is displayed under my primary mailbox 
- When I disable the toggle, there will be a message:"This team-mailbox will be hidden from your primary mailbox". If I choose Yes, I am redirected to the thread-view and I can see that team-mailbox disappeared from my primary mailbox.

[Back to Summary](#summary)

## Screenshots

![New Wireframe 1 copy (4).png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/adf00a85-1b07-4078-9cbe-f2cb018def3d)

![New Wireframe 1 copy (3).png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/4ae9d6f3-7d7f-46ad-948b-7c7559aa529e)

[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

**Comment by chibenwa** [comment]
Why not do a single "team mailboxes" section with all team mailboxes below it?

**Comment by dieptran88** [comment]
Design ticket:
https://ci.linagora.com/linagora/lgs/design/-/issues/310

**Comment by hoangdat** [comment]
Hide/Show only TeamMailbox not the children of this team mailbox
