### ISSUE TITLE
[Search] Can not search 2 characters

### ISSUE THREAD

**Issue by haftus98** [linagora/tmail-flutter#1108]
**Descriptions**
I searched a word, Tmail returned the result list. I then erased the word to 2 letters, now the search returned nothing

**Video**

https://user-images.githubusercontent.com/97084773/197444418-a7b90dfa-089a-4cf8-83da-03965dbc74d3.mp4

**Comment by dab246** [comment]
It's strange that I can still search on my phone. @haftus98 Can you check more on other mail clients like `OpenPaas or ThunderBird` to see if it works?

**Comment by chibenwa** [comment]
We do NOT support partial matches on the mail address because it is technically very expensive to operate.

Closing...
