### ISSUE TITLE
[Story] As a user, I can copy and paste the link of email/mailbox in address bar

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#1114]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC

* TODO: {link}

## Definition

- Given that I am a Tmail user
- I logged-in successfully to Tmail web

**UC1. Copy and paste the link of an email**
- I opened an email and copy the email link 
- I paste the link of email in the address bar and click enter
- Then the system will validate:
   - If I have not logged in to the account, the log-in screen will be opened. 
   - If I have logged in to Tmail in a different account, then the system will display a Page not found screen with message: "The email that you requested could not be loaded."
   - If the email is not existing,  then the system will display a Page not found screen with message: "The email that you requested could not be loaded."
   - If I have logged in to correct account, the email content will be loaded.

**UC2. Copy and paste link of a folder**
- I copy the link of a folder (thread-view)
- I paste the link of the folder in address bar and click enter 
- Then the system will validate:
   - If I have not logged in to the account, the log-in screen will be opened. 
   - If I have logged in to Tmail in a different account, then the system will display a Page not found screen with a message: "You don't have permission to the mailbox that you requested."
   - If the folder is not existing, then the system will display a Page not found screen with message: "The folder that you requested could not be loaded."
   - If I have logged in to correct account, the folder will be loaded.

[Back to Summary](#summary)

## Design ticket
https://ci.linagora.com/linagora/lgs/design/-/issues/303

[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

```

**Comment by hoangdat** [comment]
@dieptran88 please help me to tailor the story and create design ticket also

**Comment by chibenwa** [comment]
Implemented
