### ISSUE TITLE
[View attachment] Click on the attachment, the file gets automatically downloaded and opened 

### ISSUE THREAD

**Issue by haftus98** [linagora/tmail-flutter#1125]
For now, when I click on an attachment, the attachment is automatically downloaded and opened by itself.

Expected: I should be able to see the file in advance before downloading the file

**Comment by chibenwa** [comment]
You mean "preview"?

**Comment by hoangdat** [comment]
can not get your point? @haftus98. What environment you are working (because each platform have separate UX)

**Comment by chibenwa** [comment]
Closing. Please open an attachment thumbnail ticket.

**Comment by chibenwa** [comment]
TMail backend epic: https://github.com/linagora/tmail-backend/issues/528

**Comment by chibenwa** [comment]
See https://github.com/linagora/tmail-flutter/issues/1198
