### ISSUE TITLE
[Story] As a user, I want to read message in my team-mailbox

### ISSUE THREAD

**Issue by dieptran88** [linagora/tmail-flutter#1127]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC

* TODO: {link}

## Definition

- Given that I am a TMail user and I am a member of team-mailbox A 
- When I logged-in to my account, I can see the team-mailbox A under the Team-mailbox list 
- I select team-mailbox A, the folders of that team-mailbox A is shown, including: Inbox, Drafts, outbox, Sent, Trash 
- In each mailbox, user can filter messages with attachments, star, unread as other mailbox 
- The actions  "Move message" and "Mark as spam" will be hidden in team-mailbox. 

- I open a message and read it and back to thread-view
- That message is marked as unread for all other members having access to this team-mailbox 

[Back to Summary](#summary)

## Screenshots

None

[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

**Comment by hoangdat** [comment]
which identity will be used to send Read receipt?

**Comment by hoangdat** [comment]
how about when move message from personal mailbox to team mailboxes?

**Comment by dieptran88** [comment]
Move message:
- inside team-mailbox
- from personal mailbox= >team-mailbox
- from team-mailbox => personal mailbox

**Comment by hoangdat** [comment]
- read email without send ReadRecipient: what problem when receive email with ReadRecipient?

- read email with and send ReadRecipient?

@ManhNTX please consider the story with identity for Team Mailbox first?

**Comment by ManhNTX** [comment]
@hoangdat yes i will skip working with this story and working with the story of identity for Team Mailbox first

**Comment by hoangdat** [comment]
for the case of read recipient: identity default of this team mailbox will be used

**Comment by chibenwa** [comment]
Is this done?

**Comment by hoangdat** [comment]
Moved to QA column

**Comment by QuangHoang1210** [comment]
@hoangdat
