### ISSUE TITLE
[Story] As a user, I want to delete the message in my team-mailbox

### ISSUE THREAD

**Issue by dieptran88** [linagora/tmail-flutter#1129]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC

* TODO: {link}

## Definition

- Given that I am a TMail user and I am a member of team-mailbox A 
- When I logged-in to my account, I can see the team-mailbox A under the Team-mailbox list 
- I select team-mailbox A, the folders of that team-mailbox A is shown
- I can delete messages by:
   - Selecting it in the list, click on three dots button, select Delete and confirm deletion
   - Click on the mail, click on three dots button, select Delete and confirm deletion
-  Then the message is moved to Trash folder and  other members having access to team-mailbox A will see the message being in Trash folder as well.

[Back to Summary](#summary)

## Screenshots

None

[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

**Comment by chibenwa** [comment]
Moved to QA column

**Comment by Arsnael** [comment]
Status on this? I can delete a message on a team mailbox but the it appears in my personal trash. Note that we need to show the trash first in tmail though, cf https://github.com/linagora/tmail-flutter/issues/1769

**Comment by QuangHoang1210** [comment]
@hoangdat
