### ISSUE TITLE
[Story] As a user, I want to send a message by team-mailbox

### ISSUE THREAD

**Issue by dieptran88** [linagora/tmail-flutter#1130]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC

* TODO: {link}

## Definition

**UC1. Send a new message**

- Given that I am a TMail user and I am a member of team-mailbox A
- After log-in successfully, I click button Create new message
- Then the composer will be opened
- When I click to field "From", a drop-down list will be shown my list of identity and my team-mailboxes list 
- I can select an email address from team mailbox list 
- Finish typing message and then choose Send.
- The recipients will see the team-mailbox address as the sender in the message.

**UC2 Reply to the message**
- Given that I am a TMail user and I am a member of team-mailbox A
- I open an email and click button Repply
- The composer will be opened with the quoted message
-The "From" field will be filled with team-mailbox A email by default
- I can click on the field to select another identity and continue 

**UC3. Forward a message**

- Given that I am a TMail user and I am a member of team-mailbox A
- I open an email and click button Forward
- The composer will be opened with the quoted message
-The "From" field will be filled with team-mailbox A email by default
- I can click on the field to select another identity and continue 

[Back to Summary](#summary)

## Screenshots

![New Wireframe 1 copy (6).png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/49a257f6-7f3a-406c-a1b6-2f6ad3969658)

## Design ticket

https://ci.linagora.com/linagora/lgs/design/-/issues/316

[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

**Comment by chibenwa** [comment]
Why separate team mbx from regular identities?

**Comment by dieptran88** [comment]
Just to categorize between my own identities and teams.

**Comment by chibenwa** [comment]
Moved to QA column

**Comment by Arsnael** [comment]
Issue detected on this: when I send a message with the team mailbox identity, I expect a copy of the message to be present in the Sent folder of the team mailbox. However, as of today, it gets saved to my own personal Sent folder

**Comment by chibenwa** [comment]
Is this because the Outbox folder is missing?
Shouldn't on a well provisionned team mailbox this work better?

**Comment by QuangHoang1210** [comment]
@hoangdat
