### ISSUE TITLE
[Android] Study signal crash related to rendering of android

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#1133]
<img width="562" alt="image" src="https://user-images.githubusercontent.com/6462404/198927637-10634df2-ab64-4177-a676-5392e99c4486.png">

**Comment by dab246** [comment]
2 HD

**Comment by hoangdat** [comment]
https://github.com/flutter/flutter/issues/113183?fbclid=IwAR2iTtzC4dqRS-wMy8xl-2FKGHTHvfdgG17G4HLggOMv5WZrCMDkZ1lFBuM

**Comment by dab246** [comment]
1 HD

**Comment by hoangdat** [comment]
https://github.com/flutter/flutter/issues/113183?fbclid=IwAR0aSbZCqHU70-SRJgybnkqpGVQuhZuhPh9d_bj_aj0G-gW0FqLuUraCj1A#issuecomment-1302886673

Follow up the update from this ticket

**Comment by hoangdat** [comment]
no more crash log in store.
