### ISSUE TITLE
Display mailbox counter for Spam mailbox

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#1141]
Why: as a user I want to be able to know I did receive some mails categorized as Spam

Mailbox counters is a way to know this.

![Screenshot from 2022-11-02 09-41-18](https://user-images.githubusercontent.com/6928740/199383118-c7eec456-c4dd-4957-9bc9-b786aa905051.png)

**Comment by haftus98** [comment]
![image.png](https://images.zenhubusercontent.com/632aca085051fb7959dab94b/9ac55122-915f-4031-a0f2-84c93fcc8eb4)

v0.4.3 no counter showed

**Comment by hoangdat** [comment]
You read all the emails in Spam, so no counter :)
