### ISSUE TITLE
[Open mail] It takes time loading the email content

### ISSUE THREAD

**Issue by haftus98** [linagora/tmail-flutter#1145]
**Description**
When I open any mail, the screen shows loading state for about 2-5 secs then email content shows up.

**Expected**
Email content should be showed right after I open the mail

https://user-images.githubusercontent.com/97084773/199432158-6c32487c-3bf4-48d6-b923-aee592dbb3ce.mp4

**Comment by chibenwa** [comment]
Is this due to the network of the the flutter rendering?

**Comment by hoangdat** [comment]
yes, and I measured long long time ago, fetching take nearly 2000ms (my network).

**Comment by chibenwa** [comment]
-> In VN querying France a typical roundtip takes 250 ms just with latencies

The first request once in a while might get slower:

-> Establishing TCP connection requires 1 roundtrip
-> Then establishing SSH termination requires 2 rountrips

Not happen always though.

Then there is the OPTION check for cross site, which take 1 rountrip.

Then there is the actual JMAP call. Small mails take 400ms roundtrip included. Very acceptable. Emails with big attachments apparently takes longer...
