### ISSUE TITLE
Rework Destination picker screen

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#1146]
### Description

Following https://github.com/linagora/tmail-flutter/issues/899

The standard flow in mailbox destination picker requires two clicks:

 - 1. Select the folder
 - 2. Done
 
This is very annoying. At first I thought there was a bug and thought the destination picker was broken.

Because of https://github.com/linagora/tmail-flutter/issues/899 we added the + button just to create a mailbox and we mix the flow on mailbox creation, and destination picking. Thus mailking destination picking more complex.

Other problem: the current UX do not allow to create a mailbo without parent (at least I could not figure out how to do so in less than 10 seconds).

### Expected result

1 click to move emails without folder creation.

### Proposal

Stick to the original design:

 - Remove `Done`. As soon as I select a mailbox the mails are moved to it.
 
![68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3566653035316661386432633736346463333061643133622f63633664396334312d353761622d343039372d396665382d666432383736646362656266](https://user-images.githubusercontent.com/6928740/199436070-50f3834f-634d-4cec-aea5-a47f44c24a50.png)

If I click the `+` then the mailbox creation dialog opens. Including name and base mailbox, similar to mailbox creation in the mailbox panel.

![Screenshot from 2022-11-02 15-19-19](https://user-images.githubusercontent.com/6928740/199436393-160bbb97-2a8a-43d9-8072-9dba18f9d38d.png)

Once the mailbox is created I think we can automatically select it as a move destination

### General remark

Don't make 0.01% of the use cases make the UX more complex for 99.99% of the use cases.

**Comment by hoangdat** [comment]
How about remove the `+` button in destination pciker also?

**Comment by chibenwa** [comment]
> How about remove the + button in destination pciker also?

Fine with me too.
