### ISSUE TITLE
[Bug] Identity/get is invoked when opening email

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#1147]
### DoD:
- remove unnecessary request

**Comment by hoangdat** [comment]
`Identity/get` is invoked because to handle `send Receipt`.

@chibenwa what identity should be used to send Receipt?  Default is ok?

**Comment by chibenwa** [comment]
Why do we need to call `send Receipt` when opening an email?

**Comment by hoangdat** [comment]
send `Read` when open email with MDN? we dont need it?

**Comment by chibenwa** [comment]
The one matching the To field the email is received on, if any. Otherwise defaut.

And please do identity/get only when you need to send a read receipt, not all the time.

**Comment by chibenwa** [comment]
When you open a mail you do not need to identity/get that's 1000% sure.

**Comment by hoangdat** [comment]
> what identity should be used to send Receipt? Default is ok?

How about that?

**Comment by chibenwa** [comment]
> How about that?

The one matching the To field the email is received on, if any. Otherwise defaut.

**Comment by hoangdat** [comment]
please handle it with #1321
