### ISSUE TITLE
[Move mail] Didn't work on web while in advance search

### ISSUE THREAD

**Issue by haftus98** [linagora/tmail-flutter#1151]
**Description**
While I'm in advance search, "move to" function doesn't work

**Reproduce**
1. Search with advance search
2. Click button Move to from one of the  searched mails

**Video**
[Untitled_ Nov 03,2022 11_11 AM.webm](https://user-images.githubusercontent.com/97084773/199646632-352d8d88-69af-458e-90bb-756cbae4e657.webm)

Production / GG chrome / v0.3.20

**Comment by chibenwa** [comment]
Environment, version, etc...

**Comment by chibenwa** [comment]
Steps to reproduce

**Comment by sherlockvn** [comment]
It have been fixed

**Comment by hoangdat** [comment]
1HD
