### ISSUE TITLE
[COMPOSER] Better manage initial cursor position

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#1152]
### Description

When I open the composer, replay / reply all / forward a mail, then the cursor is never initialy positioned.

### Expected result

The cursor should be positionned on the first empty field, in order `To`, `Subject`, `Body`

### Current behavior

https://user-images.githubusercontent.com/6928740/199646878-61bf35a3-3211-46b0-86a3-4555f1d7ebed.mp4

**Comment by dab246** [comment]
Same issue #1153
