### ISSUE TITLE
[COMPOSER] Improve recipient input

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#1153]
### Description

Recipient validation in email composer is annoying, we can smooth the user experience on it.

The ultimate confusion for a user is to be prompted "no recipient error" when I actually typed something...

### Expected result

https://user-images.githubusercontent.com/6928740/199647522-39caa13e-412e-4fc1-a57a-fad30fe57a21.mp4

Upon sending, draft, or focus switch the current input for recipient is implicitly validated...

### Current behavior

https://user-images.githubusercontent.com/6928740/199647326-a9a5d51c-aa5a-498c-ad54-c30f8864b82e.mp4

**Comment by QuangHoang1210** [comment]
This one is not passed. I re-opened it, please following this ticket: https://github.com/linagora/tmail-flutter/issues/1479
