### ISSUE TITLE
Sending read receipts when requested fails

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#1157]
### Description

When I lick "yes, send the read receipt" it fails...

![Screenshot from 2022-11-03 14-47-40](https://user-images.githubusercontent.com/6928740/199669829-a16b7e91-66a6-4b4d-8c1f-2a5767da1034.png)

Though MDN caps is in the account capabilities...

![Screenshot from 2022-11-03 14-50-11](https://user-images.githubusercontent.com/6928740/199670080-d06def9a-88ae-4021-8376-ccc507fffdef.png)

Can you check @hoangdat ?

**Comment by hoangdat** [comment]
1HD
