### ISSUE TITLE
[Story] As a user, I want to see team-mailbox identities in my identities  

### ISSUE THREAD

**Issue by dieptran88** [linagora/tmail-flutter#1163]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC

* TODO: {link}

## Definition
**UC1. Add  team-mailbox as my identity**
- Given that I am a TMail user and I am a member of team-mailbox A
- When I logged-in to my account, I select Manage account => Identities tab
- On the identities list, When I am added to a team-mailbox, the team-mailbox is also added automatically to my identities list
- When I click on one team-mailbox identity, I can see information:
   - Name: is the team-mailbox name
   - Email: Is the email address of the team-mailbox
   - Reply to: the email address of the team-mailbox
   - Edit:  If the team-mailbox identity is added automatically by the system, I can only edit the field "Name", "Signature"
   - Delete:  If the team-mailbox identity is added automatically by the system, I cannot edit or delete it manually 

**UC2. Add/Edit new identity with team-mailbox email**
- Given that I am a TMail user and I am a member of team-mailbox A
- When I logged-in to my account, I select Manage account => Identities tab
- I click button Create new identity, a new screen will be opened 
- On the field "Email"/"Reply to","BCC", when I click on it, the drop-down list will contains all my emails and team-mailboxes that I am currently a member of
- I can select a team-mailbox and continue inputting to create a new identity 
- I can also edit the identity using team-mailbox.

**UC3. Remove team-mailbox identity**
- Given that I am a TMail user and I am a member of team-mailbox A
- For team-mailbox identity created by me: I can remove as other identity by clicking on Delete button 
- For team-mailbox identity automatically created by system: 
   - I open Team-mailboxes tab and click button Remove team-mailbox A
   - After confirm deletion, the team-mailbox a is removed successfully 
   - All the identities of that team-mailbox is also removed accordingly 

[Back to Summary](#summary)

## Screenshots

None

[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

**Comment by dieptran88** [comment]
I have some concerns related to this identity of team-mailbox:
1. When I am added to a team-mailbox, then the team-mailbox is also added to my identity automatically => can I delete this team-mailbox identity? If Yes, then when I compose an email, can I still select it in field "From"? 
2. When I create a identity, if I select a team-mailbox to the field "email" then select my personal email in the field  "Reply to", then when a person reply to that team-mailbox email, it will go to my Inbox and other members of team-mailbox will not see the replied email => should we hide this field for team-mailbox identity ?
Same with case "Bcc"

**Comment by dieptran88** [comment]
@chibenwa  @hoangdat Please help me to review

**Comment by chibenwa** [comment]
On the headline what the backend team delivered is exactly the same thing than "aliases"

 => You can create, update delete identities based on the address of the team mailbox.

**Comment by chibenwa** [comment]
We could create you a default identity per team mailboxes upon adding you to the team mailbox if needed.

The user can delete this identity, can create another if he wants, etc...

Nothing complex.

**Comment by dab246** [comment]
- How to distinguish the identity of `Personal` and the identity of `Team Mailboxes`?
- Do we need any more attributes call api `Identity/get`
```json
{
     "using": [
         "urn:ietf:params:jmap:core",
         "urn:ietf:params:jmap:submission"
     ],
     "methodCalls": [
         [
             "Identity/get",
             {
                 "accountId": "{{accountId}}"
             },
             "c0"
         ]
     ]
}
```

**Comment by QuangHoang1210** [comment]
@hoangdat

**Comment by chibenwa** [comment]
To be honnest I feel unsure that we need to "automatically add team mailbox identity"...

I fear that if someone gets many team mailboxes then having too many identities would become a mess...

For now let's wait for now?

**Comment by hoangdat** [comment]
> I fear that if someone gets many team mailboxes then having too many identities would become a mess...

agree, not implemented.
