### ISSUE TITLE
[Web] Improve more button in recipients of EmailView

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#1167]
<img width="866" alt="Screen Shot 2022-11-07 at 11 42 28" src="https://user-images.githubusercontent.com/6462404/200228460-1e5d3a5f-3a0b-4e2c-8de6-ea3524467156.png">

**Comment by chibenwa** [comment]
Please describe how you plan to improve it, for each device.

As of today I belive we likely could remove this button.
