### ISSUE TITLE
Apply new logo with official brand name Team Mail

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#1169]
# Summary

https://ci.linagora.com/linagora/lgs/design/-/issues/297 introduced SVG logos for Team-Mail using linear gradient.

I suggest the mobile team to switch to it.

### DoD:
- [ ] new logo 
- [ ] new brand name in all screens, platforms
- [ ] new store kit
- [ ] ReadMe

**Comment by chibenwa** [comment]
![20221114_TeamMail_Potrait_logo_white_text_](https://user-images.githubusercontent.com/6928740/201572421-a123bb07-8de7-46b9-aa15-650544414d1d.svg)

![20221114_TeamMail_Potrait_logo](https://user-images.githubusercontent.com/6928740/201572425-86a18f7c-2651-404a-a3b1-d331ce93a978.svg)

![20221114_TeamMail_Landscape_logo_white_text_](https://user-images.githubusercontent.com/6928740/201572427-ed1e22d9-f6e7-4452-9198-103d219e7ba5.svg)

![20221114_TeamMail_Landscape_logo](https://user-images.githubusercontent.com/6928740/201572431-6f37c966-10ae-4123-9bb9-97a21dee9fe6.svg)

**Comment by hoangdat** [comment]
2HD

**Comment by hoangdat** [comment]
1HD

**Comment by hoangdat** [comment]
2HD

**Comment by dab246** [comment]
1 HD
