### ISSUE TITLE
[Story] As an user, I want to log-out of the app 

### ISSUE THREAD

**Issue by dieptran88** [linagora/tmail-flutter#117]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC

* TODO: {link}

## Definition

- Given that I am a Tmail user and I logged-in to the app
- I touch on the hamburger icon and the side panel will be opened
- I touch on my email on the top of the panel 
- The setting screen will be opened 
- I click on the log-out button, then i am logged-out of the app.

[Back to Summary](#summary)

### Mobile
![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/cef97a48-843e-43d8-aa1c-5c68434d9700) ![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/9ac6eff3-67d2-44d4-ae7f-82398cccf420)
![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/6353bed8-0e5b-478e-986e-df5377b8130d)

### Tab
![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/08a8d0a7-d39e-4be4-bdd9-9e93f32484ca)
![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/f5223670-7e32-4949-83e5-1f766cc22559)
![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/3824f8e8-da31-4178-b4ba-c0e9ee0f10a6)

[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

**Comment by hoangdat** [comment]
why you close this @dieptran88 , it is very cool.

**Comment by dieptran88** [comment]
It is duplicated with #118 , i made a mistake :))

**Comment by hoangdat** [comment]
> It is duplicated with #118 , i made a mistake :))

Ok please add the comment for not misleading when closing sth
