### ISSUE TITLE
[Delete mail button inside a mail] There should be a confirm message when deleting mail 

### ISSUE THREAD

**Issue by haftus98** [linagora/tmail-flutter#1178]
**Description**
For now when I open a mail then click delete, there is no confirmation message and I just get directed to mailbox screen.

**Video**

https://user-images.githubusercontent.com/97084773/200629042-73792e04-940b-429f-99cb-5de68be710f3.mp4

**Expected:**
"Are you sure to delete this mail? Deleted mail will be in Trash box."

**Comment by chibenwa** [comment]
Moving to trash is easy to undo.

When deleting a mail permanently there is a confrmation dialog.
