### ISSUE TITLE
[Search mail] Returned mail number is not correct

### ISSUE THREAD

**Issue by haftus98** [linagora/tmail-flutter#1179]
**Reproduce**
1. As in video, I searched Dat to load all the mail from Dat( the last one is May 27th)
2. I selected all time, now it returned only 1 mail which is May 27th
3.  I selected last year, it still returned only 1 mail which is May 27th

**Video**

https://user-images.githubusercontent.com/97084773/200631408-2287c0ef-1fa9-4563-aeea-a91b257bbb50.mp4

**Environment**
IOS, v0.3.20

**Comment by dab246** [comment]
1 HD

**Comment by hoangdat** [comment]
1HD
