### ISSUE TITLE
[Story] As an user, I want to log-out the app

### ISSUE THREAD

**Issue by dieptran88** [linagora/tmail-flutter#118]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC

* TODO: {link}

## Definition

- Given that I am Tmail user and I already logged-in 
- I touch the hamburger icon on top of screen, the side panel will be opened
- I touch my email on the top of the panel, the settings screen will be opened
- On this new screen, I can see some settings (to be defined later) and and a Log-out button 
- I touch the Log-out button, then i am logged-out of the app

[Back to Summary](#summary)

### Mobile
![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/e63db545-2ab5-4069-956d-62317288c24c) ![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/aa08b971-6e82-4bb6-9d48-4b0fec111225)
![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/b5489b37-5823-46ea-9b64-7b3ec54a6b6f)
### Tab
![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/114a12a9-6d16-44ac-b065-eb1da118284a)
![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/992d91b8-6058-46e7-9672-c12ed5c7f9fd)
![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/0097a692-e220-4941-9b23-c6398a2d17ac)

[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

**Comment by chibenwa** [comment]
I agree with the visuals.

I do think today we can just have the logout button, and add the other later

(I do not like buttons without actions...)
