### ISSUE TITLE
[Story] As a user, I want to search mailboxes including hidden mailboxes  in the left panel

### ISSUE THREAD

**Issue by dieptran88** [linagora/tmail-flutter#1187]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC

* TODO: {link}

## Definition

- Given that I am a Tmail user and I logged-in successfully 
- On the left panel, I can see the list of mailboxes, including team-mailboxes 
- When I click Search Mailbox, the search screen will be displayed
- I type in the field and system will looking in all of my mailboxes/folders
- The result will be displayed be low search field
- If I click one mailbox in result, it will be selected and displayed with its INBOX in thread-view 
- If a matched mailbox is currently hidden, it will appear in the search result, and when I click on this mailbox, it will not be hidden anymore and shown in the mailbox list in left panel 
- In the result screen, the hidden mailbox is differentiated with shown mailbox in someway: 
ex: Blue/grey folder icon or opened/closed eye icon 

[Back to Summary](#summary)

## Screenshots

![New Wireframe 1 copy (10).png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/683dead1-1a5d-40ff-8578-e82e985328e6)

## Design ticket
https://ci.linagora.com/linagora/lgs/design/-/issues/315
[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

**Comment by chibenwa** [comment]
I think if it is hidden, it is hidden and won;'t be shown here.

Let's keep the use case simple for now.

**Comment by chibenwa** [comment]
=> I think we need a story on "hidding folders"

=> We could reuse this "hidding folders" for team mailboxes

**Comment by chibenwa** [comment]
![Screenshot from 2023-04-05 10-27-32](https://user-images.githubusercontent.com/6928740/229973904-f9d01cdb-51ec-4c55-a17d-cbe21c43602f.png)

Implemented
