### ISSUE TITLE
[Delete trash mail] Empty trash when there is no mail 

### ISSUE THREAD

**Issue by haftus98** [linagora/tmail-flutter#1188]
**Description**
Delete trash when there is no trash mail makes the text "no emails in this mailbox" gone.

**Video**
[Untitled_ Nov 10,2022 10_29 AM.webm](https://user-images.githubusercontent.com/97084773/200994621-88f120c5-d0c8-4b3c-bf17-7255bd56422e.webm)

**Environment**
gg chrome / v0.4.1

**Comment by dab246** [comment]
This issue has been fixed in previous PRs.

**Comment by chibenwa** [comment]
@QuangHoang1210 ?
