### ISSUE TITLE
[Outbox] Outbox doesn't count unread mail

### ISSUE THREAD

**Issue by haftus98** [linagora/tmail-flutter#1189]
**Description**
Outbox doesn't count unread mail

**Image**
![image](https://user-images.githubusercontent.com/97084773/200998899-b2a7e5a5-5e26-4699-bc16-9953d0e51e45.png)

**Environment**
google chrome / v0.4.1

**Comment by hoangdat** [comment]
<img width="585" alt="image" src="https://user-images.githubusercontent.com/6462404/201067521-fa606b62-21c9-4dbc-ae81-28a7107fec03.png">

It works well on my site. How about `refresh` app? @haftus98

**Comment by haftus98** [comment]
It works now
