### ISSUE TITLE
[Story] As a user, I want to filter messages : Unread 

### ISSUE THREAD

**Issue by dieptran88** [linagora/tmail-flutter#119]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Definition

- Given that I am Tmail app user and I have logged-in the app
- On thread-view, I can see icon "Filter" on the top right of the screen 
- I touch this icon, a dialog will be displayed 
- I can see the list of filter criteria including: Attachments, Unread, Star 
- I select option Unread, then the dialog disappears
- Now on the thread-view, system will display unread emails list of current mailbox 
- On the top right of screen, the filter icon is replaced by selected filter criteria "Unread"
- When I click on this filter criteria, it will be removed and the filter icon is displayed 
- Now the thread-view displays all emails.

[Back to Summary](#summary)

### Mobile
![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/80853e91-624d-468a-a6e0-1937678eafde)  ![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/b9cb28b1-fcb5-4e6d-a662-ff8c17a829e7)

![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/33126faa-686e-447d-852f-1944bc07f9b3)

### Tab

![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/ff517321-90e0-48c7-ac34-8f0e15f2e0b6)

![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/6557d7ea-9e8f-4797-a774-adfe56a7d91b)

![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/d034db25-40ac-4615-bd3a-d4b9c0478a4c)

### Design ticket

https://ci.linagora.com/linagora/lgs/design/-/issues/91

[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

**Comment by dieptran88** [comment]
@hoangdat

**Comment by hoangdat** [comment]
thanks @dieptran88, ship it!

**Comment by dieptran88** [comment]
Design ticket: https://ci.linagora.com/linagora/lgs/design/-/issues/90

**Comment by hoangdat** [comment]
> Design ticket: https://ci.linagora.com/linagora/lgs/design/-/issues/90

maybe you are wrong @dieptran88, it is related to `search`

**Comment by dieptran88** [comment]
My mistake, here it is https://ci.linagora.com/linagora/lgs/design/-/issues/91
