### ISSUE TITLE
Apply new Identity Design

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#1194]
Design: https://www.figma.com/file/rRVxJpCu1G22D0jqyvK7I9/TeamMail?node-id=6846%3A293128&t=DG2bdvxxI6sxMb9O-4

### New:
- Can be set default for identity

**Comment by hoangdat** [comment]
@chibenwa please let me know how to work with default identity? docs or contracts?

**Comment by chibenwa** [comment]
default identity: use the `sortOrder` property with a low value. Eg 10.
