### ISSUE TITLE
[Advanced search] Auto add my mail to search bar after searching

### ISSUE THREAD

**Issue by haftus98** [linagora/tmail-flutter#1199]
**Description**
I searched with Search advance / From field, then I reopened the search advance, my mail was auto added to the From field.

**Reproduce**
Step 1: Search st with Search advance/ from field
Step 2: Reopen the Search advance

**Video**
[Untitled_ Nov 11,2022 5_23 PM.webm](https://user-images.githubusercontent.com/97084773/201570622-90d63e2f-b332-41f6-a003-95f48adacaaa.webm)

**Environment**
gg chrome, v0.4.1

**Comment by dab246** [comment]
@haftus98 
1. I tried following the steps you did, but still can't reproduce this error.
2. I found out before you did an advanced search from the `from` field with the name `Linh`. At the `dashboard` screen you performed certain searches. I see email lists labeled `mailbox` differently so I guess so. Can you tell me what you did before doing the above steps to reproduce the error?
![Screenshot 2022-11-17 at 13.06.11.png](https://images.zenhubusercontent.com/605059df174a357c7888640f/6c040b7f-27b2-46d5-a711-cad7919d2054)

**Comment by hoangdat** [comment]
@haftus98 please response us

**Comment by haftus98** [comment]
I just checked and it's ok now @dab246
