### ISSUE TITLE
[CC/BCC] sent mails don't show the CC/BCC info

### ISSUE THREAD

**Issue by haftus98** [linagora/tmail-flutter#1200]
**Description**
I sent mail with CC or Bcc info then I viewed those mails. CC or Bcc info is not displayed. I clicked reply all, the cc and bcc is still visible.
Only happen when CC or Bcc only

**Reproduce**
1. Send mail with cc info or bcc info
2. view the sent mails

**Environment**
v0.4.1

**Comment by hoangdat** [comment]
evident

**Comment by chibenwa** [comment]
Are people mentionned in `Cc` or `Bcc`receiving the email at all?

Acceptance criteria:

```
Given I send a mail `To: Alice, Cc: Bob`
Then Alice recieves the mail, and sees `To: Alice, Cc: Bob`
Then Bob Receives the mail, and sees `To: Alice, Cc: Bob`
Then the email is stored on ALice `Sent` mailbox with `To: Alice, Cc: Bob`


Given I send a mail `To: Alice, Bcc: Bob`
Then Alice recieves the mail, and sees `To: Alice`
Then Bob Receives the mail, and sees `To: Alice`
Then the email is stored on ALice `Sent` mailbox with `To: Alice, Bcc: Bob`
(Stripping `Bcc` headers is done automatically by James when sending an email)
```

**Comment by chibenwa** [comment]
Please @hoangdat plan this on the next sprint.

**Comment by hoangdat** [comment]
1HD
