### ISSUE TITLE
Right click to open mailbox in a new TAB

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#1201]
# Summary

https://user-images.githubusercontent.com/6928740/201577935-ee8927d9-4de9-40df-b811-544b35b17633.mp4

**Comment by dab246** [comment]
@chibenwa  Do we support `right mouse click` in mailbox search mode?

**Comment by chibenwa** [comment]
IMO yes, I think so.

**Comment by hoangdat** [comment]
Every where we have context menu actions for mailbox, we should support it (except mobile/tablet)

**Comment by chibenwa** [comment]
Done?

**Comment by dab246** [comment]
@chibenwa  
- We now support opening `Open new tab` with app's `context menu` for each mailbox.
- If you want us to add support for the browser's `right mouse click` feature to open the `context menu` then please reopen this issue so we can implement it.

<img width="127" alt="Screenshot 2023-03-06 at 18 00 58" src="https://user-images.githubusercontent.com/80730648/223092450-c420f3b2-aac2-431d-8916-d997aa3f3599.png">

**Comment by dab246** [comment]
`Right mouse click` is not supported due to browser web view issue. #1634
