### ISSUE TITLE
[Story] As a user, I want to move messages in team-mailbox

### ISSUE THREAD

**Issue by dieptran88** [linagora/tmail-flutter#1209]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC

* TODO: {link}

## Definition

- Given that I am a Tmail user and I have logged-in successfully

**UC1. Move message inside the team-mailbox**
- I can move a message inside a team-mailbox in 2 ways:
1. On thread-view, I can select email and choose option Move or in mail content view, I click Move button, then there will be a pick destination screen:
- I  choose one of the mailboxes: Inbox, Draft, Outbox, Sent, Trash as destination 
- The message is moved successfully and there is a toast notification message.
2. I can drag a message in the team-mailbox and drop it to one of the folders of team-mailbox in left panel

**UC2. Move message from team-mailbox to my primary mailbox**
- When I drag one message from my team-mailbox then drop it to one folder in my primary mailbox, it is moved from team-mailbox to my mailbox.
- After moving successfully, there will be a notification message
- Now other members of the team-mailbox will not be able to see that message in team-mailbox. 

**UC3. Move message from my mailbox to team-mailbox**
- When I drag one message from my mailbox then drop it to one folder of a team-mailbox in the left menu, it is moved from my mailbox to that team-mailbox 
- After moving successfully, there will be a notification message
- Now other members of the team-mailbox can see that message in team-mailbox. 

[Back to Summary](#summary)

## Screenshots

None

[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

**Comment by dieptran88** [comment]
Possible improvement:
- When moving message from team-mailbox to my mailbox, it create a copy of that message to my mailbox and that message is still in the original team-mailbox

**Comment by hoangdat** [comment]
pending

**Comment by dab246** [comment]
We should have a new design for this problem.

**Comment by hoangdat** [comment]
@dieptran88, what is the reason made us pause on this story?

**Comment by hoangdat** [comment]
@chibenwa what happen if one person in the team move a message in team mailbox to his personal mailbox or to other team?

**Comment by chibenwa** [comment]
> what happen if one person in the team move a message in team mailbox to his personal mailbox or to other team?

For now let's just move the mails. Over people won't see it.

If we get complains then we would think about it.

**Comment by QuangHoang1210** [comment]
@hoangdat

**Comment by hoangdat** [comment]
Conflict with #1127 in move email
