### ISSUE TITLE
docker version - tmail web - access error

### ISSUE THREAD

**Issue by aioun** [linagora/tmail-flutter#1212]
### Description
Hello,
Using docker version of tmail-web:master , if you go http://localhost:8080 you will be redirected to http://localhost:8080/auth. Then you will got nginx error 404 not found.  If now you execute docker exec -it web /bin/bash ( to access the container) , there is no auth folder in  /usr/share/nginx/html/ 
Could you fix this please. 
### Acceptance criteria

The list of acceptance criteria (defined in the corresponding User Story or coming from your functional knowledge of the product)
These acceptance criteria must be met by the corrective implementation done by the developers.

### Context

Devices, OS

### Additional information

frequency, log files,...

**Comment by tk-nguyen** [comment]
Can you add more information? How did you run the image?

**Comment by aioun** [comment]
I followed the instruction at: https://hub.docker.com/r/linagora/tmail-web 
The env.file contains: SERVER_URL=https://my-jmap-server.com 
Knowing that tmail backend running at my localhost.
Best,

**Comment by tk-nguyen** [comment]
Can you try renaming `SERVER_URL` to `TMAIL_WEB_SERVER_URL` in your `env.file`? Then recreate the `tmail-web` container.

**Comment by aioun** [comment]
Renaming the server_url with localhost works.

**Comment by aioun** [comment]
I still have some errors in the console:
[ERROR] AccountCacheManager::getSelectedAccount(): Bad state: No element
main.dart.js:71744 [ERROR] GetAuthenticatedAccountInteractor::execute(): Instance of 'NotFoundAuthenticatedAccountException'
main.dart.js:71744 [ERROR] HomeController::_handleFailureViewState(): NoAuthenticatedAccountFailure
main.dart.js:71744 OidcConfigurationCacheManager::deleteAuthorityOidc()
2main.dart.js:71744 HiveCacheConfig::getEncryptionKey(): encryptionKey: LIm2bgJXqI2uMivoyXuGlBq7aoFWHPSgN+HAjvGjPfY=

main.dart.js:71744 HomeController::_handleSuccessViewState(): CheckOIDCIsAvailableLoading
/.well-known/webfinger?resource=http://localhost&rel=http://openid.net/specs/connect/1.0/issuer:1          Failed to load resource: net::ERR_CONNECTION_REFUSED

main.dart.js:71744 AuthorizationInterceptors::onError(): DioError [DioErrorType.response]: XMLHttpRequest error.

main.dart.js:71744 [ERROR] HomeController::_handleFailureViewState(): CheckOIDCIsAvailableFailure
/.well-known/webfinger?resource=http://localhost&rel=http://openid.net/specs/connect/1.0/issuer:1          Failed to load resource: net::ERR_CONNECTION_REFUSED

main.dart.js:71744 AuthorizationInterceptors::onError(): DioError [DioErrorType.response]: XMLHttpRequest error.

**Comment by tk-nguyen** [comment]
You need to expose port 80 of `tmail-backend` container and (for testing only) disable CORS on your browser. Also you need to provision some users on `tmail-backend`, see here: https://github.com/linagora/tmail-backend/blob/master/tmail-backend/apps/memory/README.md#provisioning

**Comment by aioun** [comment]
Done, but still some errors bellow. Thanks
![image](https://user-images.githubusercontent.com/42891685/202461825-4054073a-f7ec-490f-96e7-44acece23773.png)

**Comment by hoangdat** [comment]
> I still have some errors in the console:
> 
> [ERROR] AccountCacheManager::getSelectedAccount(): Bad state: No element
> 
> main.dart.js:71744 [ERROR] GetAuthenticatedAccountInteractor::execute(): Instance of 'NotFoundAuthenticatedAccountException'
> 
> main.dart.js:71744 [ERROR] HomeController::_handleFailureViewState(): NoAuthenticatedAccountFailure
> 
> main.dart.js:71744 OidcConfigurationCacheManager::deleteAuthorityOidc()
> 
> 2main.dart.js:71744 HiveCacheConfig::getEncryptionKey(): encryptionKey: LIm2bgJXqI2uMivoyXuGlBq7aoFWHPSgN+HAjvGjPfY=
> 
> 
> 
> main.dart.js:71744 HomeController::_handleSuccessViewState(): CheckOIDCIsAvailableLoading
> 
> /.well-known/webfinger?resource=http://localhost&rel=http://openid.net/specs/connect/1.0/issuer:1          Failed to load resource: net::ERR_CONNECTION_REFUSED
> 
> 
> 
> main.dart.js:71744 AuthorizationInterceptors::onError(): DioError [DioErrorType.response]: XMLHttpRequest error.
> 
> 
> 
> main.dart.js:71744 [ERROR] HomeController::_handleFailureViewState(): CheckOIDCIsAvailableFailure
> 
> /.well-known/webfinger?resource=http://localhost&rel=http://openid.net/specs/connect/1.0/issuer:1          Failed to load resource: net::ERR_CONNECTION_REFUSED
> 
> 
> 
> main.dart.js:71744 AuthorizationInterceptors::onError(): DioError [DioErrorType.response]: XMLHttpRequest error.

No problem with this error, if we can not find OIDC configuration, we support login with basic auth

**Comment by aioun** [comment]
Thanks a lot. I tried to send an email from alice@localhost account to bob@localhost,  but it is not working. In fact if I add bob@localhost.com the email is accepted but it is not retrieved in bob inbox. 
Thank you for your help.

**Comment by hoangdat** [comment]
What did you find in the console?

**Comment by hoangdat** [comment]
@chibenwa can you help him on this trace? Thanks

**Comment by chibenwa** [comment]
The email is in bob@my-jmap-server.com INBOX.

Please be reminded this is in-memory: a restart resets the data.

**Comment by aioun** [comment]
OK, let me explain more, 
1) I login with alice@my-jmap-server.com
2) I write an email for bob@my-jmap-server.com, the email is sent 
3) I logout
4) I login with bob@my-jmap-server.com
5) the INBOX shows Inbox(1), but I can't read the email
Hope it is clear now!
