### ISSUE TITLE
Structure Message queue to handle FCM message

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#1217]
### Desc:
1. `FcmService`
  - handle callbacks from FCM.
  - `onBackgroundHandler`: how to bind `interactor`, `reposity`, `datasource`, `api`

2. Create `FcmController`: 
  - convert message from FCM to `StateChange`
  - broadcast stream messages
  - life cycle: [init] dashboard - [dispose] with app

3. `AbstractLisnter`
4. `MailChangeListener` singleton
  - listen stream from `FcmController` -> handle `stateChange` for Email
  - [FCM]newState - [Local]oldState -> /changes + /get 
5. `MailboxChangeListener` singleton
  - //new ticket

**Comment by dab246** [comment]
2 HD

**Comment by hoangdat** [comment]
2HD
