### ISSUE TITLE
[Story] As a user, I want to manage folder visibility  

### ISSUE THREAD

**Issue by dieptran88** [linagora/tmail-flutter#1218]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC

* TODO: {link}

## Definition
**UC1. Mange folder visibility**
- Given that I am a Tmail user
- After log-in successfully, I click on my avatar and select Manage account
- In Manage account screen, there is a new item on the left menu: Folder visibility
- When I click on this new item, the screen that listing all mailboxes, including my team-mailboxes will be displayed
- I can select the checkbox in each mailbox to show  and deselect the checkbox to hide that mailbox 
- I click Save button, then the folder visibility will be updated:
- The selected mailboxes will be displayed in mailbox list the left panel and the  unselected mailboxes will be hidden.
- Default option is to show all folders. 
- When a new folder is added or when I am added to a new team-mailbox, it is automatically shown and displayed in the left panel. 
- And when a folder is hidden, it will not be shown in Folder destination picker 
- When a folder is hidden, it is also hidden in Thunderbird Mail 

**UC2. Hide a mailbox in mailbox list** 
- Given that I am a Tmail user
- After log-in successfully, I can see the mailbox list in left panel
- When I click on three-dot button of a mailbox, there will be an options popup 
- I can see a new option "Hide mailbox". This option is available for my created mailboxes and team-mailbox 
- "Hide mailbox' option is not available for system folders including: INBOX, Drafts, Outbox, Sent, Trash, Spam, Templates
-  When I select this option,  the mailbox will be hidden 
- There will be a toast notification message with button Undo, when I click this button, the mailbox is shown again

[Back to Summary](#summary)

## Screenshots

![New Wireframe 1 copy (21).png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/29a54489-c392-41da-b0a5-b6b4b5ca7aa7)

![New Wireframe 1 copy (22).png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/af1e9650-ec84-4d7a-a3f6-87d6dfc3cc34)

[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

**Comment by chibenwa** [comment]
Subscriptions is a technical term.

I suggest in the UI to instead speak of `hide`, `show` and `visibility`.

Also we need a `hide` folder action in the mailbox list.

**Comment by hoangdat** [comment]
@dieptran88  please update it in design board

**Comment by hoangdat** [comment]
How about if we have no team-mailboxes?

**Comment by chibenwa** [comment]
We can still introduce the hide action and the folder visibility panel.
