### ISSUE TITLE
[Share file] can not share application

### ISSUE THREAD

**Issue by haftus98** [linagora/tmail-flutter#1221]
**Description**
For now, when I want to share application to Tmail with the share function on mobile, it returns nothing when selecting Tmail

**Reproduce**
Step 1: Select app, select share app
Step 2: select share with Tmail

**Video**

https://user-images.githubusercontent.com/97084773/202908260-51983d93-2b2c-48f6-ae6e-91797ee53b26.mp4

**Comment by hoangdat** [comment]
not priority

**Comment by QuangHoang1210** [comment]
### Reproduce Step:
1, User tap and hold on application
2, User select share button
3, User select the direction application where he want to share

### Actual:
IOS: /app/id454638411 -- incorrect link from appstore
Android: System repsonse an error message that cannot attach cause size of file is more than 19mb.

### Expected:
IOS: [APPLE STORE](https://apps.apple.com/app/id454638411)
Android: [CHPLAY STORE](https://play.google.com/store/apps/details?id=com.facebook.orca&hl=vi&gl=US&pli=1)

### Video Reproduce:
https://user-images.githubusercontent.com/124866146/231626426-88a80f4e-8af5-4783-97b6-d9cd4897a665.mp4

### Gmail Sample:
![image](https://user-images.githubusercontent.com/124866146/231627014-54b3e50d-67f0-49c0-9fb9-362704846ca8.png)

**Comment by hoangdat** [comment]
close for short term
