### ISSUE TITLE
[Add mail to composer] auto line break when mail address is too long

### ISSUE THREAD

**Issue by haftus98** [linagora/tmail-flutter#1222]
**Description**
It would be nice if there is line break when I input long mail

**Reproduce**
Input several mails, then input a long mail

**Video**
[Untitled_ Nov 21,2022 10_09 AM.webm](https://user-images.githubusercontent.com/97084773/202955064-9c86ac9a-621c-4f80-9ada-8aa6555ed5e5.webm)

**Comment by hoangdat** [comment]
Designer: not add line break to email content if it is not contained. But the editor should fit the content

**Comment by hoangdat** [comment]
Need improvement:
When typing, if typing text is longer than the remaining room please go to next line in `to`
