### ISSUE TITLE
Build from source error: TextButton, ElevatedButton

### ISSUE THREAD

**Issue by aioun** [linagora/tmail-flutter#1224]
Flutter 3.3.8 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 52b3dc25f6 (il y a 12 jours) • 2022-11-09 12:09:26 +0800
Engine • revision 857bd6b74c
Tools • Dart 2.18.4 • DevTools 2.15.0

Target dart2js failed: Exception: Warning: The 'dart2js' entrypoint script is deprecated, please use 'dart compile js' instead.
../../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_platform_widgets-1.20.0/lib/flutter_platform_widge
ts.dart:27:1:
Error: 'MaterialElevatedButtonData' is exported from both 'package:flutter_platform_widgets/src/platform_button.dart' and
'package:flutter_platform_widgets/src/platform_elevated_button.dart'.
export 'src/platform_elevated_button.dart';
^
../../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_platform_widgets-1.20.0/lib/flutter_platform_widge
ts.dart:40:1:
Error: 'MaterialTextButtonData' is exported from both 'package:flutter_platform_widgets/src/platform_button.dart' and
'package:flutter_platform_widgets/src/platform_text_button.dart'.
export 'src/platform_text_button.dart';
^
../../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_platform_widgets-1.20.0/lib/src/platform_button.da
rt:273:9:
Error: No named parameter with the name 'color'.
        color: dataFlat.color ?? color,
        ^^^^^
../../../snap/flutter/common/flutter/packages/flutter/lib/src/material/text_button.dart:77:9:
Info: Found this candidate, but the arguments don't match.
  const TextButton({
        ^^^^^^^^^^
../../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_platform_widgets-1.20.0/lib/src/platform_button.da
rt:306:7:
Error: No named parameter with the name 'animationDuration'.
      animationDuration: dataRaised?.animationDuration,
      ^^^^^^^^^^^^^^^^^
../../../snap/flutter/common/flutter/packages/flutter/lib/src/material/elevated_button.dart:65:9:
Info: Found this candidate, but the arguments don't match.
  const ElevatedButton({
        ^^^^^^^^^^^^^^
../../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_platform_widgets-1.20.0/lib/src/platform_dialog_ac
tion.dart:174:9:
Error: No named parameter with the name 'color'.
        color: data?.color,
        ^^^^^
../../../snap/flutter/common/flutter/packages/flutter/lib/src/material/text_button.dart:77:9:
Info: Found this candidate, but the arguments don't match.
  const TextButton({
        ^^^^^^^^^^
Error: Compilation failed.

**Comment by hoangdat** [comment]
Hi @aioun, please try with Flutter 3.0.5

**Comment by aioun** [comment]
Thanks hoangdat. Now it is OK. 
Do you think an upgrade to actual version soon ?

**Comment by hoangdat** [comment]
in the roadmap, maybe at the end of 2022
