### ISSUE TITLE
[vacation] format option in html template but plain text

### ISSUE THREAD

**Issue by haftus98** [linagora/tmail-flutter#1226]
**Description**
I can only see format option in html template but plain text

**Image/Video**
[Untitled_ Nov 21,2022 11_57 PM.webm](https://user-images.githubusercontent.com/97084773/203114526-b35a7db9-c343-4195-8b11-a747ce9c5f61.webm)

**Environment**
v0.4.2

**Comment by hoangdat** [comment]
She wants toolbar for plain text also :))))
