### ISSUE TITLE
[Advance search] Search result is not correct after removing `subject` in AdvancedSearch and click on `From me` option

### ISSUE THREAD

**Issue by haftus98** [linagora/tmail-flutter#1231]
**Description**
1. Open AdvancedSearch
2. Type in `Subject`
3. Search
4. Re-open AdvancedSearch
5. Remove text in `Subject`
6. Search
7. Click on `From me` option
8. The search result is not updated

**Video**
[Untitled_ Nov 22,2022 11_44 AM.webm](https://user-images.githubusercontent.com/97084773/203264594-07983372-277e-4dfd-a460-89f928b587e5.webm)

**Environment**
v0.4.2, gg chrome

**Comment by hoangdat** [comment]
you mean `From me` is not applied in the search? am I right? Please provide the expectation also

**Comment by haftus98** [comment]
It's supposed to return only From me filter but the removed subject filter

**Comment by dab246** [comment]
- This issue has been fixed since previous PRs.


https://user-images.githubusercontent.com/80730648/219607642-4b8d3570-9b8f-4f6a-aee5-af2bdb6f7537.mov

**Comment by chibenwa** [comment]
@QuangHoang1210 ?
