### ISSUE TITLE
[Feedback] Can not copy/paste to mentioned fields in ticket with mobile application

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#1232]
OS:
Android 10 QP1 A.190711.020
IOS 16.1.1

Precondition: Bug only happen with fields mentioned in step 2 bellow

Reproduce step:
1, User copy a text content in email body
2, User tap on one of these field (Subject, To, CC, BCC)
3, User tap and hold until copy paste option is displayed

Actual: System didn't display copy paste option which let user select to paste
Expected: User can copy and paste on fields which mentioned in step 2

https://user-images.githubusercontent.com/124866146/223012443-d892b986-5a75-40e7-8ff2-7f0a1120a7e2.mp4

**Comment by hoangdat** [comment]
can not reproduce in both Android and iOS v0.4.3

**Comment by hoangdat** [comment]
@QuangHoang1210 please help us verify

**Comment by QuangHoang1210** [comment]
Reproduce step:
1, User copy a text content

**Comment by dab246** [comment]
It works well. Please check again. @QuangHoang1210 



https://user-images.githubusercontent.com/80730648/223102189-437cf3b3-30ad-4b17-b03e-1df2109bedc6.mp4

**Comment by QuangHoang1210** [comment]
@dab246  Please reproduce with case "Copy text content from **email body** then try to paste to mentioned fields above"

**Comment by dab246** [comment]
- Real device

**Comment by dab246** [comment]
> @dab246 Please reproduce with case "Copy text content from email body then try to paste to mentioned fields above"

We tested on real device, simulator all work fine.



https://user-images.githubusercontent.com/80730648/223608900-460a8154-391a-4385-bf53-b2223981d164.mp4

**Comment by QuangHoang1210** [comment]
@dab246  please following exactly reproduce step and watch video bellow:


https://user-images.githubusercontent.com/124866146/223625255-f3a32a2b-6b00-46b9-a3a2-e621933d8ce7.mp4

**Comment by QuangHoang1210** [comment]
Re-open this ticket.

It still happen on Tmail 0.7.4 Android 

https://user-images.githubusercontent.com/124866146/224928144-2d685903-32dd-4e80-9ed0-eaf8ac3cf62c.mp4

**Comment by dab246** [comment]
- Double tap: Not working
- Long tap: Work fine

**Comment by hoangdat** [comment]
- Context: in composer
- Should support: double tap and long tap also

**Comment by QuangHoang1210** [comment]
Retest on 0.7.9 IOS

- Double tap: Work fine
- Long tap: Work fine

I will do more test on new version
@hoangdat  @dab246
