### ISSUE TITLE
Email list: rendering issues

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#1233]
### Description

![signal-2022-11-22-165442_002](https://user-images.githubusercontent.com/6928740/203283803-7dc6bada-1b53-4f4d-91be-60de510986ff.jpeg)

Find where the grey bar comes from and fix it...

**Comment by dab246** [comment]
It is very difficult to reproduce it. We need more information on this matter.

**Comment by chibenwa** [comment]
I know... Sorry: I have little information to provide you with...

**Comment by dab246** [comment]
@chibenwa  It's okay I understand. In the meantime, please help me check the following issues:
1. Can you check in the current latest version `0.4.3` to see if there is a problem?
2. Does this error always or often appear?

**Comment by chibenwa** [comment]
Sorry it is not my mailbox but alex one...
