### ISSUE TITLE
 [Story] As a user, I want to see the spam report 

### ISSUE THREAD

**Issue by dieptran88** [linagora/tmail-flutter#1238]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC

* TODO: {link}

## Definition

- Given that I am Tmail user and I logged in successfully 
- Given that the spam report is enabled 
- I can see a banner in top of email listing screen with message:
" You have [number of unread/new spam email]  new spam emails !"  and buttons Show detail, Dismiss and there-dot button
- If I click Dismiss button, the banner disappears
- When I click on button Show Detail, redirect to spam mailbox.
- Each spam email includes information: Sender, Subject, Summary, Received time and button Not spam
- when I click on button Not spam, the email is moved to my Inbox and no-longer appears in this list 
- If there is no new/unread spam email, the banner will not be shown 
- And When I click on one email,the email content will be opened 

[Back to Summary](#summary)

## Screenshots

![New Wireframe 1 copy (23).png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/00e6923a-19b2-4aa2-93bc-f6bd8e189887)

![New Wireframe 1 copy (29).png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/07938c48-c355-42a2-876f-e129554c3ae1)
[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

**Comment by chibenwa** [comment]
Maybe a "trash" button next to each spam mail?

Please precise that after being categorised in this review page, spam mails ends up marked as seen.

**Comment by hoangdat** [comment]
How often report should be showed? Once a day?

**Comment by chibenwa** [comment]
> How often report should be showed? Once a day?

IMO yes, no need more. We can start with this.

**Comment by nqhhdev** [comment]
- Change the priority of not spam action in the spam mailbox
