### ISSUE TITLE
[filltering rule] move remaining mail checkbox

### ISSUE THREAD

**Issue by haftus98** [linagora/tmail-flutter#1239]
**Description**
As I created new filtering rule, it only applied to new upcoming emails but the old ones.

**Expected**
There is a checkbox called "move the remaining mails to the mailbox" which allows me to move all malls with the same chosen conditions to the selected folder.

**Comment by chibenwa** [comment]
Yes we could imagine having a folder action "run a rule against the content of this folder" agree.

We could plan some work as well on "automations"

 - Archive my INBOX automatically
 - Empty my trash after 1 week
 - Delete my drafts after 1 month
 - Delete SPams after 1 month
 
 Etc... That could be setted up by the user according to his needs.

IMO this is a bit more "longer term" but it would for sure help on the usability front.

**Comment by chibenwa** [comment]
I will open dedicated stories for this.
