### ISSUE TITLE
[Bug] email list of previous mailbox still show when current mailbox in loading

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#124]
### Description
I am using mobile (Pixel XL, emulator, Android 11)
1. I stay in mailbox A
2. all mails of mailbox A is showed
3. I click on A -> open mailbox list
4. I select mailbox B
5. Mailbox B loading but all mails of mailbox A still show

### Expected result
when loading in new mailbox, email of previous mailbox should not be showed

### Acceptance criteria

The list of acceptance criteria (defined in the corresponding User Story or coming from your functional knowledge of the product)
These acceptance criteria must be met by the corrective implementation done by the developers.

### Context

Devices, OS

### Additional information

frequency, log files,...

**Comment by dab246** [comment]
This error no longer exists.
