### ISSUE TITLE
[Story] As a user, I want to enable/disable spam report  

### ISSUE THREAD

**Issue by dieptran88** [linagora/tmail-flutter#1240]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC

* TODO: {link}

## Definition

- Given that I am a Tmail user
- I log-in Tmail successfully
- When I click on three-dot button of Spam folder, and  the spam report is enabled, there will be a new option : Disable Spam report. If I select this option,  the spam banner will not be shown on top of email listing. 
- When I click on three-dot button of Spam folder and the spam report is disabled, there will be a new options: Enable Spam report. If I select this option, the spam banner will be shown in email listing screen when there is new/unread spam email.
- If the spam report is enabled, in the spam banner, I can click on three-dot button and see the option "Learn more". When I click on it, the context menu of Trash folder will be displayed. 

[Back to Summary](#summary)

## Screenshots

![New Wireframe 1 copy (30).png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/38d29a74-e3c6-4a21-85b6-cc8ce7c74d9c)

[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

**Comment by chibenwa** [comment]
I don't knpw if this deserve a dedicated profile page... Other suggestions maybe?

**Comment by hoangdat** [comment]
Suggestion:
- show in default, turn on-off in context menu of Spam mailbox? WDYT?

**Comment by chibenwa** [comment]
Yes, sounds good!
