### ISSUE TITLE
[Preproduction link] cannot access

### ISSUE THREAD

**Issue by haftus98** [linagora/tmail-flutter#1241]
I can't access the link : https://gateway.upn.integration-open-paas.org/

![image](https://user-images.githubusercontent.com/97084773/203947957-c6ff2434-73fc-4d50-aba6-2883b813f2d0.png)

**Comment by chibenwa** [comment]
Steps to reproduce, please.

**Comment by hoangdat** [comment]
This is not an app exposed.
