### ISSUE TITLE
[Filtering rule / figma] condition after "if" is missing compared to production

### ISSUE THREAD

**Issue by haftus98** [linagora/tmail-flutter#1242]
**Description**
According to figma file, I should have 1 more condition after if.

**Image**
![image](https://user-images.githubusercontent.com/97084773/203948502-bc615f75-f50a-413c-a21f-46d7847fcaae.png)

(from figma)

![image](https://user-images.githubusercontent.com/97084773/203948617-fe9f0c82-83f3-4b01-aa4e-c68e2ae338af.png)

(From production)

**Expected**
Adjust the design according to the actual product

**Comment by chibenwa** [comment]
IMO: let's keep it simple.

Change the text to `If the following condition is met:` (we will see later for supporting composed conditions...)

**Comment by hoangdat** [comment]
At the moment, we did not apply multiple conditions in rule.
