### ISSUE TITLE
[Move to after advance search] result list went blank

### ISSUE THREAD

**Issue by haftus98** [linagora/tmail-flutter#1243]
**Description**
After I searched with advance search and I moved an mail, the mail list was gone

**Reproduce**
Step 1: Search with advance search, has attachment
Step 2: Move 1 mail from the list

**Video**
[Untitled_ Nov 25,2022 5_09 PM.webm](https://user-images.githubusercontent.com/97084773/203959755-10b122c8-c9a1-485d-b194-bc3968631262.webm)

**Environment**
v0.4.3 gg chrome

**Comment by dab246** [comment]
2 HD
