### ISSUE TITLE
Enable FCM for Web browser 

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#1246]
### 
- config FCM for Web browser
- callback message for web browser

### DoD:
- [x] enable/disable FCM for web/browser (separate with Android/iOS)
- [x] receive messages from tab open/close
- [x] configuration docs

**Comment by hoangdat** [comment]
### No notification in web
- Foreground: Only Refresh
- Background: Tab is not in foreground?
- Terminated: no tab is open? => ignore?
- Multiple tab? Message will receive in what callback?

Background/Terminated -> store StateToRefresh. When user re-open, check `StateToRefresh` to synchronize or not.

**Comment by hoangdat** [comment]
not implement background case

**Comment by dab246** [comment]
2 HD

**Comment by hoangdat** [comment]
2HD
