### ISSUE TITLE
Preflight request should be cached

### ISSUE THREAD

**Issue by quantranhong1999** [linagora/tmail-flutter#1247]
### Description
A preflight request is called every time client executes a new group JMAP request.
![image](https://user-images.githubusercontent.com/55171818/204194552-61871d98-8dc9-495b-878f-0eeaeff7419a.png)

### Expected result
It should be cached => saving us a good response time.
rf: https://developer.mozilla.org/en-US/docs/Glossary/Preflight_request

Maybe we need to add `Access-Control-Max-Age` response header from backend also?

### Context
Web (maybe android/ios also?)

**Comment by chibenwa** [comment]
> Maybe we need to add Access-Control-Max-Age response header from backend also?

Sonds fair! Please open a James issue for this @quantranhong1999

**Comment by hoangdat** [comment]
no longer preflight request in staging.
