### ISSUE TITLE
Enable FCM for iOS

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#1248]
### 
- config FCM for iOS
- callback message for iOS: foreground/background/terminated
### DoD:
 - [x] enable/disable FCM for web/browser (separate with Android/Web)
 - [x] receive messages from tab open/close

**Comment by hoangdat** [comment]
iOS:
- [ ] Use FirebaseOptions

**Comment by ManhNTX** [comment]
Need Config for IOS:
![Screenshot 2022-12-08 at 13.53.47.png]
(https://images.zenhubusercontent.com/62a1c30534da3d10032e21fb/d093e5f6-8c07-496b-b840-0ec33c9bcab8)
Example: 
![Screenshot 2022-12-08 at 13.55.47.png](https://images.zenhubusercontent.com/62a1c30534da3d10032e21fb/df5a0534-d059-4b6b-a4ab-441981cf4518)

**Comment by quantranhong1999** [comment]
> @hoangdat @quantranhong1999 Need Config for IOS

Ok I will have a look on James side.
