### ISSUE TITLE
[SPAM] mark email as spam and apply rule to email address

### ISSUE THREAD

**Issue by haftus98** [linagora/tmail-flutter#1264]
**Description**
When I received an email regarded as spam, I want to mark it as spam and apply that rule to the email sent that spam.

**Reproduce**
1 select an email by clicking on the circle icon
2 choose mark as spam 
3 click on the pop-up box that show option to run this rule for the email address

**Expectation**
When clicking mark as spam, there would be a popup message "Create spam rule for this email?"
If yes
1. the email was moved to spam and the email address which sent spam email is automatically moved to spam for any email sent later
2. Create 1 record at email rule 
From + contain "email selected"
Move message to Spam

If no
Only move the selected emails

**Environment**
Production 0.4.3

**Comment by chibenwa** [comment]
Auto-learning is handled via RSpamD.
