### ISSUE TITLE
[related email] quick search for related email

### ISSUE THREAD

**Issue by haftus98** [linagora/tmail-flutter#1267]
**Description**

In case there are too many emails with the same subjects, I want to search them quickly.

**Repoduce**

1 Choose an email in inbox or sent or other folders
2 Click finding related emails
3 The subject will be on the search bar and colored in each found related emails

**Expectation**

There should be a feature  for finding related emails

**Environment**

Production 0.4.3

**Comment by chibenwa** [comment]
This ticket is unclear because you do not use words that relates to email.

Are you speaking of an email `thread` ? IE a message and subsequent replies / forwards ?

**Comment by haftus98** [comment]
I meant list of mail not only mail thread.
For example, I have email A and B with the same subject
When I click "find related mail" button, Tmail would show a list of mail with the same subject including threads and other mails as well. Other than I have to copy the subject and paste it to advance mail

**Comment by chibenwa** [comment]
I do not see the point.

I prefer focussing on thread support.
