### ISSUE TITLE
[Draft mail] Draft mail without content shouldn't be saved

### ISSUE THREAD

**Issue by haftus98** [linagora/tmail-flutter#1273]
**Description**
From composer I input some content then remove all of it, the mail was saved to draft

**Expected**
Draft mail shouldn't be saved
 
**Video**

https://user-images.githubusercontent.com/97084773/205817692-3853c3e2-3de3-41bc-8d46-30c09f942e11.mp4

**Environment**
V0.4.2 production IOS , V0.4.2 pre production IOS

**Comment by hoangdat** [comment]
duplicated #3034
