### ISSUE TITLE
[Log out] Can not logout OIDC

### ISSUE THREAD

**Issue by haftus98** [linagora/tmail-flutter#1275]
**Description**
I logged in using OIDC, then loged out. I couldn't click on sign out button.

**Reproduce**
S1: Log in using OIDC
S2: Log out

**Video**

https://user-images.githubusercontent.com/97084773/205861012-572e82e2-e6da-4c9b-8e8e-25e6a486d4af.mp4

**Environment**
Prepod IOS v0.4.2

**Comment by hoangdat** [comment]
@haftus98 Can not reproduce in both emulator and iPhone X (iOS 16)

**Comment by haftus98** [comment]
I just deleted the app and loged out again, It worked fine this time
