### ISSUE TITLE
[Web] Notification still show in the web

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#1278]
- But TMail sends no notifications on Web so we do not need that permission
<img width="368" alt="image" src="https://user-images.githubusercontent.com/6462404/208806938-37464285-6a86-4548-b22b-d2f40c668192.png">

### Expected:
- [ ] no notification show in web browser in all case [background/foreground]
- [ ] no ask permission

**Comment by dab246** [comment]
@chibenwa  @Arsnael  Please enable the capability for `FCM` on the `preprod` server so I can double check this issue.

**Comment by Arsnael** [comment]
> @chibenwa @Arsnael Please enable the capability for `FCM` on the `preprod` server so I can double check this issue.

Ok I will put back the latest version then (I did rollback to investigate why you could not upload on preprod)

**Comment by Arsnael** [comment]
I just reupdated the tmail backend image to our latest release... can you try again @dab246 and let me know if it's ok? Thanks

**Comment by dab246** [comment]
> I just reupdated the tmail backend image to our latest release... can you try again @dab246 and let me know if it's ok? Thanks

Cool, It was working fine. Thanks @Arsnael :))
