### ISSUE TITLE
[Bug] Download attachment make the app crash sometimes in iOS

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#128]
### Description

Download attachment make the app crash sometimes in iOS

### Preconditions (optional)

attachement is attached by other user use this app to send email

### Acceptance criteria

The list of acceptance criteria (defined in the corresponding User Story or coming from your functional knowledge of the product)
These acceptance criteria must be met by the corrective implementation done by the developers.

### Context

Devices, OS

### Additional information

frequency, log files,...

**Comment by dab246** [comment]
Please provide the specific faulty tested device here.

**Comment by dab246** [comment]
Tested on some ios virtual machines without any problems. Please provide more information.

**Comment by hoangdat** [comment]
IMO, it is sometime in Iphone 11 Pro Max

**Comment by dab246** [comment]
This error was not found.

**Comment by hoangdat** [comment]
Move to sprint backlog to monitor more. I have this issue in iOS 14.3

**Comment by dab246** [comment]
Tested on simulator ios 14.3 did not detect this error.

**Comment by hoangdat** [comment]
> Tested on simulator ios 14.3 did not detect this error.

sure, we will check this when back to the office

**Comment by hoangdat** [comment]
@Kevinle2312 please help us review this case

**Comment by Kevinle2312** [comment]
@hoangdat I checked on iPhone 7 and this issue does not happen. The only thing is once the file is downloaded, there is no message for the user.

**Comment by hoangdat** [comment]
what is message? what you expect? please describe it more clearly

**Comment by Kevinle2312** [comment]
> what is message? what you expect? please describe it more clearly

Something like "File is downloaded" or "File saved"

**Comment by Kevinle2312** [comment]
PAssed on CI platform.
