### ISSUE TITLE
Improve static assets capacity loading for Firefox

### ISSUE THREAD

**Issue by quantranhong1999** [linagora/tmail-flutter#1281]
### Description
The capacity of static assets to load every time we do F5 on TMail web on Firefox is not optimal as Chrome.
- Chrome when disabling cache:
![image](https://user-images.githubusercontent.com/55171818/206075754-493f968a-57c1-4451-93db-54c2c3436ed0.png)
Transferred capacity: 12.4MB
- Chrome when using cache:
![image](https://user-images.githubusercontent.com/55171818/206075857-e737f837-bbe2-4ea1-9bae-b0156880926f.png)
Transferred capacity: 4.2KB

While for Firefox:
- Firefox when disabling cache:
![image](https://user-images.githubusercontent.com/55171818/206076117-eee359b3-b99a-4d26-b51c-33cc739de6f1.png)
Transferred capacity: 28.6MB
- Firefox when using cache:
![image](https://user-images.githubusercontent.com/55171818/206076214-13449f56-92c4-42cc-9d75-ce14b9a42e3b.png)
Transferred capacity: 16.1MB

Impact: page loading slower and use more energy on Firefox.

### Expected result
Lower static asset capacity to load for Firefox.

#### Reproduction Steps
F5 and measure the capacity load.

### Context

Chrome: Version 108.0.5359.94
Firefox: 107.1

**Comment by hoangdat** [comment]
Please verify in the latest version

**Comment by quantranhong1999** [comment]
On TMail v0.8.3 (master branch actually)
Chrome (Version 114.0.5735.198 (Official Build) (64-bit)) without cache:
![image](https://github.com/linagora/tmail-flutter/assets/55171818/b8a8318c-507f-4edb-ab79-1bf03d50989c)

Chrome with cache:
![image](https://github.com/linagora/tmail-flutter/assets/55171818/888f95ff-e47e-40ab-a44b-f86f6843a048)

Firefox (115.0 (64-bit)) without cache:
![image](https://github.com/linagora/tmail-flutter/assets/55171818/9fcccc36-ebc2-4a25-9699-3b979606cbf0)

Firefox with cache: 
![image](https://github.com/linagora/tmail-flutter/assets/55171818/994f0cbc-fd9b-41e4-a365-2a5bd3c9e1c8)

I capture the size of the resource and loading time at the point TMail is usable (emails are loaded, do not count others defer load).

The size of loaded resources is significantly reduced on both Chrome and Firefox. (that means the assets cache, gzip, JS minify and nother optimization efforts from the Flutter team did work :-) )

About loading time, I think it takes around 15s to load TMail the first time, and around 4s to load TMail after that.

As a user, the loading time in the first time is still quite long, but it is good to me for the next times.
