### ISSUE TITLE
[TMail Web] Can not scroll on 2K resolution screen?

### ISSUE THREAD

**Issue by quantranhong1999** [linagora/tmail-flutter#1291]
### Description
I can not scroll on my 2K resolution screen, while it is good on my full HD screen.
[scroll-bug.webm](https://user-images.githubusercontent.com/55171818/206629591-ffa6ff49-e488-4a90-969f-09f84e7ff2a6.webm)

### Expected result
Normally scroll on big-resolution screens.

### Current behavior
Can not scroll on a 2K resolution screen. (at least for me, not sure how about others)

#### Reproduction Steps
Scroll TMail web on >= 2k resolution screen. Try with both Chrome/Firefox.

### Context
Chrome: Version 108.0.5359.94
Firefox: 107.1

**Comment by chibenwa** [comment]
@quantranhong1999 retest?

**Comment by quantranhong1999** [comment]
> @quantranhong1999 retest?

Still the same issue for me on preprod 0.7.6.

It could be scrolled when there is a spam notification:
![image](https://user-images.githubusercontent.com/55171818/229978090-eb7a1479-1a0d-4d3b-9ac2-2315e9262f33.png)

Otherwise, it could not.
