### ISSUE TITLE
Can't close mailbox drawer when clicking outside on landscape orientation tablet

### ISSUE THREAD

**Issue by dab246** [linagora/tmail-flutter#1293]
### Desc

- Mailbox left menu can only be closed when clicking on the `x` button or dragging it.

https://user-images.githubusercontent.com/80730648/229980578-5e29e77c-5ee7-4673-9e2a-ab015a102da7.mov

### Expect

- Clicking outside (specifically EmailView) can close mailbox menu left
- Work fine on web responsive

https://user-images.githubusercontent.com/80730648/229981052-a0314073-b18e-4ca4-975c-441ba3061d79.mov

**Comment by chibenwa** [comment]
@dab246 more input please

**Comment by dab246** [comment]
> @dab246 more input please

Updated

**Comment by QuangHoang1210** [comment]
@hoangdat please support me to retest it
