### ISSUE TITLE
[Login} can not log in safari 

### ISSUE THREAD

**Issue by haftus98** [linagora/tmail-flutter#1297]
**Description**
I tried to log in Tmail production on safari, the message prompts "Unknown error occured"

**Reproduce**
Step1: from macos/safari, access https://tmail.linagora.com/
Step2: input email, password, click enter

**Image**
![image](https://user-images.githubusercontent.com/97084773/206994279-4091b380-b4a9-4353-bff1-6da3d05eb52b.png)

**Environment**
Safari, v0.4.3 production

**Comment by chibenwa** [comment]
Please provide details ;-)

**Comment by hoangdat** [comment]
<img width="1788" alt="image" src="https://user-images.githubusercontent.com/6462404/207238288-d86098c3-edc3-42df-bf05-0bab8833086b.png">

**Comment by chibenwa** [comment]
This is a backend problem. Please see https://github.com/linagora/tmail-backend/issues/536
