### ISSUE TITLE
Improve autocomplete experience on TMail when there is no match result

### ISSUE THREAD

**Issue by quantranhong1999** [linagora/tmail-flutter#1298]
### Description
Currently, when the autocomplete result is empty, we do not respond anything ⇒ user may not know there are network issues or the search server is down, or just there is no match result.

### Expected result
IMO we should somehow respond to users in that case.
E.g shake the autocomplete bar?

### Context

All platforms.

### Notes

Please help me add the UX improvement label.

**Comment by chibenwa** [comment]
GMail have the same behaviour than us.

Let's not re-invent the wheel?
