### ISSUE TITLE
Allow selecting individual emails

### ISSUE THREAD

**Issue by quantranhong1999** [linagora/tmail-flutter#1299]
### Description
Current behavior: selecting all emails and then unselecting, which is inconvenient for users.

### Expected result
Selecting individual emails

### Context

All platforms.

### Notes

Please help me add the UX improvement label.

**Comment by chibenwa** [comment]
This is doable today by a flyover on the initials of the sender.

What is expected here?

**Comment by quantranhong1999** [comment]
> What is expected here?

I expected a check box before the initials of the sender. But now I know we can do that flyover. Great.

I will close this.
