### ISSUE TITLE
[Auto suggestion] Auto suggestion list doesn't close when finishing typing 

### ISSUE THREAD

**Issue by haftus98** [linagora/tmail-flutter#1306]
**Description**
When I finish typing an address, the suggestion bar didn't close. When I clicked on the suggestion bar, the suggestion bar didn't close as well. When I removed the input address, the suggestion bar didn't close too.

**Reproduce** 
step1: Type an address, click space to get the address value
step2: check the suggestion bar appears, click on the suggestion bar => the suggestion bar doesn't close
step3: delete the type address => the suggestion bar doesn't close

**Video**

https://user-images.githubusercontent.com/97084773/207286869-e2a7236f-279d-4b1b-aee5-5fe57162dffa.mp4

**Environment**
v0.4.2 production IOS

**Comment by QuangHoang1210** [comment]
This is closed however we keep following this one https://github.com/linagora/tmail-flutter/issues/1470 which relate to this issue
