### ISSUE TITLE
Check capability in session

### ISSUE THREAD

**Issue by ManhNTX** [linagora/tmail-flutter#1309]
### DoD:
- Create a feature to validate session available for TeamMailbox. 
### Desc:
- Link Issues: https://github.com/linagora/tmail-flutter/issues/1094
- Link BE Docs: https://github.com/linagora/tmail-backend/blob/master/docs/modules/ROOT/pages/tmail-backend/features/teamMailboxes.adoc

 - Create a feature to validate session available for TeamMailbox.
 - Using API `GET` `https://gateway.upn.integration-open-paas.org/.well-known/jmap` to get all capabilities of account. Then check the list of capabilities contains `urn:apache:james:params:jmap:mail:shares` or not. If not throw error.

**Comment by hoangdat** [comment]
why we need a separate module for TeamMailboxes?

**Comment by hoangdat** [comment]
what happen if `session` not contain `capabilities` for team mailboxes?

**Comment by hoangdat** [comment]
how to filter Team Mailboxes with personal Mailboxes?

**Comment by hoangdat** [comment]
what happen with `Subscribed`?

**Comment by hoangdat** [comment]
what is DoD of this ticket?
