### ISSUE TITLE
[Dev] Display the list of `Team-Mailboxes` in `TeamMail` project

### ISSUE THREAD

**Issue by ManhNTX** [linagora/tmail-flutter#1310]
### Story:

#1105 

### DoD:

-  Display list `Team Mailboxes` in mailbox menu as new design

![Screenshot 2022-12-19 at 13.41.57.png](https://images.zenhubusercontent.com/605059df174a357c7888640f/816dd7e2-b8b5-4f07-b964-ff46980d884b)

### Desc:

1. Check capability `urn:apache:james:params:jmap:mail:shares` of TeamMailboxes in `session`

```dart
requireCapability(
   session, 
   accountId, 
   [
      CapabilityIdentifier.jmapCore, 
      CapabilityIdentifier.jmapMail,
      CapabilityIdentifier.jmapTeamMailboxes
   ]
);
```

- If `supported`: When called `GetMailboxMethod` using capabilities `requiredCapabilitiesSupportTeamMailboxes` in `jmap-dart-client`

```dart
Set<CapabilityIdentifier> get requiredCapabilitiesSupportTeamMailboxes => {
    CapabilityIdentifier.jmapCore,
    CapabilityIdentifier.jmapMail,
    CapabilityIdentifier.jmapTeamMailboxes
 };
```

- If not: Throw error and still the same old thread.

2. Only show mailbox has property  `isSubscribed` is `true`
3. Refactor `buildTree` logic in `TreeBuilder` + `BaseMailboxController`
- current 2 trees: default + personal 
- should implement 3 trees: default + personal + team mailboxes

### Related
- New design on figma: https://www.figma.com/file/rRVxJpCu1G22D0jqyvK7I9/TeamMail?node-id=7771%3A326794&t=h85Xai7IehihxtSv-1

**Comment by ManhNTX** [comment]
@hoangdat

**Comment by hoangdat** [comment]
- we should bring the value ASAP?
- How about if we deliver list team mailbox without `mark as read` in 1 week? How about if we deliver  list team mailbox with `mark as read` BUT it will take 2 weeks?
- same with `hide mailbox`

**Comment by hoangdat** [comment]
- Story? Use-case?
- DoD?
- Description? How other people can work with this ticket?

**Comment by hoangdat** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Tmail-Flutter-60d039db6ef62a0013432c14/issues/linagora/tmail-flutter/1310?planning-poker) with Zenhub @dab246 @ManhNTX
