### ISSUE TITLE
[Dev] Subscribe/Unsubscribe mailbox on Settings

### ISSUE THREAD

**Issue by ManhNTX** [linagora/tmail-flutter#1312]
### Story: 

#1105

### DoD:

- Create new menu setting: `Mailbox visibility` on mobile/tablet/web
- Display mailbox view with option `Show/Hide`

### Decs:

1. Apply new design:

<img width="591" alt="Screenshot 2022-12-21 at 11 42 12" src="https://user-images.githubusercontent.com/80730648/208823373-c771c8b5-97c6-40db-9f6c-8017bc2b6fc1.png">

2. Implement api

```
enum MailboxSubscribeState {
  enable,
  disable
}

class SubscribeMailboxRequest with Equatable {

  final MailboxId mailboxId;
  final MailboxSubscribeState newState;

  SubscribeMailboxRequest(this.mailboxId, this.newState);
}

Future<bool> subscribeMailbox(AccountId accountId, SubscribeMailboxRequest request);
```

### Related

- New design on Figma : https://www.figma.com/file/rRVxJpCu1G22D0jqyvK7I9/TeamMail?node-id=8188%3A340070&t=UmCemURpLRvpxLEp-1

**Comment by ManhNTX** [comment]
@hoangdat

**Comment by hoangdat** [comment]
- what is the story and use-case of this ticket?
- what is DoD?

**Comment by hoangdat** [comment]
@dab246 please describe

**Comment by chibenwa** [comment]
Done?

**Comment by dab246** [comment]
> Done?

Yep
