### ISSUE TITLE
[iOS] notification can not show when new message is coming

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#1317]
#### Reproduce:
- App in background
- new message is comming
- no notification 
- open the app again 
- notification show

#### Env:
- iphone X
- iOS 16
### Expected:
- [ ] notification must be showed when app in background/terminated

**Comment by hoangdat** [comment]
![image](https://user-images.githubusercontent.com/6462404/209354845-d124a466-aae3-4316-8787-70b57867a555.png)

![image](https://user-images.githubusercontent.com/6462404/209354875-fc443a42-b966-48c9-bc9a-927150908cb8.png)

https://firebase.flutter.dev/docs/messaging/usage

**Comment by hoangdat** [comment]
- must get `accountId` in storage
- Show common message: You have {%d} messages
- for iOS, when click in notification -> open Inbox

**Comment by hoangdat** [comment]
- `You have new messages`

**Comment by dab246** [comment]
2HD

**Comment by dab246** [comment]
1 point
