### ISSUE TITLE
[Notification] IOS can't receive notification

### ISSUE THREAD

**Issue by haftus98** [linagora/tmail-flutter#1318]
**Description**
I sent mail to IOS device (Ip X,  ios 15.6.1), I received the mail at inbox but tmail didn't get any notification. I turned on the Allow notification.

**Reproduce**
Step 1: From preproduction, log in firstname200.surname200@upn.integration-open-paas.org
Step 2: sent mail to firstname20.surname20@upn.integration-open-paas.org ( login on IOS device)
Step 3: check device of firstname20.surname20@upn.integration-open-paas.org for notification

**Environment**
preprod v0.5.1, Ip X,  ios 15.6.1

**Comment by hoangdat** [comment]
duplicated with #1317
