### ISSUE TITLE
Support move message in team-mailbox

### ISSUE THREAD

**Issue by ManhNTX** [linagora/tmail-flutter#1320]
### Story:
- https://app.zenhub.com/workspaces/tmail-flutter-60d039db6ef62a0013432c14/issues/gh/linagora/tmail-flutter/1209
### DoD: 
- Allow move message in team-mailbox (using destination Mailbox picker and Drag/drop)
### Decs:
- Show Team-mailbox in destination Mailbox picker
- Allow user move message form personal-mailbox to child mailbox of Team-mailbox using destination Mailbox picker
- Support move message to Team-mailbox by Drag/drop (only personal-mailbox and child mailbox of Team-mailbox)
- When drop message at parent Team-mailbox, don't allow move message.
- Allow actions "Move message" and "Mark as spam" will be hidden in message of team-mailbox.

**Comment by hoangdat** [comment]
- what use-case we will support for this story?
- how we can move message for this case?
- API?

**Comment by hoangdat** [comment]
pending move
