### ISSUE TITLE
[Dev] Handle read receipt email in `Team-mailbox`

### ISSUE THREAD

**Issue by ManhNTX** [linagora/tmail-flutter#1321]
### DoD

- Send receipt to sender with identity of team mailboxes

### Decs:

- Get `EmailAddress` from `namespace` of team-mailboxes
- Select identity of team-mailboxes from `EmailAddress` of `namespace`

**Comment by hoangdat** [comment]
it is hard to understand what we need to implement? 
- How to read this kind of email?
- What is different with common email?
- API need change anything?

**Comment by hoangdat** [comment]
@dab246 please describe ticket with identity of team mailbox
