### ISSUE TITLE
filter message in my team-mailbox

### ISSUE THREAD

**Issue by ManhNTX** [linagora/tmail-flutter#1322]
### Story:
- https://app.zenhub.com/workspaces/tmail-flutter-60d039db6ef62a0013432c14/issues/gh/linagora/tmail-flutter/1127
- In each mailbox, user can filter messages with attachments, star, unread as other mailbox
### DoD:
- In Team mailbox, user can filter messages with attachments, star, unread as other mailbox
### Decs: 
- Link Figma: https://www.figma.com/file/rRVxJpCu1G22D0jqyvK7I9/TeamMail?node-id=7771%3A326794&t=Ypqap5DK67DoXnZZ-0
- Filter messages with attachments, star, unread as other mailbox

**Comment by hoangdat** [comment]
I did not see the design in the board of figma, please take screenshot for more details

**Comment by hoangdat** [comment]
what we need to implement in this ticket?
