### ISSUE TITLE
[EPIC] Archive messages

### ISSUE THREAD

**Issue by dieptran88** [linagora/tmail-flutter#1328]

**Comment by chibenwa** [comment]
-> 1. Add an `Archive` action that when triggered move the mail into the archive folder. Should be easy to trigger from the email list view.

-> 2. And when swipping trigger this action (right to left: read/unread // left to right : archive)

Please @dieptran88 follow up with a design for this.

Cc @tprudentova

**Comment by dieptran88** [comment]
Please check : https://github.com/linagora/tmail-flutter/issues/1295

**Comment by hoangdat** [comment]
- flag `archived`
- move to `archived` folder
