### ISSUE TITLE
[Dev] Add `Hide` action for mailbox in MailboxView 

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#1331]
### Story:
- #1218
- UC 2

### Desc:
- is not applied to default mailboxes
- `isSubscribed` in Mailbox entity
- set `isSubscribed = false` to Hide

### DoD:
- [ ] Add context menu for Web
- [ ] Action for Tablet and mobile

**Comment by chibenwa** [comment]
Implemented?
