### ISSUE TITLE
[Dev] Support `Team-Mailboxes` in `jmap_dart_client`

### ISSUE THREAD

**Issue by dab246** [linagora/tmail-flutter#1332]
### DoD

- Implement `Team-mailboxes` for `GetMailbox` method
- Write unit test for `GetMailbox` method

### Desc

- Add new capability for team mailboxes `urn:apache:james:params:jmap:mail:shares` in `CapabilityIdentifier` class 

```dart
static final jmapTeamMailboxes = CapabilityIdentifier(Uri.parse('urn:apache:james:params:jmap:mail:shares'));
```

- Add some new properties for `Mailbox` object to support `Team-Mailboxes`

  - `namespace`: String
  - `rights`:  Map<String, Set<String>>

```json
{
  "totalThreads": 0,
  "name": "Sent",
  "isSubscribed": false,
  "totalEmails": 0,
  "unreadThreads": 0,
  "unreadEmails": 0,
  "sortOrder": 1000,
  "rights": {
    "firstname23.surname23@upn.integration-open-paas.org": [
      "i",
      "l",
      "r",
      "s",
      "t",
      "w"
    ]
  },
  "parentId": "e3f63dd0-64b4-11ed-88c0-338bebbdf582",
  "namespace": "TeamMailbox[human-resources@upn.integration-open-paas.org]",
  "myRights": {
    "mayReadItems": true,
    "mayAddItems": true,
    "mayRemoveItems": true,
    "maySetSeen": true,
    "maySetKeywords": true,
    "mayCreateChild": false,
    "mayRename": false,
    "mayDelete": false,
    "maySubmit": false
  },
  "id": "e3fca670-64b4-11ed-88c0-338bebbdf582"
}
```

- Create `requiredCapabilitiesSupportTeamMailboxes` list

```dart
  Set<CapabilityIdentifier> get requiredCapabilitiesSupportTeamMailboxes => {
    CapabilityIdentifier.jmapCore,
    CapabilityIdentifier.jmapMail,
    CapabilityIdentifier.jmapTeamMailboxes
  };
```

### Docs
- https://github.com/linagora/tmail-backend/blob/master/docs/modules/ROOT/pages/tmail-backend/features/teamMailboxes.adoc

**Comment by hoangdat** [comment]
`namespace` 
```
class Namespace  extends Equaltable 
```

**Comment by hoangdat** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Tmail-Flutter-60d039db6ef62a0013432c14/issues/linagora/tmail-flutter/1332?planning-poker) with Zenhub @nqhhdev @ManhNTX @dab246
