### ISSUE TITLE
[Dev] Show/Hide personal mailbox in mailbox view and search

### ISSUE THREAD

**Issue by dab246** [linagora/tmail-flutter#1336]
### DoD:
  - [ ] Add context menu for Web
  - [ ] Action for Tablet and mobile

### Desc:

1. Display UI

- Mailbox View:

  - If `isSubscribed=true`: Support option `Hide mailbox` 

- Search Mailbox View:

  - If `isSubscribed=true`: Support option `Hide mailbox` 
  - Else `isSubscribed=false`: Support option `Show mailbox`

2. Implement api

- Same #1311

```
enum MailboxSubscribeState {
  enable,
  disable
}

class SubscribeMailboxRequest with Equatable {

  final MailboxId mailboxId;
  final MailboxSubscribeState newState;

  SubscribeMailboxRequest(this.mailboxId, this.newState);
}

Future<bool> subscribeMailbox(AccountId accountId, SubscribeMailboxRequest request);
```

### Related

- New design on Figma: https://www.figma.com/file/rRVxJpCu1G22D0jqyvK7I9/TeamMail?node-id=8085%3A334825&t=f2LV1DrjxQB6ws9s-0

**Comment by chibenwa** [comment]
Implemented
