### ISSUE TITLE
[Dev] Apply new design for search all mailbox for mobile/tablet

### ISSUE THREAD

**Issue by dab246** [linagora/tmail-flutter#1337]
### DoD

 - ![Screenshot 2022-12-20 at 10.19.49.png](https://images.zenhubusercontent.com/605059df174a357c7888640f/19a15419-d4c9-48f2-887b-ab2c3616e374)
- new separated widget for search mailbox
- responsive for web

### Related

- New design on figma: https://www.figma.com/file/rRVxJpCu1G22D0jqyvK7I9/TeamMail?node-id=7771%3A326794&t=QnELEEUL2ZABXLoG-1

**Comment by hoangdat** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Tmail-Flutter-60d039db6ef62a0013432c14/issues/linagora/tmail-flutter/1337?planning-poker) with Zenhub @dab246 @ManhNTX

**Comment by chibenwa** [comment]
Implemented
