### ISSUE TITLE
[Dev] Apply new design for Destination Picker

### ISSUE THREAD

**Issue by dab246** [linagora/tmail-flutter#1338]
### DoD

![Screenshot 2022-12-20 at 10.48.28.png](https://images.zenhubusercontent.com/605059df174a357c7888640f/9aa37e83-49cb-4d13-9a9c-1ab3afb1eabf)

- add TeamMailbox in destination picker
- same with new MailboxView

### Related

- New design for figma: https://www.figma.com/file/rRVxJpCu1G22D0jqyvK7I9/TeamMail?node-id=6273%3A275482&t=QnELEEUL2ZABXLoG-1

**Comment by chibenwa** [comment]
Implemented
