### ISSUE TITLE
[Notification] group notification took long time to load

### ISSUE THREAD

**Issue by haftus98** [linagora/tmail-flutter#1343]
**Description**
From android devices I received group noti of 3 emais. When clicking to the group noti, the loading screen kept loading.

**Reproduce**
Step1: Send mail to devices to get group noti
Step 2: click on floating noti

**Expected**
Load the latest mail

**Video**

https://user-images.githubusercontent.com/97084773/208806341-ebf14568-2918-467c-8762-e2da23058b0a.mp4

**Environment**
prepod v0.5.1 android xiaomi note 9

**Comment by hoangdat** [comment]
what happen in 0:23?

**Comment by haftus98** [comment]
I clicked out app
