### ISSUE TITLE
[Noti] Android lock screen didn't get notification

### ISSUE THREAD

**Issue by haftus98** [linagora/tmail-flutter#1345]
**Description**
From Android xiaomi settings, I allowed all permission of noti for lockscreen. I couldn't still receive new mail notification but unlock the screen.

**Reproduce**
S1: allow noti permission for lockscreen
S2: send mail to device

**Environment**
prepod v0.5.1 xiaomi note 9

**Comment by dab246** [comment]
@haftus98  If possible, please provide the android version you used for me.

**Comment by haftus98** [comment]
MIUI 12.0.8
10 QP1A. 190711.020
@dab246

**Comment by dab246** [comment]
@haftus98  I checked again and it still works fine. Please check if you have allowed notifications to appear on the lock screen like the video below?

https://user-images.githubusercontent.com/80730648/209096076-4ba9ddba-e935-4d83-af8f-5753bcb6cc40.mp4



### Test Result

![321429570_472116544995820_7367576610599167425_n](https://user-images.githubusercontent.com/80730648/209096161-7abfc61b-b8c4-4641-b6ab-08feaf3c0665.jpg)
