### ISSUE TITLE
[Notification] no floating noti when killing app

### ISSUE THREAD

**Issue by haftus98** [linagora/tmail-flutter#1348]
**Description**
Normally with app running in background, when a mail comes, floating noti and noti in scroll down bar would appear. When killing app, there is only noti in scroll down bar but floating noti

**Reproduce**
S1: remove running background tmail app
S2: send mail to the device

**Video**

https://user-images.githubusercontent.com/97084773/209052029-b8368f4e-1ff7-4e78-894d-1f8c4ac3cf82.mp4

**Environment**
prepod xiaomi note 9, v0.5.1

**Comment by hoangdat** [comment]
What is floating noti? please update with the corrected term in mobile environment

**Comment by haftus98** [comment]
It's the Heads-up notification, check 0:41
