### ISSUE TITLE
Wrongly parsing HTML <a href...> tag 

### ISSUE THREAD

**Issue by quantranhong1999** [linagora/tmail-flutter#1355]
### Description
With the identical mail containing a specific `<a href...>` tag, while OpenPaas parses it well, tmail.linagora.com parses it wrong into a incorrect URL leading 404 error when user clicks to the link.

With email body blob contains the following: 
```
------=_Part_6_660328015.1672123712908
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 7bit

BUILD-FAILURE: Job 'James Gatling build/PR-157 [PR-157] [4]'. Check console output at "<a href="https://james-jenkins.open-paas.org/job/James%20Gatling%20build/job/PR-157/4/">James Gatling build/PR-157 [PR-157] [4]</a>"
```

- While OpenPaas renders remains the original URL:
```
<a href="https://james-jenkins.open-paas.org/job/James%20Gatling%20build/job/PR-157/4/" class="autolink autolink-url ng-scope" target="_blank">james-jenkins.open-paas.org/job/James%20Gatling%20build/job/PR-157/4</a>
``` 

- tmail.linagora.com renders break the URL:
```
<a href="<a href=" https:="" james-jenkins.open-paas.org="" job="" james%20gatling%20build="" pr-157="" 4="" "="" target="_blank">https://james-jenkins.open-paas.org/job/James%20Gatling%20build/job/PR-157/4/</a>
```

### Expected result
Do not break the URL in `href` attribute.

### Current behavior
tmail.linagora.com parsing breaks the URL in `href` attribute.

#### Reproduction Steps
Mail eml: [eml](https://github.com/linagora/tmail-flutter/files/10306815/BUILD-FAILURE._.Job.James.Gatling.build_PR-157.PR-157.4.zip)

Otherwise, Dat Pham has this mail in his mailbox.

**Comment by chibenwa** [comment]
Duplicates https://github.com/linagora/tmail-flutter/issues/1162
