### ISSUE TITLE
Can not use advanced search when stay in email view

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#1358]
https://user-images.githubusercontent.com/6928740/209751668-d4b1956c-a503-4fba-b0a3-992288a92fbb.mp4

Cc @hoangdat 

Plateform: Tmail web 0.5.1 on tmail.linagora.com

**Comment by hoangdat** [comment]
1. open email in EmailView
2. open advanced search 
3. input some field 
4. click on search button -> can not execute anything

**Comment by hoangdat** [comment]
@chibenwa srr for that, please go back to ThreadView to use the search while we fix that problem. Thanks

**Comment by chibenwa** [comment]
I confirm this works in thread view.
