### ISSUE TITLE
[Notification] Open noti while there is no network connection

### ISSUE THREAD

**Issue by haftus98** [linagora/tmail-flutter#1361]
**Description**
I received noti for new mail then turned off the network connection. Click on the notification leads to loading screen and message "unknown error"

**Reproduce**
S1: From firstname200.surname200@upn.integration-open-paas.org, send mails to firstname20.surname20@upn.integration-open-paas.org
S2: From account 20 device, check for new mail noti
S3: Turn off network connection
S4: Click on the noti
S5: check the screen

**Video**

https://user-images.githubusercontent.com/97084773/209776408-21e1e6b6-e584-4870-a382-9727912a850b.mp4

**Environment**
Prepod v0.5.1 xiaomi note 9

**Comment by hoangdat** [comment]
throw `No network error`

**Comment by dab246** [comment]
1 HD
