### ISSUE TITLE
[Dev] Display `Spam Report` banner view

### ISSUE THREAD

**Issue by dab246** [linagora/tmail-flutter#1362]
### Story

#1238

### DoD

- Display banner view when there is new spam email

### Desc

- Only show banner when `unreadEmails > 0`
- Get `unreadEmails` of mailbox with `role=spam` to show count spam email.

<img width="687" alt="Screenshot 2022-12-28 at 14 29 32" src="https://user-images.githubusercontent.com/80730648/209784778-bd04f8c4-2123-44da-8f6e-642af65d2c6d.png">

- Click `Show Detail` => Open `Spam` mailbox
- Click `Dismiss` => Hide banner and call `MarkAsReadAllMailbox` for `Spam` mailbox

### Related

- New design on figma: https://www.figma.com/file/rRVxJpCu1G22D0jqyvK7I9/TeamMail?node-id=8474%3A372215&t=B8vWo1L9flkAHLtF-1

**Comment by hoangdat** [comment]
please take care the case:
```
report showed, but user dont close it and spam have new message -> update the report also
```

**Comment by hoangdat** [comment]
- Create Separate Controller for spam report 

### Display report banner
When user open app, check:
  - check `lastTimeDismissedSpamReported` - currentTime > 4h
  - check Spam `unreadEmails > 0`

### Refresh 
If report showed, and user don't dismiss it. Update banner:
- case 1: FCM Available
  - listen DashboardAction: RefreshChangeMailboxAction
  - get mailbox of Spam 
- case 2: FCM not available
  - listen viewState in worker 
  
```
class SpamReportRepository {
  //store lastTimeDismissedSpamReported
  //get lastTimeDismissedSpamReported
}
```

**Comment by dab246** [comment]
- Implement `Mailbox/query` in `jmap_dart_client`

```json
{
    "using": [
        "urn:ietf:params:jmap:core",
        "urn:ietf:params:jmap:mail"
    ],
    "methodCalls": [
        [
            "Mailbox/query",
            {
                "accountId": "{{accountId}}",
                "filter": {
                    "role": "Spam"
                },
                "limit": 1
            },
            "c2"
        ],
        [
            "Mailbox/get",
            {
                "accountId": "{{accountId}}",
                "#ids": {
                    "resultOf": "c2",
                    "name": "Mailbox/query",
                    "path": "ids/*"
                }
            },
            "c3"
        ]
    ]
}
```
