### ISSUE TITLE
[Dev] Enable/Disable Spam report

### ISSUE THREAD

**Issue by dab246** [linagora/tmail-flutter#1363]
### Story

#1240 

### DoD

- [ ] Add context menu for mobile
- [ ]  Add popup menu for web

### Desc

1. Apply new design:
- Mobile: 

![Screenshot 2022-12-28 at 15.50.07.png](https://images.zenhubusercontent.com/605059df174a357c7888640f/c9bf3630-1852-4f62-ae0f-2d44a1523d32)

- Web:

![Screenshot 2022-12-28 at 15.50.19.png](https://images.zenhubusercontent.com/605059df174a357c7888640f/7c28cc2d-a8c4-4953-a6f9-e9b7d5cb35bd)

2. Implement

- Default: spam report state is `enable `
- Create enum `SpamReportState`

```dart
enum SpamReportState {
  enabled,
  disabled
}
```
- Store `SpamReportState` to `SharePreference`
- `SpamReportState=enabled` => Show banner spam report. Else `SpamReportState=disabled` => Hide banner spam report

### Related 

- New design on Figma: https://www.figma.com/file/rRVxJpCu1G22D0jqyvK7I9/TeamMail?node-id=8474%3A372215&t=B1Ms4Q6qmooFRge5-1

**Comment by hoangdat** [comment]
```
class SpamReportRepository {
   // storeSpamReportState
   // getSpamReportState
}
```
