### ISSUE TITLE
[Login] Login leads to random mail

### ISSUE THREAD

**Issue by haftus98** [linagora/tmail-flutter#1366]
**Description**
Login using oidc leads to random mail

**Video**

https://user-images.githubusercontent.com/97084773/210032615-da5daacf-ad34-424e-ad3d-09036c281194.mp4

**Environment**
Prepod, v0.5.1, xiaomi note9

**Comment by hoangdat** [comment]
it is not related to OIDC

**Comment by hoangdat** [comment]
Can not reproduce. I think you have some pre-step before? Can you reproduce this issue?

**Comment by haftus98** [comment]
it only happened on the Android xiaomi note 9 device, I checked on IOS and it worked fine. There is no pre-steps as you can see from vid, just log out and log in again
