### ISSUE TITLE
[IDENTITY] Can't edit HTML template

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#1370]
### Description

On v0.5.2 I cannot edit the HTML version of a signature.

### Current behavior

Only plan text editor. Clicking HTML template does nothing.

 -> BUG can't edit HTML, clicking the button does nothing
 -> UX plain text + HTML is confusing

https://user-images.githubusercontent.com/6928740/210314961-85a0c291-385b-44ac-9d86-ac1d13676895.mp4

### Expected result

Able to edit the HTML version of the signature, with HTML composer. Remove "plain text support" as this is confusing for users.

### Acceptance criteria

 -> REMOVE Identity plain text
 -> Use HTML conposer for identity message
 
### Context

Firefox 108.0

v0.5.2

tmail.linagora.com

**Comment by dab246** [comment]
Fixed in #1424

**Comment by QuangHoang1210** [comment]
Re-open this ticket. There is still display Plaintext/Html option.
Please following this ticket: https://github.com/linagora/tmail-flutter/issues/1476
