### ISSUE TITLE
[Story] As a user, I want to search email with text pattern 

### ISSUE THREAD

**Issue by dieptran88** [linagora/tmail-flutter#138]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Definition

- Given that I am Tmail app user and I have logged-in the app 
- I click on Search icon, the search bar and keyboard will be opened
-  I can touch chevron icon to close the search bar 
- I  input some text and see a suggestion box below. If the search text is too long, it will be truncated in suggestion box .
- I can click on that suggestion box or touch in Search icon in keyboard
- The app will search the inputted text the body, cc, bcc, to, from and subject of emails in all mailboxes and displays the matched in Result screen
- On result screen, I can see the list of emails with the highlighted content that matched search- text. 
- I can see the mailbox of each email on the result list
- I can click icon close on Search bar to remove the search text.

[Back to Summary](#summary)

### Mobile
![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/ee4e525a-8091-4b2b-bea7-a081cb23dfe7) ![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/cd3272ee-6c28-41d5-b3ee-20f31871163c)

![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/b6271591-aac7-4c02-9b16-33fb937ec93d) ![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/d1db2f8a-0bd2-4c92-9268-ea950962c7e1)

![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/3b1be772-9230-4646-8b69-6df3434f3917)  ![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/c5dd328f-264c-497c-a526-9c7c79541ff7)

### Tab
![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/2d534da8-35ce-4678-90e2-fae2609883f3)
![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/483830d3-4fd9-41cc-9c3c-db2851bc5979)
![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/fc8c3680-4420-40bf-8d56-fdd1927a73dd)

![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/c782f83f-c457-4c7c-ac2f-ea44142c7765)
[Back to Summary](#summary)
![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/88587d29-192b-4bc7-929b-8e33a1e7ce60)

## Misc

None

[Back to Summary](#summary)

**Comment by dieptran88** [comment]
@hoangdat Please check the mockups

**Comment by chibenwa** [comment]
Good to me for the simple search.

**In the future** I would like to have a `more options...` button bringing to advanced searched options but we can do that for later.

**Comment by hoangdat** [comment]
> In the future I would like to have a more options... button bringing to advanced searched options but we can do that for later.

For the point of comparing with some other app, I found that not too much app support advance search in mobile app, but we have more time to discuss that. And discovering more and more app with other UX.

**Comment by hoangdat** [comment]
@dieptran88 so good, but you still miss the mockup for the tablet view with three view visible: Mailbox, Thread, Email View

**Comment by chibenwa** [comment]
> For the point of comparing with some other app, I found that not too much app support advance search in mobile app, but we have more time to discuss that. And discovering more and more app with other UX.

Agree not a priority.
