### ISSUE TITLE
Apps TAB should appear as clickable

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#1382]
### Description

Flyover the apps panel the appearance of the mouse do not change thus it is hard to know that this item is clickable.

### Expected result

I expect this item to appear as clickable, just like the settings item next to it for instance.

### Current behavior

https://user-images.githubusercontent.com/6928740/210740670-68175f87-24bd-42bd-99e3-16bdb6d82245.mp4

### Context

Chromium 108.0

**Comment by QuangHoang1210** [comment]
--- 

![Image](https://user-images.githubusercontent.com/124866146/219997090-18028bfa-541b-4aeb-94a4-14847e5a449d.png)

**Comment by chibenwa** [comment]
Apps tab is not setted up on tmail.upn-xxx . So that is expected.
