### ISSUE TITLE
[Email rule] Icon edit and delete might be seen as disable

### ISSUE THREAD

**Issue by haftus98** [linagora/tmail-flutter#1385]
### Description
UI/UX, Icon edit and delete might be seen as disable since they are greyed out.

### Expected result
Some colour to allow user to know that they are enable

### Image
![image](https://user-images.githubusercontent.com/97084773/211237809-99c76611-0cc4-4860-a1da-81dcbb270d14.png)

**Comment by chibenwa** [comment]
I expect these icon to be displayed in blue
