### ISSUE TITLE
Too much notifications...

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#1388]
# Why ?

Flooded notifications. We need to improve the feature to make it less disturbing for people receiving a lot of emails.

# Suggestions

```
GIVEN I already have one TMail notification (You have a one new mail A)
WHEN I receive a new email B
THEN the current notification is updated in place (You have 2 new  mails, mail A and mail B) and do this without sound notifications.

(no 2 notifications, sound is only ON when there is not yet notification)
```

```
Notifications setting in TMail?
 -> Activate / disactivate
 -> Turn on/off notification sound?
 -> Hours for notifications?
 ```

**Comment by hoangdat** [comment]
How about setup notification for 'to', 'cc', 'bcc'?

**Comment by chibenwa** [comment]
What do you mean? Only notifs when the email is addressed to me (to) and not cced?

**Comment by chibenwa** [comment]
Here is the behaviour on samsung email application regarding notifications:

![signal-2023-02-06-123321](https://user-images.githubusercontent.com/6928740/216891632-8b7fd73e-6657-4199-8fb1-cf67d77493bc.jpeg)

![signal-2023-02-06-123326](https://user-images.githubusercontent.com/6928740/216891649-f268ab70-162f-485c-a428-5872aad67a91.jpeg)

**Comment by chibenwa** [comment]
> the current notification is updated in place

Already the case
