### ISSUE TITLE
[Send mail] Can not receive mail sent

### ISSUE THREAD

**Issue by haftus98** [linagora/tmail-flutter#1391]
### Description
I sent mail to Tmail and also gmail, I couldn't receive the sent mails
Email from mtha@linagora.com
Email to: tmnguyen@linagora.com
Email to: haminhtu2610@gmail.com

#### Reproduction Steps
S1: send mail to tmail account and gmail
S2: check the inbox

### Context
gg chrome, v0.5.2, production

**Comment by chibenwa** [comment]
Backend issue. Currently investigating.
