### ISSUE TITLE
[Replied mail from thunderbird] mail body content got the ">" symbol at the front line 

### ISSUE THREAD

**Issue by haftus98** [linagora/tmail-flutter#1392]
### Description
I received replied mails from thunderbird, the content got the ">" symbol at the front line 

### Expected result
Show normal replied mail body format

#### Reproduction Steps
S1: Send mail from Tmail
S2: Reply the sent tmail from thunderbird
S3: check mail from Tmail

### Context
IOS, production v0.5.2

### Image

![image](https://user-images.githubusercontent.com/97084773/211967515-a2a2f4af-b1f0-4a5d-87c9-8cdc4ebc51af.png)

**Comment by chibenwa** [comment]
Please share the email of the email replied to.

**Comment by chibenwa** [comment]
That's expected and that's a behaviour that we can tie down to Thunderbird.

Visualy the quoting still gets viewed efficiently and overriding it would be hard.

Won't do.
