### ISSUE TITLE
[BUG] Improve UI, UX for identity creator view on web

### ISSUE THREAD

**Issue by dab246** [linagora/tmail-flutter#1418]
### DoD
- Remove bottom padding

![Image](https://user-images.githubusercontent.com/80730648/215720859-2607c3cb-c401-4560-8844-40573d0e1626.png)

- Can not click `arrow down` of `reply field`  and `html` button of `signature`

https://user-images.githubusercontent.com/80730648/215721334-44e3e9b8-7ea5-4c40-812a-2c0fe33c12d0.mov

- The for signature editor is too small

![Image](https://user-images.githubusercontent.com/80730648/215722204-db663843-e1d0-4df9-996b-56e6bcc0b49a.png)

**Comment by christophechevalier** [comment]
Additionnal bug :bug: 

![image](https://user-images.githubusercontent.com/7148846/216638947-2a61b378-8a9c-48db-88eb-9a0d574b0786.png)

**Comment by QuangHoang1210** [comment]
This ticket #1418 is closed however we should take a look the description in ticket https://github.com/linagora/tmail-flutter/issues/1476
