### ISSUE TITLE
Submit app in store

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#144]
### To Do:
- [ ] promote content
- [ ] screenshot mobile
- [ ] screenshot tablet
- [ ] description
- [ ] license
- [ ] privacy
- [ ] test information

### DoD
- [ ] apple store
- [ ] google play

**Comment by chibenwa** [comment]
IMO we would need to do a polish first. And test the App against FastMail...

Also we should manage to be listed on JMAP.io (let me do).

GA should be done in December, we got time...

**Comment by hoangdat** [comment]
For publishing an app in store: after CD we need to get the approval from store, besides that, we can publish app in many steps (close, alpha, beta) before production. Don't worry, we should take care it as soon as possible. This step may be a verification for our app against privacy, rule, issue, ....
