### ISSUE TITLE
[Team-Mailbox] Support drag-drop email to team-mailbox on web

### ISSUE THREAD

**Issue by dab246** [linagora/tmail-flutter#1451]
### Issues
#1209 

### DoD

-  Support move from team-mailbox to personal mailbox
-  Support move from team-mailbox to team-mailbox
-  Support move from personal mailbox to team-mailbox

**Comment by chibenwa** [comment]
Why not support drag and drop to team mailbox?

**Comment by hoangdat** [comment]
hi @chibenwa, please discuss it here: https://github.com/linagora/tmail-flutter/issues/1209

**Comment by nqhhdev** [comment]
Move from team-mailbox to personal mailbox

https://user-images.githubusercontent.com/99852347/219419161-d2d5b34d-7e25-478c-bb29-b7fa5966e28a.mov
