### ISSUE TITLE
[Inbox] There is no inbox on version 0.7.0

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#1458]
*Precondition:
- Update version 0.6.0 to 0.7.0 while user keep login on application

Step:
1, Login to TMail version0.7.0
2, Click to Menu

Actual: System didn't display inbox
Expected: System display inbox

https://user-images.githubusercontent.com/124866146/219261555-2a58257d-8719-457d-a53c-d99c523da8e2.mp4

**Comment by Arsnael** [comment]
I spotted similar issue on tmail-web, and by looking at dev tools I can bring more infos.

So I opened a new session on incognito mode (no cache, ...)

And i got this: 

![tmail-bug](https://user-images.githubusercontent.com/9005025/219273413-bfdb50be-f49c-46db-a97c-51e2ee14a3cd.jpg)

You do first a mailbox/query to fetch spam and do your spam banner -> you get latest state from that
Then you use that state on your mailbox/changes... and it returns nothing. So we have no mailboxes

Maybe do spam query after? or do a get mailboxes general when opening a session at first... I don't know :)

**Comment by chibenwa** [comment]
Summary from a chat discussion:

```
Backend should subscribe when...
 -> provisionning INBOX upon IMAP connection (authenticate processor)
 -> provisionning INBOX upon email receival (LocalDelivery)
 -> JMAP draft + JMAP rfc-8621 should register the mailboxes being provisionned.
 -> We *may* add an option to subscribe automatically a mailbox upon create
 
 On side, alsways show system mailboxes please
```

https://github.com/linagora/james-project/issues/4728
