### ISSUE TITLE
[Inbox] System didn't automatic reload inbox list then user can not see the newest inbox

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#1459]
*ENV: 
OS: Android/IOS/Window
Device: Mobile/Laptop
Browser: Chrome/Safari/Firefox
Versionapp: 0.7.0

*Precondition: User already open teammail app / inbox screen on mobile

1, User send an email from other mail to teammail

Actual: User can't see the new messsage until user have to click reload button or reload the inbox screen.
Expected:  System automatically reload inbox page up-to-date

**Comment by hoangdat** [comment]
what is the platform you connect to? `prod` or `preprod`?

**Comment by QuangHoang1210** [comment]
@hoangdat already check both of them

**Comment by dab246** [comment]
This issue is related to `FCM`. Please check if `FCM` is `enabled` or not?

**Comment by hoangdat** [comment]
@QuangHoang1210 please provide the evidence

**Comment by QuangHoang1210** [comment]
It's already resolved -- Last testing date: 18 Feb 2023
