### ISSUE TITLE
[Team-mailBox] User can not send an email to other account as Team-mailbox identity

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#1463]
Step:
1, User login as account which is member of Team-mailbox (hiring@upn.integration-open-paas.org)
2, User click [Compose] button

Actual: New message popup will displayed. But there is no identity option to select what email address will do sending email action
Expected: New message popup will displayed. There is exist identity option to select what email address will do sending email action.
Example: User can select send email by hiring@upn.integration-open-paas.org

![Image](https://user-images.githubusercontent.com/124866146/219324360-8241da0d-789a-4e4e-9611-51cd8d6ffb74.png)

**Comment by chibenwa** [comment]
Investigated on the backend side https://github.com/linagora/tmail-backend/issues/566
