### ISSUE TITLE
[Team-Mailboxes/email droplist down] The content is hided by other elements once user click droplist down button

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#1468]
OS: Android, IOS, Window
Device: Mobile/Laptop
TMail version: 0.7.0

Reproduce step: Following video bellow

https://user-images.githubusercontent.com/124866146/219804414-82e89dfd-a9f3-4040-896f-519833cb77c1.mp4

Actual:

![Image](https://user-images.githubusercontent.com/124866146/219804507-391b76a8-f3b1-4551-90fa-dd311f8c28c0.png)

Expected:

User can see content of options once click droplist down icon

**Comment by chibenwa** [comment]
Ok and you cannot scroll down to see the sales team mailboxes, right?

**Comment by QuangHoang1210** [comment]
@chibenwa  Yes I cannot scroll down to see.
