### ISSUE TITLE
[Suggestion of Receiver email] The email suggest function is working incorrect

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#1470]
OS: Android, IOS, Window
Device: Mobile/Laptop
TMail version: 0.7.0

*Precondition: User never send email to this address <Example in video: firstname27.surname27@upn.integration-open-paas.org>

*Reproduce Step:
1, User login to account firstname31.surname31@upn.integration-open-paas.org
2, User tap to Compose button
3, User type firstname27.surname27@upn.integration-open-paas.org on "To:" field

Actual: System force user select saved email by checking @upn.integration....
Expected: System didn't suggest for new email which user never get in touch.

https://user-images.githubusercontent.com/124866146/219816828-0f18c886-aabb-4c39-ae38-908592d83b3e.mp4

**Comment by chibenwa** [comment]
Move this to the backend (tmail-flutter)

Provide sample input where recommendations are not good enough...

On back side we might move local part and domain part to separated indexed fields and boost the localpart. Sorting should match scoring.
