### ISSUE TITLE
[Send Email / Email Description] The email description is display weird in different window size

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#1471]
OS: Window
Device: Laptop
TMail version: 0.7.0

*Precondition: User writing an email which including image & text
*Reproduce step:
1, Compose an email which including image & text
2, Click resize window icon

Actual: The text and image display weirdly
Expected: The text and image display responsive

https://user-images.githubusercontent.com/124866146/219812868-f7780f75-2c19-4117-92de-22db8ef56762.mp4

**Comment by chibenwa** [comment]
Is there a line break between the text and the image?

If no it looks okish to me...
