### ISSUE TITLE
[Send email/Writing email] User can't see what they are typing in case email description having an image

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#1473]
OS: Android, IOS, Window
Device: Mobile/Laptop
TMail version: 0.7.0

*Precondition: Email description must include an image
*Note: This issue happens as different behaviour on each Mobile or Laptop <Following 2 videos bellow>

https://user-images.githubusercontent.com/124866146/219814705-11fafd15-61d8-4a25-9158-0c8555bce9d0.mp4

https://user-images.githubusercontent.com/124866146/219814722-b7acb907-84cc-4591-a617-729798c707e9.mp4

**Comment by chibenwa** [comment]
I think it is an auto scroll missing. Same behaviour with loooong text?

Ie not specific to image

**Comment by hoangdat** [comment]
Whenever user add image inline, add `<div>` tag
