### ISSUE TITLE
[Send Email] User can't send an email without select validate email by system

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#1479]
OS: Window
Device: Laptop
TMail version: 0.7.0

*Reproduce step:
1, User input text at subject firstly
2, User input text in description secondly
3, User input correct email address at To: fields thirdly
4, User click [Send] button

Actual: System didn't verified the email address. System display error message. User can't send an email.
Expected: System verify email address. User can send an email to that email address.

https://user-images.githubusercontent.com/124866146/219948707-f57b2567-2b94-442d-b3a8-443bf05b63d6.mp4

**Comment by dab246** [comment]
same #1153
