### ISSUE TITLE
[Drafts][View drafts] User can't view another drafts mail while opening one

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#1480]
OS: Window
Device: Laptop
TMail version: 0.7.0

*Precondition: User already open one draft mail to view

*Reproduce Step:
1, User click to open another draft mail to view

Actual: There is no other dratf mail window being opened to let user view.
Expected: System should display another draft mail window and minimize the current one.

https://user-images.githubusercontent.com/124866146/219949268-be7ad79d-0bcb-4c5d-adfe-24431e86edf3.mp4

**Comment by chibenwa** [comment]
We currently only support one composer so I guess we should close the current composer and open a new one...

**Comment by chibenwa** [comment]
Duplicates https://github.com/linagora/tmail-flutter/issues/1192
