### ISSUE TITLE
[Drafts][Save Darfts] The logic of saving drafts is not good enough

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#1481]
OS: Android, IOS, Window
Device: Mobile/Laptop
TMail version: 0.7.0

Reproduce step:
1, User click Compose button to writing a new email
2, User click close icon

Actual: System saving empty email on drafts
Expected: If user do not type anything , it should be closed without saving empty mail into draft box.

https://user-images.githubusercontent.com/124866146/219949776-c43ce22c-e5d8-46bb-a5ca-d1266d95b5d7.mp4

**Comment by dab246** [comment]
According to the video, you removed the `signature` and then closed it. IMO, you should describe the steps of executing one case to avoid side effects in another case.
