### ISSUE TITLE
[UX][Send Email] User can not drag and drop a file to send an email with attachment

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#1482]
OS: Window
Device: Laptop
TMail version: 0.7.0

*Reproduce Step:
1, User click [Compose] button
2, User drag and drop a csv,xlsx .... file to textbox

Actual: System can't let user drag and drop a file into textbox
Expected: System let user drag and drop a file into textbox

https://user-images.githubusercontent.com/124866146/220013922-a8d2c467-0cfc-4e5f-b88d-8fa617b06919.mp4

**Comment by chibenwa** [comment]
That is an actual feature, with a dedicated user story: https://github.com/linagora/tmail-flutter/issues/307

Not a bug...
