### ISSUE TITLE
[Story] Team Mail Calendar events

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#1489]

**Comment by chibenwa** [comment]
I will look into it in more carefully tomorrow.

## US 1

IMO the `Subject` of the email for events should be good enough, we do NOT need to display event title.

JUST display the icon in the thread view.

Displaying event title in thread view would be too expensive / complicated to do.

**Comment by QuangHoang1210** [comment]
@chibenwa  I want to confirm these things bellow:

1, Hyperlink to go to the event: 
- I think this one will be any link which used for Offline event & Online event (go to calender app | google map link | link other app meeting | link to an pdf file for offline meeting which in order to invite wedding celebration or dating night at restaurant for example). WDY think about it!?

2, [Yes/No/Maybe/Propose another time schedule] will be discussed on another story so I will not mention about it into this story.

**Comment by chibenwa** [comment]
> 2, [Yes/No/Maybe/Propose another time schedule] will be discussed on another story so I will not mention about it into this story. However I already discuss with @hoangdat , he said we couldn't have this feature because there is no third-party stakeholder which can use.

+1

> 1.  Hyperlink to go to the event

IMO that's not needed then.

Hyperlink to calendar app should be done in another issue.

**Comment by hoangdat** [comment]
https://github.com/linagora/tmail-flutter/blob/8ce36b42454408f0736009b13679f6be8b7b799f/docs/stories/TF-1489-TeamMail-Calender-Events.md
