### ISSUE TITLE
Problem with dependencies

### ISSUE THREAD

**Issue by GianP00** [linagora/tmail-flutter#1491]
Resolving dependencies...
Because every version of flutter_test from sdk depends on collection 1.17.1 and tmail_ui_user depends on collection 1.16.0, flutter_test from sdk is forbidden.
So, because tmail_ui_user depends on flutter_test from sdk, version solving failed.

**Comment by tk-nguyen** [comment]
Hello! Have you tried building on flutter 3.0.5? It's what we're currently using in [our CI](https://github.com/linagora/tmail-flutter/blob/master/.github/workflows/ci.yaml#L35-L42).

**Comment by hoangdat** [comment]
FYI, we are upgrading ...
