### ISSUE TITLE
[Signature][Reply screen] The signature content is not auto fill when user reply email by their identity

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#1494]
OS: Android/ IOS / Window
Device: Mobile / Laptop
TMail version: 0.7.0

*Precondition: User already configure the identity in Manage Setting

*Reproduce step:
1, User click [Reply] button an email
2, User select identity 1

Actual: The signature is not auto fill in email description text area
Expected: The signature should auto fill in email description text area

https://user-images.githubusercontent.com/124866146/220569100-762ea999-0091-4d48-acdc-6a21b162f08b.mp4

**Comment by dab246** [comment]
@QuangHoang1210 Please note the current processing flow in the application described below

1. In the editor, `signature` is displayed only on large screens (`Web, Tablet`), not on `Mobile`. (Why? Mobile is small in size, we just want to focus on the email content so we don't need to care about `signature`).
2. The `Signature` of `Identity` selected will automatically fill in the bottom of the email body when the email is sent on `Mobile`.
