### ISSUE TITLE
[Mailbox Visibility] User can't see inbox even if they select show inbox in Mailbox Visibility

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#1495]
OS: Android/ IOS / Window
Device: Mobile / Laptop
TMail version: 0.7.0

*Precondition: User login account firstname2005 (can try with other one, example: firstname2006 -> firstname2009)

*Reproduce step:
1, User tap [Menu] button
2, User tap on Manage Account
3, User tap on Mailbox Visibility
4, User tap on Show at Inbox rows

Actual: The inbox is not showed up. System display error message :"Account not found"
Expected:  The inbox is showed up.

https://user-images.githubusercontent.com/124866146/220596368-76e4e992-9a45-4d8a-b12d-e0fd5ac1d66f.mp4

**Comment by dab246** [comment]
- Fixed at PR #1464 
- We will soon apply it in the upcoming release `v0.7.1`
