### ISSUE TITLE
[UX][Edit Mailbox] Edit icon is working weirdly

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#1496]
OS: Android/ IOS / Window
Device: Mobile / Laptop
TMail version: 0.7.0

*Precondition: User already delete all mail
*Noted: It happened on all screen which have edit icon

*Reproduce step:
1, User click [Edit] button

Actual: Following video
Expected: This edit button should be disabled whenever mailbox is empty

https://user-images.githubusercontent.com/124866146/220597779-3ef6f836-36c5-4368-ad7e-ce3f63dcde63.mp4

**Comment by nqhhdev** [comment]
It's the same #1475  :)

We fixed it, pls check new release version 0.7.1
