### ISSUE TITLE
[Trash] System display error message when user try to empty trash

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#1498]
OS: Android/ IOS / Window
Device: Mobile / Laptop
TMail version: 0.7.0

*Precondition: User already at Trash which included some removed email.

*Reproduce step:
1, User click edit button
2, User select all mail on trash
3, User click delete

Actual: All mail is deleted but system display error message :"account not found"
Expected: all mail is deleted, the trash is empty. System only display message "..mail is deleted"

https://user-images.githubusercontent.com/124866146/220599327-fe58c4c2-c015-40a5-9d4e-08b06c8a210d.mp4

**Comment by chibenwa** [comment]
> Actual: The signature is not auto fill in email description text area
> Expected: The signature should auto fill in email description text area

Is this related?

**Comment by QuangHoang1210** [comment]
@chibenwa  no sorry, just a mistake from copy-paste action. I already edit the content

**Comment by nqhhdev** [comment]
Pls check it again on new release version

**Comment by nqhhdev** [comment]
@QuangHoang1210 plss check it
