### ISSUE TITLE
[UnreadCounter] [Outbox/Spam] Unread counter is not working correctly

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#1511]
OS: ios/ android
Device: mobile
TMail version: 0.7.1

*Precondition: User already login successfully and there is some unread mail exist

*Data test: 
- Account firstname31.
- Spam box exist 3 unread email

*Reproduce Step:
1, User tap on menu then tap to view spam box

Actual: The counter is 4 however there is only 3 unread email on spambox
Expected: The counter should be same with total of unread email

https://user-images.githubusercontent.com/124866146/221738601-93fa1d8e-025a-4d5b-ac7f-ecf9d82541b7.mp4

**Comment by chibenwa** [comment]
Please let's confirm first this is not a cache issue (force a reload: does the problem persist?

Then, counters issues are expected-to-be encoutered and counters are expected to be more-or-less correct.

That's a likely backend issue. Move it to tmail-backend please if we rule out the cache issue...

**Comment by QuangHoang1210** [comment]
I already reproduce by the way removing data from application. So it may be back-end issues @chibenwa

**Comment by chibenwa** [comment]
Reopen on tmail backend then.
