### ISSUE TITLE
[Inbox] System didn't display new email automatically

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#1522]
OS: Window
Device: Laptop
TMail version: 0.7.1 -- Production

*Precondition: User already log in successfully and staying at inbox screen

*Reproduce Step:
1, User send an email by another mail account to tmail account

Actual: User can't see new email automatically. User must click to reload icon to see new email.
Expected: System automatically display new email once tmail account recieve new email/reply/...

https://user-images.githubusercontent.com/124866146/222364856-3ce46a38-08d4-4e19-ad72-65daeba97e84.mp4

**Comment by hoangdat** [comment]
still not support push notification in production. wait for back-end team and re-test this later
