### ISSUE TITLE
Can not continue add recipient after enter a recipient

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#1527]
### Reproduce:
1. Composer
2. To/cc/bcc
3. Typing email `alice@domain.com`
4. `Enter` to select this email
5. Can not continue to add more email (focus lost)

https://user-images.githubusercontent.com/6462404/222661380-0f5627f9-5d43-484b-9148-f78c50c8fea1.mov

### DoD:
- focus still in the same fields to continue add other email

**Comment by dab246** [comment]
Don't understand the demo video doesn't match the re-enactment steps you describe?
