### ISSUE TITLE
[Story] As an user, I want to mark an email as spam/unspam

### ISSUE THREAD

**Issue by dieptran88** [linagora/tmail-flutter#153]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC

https://app.zenhub.com/workspaces/tmail-flutter-60d039db6ef62a0013432c14/issues/linagora/tmail-flutter/26

## Definition
**UC1. Mark a message as spam**
- Given that i am a Tmail user and i already had an account (John Doe) 
- Given that i log-in successfully to the Tmail app
- I can open a mailbox (except folder Draft) and see the list of emails
- I can mark this email as spam in 2 ways:
 1.
 I open that email, then I touch the icon "spam", then the email will be moved to folder "Spam". If I long-press on the icon , there will be a help message "Mark as spam" 
   - The email view will be closed and the previous screen (thread-view) will be displayed. 
   - I can see a toast message :"Marked as spam" and a button Undo. 
 2. 
On the thread-view, i can long-press on the avatar to select that email, then there will be an action bar displayed on the top.
      - I can touch on three-dots button then there will be a context menu that contain actions. I select option "Move to spam", then the email will be moved to folder "Spam"
      - I can see a toast message :"Marked as spam" and a button Undo. 
- When I touch the option "Undo", the email will be returned back to the original folder.

**UC2. Mark a message as not spam**
- When an mail is marked as spam, i can marked it as Not spam in 2 ways:
1. I open that email on folder Spam, and touch the icon " not spam" icon on the top of screen, then i am navigated back to listing emails screen.
- The email is returned back to the original folder
- I can see a toast message :"Marked as not spam" and a button Undo. 
2. - On the threadview, i can long-press the avatar to select that message, then there will be an action bar displayed on the top
   - I touch on three-dot button then there will be a context menu that contain actions. I select option "Not spam"
   - The email will be returned to original mailbox 
   - I can see a toast message :"Marked as spam" and a button Undo. 
- - When I touch the option "Undo", the email will be returned back to the Spam folder.

[Back to Summary](#summary)

### Mobile
![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/37ab2aac-0550-4cac-8746-599478487dbb) ![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/740f6bc3-e098-40f3-8603-b52a27965287)
![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/edb086dd-bb4e-454b-b24e-260c5c63c4ec)  ![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/b3e8ba33-c068-4105-8efe-d4f74a25f43f)
![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/58a70ca0-abf5-472d-b9cf-9f59aeca3c1a) ![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/1fccded1-f810-44c8-a2a3-2dae4020a296)
![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/dfa4c5bb-b935-48d6-8ff3-e9cd172f7efe) ![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/cdb9ea8f-b596-44ed-8388-2a12853e104c)

### Tab
![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/437c03d8-6af2-465c-97c2-40cbc114618c)
![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/d57771f6-4dbb-40a6-9a5d-0cfea561b39f)
![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/5325a8d8-1a4e-4942-92d0-41595a4e9fea)
![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/3e2270c7-97f4-488d-965f-38e4ffe2a3d8)
![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/66bd0546-defb-4550-aabb-ea744eda13d2)
![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/986e79a2-a2d0-4f21-829d-6d9da1c5ad61)

[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

## Design ticket

https://ci.linagora.com/linagora/lgs/design/-/issues/129

**Comment by hoangdat** [comment]
@dieptran88 this ticket hasn't designed

**Comment by Kevinle2312** [comment]
Passed on the Production platform.
