### ISSUE TITLE
Many attachments: some attachments not displayed

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#1530]
### Description

Given a mail with many attachment I can just see the first 3 or 4

![Screenshot from 2023-03-03 16-11-10](https://user-images.githubusercontent.com/6928740/222680186-f0abc7f4-9f0b-46ca-a6bd-12335f32c3f5.png)
![Screenshot from 2023-03-03 16-11-28](https://user-images.githubusercontent.com/6928740/222680200-12007d99-4def-4947-b150-e45b97401374.png)
![Screenshot from 2023-03-03 16-12-45](https://user-images.githubusercontent.com/6928740/222680206-bb60b783-590c-4a5f-85c8-68badc37b643.png)

Give me a way to see all the attachments of the emails, when I expand them.

tmail.linagora.com v0.7.1 Firefox 99.0.1

**Comment by dab246** [comment]
You can scroll horizontally to see them.

**Comment by hoangdat** [comment]
https://user-images.githubusercontent.com/6462404/222686135-b0113da9-c969-43ca-b7ea-2d2073828eb5.mov

**Comment by chibenwa** [comment]
> yes, but you can not scroll? @chibenwa

Not clear enough!

If I can not find it by instinct and feel the need to fill a ticket, it means there is a UX problem! Mme Michu and other regular users would also never find it...

**Comment by chibenwa** [comment]
We should get an explicit horizontal scroll-bar?

**Comment by dieptran88** [comment]
Most of other apps will show all attachments, why dont we also show all attachments after uploading them and have button hide/show like when opening an email that contains multiple attachments

**Comment by dab246** [comment]
Improvement at #2116

**Comment by QuangHoang1210** [comment]
Passed 

![Image](https://github.com/linagora/tmail-flutter/assets/124866146/c5d5979a-538d-4891-b5fc-969b0f01108f)
