### ISSUE TITLE
[UX] User can not blacken out full text content in email body

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#1534]
OS: Andoird / Ios
Device: Mobile
TMail version: 0.7.1

*Precondition: User already open one email to view

*Reproduce Step:
1, User tap on text content on email body
2, User try to blacken out the text content

Actual: User cannot blacken out it. The screen is moving following blacken out action
Expected: User can blacken out the text content. The screen is not moving.

https://user-images.githubusercontent.com/124866146/223033692-c87d9bab-a304-469c-bb9c-b20be4d84c52.mp4

**Comment by dab246** [comment]
- Android: Work fine
- iOS: Not work
