### ISSUE TITLE
[UX] User cannot scroll to view email list on Tmail production responsive version browser

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#1535]
OS: Andoird / Ios
Device: Mobile
Browser: Chrome ver 110.0.548165
TMail version: 0.7.1 - production

*Precondition: User already login successfully and user staying at inbox view list screen

*Reproduce Step:
1, User tap and scroll down/up to view other list email

Actual: User cannot scroll down/up. This action being move and drag email
Expected: User can scroll down/up to view list email

https://user-images.githubusercontent.com/124866146/223045855-91ec29e0-ae0d-4010-a405-e9dcc54c9710.mp4

**Comment by hoangdat** [comment]
side effect @nqhhdev

**Comment by chibenwa** [comment]
Side effect means regression here, right?

**Comment by hoangdat** [comment]
I have the same in chrome in iOS.

**Comment by QuangHoang1210** [comment]
Wait to test on new version of production
