### ISSUE TITLE
[UI] [Advance Search] System auto detect the searching keyword once user press space

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#1539]
OS: Andoird / Ios / Window
Device: Mobile / Laptop
TMail version: 0.7.1 - production

*Precondition: User already login successfully

*Reproduce Step:
1, User tap on advance search
2, User tap on From: text field
3, User try to input Cooking then Press space <in case we have Name of email being Cooking Mama>

Actual: System auto detect email name once user press space.
Expected: System only detect email name when user press enter.

https://user-images.githubusercontent.com/124866146/223050734-7e11015f-bd57-45ed-9428-febfd84f3d17.mp4

**Comment by chibenwa** [comment]
I am not schocked here...

**Comment by hoangdat** [comment]
please apply the same UX with auto completed in Composer. Not priority

**Comment by dab246** [comment]
### DoD

- [x] Allow use space when type email
- [x] Hide suggestion box after select item suggestion
