### ISSUE TITLE
[BE] [Searching] System not save searching result so user will lost the result of searching when try to reload page

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#1540]
OS: Andoird / Ios / Window
Device: Mobile / Laptop
TMail version: 0.7.1

*Precondition: User already login sucessfully

*Reproduce Step:
1, User tap on advance search box
2, User input 'dat' on Has the words field
3, User click [Search] button
4, User tap on url and reload the page

Actual: System display empty page then responde user to homepage (default all mail listing)
Expected: System should keep the searching result page which user already search

https://user-images.githubusercontent.com/124866146/223054006-9df1cc5a-03e9-4be2-ac41-bcbfd43ea016.mp4

**Comment by dab246** [comment]
Currently we only support simple search via `keyword` when `reload` browser. Please see details in this PR #1195

**Comment by chibenwa** [comment]
Acceptable to me.

I am closing this as according to me this can be seen as a missing feature.

Don't hesitate to open a feature request on this though.
