### ISSUE TITLE
[Advance Search] Custom Range option doesn't have meaning

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#1542]
OS: Andoird / Ios / Window
Device: Mobile / Laptop
TMail version: 0.7.1

*Precondition: User already log in sucessfully

*Reproduce Step:
1, User click on Advance Search
2, User select Custom Range in all Date field

Actual: Custom Range is selected. The calender is not opened to let user select date range.
Expected: We should remove custom range option or if let it be then calender will display once user select custom range option

https://user-images.githubusercontent.com/124866146/223067688-47671804-7d46-4560-ba87-b86a6d3ca6fc.mp4

**Comment by dab246** [comment]
Fixed at PR #1524
