### ISSUE TITLE
[UI] Application UI is blocking user after zoom in/ zoom out

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#1543]
Window only

Please following video attatchment

Reproduce step:
1, User zoom in 125 or 150 %
2, User click to reset to remove zoom in status.

Actual: UI broken. Blocking user. User must reload page to continue using Tmail.
Expected: It should still be smoothly

![Image](https://user-images.githubusercontent.com/124866146/223073686-4663b8d8-c55c-4dfd-a440-350d14b3f796.png)

https://user-images.githubusercontent.com/124866146/223072475-a1914e96-15ab-4957-b15a-401c2d8a4162.mp4

https://user-images.githubusercontent.com/124866146/223072524-a1d9f160-30f6-46fd-a5b8-12826807aaf5.mp4

**Comment by chibenwa** [comment]
Which browser?

**Comment by QuangHoang1210** [comment]
Chrome Version 110.0.5481.178 (Official Build) (64-bit) @chibenwa

**Comment by hoangdat** [comment]
@QuangHoang1210 please reproduce in preload

**Comment by QuangHoang1210** [comment]
Its not happen on preprod. Only happen on production 0.7.1
