### ISSUE TITLE
[UX] User can not move to another fields by press TAB

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#1544]
OS: Window
Device: Laptop
TMail version: 0.7.1

*Precondition: User login sucessfully

*Reproduce Step:
1, User click [Compose] button
2, User press TAB

Actual: User can not move to another fields. It only move another object in same fields right now.
Expected: User can move to another fields.

https://user-images.githubusercontent.com/124866146/223075184-54f11fce-f421-4f0f-90c3-d5790d85deca.mp4

**Comment by chibenwa** [comment]
CF https://github.com/linagora/tmail-flutter/issues/1150 that's part of a feautre for shortcuts ;-)

Not a bug, closing...

**Comment by hoangdat** [comment]
this is a bug: can not change focus to different field

**Comment by QuangHoang1210** [comment]
### Verify on 0.7.7 QA ENV

### *Reproduce Step:
1, User click [Compose] button
2, User press TAB

Actual: User only can change focus with To-cc-bcc-subject-emailbody and then if user tab again the focus is removed
Expected: User can change focus unlimited but only with elements inside Composer

Sample: To-cc-bcc-subject-email body-Cancel-Drafts-Send

<Accessibility testing>

@

**Comment by chibenwa** [comment]
Video please

**Comment by QuangHoang1210** [comment]
https://user-images.githubusercontent.com/124866146/232670452-d7cd3006-4ef4-4301-8ffa-02d42987e635.mp4

**Comment by QuangHoang1210** [comment]
Closed this ticket -- Long term improvement other action by following other one: https://github.com/linagora/tmail-flutter/issues/1780
