### ISSUE TITLE
[UX] [Text Background Color] Choose color popup is display not following one style which make user feel uncomfortable

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#1545]
OS: Window

OS: Andoird / Ios
Device: Mobile
TMail version: 0.7.1

*Reproduce Step:
1, User click on [Compose] button
2, User click on Text Background Color icon
3, User select Primary/Accent/Wheel type of choosing color screen

Actual: The choose color popup is changed once user select type.
Expected: We should fix the popup size which not changed once  user select type.

https://user-images.githubusercontent.com/124866146/223077321-2e2ab689-dabf-468a-8984-18f661878ee6.mp4

**Comment by dab246** [comment]
Please suggest a specific design that has this problem.

**Comment by chibenwa** [comment]
@dieptran88 ?

**Comment by dab246** [comment]
### DoD

- Apply as design
  + Desktop/Tablet: Color picker in the middle of the screen
  + Mobile: Color Picker in the bottom of the screen. 
- Tittle dialog: `Select a color`
- Add 2 button: `Cancel` and `Select` in bottom dialog

![Image](https://user-images.githubusercontent.com/80730648/228712268-662ded71-907d-4124-9f6f-827ce300b443.png)
