### ISSUE TITLE
[UI] System didn't automatically trim the blank space after ending characters of email input

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#1546]
OS: Andoird / Ios / Window
Device: Mobile / Laptop
TMail version: 0.7.1 - production

*Precondition: User must input an email which is not in suggestion list

*Reproduce Step:
1, User click [Compose] button
2, User input into bcc field an email which not in suggestion list "binlinzin22@gmail.com"
3, User press space
4, User press enter

Actual: System didn't trim the blank space after ending characters of email inputed.
Expected: System should trim automatically the blank space after ending characters of email inputed.

Note: It happen with all input fields in Compose.

https://user-images.githubusercontent.com/124866146/223080340-8a013ef6-d02b-461e-8a27-71ba6c7746e8.mp4

**Comment by hoangdat** [comment]
@dab246 how about: double space should be considered as selected?
