### ISSUE TITLE
`To` in Reply/ReplyAll should be filled by `ReplyTo`

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#155]
### Current behavior

![to_should_be_filled_with_replyTo.jpeg](https://images.zenhubusercontent.com/5f7d8ef759d36aecc684e2a4/f730d9e0-208b-4ee7-ae89-4bb4128fcd5b)

**Comment by chibenwa** [comment]
I think the bug might be that `replyTo` field matches my address :-)

**Comment by dab246** [comment]
I took all replyTo from the beginning. You should double check your error email. Or you can forward the error email to me to check.
