### ISSUE TITLE
[UI] [Change languages] Some words are not translated

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#1550]
OS: Andoird / Ios / Window
Device: Mobile / Laptop
TMail version: 0.7.1

*Reproduce Step:
User change languages to other one.

Actual: Some words still being english
Expected: Should be translated.

https://user-images.githubusercontent.com/124866146/223084461-5ec39b1e-2f50-4226-b31c-69c699eee939.mp4

**Comment by chibenwa** [comment]
@QuangHoang1210 please see with Dat to solve all translations topics for Vietnamese.

**Comment by hoangdat** [comment]
Good topic for `super IPH` :)
