### ISSUE TITLE
[Email Moving] User shouldn't have permission to move email from any box to these: DRAFTS, SENT, OUTBOX

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#1557]
OS: Window/ios/android
Device: Laptop/mobile
TMail version: 0.7.1

*Precondition: User already log in successfully

*Reproduce Step:
1, User drag and drop an email from anybox into one of these box: Drafts, sent. outbox

Actual: User can move it however the title of email is changed after moving.
Expected: User can't move to Drafts, sent, outbox. User can move to others one which I already compare with gmail.

https://user-images.githubusercontent.com/124866146/223360909-43c53ae5-243a-4b00-9197-b2e47bb5ffdc.mp4

**Comment by hoangdat** [comment]
Designer + BA: no impact so no limitation.

@chibenwa WDYT?

**Comment by chibenwa** [comment]
Yes IMO not needed.

I do not see any good reasons to forbid a user doing that.

I do regulary move emails from sent to other mailboxes for archival when it is important for instance.
