### ISSUE TITLE
Should not kept sender in the recipients of `Reply all`

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#156]
### Expected result
```
Given that i am in the rcpts of the original emails,
I should not be kept as a recipient after clicking "replyToAll".
```
### Acceptance criteria

The list of acceptance criteria (defined in the corresponding User Story or coming from your functional knowledge of the product)
These acceptance criteria must be met by the corrective implementation done by the developers.

### Context

Devices, OS

### Additional information

frequency, log files,...

**Comment by dab246** [comment]
How is the problem? It's too vague. Please be more clear with pictures.
