### ISSUE TITLE
[RemoveFromSpam] System unloaded new email list therefore user can select Mark As Spam option even staying at spambox

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#1563]
OS: Window
Device: Laptop
TMail version: 0.7.1 - production
TMail version: 0.7.2 - preprod

**Precondition:**
- There is a lot of (At least 30-50 mail) email in spam box.
- Must remove email from spam box quickly <following video>

**Reproduce Step:**
1, User login successfully
2, User go to spambox
3, User hoover mouse on to email rows
4, User click con '...' more icon
5, User click [Remove From Spam] option
6, Redo from step 3 several times.

Actual: System unloaded new email list, user can select Mark As Spam option even staying at spambox
Expected: System loaded new email list well then user cannot select Mark As Spam option when staying at spambox

**Note:**
Bug happens from 1:18 in the video bellow

![Image](https://user-images.githubusercontent.com/124866146/223624093-78ea5b5c-a93a-43bf-84fa-d540df600c80.png)

https://user-images.githubusercontent.com/124866146/223624137-64bd0cfc-f3a4-4cf0-851b-45ec9b3e2ac7.mp4

**Comment by nqhhdev** [comment]
I have rechecked version 0.7.6 and no issue occurred. Please retest above 0.7.6
cc: @QuangHoang1210
