### ISSUE TITLE
[Send email] [Performance] [Attachment] Uploading image on email body is too low

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#1567]
OS: Andoird/IOS/Window
Device: Laptop / Mobile
Tmail 0.7.1 production
Tmail 0.7.2 preprod

Precondition: User prepare an image or file which have 2 - 3 mb of size

Step: 
1, User click [Compose] button
2, User click Attachment icon to import an image

Actual: Tmail is uploading too low
Expected: I compare with other platform, its quickly.

https://user-images.githubusercontent.com/124866146/223651596-5a907eac-19fb-4a93-ab86-a649f2bbe62a.mp4

**Comment by dab246** [comment]
IMO, You should check back a few times, on different days. I think it's because of the network connection with the server.

**Comment by QuangHoang1210** [comment]
I need time to reproduce again the **attach image flow** and compare with other email clients
