### ISSUE TITLE
[Send email] [Attachment] I can't drag and drop attachment file into email body

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#1568]
OS: Window
Device: Laptop
Tmail 0.7.1 production
Tmail 0.7.2 preprod

Precondition: User prepare a video / pdf, word, excel .. or file which have 2 - 3 mb of size

Step:
1, User click [Compose] button
2, User drag and drop a video or file into email body

Actual: User cannot upload attachment file.
Expected: User can upload attachment file.

https://user-images.githubusercontent.com/124866146/223652456-39ec25e1-589c-4b5f-80ac-9fc650443438.mp4

**Comment by dab246** [comment]
Currently we only support `drag and drop` with `Image & Text` for body composer 


<img width="560" alt="Screenshot 2023-03-08 at 15 03 29" src="https://user-images.githubusercontent.com/80730648/223655840-a58d636e-fa6a-40a4-b94c-738329e565c0.png">

**Comment by chibenwa** [comment]
CF https://github.com/linagora/tmail-flutter/issues/307
