### ISSUE TITLE
[BackgroundApp] Android system keeps showing an app that run at background

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#1569]
**OS:** Andoird 10 QP1A.190711.020
**Device:** Mobile Redmi Note 9 128GB | MIUI Global 12.0.8
**Setting:**  
Sleep after 1 minute not working
Lock screen when put phone in  bag
**App version:**
Tmail 0.7.1 production
Tmail 0.7.2 preprod

**Precondition:** User already login and keep Tmail app running until screen is locking

Step:
1, User open the application
2, User keep it until lock screen
3, User open mobile again to continue using app

Actual: Tmail screen is still displaying but User cannot do any action until input the passcode.
Expected: Tmail screen shouldn't displaying in locking screen mode. 

https://user-images.githubusercontent.com/124866146/223908469-8cba89a4-83d8-438c-8787-25c29cd47ad0.mp4

**Comment by QuangHoang1210** [comment]
This issue still happen on Redmi. 
I think I will show you on tmr (thursday, April 6, 2023) @dab246 
cc @chibenwa

**Comment by hoangdat** [comment]
the fixed version is not released @QuangHoang1210, please wait for v0.7.7

**Comment by dab246** [comment]
@QuangHoang1210  We tested on Redmi Note 9  and it worked fine. Clear
