### ISSUE TITLE
[Compose] User can't see the cursors when typing with precondition as long content in email body

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#1573]
**OS:** Andoird/ IOS
**Device:** Mobile
**App version:**
Tmail 0.7.1 production
Tmail 0.7.2 beta

**Precondition:** User already login successfully

Step:
1, User tap on [Compose] button
2, User tap on email body text area
3, User typing some text then press enter then typing again to make a long content in email body.
4, User leave cursor at last words or middle of paragraph then scroll up 
5, User continue to type words

Actual: We had double cursor, one on subject, one on email body. Tmail screen not focus on cursor which on email body. It's not moving but user still can type.
Expected: Tmail screen should focus on cursor.

**NOTE** : Bug happens at 00:00:39

https://user-images.githubusercontent.com/124866146/223955188-b2f77d3e-3829-417b-986a-862d25e22b90.mp4

**Comment by dab246** [comment]
### DoD
- [ ] Remove double cursor (Only on android device)
- [ ] Cursor auto move while typing
