### ISSUE TITLE
[Advanced Search] List result showing duplicated email when advanced search with custom date range

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#1575]
### Reproduce:
1. Advanced Search with custom date 

![Image](https://user-images.githubusercontent.com/6462404/223956610-4b8c6f2c-e213-48dd-adeb-919187525fdc.png)

2. Search
3. Obverse list

https://user-images.githubusercontent.com/6462404/223957384-1c3c8a2b-4765-4751-bb9a-1772ef64007d.mov

**NOTE**: Compare 2 items of `haftus` at the time `0:04` with 2 items of `haftus` at `0:15`.
After show all the results to the end of list (28 Nov), results are duplicated.....

### DoD:
- list result should be show exactly

**Comment by hoangdat** [comment]
Report by @chibenwa

**Comment by dab246** [comment]
Fixed on version `v0.7.4`

**Comment by hoangdat** [comment]
> Fixed on version `v0.7.4`

Hi, what is the root cause?

**Comment by dab246** [comment]
> > Fixed on version `v0.7.4`
> 
> Hi, what is the root cause?

@hoangdat 

- Due to incorrect `SearchEmailFilter` filter. Specifically in the `beforeDate` and `afterDate` values of the filter
