### ISSUE TITLE
[TRANSLATION] Add Arabic support

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#1581]
### Description

Ask Linagora Tunisia to complete Arabic translation and add an Arabic option to team mail.

**Comment by QuangHoang1210** [comment]
Not translated most of wording.

![Image](https://user-images.githubusercontent.com/124866146/224887190-c5bb3e3a-f159-4988-ad8a-9048687fb011.png)



![Image](https://user-images.githubusercontent.com/124866146/224887268-7aac5d3f-83cb-4ae8-9c6f-100d4be3ebc3.png)

**Comment by chibenwa** [comment]
Yes translation is in progress
