### ISSUE TITLE
OIDC: support implicit flow for web

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#1591]
# Summary

From the `.well-known/openid-configuration` TMail should detect the OIDC flow.

Especially TMail web should support the implicit flow.

https://pub.dev/packages/flutter_appauth relies on native libraries thus do not support implicit flow

![Screenshot from 2023-03-13 10-44-20](https://user-images.githubusercontent.com/6928740/224603480-8287e040-7f13-45fe-be7e-71698b52dd1a.png)

However there is an open ticket for browser support => Investigate! https://github.com/MaikuB/flutter_appauth/issues/70

**Comment by dab246** [comment]
@chibenwa  Currently on the web, we use the library [flutter_appauth_web](https://github.com/CarlosPacheco/flutter_appauth_web) to support OIDC flow

**Comment by chibenwa** [comment]
Does it easily support implicit flow?

**Comment by dab246** [comment]
I think it's quite complicated. Currently they only support `authorization_code`. We need time to learn how to implement it.

**Comment by chibenwa** [comment]
Sure. We also need to understand to which extent `implicit flow` is needed...

**Comment by idc77** [comment]
implicit flow should not be used. code flow should be used

**Comment by chibenwa** [comment]
Yes @idc77 this was our understanding, too. Closing...
