### ISSUE TITLE
[BE] [Email Rules] Receiver who configured the email rule is not received the email from other user

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#1592]
OS: Window / IOS / Android
Device: Laptop / Mobile
TMail version: 0.7.4 - preprod

**Precondition:**
Receiver: firstname31.surname31@upn.integration-open-paas.org 
Sender: firstname27.surname27@upn.integration-open-paas.org (Which have identity = wwang)
--Email rule of Receiver: 
From contains 'ww' --> move message to spam box
![Image](https://user-images.githubusercontent.com/124866146/224646388-1e07b8e7-3009-426c-a7dc-996b1a2a549d.png)

**Reproduce Step:**
1, Sender send an email to Receiver
2, Receiver go to check in inbox / spam box

**Actual:** 
The sent email is not displayed in anywhere of Receiver mailbox. 
The sent email is not displayed in Sent box of Sender

**Expected:** 
It should be displayed at least at inbox (in case not match any email rules) \\ If its matched email rule then it's displayed on spambox of Reciever.

https://user-images.githubusercontent.com/124866146/224647974-25b598d2-09d6-4220-ac25-717e97515029.mp4

**Comment by chibenwa** [comment]
Likely a backend bug. Likely the matching is limited to the email address, not the display name.

Cc @quantranhong1999 can you confirm this and move the ticket to backend?

**Comment by Arsnael** [comment]
Wait cause that might be more linked to the fact that it seems you can't send emails anymore on preprod at the moment actually

**Comment by quantranhong1999** [comment]
The filter with identity' display name works on production.

![image](https://user-images.githubusercontent.com/55171818/224665336-e5dafdc2-f66f-493d-9582-1edd59c5d1ae.png)

![image](https://user-images.githubusercontent.com/55171818/224665698-524363d0-1cfc-4e50-87c4-83c3ac87879e.png)

Not a bug IMO.
