### ISSUE TITLE
[Send Email] User cannot send new email sucessfully

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#1594]
OS: Window / IOS / Android
Device: Laptop / Mobile
TMail version: 0.7.4 - preprod

*Precondition: User already login successfully

*Reproduce step:
1, User click [Compose] button
2, User input correctly email address
3, User input subject
4, User input email body
5, User click [Send] button

**Actual:** User cannot send an email. There is no email/set jmap request 
**Expected:** User can send an email sucessfully.

https://user-images.githubusercontent.com/124866146/224661609-eefe93a9-d69b-4769-81d4-29160d43bbff.mp4

**Comment by QuangHoang1210** [comment]
cc @chibenwa

**Comment by chibenwa** [comment]
For regression I would like to have the SHA-1 off the commit that introduced the defect please.

**Comment by dab246** [comment]
It still works fine on
- Chrome version `111.0.5563.64 `
- MacOS Ventura 13.1

We need to investigate further.

**Comment by chibenwa** [comment]
https://tmail.upn.integration-open-paas.org/ 0.7.4

$ firefox -v
Mozilla Firefox 110.0.1

Same, message not sent
