### ISSUE TITLE
[TMAIL WEB] Can not synchronize new message in background (without disabling cache)

### ISSUE THREAD

**Issue by quantranhong1999** [linagora/tmail-flutter#1597]
### Description
I can not synchronize new messages upon FCM push on TMail web (without disabling the browser cache).

### Expected result
I can synchronize new messages upon FCM push in the normal case (without disabling the browser cache).

### Current behavior
I can not synchronize new messages upon FCM push.

#### Reproduction Steps
[background sync for push not work.webm](https://user-images.githubusercontent.com/55171818/224904041-6f876cad-7cb5-4b56-8b22-bd8d19a47546.webm)

In the first part of the video: I can not sync new messages without selecting disable cache.
In the second part of the video: I can sync new messages when selecting disable cache.

The console logs show the TMail web seems still receive updates from FCM, not sure what FE is missing here...

### Acceptance criteria
I can synchronize new messages upon FCM push on TMail web.

### Context
Env: production (TMail web v 0.7.1)

**Comment by dab246** [comment]
- Is this error always happening?
- I don't know, did you do anything else before sending email?

**Comment by quantranhong1999** [comment]
> I don't know, did you do anything else before sending email?

Nothing. I just F5 and go to composer right away.

> Is this error always happening?

Yes. And even sometimes selecting disable cache does not make the sync work.

**Comment by chibenwa** [comment]
Which browser with which version?

**Comment by quantranhong1999** [comment]
> Which browser with which version?

Google Chrome Version 111.0.5563.64 (Official Build) (64-bit)

**Comment by quantranhong1999** [comment]
Update: send the second mail would get first mail sync, send the third mail would get second mail sync...

**Comment by hoangdat** [comment]
should be resolved with #1631
