### ISSUE TITLE
Improve Spam report banner

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#1598]
### Description

 -> Dismiss should mark emails in the spam box as seen
 -> Option to disable the banner.

**Comment by dab246** [comment]
- Option to disable the banner: Supported on mailbox context menu


![Image](https://user-images.githubusercontent.com/80730648/227838106-500e112f-e8c6-4ccd-b4d8-594350c0bb62.png)

**Comment by chibenwa** [comment]
> Option to disable the banner: Supported on mailbox context menu

Cool!
