### ISSUE TITLE
Remove notification when read

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#1599]
### Description

```
Given BOB receives an email, Bob will get a notification on his phone
When BOB reads the email on his laptop
Then the notification is removed from BOB phone
```

Technically, the email will be updated (marked as read, and the phone can detect it, and remove those notifications.

**Comment by dab246** [comment]
Some issues should be noted here:
1.  Does the server send a new status to `FCM` to be sent to the phone every time it performs `mark as read` actions? Currently I only see this action being performed every time there is a `new email`.
2. On the font-end platform side:
- Notifications on iOS are common to all `push notifications`. It does not contain an `EmailId` to distinguish each email.

**Comment by chibenwa** [comment]
> Does the server send a new status to FCM to be sent to the phone every time it performs mark as read actions?

Yes, an update on the `Email` entity.

**Comment by dab246** [comment]
> > Does the server send a new status to FCM to be sent to the phone every time it performs mark as read actions?
> 
> Yes, an update on the `Email` entity.

Cool, So we can implement on Android platform.

**Comment by QuangHoang1210** [comment]
@dab246 

### Reproduce step:
1, User A send email to user B
2, User B login by PC to read the email
3, User B check notification on his phone

### Actual:
The notification on his phone is not removed. The symbol TeamMail still being displayed with new notification numbers.
I have to go to application and scroll down to reload email list again then notification will be disappeared.

### Expected:
Notification will be removed on phone once email as read. The symbol TeamMail is being displayed no new notification number.



https://user-images.githubusercontent.com/124866146/232632325-6083b958-a37c-43cd-bc02-1e04781f8754.mp4

**Comment by dab246** [comment]
@QuangHoang1210  We have tested it again and it is working fine on version 0.7. You can check again if it still doesn't work we need to discuss this again
