### ISSUE TITLE
Team-Mail should use set `References` and `In-Reply-To` fields

### ISSUE THREAD

**Issue by guimard** [linagora/tmail-flutter#1608]
### Description

When using TMail to transfer/respond, it doesn't set `Reference` and `In-Reply-To` fields. Then for receiver, the mail isn't seen as part of an existing conversation.

### Expected result

Conversation grouped in Thunderbird

### Current behavior

Each message received from Tmail is a new conversation

#### Reproduction Steps

* Configure Thunderbird to group conversations
* Exchange mails from Thunderbird to Team-Mail

### Acceptance criteria

Message well grouped

### Context

Devices, OS : Androïd 12

### Additional information

Mime header should contain:
```
References: <3447ccb0-32c3-c568-8552-6f61f80880c5@linagora.com>
In-Reply-To: <3447ccb0-32c3-c568-8552-6f61f80880c5@linagora.com>
```
where `3447...` is the `Message-Id` of original message

**Comment by chibenwa** [comment]
Good catch @guimard ...

FYI mobile team this is easy to add as JMAP exposes helpers for setting those headers:

```
inReplyTo: String[]|null (immutable) The value is identical to the value of header:In-Reply-To:asMessageIds.
references: String[]|null (immutable) The value is identical to the value of header:References:asMessageIds.
```

Here are the expected behaviours:

```
When I reply to Mail A with `messageId` property set to ABCD, and references ref1, ref2
THEN the reply should have
   - inReplyTo set to ["ABCD"]
   - references set to ["ABCD", "ref1", "ref2"]
```

(preserve previous references...)


```
When I forward  Mail A with `messageId` property set to ABCD, and references ref1, ref2
THEN the forwarded email should have
   - references set to ["ABCD", "ref1", "ref2"]
```

**Comment by chibenwa** [comment]
CF https://www.mail-archive.com/server-dev@james.apache.org/msg72982.html
