### ISSUE TITLE
Group notifications together

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#1609]
### Description

https://user-images.githubusercontent.com/6928740/225349623-01c8a592-35a0-4ee0-93b9-065f75786efd.mp4

[signal-2023-03-15-210043.zip](https://github.com/linagora/tmail-flutter/files/10981350/signal-2023-03-15-210043.zip)

## Actual behaviour

Today I am overwhelmed by notification: this evening I got 30+ notifications! (I did remove some before thinking turning recording on...)

Given That I already read my mail in the app, I have no way to "massively discard" notifications and have to delete them one by one: not user friendly and time consuming...

As such, heavy mail users (me, Alex and Michel for instance) might just turn notifications off, and that is a pity!

## Expected behaviour

Over applications folds notifications together into a notification group: "messenger", "samsung native email app".

This allows discarding them all at once easily!

My bet is that we should try to do the same with TMail...

**Comment by chibenwa** [comment]
That's weird before going to bed the notification were grouped...

https://user-images.githubusercontent.com/6928740/225385270-551acc12-8155-4236-9f91-791e380de9e5.mp4

(expected)

**Comment by dab246** [comment]
> That's weird before going to bed the notification were grouped...
> 
> (expected)

We have implemented `group notification`. Maybe it's delayed for a while. If there is a new message, it will automatically aggregate into 1.
