### ISSUE TITLE
[UI] [Vacation] Start time textbox is displayed smaller once user input invalid time

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#1610]
OS: Window
Browser: firefox, chrome, safari
Device: Laptop
TMail version: 0.7.1
*Note: Only happen on production

*Precondition: User already login sucessfully

*Reproduce Step:
1, User click to Manage Account
2, User click to Vacation left menu
3, User click on Swipe right button
4, User Select Start date
5, User Select start time
6, User click on keyboard button at start time field
7, User input 00 into the text field
8, User click [Ok] button

Actual: System display error message. The border of textbox is smaller
Expected: System display error message. The border of textbox is not changed.

![Image](https://user-images.githubusercontent.com/124866146/225419046-0f61676b-5066-40c2-885b-882bf06070ae.png)

https://user-images.githubusercontent.com/124866146/225419111-53d525c6-1e34-4a14-95b5-460ed0151754.mp4

**Comment by dab246** [comment]
Fixed on flutter `3.7.5`
