### ISSUE TITLE
[Vacation] User got blocking once html type is selected

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#1611]
OS: Window
Device: Laptop
Browser: Chrome / safari / firefox
TMail version: 0.7.4 https://tmail.upn.integration-open-paas.org/#/
Tmail version: 0.7.1 production tmail.linagora.com](https://tmail.linagora.com/#/

*Precondition: User already at Vacation setting screen and Automatically reply is turn on

*Reproduce Step:
1, User click to Html template
2, User scroll down a little bit
3, User click Start time field

Actual: Time selection popup is displayed however user cannot click anything eles (Ok / cancel ,.... etc) 
Expected: Time selection popup is displayed. User action is working normally.

https://user-images.githubusercontent.com/124866146/225432699-eec9cc07-ab98-405d-95a3-02c86c398cea.mp4

**Comment by chibenwa** [comment]
Can we please also open a ticket to just get the rich text composer in there?

My mum would never understand HTML/Plain Text thing...

**Comment by chibenwa** [comment]
Please also put logs from the debugger console.
