### ISSUE TITLE
When network is down, Tmail shouldn't prompt for a password

### ISSUE THREAD

**Issue by guimard** [linagora/tmail-flutter#1613]
### Description

When network is down, Tmail prompts for a password instead fo displaying the real problem. Then user think it's a Tmail only problem (credential lost)

### Expected result

Simple message "Unable to koin server, check your connection"

### Current behavior

Prompts for a password

#### Reproduction Steps

Shut down your DNS and see the result :wink:

### Context

Android 12

**Comment by chibenwa** [comment]
Error management: 500 / socket timeouts are not 401...

**Comment by guimard** [comment]
It seems also that credentials are lost on connection problems
