### ISSUE TITLE
In INBOX, prompted for delete email permanently

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#1623]
### Description

Prompted for delete permanently in INBOX

![Screenshot from 2023-03-20 17-27-17](https://user-images.githubusercontent.com/6928740/226313526-182d14cc-0bc6-41f8-b816-6084f5fdf509.png)

This happens randomly.

### Expected result

![Screenshot from 2023-03-20 17-27-32](https://user-images.githubusercontent.com/6928740/226313652-4e3ac522-de78-47bf-bf8b-f6018fb91a9f.png)

In INBOX always be prompted for "move to trash

### Context

Firefox, tmail.linagora.com, v 0.7.1

### Additional information

frequency, log files,...

**Comment by dab246** [comment]
@chibenwa If possible can you give us `response` information of `Email/query`. We need to determine if the `mailboxIds` property of that email is correct only the `mailboxId` of `INBOX`?.
