### ISSUE TITLE
[Languages & Region] Elements are cut in each other

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#1632]
OS: Android (Android only)
Device: Mobile (Redmi note 9)
TMail version: 0.7.4 (preprod)

*Precondition: User already login successfully

*Reproduce Step:
1, User click to view Manage Account menu
2, User click to [Languages & Region] menu

Actual: The text [Languages & Region] is cut in Setting menu
Expected: It shouldn't cut in each other

![Image](https://user-images.githubusercontent.com/124866146/226421161-610a9851-48a0-4f50-a148-632f1474281d.png)

**Comment by dab246** [comment]
if text max length => Add 3 dots for `Settings`
