### ISSUE TITLE
[TeamMailboxes] User cannot drag and drop to move mailbox

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#1633]
OS: Window
Device: Laptop
TMail version: 0.7.4 (preprod)
TMail version: 0.7.1 (production) Tmail.linagora.com

*Precondition: User already login successfully

*Reproduce Step:
1, User drag and drop an mailbox into another box

Actual: User cannot drag and drop mailbox to move to another one.
Expected:  User can drag and drop to move mailbox to another one.

https://user-images.githubusercontent.com/124866146/226431062-6a3cf3ed-2e17-4a8e-af9c-555e8d0b6fa2.mp4

**Comment by dab246** [comment]
Not supported
