### ISSUE TITLE
[COMPOSER] Keyboard overriding rich text context menu on mobile

### ISSUE THREAD

**Issue by dab246** [linagora/tmail-flutter#1666]
### Desc

- Only on Android

https://user-images.githubusercontent.com/80730648/228116371-41a098a5-3657-4179-a7e8-015cc9a1a1b6.mp4

**Comment by nqhhdev** [comment]
Need merge PR https://github.com/linagora/rich-text-composer/pull/21 to resolve this issue

https://user-images.githubusercontent.com/99852347/228313217-e623dca2-9dde-4411-97a0-bb55c6d8dbb0.webm

**Comment by dab246** [comment]
> Need merge PR [linagora/rich-text-composer#21](https://github.com/linagora/rich-text-composer/pull/21) to resolve this issue

- Please attach video demo in PR https://github.com/linagora/rich-text-composer/pull/21
- Please test case: Click on one of the other fields `(Subject, To, Cc, Bcc)` then click on the `editor` again
