### ISSUE TITLE
[Energy-Economy] Do not request spam on every email I move

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#1667]
### Description

Drag and drop an email to move it.

TeamMail always requests the Spam status.

![Screenshot from 2023-03-28 13-10-31](https://user-images.githubusercontent.com/6928740/228144930-88beb4a0-6c34-4d19-bcb3-a6688e066465.png)

### Expected result

Minimize the count of requests done: spam status report can be built from mailbox list in the cache.

**Comment by chibenwa** [comment]
Also happens when I open a mail

**Comment by hoangdat** [comment]
> Also happens when I open a mail

yes, maybe a pooling strategy for spam report

**Comment by dab246** [comment]
### Root causes

- Currently always call `Mailbox/query` after `Mailbox/changes` called

### Suggestion

- Call `getAllMailboxCache` (local) to get `Spam mailbox` after `Mailbox/changes` called

**Comment by chibenwa** [comment]
I agree with the suggestion
