### ISSUE TITLE
[ManageAccount][Fowarding] Email validation is not working well

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#1677]
OS: Window / IOS / ANDROID
Device: Laptop / Mobile
TMail version: 0.7.6

*Precondition: User already login successfully

### *Reproduce Step:
1, User click on Account Manager
2, User click on Fowarding
3, User input correctly email format then click [+Add Recipient] button
4, User leave input fields being blank then click [+Add Recipient] button

### **Actual:** 
- System display error message: Incorrect email format. User cannot add recipient.
- System display message: The email has been added from recipient list.

### **Expected:** 
- In case User input wrong email format and he press Enter -> System detect that as red tag.
- The msg validation only display when user click on [+Add Recipient] button

https://user-images.githubusercontent.com/124866146/228794783-000b32b1-99bb-4cf4-a8d1-a7158a912515.mp4

**Comment by hoangdat** [comment]
this bug similar with `to``cc`, `bcc` in composer, when not select the input as a tag then `add recipient` -> input was not consider as an email. Not a regression.

**Comment by chibenwa** [comment]
Please also takethe time to cosider `alice@localhost` as a valid email address

**Comment by QuangHoang1210** [comment]
@nqhhdev missing AC: alice@localhost as a valid email address

**Comment by chibenwa** [comment]
> Or all email with format 'email@localhost' as valid one !?

Of course all...
