### ISSUE TITLE
[Identity] Button 'X' : Sometime it's hidden, sometime it's displayed

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#1679]
OS: IOS / ANDROID
Device: Mobile
TMail version: 0.7.6

*Precondition: User already login successfully

### *Reproduce Step:
1, User click on Manage Account
2, User click on Profile
3, User click on [+Create new identity] button
4, Scroll down or click on Signature text area

### **Actual:** 
Sometime 'X' button is displayed. Sometime it's not.

### **Expected:** 
It should be displayed stable

https://user-images.githubusercontent.com/124866146/228798875-36245e87-b503-462d-b5e8-ad64e4815c55.mp4

**Comment by chibenwa** [comment]
@QuangHoang1210 can you also open a bug report for this?

**Comment by QuangHoang1210** [comment]
This issue same on Identity screen which I discussed on daily meeting.
Please take a look. @dab246  cc @hoangdat  @chibenwa 

1, The Cancel/Save button is hidden
https://github.com/linagora/tmail-flutter/issues/1694

2, There are 2 cursors on Create Identity screen
https://github.com/linagora/tmail-flutter/issues/1693
