### ISSUE TITLE
[Identity] The email text at 'Reply:' fields is display as three dot

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#1680]
OS: IOS / ANDROID
Device: Mobile
TMail version: 0.7.6

*Precondition: User already login successfully

### *Reproduce Step:
1, User click on Manage Account
2, User click on Profile
3, User click on [+Create new identity]
3, Scroll down a bit and focus on Reply: field
4, User select human@-resources@upn.integraion-open-paas.org email from option droplist down

### **Actual:** 
System display the selected option  with three dot || **Example: "human@-..."**

### **Expected:** 
it should be displayed same other selected option

https://user-images.githubusercontent.com/124866146/228800298-443e7d0e-34e4-49da-b908-c20d21a7a3a6.mp4

**Comment by dab246** [comment]
Same #1779
