### ISSUE TITLE
[UX] [Improve] [Vacation] There is no difference between Label with Option which make user feel confuse

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#1683]
OS: IOS / ANDROID
Device: Mobile
TMail version: 0.7.6

*Note: On some smaller screen on mobile of another device, the label "Message" is looking so close with the option "Plain Text" and "Html"

### *Reproduce Step:
1, User click on Manage Account
2, User click on Vacation
3, User swipe on Auto reply mode
3, User scroll down to focus on Message text area.

### **Actual:** 
The label "Message" is so close with 2 options: "Plain Text" and "Html". It make user feel confuse that "Message" will be an option?

### **Expected:** 
It should highlight the label "Message". Maybe using Bold text style for the title (label) of each section.
Or we should reduce the text size of 2 options "Plain Text" and "Html".

![Image](https://user-images.githubusercontent.com/124866146/228805769-940621df-a4f7-488f-917c-bdd5349860e6.png)

https://user-images.githubusercontent.com/124866146/228805845-bb72da4d-c22c-4ac0-aa56-9cf4a57f71ed.mp4

**Comment by chibenwa** [comment]
Noticed by a customer.

Please make plain text the default option quickly...

![Screenshot from 2023-07-05 13-56-21](https://github.com/linagora/tmail-flutter/assets/6928740/842cb372-7773-4891-84cd-c4f115dd5b80)

IMPORTANT: from the HTML version deduce the plain text version before creating it server side.

Cc @hoangdat

**Comment by hoangdat** [comment]
So now, we will remove `Plain text` option?

**Comment by chibenwa** [comment]
> So now, we will remove Plain text option?

Yes

And fill plain text option by removing HTML tags of the HTML part.

**Comment by QuangHoang1210** [comment]
Passed
