### ISSUE TITLE
[Identity] User click on blank area but system redirect user to 404 not found page <weird link>

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#1684]
OS: Window
Device: Laptop
TMail version: 0.7.6

*Precondition: There is one Identity is created with 2 links in the signature content
*Data test: User firstname31.surname31@upn.integration-open-paas.org

### *Reproduce Step:
1, User click on Manage Account
2, User click on Profile
3, User select Identity that mentioned in Precondition
4, User click on blank area near the link <following image or video>

### **Actual:** 
System redirect user to this link: https://www.google.com/https://www.w3schools.com/ [404 not found]

### **Expected:** 
1, Underline the link
2, System only redirect user to the link once user click exactly to the link.

![Image](https://user-images.githubusercontent.com/124866146/228808345-8340a928-196c-449d-96ab-7d52b815a564.png)

![Image](https://user-images.githubusercontent.com/124866146/228808421-d3b3c0c2-c964-4af6-a310-2561afade08b.png)

https://user-images.githubusercontent.com/124866146/228808019-abcf9923-5544-4159-a199-c28def3d5fb0.mp4

**Comment by chibenwa** [comment]
Share the raw html of this signature.

To determine where the problem comes from...
