### ISSUE TITLE
[Compose] User cannot scroll down to start writing email in specific behaviour

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#1686]
OS: Window
Device: Laptop
TMail version: 0.7.6

*Precondition: There is at least 1 attachment showing
*Data test: User firstname31.surname31@upn.integration-open-paas.org

### *Reproduce Step:
1, User click on [Compose] button
2, User click on CC
3, User click on BCC
4, User scroll down or click into email body field

### **Actual:** 
User cannot scroll down to view email body so he cannot start writing an email.

### **Expected:** 
User can scroll down to view email body to start writing an email.

https://user-images.githubusercontent.com/124866146/228811251-f2b53c14-6889-449c-bd5a-c2263440d353.mp4

**Comment by QuangHoang1210** [comment]
@chibenwa Mine 1920x1080 :D

**Comment by chibenwa** [comment]
I can reproduce only with a resized window

![Screenshot from 2023-03-31 11-30-36](https://user-images.githubusercontent.com/6928740/229023042-1195ada7-cec2-43f2-9093-19afd251d6db.png)

**Comment by hoangdat** [comment]
@QuangHoang1210 please create design ticket

**Comment by hoangdat** [comment]
@QuangHoang1210please provide design ticket

**Comment by QuangHoang1210** [comment]
@hoangdat  yes it is https://ci.linagora.com/linagora/lgs/design/-/issues/420

**Comment by dab246** [comment]
Improvement at #2116
