### ISSUE TITLE
[Identity] [Crashed] Tmail UI is broken after user create identity successfully by html style

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#1688]
OS: Window
Device: Laptop
TMail version: 0.7.6

*Precondition: User created identity with html style in signature
*Data test: 
- User firstname31.surname31@upn.integration-open-paas.org
- html source: 
`<!DOCTYPE html>
<html>
<body>

<h2 title="I'm a header">The title Attribute</h2>

<p title="I'm a tooltip">Mouse over this paragraph, to display the title attribute as a tooltip.</p>

</body>
</html>`

### *Reproduce Step:
1, User click on Manage Account
2, User click on Profile
3, User click on [+Create Identity] button
4, User copy an html into signature
5, User click [Create] button
6, User click Team Mail logo to back to homepage 

### **Actual:** 
UI is broken. The content from html signature is still display overlaps other element.

![Image](https://user-images.githubusercontent.com/124866146/228814154-3489400a-00c8-472b-bf1f-b5d0904c1814.png)

https://user-images.githubusercontent.com/124866146/228814221-10e3d373-abc2-4c15-b064-b45f67fe06c8.mp4

### **Expected:** 
User can go back to homepage smoothly. UI is not broken

**Comment by chibenwa** [comment]
Please specify the browser
