### ISSUE TITLE
Unable to display mailbox created from IMAP

### ISSUE THREAD

**Issue by ducnm0711** [linagora/tmail-flutter#1691]
### Description

Context:
- From IMAP create new mail "Archive" and 3 sub mailbox Archive / Aggregate, Forensic, Invalid

![image](https://user-images.githubusercontent.com/59911858/229013461-17a9829d-d2c5-4d60-a5dd-58bc19a2100e.png)

### Expected result

Able to see content of sub mailboxes
![image](https://user-images.githubusercontent.com/59911858/229013558-7a2c68da-05de-4d37-be81-031a9df45f80.png)

### Current behavior

Empty 

![image](https://user-images.githubusercontent.com/59911858/229013632-27803be3-2b25-4a8b-9aa2-7246f6ef17b6.png)

**Comment by chibenwa** [comment]
`> Settings > Mailbox visibility`

**Comment by chibenwa** [comment]
Which Mail User Agent are you using? I suppose it do not subscribes to mailboxes...

I did not reproduce using Thunderbird.

**Comment by chibenwa** [comment]
Because of parsedmarc client
