### ISSUE TITLE
Focus lost when inout recipient

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#1692]
### Description

Around half of the time when I validate a recipient, focus is lost.

### Expected result

After pressing enter to input a recipient, the focus should still be in this field, allowing me to inputone more recipient.

### Current behavior

https://user-images.githubusercontent.com/6928740/229023188-a9ef39f7-ff92-4ac0-abf6-f412fe94c5d9.mp4

### Context
tmail.linagora.com, firefox, v0.7.1

**Comment by dab246** [comment]
Same #1527 and Fixed at #1541
