### ISSUE TITLE
[Identity] There are 2 cursors on Create Identity screen

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#1693]
OS: IOS / ANDROID
Device: Mobile
TMail version: 0.7.6

*Precondition: User already login successfully

### *Reproduce Step:
1, User click on Manage Account
2, User click on Profile
3, User click on [+Create new identity] button
4, Click on bcc
5, Scroll down or click on Signature text area

### **Actual:** 
There are 2 cursors:
- Blue cursor at Bcc
- Black cursor at Signature text area

### **Expected:** 
It should be displayed only one cursor

https://user-images.githubusercontent.com/124866146/228798875-36245e87-b503-462d-b5e8-ad64e4815c55.mp4

**Comment by chibenwa** [comment]
Android also on composer (0.7.1)
