### ISSUE TITLE
[Identity] The Cancel/Save button is hidden

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#1694]
OS: IOS / ANDROID
Device: Mobile
TMail version: 0.7.6

*Precondition: User already login successfully

### *Reproduce Step:
1, User click on Manage Account
2, User click on Profile
3, User click on [+Create new identity] button
4, Scroll down or click on Signature text area
5, Keep scroll down again

### **Actual:** 
There is a blank space hide these buton [Cancel] / [Save]

### **Expected:** 
The buttons should be displayed normally

https://user-images.githubusercontent.com/124866146/228798875-36245e87-b503-462d-b5e8-ad64e4815c55.mp4

**Comment by chibenwa** [comment]
Duplicates https://github.com/linagora/tmail-flutter/issues/1658 ?

**Comment by QuangHoang1210** [comment]
@chibenwa  no I think it's separately issue. On mobile there is a space blank hide the button
