### ISSUE TITLE
[EmailRule] Receiver cannot view email detail because it is missing after it's processed by email rule of him

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#1695]
OS: IOS / ANDROID / WINDOW
Device: Mobile / Laptop
TMail version: 0.7.6

*Precondition: User config both email rule same time
- move trash: All email from address which contains 'first' is moved to trash
- move spam: All email from address which contains 'first' is moved to spam

*Data test:
- Receiver who set email rule: Using account firstname31.surname31@upn.integration-open-paas.org
- Sender: Using account firstname27.surname27@upn.integration-open-paas.org

### *Reproduce Step:
1, Sender send an email to Receiver that have email content as 'Move trash or spam'
2, Receiver click to view detail of that email

### **Actual:** 
Receiver can preview the short detail of email on thread-view however he cannot see email details on details-view.
The email details is missing.

### **Expected:** 
Receiver can see email details normally.
The email details is not missing.

https://user-images.githubusercontent.com/124866146/229031256-8c115ce6-8f00-4830-b36d-8aed14ebf056.mp4

**Comment by chibenwa** [comment]
As this is a display bug please share the underlying EML.

**Comment by QuangHoang1210** [comment]
@chibenwa  it's quite long a bit to load the email details. I can see it after waiting a few minute. Maybe I got slow connection internet yesterday when I met this issue.

Today It's display well when I reproduce it.

So I already close this one.
