### ISSUE TITLE
[Vacation] Error font on Subject of automatically reply email

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#1696]
OS: IOS / ANDROID
Device: Mobile
TMail version: 0.7.6

*Precondition: User config the automatically reply email on vacation setting:
- Receiver: Subject as 'Tao dang di nghi mat thêm 31'

![Image](https://user-images.githubusercontent.com/124866146/229032876-6f793ef6-04b1-40bd-9959-15638a26abdd.png)

*Data:
- Receiver who config vacation mode: firstname31.surname31@upn.integration-open-paas.org
- Sender: firstname27.surname27@upn.integration-open-paas.org

### *Reproduce Step:
1, Sender send an email to Receiver who on vacation mode
2, Sender click to view the automatically reply from Receiver

### **Actual:** 
The subject is displayed as error font 'Tao dang di nghi mat th??m 31'

![Image](https://user-images.githubusercontent.com/124866146/229032859-1e5a4e35-1110-48b5-a3d1-8721ae42cec3.png)

### **Expected:** 
The subject should be display as correct font

https://user-images.githubusercontent.com/124866146/229032954-d4a6b6d3-92a3-427b-9846-6e080030f647.mp4

**Comment by chibenwa** [comment]
Interesting!

@Arsnael this looks like a backend bug (missing mime encoding).

I'll check after lunch.

**Comment by chibenwa** [comment]
https://issues.apache.org/jira/browse/JAMES-3898

**Comment by chibenwa** [comment]
CF https://github.com/linagora/james-project/issues/4756
