### ISSUE TITLE
[Search] Expected total email is not correct in the searching result

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#1697]
OS: IOS / ANDROID / WINDOW
Device: Mobile / LAPTOP
TMail version: 0.7.6

*Precondition: There are 6 emails which contains 'quang'

*Data:
- Receiver: firstname28.surname28@upn.integration-open-paas.org

### *Reproduce Step:
1, Input 'quang' into the search box
2, Click on search button

### **Actual:** 
There are 4 email in the searching result

![Image](https://user-images.githubusercontent.com/124866146/229036493-60777fac-3010-40d7-bde5-1a5111839230.png)

### **Expected:** 
It should be 6 email in the searching result

![Image](https://user-images.githubusercontent.com/124866146/229036429-84b63531-f6dc-4d04-ae0c-da620ae2a63b.png)

https://user-images.githubusercontent.com/124866146/229036537-71117135-31e5-4dca-bc83-0f7a20807c87.mp4

**Comment by QuangHoang1210** [comment]
### Payload request:

`{
  "using": [
    "urn:ietf:params:jmap:core",
    "urn:ietf:params:jmap:mail",
    "urn:apache:james:params:jmap:mail:shares"
  ],
  "methodCalls": [
    [
      "Email/query",
      {
        "accountId": "a1940ead3d56331661e160706b12fe25f63fe306901965191e07e87df007b4ac",
        "filter": {
          "operator": "AND",
          "conditions": [
            {
              "text": "quang"
            }
          ]
        },
        "sort": [
          {
            "isAscending": false,
            "property": "receivedAt"
          }
        ],
        "limit": 20
      },
      "c0"
    ],
    [
      "Email/get",
      {
        "accountId": "a1940ead3d56331661e160706b12fe25f63fe306901965191e07e87df007b4ac",
        "#ids": {
          "resultOf": "c0",
          "name": "Email/query",
          "path": "/ids/*"
        },
        "properties": [
          "id",
          "subject",
          "from",
          "to",
          "cc",
          "bcc",
          "keywords",
          "size",
          "receivedAt",
          "sentAt",
          "preview",
          "hasAttachment",
          "replyTo",
          "mailboxIds"
        ]
      },
      "c1"
    ]
  ]
}`


### Payload Response:

`{
  "sessionState": "2c9f1b12-b35a-43e6-9af2-0106fb53a943",
  "methodResponses": [
    [
      "Email/query",
      {
        "accountId": "a1940ead3d56331661e160706b12fe25f63fe306901965191e07e87df007b4ac",
        "queryState": "96692506",
        "canCalculateChanges": false,
        "ids": [
          "21fd8c80-cf88-11ed-90c9-99a9242b6bc0",
          "ef6ee430-cf87-11ed-82d5-cb3ad33d33b8",
          "e1604230-cf87-11ed-90c9-99a9242b6bc0",
          "d3482a50-cf87-11ed-82d5-cb3ad33d33b8"
        ],
        "position": 0
      },
      "c0"
    ],
    [
      "Email/get",
      {
        "accountId": "a1940ead3d56331661e160706b12fe25f63fe306901965191e07e87df007b4ac",
        "notFound": [],
        "state": "a25673b0-cf88-11ed-a749-ef9a44ef5a9e",
        "list": [
          {
            "replyTo": [
              {
                "email": "firstname30.surname30@upn.integration-open-paas.org"
              }
            ],
            "preview": "sadasdsads ád sad sa d á d dsa Quang1210 QuangDepzai Quang1102 HoangNhatQuang",
            "to": [
              {
                "email": "firstname28.surname28@upn.integration-open-paas.org"
              },
              {
                "name": "firstname4166.surname4166@upn.integration-open-paas.org",
                "email": "firstname4166.surname4166@upn.integration-open-paas.org"
              }
            ],
            "id": "21fd8c80-cf88-11ed-90c9-99a9242b6bc0",
            "mailboxIds": {
              "faba4610-30a9-11eb-9a8d-254ee97830fe": true
            },
            "from": [
              {
                "name": "Firstname30 Surname30",
                "email": "firstname30.surname30@upn.integration-open-paas.org"
              }
            ],
            "keywords": {},
            "receivedAt": "2023-03-31T05:51:51Z",
            "sentAt": "2023-03-31T05:51:38Z",
            "hasAttachment": true,
            "subject": "adadadqj Quang Hoang HoangNhatQuang",
            "size": 2188047
          },
          {
            "replyTo": [
              {
                "email": "firstname30.surname30@upn.integration-open-paas.org"
              }
            ],
            "preview": "asdlasnlkdnsad asdlsald;;án l;dlasnd; n ;askd Quang1210 QuangDepzai Quang1102 HoangNhatQuang",
            "to": [
              {
                "email": "firstname28.surname28@upn.integration-open-paas.org"
              }
            ],
            "id": "ef6ee430-cf87-11ed-82d5-cb3ad33d33b8",
            "mailboxIds": {
              "faba4610-30a9-11eb-9a8d-254ee97830fe": true
            },
            "from": [
              {
                "name": "Firstname30 Surname30",
                "email": "firstname30.surname30@upn.integration-open-paas.org"
              }
            ],
            "keywords": {},
            "receivedAt": "2023-03-31T05:50:26Z",
            "sentAt": "2023-03-31T05:50:14Z",
            "hasAttachment": false,
            "subject": "kmkmkmkmkmkm Quang",
            "size": 1438
          },
          {
            "replyTo": [
              {
                "email": "firstname30.surname30@upn.integration-open-paas.org"
              }
            ],
            "preview": "Quang1210 QuangDepzai Quang1102 HoangNhatQuangsm,nálfsafmlmasf sfjas 'fj' asjfp' á 'f'sak 'fkas 'kf 'askf' ask'",
            "to": [
              {
                "email": "firstname28.surname28@upn.integration-open-paas.org"
              }
            ],
            "id": "e1604230-cf87-11ed-90c9-99a9242b6bc0",
            "mailboxIds": {
              "faba4610-30a9-11eb-9a8d-254ee97830fe": true
            },
            "from": [
              {
                "name": "Firstname30 Surname30",
                "email": "firstname30.surname30@upn.integration-open-paas.org"
              }
            ],
            "keywords": {},
            "receivedAt": "2023-03-31T05:50:02Z",
            "sentAt": "2023-03-31T05:49:51Z",
            "hasAttachment": false,
            "subject": "Quang Cuc ky Dep zai",
            "size": 1508
          },
          {
            "replyTo": [
              {
                "email": "firstname30.surname30@upn.integration-open-paas.org"
              }
            ],
            "preview": "Quang1210 QuangDepzai Quang1102 HoangNhatQuang",
            "to": [
              {
                "email": "firstname28.surname28@upn.integration-open-paas.org"
              }
            ],
            "id": "d3482a50-cf87-11ed-82d5-cb3ad33d33b8",
            "mailboxIds": {
              "faba4610-30a9-11eb-9a8d-254ee97830fe": true
            },
            "from": [
              {
                "name": "Firstname30 Surname30",
                "email": "firstname30.surname30@upn.integration-open-paas.org"
              }
            ],
            "keywords": {},
            "receivedAt": "2023-03-31T05:49:39Z",
            "sentAt": "2023-03-31T05:49:31Z",
            "hasAttachment": false,
            "subject": "Quang Đẹp Trai - Quang Dep Zai",
            "size": 1321
          }
        ]
      },
      "c1"
    ]
  ]
}`

**Comment by chibenwa** [comment]
MMMMMMM the day you come at the office we will have a course on full text search, analysis and tokenization.

For now remeber that `quang` will match `quang xxx` but not `QuangXXX`.
