### ISSUE TITLE
[Story] Mockup for Team Mail Calendar events

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#1700]
### Calendar events thread-view

![Image](https://user-images.githubusercontent.com/124866146/229365003-93d58c56-84b9-464f-8c3c-0ba8094bc8c9.png)

### Calendar events / Email details-view / NEW INVITATION

![Group 4 (3)](https://user-images.githubusercontent.com/68209176/233356030-b19a98fb-5c04-473b-bca0-69899c5f3efb.png)

### Calendar events / Email details-view / UPDATED INVITATION

![Frame 5](https://user-images.githubusercontent.com/68209176/233358507-47cf2695-23c5-45f5-a0fa-58fe1efebd72.png)

### Calendar events / Email details-view / CANCELED INVITATION

![Group 5 (7)](https://user-images.githubusercontent.com/68209176/233358729-43c9b307-f547-4719-ae47-449b72c6a2b8.png)

**Comment by chibenwa** [comment]
Last CoTeamMail I think you did not get it, but you are missing the point...

Please put a big grey square on the body: Don;t make any assumption on it.

The "calendar widget" should contain the information of what happen (cancelation, updates, invitation).

That is not the case here.
