### ISSUE TITLE
[CYRUS] Preprovision requested folder if missing

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#1705]
### Description

Connecting on TeamMail on Cyrus, we only have `Inbox` folder.

All folders like `Drafts`, `Trash`, `Sent`, etc... are missing, causing multiple issues with TeamMail.

### Expected result

I would expect TeamMail to create those folders if missing, with appropriate roles.

(I did create the folders in TMail then manually changed their roles [1])

[1]:

```
interview1@interview1-HP-ProBook-440-G6:~/Documents/cyrus-postfix-docker$ curl -X POST      -H "Content-Type: application/json"      -H "Accept: application/json"      --user example:example      -d '{"using": [ "urn:ietf:params:jmap:core", "urn:ietf:params:jmap:mail" ],"methodCalls": [["Mailbox/set",{"update": {"3xeoz8bce70x5y3232tbthcv": {"role": "drafts"}}},"c1"]]}'  http://localhost:8008/jmap/ | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   419  100   249  100   170   3036   2073 --:--:-- --:--:-- --:--:--  5109
{
  "methodResponses": [
    [
      "Mailbox/set",
      {
        "oldState": "29",
        "newState": "30",
        "created": null,
        "updated": {
          "3xeoz8bce70x5y3232tbthcv": null
        },
        "destroyed": null,
        "notCreated": null,
        "notUpdated": null,
        "notDestroyed": null,
        "accountId": "example"
      },
      "c1"
    ]
  ],
  "sessionState": "0"
}
```

### Current behavior

Those folders are never provisionned.

**Comment by dab246** [comment]
> ### Description
> Connecting on TeamMail on Cyrus, we only have `Inbox` folder.
> 
> All folders like `Drafts`, `Trash`, `Sent`, etc... are missing, causing multiple issues with TeamMail.
> 
> ### Expected result
> I would expect TeamMail to create those folders if missing, with appropriate roles.
> 
> (I did create the folders in TMail then manually changed their roles [1])
> 
> [1]:
> 
> ```
> interview1@interview1-HP-ProBook-440-G6:~/Documents/cyrus-postfix-docker$ curl -X POST      -H "Content-Type: application/json"      -H "Accept: application/json"      --user example:example      -d '{"using": [ "urn:ietf:params:jmap:core", "urn:ietf:params:jmap:mail" ],"methodCalls": [["Mailbox/set",{"update": {"3xeoz8bce70x5y3232tbthcv": {"role": "drafts"}}},"c1"]]}'  http://localhost:8008/jmap/ | jq
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100   419  100   249  100   170   3036   2073 --:--:-- --:--:-- --:--:--  5109
> {
>   "methodResponses": [
>     [
>       "Mailbox/set",
>       {
>         "oldState": "29",
>         "newState": "30",
>         "created": null,
>         "updated": {
>           "3xeoz8bce70x5y3232tbthcv": null
>         },
>         "destroyed": null,
>         "notCreated": null,
>         "notUpdated": null,
>         "notDestroyed": null,
>         "accountId": "example"
>       },
>       "c1"
>     ]
>   ],
>   "sessionState": "0"
> }
> ```
> 
> ### Current behavior
> Those folders are never provisionned.

HI @chibenwa I cannot update `role` to `outbox` or `Spam` folder. I get an `invalidProperties` error. Other default folders still work normally like `Sent/Trash/Drafts`. Please see `request` and `response` below:

```
root@808269e61bda:/# curl -X POST      -H "Content-Type: application/json"      -H "Accept: application/json"      --user example:example      -d '{"using":["urn:ietf:params:jmap:core","urn:ietf:params:jmap:mail"],"methodCalls":[["Mailbox/set",{"update":{"8dcm9kzl9pykyj9yw9oijerw":{"role":"Outbox"},"7lze2m1q9pn91nkwuadvgs81":{"role":"Spam"}}},"c1"]]}'      http://localhost:8008/jmap/ | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   578  100   373  100   205  31083  17083 --:--:-- --:--:-- --:--:-- 48166
{
  "methodResponses": [
    [
      "Mailbox/set",
      {
        "oldState": "34",
        "newState": "34",
        "created": null,
        "updated": null,
        "destroyed": null,
        "notCreated": null,
        "notUpdated": {
          "8dcm9kzl9pykyj9yw9oijerw": {
            "type": "invalidProperties",
            "properties": [
              "role"
            ]
          },
          "7lze2m1q9pn91nkwuadvgs81": {
            "type": "invalidProperties",
            "properties": [
              "role"
            ]
          }
        },
        "notDestroyed": null,
        "accountId": "example"
      },
      "c1"
    ]
  ],
  "sessionState": "0"
}
```

**Comment by chibenwa** [comment]
Please do not set role.
Just fallback to the mailbox name : outbox

**Comment by hoangdat** [comment]
Ok, create Spam without role.
