### ISSUE TITLE
Sorting search results for web

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#1709]
# Summary

By default search results are sorted by date by default.

I should be able to sort search requests.

In the advanced search, I have a button `Sorting options`.

When I click on it, I have several options:

 - By date, descending (default)
 - By date, ascending
 - By relevance (No sort)
 - Sort by sender (A-Z) ascending and decending
 - Sort by subject (A-Z) ascending and descending
 
The option is applied to the search result order.

Special attention needs to be taken to the infinite scroll which can no longer be date based (need to rely on offset + limit in Email/query)

- On Search result screen,  I can see the current selected sort in top right of the email list. This button only appears in search result screen, not in any folder view. 
- When click on it, I can see the list of sorting options and when I select another option, it will be applied to the results list. 

### Mockups 

![Group 165](https://github.com/linagora/tmail-flutter/assets/68209176/87760218-fe1f-4065-9e64-faf8c3cc0f6c)

![Group 166](https://github.com/linagora/tmail-flutter/assets/68209176/db14a646-6bd8-46b1-879f-0b236b7b8c94)

**Comment by chibenwa** [comment]
Discussed with @mmaudet , needs to resume discussions of this.

**Comment by chibenwa** [comment]
@dieptran88 thanks for proposing a design for this, and ask the design team.

**Comment by dieptran88** [comment]
I updated the mockups @hoangdat @chibenwa

**Comment by chibenwa** [comment]
Good to me!

**Comment by dab246** [comment]
## Desc
- Add `sortOrder` property to `SimpleSearchFilter` (mobile) and `SearchEmailFilter` (web)
