### ISSUE TITLE
Empty trash: folder action

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#1712]
# Summary

From within the mailbox list view, I want to have a `"Empty Trash"` action exposed to me.

![Screenshot from 2023-04-04 14-32-14](https://user-images.githubusercontent.com/6928740/229720539-8e19bc80-0e10-44df-a444-5d179a374639.png)

**Comment by hoangdat** [comment]
duplicated #1984

**Comment by dab246** [comment]
Same #1792
