### ISSUE TITLE
Refreshing mailbox: display an animation wwhile loading

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#1714]
### Description

Right now, when I refresh a mailbox, there is no animation to show me that the loading is pending.

This can be frustrating if I do not know if loading is pending or if I am really up to date.

A little loader animation could be nice.

Example:

Uploading loading-animation.mp4…

**Comment by dab246** [comment]
@chibenwa Please update the video example again. It is failing to upload successfully.

**Comment by chibenwa** [comment]
https://github.com/linagora/tmail-flutter/assets/6928740/f3cce216-2bf6-4464-8a56-2b525d720879

**Comment by chibenwa** [comment]
The issue is sometime the "loading animation" shows but also sometime not...
