### ISSUE TITLE
Helper to easily unsubscribe from email / mailing lists

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#1718]
# Summary

Commercial email and email from mailing lists often include information to easily unsubscribe.

EG:

```
List-Unsubscribe: <mailto:topdevvn+unsubscribe_637edc2ee899a039346076@gmail.com>,
 <https://hr.topdev.vn/email/unsubscribe/637edc2ee899a039346076>
```

In `Email detailed view` when I open such email, add an option to easily unsubscribe from this email.

https links should be prefered, but mailto links, if they are the only available, should be handled too.

# Story
### Description

- Given that I am TMail user
- After log-in successfully, I can see the list of emails of Inbox folder 
- If I signed up on a site that sends lots of emails, like promotions or newsletters, and the sender provides in their email content an unsubscribe link, then TMail will display a more convenient way to unsubscribe from the mailing list:
- On email detail screen, I can see a hyperlink "Unsubscribe" next to the sender's name, When I click on this link, I can see a popup asking:"Are you sure you'd like to stop receiving similar messages from [Sender's name]?
-  I click button Unsubscribe in the popup to confirm:
   - If the unsubscribe is a https link, then the system will send the unsubscribe-confirmation to the sender through this link without opening it 
   - If the unsubscribe is a mailto link, then the system will auto-generate a message with pre-filled fields as included in the mailto link then send to the sender to unsubscribe. 
- After unsubscribe successfully, there will be a toast message: "Unsubscribed from this mailing list"
- Now When I opened the message that I just unsubscribe before, the hyperlink:"Unsubscribe" next to sender name is not displayed anymore, and there will be a text under saying :"You unsubscribe from [Sender's email address]".

### Screenshots
Web: 

![Group 158](https://github.com/linagora/tmail-flutter/assets/68209176/9e8115c7-9fa7-48ee-b411-73c05dfbf1ed)

![Group 159](https://github.com/linagora/tmail-flutter/assets/68209176/876c8904-040f-4247-b05f-b02edec0a90b)

![Group 160](https://github.com/linagora/tmail-flutter/assets/68209176/cc96142f-1257-4ab6-9323-3bb09114d9eb)

Mobile:

![image](https://github.com/linagora/tmail-flutter/assets/68209176/04c07c89-11d0-46df-a28e-b9ebcfb12578)  ![image](https://github.com/linagora/tmail-flutter/assets/68209176/b04e73cd-3d24-4996-ab4e-9e0c988dc81d)

![image](https://github.com/linagora/tmail-flutter/assets/68209176/cd8d4741-604c-4dbe-8643-f3518342d49b)

**Comment by hoangdat** [comment]
- [ ] find the link in `List-Unsubscribe`
- [ ] find the link via html dom

**Comment by QuangHoang1210** [comment]
Reopened this ticket cause these issues:
https://github.com/linagora/tmail-flutter/issues/2390
https://github.com/linagora/tmail-flutter/issues/2391
