### ISSUE TITLE
Deleted Message Vault JMAP extension

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#1719]
# Summary

As a user I want to restore messages that I did delete by mistake.

James possesses an extension to retain (for a configurable amount of time) messages that had been deleted. This can be used by users to retrieve the message they deleted by mistake.

Privacy is ensured by limiting restoring more than 5 (configurable) messages. An attacker cannot restore and access all deleted messages.

Screenshot on OpenPaaS:

![93195375-64a42480-f773-11ea-813c-7ea9b47f8ac6](https://user-images.githubusercontent.com/6928740/229741471-6b4df15f-3580-49fa-958b-3504f8fd484f.png)

There is a trash action: recover deleted messages.

When I click on `recover deleted messages` action, the `recovery dialog` opens. It have fields enabling me to say which email to restore:
 - Deletion date (date picker)
 - Reception date (date picker)
 - Terms contained in the subject
 - Recipient
 - Sender
 - hasAttachment

A message explains that the message recovery is in progress and might take time...

When restoring deleted messages, a system folder `Deleted-Messages` is added to the system folders, with restored emails in it.

**Comment by hoangdat** [comment]
@dab246 @nqhhdev

**Comment by hoangdat** [comment]
Story: https://github.com/linagora/tmail-flutter/blob/master/docs/stories/EPIC-Restore%20deleted%20messages/TF-1719-User-can-restore-deleted-messages.md

**Comment by hoangdat** [comment]
Design https://www.figma.com/file/rRVxJpCu1G22D0jqyvK7I9/TeamMail?type=design&node-id=12542-18611&mode=design

**Comment by hoangdat** [comment]
@QuangHoang1210, please spent time to verify this
