### ISSUE TITLE
Improve Email rules

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#1728]
# Summary

Today email rules are rather limited.

We can improve this by...

Adding more actions:

 - https://github.com/linagora/tmail-flutter/issues/1727 (separated issue)
 - Mark as read
 - Mark as important
 - Report as Spam (shortcut for move into spam mailbox)
 - Reject

User should be able to select several condition and link them by logical AND `all of`, logical OR `any of`.

User should be able to select several actions (all actions applies).

CF backend epic: https://github.com/linagora/james-project/issues/4568

## Related EPIC

* TODO: {link}

## Definition

TODO

## Screenshots

None

## Misc

None

**Comment by hungphan227** [comment]
The backend api has been updated to combine rule condtions. Refer to the ticket https://github.com/linagora/tmail-backend/issues/757

**Comment by hoangdat** [comment]
done in 0.11.3
