### ISSUE TITLE
[Bug]: Filter by date not applied to search results

### ISSUE THREAD

**Issue by tprudentova** [linagora/tmail-flutter#1736]
Bug details
- Environment(version): tmail.linagora.com, v 0.7.6, Google Chrome
- Steps to reproduce:
1.	Type any search request to the search box
2.	Apply filter “with attachment”, date is filtered “last 7 days” by default
3.	Search
4.	Delete everything from the search box and click enter 
5.	The filter says “last 7 days” but letters from all time are displayed
- Expectation: The results are shown only for the last 7 days
NB: After this bug occurred and I refreshed the page to fix it, the bug #1735  started to appear instead
- Image/Video envidence:

https://user-images.githubusercontent.com/97684890/230066946-241e0985-3c04-475b-8a6b-bfba543e3652.mov

**Comment by QuangHoang1210** [comment]
### Reproduce:
- It's a little bit make user confuse which I mentioned before https://github.com/linagora/tmail-flutter/issues/1477

### User Guide:
- User should select the filter condition following video bellow:

https://user-images.githubusercontent.com/124866146/230075205-0ab87d33-ab4c-4acb-8676-4b05bea4a9d6.mp4
