### ISSUE TITLE
[COMPOSER] Double scrollbar

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#1740]
### Description

When replying to a long mail I have 2 scroll bar on the side of the composer.

### Expected result

I expect only one scroll bar.

### Current behavior

![Screenshot from 2023-04-06 11-44-51](https://user-images.githubusercontent.com/6928740/230274312-95492038-b29a-4c03-bba9-f1fed1909a4f.png)

### Context

tmail.linagora.com, v0.7.6

Chromium, 111.0.5563.146 snap

**Comment by hoangdat** [comment]
Regression by: https://github.com/linagora/tmail-flutter/pull/1583. Related to `html`. 
Difficulty: Hard
