### ISSUE TITLE
[COMPOSER] Background color from the quoted reply applied everywhere

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#1741]
### Description

`GIVEN` an email with a background color

`WHEN` I reply to this email

`THEN` the background of my answer from within the composer and the quoted reply have the background color.

### Expected result

`GIVEN` an email with a background color

`WHEN` I reply to this email

`THEN` the quoted reply have the background color.

`AND` my answer part of the reply have no background color. 

Eg in thunderbird:

![Screenshot from 2023-04-06 13-16-00](https://user-images.githubusercontent.com/6928740/230287650-e4931fd2-dbb2-4546-a7ab-ef3e292e8b16.png)

### Current behavior

![Screenshot from 2023-04-06 12-13-32](https://user-images.githubusercontent.com/6928740/230287672-02c1d7af-7abe-48a9-98c8-8e3e6fd9ecfc.png)

#### Reproduction Steps

[ccifv-15-04.txt](https://github.com/linagora/tmail-flutter/files/11166974/ccifv-15-04.txt)

### Context
Chromium, tmail.linagora.com, v0.7.6

**Comment by nqhhdev** [comment]
We are fixed on v0.7.8

**Comment by hoangdat** [comment]
@nqhhdev can you attach commitId related to the fix
