### ISSUE TITLE
[Composer] Can not click send button

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#1744]
### Description

When in full screen mode.

https://user-images.githubusercontent.com/6928740/230331860-ecf468ea-54f8-413e-a96d-5190afc10f8d.mp4

**Comment by QuangHoang1210** [comment]
### Reproduce step:
1, User click on [Compose]
2, User input at least 2 email address on recipients
3, User type a long content in email body <I copy and paste in videos>
4, User open full size composer
5, User click on [Send] button

### Actual:
User cannot click on any button [Cancel] [Save Drafts] or [Send]

### Expected:

https://user-images.githubusercontent.com/124866146/230553761-06720ff6-be7f-45b7-ad9b-1b9167415ff7.mp4


User can click on them normally.

**Comment by dab246** [comment]
Cannot reproduce on MacOS. Need time to test on Linux vs Windows

**Comment by chibenwa** [comment]
Edit: the right most corner is clickable but not the center and it feels really unatural.

Yes that is for all emails :-/

**Comment by dab246** [comment]
Fixed at #1664
