### ISSUE TITLE
[EmailSuggesstion] Email at cc is removed once user select email at bcc suggesstion list

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#1753]
OS: WINDOW
Device: Laptop 
TeamMail Prod <0.7.6> and Preprod

*Precondition: 
- User A (userA@linagora.com) already login successfully
- Only in case the suggesstion list is displayed  as drop list up (following image bellow)

![Image](https://user-images.githubusercontent.com/124866146/230827988-147172d5-aa36-42f7-99f3-88027c305705.png)

### *Reproduce Step:
1, User click on [Compose] button
2, User click to open cc and bcc
3, User input QA Test 4 on cc and select the email in suggesstion list
4, User input QA Test 4 on bcc and select the email in suggesstion list

### **Actual:** 
The selected email in cc is removed.
The selected  email in bcc is not selected.

### **Expected:** 
The selected email in cc is keep showing.
The selected  email in bcc is selected.

https://user-images.githubusercontent.com/124866146/230827894-fad85cbc-2f4f-45e1-9e2b-561011cd5413.mp4

**Comment by dab246** [comment]
same #1576
