### ISSUE TITLE
[Sotorage] [Android Only] System still keep user's storage on Tmail application even if user unistall the app and reinstall it

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#1761]
OS: WINDOW
Device: Laptop
TMail version: 0.7.6

*Precondition: 
- User already login successfully on the application

### *Reproduce Step:
1, User already login and access on Tmail
2, User logout account sucessfully
3, User unistall Tmail
4, User reinstall Tmail and open it

### **Actual:** 
User can access Tmail directly without login step.

### **Expected:** 
User must login again

**Sign Out successfully**

![Image](https://github.com/linagora/tmail-flutter/assets/124866146/574833c8-6f51-4b2e-8500-59486fdc07b6)

**Unistall application**

![Image](https://github.com/linagora/tmail-flutter/assets/124866146/f5dc308b-804f-4c8b-af8b-0738dcfcff81)

**Reinstall application**

![Image](https://github.com/linagora/tmail-flutter/assets/124866146/c28616ec-3e82-4dc2-a266-79725f307523)

**Comment by QuangHoang1210** [comment]
Already reproduce with @dab246 cc @chibenwa  @hoangdat

**Comment by QuangHoang1210** [comment]
### Reproduce on Samsung GALAXY A51 - Android version A515FXXU5GVK6

https://github.com/linagora/tmail-flutter/assets/124866146/178e8d46-2e12-4159-823e-f24ea5778a0b

**Comment by hoangdat** [comment]
@QuangHoang1210 please compare with other app, especially Twake app.

**Comment by dab246** [comment]
- This problem no longer occurs.
- Tested on `OPPO F7 - v0.9.3`

**Comment by QuangHoang1210** [comment]
Still happen on 0.10.1 Android 


https://github.com/linagora/tmail-flutter/assets/124866146/d02b0271-9000-4f8c-80f2-1c26e1fedf02

**Comment by QuangHoang1210** [comment]
not reproduce on SAMSUNG A10
