### ISSUE TITLE
Reply / Forward: original message should be marked, not the sent one

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#1767]
### Description

https://user-images.githubusercontent.com/6928740/232434389-560902f9-7954-4321-abfa-83cc0827f06c.mp4

Reply / Forward: original message should be marked, not the sent one

Please implement Thuderbird behavour !!!

**Comment by chibenwa** [comment]
Needs to be fixed for v0.7.7

**Comment by hoangdat** [comment]
Hi @chibenwa @Arsnael , how is the best way to update keywords for email which was replied? We tried but not success.

ATM, we separate 2 requests: 
(i) Email/set +  EmailSubmission/set -> to send and update new email
(ii) Email/set -> to update email which was replied 

Please help us on it.

**Comment by chibenwa** [comment]
Nope on tmail-qa I see 

```

			"onSuccessUpdateEmail": {
				"#7d6c6cf0-ddaa-11ed-af69-8520fde82e01": {
					"mailboxIds/9ace9120-32cf-11eb-995c-a3ae66e9f96a": true,
					"mailboxIds/9ac08760-32cf-11eb-995c-a3ae66e9f96a": null,
					"keywords/$seen": true,
					"keywords/$draft": null,
					"keywords/$answered": true,
					"keywords/$forwarded": null
				}
```

Several things to say:

`"keywords/$forwarded": null` => don't reset this flag please.

```
GIVEN an email is marked as replied
WHEN I forward it
THEN it should be marked as reply AND forwarded
```

Vice versa


```
GIVEN an email is marked as forwarded
WHEN I reply to it
THEN it should be marked as reply AND forwarded
```

If you reset the flags it won't just happen.

Also the new mail should not be marked as neither seen nor replied.

BTW on v0.7.7 the requests I have is...

*send the new mail*: Email/set + EmailSubmission/set and resync Email/changes + Email/get x2 and Mailbox/changes + Mailbox/getx2.

And yes what you describe is correct. I would just wrap (1) and (2) in the same method call.

**Comment by hoangdat** [comment]
> Nope on tmail-qa I see

I mean, we are working on test

**Comment by hoangdat** [comment]
> I would just wrap (1) and (2) in the same method call.

IMO, if we wrap (i) and (ii) in the same JMAP request, we can not verify what happen in (i) is success or not. It is a risk

**Comment by chibenwa** [comment]
> IMO, if we wrap (i) and (ii) in the same JMAP request, we can not verify what happen in (i) is success or not. It is a risk

Why?

We have method level failure...
