### ISSUE TITLE
[V0.7.7] Broken infinite scroll ???

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#1768]
### Description

https://user-images.githubusercontent.com/6928740/232435574-f3ece9f0-94c7-4e02-99ee-52e8fca8f1c8.mp4

**Comment by hoangdat** [comment]
![Uploading Screenshot 2023-04-17 at 16.11.12.png…]()

**Comment by chibenwa** [comment]
Not a mobile problem cf https://github.com/linagora/james-project/issues/4768
