### ISSUE TITLE
Add `CalendarEvent/parse` method to jmap-dart-client

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#1775]
### Desc:
Story: https://github.com/linagora/tmail-flutter/issues/1489

Docs: https://github.com/linagora/tmail-backend/blob/c7698094b94487aa29f949d00665b274542a7706/docs/modules/ROOT/pages/tmail-backend/jmap-extensions/calendarEventParsing.adoc

Contract: https://github.com/linagora/tmail-backend/blob/a17a3051ee3176f93714b46f89f7b8c3ffc42961/tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/LinagoraCalendarEventParseMethodContract.scala

- create folder `jmap/mail/calendar`
- create `CalendarEvent` class + parsing methods to/from Json
- create folder `jmap/mail/calendar/parse` then implement `parse` method and response
- create unit tests to test parsing methods 

### DoD:
- [ ] passed unit tests

**Comment by chibenwa** [comment]
> Am I right?

Some changes are being discussed within the IETF, especially `BlobId[CalendarEvent[]]`

(Each individual ICS might contain several events)

**Comment by Arsnael** [comment]
We seem to go towards a consensus with the IETF though. I've been quite taken by solving indexing issues on preprod though... Will update the doc (and backend code) as soon as I can @hoangdat
