### ISSUE TITLE
Test TMail on very old devices

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#1777]
Verify that TMail runs on very old smartphone

 - Samsung Galaxy ACE (2011)
 - Iphone 4s (2013)

Question to @hoangdat :
 -  is this supported by flutter?
 - Which is the oldest model used by the team?

Question to @QuangHoang1210 : 
 - what could be the plan to test TMail on very old devices?

**Comment by hoangdat** [comment]
- Flutter depends on platforms, not on devices. https://docs.flutter.dev/reference/supported-platforms\
- Currently, TeamMail minimum supports: Android 19, iOS 11.

> Which is the oldest model used by the team?

Android 8.1 Xiaomi

**Comment by hoangdat** [comment]
This is the latest distribution of Android API

<img width="555" alt="image" src="https://user-images.githubusercontent.com/6462404/233221522-35460a27-176f-4f85-9dfe-324546752275.png">

IMO, we tried to support as much as device at the moment.

**Comment by hoangdat** [comment]
Source: https://iosref.com/ios-usage

<img width="916" alt="image" src="https://user-images.githubusercontent.com/6462404/233221831-73eefd4c-a5bd-482c-8bab-fb14d2027b68.png">

**Comment by cbusolin** [comment]
Thank you for these precisions. If it depends on the flutter, could you tell me what is the minimum support for Gmail or outlook type applications to be able to compare with Tmail? If you don't have the information, I'm looking for leads on where I can find it.

> Flutter depends on platforms, not on devices. [https://docs.flutter.dev/reference/supported-platforms\](https://docs.flutter.dev/reference/supported-platforms%5C)

Thank you for these precisions. If it depends on the flutter, could you tell me what is the minimum support for Gmail or outlook type applications to be able to compare with Tmail? If you don't have the information, I'm looking for leads on where I can find it.

**Comment by hoangdat** [comment]
1. please go to Play store. Fx: Outlook https://play.google.com/store/apps/details?id=com.microsoft.office.outlook
2. About this app 

<img width="774" alt="Screenshot 2023-04-29 at 08 31 25" src="https://user-images.githubusercontent.com/6462404/235277259-8875c79b-6e8e-42a5-8ef8-1f440bdf5e52.png">

As I check for Gmail, it seems special 
<img width="754" alt="image" src="https://user-images.githubusercontent.com/6462404/235277321-0e73a5ce-98bb-4845-87b6-ba2297f9f360.png">

Nice to support you.
