### ISSUE TITLE
[Improvement] [UX] TAB action

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#1780]
**GIVEN** I am TeamMail user
**AND** I open the Composer
**AND** the default focus at **To** field
**WHEN** I press TAB on keyboard
**THEN** the focus will be change sequentially from up to down | left to right

Expectation: 
To -> cc -> bcc -> subject -> Attach file icon -> Attach image icon -> Email body -> Cancel button -> Save to drafts button -> Send button -> X close icon -> From field <identity selecting> -> To -> cc ...

**GIVEN** I am TeamMail user
**AND** I open the Composer
**AND** the default focus at **To** field
**AND** I inputed at least 1 valid email each To, Cc, bcc field
**WHEN** I press TAB on keyboard
**THEN** the focus will be change sequentially from up to down | left to right
**AND** user can start typing to input other email

**Comment by chibenwa** [comment]
Please no jump directly from Subject to the body.

In the body tab is TAB (ie spaces)

Expectation:
To -> cc -> bcc -> subject  -> Email body
