### ISSUE TITLE
No subject in tablet view (ipad)

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#1784]
### Description

![Screenshot_20230423-141122_Gallery](https://user-images.githubusercontent.com/6928740/233825411-31b14aac-6c61-4d2f-84e5-f1c661dfcf3d.jpg)

On ipad in landscape mode email subjects are not displayed.

Web, safari, on tmail.linagora.com v0.7.6

**Comment by dab246** [comment]
Wok fine on `0.9.3`

<img width="1180" alt="Screenshot 2023-10-06 at 13 00 45" src="https://github.com/linagora/tmail-flutter/assets/80730648/cee3ab7c-ad39-483e-bdd7-0d617b08a200">
