### ISSUE TITLE
[Story] As a user, I want to delete message permanently from Spam folder 

### ISSUE THREAD

**Issue by dieptran88** [linagora/tmail-flutter#1793]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC

* TODO: {link}

## Definition

- Given that I am Tmail user and I have logged in successfully 
- I opened Spam folder and see the list of messages

**UC1. Delete a message permanently in Spam folder**

- When I hover a message on thread-view of Spam folder, I can see icon Delete. When I hover this icon, there will be a tooltip: "Delete permanently" 
- Or when I open an message, I can see Delete icon on top right or screen. 
- If I click on this icon, then there will be a confirmation popup:" You are about to delete permanently this message. Do you want to continue?". 
- If I choose Delete, the selected message is removed forever ( not moved to Trash folder as currently), there will be a notification message. 

**UC2. Delete multiple messages permanently in Spam folder**

- When I select multiple messages on thread view of Spam folder, there will be an action bar displayed 
- I click on icon "Delete permanently", there will be a confirmation popup "You are about to permanently delete [number of selected items] in Spam. Do you want to continue?". 
- If I choose Delete, selected items are removed forever (not moved to Trash folder as currently), there will be a notification message 

[Back to Summary](#summary)

### Delete single message
![Group 786 (1)](https://user-images.githubusercontent.com/68209176/233975171-c947bf80-2a0f-4381-af4b-c1b0866f7ea3.png)
![Group 784](https://user-images.githubusercontent.com/68209176/233975237-8dbc0f67-6702-4fff-8e92-898c97fbe5bc.png)
![Group 787](https://user-images.githubusercontent.com/68209176/233975321-2f4d6531-61fc-4790-8b73-7a7b6de66d1a.png)
![Group 788](https://user-images.githubusercontent.com/68209176/233975383-456fc7d2-8457-4997-b3d7-2f2865aadf5f.png)

#### Delete multiple messages 

![Group 783](https://user-images.githubusercontent.com/68209176/233975528-4b34867d-8dd6-43cd-9127-05c2f2838f9d.png)
![Group 789](https://user-images.githubusercontent.com/68209176/233975583-4da15ac8-2f6c-4415-a4ae-9d037d820269.png)
![Group 785 (1)](https://user-images.githubusercontent.com/68209176/233975670-83eadbcb-2315-4075-8c4c-4190946a25b2.png)

None

[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

**Comment by chibenwa** [comment]
=> Like trash ^^

**Comment by QuangHoang1210** [comment]
@dab246 

Reopened this one. Not work on 0.9.1

**Comment by hoangdat** [comment]
Hi @Arsnael , I think you can try with this ticket, not too much UI :)))
