### ISSUE TITLE
[Notification] System not display notification on IOS platform

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#1797]
OS: IOS only
Device: Iphone
TMail version: 0.7.8

*Precondition: 
- User already allow notification for TeamMail on device setting

![Image](https://user-images.githubusercontent.com/124866146/234509354-58cc1cd7-0853-43d5-af22-e84cb48b3841.png)

*Data test: User firstname31.surname31

### *Reproduce Step:
1, User A send an email to User B

### **Actual:** 
User B didn't see notification of new email

### **Expected:** 
User B should see notification of new email

![Image](https://user-images.githubusercontent.com/124866146/234509395-6b07da68-e78f-42ba-a09b-7dee8c0951c9.png)

![Image](https://user-images.githubusercontent.com/124866146/234509408-734ce9fb-4c83-4616-8894-35169964f392.png)

**Comment by dab246** [comment]
It works fine on iOS
- Version: 0.7.8 (TestFlight)
- Device: iPhone 13 Promax - iOS 16.2

@QuangHoang1210  Please remove app reinstall it. Thanks
