### ISSUE TITLE
Ignore autodiscovery for JMAP

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#18]
### Desc:
Jmap publish service autodiscovery based on 
`.well-known/jmap`

Spec: https://jmap.io/spec-core.html#service-autodiscovery

### DoD:
- [ ] ignore autodiscovery when user input session endpoint directly

**Comment by chibenwa** [comment]
User input: tmail.com
Apply auto discovery: https://tmail.com/.well-known/jmap

User input: tmail.com/jmap/session
Do not apply auto discovery: https://tmail.com/jmap/session

**Comment by chibenwa** [comment]
Can we close this @hoangdat ?

**Comment by hoangdat** [comment]
At the moment, we have not accepted user input URL like this `tmail.com/jmap/session`.  If we do this, need to fix the OIDC discovery flow a bit also.

**Comment by chibenwa** [comment]
> At the moment, we have not accepted user input URL like this tmail.com/jmap/session

Not important as now all enve have .well-known in place IMO
