### ISSUE TITLE
[View Email] User cannot hide/show the attachment rows in email details view

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#1801]
OS: WINDOW, ANDROID, IOS
Device: Mobile, LAPTOP
TMail version: 0.7.8 QA stable and 0.7.6 production

*Precondition: 
- User send/receive an email which include attachment files.

*Data test: User firstname31.surname31

### *Reproduce Step:
1, User open that email in precondition from inbox / sent box
2, User click on Show / Hide button

### **Actual:** 
Nothing happens

### **Expected:** 
The attachments row should be hide / show 

https://user-images.githubusercontent.com/124866146/234753568-26b94b50-ee68-4254-8f45-66b447930ca4.mp4

**Comment by hoangdat** [comment]
verify later with new composer in v0.9.2

**Comment by hoangdat** [comment]
https://www.figma.com/file/XqLqMINlZw09BdEHI8yLb9/Teammail---1.1?type=design&node-id=277-89312&mode=design&t=dNw457n4d0Hl3HF5-4

**Comment by hoangdat** [comment]
### DoD:
- [ ] apply new style for attachment
- [ ] mobile: 
  - [ ] bottom sheet to show all + show more, 
  - [ ] limit <= 2 attachments in email view
- [ ] web: limit <= 2 lines of attachment
- [ ] tablet: limit <= 2 lines of attachment
