### ISSUE TITLE
FCM broken?

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#1802]
### Description

I have a notification `updated in the background` but I manually need to click the update to see the updates applied.

https://user-images.githubusercontent.com/6928740/234817535-9a6e1bdf-c03b-4362-be0f-8e9f68772097.mp4

**Comment by dab246** [comment]
@chibenwa  

- I checked again on server prod (latest release, latest master) and found file `env.fcm` missing information `FIREBASE_WEB_VAPID_PUBLIC_KEY`

- `FIREBASE_WEB_VAPID_PUBLIC_KEY` is the VAPID (Voluntary Application Server Identification) public key. When getting `token` on web platform we need to use it.

```
final fcmToken = await FirebaseMessaging.instance.getToken(vapidKey: ....");
```

- And for this issue we also wrote `adr` file [fcm_configuration.md](https://github.com/linagora/tmail-flutter/blob/master/docs/configuration/fcm_configuration.md) in Team Mail project .
- Please add `FIREBASE_WEB_VAPID_PUBLIC_KEY` to `env.fcm` file when we want to enable FCM for web

**Comment by Arsnael** [comment]
@dab246 I see, indeed this is missing. Good diagnosis!

However I do not have the creds on Firebase... I would guess @hoangdat is the one to ask for it logically? :) Can you get us that  VAPID key on firebase please so we can add it to the prod conf?

And can you get the VAPID for preprod as well, as I'm seeing it is missing too? Thanks :)

**Comment by dab246** [comment]
@Arsnael   This is VAPID `BIOHtNeniv0BOkQY_HvHwVvAnQ7bzNmBlNRunpL_oZwrOT5MnmSYbU6igq61Wu-sQrEi3VcfC2WY7sHawSpkwms`

**Comment by Arsnael** [comment]
[fcm_error.webm](https://github.com/linagora/tmail-flutter/assets/9005025/277bd3d4-8c50-44d3-b132-270d698cccd9)

So I added the VAPID and... it still does not work, as you can see on the video. Added it to the prod env.fcm conf file (on tmail, canary and oncommit versions), tested with chromium on the video but I could see the same with Firefox

@hoangdat did you give me the right key? (prod not preprod for example). If yes, please can you or someone in your team (@dab246 ?) investigate again please? Thanks :)

**Comment by chibenwa** [comment]
> @hoangdat did you give me the right key? (prod not preprod for example). If yes, please can you or someone in your team (@dab246 ?) investigate again please? Thanks :)

Again, I'm pretty sure the FCM messages are received but not act upon.

I receive "app updated in the background" system notifications but... nope.

**Comment by dab246** [comment]
Ok. We will re-investigate it
