### ISSUE TITLE
[Web] Mail composer buttons are not clickable after uploading an attachment 

### ISSUE THREAD

**Issue by quantranhong1999** [linagora/tmail-flutter#1805]
### Description
Mail composer buttons are not clickable after uploading an attachment.

### Expected result
Mail composer buttons are clickable after uploading an attachment or whatever.

### Current behavior
Mail composer buttons are not clickable after uploading an attachment.

#### Reproduction Steps
Open TMail Web by Chrome -> select mail composer -> open it full size -> draft a mail (buttons are clickable) -> upload attachment -> buttons are not clickable.
[mail compose buttons are not viable after attachment upload.webm](https://user-images.githubusercontent.com/55171818/235121061-4a3d2ec1-8f1e-40a9-b8ca-3f5659c20474.webm)

I reproduced by incognito mode of Chrome too.

### Context
TMail FE v0.7.6 prod
Chrome Version 112.0.5615.165 (Official Build) (64-bit)

**Comment by hoangdat** [comment]
Raised and fixed
