### ISSUE TITLE
[Bug]: Impossible to disable used fonts in email composer

### ISSUE THREAD

**Issue by tprudentova** [linagora/tmail-flutter#1806]
•	Environment(version): tmail.upn.integration-open-paas.org, v 0.7.8, Google Chrome
•	Date of occurrence: 28.04.2023
•	Steps to reproduce:
1.	Type any text in the email composer
2.	Apply different fonts to different parts of it (bold, italic etc)
3.	Go to the next line
4.	Remove all fonts 
5.	Type some text 
6.	The fonts are still applied to it
•	Expectation: When I disable all fonts, the text is typed in in regular font
•	Image/Video envidence:

https://user-images.githubusercontent.com/97684890/235603693-39657f22-fec7-4952-866a-5320993bb3f0.mov

**Comment by chibenwa** [comment]
Reproduced (tmail.linagora.com on v0.7.6, chromium)
