### ISSUE TITLE
[Dev] Store email when receive in foreground

### ISSUE THREAD

**Issue by dab246** [linagora/tmail-flutter#1810]
### Issue

- #1702 - US 2

### DoD

- [ ] Store email when receive in foreground (Android - iOS)

### Desc

- Keep 10 email recent 
- Add box name  static const String fcmEmailCacheBoxName = 'fcm_email_cache_box';
- Create object `FcmEmailDetailCache`
```
class FcmEmailDetailedCache {
 ....(property of email) 
  final String emailId;
  final List<AttachmentCache> attachments;
  final String emailBodyFile; 
  final Set<EmailHeaderCache> headers;
  final DateTime dateTimeSaved;
}
```
- Add `GetEmailDetailForFcmInteractor` to get email (full property) => convert `Email` to `FcmEmailDetailCache`
- Store email content html to file.
- Store `FcmEmailDetailCache` to hive database

**Comment by QuangHoang1210** [comment]
Not passed 0.7.11 -> https://github.com/linagora/tmail-flutter/issues/1923
