### ISSUE TITLE
[Dev] Manage the sending queue

### ISSUE THREAD

**Issue by dab246** [linagora/tmail-flutter#1813]
### Issue

- #1702 - US 1.b

### Desc:
- check queue existed
- add fake folder to Default Mailbox tree
- handle navigation to `SendingQueueView` (mobile + tablet)

### DoD

- [ ] Display list of emails in the sending queue (to + subject + date + attachment)

**Comment by hoangdat** [comment]
@hoangdat please discuss the UI with designer
