### ISSUE TITLE
[Release] Production Release v0.7.8

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#1820]
### Working well on version 0.7.8 mobile and laptop.

- [x] Resolved all crashed issue.
- [x] Resolved all blocking issue.
- [x] All elements can be clickable.
 

### Remaining Issue:

- [ ] Notification on IOS -> Will be applied fix on later version.
- [ ] https://github.com/linagora/tmail-flutter/issues/1497 -> This will be fix later.
- [ ] Upload image slowly -> Rarely reproduce, I will take more time to retest clearly. Also with phone storage.

**Comment by hoangdat** [comment]
About notification, issue at the moment: if user upgrade app from store, no more notification, so need to re-install. Need more investigation

**Comment by hoangdat** [comment]
- [x] AppStore is in progress 
- [x] PlayStore is in progress
