### ISSUE TITLE
Change from SVG icon to Icon data of Material 3 will make the app reduce the binary size

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#1826]
### Desc:
- we use a lot of custom icons, so we need to add a lot of assets
- we should use the built-in IconData of Flutter will make us to reduce assets and binary size, also reduce the time to download main.dart.js at the first time.

### DoD:
- [ ] Change from all svg to icon data
- [ ] calculate the size of apk, ipa, main.dart.js BEFORE and AFTER

**Comment by dab246** [comment]
We can use this page [fluttericon](https://www.fluttericon.com/) to convert `svg` to `IconData`. It also produces Flutter code :))

**Comment by hoangdat** [comment]
not priority
