### ISSUE TITLE
[UX] User cannot scroll to view other attachment file in hidden list by using mouse devices

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#1832]
OS: Window
Device: Laptop
TMail version: 0.7.8

*Precondition: User using desktop or laptop with mouse device.

### *Reproduce Step:
1, User click [Compose]
2, User attach at least 5 image/files
3, User hoover mouse on attachment rows and try to scroll

### **Actual:** 
- User cannot scroll to see hidden attachment

### **Expected:** 
- User can scroll to see hidden attachment

https://user-images.githubusercontent.com/124866146/237565648-14599650-974f-40e7-b9a7-d57f177280e9.mp4

**Comment by dab246** [comment]
@QuangHoang1210  Please use this while we improve it to show draggable scrollbars. 
[How to move window content horizontally using keyboard and mouse](https://help.sap.com/saphelp_SCM700_ehp02/helpdata/en/9a/313b8b7d3a46f592afa460a6aa8d0f/content.htm?no_cache=true#:~:text=You%20can%20move%20the%20contents,the%20keyboard%20and%20the%20mouse.&text=Move%20contents%20to%20the%20right,scroll%20the%20mouse%20wheel%20down)
