### ISSUE TITLE
[COMPOSER] Selected "rich text menu" do not match current text status

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#1851]
### Description

When composing rich text with special attibutes, and I move (click) cursor in an area with text with different , previous rich text attributes of the menu are kept, and becomes out of sink with what I type.

### Expected result

When I move the typing cursor, I expect the rich text menu to match the attributes of the text I am typing. Text attributes of the rich text bar needs to match properties of currently selected area.

For instance:

```
GIVEN I am typing text bold green
WHEN I move (click) the cursor in an area with normal text
THEN the rich text bar shows no option
AND when I type I type normal text


GIVEN I am typing text bold green
WHEN I move (click) the cursor in an area with normal text
AND select bold
THEN the rich text bar is bold
AND when I type the text is bold
```

### Current behavior

```
GIVEN I am typing text bold green
WHEN I move (click) the cursor in an area with normal text
THEN the rich text bar shows bold green
AND when I type I type normal text

GIVEN I am typing text bold green
WHEN I move (click) the cursor in an area with normal text
AND unselect bold
THEN the rich text bar is not bold
AND when I type the text is bold
```

https://github.com/linagora/tmail-flutter/assets/6928740/043cfa01-7707-4683-9670-869e0c8e6122

`:10` and `1:12`

### Context

Firefox https://oncommit-tmail.linagora.com `v0.7.9+`

**Comment by QuangHoang1210** [comment]
Verifed 0.8.2 -

### Chrome: 
**Actual:** Working well with other AC except the one bellow:
**Expectation:**
1, The font family should be selected which matched with text status when user focus on.


### Firefox: Not catch the AC
**Actual:** All ACs  are not working well on firefox
**Expectation:** 
1, The 'B - I - U' icon should be selected which matched with text status when user focus on.
2, The color should be selected which matched with text status when user focus on.
3, The paragrap should be selected which matched with text status when user focus on.
4, The font family should be selected which matched with text status when user focus on.

https://github.com/linagora/tmail-flutter/assets/124866146/5be97170-f3c7-4941-8fa1-d2b3f28eb79c

@dab246
