### ISSUE TITLE
Right click on email item in email list view

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#1862]
### Description

Firefox:

```
GIVEN I am in email list view
WHEN I right click on an item
THEN the right clicks menu open
AND the move dialog is shown

WHEN I close the right click dialog 
THEN the move dialog is still here
```

Chome :

```
GIVEN I am in email list view
WHEN I right click on an item
THEN the right clicks menu open
AND the move dialog is shown

WHEN I close the right click dialog 
THEN the move dialog is still here
```

### Expected result

Do not show the move dialog at all when I right click...

### Current behavior

Firefox:

https://github.com/linagora/tmail-flutter/assets/6928740/ae55073d-367e-4769-85ef-7ea99d636f1b

Chrome:

https://github.com/linagora/tmail-flutter/assets/6928740/977862a6-d2b5-47b0-9b70-b117a77d0a04

### Context

https://oncommit-tmail.linagora.com

**Comment by QuangHoang1210** [comment]
Verified on 0.8.2 - 

Firefox: Looking well
Chrome: The move dialog still displayed  in 1 second when user right click on email rows.

Expected: The move dialog only display when user drag the email.



https://github.com/linagora/tmail-flutter/assets/124866146/b09a7440-c549-42be-9d8d-33cb0e4365b9

**Comment by dab246** [comment]
@QuangHoang1210 Please verify help us. Thanks
