### ISSUE TITLE
[COMPOSER] Underline then color

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#1867]
### Description

If I underline some text then set color for it
Then the color is not applied for the underline, only for the main letters.

### Expected result

 - Underline then color

And

 - Color then underline
 
 Should commute (ie yield the same result) IE both the text and the underline should be colored.
 
### Current behavior

https://github.com/linagora/tmail-flutter/assets/6928740/01aef240-5471-432b-a237-a88a223b92ef

### Context

https://oncommit-tmail.linagora.com v0.7.9+ firefox

**Comment by dab246** [comment]
Fixed on version 0.8.2
