### ISSUE TITLE
Hide parent - show child: nothing displayed in the side bad

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#1868]
### Description

```
GIVEN mailbox A, mailbox B with mailbox B in mailbox A
AND mailbox A and B are hidden
WHEN I show mailbox B
THEN mailbox A is not show and I cannot see mailbox B in the mailbox panel
```

### Expected result

When Hiding mailboxes we have a rule to say that child will be hidden too:

```
GIVEN mailbox A, mailbox B with mailbox B in mailbox A
AND mailbox A and B are visible
WHEN I hide mailbox A
THEN mailbox A and B are hidden
```

This would give:

```
GIVEN mailbox A, mailbox B with mailbox B in mailbox A
AND mailbox A and B are hidden
WHEN I show mailbox B
THEN mailbox A and B are visible
```

### Current behavior

https://github.com/linagora/tmail-flutter/assets/6928740/2f508305-aa22-4189-8d77-4738e95813f8

### Context

https://oncommit-tmail.linagora.com

**Comment by dab246** [comment]
@chibenwa 

With 

```
GIVEN mailbox A, mailbox B with mailbox B in mailbox A
AND mailbox A and B are hidden
WHEN I show mailbox B
THEN mailbox A and B are visible
```

```
WHEN I show mailbox A
THEN mailbox A and B are visible?
```

**Comment by chibenwa** [comment]
>WHEN I show mailbox A
>THEN mailbox A and B are visible?

No I would say we can hide mailbox B in mailbox A.

But if a mailbox is visible then it's parents needs to be visible too.

**Comment by chibenwa** [comment]
Note to self: we MAY be able to implement this on the backend side ;-)

**Comment by dab246** [comment]
> > WHEN I show mailbox A
> > THEN mailbox A and B are visible?
> 
> No I would say we can hide mailbox B in mailbox A.
> 
> But if a mailbox is visible then it's parents needs to be visible too.

No, I get what you mean.
But now we are doing: `If parent mailbox is opened, all its children are open`. Is that true for the scenario we want?

**Comment by chibenwa** [comment]
> But now we are doing: If parent mailbox is opened, all its children are open. Is that true for the scenario we want?

No not necessarily

**Comment by QuangHoang1210** [comment]
Passed
