### ISSUE TITLE
Tmail-web does not load anymore after clearing cache

### ISSUE THREAD

**Issue by Arsnael** [linagora/tmail-flutter#1873]
### Description

On our testing environment, `tmail.upn.integration-open-paas.org/`, after clearing the cache, the web app does not load anymore. The last file it loads is the env.file, and then it hangs on a blank screen.

I believe the problem is recent, on the master branch as:
-  `tmail.upn.integration-open-paas.org/` is based on the master branch
- `tmail-qa.upn.integration-open-paas.org` is based on the release branch and I don't see that problem there.

### Expected result

It should loads all necessary files on a cleared cache and present me with the login screen.

### Current behavior

It stops at loading the env.file and just hangs with a white blank screen

### Preconditions (optional)

- Clear your cache before trying to load the web app 

#### Reproduction Steps

- Clear your cache in your browser
- Load the web app in `tmail.upn.integration-open-paas.org/`
- it stops at the `env.file` and hangs on a blank screen

### Acceptance criteria

It should loads all necessary files on a cleared cache and present me with the login screen.

### Context

- Laptop 
- browsers Chromium + Firefox (tried both)
- after clearing cache
- `tmail.upn.integration-open-paas.org/` (based on master branch)

### Additional information

[bug-load-tmail-web.webm](https://github.com/linagora/tmail-flutter/assets/9005025/23bdf17e-902d-4d70-ad88-48ca42df821b)

**Comment by quantranhong1999** [comment]
"Could" be related to the cache: https://github.com/linagora/tmail-flutter/pull/1840 ? (it is on master and not released yet?)

I am not sure yet, will have a look when I have time.

**Comment by QuangHoang1210** [comment]
### Reproduce on Tmail production 
**Step**
1, Login tmail sucessfully
2, Clear the cache
3, Reload the page

**Actual:** 
Tmail is hangon in blank for a while

**Expected**
Tmail is loading smoothly

https://github.com/linagora/tmail-flutter/assets/124866146/d88c58ec-967b-49d4-90b2-a5f54607e1fc

### Addition information

**Console**
```
New service worker available.
(index):94 Failed to load app from service worker. Falling back to plain <script> tag.
(anonymous) @ (index):94
setTimeout (async)
(anonymous) @ (index):92
load (async)
(anonymous) @ (index):57
(index):68 Installed new service worker.
main.dart.js:18197 Flutter Web Bootstrap: Auto.
main.dart.js:81042 Got object store box in database encryptionkeycache.
main.dart.js:9567 [Violation] 'setTimeout' handler took 102ms
main.dart.js:81042 Got object store box in database recentsearchcache.
main.dart.js:81042 Got object store box in database accountcache.
main.dart.js:18140 [Violation] 'requestAnimationFrame' handler took 182ms
main.dart.js:18140 [Violation] 'requestAnimationFrame' handler took 65ms
/#/login:1 Access to XMLHttpRequest at 'https://jmap.linagora.com/.well-known/webfinger?resource=https://jmap.linagora.com&rel=http://openid.net/specs/connect/1.0/issuer' from origin 'https://tmail.linagora.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
main.dart.js:134575     GET https://jmap.linagora.com/.well-known/webfinger?resource=https://jmap.linagora.com&rel=http://openid.net/specs/connect/1.0/issuer net::ERR_FAILED 404 (Not Found)
```

**Note**
Some files which having **.ttf** exentions are tooking a long time to loading (10000ms to 30000ms)

![image](https://github.com/linagora/tmail-flutter/assets/124866146/9ee35ad2-e5f0-4b4c-97da-e4e5a8d1fe63)

@dab246  @Arsnael @chibenwa @hoangdat

**Comment by Arsnael** [comment]
@QuangHoang1210 I was talking about tmail testing env :)

FYI I have no problem on my side loading the page on tmail.linagora.com (prod) after clearing the cache

**Comment by quantranhong1999** [comment]
> "Could" be related to the cache: https://github.com/linagora/tmail-flutter/pull/1840 ? (it is on master and not released yet?)

Tested and seems not related.

BTW latest master image works normally on my local. Maybe thanks to https://github.com/linagora/tmail-flutter/pull/1875 ? (https://linagora.github.io/tmail-flutter/1875 loads normally btw).

**Comment by quantranhong1999** [comment]
Restart tmail-web deployment (to force load latest image), `https://tmail.upn.integration-open-paas.org/` can loads normally for me now.

**Comment by Arsnael** [comment]
Ok to me now... notice I forgot a little piece of conf in tmail-backend to change from krakend to apisix, could have been that^^' Apologies if it was the case

Can close this issue I guess?
