### ISSUE TITLE
[Composer] The 1st and 2nd text row will be moved once user blacken out the 1st by double click then select paragraph type

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#1876]
### ENV: Chrome on Windows
version 0.7.9 -- https://canary-tmail.linagora.com/

### Reproduce Step:
1, User open composer
2, User double click to blacken out only the 'quang' text
3, User select one of paragraph option

**Actual**: The 'quang' text and 'huy' text (1st row and 2nd row) is moved 
**Expected**: Only blacken out text is moved. Not other one.

https://user-images.githubusercontent.com/124866146/240842846-60dc39be-a201-4743-8ff8-e7fcb4c544bc.mp4

**Comment by dab246** [comment]
Fixed on version 0.8.2
