### ISSUE TITLE
[Composer] Text Style is not changed correctly once user change the focus

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#1877]
**UC1: User can select text style in droplist down**
```
GIVEN There are Heading 1 in style droplist down
WHEN user select Heading 1 in style droplist down
AND user write some words
THEN Heading 1 is selected
AND words are being heading 1 style
```
**UC2: User can change text style of text by the way that blacken out the word first then select the text style**
```
GIVEN 'quang' text is normal style
WHEN user blacken out 'quang' text
THEN user select heading 1 style then 'quang' text style is changed to heading 1
```
**UC3: The selected text style will be changed once user change focus**
```
GIVEN 'quang' text is normal style
AND 'huy' text is heading 1 style
AND 'dat' text is heading 2 style
AND 'Abc' text is code style
WHEN user change focus to one of those text
AND user select the style
THEN the text style is applied and changed
```

**UC4: User can change text style of text by the way that change focus to the word first then select the text style**
```
GIVEN 'quang' text is normal style
AND 'huy' text is heading 1 style
AND 'dat' text is heading 2 style
AND 'Abc' text is code style
WHEN user click to focus on 'quang' text
AND user select style to be heading 1
THEN 'quang' text is being heading 1
```

**UC5: The selected text style should be changed correctly belong to the text style of word which user focus on**
```
GIVEN 'quang' text is Time New Roman font family
AND 'huy' text is Sans Serif
AND user focus at 'quang' text
WHEN user change focus to 'huy' text
THEN Sans Serif will be selected in font family droplist down
```

### ENV: Chrome on Windows
version 0.7.9 -- https://canary-tmail.linagora.com/

### Reproduce Step:
1, User open composer
2, User click on style droplist down
3, User select one style in droplist down

**Actual**: Nothing is selected
**Expected**: It should be selected and catch the UC requirement above

https://user-images.githubusercontent.com/124866146/240841408-5c38ac63-8015-4619-81be-663b6d16bb8a.mp4

**Comment by dab246** [comment]
Fixed on version `0.8.2`
