### ISSUE TITLE
[Android] Image sharing - multiple images and type text

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#1889]
### Description

```
GIVEN I open ImageViewer
AND I Select two images
WHEN I click "Share with TMail"
THEN a single inage is loaded
AND I cannot write the HTML body
```

### Expected result

```
GIVEN I open ImageViewer
AND I Select two images
WHEN I click "Share with TMail"
THEN the two  images are loaded
AND I can write the HTML body
```

### Current behavior

https://github.com/linagora/tmail-flutter/assets/6928740/626ff62b-db6a-4b88-a2eb-e161822e17a3

### Context

Android, 0.7.6

**Comment by chibenwa** [comment]
@QuangHoang1210  can you confirm?

Is that fixed in latest releases?

**Comment by QuangHoang1210** [comment]
### Verify on lastest version in store: 0.7.8 -> Working well both Android & IOS

https://github.com/linagora/tmail-flutter/assets/124866146/09362092-895e-40b1-a6e3-25ba390c8d25


### Verify on Preprod 0.7.9 -> Cannot upload the images which are mentioned in this ticket https://github.com/linagora/tmail-flutter/issues/1799

Reproduce step:
1, Select 1 or multiple image in Photos
2, Select sharing with Tmail

Actual: There is no image is uploaded. The 
Expected: It should be uploaded sucessfully.

@chibenwa @hoangdat
