### ISSUE TITLE
[Bug] Children of default mailbox is showed with unclearly parent

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#189]
### Current behavior

 Children of default mailbox is showed without parent.

### Expected result

TreeView for default mailbox

**Comment by hoangdat** [comment]
@chibenwa the sub-folder of `default mailbox` should be show in `folder` tree or should be sub of default mailbox in UI. 
Ex: 
```
Inbox
  | - - Sub inbox
 Sent
  | - - sub Sent
.......
Folder
   | - - other folders
```

or 

```
Inbox
  |
Sent
  |
.......
Folder
  | - - Sub of Inbox
  | - - Sub of Sent
  | - - other folders
```

**Comment by chibenwa** [comment]
I prefer option 1
