### ISSUE TITLE
Reading long mail on phone: mail trucated

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#1890]
### Description

Today in COSOFT I had a user report that complained getting his email truncated.

This needs to be confirmed with strong evidance.

TODO investigate.

### Context

Android ??? v 0.7.6 ???

**Comment by chibenwa** [comment]
Cc @QuangHoang1210

**Comment by hoangdat** [comment]
this is fixed. Alex still faces the same issue? Which version he is using?

**Comment by hoangdat** [comment]
https://github.com/linagora/tmail-flutter/issues/1521

**Comment by hoangdat** [comment]
on master


https://github.com/linagora/tmail-flutter/assets/6462404/8ce34ac4-600c-4f4a-a018-7211a656299b

**Comment by hoangdat** [comment]
@QuangHoang1210 please verify with latest version in store

**Comment by QuangHoang1210** [comment]
### Verify on lastest version in store - 0.7.8 -> It's working well both Android and IOS

https://github.com/linagora/tmail-flutter/assets/124866146/33ec8142-9000-4892-b8b6-f46bea13fec8

### Verify on preprod - 0.7.9 -> It's working well both Android and IOS

https://github.com/linagora/tmail-flutter/assets/124866146/e3f12531-60e1-4236-8f32-52a9b4b3e308


@hoangdat  @chibenwa
