### ISSUE TITLE
[Auto Sync] [Chrome/Firefox] System not auto sync once user recieved new email

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#1896]
OS: Chrome / Firefox
Device: Laptop
TMail version: 0.7.9 - preprod
TMail version: 0.7.8 - production

### *Reproduce Step:
1, User A send a new email to user B
2, Go to check user B email thread

### **Actual:** 
System not auto sync and reload to displaye the new email on the list

### **Expected:** 

System should auto sync and reload to display the new email on the list

https://github.com/linagora/tmail-flutter/assets/124866146/d706b8ee-3f7e-4bd1-8da6-0b1a491d1e24

**Comment by dab246** [comment]
Work fine on version `0.8.3`

**Comment by QuangHoang1210** [comment]
Not Passed

**Comment by QuangHoang1210** [comment]
Re test -> Not Passed 

Version: 0.8.8 -- https://canary-tmail.linagora.com/

![Image](https://github.com/linagora/tmail-flutter/assets/124866146/b9a2337f-c1bf-4b70-8151-7e4be95c4cbf)

@dab246

**Comment by dab246** [comment]
After investigate, i found the error:



![Image](https://github.com/linagora/tmail-flutter/assets/80730648/6699bd40-b8f6-459a-b238-fd6bd75dee0f)


Furthermore, the file `env.fcm` is missing the `FIREBASE_WEB_VAPID_PUBLIC_KEY` variable to get the correct token on the web

**Comment by hoangdat** [comment]
@ducnm0711 can you help us on it?

**Comment by hoangdat** [comment]
Regress a lot. Take a lot of time to check in every releasing

**Comment by dab246** [comment]
![Image](https://github.com/linagora/tmail-flutter/assets/80730648/73083d23-da77-493c-8fc2-37b49eb0b304)

**Comment by dab246** [comment]
- Work fine on `canary`
