### ISSUE TITLE
More Filter actions

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#1902]
### Description

CF https://github.com/apache/james-project/pull/1563

CF https://github.com/linagora/tmail-backend/issues/687

Add the following actions:

 - [ ] `mark as seen`
 - [ ] `mark as important`
 - [ ] `reject`
 - [ ] `Spam` will move the email into the spam mailbox using the appendIn directived

As a user I can select several actions.

Reject should NOT be combined with other options. If selected, other fields are disabled, with their input reset.

Cc @dieptran88 can you work on a design for this with design team?

Cc @Arsnael @hoangdat

**Comment by hoangdat** [comment]
### JMAP module: 

`rule_filter` inside `tmail-project`

### Presentation:

```
lib/features/rules_filter_creator
```

Start from: `lib/features/rules_filter_creator/presentation/rules_filter_creator_controller.dart` and `lib/features/rules_filter_creator/presentation/rules_filter_creator_view.dart`

**Comment by dieptran88** [comment]
Hi @chibenwa I have one  question: Currently we already had action Move to Spam folder => Do we need another action Spam ? 
How about action "Forward" ?

**Comment by chibenwa** [comment]
> How about action "Forward" ?

Yes nice idea.

> Currently we already had action Move to Spam folder => Do we need another action Spam ?

My idea would be to have a shortcut in the UI, yes!

**Comment by Arsnael** [comment]
@hoangdat : I would see this being done in 3 smaller steps (so 3 PRs) to ease dev : 
- 1. add the actions mentioned in the description
- 2. performing multiple actions on a filter
- 3. being able to add multiple conditions on a filter
