### ISSUE TITLE
App grid: application names where not removed

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#1903]
### Description

When closing the app grid on prod, canary in firefox, the application names were still displayed....

https://github.com/linagora/tmail-flutter/assets/6928740/033ce7a4-7db6-4130-be3a-26b0a29616a0

Lucky I was recording, because I do not succeed to reproduce...

**Comment by dab246** [comment]
@QuangHoang1210  please help us verify it.

**Comment by QuangHoang1210** [comment]
1, Why the Tmail version of Benoit is 0.7.9 on Canary!?
2, There is 0.8.5 on my Canary -- Cannot reproduce


https://github.com/linagora/tmail-flutter/assets/124866146/5f20@dab246 -873d-40be-baf5-ae8d3c9228a8

@chibenwa  cc @dab246

**Comment by chibenwa** [comment]
Yes this bug was WTF, I suceed to get it on camera but I did not succeed to reproduce...

IMO let's not spend too much time on that UI glitch...

**Comment by hoangdat** [comment]
Maybe a rendering issue in Firefox, the same as drag n drop in firefox.

**Comment by dab246** [comment]
@QuangHoang1210  Please test on version `0.9.1`
