### ISSUE TITLE
Investigate scheduling to send emails while offline on iOS devices

### ISSUE THREAD

**Issue by dab246** [linagora/tmail-flutter#1909]
### DoD

- Research the UX of other email clients (Gmail, Apple mail,...)
- The most optimal solution with [workmanager](https://pub.dev/packages/workmanager)

**Comment by dab246** [comment]
> Research the UX of other email clients (Gmail, Apple mail,...)
>

@QuangHoang1210  please help me confirm

**Comment by QuangHoang1210** [comment]
### **[GMAIL]** Send offline behaviour: 

**Step:**
1, User turn off internet
2, User click on Composer
3, User input Reciever
4, User input/attach text /image/ file into email composer
5, User click [Send] button

**Actual:** 
- System display a toast :"Offline. Will send when online" in few seconds then it be disappeared
- Animation: The icon avatar is having loading animation which indicate email is in sending queue
- User can open the email to view exactly content (text/image/file icon)

https://github.com/linagora/tmail-flutter/assets/124866146/3715cb58-2a98-4de6-bfde-081d4081546d


@dab246

**Comment by dab246** [comment]
> ### **[GMAIL]** Send offline behaviour:
> **Step:** 1, User turn off internet 2, User click on Composer 3, User input Reciever 4, User input/attach text /image/ file into email composer 5, User click [Send] button
> 
> **Actual:**
> 
> * System display a toast :"Offline. Will send when online" in few seconds then it be disappeared
> * Animation: The icon avatar is having loading animation which indicate email is in sending queue
> * User can open the email to view exactly content (text/image/file icon)
> 
>  signal-2023-06-05-145804_002.mp4 
> @dab246

1. Please further check the case it is sent when we turn on the network.
2. Test more cases to create 2-3 emails offline and automatically send them when network is available.

**Comment by QuangHoang1210** [comment]
@dab246 
1, It sent successfully when user turn on the network
2, All email is sent successfully once network is available -- And only one toast is displayed "Sent"

**Comment by QuangHoang1210** [comment]
### Case 1: Kill app

1, Sent offline
2, Kill App
3, Reconnect

-> Actual: No email was sent successfully until user open the app gmail again.


### Case 2: App run in background

1, Sent offline
2, Kill App
3, Reconnect

-> Actual: No email was sent successfully until user open the app gmail again.
