### ISSUE TITLE
Rendering issue on TMail when reading an email

### ISSUE THREAD

**Issue by Arsnael** [linagora/tmail-flutter#1912]
### Description

I received a mail from the IETF asking me to do some modifications on my draft document regarding JMAP quotas. Those asked modifications just don't show in TMail, while they show perfectly in Openpaas and Thnderbird. 

The parts that don't show are wrapped with the XML comment syntax : 
```
<!-- 
blablabla...
-->
```
I believe somehow the rendering in TMail interprets that as a comment while it should not (see video to better understand what this is about).

I experienced that in tmail-web and tmail iOs app, on prod (tmail.linagora.com).

### Expected result

Those parts should show up when I'm reading the email with TMail

### Current behavior

Those parts don't show, it's like tmail interprets body content `<!-- ... -->` really as comments while it shouldn't...

### Preconditions (optional)

Having mail with body parts containing XML comment style blocks

```
<!--
blablabla...
-->
```

#### Reproduction Steps

- Send a mail with xml comment blocks
- Read mail with TMail
- What's inside those commented xml blocks is not rendered in TMail

### Context

- Environment: production (tmail.linagora.com)
- Apps: tmail-web and iOs tmail app

### Additional information

[format_issue_tmail.webm](https://github.com/linagora/tmail-flutter/assets/9005025/9eef8a7c-eef0-4e54-abb2-2c8bdf19713d)

**Comment by dab246** [comment]
Please provide more `eml` file so we can get more information about it.

**Comment by chibenwa** [comment]
See https://github.com/linagora/tmail-flutter/issues/309

**Comment by chibenwa** [comment]
Issue: text plain is rendered directly as HTML

HTML rendering needs to be turned off for text plain.

**Comment by Arsnael** [comment]
@dab246 
[message.zip](https://github.com/linagora/tmail-flutter/files/11650942/message.zip)

**Comment by chibenwa** [comment]
Ping

**Comment by QuangHoang1210** [comment]
Passed
