### ISSUE TITLE
[Dev] Update status sending email in sending queue

### ISSUE THREAD

**Issue by dab246** [linagora/tmail-flutter#1915]
### DoD

- Design: https://www.figma.com/file/rRVxJpCu1G22D0jqyvK7I9/TeamMail?type=design&node-id=11070%3A410803&t=QCePG6Nxv0Fw7vqw-1

### Desc

2 state: 

- `Delivering`: Sending email has been pushed to work manager and is waiting to be done.
- `Error`: Work manager took action with sending email but failed or reported error

**Comment by QuangHoang1210** [comment]
Retest again on next version once Offline mode issues are fixed

**Comment by QuangHoang1210** [comment]
Verified on 0.8.3 -> Getting issue in AC error status https://github.com/linagora/tmail-flutter/issues/1971
