### ISSUE TITLE
[Story] Because TeamMail support app can run in offline mode, so the connection status need to optimized and avoid to prevent user in using app

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#1917]
### Toast: No connection - Connection status

**No connection**

AC1:  No connection toast will be displayed and hide following rule bellow:
```
GIVEN I'm Tmail user
WHEN I turn off network
AND I open Tmail application
THEN System display a toast : No connection with red background
AND It will be disappeared after 5 second or it will be disappeared immediately once user do any action except (view other mailboxes / Infinity scroll to load more email)
```

AC2:  No connection toast will be displayed again
```
GIVEN I'm in offline mode with Tmail application
AND the No connection toast is already disappeared
WHEN I tap to view other mailboxes or scroll to load more email
THEN No connection toast will be displayed again and keep the rule same with AC 1
```

AC3:  Toast when re-connect network
```
GIVEN I'm opening Tmail application
AND I'm in offline mode
WHEN I re-connect the network
THEN nothing happen
AND I can use Tmail normally
```

**Comment by hoangdat** [comment]
@QuangHoang1210 please help us to analyze it and do the mockup. Thanks and BRs

**Comment by dieptran88** [comment]
As my under standing, The circle will always be there and its color will be depended on network status ? I dont think user can understand a circle is representative for network status. 
My suggestion is that we still keep displaying toast messages but it will be hidden/shown upon user' actions, for example when it is offline, user scrolls down to reload => toast message shown. When user scrolls up, it does not show error toast

**Comment by QuangHoang1210** [comment]
already update the AC -- Please review it @dieptran88
