### ISSUE TITLE
[Offline Mode] User stuck in the reloading screen when try to access to Tmail once reconnect the network

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#1924]
OS:  IOS / Android
Device: Mobile
TMail version: 0.7.11

*Precondition: 
- User A is offline and Tmail is not running in background or foreground

### *Reproduce Step:
1, User A is open TMail in offline mode
2, User A click on Skip at No connection error msg
3, User A turn on the network

### **Actual:** 
User A is getting stuck in reloading screen. He cannot access the TMAIL normally except close the TMAIL and reopen again.

### **Expected:** 
User A can access the TMAIL application normally once the network is reconnect

https://github.com/linagora/tmail-flutter/assets/124866146/307679e5-ffa4-481f-a8a0-402cc6ae4d2f

**Comment by dab246** [comment]
Waiting version 0.8.0

**Comment by QuangHoang1210** [comment]
Working well on 0.8.0
