### ISSUE TITLE
[EmailDetailed] Email content, attachments disappear when there are many recipient addresses

### ISSUE THREAD

**Issue by dab246** [linagora/tmail-flutter#1927]
### Description

```
When open email detailed
Then click `arrow down` button of recipient addresses
```

Email content, attachments disappear 

### Expected result

Email content, attachments appear 

### Current behavior

![Image](https://user-images.githubusercontent.com/80730648/245345551-c57932f8-e5b1-4462-baf6-460c52318377.png)

**Comment by hoangdat** [comment]
@hknguyen can you take a look

**Comment by hoangdat** [comment]
limit the max height of this field and support scrollable
