### ISSUE TITLE
[Sending Queue] Tmail app is crashed when user click on [Proceed] button to send email in offline mode from 5 to 6 times

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#1934]
OS:  IOS / Android
Device: Mobile
TMail version: 0.8.0

*Precondition: 
- User try to send email in offline mode several times
- It only happen on Android 10 , not happen on Android 13

*Device information: 
- Redmi Note 8
- Android 10

![Image](https://user-images.githubusercontent.com/124866146/245990914-840c1136-799f-4f85-9459-540cf5c7d20c.png)

### *Reproduce Step:
1, User A is offline
2, User A click on Compose
3, User A type email address
4, User A type subject
5, User click Send
6, User click [Proceed] button

### **Actual:** 
App is crashed. The email is not move to sending queue

### **Expected:** 
App is smoothly. The sent email come to sending queue

https://user-images.githubusercontent.com/124866146/245991343-7d58eefc-38c0-4580-a3fb-bda78d22cfb8.mp4

**Comment by dab246** [comment]
Cannot reproduce. We will test again in the new version

**Comment by QuangHoang1210** [comment]
Cannot reproduce
