### ISSUE TITLE
OIDC for WEB: customize scope

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#1935]
### Description

As an administrator I want to configure a specific scope for my OIDC set up.

EG: `openid profile email` instead of the defaults.

### Definition of done

A property for this in env.file:

```
WEB_OIDC_SCOPE=openid profile email
```

**Comment by hoangdat** [comment]
will be resolved in 0.8.1

**Comment by QuangHoang1210** [comment]
Question: 

![Image](https://github.com/linagora/tmail-flutter/assets/124866146/c5e70b53-04ce-4dba-88c6-792823ce2efd)
