### ISSUE TITLE
[Bug] Filter "With attachments" isn't applied straight away

### ISSUE THREAD

**Issue by tprudentova** [linagora/tmail-flutter#1937]
•	Bug occurred time: 15/06/2023
•	Environment(version): tmail.upn.integration-open-paas.org (0.8.0)
•	Steps to reproduce:
1.	Select filters -> With attachment
2.	No results are in the list
3.	Unselect the filter
4.	Scroll down to reach the letters with attachments 
5.	Select filters -> With attachment
6.	You see the corresponding results
=> Expectation
I see the results without scrolling down first
•	Image/Video evidence:

https://github.com/linagora/tmail-flutter/assets/97684890/0a33ae5f-a861-49c5-b5e6-3ecbcdad8d77

**Comment by hoangdat** [comment]
fixed
