### ISSUE TITLE
[Improvement] Only one line of email body is visible if a file is attached in the collapsed view of email composer

### ISSUE THREAD

**Issue by tprudentova** [linagora/tmail-flutter#1944]
•	Environment(version): tmail.upn.integration-open-paas.org, 0.8.0 Google Chrome, Mac
•	Steps to reproduce:
1.	Open email composer in collapsed view
2.	Attach a file
3.	Only one line of the email body is visible after that
•	Image/Video evidence:

https://github.com/linagora/tmail-flutter/assets/97684890/ec22fc83-37d1-42f7-a95f-3036e61ccf98

**Comment by tprudentova** [comment]
<img width="1280" alt="Screenshot 2023-06-15 at 15 55 02" src="https://github.com/linagora/tmail-flutter/assets/97684890/cf6e905d-2094-4974-b1a9-7c4f14ca1e00">
<img width="1280" alt="Screenshot 2023-06-15 at 15 55 31" src="https://github.com/linagora/tmail-flutter/assets/97684890/01199742-f7bf-48ea-8882-936ee09aae85">
You can check the way it's done in gmail and yandex mail, maybe something like that would be nice?

**Comment by chibenwa** [comment]
Please share your screen resolution

**Comment by tprudentova** [comment]
@chibenwa hello! It's 13,3-inch (2560 × 1600)

**Comment by dab246** [comment]
Implement at #2116
