### ISSUE TITLE
Swipe left in unread item of ThreadView

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#1946]
### DoD:
- [ ] only UI 
- [ ] implement the swipe left action in unread item in ThreadView
- [ ] adding the view like that for mobile/tablet

![Image](https://user-images.githubusercontent.com/6462404/246723317-dfd487cc-6725-4aa0-a9ff-7b2935963a46.png)

![Image](https://user-images.githubusercontent.com/6462404/246723410-aa3a1616-cce9-4ab4-b48d-811e23d23d44.png)

### Design

- https://www.figma.com/file/rRVxJpCu1G22D0jqyvK7I9/TeamMail?type=design&node-id=9406%3A385519&mode=dev

**Comment by QuangHoang1210** [comment]
Passed on canary 0.9.3
