### ISSUE TITLE
Swipe left in read item of ThreadView

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#1947]
### DoD:
- [ ] only UI
- [ ] implement the swipe left action in read item in ThreadView
- [ ] adding the view like that for mobile/tablet

![Image](https://user-images.githubusercontent.com/6462404/246723931-da3d56b4-f681-481d-ac5f-2a1f7fbdbbda.png)

![Image](https://user-images.githubusercontent.com/6462404/246723972-9f6d6c9d-eee8-4662-b5d9-642c4092afbf.png)

### Design

- https://www.figma.com/file/rRVxJpCu1G22D0jqyvK7I9/TeamMail?type=design&node-id=9406%3A385519&mode=dev

**Comment by QuangHoang1210** [comment]
passed on canary 0.9.3
