### ISSUE TITLE
Android: no signature displayed in composer

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#1952]
### Description

Given I write an email in android v0.7.8 the signature is added only when sending the mail.

When I compose my email I cannot view / edit the signature.

### Expected result

I expect to view / edit the signature when editing the mail.

### Current behavior

https://github.com/linagora/tmail-flutter/assets/6928740/45928090-048b-416b-8aa7-337465d5542b

Bonus: the app crashed!

### Context

Android v0.7.8 on jmap.linagora.com

**Comment by hoangdat** [comment]
for mobile, we automatically hide the signature to save the editor room. Hope to find the better UX for that @dab246

**Comment by hoangdat** [comment]
@QuangHoang1210 please help us test the crashed (must test also send to the sender)

**Comment by dab246** [comment]
> for mobile, we automatically hide the signature to save the editor room. Hope to find the better UX for that @dab246

That's right, It's not an error. Currently we only show signatures for devices with large screen sizes like `Tablet/Desktop/Web`. `Mobile` will not show the signature in the editor, but you can still select `Identity`. And the signature is automatically added to the email after the user sends or saves the draft

**Comment by chibenwa** [comment]
IMO this makes little sense...

It is as if, when I reply to an email, you where hidding to me the quoted email because it takes room into the composer, and add it on the fly when I send an email...

Please show the signature on mobile.

**Comment by dab246** [comment]
> IMO this makes little sense...
> 
> It is as if, when I reply to an email, you where hidding to me the quoted email because it takes room into the composer, and add it on the fly when I send an email...
> 
> Please show the signature on mobile.

Ok, we will fix it as soon as possible.
