### ISSUE TITLE
[RTL] Cursor is not moving correctly to the left/right when user use keyboard to move the cursor < >

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#1955]
OS:  Website
Device: Laptop
TMail version: 0.8.2 - [canary](https://canary-tmail.linagora.com/)

*Precondition: 
- Select Arabic language on Account Manager Setting > Languages
- Input Arabic words: أنا كوا   أنا كوانجأنا كوانجنج

*Note:
This issue is happen on all input fields

### *Reproduce Step:
1, User input arabic words "أنا كوا   أنا كوانجأنا كوانجنج" on one of the input fields on every Tmail screen
2, User press < > on keyboard to move the cursor to the  left/right

### **Actual:** 
1, User press < on keyboard ==> Cursor move to the right
2, User press > on keyboard ==> Cursor move to the left

### **Expected:** 
1, User press < on keyboard ==> Cursor move to the left
2, User press > on keyboard ==> Cursor move to the right
<Already compare with other email clients with Arabic languages>

https://user-images.githubusercontent.com/124866146/247698725-c2b38fc5-6c70-4246-bce5-c6b9e1c07735.mp4

**Comment by dab246** [comment]
Follow more https://github.com/flutter/flutter/issues/78660
