### ISSUE TITLE
Form validation in Login form

### ISSUE THREAD

**Issue by hantt12** [linagora/tmail-flutter#196]
Currently there is no validation in Login form. I tested a few cases:

1. Incorrect server url
2. Incorrect username
3. Incorrect password

Currently app just resets the form without showing any message
Not sure this is a bug or an improvement

**Comment by Kevinle2312** [comment]
Failed on CI platform. No message pop up when the user type in the wrong credential information or mail server address.

**Comment by Kevinle2312** [comment]
> can you share the proof?

This is the test case: 
- wrong mail server
- wrong id
- wrong password


https://user-images.githubusercontent.com/32490981/170664742-e0ac9da5-8bf2-46aa-b9bd-f9f2d68fab49.mp4
