### ISSUE TITLE
Double scroll bar in the editor

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#1962]
### Current behavior

![Screenshot from 2023-06-22 13-18-56](https://github.com/linagora/tmail-flutter/assets/6928740/3a53a64e-3c57-4867-b9eb-3af62e56d690)

Double scroll bar spotted when answering 
[truncated-eml.txt](https://github.com/linagora/tmail-flutter/files/11829533/truncated-eml.txt)

### Expected result

Only one scroll bar.

### Context

Web tmail.linagora.com chromium v0.8.2

**Comment by nqhhdev** [comment]
@chibenwa Pls give me .eml file. Thank you!

**Comment by chibenwa** [comment]
![Screenshot from 2023-06-22 14-54-12](https://github.com/linagora/tmail-flutter/assets/6928740/e055f71e-f8c5-42bd-8882-22dfbcc6552f)

Read more carefully please

**Comment by dab246** [comment]
> ![Screenshot from 2023-06-22 14-54-12](https://user-images.githubusercontent.com/6928740/247863231-e055f71e-f8c5-42bd-8882-22dfbcc6552f.png)
> 
> Read more carefully please

Why don't you `compress` it under the `.eml` file. File `.txt` it will be inaccurate and difficult for us to reproduce.

**Comment by chibenwa** [comment]
[Tr.Alexandre.Blick.Rothenberg.Seminar.IR35.Regulations.the.practical.aspects.-.Alexandre.ZAPOLSKY.azapolsky@linagora.com.-.2023-06-21.1936.zip](https://github.com/linagora/tmail-flutter/files/11832318/Tr.Alexandre.Blick.Rothenberg.Seminar.IR35.Regulations.the.practical.aspects.-.Alexandre.ZAPOLSKY.azapolsky%40linagora.com.-.2023-06-21.1936.zip)

**Comment by QuangHoang1210** [comment]
Already reproduce -- It happens only with this kind of email
- Both Chrome and Firefox
@dab246

**Comment by dab246** [comment]
Fixed at #2093. Work fine on v0.9.0
