### ISSUE TITLE
Unexpected text is added to email content

### ISSUE THREAD

**Issue by hantt12** [linagora/tmail-flutter#197]
This issue does not always happen but it happened once when I test. 
"Sending from Gmail" text is automatically added to the email body 

![image_2021_10_18T09_42_33_285Z.png](https://images.zenhubusercontent.com/5ee9def7c40b48447a4362e2/8b9cf402-f8aa-43a4-8775-e4fb6425a33d)

**Comment by chibenwa** [comment]
Can you share the TMail display for this?

**Comment by chibenwa** [comment]
Thunderbird display

![Screenshot from 2021-10-19 10-14-47](https://user-images.githubusercontent.com/6928740/137840035-c599bae2-978f-40c4-8bad-b84b96a9bf59.png)

Tmail display:

![Screenshot_20211019-103829_Team Mail](https://user-images.githubusercontent.com/6928740/137840051-1e3f0d00-ab3a-48e5-a905-966da00974b7.jpg)


I would say it looks like we look good. QA you agree?

**Comment by hantt12** [comment]
But why do we have “sending from Gmail” text? I didn’t input mail body when I sent the email

**Comment by chibenwa** [comment]
Closing because the text also appears in thunderbird: this is in no way a TMail problem.

**Comment by chibenwa** [comment]
No the email was written in GMail, correct?

**Comment by chibenwa** [comment]
No!

```
Received: from 172.17.0.1 (EHLO incoming.linagora.com) ([172.17.0.1])
          by incoming.linagora.com (JAMES SMTP Server ) with ESMTP ID 1640832626
          for <tlle@linagora.com>;
          Mon, 18 Oct 2021 09:36:08 +0000 (GMT)
Received: from smtp.linagora.com (smtp.linagora.com [54.36.8.78])
	by incoming.linagora.com (Postfix) with ESMTPS id 539539C401
	for <tlle@linagora.com>; Mon, 18 Oct 2021 09:36:08 +0000 (UTC)
Received: from ?Open?PaaS?SMTP?server?for?Linagora? (unknown [51.83.109.124])
	(using TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits))
	(No client certificate requested)
	by smtp.linagora.com (Postfix) with ESMTPSA id C529C41896
	for <tlle@linagora.com>; Mon, 18 Oct 2021 10:12:31 +0200 (CEST)
```

This proves the EMail only transited by linagora email infrastructure...

**Comment by chibenwa** [comment]
```
$ grep Gmail * -R
[no results]
```

WTF !

**Comment by hantt12** [comment]
> Let me make it clear:
> 
> 1. Compose mail by TeamMail (sender account)
> 2. Open that email in thunderbird (recipient account)
> 3. `Sending from Gmail` is appended?
> 
> Am I right? @hantt12

1. Email is sent from Tmail
2. Email is opened in whatever email client you can (openpaas , thunderbird, even Tmail...)
3. "Sending from Gmail" text is there

**Comment by Kevinle2312** [comment]
Passed on the Production platform.
