### ISSUE TITLE
[Offline Mode] [Sending Queue] There is no status of email which get error in sending queue

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#1971]
OS:  Android
Device: Mobile
TMail version: 0.8.3

*Precondition: 
- User A is offline 
- User send / foward / reply an email but the email address is invalid

### *Reproduce Step:
1, User A send / foward / reply an email in offline mode but the email address is invalid
2, User A click [Proceed] button in popup Sending Queue
3, User A reconnect network

### **Actual:** 

- Emails which in Sending Queue is sent. 
- But some email is invalid is cannot send but don't have any error status for it
- Some invalid email is being bold text

### **Expected:** 

- Emails which in Sending Queue is sent. 
- If email cannot send -> displayed error status
- Some invalid email is not being bold text

https://github.com/linagora/tmail-flutter/assets/124866146/47e73cff-0b81-49db-ae92-e5efe44adffb

**Comment by hoangdat** [comment]
<img width="398" alt="Screenshot 2023-08-02 at 09 43 06" src="https://github.com/linagora/tmail-flutter/assets/6462404/8b4b50db-4595-4748-b1c5-505d984fb014">

**Comment by QuangHoang1210** [comment]
Passed on Android --- Not yet ready on IOS
