### ISSUE TITLE
UPCOMING breaking changes

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#1975]
You MUST be informed that RFC-9425 involves some minor changes compared to the previou drafts.

The tests in the diff are informative regarding those changes.

Namely:
 - limit -> hardLimit
 - types -> dataTypes

So far the mobile app will need to handle both.

IE Read hardLimit first and fallback to limit if empty. Same with dataTypes, fallback to types.

This is important to contribute this change as early as possible to the JMAP dart client so as to maintain the widest possible applicative compatibility.

CF https://datatracker.ietf.org/doc/rfc9425/

**Comment by hoangdat** [comment]
will do in #2063
