### ISSUE TITLE
[Barcamp] Create folder - How to create filter easier

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#1983]
### Desc:
- Create action in context menu
- Create action inside folder list

**Comment by dieptran88** [comment]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC

* TODO: {link}

## Definition

- Given that I am an Tmail user 

[Back to Summary](#summary)

## Screenshots

None

[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

**Comment by dieptran88** [comment]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC

* TODO: {link}

## Definition

- Given that I am a Tmail user 
- After logged-in successfully to Tmail, I can click button Create a new folder 
- I input folder name then click button Done, the new folder is created 
- I am redirected to this new folder 
- In the folder, there is a blank page without any email. I can see a button :"Create filter" in this page 
- When I click button "Create filter", the screen "Create new rule" will be opened. 
- On the new rule screen, I can see on the " Perform following action " part, the default selection is "Move message" to "New created folder". 

[Back to Summary](#summary)

### Screenshots

### Web 
![Group 863 (1)](https://github.com/linagora/tmail-flutter/assets/68209176/8cfd4356-ca4d-4c5f-9eea-cfca971d13ce)
![Group 864](https://github.com/linagora/tmail-flutter/assets/68209176/f57f8400-2e55-4ed1-b59f-357c2ce122d7)

### Mobile 
![image](https://github.com/linagora/tmail-flutter/assets/68209176/52abd02f-858c-4cab-b260-87198977a9c5)  ![image](https://github.com/linagora/tmail-flutter/assets/68209176/c72425b4-4868-4906-a05e-4954179c9597)




[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

**Comment by dieptran88** [comment]
@hoangdat My question is , currently our system will not applied the rule for current messages. So  after creating new rule, what will happen? It still shows blank page of folder or it will open the filter listing screen ?
=>> My suggestion: After create rule successfully, there is toast message: "New filter was created" and a button Open next to it> When I click this button Open, it will show filter listing screen. Otherwise it will stay at the folder .

**Comment by hoangdat** [comment]
![Image](https://github.com/linagora/tmail-flutter/assets/6462404/0281a7c8-f8cb-4fd5-9d42-18b8b273b541)

**Comment by hoangdat** [comment]
Design: https://www.figma.com/file/XqLqMINlZw09BdEHI8yLb9/Teammail---1.1?type=design&node-id=284-34959&mode=design&t=81niOMGDMcO644Pq-4
