### ISSUE TITLE
[Barcamp] Counter for Trash/Spam + empty action for Sent/Trash/Spam

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#1984]
### Desc:
- Show counter for all item in `Trash`, `Spam`
- Quick action for `empty Trash/Spam` in left menu

**Comment by dieptran88** [comment]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC

* TODO: {link}

## Definition

-  GIVEN that I am a Tmail user
-  WHEN I logged in successfully
-  THEN I can see the counter of total items of Trash folder if the number of items is more than 0
-  When there is at least one email in Trash folder, there will be an button "Empty" next to the counter. It there is no Trash email, this button is not displayed
- I click "Empty" button on Trash folder, there will be a confirmation popup "You are about to permanently delete all items in Trash. Do you want to continue?"
- If I choose Yes, all item in Trash folder will be deleted permanently

[Back to Summary](#summary)

## Screenshots
### Web 

![Group 862](https://github.com/linagora/tmail-flutter/assets/68209176/416e5119-3ae9-4cd2-a13e-62ee821be140)
![image 190](https://github.com/linagora/tmail-flutter/assets/68209176/eddc9108-48fa-4934-a4fb-e1e9a156bf2e)


### Mobile

![image](https://github.com/linagora/tmail-flutter/assets/68209176/9cdfa3eb-08ce-4cf2-b10c-7e2c00729bc6) 
![image](https://github.com/linagora/tmail-flutter/assets/68209176/36fd9ee7-8253-451c-b456-03eee5881854)


None

[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

**Comment by dab246** [comment]
Same #1792

**Comment by dab246** [comment]
https://www.figma.com/file/rRVxJpCu1G22D0jqyvK7I9/TeamMail?type=design&node-id=9406%3A385520&mode=design&t=9JPQaCvvYJmcXN9l-1

**Comment by QuangHoang1210** [comment]
Passed on Canary 0.9.3
