### ISSUE TITLE
[Barcamp] Test TeamMail on Safari

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#1987]

**Comment by QuangHoang1210** [comment]
![Image](https://github.com/linagora/tmail-flutter/assets/124866146/281d27c1-f8e7-49f2-8c3f-068a2c951853)


Cannot access c3po with Safari

**Comment by chibenwa** [comment]
Cache issue maybe?

Safari version?

**Comment by hoangdat** [comment]
Please clean the cache and re-test

**Comment by QuangHoang1210** [comment]
Idk why I cannot upload video on this comment -  I upload video evidence to Linagora drive: https://drive.google.com/file/d/1dIwg-jD5XllFk1J1dXQoJaQ6C8oom8Jq/view?usp=sharing

![image](https://github.com/linagora/tmail-flutter/assets/124866146/ee88c8ac-4456-408a-a56d-4fc4643fa333)

@dab246  @chibenwa

**Comment by hoangdat** [comment]
@chibenwa confirmed. this error come back

**Comment by chibenwa** [comment]
Fixed (avoid the redirect at the Apisix level on backend side)
