### ISSUE TITLE
[Barcamp] Has attachment checkbox is overflow once it be translated in russia

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#1993]

**Comment by dab246** [comment]
@hoangdat  IMO, we should leave the checkbox button in 1 line to avoid overflow. Because the width of advanced search view is not enough space for long text. WDYT?

![Image](https://github.com/linagora/tmail-flutter/assets/80730648/1f0e7e99-c014-4bc8-a231-28d80f0c8e88)

**Comment by QuangHoang1210** [comment]
Passed
