### ISSUE TITLE
[Story] As an user, i want to search a specific folder (mailbox)

### ISSUE THREAD

**Issue by dieptran88** [linagora/tmail-flutter#2]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Technical issues](#technical-issues)
* [Misc](#misc)

## Definition

- Given that i am a Tmail user and i already had an account
- Given that i log-in successfully to the Tmail app
- I can see the default view is "Inbox" folder
- when i click on screen title "Inbox", i can see the listing mailboxes screen.
- In listing mailboxes screen, i can see a search bar 
- I touch the search bar, the keyboard will appear
- when I start typing in the search bar, the app will display result as a list under search bar
- The result will updated instantly when i am typing 
- The search result contains folders in ALL  level of folder tree. 
- If a mailbox of ANY level contains the search pattern then it should be displayed with its parent.
- The mailbox list result will be highlighted (bold text?)

[Back to Summary](#summary)

#### Final design

![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/87f4aa93-042e-4eff-b399-ddb1f8277e80)   
![image](https://user-images.githubusercontent.com/68209176/132978497-38f28cdc-b66a-4ab2-8960-fde3a27e7a56.png)

[Back to Summary](#summary)

## Technical issues

[Back to Summary](#summary)

## Misc

[Back to Summary](#summary)

UI Design: https://www.figma.com/file/QoVfZgIEtOq8DI2lyI2aX3/TMail-App?node-id=53%3A37

**Comment by hoangdat** [comment]
please add the result screen when matched mailboxes is sub-folder

**Comment by hknguyen91** [comment]
I suggest an additional case that we can search folders in normal search like what Google does.
![thread view](https://user-images.githubusercontent.com/95336527/150297776-ca3ed599-a376-4547-9961-0e0aea2dae43.png)

**Comment by dieptran88** [comment]
To do that, mail app need to recognize the text that user inputted is matched with one current folder and give the suggestion. Otherwise it will be not convenient for user. 
@hoangdat WDYT?

**Comment by chibenwa** [comment]
I am not that fan of mixing search for inbox and search for folders.

@hknguyen91 example of other email apps doing this?
