### ISSUE TITLE
[View email details] User cannot swipe to view the next email details after loading more email by infinity scroll

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#2004]
OS: IOS/Android
Device: Laptop
TMail version: 0.8.3 

*Precondition: Open an email to view details then swipe left to view the next one

### *Reproduce Step:
1, User open an email to view details
2, User swipe left 19 times to see the last email in the first loading
3, User tap on back to inbox
4, User scroll to load more email
5, User tap on 20th email to view and keep swipe left to view the next details email 

### **Actual:** 
Nothing happen when user swipe.

### **Expected:** 
User can keep swipe left to view the next one
User can keep swipe right to view the previous one

https://user-images.githubusercontent.com/124866146/250882166-b9024ee0-b2ed-46d9-ace4-05fd474cfcc4.mp4

**Comment by dab246** [comment]
Followed reproduce step. The result works fine on version `0.9.1`
