### ISSUE TITLE
Retrieve default language from browser/device setting before falling back to english

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#2007]
### Description

Given I am a franch lawyer, with french turned on everywhere on my laptop.

By default, TMail is in english.

I need to go to settings to change it to French.

### Expected result

Upon initial load, TMail should look at browser default language, and use that default language in the App in priority.

EG for the lawyer, the App should be in French.

**Comment by hoangdat** [comment]
As we implemented, it work now, @QuangHoang1210 please help us verify it

**Comment by hoangdat** [comment]
### Settings in Chrome:

<img width="1295" alt="image" src="https://github.com/linagora/tmail-flutter/assets/6462404/f30e7637-7b6b-421a-a2dc-82538393d099">

### Result

<img width="598" alt="image" src="https://github.com/linagora/tmail-flutter/assets/6462404/2201f90a-5e00-405b-81b7-57751ec6bcfc">

**Comment by QuangHoang1210** [comment]
Verified  on TMail 0.8.2 -> Passed

https://github.com/linagora/tmail-flutter/assets/124866146/5916d490-11fc-48c3-b03f-a7cddb714c1c

**Comment by hoangdat** [comment]
@QuangHoang1210 please carefully to evaluate, maybe someone change the language of browser, but someone not, we need to see the behavior for almost the common case in desktop.
