### ISSUE TITLE
Deploy an TeamMail environment to work with `auth.tom-dev.xyz`

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#2016]
### Desc:
- we have a dev env for lemonLdap: `auth.tom-dev.xyz`
- But we dont have any dev environment have the integration `TeamMail + lemonLdap`
- Some days ago, we have some problem related to `refreshToken` in production and customer env also.
- We want to reproduce it in dev platform

### DoD:
- [ ] have an enviroment for `TeamMail + lemonLdap`
- [ ] have the admin account to easily to config the client to reproduce the bug

**Comment by hoangdat** [comment]
cc @chibenwa @Arsnael and @guimard

**Comment by guimard** [comment]
Hi, do you ask for "offline" token ?

**Comment by hoangdat** [comment]
> Hi, do you ask for "offline" token ?

ohh, maybe missing it. Thanks. Investigate more

**Comment by Arsnael** [comment]
And why not using the on-commit env for that? It's expected to not be stable

**Comment by hoangdat** [comment]
yes, any env is ok too, we only need the integration with lemonLdap and the admin account to easier in configuration

**Comment by hoangdat** [comment]
done in local
