### ISSUE TITLE
[COMPOSER] Recipient input validation is hard when we have inaccurate auto-complete

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#2024]
### Description

When writing mails to new people, I can get innacurate suggestions.

Those bad suggestions prevents me from validating my input... By default pressing `ENTER` would validate the suggestion and not my input....

Only clicking outside of the selection zone validates my input which is counter intuitive.

### Expected result

Should be easy to validate my input if no suggestion matches...

### Current behavior

![Screenshot from 2023-07-11 00-37-21](https://github.com/linagora/tmail-flutter/assets/6928740/3203a1cc-d996-4b90-aa86-89b97547119c)

#### Reproduction Steps

Try to write a mail to `newcomer@linagora.com` ...

**Comment by hoangdat** [comment]
IMO:
- when have only one bad suggestion, and it is an email address, client should add one more suggestion which equal to what user inputted
- when this is the exactly one, no need to do anything

**Comment by chibenwa** [comment]
> when have only one bad suggestion, and it is an email address, client should add one more suggestion which equal to what user inputted

This was just an example but it already happened to me a couple of time.

**Comment by hoangdat** [comment]
Or one more filter layer in client side

**Comment by chibenwa** [comment]
> Or one more filter layer in client side

Could be...

If the user input matches `.*@.*\..*` ie contains `@` then contains `.` THEN completion input should be prefixed by user input.

EG

I type: `btellier@linagora.c` then autocomplete result `btellier@linagora.com` is shown but not `whatever@linagora.com` (not prefixed by the search input).

IMO it would be better to do such filtering on back side and just do nothing on front side. Agree @hoangdat ?

**Comment by hoangdat** [comment]
> I type: btellier@linagora.c then autocomplete result btellier@linagora.com is shown but not whatever@linagora.com (not prefixed by the search input).

you mean you will change in the back side? if yes, so great for us.

**Comment by dab246** [comment]
>
> IMO it would be better to do such filtering on back side and just do nothing on front side. Agree @hoangdat ?

+1 Respect for that
