### ISSUE TITLE
Selection on firefox

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#2025]
### Description

When I select a mail in firefox, then the selection icon is not shown, it is just **blank**.

### Expected result

We should do like in chrome, show that the email is selected.

### Current behavior

https://github.com/linagora/tmail-flutter/assets/6928740/14ff1f57-16a1-4ed9-a381-792751870b9d

### Context

0.8.5 firefox https://oncommit-tmail.linagora.com

**Comment by dab246** [comment]
@QuangHoang1210  Please verify help us. Thanks

**Comment by QuangHoang1210** [comment]
Passed on 0.9.1 and 0.9.0

![Image](https://github.com/linagora/tmail-flutter/assets/124866146/918cf1a2-42df-4480-9817-31e8e0c34bd4)



![Image](https://github.com/linagora/tmail-flutter/assets/124866146/02c5f91d-34d3-4da0-ae95-d114c9537404)
