### ISSUE TITLE
[COMPOSER] "Save as draft" should not close the composer

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#2026]
### Description

![Screenshot from 2023-07-11 15-54-31](https://github.com/linagora/tmail-flutter/assets/6928740/657f017d-3ce2-4f05-acd1-5c5d1f218a50)

**GIVEN** I type a very long and very import email

**THEN**  I want to periodically save my input

**AND** continue typing

### Expected result

I expect `Save as draft` button not to close the composer.

### Current behavior

I expect `Save as draft` save the draft and closes the composer.

 - 1. I cannot continue typing (unless I go in draft folder and reopen the draft)
 - 2. It duplicates in behaviour the `X` (close button) of the composer that also save a draft and the composer

**Comment by QuangHoang1210** [comment]
Passed on 0.9.3 canary
