### ISSUE TITLE
[LAGGY COMPOSER] Turn off composer logs by defaults?

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#2030]
Lot's of logs are not necessary and might make the composer laggy.

Can we turn off those logs by default?

It's ok to have an `env.file` entry to turn them on on development / Linagora internal deployments.

**Comment by hoangdat** [comment]
for the case of `env`, not in the codebase, but in building step in docker file

**Comment by hoangdat** [comment]
https://github.com/linagora/tmail-flutter/assets/6462404/01796aae-a0a5-4baf-9e1b-8aebb88d1460

Please also remove the log from `Toolbar`.

**Comment by QuangHoang1210** [comment]
Passed -> Quick report Composer Performance comparing

https://docs.google.com/spreadsheets/d/1Tuwbe0T2PyB29UBjxBZT5AL7216kLtuwuEkNrH_PO2s/edit?usp=sharing
