### ISSUE TITLE
Improve security for docker image: with app user only

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#2039]
### Desc:
https://docs.bridgecrew.io/docs/bc_k8s_37

**Comment by tk-nguyen** [comment]
We're using nginx docker image, which should run `nginx` process under [`nginx` user and group](https://github.com/nginxinc/docker-nginx/blob/4b0d808b8f320df132c154a974ebe46e9e5f5ffe/mainline/debian/Dockerfile#L16-L17). There should be no issue here.
