### ISSUE TITLE
[Link] Can not see the link when type is text/plain in email view

### ISSUE THREAD

**Issue by dab246** [linagora/tmail-flutter#2047]
## Desc

- TeamMail:

![Image](https://user-images.githubusercontent.com/80730648/254497145-722a0439-7290-4b7c-814c-4d49416175ce.png)

- OpenPaas

![Image](https://user-images.githubusercontent.com/80730648/254497777-139b94c5-5eaf-4a39-8c73-cc5f01490a40.png)

**Comment by hoangdat** [comment]
`v0.8.7`
