### ISSUE TITLE
[Notification] Missing notification on Mobile

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#2050]
OS:  IOS, ANDROID
Device: Mobiile
TMail version: 0.8.8

*Precondition: 
- User already login successfully on the application

### *Reproduce Step:
1, User already login and access on Tmail
2, User A send user B an email

### **Actual:** 
User B not receive any notification on both IOS and Android

### **Expected:** 
User B should receive notification

**Comment by dab246** [comment]
## Cases

1. Android Platform

- [x] Install new app => **Passed**
- [ ] Update from old version

2. iOS Platform

- [ ] Install new app
- [ ] Update from old version

**Comment by QuangHoang1210** [comment]
@hoangdat

**Comment by hoangdat** [comment]
Maybe the issue come from the new token when updated.
@QuangHoang1210 confirmed that Android have no problem when upgrade app via store.

**Comment by QuangHoang1210** [comment]
Noted for now: IOS is getting notification once receiving new email already.

**Comment by dab246** [comment]
- Android: `OK`
- iOS: `Investigate`

**Comment by dab246** [comment]
Work fine on `0.9.0`
