### ISSUE TITLE
[Email Threads] Tmail is not auto reload to display the newest email

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#2051]
OS:  IOS, ANDROID, WINDOW, OS
Device: Mobiile, LAPTOP
TMail version: 0.8.8

*Precondition: 
- User A send user B a new email

### *Reproduce Step:
1, User B is login successfully and keep stay on email thread view
2, User A send user B a new email
3, User B wait to see new upcoming email

### **Actual:** 
User B cannot see new email if not click on reload button

### **Expected:** 
New email is auto displaying on email thread view after few seconds.
User B can see new email.

https://user-images.githubusercontent.com/124866146/254974987-704391ac-f9df-4a62-acdf-81225ddbdf86.mp4

**Comment by QuangHoang1210** [comment]
Same with https://github.com/linagora/tmail-flutter/issues/1896

**Comment by hoangdat** [comment]
duplicated
