### ISSUE TITLE
[Dev] Update properties for Quota in jmap-dart-client

### ISSUE THREAD

**Issue by dab246** [linagora/tmail-flutter#2063]
## Story

https://github.com/linagora/tmail-flutter/issues/33

https://github.com/linagora/tmail-flutter/issues/1975

## Desc

- According to the standard documentation [rfc9425](https://datatracker.ietf.org/doc/rfc9425/) we need to add some properties for Quota
- Properties missing: `hardLimit`

**Comment by hoangdat** [comment]
please check the request here: https://github.com/linagora/tmail-flutter/issues/1975

**Comment by dab246** [comment]
Related: https://github.com/linagora/james-project/issues/4814
