### ISSUE TITLE
[Dev] Display banner when the quota reaches the limit

### ISSUE THREAD

**Issue by dab246** [linagora/tmail-flutter#2064]
## Story

https://github.com/linagora/tmail-flutter/issues/33

## DoD

- `warnLimit ~ 90%`

![Image](https://user-images.githubusercontent.com/80730648/257402501-fe939fae-671c-4c32-81d8-ab50ab60f9de.png)

- `hardLimit ~100%`

![Image](https://github.com/linagora/tmail-flutter/assets/80730648/62852627-c646-44a8-bfa9-3e0c17d9c0fa)

- Figma: https://www.figma.com/file/rRVxJpCu1G22D0jqyvK7I9/TeamMail?type=design&node-id=2%3A17&mode=dev

## Desc

- orange 90% -> `warnLimit`
- red 100% -> `hardLimit`

**Comment by chibenwa** [comment]
`Upgrade storage` button only makes sens for SAAS. 

Let's not put it now IMO...

**Comment by QuangHoang1210** [comment]
Pending -> Wait to test with #2038
