### ISSUE TITLE
[Calendar] [Improvement] As an Tmail user, I want to have a button to send an email to all invitees of the event

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#2073]
```
GIVEN I'm Tmail user
AND I want to have a button 'Reminder' which under the Calendar widget date
WHEN I click on Reminder button
THEN System open a composer 
AND Its address automatically fullfill all email address of invitees
```

Mockup:

![Image](https://github.com/linagora/tmail-flutter/assets/124866146/a1ba87ce-dccc-42a0-a366-33e75338936c)

**Comment by hoangdat** [comment]
@Arsnael, @chibenwa what do you think?

**Comment by chibenwa** [comment]
No. `Reminder` do not mean `mail to all`.

I would think that it should be located next to who and renamed "mail to attendees"

**Comment by Arsnael** [comment]
IMO, `reminder` means more "I want TMail to remind me (and not other invitees) that I have a meeting at that time"

Is a function like this really necessary though? I hardly see myself taking the time searching through my mails to send reminding emails a bit before a meeting to other attendees saying that hey we have a meeting starting soon don't forget, for something that I would expect people being able to manage their schedule and calendar good enough to be present anyways..?
