### ISSUE TITLE
[Filtering rule] Add/remove `condition`s in UI

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#2083]
### Desc:
- Design:

![Image](https://user-images.githubusercontent.com/6462404/259908011-9b1d3727-3938-4021-a716-8dfc2ae56e82.png)

#### Model:
- `RuleCondition`: rule_filter/lib/rule_filter/rule_condition.dart

#### View:
- `RuleFilterCreatorView`: lib/features/rules_filter_creator/presentation/rules_filter_creator_view.dart
- `RulesFilterCreatorController`: lib/features/rules_filter_creator/presentation/rules_filter_creator_controller.dart

#### Requirements:
- Try to reuse `condition` widget

![Image](https://user-images.githubusercontent.com/6462404/259909438-59433de1-7fd2-4800-bf3a-a7e6efdf05f8.png)

### Technical

- Create new StatelessWidget `RuleFilterConditionWidget` class. To display

![Image](https://user-images.githubusercontent.com/6462404/259909438-59433de1-7fd2-4800-bf3a-a7e6efdf05f8.png)

`RuleFilterConditionWidget` included: 
  - `DropDownButtonWidget`: Widget that displays a list of `Field`
  - `DropDownButtonWidget`: Widget showing the list of `Comparator`
  - `RulesFilterInputField`: Input the value `Condition`

- In `RulesFilterCreatorController`,  replace `ruleConditionFieldSelected` and `ruleConditionComparatorSelected` to `listRuleCondition`: List of conditions
```
final listRuleCondition = RxList<RuleCondition>();
```

Every time `+ Add condition` is clicked add an element to `listRuleCondition`

Trigger variable `listRuleCondition` in `RuleFilterCreatorView` 

```
Obx(() {
 return ListView.builder(
      itemCount: listRuleCondition.length,
      itemBuilder: (context, index) => RuleFilterConditionWidget(listRuleCondition[index]),
    );
})
```

### DoD:
- [ ] can click `+` to add more condition
- [ ] can click `-` to remove condition
- [ ] demo for all mobile/tablet/web

**Comment by Arsnael** [comment]
Not related to the ticket, but regarding the design, just the `+ Add condition` on the actions section should be `+ Add action` instead :)

But thanks for the ticket @hoangdat I will try to get starting on it today

**Comment by hoangdat** [comment]
> + Add condition on the actions section should be + Add action instead :)

Raised to design team.

**Comment by hoangdat** [comment]
@dab246 please more detail in technical description

**Comment by Arsnael** [comment]
@hoangdat I think we concluded yesterday this isn't a good first issue?

All the logic layers, from the view, passing to the controller, all the way down to the API level, are all based on one unique condition in the code. Allowing multiple requires quite the refactoring I believe, and a bit of a complex one. (would be probably true for the ticket allowing multiple actions as well)

**Comment by hoangdat** [comment]
ok, I will assign it to @hieutbui , and hope you can follow it to review and help him :)))

**Comment by Arsnael** [comment]
Newcomer? I feel bad for him now ^^'

**Comment by hieutbui** [comment]
IM worry :_(

**Comment by dab246** [comment]
https://www.figma.com/file/XqLqMINlZw09BdEHI8yLb9/Teammail---1.1?type=design&node-id=284%3A34937&mode=design&t=KirVajmGVX5Vd2sd-1
