### ISSUE TITLE
[Filtering rule] Add/remove `actions` in UI

### ISSUE THREAD

**Issue by nqhhdev** [linagora/tmail-flutter#2084]
### Desc:
- Design:

![Image](https://user-images.githubusercontent.com/99852347/259919204-55820eb2-26ab-4883-86ce-c0fc1d913df5.png)

#### Model:
- `EmailRuleFilterAction`: lib/features/rules_filter_creator/presentation/model/email_rule_filter_action.dart
```
enum EmailRuleFilterAction {
  moveMessage,
  maskAsSeen,
  startIt,
  rejectIt,
  markAsSpam,
  forwardTo;
}
```

#### View:
- `RuleFilterCreatorView`: lib/features/rules_filter_creator/presentation/rules_filter_creator_view.dart

- `RulesFilterCreatorController`: lib/features/rules_filter_creator/presentation/rules_filter_creator_controller.dart

#### Requirements:
- Try to reuse `condition` widget with action

![Image](https://user-images.githubusercontent.com/99852347/259919995-f77745a5-b99d-4b57-820c-dde18ce4371a.png)

### DoD:
- [ ] can click `+` to add more action
- [ ] can click `-` to remove action
- [ ] Demo on mobile/tablet/web

**Comment by Arsnael** [comment]
Careful of the bad copy/paste of descriptions... Talking about actions here, not conditions :P

**Comment by hoangdat** [comment]
- make sure no duplicated actions were selected

**Comment by hieutbui** [comment]
There are a few issues with backend and UI: 
- There is no forwardTo in Filter API but withKeyWords is found as String[] with no UI for it.
- Since moveTo allows users to select Spam mailbox in UI, is markAsSpam really necessary (logic for markAsSpam is the same with moveTo: using appenIn directived)

Docs for Filter/set:
![image](https://github.com/linagora/tmail-flutter/assets/80142234/fca97178-c643-4825-8ed2-cdaa1485fa8a)
![image](https://github.com/linagora/tmail-flutter/assets/80142234/ce7762dd-40a5-46ae-823f-34782318ea32)

**Comment by chibenwa** [comment]
> There is no forwardTo in Filter API but withKeyWords is found as String[] with no UI for it.

@Arsnael we caan add a `forwardTo` action that replace current email address with an array of other mail addresses ?

It is not implemented on the backend side but easily can be. I will create the issue. You can skip this for now.

> Since moveTo allows users to select Spam mailbox in UI, is markAsSpam really necessary (logic for markAsSpam is the same with moveTo: using appenIn directived)

Yes it is as it saves user one click, and do not require him to know and remeber how "mark as spam" is implemented.

**Comment by QuangHoang1210** [comment]
@hieutbui 
Wording issue: 
[] Need to change "Start it" to "Star it"



![Image](https://github.com/linagora/tmail-flutter/assets/124866146/6ba66fc4-ed99-48f7-b5c5-bb1660a90aec)



![Image](https://github.com/linagora/tmail-flutter/assets/124866146/32004a5c-e2d3-4307-b764-d7478bd372ea)
