### ISSUE TITLE
[Filtering Rule] action validation when selecting actions

### ISSUE THREAD

**Issue by nqhhdev** [linagora/tmail-flutter#2086]
### Desc:
- Design:

![Image](https://user-images.githubusercontent.com/99852347/259920462-265761ae-c986-4f79-ada1-380a742e9483.png)

#### Model:
- `RuleCondition`: rule_filter/lib/rule_filter/rule_action.dart

#### View:
- `RuleFilterButtonField`: lib/features/rules_filter_creator/presentation/widgets/rule_filter_button_field.dart

#### Requirements:

- Display UI according to selected actions

![Image](https://user-images.githubusercontent.com/99852347/259921263-b6b82d8c-ba38-4114-927a-ddcc28ad70a4.png)

### DoD:
- [ ] Add action
- [ ] Can select action
- [ ] Check the conditions after selecting actions => show error
- [ ] Write unit test

**Comment by hoangdat** [comment]
- Separate ticket for creating widget for each action
