### ISSUE TITLE
Signature delimiter shold be dash - dash - space

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#2092]
### Description

https://pthree.org/2010/09/21/email-netiquette-part-4/ customer wants to stick to netiquette

Thus accordingly to them the signature separator shall be `-- ` and not just `--` as it is today.

Nitpicking but thats a easy feedback to take into account.

**Comment by chibenwa** [comment]
cc @hoangdat

**Comment by chibenwa** [comment]
![image](https://github.com/linagora/tmail-flutter/assets/6928740/7a369074-b631-4740-9d0d-211cc16bb4c0)

**Comment by chibenwa** [comment]
(only dash dash on oncommit-tmail.linagora.com)

**Comment by QuangHoang1210** [comment]
### Reproduce on tmail 0.9.1 canary @dab246  -> Reopened this ticket

1, Config the signature in Profile
2, Click on Composer
3, Focus on the header of signature

**Actual**: It still being dash+dash
**Expected**: dash+dash+space

https://github.com/linagora/tmail-flutter/assets/124866146/a3190d41-d739-43a5-a697-a83e44f81407

**Comment by QuangHoang1210** [comment]
Passed on 0.9.3 canary
