### ISSUE TITLE
User input might be lost when going full screem

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#2097]
### Description

```
GIVEN I type a message
WHEN I go full screen
THEN part of the messag is lost
```

### Expected result

When going full screen the text input stays EXACTLY the same

### Current behavior

[screen-capture (1).webm](https://github.com/linagora/tmail-flutter/assets/6928740/a6677526-19ae-4eee-b889-d5f2cae63cb6)

### Context

Chromium 115.0.5790.170 snap

tmail.linagora.com, v0.8.3

Cc @hoangdat

**Comment by dab246** [comment]
@QuangHoang1210  Please verify help us. Thanks

**Comment by QuangHoang1210** [comment]
Hi @chibenwa ,

Is that 'lost' meaning the content in composer being disapeared in a sec and appear again !?

I try to reproduce this case. It seem like refresh data not lost the text in the composer.

cc @dab246  @hoangdat 

https://github.com/linagora/tmail-flutter/assets/124866146/96b2c2f7-544f-43db-b0e2-017c4004ff09

**Comment by chibenwa** [comment]
No the inout was lost lost

**Comment by dab246** [comment]
> No the inout was lost lost

Version `0.9.0` is available on `tmail.linagora.com`. @chibenwa  Please check again help us.

**Comment by dab246** [comment]
@chibenwa Are you still experiencing this error? Please tell us more.

**Comment by chibenwa** [comment]
No not recently. IMO can be closed.
If it happens again I will reopen.
