### ISSUE TITLE
oncommit-tmail.lng.com to not append default signature

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#2098]
### Description

No signature when I reply to an email

### Expected result

Like on tmail.linagora.com

![Screenshot from 2023-08-21 16-11-32](https://github.com/linagora/tmail-flutter/assets/6928740/087dc7ca-e449-4d74-8191-95fab1a8d219)

### Current behavior

No signature is appended

![Screenshot from 2023-08-21 16-11-21](https://github.com/linagora/tmail-flutter/assets/6928740/1db26b48-8277-4662-a20c-492e0137e1b5)

#### Reproduction Steps

- Set up a default identity
- Select an email and reply to all

THe default identity is not carried over

### Acceptance criteria

The list of acceptance criteria (defined in the corresponding User Story or coming from your functional knowledge of the product)
These acceptance criteria must be met by the corrective implementation done by the developers.

### Context

https://oncommit-tmail.linagora.com/

Chromium

Cc @QuangHoang1210 @hoangdat

**Comment by chibenwa** [comment]
Now happening on tmail.linagora.com v0.9.0

**Comment by QuangHoang1210** [comment]
@chibenwa  @dab246  @hoangdat 

I already can reproduce this issue on all enviroment 100% by this way:

### **Reproduce step:**
1, Open an email -> Click reply to all
2, Type some words in three rows
3, Select identity signature A
4, Select identity signature B

**Actual**: The signature is disappeared
**Expected**: Need to show signature



https://github.com/linagora/tmail-flutter/assets/124866146/15fd2c00-e82f-46f2-93e2-841ff7097e50

Noted: 0.9.1 version

**Comment by dab246** [comment]
The signature selection has been removed on the new composer

**Comment by dab246** [comment]
The signature selection has been removed on the new composer. We will test it again on the new composer
