### ISSUE TITLE
oncommit-tmail.linagora.com : quota information are missing

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#2099]
### Description

No quota bar.

### Expected result

![Screenshot from 2023-08-21 14-18-45](https://github.com/linagora/tmail-flutter/assets/6928740/2f238310-9b99-45af-b3f4-6cc1392e4f06)

Display a quota bar like on tmail.linagora.com

### Current behavior

![Screenshot from 2023-08-21 14-18-54](https://github.com/linagora/tmail-flutter/assets/6928740/d2719e1f-a4b8-4d26-923f-e6c2e94c3c9f)

No quota bar is currently displayed.

### Context

https://oncommit-tmail.linagora.com/ chromium

### Additional information

I suspect [XXX](https://github.com/linagora/james-project/issues/4814) to be the root cause.

Tmail needs to support both formats: the old, and the new.

**Comment by QuangHoang1210** [comment]
@Arsnael I think this one as we discussed on the morning

**Comment by hoangdat** [comment]
> Tmail needs to support both formats: the old, and the new.

Good catch

**Comment by QuangHoang1210** [comment]
Passed on 0.9.1
