### ISSUE TITLE
[Arabic] Letters are not linked between them

### ISSUE THREAD

**Issue by wboudiche** [linagora/tmail-flutter#2109]
### Description
When we receive an email written in arabic (frm gmail or tmail) and the language setted is English or French  the letters that constitute words are unlinked between them.
But when i switch language to Arabic things will be ok

### Expected result
Letters that constitute word should be linked
![Capture d’écran du 2023-08-24 10-49-07](https://github.com/linagora/tmail-flutter/assets/122379954/eea1d231-48e5-4020-9824-c8b8717b6228)

### Current behavior
When language is french or english the letters that constitute word are unlinked
![Capture d’écran du 2023-08-24 09-53-33](https://github.com/linagora/tmail-flutter/assets/122379954/6893cd77-ed14-4ace-8029-aa1d8adc7015)

#### Reproduction Steps
1- Send an email in arabic from gmail 
2- read mail with tmail mobile or web with English or French as language -> KO
3- Change the language to Arabic -> OK

### Context
Mobile, Android
Laptop, Ubuntu

**Comment by dab246** [comment]
@QuangHoang1210  Please verify help us.
