### ISSUE TITLE
[VSTEFFEN] [STORY] In app attachment drag and drop

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#2118]
### Description

 GIVEN I Open an email which contains attachments and I Open a composer
 WHEN I drag an attachment from the opened email to the composer, then the composer is shadowed with a text "Add as attachment
 I Drop the file to the shadowed area of the composer 
THEN the mail's attachment is attached in the composer

Rationals: Acting as a proxy, some people write a lot mails saying "hey I received this"

Question: Shall we then remove the button "upload the attachments from another mail" button as we propose a better UX for it?

Feature supported in Thunderbird:

https://github.com/linagora/tmail-flutter/assets/68209176/13f0dac7-dc42-44da-8c1e-9390d3f71d93

##### Mockup 
![Group 875](https://github.com/linagora/tmail-flutter/assets/68209176/aca792ee-3d5c-49f7-a79a-8bf2702ac99e)
 
### Description
GIVEN I open a composer
WHEN I open my PC' file browser 
I select files from file browser then drag to the composer
THEN The composer is shadowed and :
- If I drop selected image, it will be added as inline image 
- If I drop selected file which is not image, it will be added as an attachment 

I can select multiple files then drag and drop to the composer to add them as attachments.

**Comment by hoangdat** [comment]
- [ ] Drag n Drop image -> inline image by default
- [ ] Drag n Drop file -> attach file
