### ISSUE TITLE
[Text Font] Searching result text font is differently with normal text font

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#2122]
Searching result:

![Image](https://user-images.githubusercontent.com/124866146/263819357-49c0f184-eefc-40d4-955e-1079aa1fea5c.png)

Normal:

![Image](https://user-images.githubusercontent.com/124866146/263819419-8204614f-4aaa-408a-a8d0-ff683b2e774a.png)

**Comment by QuangHoang1210** [comment]
already discuss with @dab246

**Comment by dab246** [comment]
```[tasklist]
- [ ] hello
```

**Comment by QuangHoang1210** [comment]
IOS 0.11.3415 -> Passed
WEBPC -> Waiting next deployment

**Comment by hoangdat** [comment]
included in `refactor` branch
