### ISSUE TITLE
Problem with dependencies 

### ISSUE THREAD

**Issue by SergeOin** [linagora/tmail-flutter#2131]
### Description
Hello, I have a message with my dependencies, when I follow the getting started guide, this is the error that I encounter.
![image](https://github.com/linagora/tmail-flutter/assets/51446536/6f472c36-3ee7-4dfa-811c-506feadefcb7)

And when I try to change the dependencies collection, this is what it shows
![image](https://github.com/linagora/tmail-flutter/assets/51446536/251b440b-be9e-47b9-ba75-6df675b1ea9a)

### Expected result
Resolved

### Current behavior
In project folder, run `bin/bash prebuild.sh`

**Comment by SergeOin** [comment]
Thank you, here is my configuration
```
[√] Flutter (Channel stable, 3.13.1, on Microsoft Windows [version 10.0.22621.2215], locale fr-FR)
    • Flutter version 3.13.1 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e1e47221e8 (2 weeks ago), 2023-08-22 21:43:18 -0700
    • Engine revision b20183e040
    • Dart version 3.1.0
    • DevTools version 2.25.0

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\Pierre\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.7.3)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.7.34024.191
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[√] IntelliJ IDEA Ultimate Edition (version 2021.3)
    • IntelliJ at C:\Users\Pierre\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\213.5744.223
    • Flutter plugin version 63.2.4
    • Dart plugin version 213.5744.122

[√] VS Code (version 1.81.1)
    • VS Code at C:\Users\Pierre\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.72.0

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [version 10.0.22621.2215]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 116.0.5845.142
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 116.0.1938.69

[√] Network resources
    • All expected network resources are available.

• No issues found!
```

**Comment by dab246** [comment]
> shows



> Thank you, here is my configuration
> 
> ```
> [√] Flutter (Channel stable, 3.13.1, on Microsoft Windows [version 10.0.22621.2215], locale fr-FR)
>     • Flutter version 3.13.1 on channel stable at C:\flutter
>     • Upstream repository https://github.com/flutter/flutter.git
>     • Framework revision e1e47221e8 (2 weeks ago), 2023-08-22 21:43:18 -0700
>     • Engine revision b20183e040
>     • Dart version 3.1.0
>     • DevTools version 2.25.0
> 
> [√] Windows Version (Installed version of Windows is version 10 or higher)
> 
> [√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
>     • Android SDK at C:\Users\Pierre\AppData\Local\Android\sdk
>     • Platform android-34, build-tools 34.0.0
>     • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
>     • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
>     • All Android licenses accepted.
> 
> [√] Chrome - develop for the web
>     • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe
> 
> [√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.7.3)
>     • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
>     • Visual Studio Community 2022 version 17.7.34024.191
>     • Windows 10 SDK version 10.0.22621.0
> 
> [√] Android Studio (version 2022.3)
>     • Android Studio at C:\Program Files\Android\Android Studio
>     • Flutter plugin can be installed from:
>        https://plugins.jetbrains.com/plugin/9212-flutter
>     • Dart plugin can be installed from:
>        https://plugins.jetbrains.com/plugin/6351-dart
>     • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
> 
> [√] IntelliJ IDEA Ultimate Edition (version 2021.3)
>     • IntelliJ at C:\Users\Pierre\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\213.5744.223
>     • Flutter plugin version 63.2.4
>     • Dart plugin version 213.5744.122
> 
> [√] VS Code (version 1.81.1)
>     • VS Code at C:\Users\Pierre\AppData\Local\Programs\Microsoft VS Code
>     • Flutter extension version 3.72.0
> 
> [√] Connected device (3 available)
>     • Windows (desktop) • windows • windows-x64    • Microsoft Windows [version 10.0.22621.2215]
>     • Chrome (web)      • chrome  • web-javascript • Google Chrome 116.0.5845.142
>     • Edge (web)        • edge    • web-javascript • Microsoft Edge 116.0.1938.69
> 
> [√] Network resources
>     • All expected network resources are available.
> 
> • No issues found!
> ```

@SergeOin Currently our project is in short-term development, so it is only compatible with flutter version `3.10.x` (Specifically `3.10.6`). Please downgrade flutter to version `3.10.x` to use.

```
flutter downgrade <version>
```

**Comment by SergeOin** [comment]
Thanks @dab246 for your help! 
I didn't realize there was a specific version I needed to use. 
Good luck with everything!
