### ISSUE TITLE
[WEB] mailto URL

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#2134]
### Description

WHEN I redirect to URL `https://tmail.linagora.com/mailto?uri=dphamhoang%40linagora.com` (email address is base46 encoded)
THEN

![image](https://github.com/linagora/tmail-flutter/assets/6928740/d57e2cd7-af6b-4863-a03b-d335ac4cbbc1)

Why? Because it would make it way easier to integrate the "write an email to X'' feature with 3rd party app. For instance right now in CNB:

![image](https://github.com/linagora/tmail-flutter/assets/6928740/51e8a77a-cd41-4bb2-a3fe-f1d47357b852)

With the proposed change we could easily intercept the call in NGinx and redirect it to TMail...

Cc @hoangdat @pvi-github @guimard

**Comment by hoangdat** [comment]
what happen if uri is invalid => go to 404 page?

**Comment by chibenwa** [comment]
if uri is invalid then say then open the composer with an invalid recipient? 

![image](https://github.com/linagora/tmail-flutter/assets/6928740/ee4f36f0-410d-4b64-bc53-06cfd8cc7b1b)

**Comment by QuangHoang1210** [comment]
Passed on canary 0.9.3
