### ISSUE TITLE
[Story] User can config the cache to keep emails with in X days

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#214]
```
Given user logged in the app
User dont want to keep cache of mails too much in mobile device
User will go to settings of TeamMails
User choose the efficient days what he want to keep in the cache: 1 days, 7 days, 30 days, 3 months, 6 months
```

**Comment by chibenwa** [comment]
We should make it clear in the wording exposed to the end user that we are not keeping the whole emails but their preview.

`Keep email previews for  1 days, 7 days, 30 days, 3 months, 6 months`

On the long term we could add `off line` logic, like:

 - [ ] Pre-load new email body
 - [ ] Pre-load new email attachments
 - [ ] Keep email content for  1 days, 7 days, 30 days
 - [ ] Send emails offline (save emails to send them when network is back)
 
 But it is likely more an offline story!

**Comment by hoangdat** [comment]
Hi @guimard, how about #1431 ?

**Comment by guimard** [comment]
Hi @hoangdat, yes that's the idea

**Comment by chibenwa** [comment]
Closing as it duplicates https://github.com/linagora/tmail-flutter/issues/1431 and is covered by the offline mode story: https://github.com/linagora/tmail-flutter/issues/1702
