### ISSUE TITLE
mailbox => folder

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#2156]
![Screenshot from 2023-09-19 17-08-35](https://github.com/linagora/tmail-flutter/assets/6928740/272daf0d-a7e7-4f96-8b69-4748d3acb4a7)

**Comment by chibenwa** [comment]
![Uploading Screenshot from 2023-09-19 19-27-34.png…]()

**Comment by chibenwa** [comment]
![Screenshot from 2023-09-19 19-36-44](https://github.com/linagora/tmail-flutter/assets/6928740/9e523a20-9929-4dec-ac3d-d9dc190404cc)
![Screenshot from 2023-09-19 19-36-54](https://github.com/linagora/tmail-flutter/assets/6928740/90d333ac-ab8f-4826-a22b-3fdb0c848f2e)
![Screenshot from 2023-09-19 19-37-17](https://github.com/linagora/tmail-flutter/assets/6928740/8d94262e-7585-490e-b66e-7c62a4444b59)
![Screenshot from 2023-09-19 19-37-29](https://github.com/linagora/tmail-flutter/assets/6928740/d9ef4164-7600-4e40-8ba6-1f3ee5595128)

**Comment by chibenwa** [comment]
![Screenshot from 2023-09-19 19-39-26](https://github.com/linagora/tmail-flutter/assets/6928740/d6a9a3f1-140a-4d89-8099-e4708d1eb2c9)
![Screenshot from 2023-09-19 19-39-32](https://github.com/linagora/tmail-flutter/assets/6928740/2cf11b47-5a2d-4eec-a386-68d62d987970)
![Screenshot from 2023-09-19 19-39-39](https://github.com/linagora/tmail-flutter/assets/6928740/5e54f00a-e186-4c2e-8c5c-614b49602dbb)

**Comment by hoangdat** [comment]
Dear @QuangHoang1210 , please verify in English and Vietnam also.

**Comment by chibenwa** [comment]
I just did the franch translations FYI
