### ISSUE TITLE
[SIGNATURE] Remove the fold / unfold button on the signature before sending the mail

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#2157]
### Description

Folding unfolding signature in the composer IS great. Koodo for pulling that off, it is definitly helpful!

However, the fold / unfold section should be removed when sending the mail. Receivers should always see the signature.

TeamMail frontend needs to remove the `Signature` button and unfold the signature upon sends.

### Expected result

![image](https://github.com/linagora/tmail-flutter/assets/6928740/277ad161-1e52-4775-9324-a2a2a1185caf)

### Current behavior

![Screenshot from 2023-09-19 21-06-16](https://github.com/linagora/tmail-flutter/assets/6928740/1763e3be-f2a4-498d-aa3f-2d587b98bf3a)
![Screenshot from 2023-09-19 21-06-19](https://github.com/linagora/tmail-flutter/assets/6928740/e950b3d6-67df-4074-ad4c-07e01f2eae59)

**Comment by dab246** [comment]
@hoangdat Please verify with design help us.

**Comment by hoangdat** [comment]
Hi,
1. it was implemented as designed
<img width="689" alt="image" src="https://github.com/linagora/tmail-flutter/assets/6462404/77e99e10-aa99-4e28-9c51-f021283c5614">

2. it is only showed signature in TeamMail, no problem in other mail client. We removed it when sending email. Is it ok? @chibenwa

**Comment by chibenwa** [comment]
Hello,

We should NOT show the fold / unfold button once the mail is sent. period.

The fold / unfold button should only be shown in the composer. period.

Please fix.

**Comment by chibenwa** [comment]
Still happens to me on https://oncommit-tmail.linagora.com

**Comment by dab246** [comment]
@QuangHoang1210  please verify it help us.

**Comment by QuangHoang1210** [comment]
Passed the AC excepted one rarely case which already discuss with @dab246 

I'll close this ticket first and trying to reproduce.



![Image](https://github.com/linagora/tmail-flutter/assets/124866146/a85d22fc-b193-4bc0-85a3-facd1e308a3c)
