### ISSUE TITLE
[COMPOSER] CTRL+MAJ+Z

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#2167]
### Description

CTRL+Z reverts the input the user typed. (UNDO)

As a convention, CTRL+MAJ+Z is supposed to be able to restore the user input. (REDO)

However CTRL+MAJ+Z currently have no effect...

### Expected result

https://github.com/linagora/tmail-flutter/assets/6928740/2c801d20-dc92-4f10-88d2-07c3f5d5c90b

### Current behavior

https://github.com/linagora/tmail-flutter/assets/6928740/2af93c9f-4aee-43af-a019-262296f8543a

**Comment by dab246** [comment]
Same #1774

**Comment by hoangdat** [comment]
I tested on Chrome (MAC) it works well @QuangHoang1210 please verify in Window and Linux.

**Comment by QuangHoang1210** [comment]
Ctrl Z is working
Ctrl Shift Z is not working

ENV: Windows and Linux
