### ISSUE TITLE
[MAILTO] Invalid recipient

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#2168]
### Description

Calling `GET /mailto/?uri=mailto:btellier%40linagora.com` opens the composer but with an invalid recipient.

### Expected result

Should open the composer for `btellier@linagora.com`

### Current behavior

https://github.com/linagora/tmail-flutter/assets/6928740/5bc52e74-4bb8-4e10-852c-32664bc3f6a1

Cc @hoangdat

**Comment by chibenwa** [comment]
While we are at it we can add support for the `subject` HTTP query param and pass the email subject to the mailto composer...

![image](https://github.com/linagora/tmail-flutter/assets/6928740/609823b1-ea17-446b-a72f-d08dfd432ca0)

**Comment by hoangdat** [comment]
Hi, IMO, I think it is another case, not a BUG. 
- #2134: the format is `https://tmail.linagora.com/mailto?uri=dphamhoang%40linagora.com`

- not support for: `/mailto/?uri=mailto:btellier%40linagora.com`. If you want, we will add it

**Comment by chibenwa** [comment]
> not support for: /mailto/?uri=mailto:btellier%40linagora.com. If you want, we will add it

Remove the `mailto:` prefix if present then....

Needed for OpenPaaS compatibility...

**Comment by QuangHoang1210** [comment]
Passed on canary 0.10.1 

Not passed on CNB
