### ISSUE TITLE
[BUG][WEB][SAFARI] Cannot empty the trash

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#2170]
### Description

In safari clicking the empty trash button do not have effects.

### Expected result
When I click on the empty-the-trash button in Safary, I expect emails to be cleared.

### Current behavior

https://github.com/linagora/tmail-flutter/assets/6928740/37506a07-d437-40cc-b9aa-b09714bca4a5

@QuangHoang1210  can you validate this bug please?

**Comment by chibenwa** [comment]
I tested with chrome and v0.9.3 on oncommit.... No issue clearing 200 MB of mails.

**Comment by hoangdat** [comment]
can not reproduce


https://github.com/linagora/tmail-flutter/assets/6462404/0c5be805-ac8f-4e98-a213-881c35032bb4

**Comment by QuangHoang1210** [comment]
Cannot reproduce it by my side
