### ISSUE TITLE
Drag and Drop attachment from other mail to composer

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#2172]
### Desc:
- Support Drag n Drop attachment from old email to composer

**Comment by dab246** [comment]
@dieptran88  Do we support dragging multiple files?. If so, help us describe that flow of action

**Comment by chibenwa** [comment]
No IMO only a single file at once

**Comment by QuangHoang1210** [comment]
Passed on 0.10.1

Noted: Now can drag and drop multiple files
