### ISSUE TITLE
Appgrid on the tmail.linagora.com sometimes is outdated

### ISSUE THREAD

**Issue by shepilov** [linagora/tmail-flutter#2176]
### Description
When I login to the tmail.linagora.com I see the outdated uppgrid
<img width="1438" alt="image" src="https://github.com/linagora/tmail-flutter/assets/14924963/5d50e7ff-6423-464c-ba25-6e6923a20e44">

### Expected result
I want to see the updated version of appgrid without clearing all data in the browser

### Acceptance criteria

The list of acceptance criteria (defined in the corresponding User Story or coming from your functional knowledge of the product)
These acceptance criteria must be met by the corrective implementation done by the developers.

### Context

Devices, OS
Chrome Version 116.0.5845.110 (Official Build), macos

### Additional information

frequency, log files,...

**Comment by dab246** [comment]
@QuangHoang1210  Please verify help us. Thanks

**Comment by hoangdat** [comment]
the same with canary. Please fix it in the front-end first. @dab246

**Comment by hoangdat** [comment]
https://www.figma.com/file/Cu4NB44bcURKEy40DEfwWi/Design-system-1.0?type=design&node-id=54754-25989&mode=design&t=K93f5pUcEvG3mwUz-4
