### ISSUE TITLE
[Attachment] Download attachment file is not working

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#2177]
### Desc:
- Max Nguyen: download in Chrome, Window 11 -> no download request, v0.9.3

**Comment by dab246** [comment]
Work fine on Mac.
@QuangHoang1210  please verify it on windows/linux

**Comment by chibenwa** [comment]
I encouter the same on Chromium with 0.9.0

Since the switch to 0.9.3 no issue

**Comment by QuangHoang1210** [comment]
@dab246  @hoangdat  Still reproduce but rarely
