### ISSUE TITLE
[UI] Different font in Russian languages

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#2181]
**ENV:** Mobile / IOS - Android
0.9.3

**Reproduce step:**
1, User Menu header

**Actual:** The label of mail folder is having different font

**Expected:** Should be same font

![Image](https://github.com/linagora/tmail-flutter/assets/124866146/f4b7af91-19c1-47fb-87b9-dedbc0097160)

**Comment by dab246** [comment]
@QuangHoang1210  Please verify again
