### ISSUE TITLE
[BLUE-BAR] No blue bar for Office 365 events

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#2182]
[event.eml.txt](https://github.com/linagora/tmail-flutter/files/12747664/event.eml.txt)

![Screenshot from 2023-09-28 15-59-19](https://github.com/linagora/tmail-flutter/assets/6928740/fc71266b-6de1-4d78-bc72-8a006fff2a53)
![Screenshot from 2023-09-28 15-59-43](https://github.com/linagora/tmail-flutter/assets/6928740/45216f7e-b71b-4c32-ac81-818c0a3f1be1)

```
X-MEETING-METHOD: REQUEST
X-MEETING-UID: 040000008200E00074C5B7101A82E00800000000602312E836EDD90100000000000000001000000009C40B24EBC55C49B5E76D3C60DFC74F
X-MEETING-SEQUENCE: 0
X-MEETING-DTSTAMP: 20230922T072808Z
```

**Comment by hoangdat** [comment]
All the things from our calendar have the same problem

<img width="960" alt="image" src="https://github.com/linagora/tmail-flutter/assets/6462404/14563fa1-3cfe-4a0b-9fc0-59372810ab94">

**Comment by hoangdat** [comment]
we based on the old version:
https://github.com/linagora/tmail-backend/blob/a17a3051ee3176f93714b46f89f7b8c3ffc42961/tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/LinagoraCalendarEventParseMethodContract.scala

The problem is miss communication of the upgrade. @chibenwa @Arsnael. Hope we can find the solution to not have this.

**Comment by hoangdat** [comment]
And @QuangHoang1210 : please very careful when you press the button of release.

**Comment by dab246** [comment]
Unable to parse events from `Outlook`. I tried creating events from Outlook to 2 email addresses of Gmail and Linagora. But `CalendarEvent/parse` cannot parse the `blobId` of the `ics` file



https://github.com/linagora/tmail-flutter/assets/80730648/083456c9-db6a-42a7-87bb-48a6d881275e

**Comment by chibenwa** [comment]
Ok. Backend bug.

**Comment by QuangHoang1210** [comment]
1, Google calendar -> Passed

2, Outlook calendar -> Failed -- Missing blue bar

![Image](https://github.com/linagora/tmail-flutter/assets/124866146/19bb9471-2252-486d-8f69-0500e423f1d5)

**Comment by chibenwa** [comment]
Sure that is getting fixed on backend side
