### ISSUE TITLE
[Offline] Click on back button in `Sending Queue` mailbox -> close the app

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#2187]
### Desc:
1. open Sending queue folder 
2. Click on System back button
3. App close

### Expected:
- [ ] Back to inbox or previous folder

**Comment by dab246** [comment]
Please check with other mailboxes. The `Sending Queue` mailbox is similar to other mailboxes.

**Comment by QuangHoang1210** [comment]
- [ ] Change **Back button -> Cancel button** 

--> Dialog is closed --> Passed
