### ISSUE TITLE
[Vsteffen] Folder action: create subfolder

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#2194]
Creating a subfokdertoday requires a lot of actions.

Having a create child folder action that prefills parent would ease things alot.

[Screencast from 30-09-2023 12:09:46.webm](https://github.com/linagora/tmail-flutter/assets/6928740/9ba07293-19b2-43eb-ad8f-27e5713d8bae)

**Comment by dab246** [comment]
## DoD

- [ ] Add option `New Subfolder` to popup menu web
- [ ] Add option `New Subfolder` to context menu mobile

## Desc

- Option `New Subfolder` only support for `Default mailbox` & `Personal mailbox`.
