### ISSUE TITLE
[Vsteffen] composer hyperkink to identity management

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#2195]
Why: as a user the way to know i can manage my identity from the composer is not obvious.

Solution: We should have an hyperlink to manage identity profile page

Option 1: manage button on the right of from field

![Screenshot from 2023-09-30 12-07-00](https://github.com/linagora/tmail-flutter/assets/6928740/79703cd5-42a3-48a0-be40-44c8224aa540)

Option 2: in the from dropdown menue add a 'manage' item.

[Screencast from 30-09-2023 12:03:10.webm](https://github.com/linagora/tmail-flutter/assets/6928740/d037dcdb-0c80-4b54-af29-291bbefaff29)

**Comment by hoangdat** [comment]
- `pen icon` is not enough?

**Comment by chibenwa** [comment]
> pen icon is not enough?

That's what I call option 1, cf screenshot, and it is perfectly valid IMO

https://user-images.githubusercontent.com/6928740/271754997-79703cd5-42a3-48a0-be40-44c8224aa540.png
