### ISSUE TITLE
[Composer] Where is from ?

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#2196]
![image](https://github.com/linagora/tmail-flutter/assets/6928740/5e8da980-3e23-4555-a784-eb4ea670eb61)

Cannot be found in the new composer

**Comment by chibenwa** [comment]
Suggestion

![Screenshot from 2023-09-30 12-11-50](https://github.com/linagora/tmail-flutter/assets/6928740/0097855f-3367-4a59-a7ac-c0a08534bb5f)

**Comment by dab246** [comment]
@chibenwa According to the new design I received it does not have a `From` field. So this is not a bug.

<img width="811" alt="Screenshot 2023-10-02 at 09 23 18" src="https://github.com/linagora/tmail-flutter/assets/80730648/3c631550-c5ff-4221-a062-01f4b23860c1">

**Comment by chibenwa** [comment]
Ok, but it is a big missing feature!

So please do as I say: add an option next to cc,bcc to add a custom From field if needed nheee

**Comment by hoangdat** [comment]
Design: https://www.figma.com/file/XqLqMINlZw09BdEHI8yLb9/Teammail---1.1?type=design&node-id=1113-71669&mode=design

**Comment by chibenwa** [comment]
Looks great to me!
