### ISSUE TITLE
Cannot delete a folder when emptying

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#2197]
[Screencast from 30-09-2023 12:17:27.webm](https://github.com/linagora/tmail-flutter/assets/6928740/6ed76283-935f-4887-b9e2-7ca246f6afd6)

**Comment by chibenwa** [comment]
BTW should deleting a folder place it to the trash ?

[Screencast from 30-09-2023 12:22:45.webm](https://github.com/linagora/tmail-flutter/assets/6928740/522fd1d4-5266-4d24-aa8a-654b1843c479)

**Comment by dab246** [comment]
It seems that it does not correspond to the function of `Empty Trash`. Or am I misunderstanding action. Currently we only delete all emails in it, not the `folder` in `Trash`

**Comment by chibenwa** [comment]
Yes, drag n drop folder to trash would do. Closing.
