### ISSUE TITLE
[UX] [Suggesstion] User cannot see the email suggesstion if that email is new with our system

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#2199]
OS: Window/IOS/Android
Device: Laptop/Mobile
TMail version: 0.9.3

*Precondition: Recipients email is not exist in our system
Example: 
vietnam@liangora.com -- Not exist
smtp-vietnam@linagora.com -- Existed

### *Reproduce Step:
1, User click on [Composer]
2, User input vietnam@liangora.com at To field

### **Actual:** 
Only smtp-vietnam@linagora is displayed on suggesstion list. It not bring user to his expectation once press Enter.

### **Expected:** 
If the recipients email is new with system then create the new email on suggesstion list and priotize that email to the top of suggesstion list which in order to let user can press Enter to select correct email.

https://github.com/linagora/tmail-flutter/assets/124866146/673c2506-874d-4e44-a053-cf98b3333557

**Comment by hoangdat** [comment]
### case 1: suggestion list empty, but it is an email 
  - add 1 suggestion item with the whole email 
<img width="510" alt="image" src="https://github.com/linagora/tmail-flutter/assets/6462404/18811de5-6e55-4d4a-a900-2c628c4a50c1">

### case2: suggestion list not empty, and not include typed email
- add 1 suggestion item to the top of suggestion list with whole email
