### ISSUE TITLE
[Vacation] - Cannot turn on togge " "Vacation stops at" 

### ISSUE THREAD

**Issue by dieptran88** [linagora/tmail-flutter#2200]
OS:  Android / IOS / WINDOW
Device: Mobile / LAPTOP
TMail version: 0.9.3 -- https://tmail.linagora.com

*Precondition: 

### *Reproduce Step:
1 Log-in and open Manage account => Vacation
2. In Vacation setting screen, Turn on toggle "Automatically reply to messages when they are received". 
3. Input Start date 
4. Turn off toggle: "Vacation stops at" then Click button Save changes 

### **Actual:** 

- Vacation mode is on with toggle  "Vacation stops at" is automatically turned on 

### **Expected:** 

- Toggle  "Vacation stops at" is automatically turned off as setting and this vacation does not have an end date 
=> Suggestion: When user turn off the toggle  "Vacation stops at", there is a text appears " Your vacation will not have and end-date". 

[screen-capture - 2023-10-02T105033.764.webm](https://github.com/linagora/tmail-flutter/assets/68209176/fea06f06-50a8-422b-9178-4f46f162bf82)

**Comment by dieptran88** [comment]
cc @QuangHoang1210 @hoangdat

**Comment by QuangHoang1210** [comment]
1, The vacation setting is based on "Automatically reply to messages when they are received" toggle ON/OFF
--> So the vacation stop will be automatically turn ON once the "Automatically reply to messages when they are received" toggle is ON

2, Solution for this UX:
- The Vacation stop toggle is always turn on.
- The End date always update as default value = Start date. If user want to change the end date then he can change it.

3, We only can turn off Vacation stop toggle once turn OFF "Automatically reply to messages when they are received" 

@dieptran88 cc @dab246  @hoangdat

**Comment by dieptran88** [comment]
1.IF the " vacation stop" depends on "Automatically reply to messages when they are received" toggle ON/OFF, then why we display this toggle for user to turn it on/off? We can just remove it and display end-date field. 
In this case we agree that if vacation mode is on, there must be an end date ?

**Comment by QuangHoang1210** [comment]
@dieptran88  yes exactly. I mean we can implement this point. The end date will be updated as default value. Not the previous setting. Does it make sense!? 

2, Solution for this UX:

The Vacation stop toggle is always turn on.
The End date always update as default value = Start date. If user want to change the end date then he can change it.
