### ISSUE TITLE
[Attachment] The token expired make user cannot download attachment

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#2208]
OS:  Android / IOS
Device: Mobile
TMail version: 0.9.3 tmail.linagora.com

### *Reproduce Step:
1, User A open to view the email detail which included attachment
2, User A keep the Tmail tab on browser and not do anything in 5 minutes
3, User A click on Download attachment

### **Actual:** 
System call API failed 401 --- user cannot download 

### **Expected:** 
System recall API -> User can download successfully

https://github.com/linagora/tmail-flutter/assets/124866146/d5c50163-1b18-4e1b-8c5c-88a5a60eca9e

**Comment by dab246** [comment]
Please clear `cookie` and `cache`
