### ISSUE TITLE
Communicating I18N to remote servers

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#2215]
### Why ?

When I send an email outside of TMail,
Remote systems do not get my i18n/language settings

Which means that remote systems won't know which language settings to use.

We need to use a way to communicate i18n/language settings to remote systems.

### How ?

Set the following headers:

```
Accept-Language: fr-FR, en-US
Content-Language: fr-FR
```

Based of the language settings of the frontend application.

**Comment by hoangdat** [comment]
### Desc:
- create `LocaleInterceptor`
- Locale curentlocale;
- setLocale(Locale): 
  - when create instance LocaleInterceptor: from Hive
  - when change language: from settings

**Comment by dab246** [comment]
Only set headers for Email/set method when send email

**Comment by hoangdat** [comment]
@chibenwa how to verify it?

**Comment by chibenwa** [comment]
https://oncommit-tmail.linagora.com/

![image](https://github.com/linagora/tmail-flutter/assets/6928740/1875103f-9dbe-4244-8108-3917ae2fe475)

Not the case today!

(Email composed in tmail, email replied in tmail, email forwarded in tmail)

![image](https://github.com/linagora/tmail-flutter/assets/6928740/e5c4fac8-1d0d-4123-9f4f-854e12ce8d1e)

No `Accept-Language` and no `Content-Language`...

**Comment by hoangdat** [comment]
**** me!. Hi @dab246 , please add these to Email headers.
