### ISSUE TITLE
[CNB Preprod] [Safari] 1st login with TMAIL took so long time to load, sometime it's loading forever

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#2228]
OS:  Website only safari
Device: Laptop
TMail version: 0.9.3 https://mail.dpk-linagora-cl01.agoracalyce.net/

### *Precondition: 
- User 1st time login TMAIL (can clear all history in cache to reproduce this case)

### *Reproduce Step:
1, User A access https://mail.dpk-linagora-cl01.agoracalyce.net/
2, User A input correct credentials and start login

### **Actual:** 
System loading TMAIL landing screen unstoppable

### **Expected:** 
System loading success and redirect user to TMAIL home screen

https://github.com/linagora/tmail-flutter/assets/124866146/7e83cbd6-c177-4a0c-9b1d-d6822a432ca7

**Comment by Arsnael** [comment]
TBH I had the pleasure to observe similar issue on first loading in other browsers as well, and not only safari, like FF or chromium

**Comment by hoangdat** [comment]
duplicated #2210

**Comment by QuangHoang1210** [comment]
Reopened this one 

![Uploading image.png…]()
