### ISSUE TITLE
[Improvement] Change "mailbox" to "folder"

### ISSUE THREAD

**Issue by tprudentova** [linagora/tmail-flutter#2234]
- Occurred time: 09/10/2023

- Environment(version): https://tmail.linagora.com/

- Steps to reproduce:

1. Log into Tmail
2. Click Create new Folder 
3. Inside the creator it's still called a mailbox

Expectation: "new folder", "enter name of folder", "all folders"

- Image/Video evidence:

<img width="1280" alt="Screenshot 2023-10-10 at 12 30 05" src="https://github.com/linagora/tmail-flutter/assets/97684890/0577e3cb-361c-4bf8-a5e0-0cdb4d281451">

**Comment by chibenwa** [comment]
https://github.com/linagora/tmail-flutter/issues/2156

Duplicate
