### ISSUE TITLE
[Improvement] Cancel button looks deactivated

### ISSUE THREAD

**Issue by tprudentova** [linagora/tmail-flutter#2235]
Button Cancel in the composer is greyed out as if it were deactivated. Maybe we can make text blue as in the Save to drafts? 
<img width="1280" alt="Screenshot 2023-10-10 at 15 54 58" src="https://github.com/linagora/tmail-flutter/assets/97684890/68fd6579-fe30-4596-ad7a-caaa21bcf587">

**Comment by vijaymehrotra** [comment]
Hello @tprudentova ,
Can you assign this issue to me

**Comment by hoangdat** [comment]
changed to new composer. no more `cancel` button
