### ISSUE TITLE
[Bug] Cannot download attachment

### ISSUE THREAD

**Issue by tprudentova** [linagora/tmail-flutter#2238]
Occurred time: 09/10/2023

Environment(version): https://tmail.linagora.com/

Steps to reproduce:

1. Log into Tmail
2. Open an email with attachment 
3. Try to download it 
4. "Couldn't download attachment" error 

NB: This bug happened on Diana's device, I didn't manage to reproduce it but maybe you can

Image/Video evidence:

https://github.com/linagora/tmail-flutter/assets/97684890/01ad1182-5db0-4d97-ba1e-6f14a77ca6f9

**Comment by QuangHoang1210** [comment]
This is known issue https://github.com/linagora/tmail-flutter/issues/2177

**Comment by chibenwa** [comment]
Should close as it is a duplicate?
