### ISSUE TITLE
[Bug] Cannot select letter 

### ISSUE THREAD

**Issue by tprudentova** [linagora/tmail-flutter#2239]
Occurred time: 09/10/2023

Environment(version): https://tmail.linagora.com/

Steps to reproduce:

1. Log into Tmail
2. Try to select a message 
3. Cannot select a message 

NB: I also couldn't reproduce this bug but please try to do it as well 

Image/Video evidence:

https://github.com/linagora/tmail-flutter/assets/97684890/b06b6fa3-4a1f-4a20-82d9-b8db030a8975

**Comment by QuangHoang1210** [comment]
I cannot reproduce this issues. Maybe it's keyboard issue.

https://github.com/linagora/tmail-flutter/assets/124866146/8b87b931-c294-483f-b021-61a3a99b1d86

**Comment by hoangdat** [comment]
@tprudentova please test it together

**Comment by QuangHoang1210** [comment]
working well on my side.

How about yours ? @tprudentova
