### ISSUE TITLE
[Improvement] Work on naming for "Language and region"

### ISSUE THREAD

**Issue by tprudentova** [linagora/tmail-flutter#2241]
Rn we cannot change/view anything except language here, but we state that we can also set time zone and time format. 

<img width="1280" alt="Screenshot 2023-10-10 at 16 52 52" src="https://github.com/linagora/tmail-flutter/assets/97684890/2dcdfa6d-4d72-4c37-9504-f78af2573829">

**Comment by SidikiSako** [comment]
Hi @chibenwa  . So just keep the subtitle "Set the language" and the title to "Language" ? I can do that :)

**Comment by hoangdat** [comment]
> Hi @chibenwa  . So just keep the subtitle "Set the language" and the title to "Language" ? I can do that :) 

Thank you. Let's go
