### ISSUE TITLE
[Bug] Message "Auto reply is activated" stays even after it's been deactivated 

### ISSUE THREAD

**Issue by tprudentova** [linagora/tmail-flutter#2243]
You can see that auto reply is deactivated, however, message "Auto reply is activated" stays at the top of the page.

https://github.com/linagora/tmail-flutter/assets/97684890/52df319a-0065-4b8e-9e05-4e64480b32d9

**Comment by QuangHoang1210** [comment]
@tprudentova  cc @hoangdat This is not a bug.

You should scroll down to click on Save button. If only switch off the toggle then vacation setting is not changed

https://github.com/linagora/tmail-flutter/assets/124866146/4c45ee0f-0323-485a-8fd6-b1764a06f644

**Comment by tprudentova** [comment]
Then I believe we need to think about UX/UI. When you switch the toggle off, everything below looks greyed out and deactivated, I personally didn't even think I needed to press any additional buttons :(

**Comment by chibenwa** [comment]
+1 save changes should likely be at the top?

**Comment by QuangHoang1210** [comment]
already move to Designing @hoangdat

**Comment by hoangdat** [comment]
move `save` button to the top
