### ISSUE TITLE
[Bug] Cannot receive letters from .ru mail addresses

### ISSUE THREAD

**Issue by tprudentova** [linagora/tmail-flutter#2244]
Occurred time: 09/10/2023

Environment(version): https://tmail.linagora.com/

Steps to reproduce:

1. Send a letter from a .ru mail address.
2. The letter is not received by TMail (neither in inbox nor in spam)

Image/Video evidence:

https://github.com/linagora/tmail-flutter/assets/97684890/a6e1a4f5-d398-4ad0-af3d-af360b089374

**Comment by chibenwa** [comment]
Not related to frontend neither to backend...

It looks more like an infrastructure topic. I suspect mxguarddog to block the traffic. 

Could you check?
