### ISSUE TITLE
[Attachment] Cannot upload attachment or Image on Canary v0.10.0

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#2245]
OS: WINDOW
Device: Mobile, LAPTOP
TMail version: 0.10.0 https://canary-tmail.linagora.com/

### *Reproduce Step:
1, User click on composer
2, User click on Attachment icon
3, User select any files

### **Actual:** 
It's uploading failed

### **Expected:** 
Upload successfully

### *Noted: It happens same with  upload  image

**Attachment:**

https://github.com/linagora/tmail-flutter/assets/124866146/1b1ec228-112b-4dd1-a8cb-6080c6bfbf21

**Upload image:**

https://github.com/linagora/tmail-flutter/assets/124866146/730cdee4-8749-4ec9-b447-d5462ac8c959

**Comment by dab246** [comment]
Please compare with version `0.9.3` on tmail.linagora.com

**Comment by hoangdat** [comment]
- [ ] add refresh token flow

**Comment by hoangdat** [comment]
- can upload with new token, but no response in a long time 
- try to use new token with postman -> 401

**Comment by hoangdat** [comment]
verify on 0.10.4

**Comment by QuangHoang1210** [comment]
Passed on 0.10.4 canary and 0.10.3 production


https://github.com/linagora/tmail-flutter/assets/124866146/ff174168-7d75-4a8b-a2c8-17879efbad86
