### ISSUE TITLE
[Improvement] New composer need take more than one minute to loading UI -> Feeling lag and slow

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#2246]
OS: WINDOW
Device: Mobile, LAPTOP
TMail version: 0.10.0 https://canary-tmail.linagora.com/

### *Reproduce Step:
1, User click on composer
2, User quickly input something into the To field

### **Actual:** 
The suggesstion is not displayed quickly. Feeling composer need time to load. Feeling lag.

### **Expected:** 
Need to improve loading time of composer.

https://github.com/linagora/tmail-flutter/assets/124866146/61ebd96d-728f-4bcb-b44c-649d6a3f71b6

**Comment by dab246** [comment]
Please compare load times with version `0.9.3` on tmail.linagora.com
