### ISSUE TITLE
[New Composer] Tmail seem crash and user cannot type or do anything once user do many action with composer in the same time

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#2247]
OS: WINDOW
Device: Mobile, LAPTOP
TMail version: 0.10.0 https://canary-tmail.linagora.com/

### *Reproduce Step:
1, User click on composer
2, User drag and drop an image to composer
3, User drag and drop some attachment file (xlsx, ics, pdf,..) to composer
4, User start writing email body during juploading time at step 3
5, User click on image icon to upload new image on composer
6, User keep writing email body

### **Actual:** 
TMAIL is crashed. User cannot do anything in a while

### **Expected:** 
New composer should be more smoothly

https://github.com/linagora/tmail-flutter/assets/124866146/7bad3f37-f859-48fe-84f7-860478e488f9

**Comment by dab246** [comment]
Please also test on other envs `oncommit`, `tmai.linagora.com`
