### ISSUE TITLE
UI broken when user reply/foward/send a long email content

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#2261]
OS:  IOS / Android
Device: Mobile
TMail version: 0.10.1 canary

### *Reproduce Step:
1, User open to view the email content
2, User reply/foward/send that email content
3, User click [Send] button

### **Actual:** 
UI is broken

![Image](https://github.com/linagora/tmail-flutter/assets/124866146/2dde3995-7c02-4cbc-8f7a-4a1eeb2d5a3e)

### **Expected:** 
UI not broken

https://github.com/linagora/tmail-flutter/assets/124866146/107ca314-144d-46a8-9fb2-e92bf958cd6d

**Comment by dab246** [comment]
Only happens on iOS.
