### ISSUE TITLE
The subject will be auto replace by "Identity Inline Image" when user reply/send/foward an email with signature as Image

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#2262]
OS:  IOS / Android
Device: Mobile
TMail version: 0.10.1 canary

### *Reproduce Step:
1, User send/foward/reply an email with that Identity which having image
2, User input Subject
3, User click [Send] button

### **Actual:** 
The subject is auto replace to "Identity Inline Image"

### **Expected:** 
The subject should be kept

![Image](https://github.com/linagora/tmail-flutter/assets/124866146/53ac4a3a-6754-4f38-b01f-8569bb56b909)

**Comment by hoangdat** [comment]
it is sender's name
