### ISSUE TITLE
[UI Bug] - Recipient list in field "Cc" is not in correct position 

### ISSUE THREAD

**Issue by dieptran88** [linagora/tmail-flutter#2263]
Occurred time: 17/10/2023

Environment(version): https://tmail.linagora.com/

Steps to reproduce:

1. Open an email that contain recipients in field "cc"
2. click button Hide/Show => Recipient list is not displayed in correct potition 

Image/Video evidence:

Mobile :

https://github.com/linagora/tmail-flutter/assets/68209176/43abcbbb-6813-47b3-8962-1462ea2e6ec7

[screen-capture - 2023-10-17T104215.947.webm](https://github.com/linagora/tmail-flutter/assets/68209176/24bebeb9-4a1a-4182-9a79-1aa9186e82b6)

**Comment by Taosif7** [comment]
Please assign this to me, I have found solution for this
