### ISSUE TITLE
Woding: empty => clean

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#2267]
![Screenshot from 2023-10-18 08-54-58](https://github.com/linagora/tmail-flutter/assets/6928740/f43a105c-d8aa-4918-8c7c-6493068c0584)

Because empty can be undestood as both verb and adjective.

Clean is more straightforward. THis should be used instead.

**Comment by SidikiSako** [comment]
Hi @chibenwa. I would like to work on this.
