### ISSUE TITLE
[Story] Network status in the app: indicate the status of network

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#228]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Technical issues](#technical-issues)
* [Misc](#misc)

## Definition

- Given that i am a Tmail user and i already had an account (John Doe) 
- Given that I log-in successfully to the Tmail app
- When I am using app, the network is disconnected
- Then I can see a dialog with the text :"No network connection"
- This dialog will  disappear when the network is back
 
[Back to Summary](#summary)

#### Mockups

![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/a3f4fb82-6cbf-48b9-8629-41e6182e7be9)

#### Design ticket

https://ci.linagora.com/linagora/lgs/design/-/issues/101

[Back to Summary](#summary)

## Technical issues

[Back to Summary](#summary)

## Misc

[Back to Summary](#summary)

**Comment by dieptran88** [comment]
@hoangdat

**Comment by Kevinle2312** [comment]
Passed on the Production platform.
