### ISSUE TITLE
[Story] Read email in offline mode

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#229]

**Comment by chibenwa** [comment]
I do not think we should download a lot of emails for ofline usages. I propose:

 - **unread emails** to a maximum of 100MB / 1000 emails.
 - Then the last unread emails to a maximum of 100MB / 1000 emails.
 
 BTW I think we should be working on Mailbox actions and having a feature complete online mode before starting work on an offline mode.

**Comment by chibenwa** [comment]
Offline mode story: https://github.com/linagora/tmail-flutter/issues/1702
