### ISSUE TITLE
Investigate notification for Android

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#2298]
### Desc:
- updated version can not get notification

**Comment by hoangdat** [comment]
- [ ] build local release with firebase analytic
- [ ] log
- [ ] show default notification in the case failed in fetching data
- [ ] steps for reproduce: build with version -> increase version -> build with new version

**Comment by hoangdat** [comment]
- if token is not changed, but FCMRegistration expired, `current code` register the new one with the same `deviceClientId` -> response failed

**Comment by hoangdat** [comment]
### Web try to reload:

Before register again:

![Image](https://github.com/linagora/tmail-flutter/assets/6462404/309693f2-565a-4f82-bc13-0026853c6739)

Try to register



![Image](https://github.com/linagora/tmail-flutter/assets/6462404/f61bd44b-19ae-4c75-a50c-05078f7d4ca7)

**Comment by dab246** [comment]
> * if token is not changed, but FCMRegistration expired, `current code` register the new one with the same `deviceClientId` -> response failed

No, our scenario is not like that. We only register a new one when we do not find any `deviceId` registered on the server. If we already have it and it `expired`, we will update the `expires` time of that token.
