### ISSUE TITLE
[Story] List and show mailboxes in offline mode

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#231]

**Comment by chibenwa** [comment]
Is this done?

**Comment by hoangdat** [comment]
Still not support offline mode

**Comment by chibenwa** [comment]
Done as far as I know

**Comment by hoangdat** [comment]
Need to open a bug for it, the blocker point for all offline case is `Session`. Added in my radar. I will open bug or sth like that later.
