### ISSUE TITLE
[Safari] Cannot access TMAIL production on Safari

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#2310]
OS: OS
Device: Laptop
TMail version: 0.10.3 safari only

### *ENV:
- tmail.linagora.com
- jmap.linagora.com/oidc

### *Reproduce Step:
1, User access to tmail.linagora.com on safari

### **Actual:** 
Tmail is loading nonstop

### **Expected:** 
User can access TMAIL successfully

**Console**
<img width="1151" alt="Screenshot 2023-11-15 at 16 23 14" src="https://github.com/linagora/tmail-flutter/assets/124866146/2d506350-f6c4-45ae-a2d2-9f48573db7e8">

https://github.com/linagora/tmail-flutter/assets/124866146/419ebce1-386c-468c-87a3-d3e5105c562b

--- additional

https://github.com/linagora/tmail-flutter/assets/124866146/4abe4ffe-c9f5-4dac-9801-25d9056437e1

**Comment by hoangdat** [comment]
- try to type: `tmail.linagora.com` in safari and firefox, app can not load

**Comment by hoangdat** [comment]
fixed
