### ISSUE TITLE
Quick search: filter not applied to suggestion

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#2323]
### Description

Preconditions:

```
GIVEN I click "quick search"
AND input first letters of one's mail address
WHEN Select his mail
THEN the From filter is applied to this mail address
```

Now:

```
WHEN I input some text
THEN I am prompted with suggestions from other senders
AND the from directive is not applied
```

Note: The from criterion is actually applied to the actual search resutls.

### Expected result

I expect the from criterion to also be applied to search recommendations,

### Current behavior

https://github.com/linagora/tmail-flutter/assets/6928740/fd4c4282-42e9-4900-9797-86857a8dd580

### Context

Chromium, https://oncommit-tmail.linagora.com/ v0.10.4

**Comment by hoangdat** [comment]
- [ ] update `from` button with selected email 
- [ ] `from` button can choose other email when click
