### ISSUE TITLE
[Improvement] Add counter to Drafts folder

### ISSUE THREAD

**Issue by tprudentova** [linagora/tmail-flutter#2326]
We need to add counter of letters to Drafts folder
See Gmail reference 
<img width="1280" alt="Screenshot 2023-11-15 at 16 33 30" src="https://github.com/linagora/tmail-flutter/assets/97684890/5802a82d-43e8-4d78-8f8c-e8fea5f7d4cc">

**Comment by chibenwa** [comment]
Please display in this counter **the total number of draft mails** and not the number of unread emails

**Comment by dab246** [comment]
@hoangdat  We do not yet have a PR commit for this issue on the `v0.11.3-patch4-dev` branch
