### ISSUE TITLE
[Bug] Broken layout in some places of the mobile app

### ISSUE THREAD

**Issue by tprudentova** [linagora/tmail-flutter#2327]
Layout is a bit broken in Delete message warning and in bottom action bar

Phone - Redmi Note 9

![photo_2023-11-15_17-37-41](https://github.com/linagora/tmail-flutter/assets/97684890/b6773a4a-d562-471a-b6d0-0f393078f234)

![photo_2023-11-15_17-37-31](https://github.com/linagora/tmail-flutter/assets/97684890/f06220c5-14c5-43c6-ad23-d441630bf36b)

**Comment by hoangdat** [comment]
hi @tprudentova what is the problem of 

![image](https://github.com/linagora/tmail-flutter/assets/6462404/737501a3-2da7-48a3-b65a-2a4aa2558250)
