### ISSUE TITLE
[Improvement] Move Sent folder up in the list of folders

### ISSUE THREAD

**Issue by tprudentova** [linagora/tmail-flutter#2328]
Would be better for the folders to be displayed in the following order: 
Inbox 
Sent 
Everything else

**Comment by hieutbui** [comment]
@hoangdat We already have sortOrder for default mailboxes
![image](https://github.com/linagora/tmail-flutter/assets/80142234/1490d45c-36b4-4f21-a7ce-a658166f56c7)

**Comment by chibenwa** [comment]
![image](https://github.com/linagora/tmail-flutter/assets/6928740/445f13d7-326f-4f58-8d29-ddc6a6d770de)

+1 let's fix that on the backend side

**Comment by chibenwa** [comment]
https://github.com/apache/james-project/pull/1956

**Comment by quantranhong1999** [comment]
https://github.com/linagora/tmail-backend/pull/925
