### ISSUE TITLE
[Story] As a user, I want to add new mailbox or create a sub-mailbox

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#233]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Definition

- Given that I am a Tmail user and i already had an account
- Given that I log-in successfully to the Tmail app
- I can see the default view is "Inbox" folder
- when I click on screen title "Inbox", I can see the listing mailboxes screen
- I this screen I click button "Create folder" at the bottom, a new screen will be opened
- In this new screen, I can see 2 field:
   - Folder name: a Text field. This is a mandatory field and I need to input new folder name to this field
   - Is located under:  Optional field. When I click on this field, a drop-down list will be opened, including all current mailboxes 
   - If the mailbox has child folder, I can touch the arrow icon to expand the parent folders to the last child folder.
   - When I touch a folder on the list, it will be selected to the field "is located under"
- When I click button Save, the system will validate:
   - If the folder name is blank, there will be an error message: "This field cannot be blank"
   - If  there is already a folder with same name in parent folder, there will be an error message:" There is already folder with the same name"
   - If the name contains any special character, there will be an error message: "Mailbox name cannot contain special characters"
- If the name is validated, a new folder will be created under the selected parent folder 
- There will be an notification: "[New folder name] is created"
- If I do not select any parent folder, the new folder will be created as a first-level folder in folder tree and located at the bottom of the mailboxes list  

[Back to Summary](#summary)

## Screenshots

![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/aff12cc0-4334-4c41-b77b-7ec2e9cfa544)  ![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/1b62a9a3-47e2-445b-b0e7-daabbe37215f)

![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/cf8dc739-6049-4976-89b0-b73259771b69)  ![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/7031e5ae-a8d2-46ea-a3e8-c8e037a24356)

![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/3dd441f3-9df6-41c6-b57a-007c8d920f20)  ![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/f243cba0-ccd2-432c-8bea-5e64224fcf03)

![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/a320682d-f51d-4084-a501-4f161b46f630)![ .png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/579a47bf-dd8b-4049-82d5-2cd4a86df221)
 
[Back to Summary](#summary)

## Design ticket

https://ci.linagora.com/linagora/lgs/design/-/issues/97

## Misc

None

[Back to Summary](#summary)

**Comment by hoangdat** [comment]
please refer to #36

**Comment by dieptran88** [comment]
@hoangdat  @chibenwa  Please help me to verify this story

**Comment by hoangdat** [comment]
it is ok for me. But please focus to destination picker in `is located under`

**Comment by hoangdat** [comment]
figma: https://www.figma.com/file/rRVxJpCu1G22D0jqyvK7I9/TeamMail?node-id=424%3A45329
