### ISSUE TITLE
[Improvement] Archive action on swipe

### ISSUE THREAD

**Issue by tprudentova** [linagora/tmail-flutter#2335]
It would be nice to add Archive action on swipe, as you ofter need to get rid of multiple messages at a time in your inbox. Rn on swipe it's only Mark as read/unread.

**Comment by chibenwa** [comment]
https://github.com/linagora/tmail-flutter/issues/2335

**Comment by hoangdat** [comment]
> #2335

I think it is a mistake paste. @chibenwa

**Comment by chibenwa** [comment]
Right https://github.com/linagora/tmail-flutter/issues/1328
