### ISSUE TITLE
[Story] As a user, I want to delete a mailbox

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#234]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC
https://app.zenhub.com/workspaces/tmail-flutter-60d039db6ef62a0013432c14/issues/linagora/tmail-flutter/227

## Definition

- Given that I am Tmail app user and I already logged-in 
- I touch the hamburger icon on top of screen, the mailboxes listing view will be opened. 
- I long-press on a mailbox which is created by me (not a default mailbox), a mailbox management dialog will be displayed with options:
   - Rename the mailbox
   - Move the mailbox
   - Mark all emails as read
   - Delete the mailbox
- Or When a mailbox in mailbox list is focused, there will be a three-dot button. I can click on this button then the mailbox management dialog will be displayed.
- I select option "Delete the mailbox", I am prompted with a confirmation dialog: "[Folder's name]  and all the messages it contains will be deleted and you won't be able to recover them." and 2 buttons Cancel/Delete
- If I select Delete, that mailbox will be deleted with all  inside emails 
- Now I can not see that mailbox in mailbox list 

[Back to Summary](#summary)

### mockups
![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/3e1ecaa6-ffa6-4dbe-bce4-eeff92c5700d)  ![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/089cbcfd-1591-4ffe-b44d-126575222f6a)

![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/9a155b50-7134-4e64-938b-0dfe012e964e)

## Design ticket
https://ci.linagora.com/linagora/lgs/design/-/issues/102

[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

**Comment by dieptran88** [comment]
@hoangdat Please verify story

**Comment by hoangdat** [comment]
hi @chibenwa, @Arsnael how to delete a mailbox and its sub-mailbox in 1 request?
I tried to arrange the `destroy` array in `Mailbox/set` method, it does not work

![image](https://user-images.githubusercontent.com/6462404/157800534-68799759-85af-4012-b853-f3fdb9aee609.png)

**Comment by chibenwa** [comment]
> hi @chibenwa, @Arsnael how to delete a mailbox and its sub-mailbox in 1 request?
I tried to arrange the destroy array in Mailbox/set method, it does not work

Yes we don't order the deletes hierarchically.

You can try:

```
{
   ...
   "methodCalls": [
       [ "Mailbox/set", {"destroy mbx A"}, "#0"],
       [ "Mailbox/set", {"destroy mbx B"}, "#0"],
       [ "Mailbox/set", {"destroy mbx C"}, "#0"],
       [ "Mailbox/set", {"destroy mbx D"}, "#0"]
    }
}
```

Starting with child mailboxes first.
