### ISSUE TITLE
Re-organize email list view top menus on mobile

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#2340]
This ticket merges: https://github.com/linagora/tmail-flutter/issues/2332 https://github.com/linagora/tmail-flutter/issues/2338 and complements them.

 - [ ] Remove the `Edit` option to switch in selection mode. Long press is enough.
 - [ ] Move the folder selector to the left cf https://github.com/linagora/tmail-flutter/issues/2332
 - [ ] Align the filter selector with the search bar
 - [ ] And add the `Settings` link on the top right. See https://github.com/linagora/tmail-flutter/issues/2338 .

![signal-2023-11-16-151421](https://github.com/linagora/tmail-flutter/assets/6928740/5f73dfc3-b41c-4a29-b770-35fafb126ab6)

Please @dieptran88 provide a design for it.

**Comment by hoangdat** [comment]
Design: https://www.figma.com/file/1veHgQB4dtngGynRyJpPaO/Design-System-Tmail?type=design&node-id=2390-23019&mode=design&t=8LJwKCexhO0ifj2K-4
