### ISSUE TITLE
Image in Identity: As a user resizing images manually is a pain

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#2346]
### Description

Today when inlining an image in base64, we do encore the image in each signature using base64 in the image tag,

This image being sent with each and every email, we do want to limit the size of the image to limit the impact on the storage.

As such we require the image to fit in 16 KB.

However user wants to submit arbitrary images.

### Expected result

If the image is too big we could attempt to compress it on-the-fly using tools like https://pub.dev/packages/flutter_image_compress 

### Current behavior

![image](https://github.com/linagora/tmail-flutter/assets/6928740/eb6fdd8f-42c9-408b-8882-e282125f63bf)

Thoughts @PatrickPereiraLinagora @hoangdat @dab246 @mmaudet ?

**Comment by hoangdat** [comment]
- [ ] not allow user paste image more than `maxFileSize`
- [ ] if the image size < 2MB use image directly 
- [ ] try to compress image to lossless format with maximum size 2Mb, if compressed image > 2MB -> throw error popup

@chibenwa are you ok with it?

**Comment by chibenwa** [comment]
2 MB is WAY to much.

I agree to go up to 128 KB, and not more.
