### ISSUE TITLE
Change App Icon for Android

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#2349]

**Comment by QuangHoang1210** [comment]
### Not yet changed on android Logo on page and logo on preview app

![Image](https://github.com/linagora/tmail-flutter/assets/124866146/b6b5cf4d-f7b4-4936-ae80-163fcf7cde5c)

![Image](https://github.com/linagora/tmail-flutter/assets/124866146/ab7f0200-7e63-4455-b587-ee66d2a0e8cb)

**Noted: Only change in Playstore**
