### ISSUE TITLE
[Story] As a user, I want to rename a mailbox

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#235]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC

https://app.zenhub.com/workspaces/tmail-flutter-60d039db6ef62a0013432c14/issues/linagora/tmail-flutter/227

## Definition

- Given that I am Tmail app user and I already logged-in 
- I touch the hamburger icon on top of screen, the mailboxes listing view will be opened. 
- I long-press on a mailbox which is created by me (not a default mailbox), a mailbox management dialog will be displayed with options:
   - Rename the mailbox
   - Move the mailbox
   - Mark all emails as read
   - Delete the mailbox
- Or When a mailbox in mailbox list is focused, there will be a three-dot button. I can click on this button then the mailbox management dialog will be displayed.
- I select option "Rename the mailbox", I am prompted with a  dialog to rename my mailbox 
- I fill in the text field and click button Rename, system will validate:
- When I click button Save, the system will validate:
   - If the folder name is blank, there will be an error message: "This field cannot be blank"
   - If there is already a folder with same name in parent folder, there will be an error message:" There is already folder with the same name"
   - If the name contains any special character, there will be an error message: "Mailbox name cannot contain special characters"
- If the name is validated, the mailboex will be renamed  successfully 

[Back to Summary](#summary)

### Mockups
![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/3e5f62e6-d0d4-4609-803a-4c02d4e1fcf9)  ![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/2c4fceb8-8f76-4e1e-8bab-f65c7cd824cd)

## Design ticket

https://ci.linagora.com/linagora/lgs/design/-/issues/104

[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

**Comment by dieptran88** [comment]
@hoangdat  Please review the story

**Comment by hoangdat** [comment]
@dieptran88 only concerned about the mailbox management dialog.
