### ISSUE TITLE
Missing body when read mail with ics attachment

### ISSUE THREAD

**Issue by quantranhong1999** [linagora/tmail-flutter#2351]
### Description
Given I received a mail with an ics attachment and body.

### Expected result
The blue bar should display and the body should display.

### Current behavior
The body did not display.

#### Reproduction Steps

https://github.com/linagora/tmail-flutter/assets/55171818/f3e04f97-f3e6-4679-a384-046d59a47cfa

### Context

TMail WEB tmail.linagora.com version 0.10.3.

The same is TMail Android 0.10.4.

cc @QuangHoang1210 please help me verify if we reported this issue before. I had a quick look and seems non.

**Comment by dab246** [comment]
Please attach your `ics` file here.

**Comment by quantranhong1999** [comment]
> Please attach your ics file here.

[invite.ics.zip](https://github.com/linagora/tmail-flutter/files/13421296/invite.ics.zip)

BTW as I obverse, this seems to happen for all ics.

**Comment by chibenwa** [comment]
We need the blue bar AND the body

**Comment by quantranhong1999** [comment]
Hi,

It seems a regression on web 0.14.2 and mobile 0.14.2.

https://github.com/user-attachments/assets/8624a790-0ab4-400d-82eb-f7b48851c7b9

MU customers complain they can not see the meeting link when receiving a Microsoft Teams meeting invitation (which is supposed to be in the mail body).

EML for Microsoft Team meeting: 
[Test.eml.zip](https://github.com/user-attachments/files/18121658/Test.eml.zip)

**Comment by hoangdat** [comment]
hi @quantranhong1999,
we will have 2 cases:
- Case 1: no description in `ics` file -> we still display the content body of original email 
<img width="1062" alt="Screenshot 2024-12-13 at 14 43 41" src="https://github.com/user-attachments/assets/54e82260-fba9-4224-a182-7fb5985ecea4" />


- Case 2: (same with your case), `ics` also have body content and original also have content 
<img width="512" alt="image" src="https://github.com/user-attachments/assets/dc739248-a70a-41ec-a031-b2cc26f7d9f7" />

Case 2, it is our blind. So the question now, how to display 2 content body in our blue bar @chibenwa ?

**Comment by chibenwa** [comment]
> Case 2, it is our blind. So the question now, how to display 2 content body in our blue bar @chibenwa ?

Display both?

**Comment by hoangdat** [comment]
how to display it?
