### ISSUE TITLE
[Story] As a user, I want to mark all email in mailbox as read

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#236]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC
https://app.zenhub.com/workspaces/tmail-flutter-60d039db6ef62a0013432c14/issues/linagora/tmail-flutter/227

## Definition

- Given that I am Tmail app user and I already logged-in 
- I touch the hamburger icon on top of screen, the mailboxes listing view will be opened. 
- I long-press on a mailbox, a mailbox management dialog will be displayed with options:
   - Rename the mailbox
   - Move the mailbox
   - Mark all emails as read
   - Delete the mailbox
- Or When a mailbox in mailbox list is focused, there will be a three-dot button. I can click on this button then the mailbox management dialog will be displayed.
- The option "Mark all emails as read" is only enabled when there is at lease 1 unread email in that mailbox 
- When I select this option, all unread email in the mailbox will be marked as read. The unread email counter will disappeared. 
There will be a successful toast message: "All messages in folder have been marked as read" and a button Undo. 
- When I click on "Undo", all the emails that are marked as read before now reverted to unread and now the unread email counter appears on the mailbox tittle. 

[Back to Summary](#summary)

### mockups

![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/2d3d373e-3e12-4c0c-83dd-ca8697820e7a)  ![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/f9210936-6c04-405f-9eb5-4e66fc213533)
## Design ticket

https://ci.linagora.com/linagora/lgs/design/-/issues/191

https://ci.linagora.com/linagora/lgs/design/-/issues/105

[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

**Comment by dieptran88** [comment]
@hoangdat Please review the story

**Comment by hoangdat** [comment]
@dieptran88  dialog in mobile not always show like that, please get the idea from designer. But I prefer context menu or something like that.

**Comment by dieptran88** [comment]
I want user to know which folder he is interacting with, so I put the dialog above or below the selected folder. But it is just my ideal and I have created design ticket for it. Design experts  will help us :))
