### ISSUE TITLE
Wide screen: list of emails do not expend to the bottom.

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#2362]
![image](https://github.com/linagora/tmail-flutter/assets/6928740/53b72f8d-fdc5-4221-8af5-336b74b563e4)

The list do not expend to the bottom...

... and it is impossible to scroll...

### Proposed solution

If the display width allows for it, load more items (100?)

### Credit

@damienlaine

**Comment by QuangHoang1210** [comment]
Cannot load more email when user zoom out screen even if user refresh page

https://github.com/linagora/tmail-flutter/assets/124866146/848a0f07-0c8d-434c-8d2c-d5bc29d76c57

**Comment by hoangdat** [comment]
please pick it to `patch4-dev` branch
