### ISSUE TITLE
User input lost upon SSO Refresh?

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#2368]
```
WHEN a token expires
THEN I am redirecting to the SSO
I login again and come back to TMail
AND my input is lost
```

We should save user input in a local cache in order to show it again to the user after re-log in.

(NEVER loose user input)

I'll try to reproduce it this weekend...

**Comment by hoangdat** [comment]
Did you reproduce it?
It is very rare case IMO: `access-token` and `refresh-token` expired in the same time with sending email.

For the solution: save to cache for the case of logout is good in security and privacy?

**Comment by chibenwa** [comment]
> It is very rare case IMO: access-token and refresh-token expired in the same time with sending email.

How long is expiracy of refresh token? access token?

> For the solution: save to cache for the case of logout is good in security and privacy?

Let's reproduce first. 
But the cache should be domain scoped, no?

**Comment by hoangdat** [comment]
- Web app: access_token 5 mins, refresh_token 1 week will expire
- Mobile: access_token 2 mins, refresh_token 2 years will expire
@guimard Am I right with the expiration time of our tokens?

**Comment by chibenwa** [comment]
Ok then maybe linked to oldish app then...

**Comment by chibenwa** [comment]
This happened AGAIN to gael lago on tmail.linagora.com web

Input a long test
Forget it a couple of minutes
Come back to the webpage: he was redirected to SSO
When loging back in, the input was loss.

PLEASE use a local cache in order NOT to loose user input.

**Comment by hoangdat** [comment]
Handle with #2882

**Comment by hoangdat** [comment]
https://github.com/linagora/tmail-flutter/issues/2987
