### ISSUE TITLE
[Attachment] Missing attachment file in email which sent from gmail to Tmail

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#2369]
OS:  WEB / IOS / ANDROID
Device: Laptop / Mobile
TMail version: 0.10.5

### *Precondition: 
- User using GMAIL to send an email which included attachment to TMAIL

### *Reproduce Step:
1, User send attachment email from GMAIL to TMAIL
2, Check inbox in TMAIL

### **Actual:** 
- The attachment icon still displaying
- Attachment file is missing

### **Expected:** 
- The attachment icon is displaying
- Attachment file is not missing

https://github.com/linagora/tmail-flutter/assets/124866146/2823cde8-cb89-41cb-8fec-88ec38974ac8

**Comment by hoangdat** [comment]
@QuangHoang1210 urgent ticket.
