### ISSUE TITLE
[Android Only] User have been login account 1 and uninstall TMAIL but when user reinstall it then system auto login account 2

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#2373]
OS:  ANDROID
Device: Mobile
TMail version: 0.10.5

### *Precondition: 
1, User login TMAIL as account 1
2, User logout

### *Reproduce Step:
1, User open TMAIL
2, User login as account 2
3, User go to CHPLAY Store and unistall TMAIL
4, User reinstall TMAIL
5, User click on [Open] to access TMAIL

### **Actual:** 
- System automatically login as account 1

### **Expected:** 
- System should redirect user to login page and require user login again

**Case 1: Logout acc1 and login as acc2 -> Unistall Tmail -> Reinstall again -> Issue: System auto login acc1**

https://github.com/linagora/tmail-flutter/assets/124866146/b5ec002e-a503-43ac-8aec-6e3bbaaad674

**Case 2: Logout acc1 -> Unistall Tmail -> Reinstall again -> Issue: System auto login acc1**

https://github.com/linagora/tmail-flutter/assets/124866146/e931defe-c0a1-4ed8-b609-cd0323a49d3f

**Comment by hoangdat** [comment]
please test again
