### ISSUE TITLE
[Android Only] User cannot select account in suggestion dropdown list at Login screen

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#2374]
OS:  ANDROID
Device: Mobile
TMail version: 0.10.5

### *Precondition: 
1, User already login that account before that make it existed in Suggestions dropdown list at login screen

### *Reproduce Step:
1, User open TMAIL
2, User input some word which relate to account in precondition
3, User select that account in suggestion dropdown list

### **Actual:** 
- Can't select. Nothing happen

### **Expected:** 
- User can select it

https://github.com/linagora/tmail-flutter/assets/124866146/dc7ab3b9-79a3-43f0-8d67-51ba6a9f1cc0

**Comment by dab246** [comment]
@QuangHoang1210  I cannot reproduce it. It still works fine.
