### ISSUE TITLE
Too many attachments displayed

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#2388]
oncommit-tmail.linagora.com

![image](https://github.com/linagora/tmail-flutter/assets/6928740/474c8734-2e75-4ba7-9dec-3d153b115584)

Should be

![image](https://github.com/linagora/tmail-flutter/assets/6928740/f2fc81eb-6fe7-4d1b-bafd-232d32042bb1)

Note that the signature image is here displayed as an attachment and inlined in the content.

```
------=_NextPart_001_004E_01DA2860.67B4BB00
Content-Type: image/png;
	name="image001.png"
Content-Transfer-Encoding: base64
Content-ID: <image001.png@01DA285F.638DEA20>

iVBORw0KGgoAAAANSUhEUgAAAH4AAACRCAYAAAAFMQzfAAAAAXNSR0IArs4c6QAAAAlwSFlzAAAO
xAAADsQBlSsOGwAAABl0RVh0U29mdHdhcmUATWljcm9zb2Z0IE9mZmljZX/tNXEAAEd1SURBVHhe
7V0HYJXV2X6z9yYJCSEJI+y9kSkIqODAhUq1tWqxraOtVqttVbDaWq1arbPWuqrVWhVUFBwgCsje
e2WRBLL3Tv7nOef77spNcm+SG+0vR0PG/cY55x3n3a/v0qVL5cz4/u2A77333tv8XV92s5phs3h5
```

Content ID is matching, but no `Content-Disposition: inline`.

If we succeeded to inline the attachment in the display, maybe we should not display it as an attachment?

Mail user agent: `X-Mailer: Microsoft Outlook 16.0`

**Comment by dab246** [comment]
@chibenwa please help us attach `eml` file

**Comment by chibenwa** [comment]
[fetch.txt](https://github.com/linagora/tmail-flutter/files/13597405/fetch.txt)
