### ISSUE TITLE
[Android/IOS] Missing Unsubcribe hyperlink on mobile

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#2390]
OS: Android / IOS
Device: Mobile only
TMail version: 0.10.5

### *Data Test:
EML
[Re_ \[linagora_tmail-flutter\] \[Android Only\] User cannot select account in suggestion dropdown list …..eml.zip](https://github.com/linagora/tmail-flutter/files/13600823/Re_.linagora_tmail-flutter.Android.Only.User.cannot.select.account.in.suggestion.dropdown.list.eml.zip)

### *Reproduce Step:
1, User click on email which included hyperlink to unsubcribe

### **Actual:** 
Missing Unsubcribe button

### **Expected:** 
Should have on mobile

Base on this AC: https://github.com/linagora/tmail-flutter/issues/1718 

![Image](https://github.com/linagora/tmail-flutter/assets/124866146/b5dafdc5-3311-484c-b34a-33e9941cc2f5)

https://github.com/linagora/tmail-flutter/assets/124866146/f3d3e9fa-ce22-4a35-ad7f-68cfc5f09f2e

Unsubcribe button cacth expectation on Website:

![Image](https://github.com/linagora/tmail-flutter/assets/124866146/6f95ea14-628c-4f3a-af45-c8cd7669e9f0)

**Comment by chibenwa** [comment]
No excuse: there's a header:

```
List-Unsubscribe: <mailto:unsub+A5YU4YTLKPIH4WPOWDES7UODPZSJHEVBNHHHREA2KY@reply.github.com>,
 <https://github.com/notifications/unsubscribe/A5YU4YQOGFOPZE3437PBCNTYIEUZHANCNFSM6AAAAABAFBGA2I>
```

**Comment by dab246** [comment]
This is not an error. According to the design, the `Unsubscribe` button is added to the context menu on Mobile (Only with portrait mode). With other screens it will be displayed immediately after the email sender address.

![Screenshot 2023-12-08 at 08 42 05](https://github.com/linagora/tmail-flutter/assets/80730648/b461602d-8aa5-4682-ba9b-a021b3185cea)
