### ISSUE TITLE
[Website] Unsubcribe hyperlink on website is not correct blue color

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#2391]
OS: Website
Device: Laptop
TMail version: 0.10.5

### *Test data:
EML: 

[Re_ \[linagora_tmail-flutter\] \[Android Only\] User cannot select account in suggestion dropdown list …..eml.zip](https://github.com/linagora/tmail-flutter/files/13600823/Re_.linagora_tmail-flutter.Android.Only.User.cannot.select.account.in.suggestion.dropdown.list.eml.zip)

### *Reproduce Step:
1, User click on email which included hyperlink to unsubcribe

### **Actual:** 
Unsubcibe hyerplink is having grey color

### **Expected:** 
It should be blue color 

Base on this AC: https://github.com/linagora/tmail-flutter/issues/1718 

Unsubcribe button on Website:

![Image](https://github.com/linagora/tmail-flutter/assets/124866146/6f95ea14-628c-4f3a-af45-c8cd7669e9f0)

**Comment by dab246** [comment]
It is not bug. Please confirm it with the design.

![Screenshot 2023-12-08 at 08 55 17](https://github.com/linagora/tmail-flutter/assets/80730648/dde3670e-c94b-4f87-9b10-bc72de5fdec4)
