### ISSUE TITLE
[Sorting & Search Result] Sort by subject name A-Z or Z-A is not correctly

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#2392]
OS: Website
Device: Laptop
TMail version: 0.10.5

### *Reproduce Step:
1, User click on advance search
2, User select sort by subject name A-Z / Z-A

### **Actual:** 
The list of email in searching result is sorted incorrectly. It feel like not base only on condition as Subject Name.

It base on folder where email placed in also.

### **Expected:** 
It should be sorted base on only Subject Name --

https://github.com/linagora/tmail-flutter/assets/124866146/1a4ffb0b-b95b-4388-8031-0be3307409e0

**Comment by chibenwa** [comment]
James removes `Re`,` Fwd ` from begining of messages.
Sender is another topic.
Weird emojis could likely be filtered (ASCII text only kept when indexing). @quantranhong1999  can you open a James issue for that?
