### ISSUE TITLE
[UI] [Quick Search] Email Searching result is blink blink once user click to Sorting dropdown list button

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#2393]
OS:  WEB
Device: LAPTOP
TMail version: 0.10.5

### *Reproduce Step:
1, User click on Search email bar
2, User input "Test"
3, User select "qatest3@linagora.com" in quick search
4, User click on Sorting dropdown list
5, User select any option
6, User click on Sorting dropdown list again

### **Actual:** 
The searching result is reload again once user click on sort dropdown list

### **Expected:** 
Only reload searching result once user already select sort option in dropdown list

https://github.com/linagora/tmail-flutter/assets/124866146/9aa3b99a-a6c0-4717-9053-8f3efa3e1d22

**Comment by dab246** [comment]
- Fixed at PR #2360
- Demo



https://github.com/linagora/tmail-flutter/assets/80730648/3d38a36c-5eb2-4c86-a87c-438da5be9644
