### ISSUE TITLE
Copy feature

### ISSUE THREAD

**Issue by Arsnael** [linagora/tmail-flutter#2407]
I was actually surprised to realize this morning, when I wanted to copy some emails into an other mailbox, that It seems completely missing in Tmail flutter app. 

I don't see any issue opened on that either. Why? I feel this is such a basic email feature for an email client, and I think it is something we are missing.

I had to resort doing that action on IMAP with Thunderbird in the end...

WDYT?

**Comment by chibenwa** [comment]
Why would you need "Copy" and not "Move" ?

**Comment by Arsnael** [comment]
> Why would you need "Copy" and not "Move" ?

Maybe I want some emails in multiple mailboxes for easier search and classification?

> How do you even do a "copy" with thunderbird?

Right click, in the drop down menu you have copy, I think below the move one?

But honestly I forgot labels was a topic and it works for that too, so I will close this :)

**Comment by chibenwa** [comment]
To be fair if I want a copy of a mail I send I add myself as a (b)cc ...
