### ISSUE TITLE
Notification when receive new email

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#241]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC

* TODO: {link}

## Definition

- Given that I am Tmail user and logged-in to the app 
- Given that the notification permission is turned on for Tmail app and the app is running in background
1. Types of notification
- When there is a new message, there will be push notification types as below:
   - Lock screen notification: This notification is shown when the screen is locked and there is a new message. And this notification will disappear when user open lock- screen
   - Status bar: When there is a new message, , it first appears as an icon in the status bar. Only in Android 
   - Floating notification/Heads up (Android) or Banners (IOS) It appears only if the device is unlocked.: This floating notification disappears after a moment, but remains visible in the notification center as usual.
   - Notification center: User can swipe down on the status bar to open the notification drawer, where they can view more details and take actions with the notification. All notifications will disappear when user opens the Tmail app 
   - App icon badge: app icons indicate number of unread messages with a colored "badge" (also known as a "notification dot") on the app launcher icon.

-2. A notification of new message will includes information:
   - App icon and name
   - Time to receive the new message
   - Sender' name and his email address 
   - Subject (partial if it is too long) 
   - Message's content (partial if it is too long) 
  
3. Group notification
 
   - In Android mobile, if there is more than 1 new message, they will be grouped in 1 notification
   - If user swipe down this group notification, he can see details notification of each new email
 
[Back to Summary](#summary)

## Screenshots

[Back to Summary](#summary)

## Design ticket

https://ci.linagora.com/linagora/lgs/design/-/issues/137

## Misc

None

[Back to Summary](#summary)

**Comment by hoangdat** [comment]
Behavior of notification when app in foreground or background

**Comment by hoangdat** [comment]
@dieptran88 this need to be filled

**Comment by hoangdat** [comment]
### DoD:
- When user click on notification on Android/iOS, app will open the `EmailView` of this Email

**Comment by guimard** [comment]
Hi, on Android 12, I no more receive any notifications. It seems that Tmail doesn't receive pushed info from server

**Comment by hoangdat** [comment]
> Hi, on Android 12, I no more receive any notifications. It seems that Tmail doesn't receive pushed info from server

yes, a side effected issue, we fixed this. Next version > v0.7.6 will include it
