### ISSUE TITLE
[Story] As a user, I want to delete email (move to trash) 

### ISSUE THREAD

**Issue by dieptran88** [linagora/tmail-flutter#242]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC

https://app.zenhub.com/workspaces/tmail-flutter-60d039db6ef62a0013432c14/issues/linagora/tmail-flutter/26

## Definition

- Given that I am a Tmail user and I already had an account (John Doe) 
- Given that i log-in successfully to the Tmail app
- I can open a mailbox and see the list of emails
- The action :"Move to Trash" is available on every mailbox/folder except folder:"Trash".
- I can move a message to Trash in 2 ways:
 1. I open that email, then I click on icon Delete on the top right, then the email is moved to Trash folder
      - I am navigated back to thread-view and see a toast message: "Moved to Trash" with button Undo
      - I click button Undo, the email is reverted to original mailbox
 2. - On the thread-view, i can long-press on the avatar to select multiple emails, then there will be an action bar displayed on the top.
     - I can touch the icon "Delete" then selected messages will be move to Trash, or i can click on three-dots button then there will be a context menu that contain actions. I select option "Move to Trash"
      - I am navigated back to thread-view and see a toast message: "Moved to Trash" with button Undo
      - I click button Undo, the emails is reverted to original mailbox

[Back to Summary](#summary)

## Screenshots

![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/3bd66aeb-a23d-4e69-9d54-42542c5f5349) ![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/1d94f4e8-3341-40b2-9d5d-542585f7b891)

![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/aa6a4496-3066-4030-a66a-68963c9c255f) ![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/e4ed3d18-f013-4f65-abcb-d49a14a8fddc)

[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

**Comment by Kevinle2312** [comment]
PAssed on Production platform.
