### ISSUE TITLE
[Composer] Something is overlapping the body in composer

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#2427]
OS:  WEB only
Device: laptop
TMail version: 0.10.5 Tmail canary only

### *Precondition: 
- User not attach anything in email composer

### *Reproduce Step:
1, User click composer
2, User write long content as a link
3. User scroll down a bit

### **Actual:** 
- Something is overlapping the body in composer

### **Expected:** 
- It should be same with production 0.10.4

### **NOTE:** 
**Happen only on Tmail 0.10.5 canary:**

![Image](https://github.com/linagora/tmail-flutter/assets/124866146/f48063f8-2c9f-45f9-bc0b-b7e797f32495)

https://github.com/linagora/tmail-flutter/assets/124866146/6f1a713c-e71d-4b40-9c41-de475dd01905

**Working well on Tmail 0.10.4 Production:**

![Image](https://github.com/linagora/tmail-flutter/assets/124866146/ee12efac-4a60-43ec-a098-3c751a48fa54)

https://github.com/linagora/tmail-flutter/assets/124866146/f749d786-ca49-40d1-a1ff-8a9afd2cd361

**Comment by dab246** [comment]
- [x] Work well on Chrome Mac M1
- [ ] On WindowsWindows/Linux. 


https://github.com/linagora/tmail-flutter/assets/80730648/de63e17c-18ad-4e69-821b-8530de133361

**Comment by hieutbui** [comment]
- On Windows

https://github.com/linagora/tmail-flutter/assets/80142234/705f42b0-380b-49d5-be0d-756b0de296ea

**Comment by hoangdat** [comment]
@dab246 hello
