### ISSUE TITLE
[Safari Only] Cannot access Twake Mail -- Waiting really long until 10 minutes but still loading

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#2439]
OS:  IOS only
Device: laptop
TMail version: 0.11.0 Twake mail canary 

### *Precondition: 
- User never access Twake mail on this device <Mac OS>
- User never login Twake mail on Mac OS Safari

### *Reproduce Step:
1, User clear cache < or use new device> -- noted: Clear cache -- can login sometimes, but new device cannot access.
2, User access Twake mail canary

### **Actual:** 
- User cannot access twake mail canary
- Main.dart still in Queue really long not stop loading
- But user can access Twake Mail production - tmail.Linagora.com

### **Expected:** 
- User can access Twake Mail canary smoothly

**Video**

https://github.com/linagora/tmail-flutter/assets/124866146/ba650c9f-09fc-4877-8819-534166efa3ee

**Noted**
- Working well on firefox and chrome both twake mail production and canary.
- Issue on Safari for canary only, working well on production.

**Comment by hoangdat** [comment]
#2310
