### ISSUE TITLE
[Recovery Email] Recovery is wrong logic

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#2441]
OS:  IOS only
Device: laptop
TMail version: 0.11.0 Twake mail canary 

### *Precondition: 
- User moved some email to Trash

### *Reproduce Step:
1, User go to Trash folder
2, User select 6 email in Trash folder
3, User select Delete email forever
4, User go to Inbox folder
5, User select 5 email in Inbox folder and move them to Trash folder
6, User click three dot beside Trash folder and click on Recovery 
7, User select that 4 Recovery Emails and Move them to Trash
8, User try Recovery again -> System recovery that 4 email which move to Trash at step 7
9, User try Recovery one more time -> System still recovery same that 4 email which move to Trash at step 7
10, User try Recovery one more time -> Again , System still recovery same that 4 email which move to Trash at step 7
...

### **Expected:** 
- When do recovery email -> System get one list email which have been removed in that recovery period then the most recent 5 emails which in the list will be selected to Recovery.
- If no other Emails have been Delete Forever during this time then when user do recovery again -> the next 5 most recent emails which in the list <excluded 5 emails which already recovery at the previous step> will be selected to Recovery. And so on.
- Recovery function will not support for the Emails which only Move to Trash.

**Video** [Link](https://drive.google.com/file/d/1UzWKX9yNCUAl9v7Ve4ggM_xu4O3tPPrV/view?usp=sharing)

Story: [Link](https://github.com/linagora/tmail-flutter/blob/master/docs/stories/EPIC-Restore%20deleted%20messages/TF-1719-User-can-restore-deleted-messages.md)

**Comment by hieutbui** [comment]
@QuangHoang1210 As BE reply, this issue is because of the logic of `EmailRecovery` that user can only recover last 5 emails matched.
