### ISSUE TITLE
[Android only] If user using old version and upgrade version from CHPLAY then New Twake Mail App icon is not change yet in Logo on app and preview app in slider

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#2442]
### Not yet changed on android Logo on page and logo on preview app

**Precondition:** User user old version 0.10.5 and try upgrade Twake Mail new version 0.11.0 trên chplay

**Noted: Only change in Playstore**

**Comment by quantranhong1999** [comment]
Feedback: the new Twake Mail App icon has been updated automatically just fine on 0.11.2 for me.

The TMail app upgrade has been executed automatically for me BTW.
