### ISSUE TITLE
[Sorting] Cannot sort with sender name

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#2447]
OS:  IOS / Android / All browser <chrome, firefox, safari>
Device: laptop / mobile
TMail version: 0.11.0 Twake mail canary 

### *Reproduce Step:
1, User input any keyword in search field
2, User select sort option = Sender name

### **Actual:** 
- Blank page

### **Expected:** 
- Should sort by sender name A-Z, Z-A

### **Video**

**Mobile**

https://github.com/linagora/tmail-flutter/assets/124866146/18dd1fcc-d16b-4681-8a2d-c31a57293fbb

**Web**

https://github.com/linagora/tmail-flutter/assets/124866146/b5364bf9-c2ba-49d5-897f-bd597d3ec0f2

**API request**
```
{"using":["urn:ietf:params:jmap:core","urn:ietf:params:jmap:mail","urn:apache:james:params:jmap:mail:shares"],"methodCalls":[["Email/query",{"accountId":"912618096e03fb03fe14293a97102272d4875bd9c3d80ad49de32c58bb4b28bd","position":0,"filter":{"operator":"AND","conditions":[{"text":"quang"}]},"sort":[{"isAscending":true,"property":"from"}],"limit":20},"c0"],["Email/get",{"accountId":"912618096e03fb03fe14293a97102272d4875bd9c3d80ad49de32c58bb4b28bd","#ids":{"resultOf":"c0","name":"Email/query","path":"/ids/*"},"properties":["id","subject","from","to","cc","bcc","keywords","size","receivedAt","sentAt","preview","hasAttachment","replyTo","mailboxIds","header:X-MEETING-UID:asText"]},"c1"]]}
```

**API response**
```
{"sessionState":"2c9f1b12-b35a-43e6-9af2-0106fb53a943","methodResponses":[["error",{"type":"serverFail","description":"Request failed: [search_phase_execution_exception] all shards failed"},"c0"],["error",{"type":"invalidResultReference","description":"Failed resolving back-reference: List((,List(JsonValidationError(List(MethodCallId(c0) references a MethodName(error) method),List()))))"},"c1"]]}
```

**Comment by Arsnael** [comment]
Result of the mapping on the mailbox index not being updated on prod after the code was implemented on the backend: https://github.com/apache/james-project/pull/1811

I will update the mapping, just give me a bit of time, need to be careful on prod with those things :)

**Comment by Arsnael** [comment]
That likely needs a reindexing though... I hate those in prod... Might need to think carefully here

**Comment by Arsnael** [comment]
@chibenwa what is the best approach here do you think:

- apply new mapping on mailbox_v2 and reindex data fully (documents will be deleted before being reindex by the task)
- create mailbox_v3 with new mapping, keep read alias on mailbox_v2, have write alias point to v2 and v3, reindex tmail on mailboxv3, delete mailbox_v2 when finish reindex

**Comment by chibenwa** [comment]
> have write alias point to v2 and v3

Won't do as the structure between the two index is different.

Full reindex needed...

**Comment by Arsnael** [comment]
Alright chief, first option then. Will get on this this afternoon or tomorrow, so hopefully it runs the weekend without issues and it fixes everything early next week :)

**Comment by Arsnael** [comment]
@hoangdat Pretty sure this has been fixed and released on prod btw, should work now

**Comment by hoangdat** [comment]
fixed
