### ISSUE TITLE
[SAFARI ONLY] Cannot access Twake Mail on Safari

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#2467]
OS:  Web Safari
Device: laptop 
TMail version: 0.11.3 Twake mail canary 

### *Reproduce Step:
1, User clear cache or using incognito tab to access Twake Mail Canary

### **Actual:** 
- Blank page, loading animation

### **Expected:** 
- Can access Twake Mail normally

### **Video**

https://github.com/linagora/tmail-flutter/assets/124866146/057f2a32-4b99-44e5-a0d4-e9321e53044b

**Comment by hoangdat** [comment]
can not reproduce.

**Comment by hoangdat** [comment]
same with #2310
