### ISSUE TITLE
[Improvement] Image isn't resized in the mobile app

### ISSUE THREAD

**Issue by tprudentova** [linagora/tmail-flutter#2474]
Version: 0.11.2, Android 

Image imbedded into text isn't resized and is displayed in full size, which makes it hard to view it. You have to scroll to see different parts of the image 

https://github.com/linagora/tmail-flutter/assets/97684890/6e4f0ef8-4bcb-417e-92e5-a89ffcb57d8e

**Comment by hoangdat** [comment]
Hi @tprudentova , how you input this image? Can we compare with other email client in mobile?
