### ISSUE TITLE
[Bug] Fonts don't work in mobile app

### ISSUE THREAD

**Issue by tprudentova** [linagora/tmail-flutter#2475]
Version: 0.11.2, Android

1. Open Composer, enter some text 
2. Highlight text and try to change fonts (bold, italic etc) 
3. Nothing happens

https://github.com/linagora/tmail-flutter/assets/97684890/02241a1c-7007-427d-bce4-3dda31c01d77

**Comment by hoangdat** [comment]
@QuangHoang1210

**Comment by hoangdat** [comment]
- [ ] cherry to `dev-feature` branch
