### ISSUE TITLE
[TwakeMail-Box] Mark as spam should be hidden with mail in TwakeMail-box cause we also don't have Spam folder in TwakeMail-Box

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#2479]
OS:  Web Firefox / Chrome
Device: laptop 
TMail version: 0.11.3 Twake mail preprod 

### *Test data:
firstname23.surname23
firstname31.surname31

### *Precondition:
- Tmail-box 1 <hiring> is config to user A
- User A <userA@linagora.com>

### *Reproduce Step:
1, User A and B access TwakeMail in different browser
2, User A select TwakeMail-box
3, User A hoover and click on three-dot action

### **Actual:** 
- Dropdown list will be displayed
- Mark as spam action still be there

### **Expected:** 
Should hide Mark as spam option in dropdown list

![Image](https://github.com/linagora/tmail-flutter/assets/124866146/bf697614-3459-45af-b08d-995c7849d011)

**Comment by hoangdat** [comment]
User Story: #1127
