### ISSUE TITLE
[Improve] [Feedback] User cannot edit insert link in composer

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#2482]
1, Feedback from Anton:
```
I didn't manage to edit link name.
I have this window and it's not scrollabel
```

![Image](https://github.com/linagora/tmail-flutter/assets/124866146/426f5c79-db42-4d3d-95d0-ad407d8af1d2)

-> Known issue: https://github.com/linagora/tmail-flutter/issues/2426

**Comment by chibenwa** [comment]
Closing as it is a duplicate?
