### ISSUE TITLE
[Improve] [Feedback] UI some button not responsive and unclickable

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#2486]
1, Feedback from Anton:
```
UI is not responsive
Some of the elements are responsive, but buttons are not, and I don't see any reson why. For me it looks like dead, and every time I have a feeling that it's not clickable and when I click nothing will happen
```

--> I cannot reproduce cause now the UI is responsive and buttons are clickable

**Video:**

https://github.com/linagora/tmail-flutter/assets/124866146/6c5e6dae-9e13-4fbb-a711-bb8cd9327c33

**Comment by chibenwa** [comment]
Design feedback needed IMO
