### ISSUE TITLE
[Improve] [Feedback] Missing app grid

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#2490]
1, Feedback from Anton:

`The menu is still old with "old" Twake and without Twake Drive `

--> What is your version!? Cause its working well on v.0.11.3

**Video:**

https://github.com/linagora/tmail-flutter/assets/124866146/767b4044-eb34-4aa5-a1d8-5fc70c966742

**Comment by chibenwa** [comment]
Deployment issue, not a software issue
