### ISSUE TITLE
[Improve] [Feedback] Signature buggy

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#2492]
1, Feedback from Anton:
`Signature is still bugy, sometimes I have multiple signatures in one email or when I view email in different app it looks like this with the button `

--> Following this issue: https://github.com/linagora/tmail-flutter/issues/2249

**Comment by chibenwa** [comment]
I feel this might not be happening on the latest version 0.11.3 .

Correct @shepilov  ?

**Comment by shepilov** [comment]
> I feel this might not be happening on the latest version 0.11.3 .
> 
> Correct @shepilov ?

I use the 0.11.3
<img width="255" alt="image" src="https://github.com/linagora/tmail-flutter/assets/14924963/a6f597ec-652d-4dee-9f92-f4aac3915b34">
