### ISSUE TITLE
Missing FR translations

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#2506]
The following terms are not translated:

`Folder visibility` should be in French `Visibilité des dossiers`

`Clean` should be in French `Nettoyer`

`Clear folder` should be in French `Nettoyer le dossier`

`The message in Spam folder will be permanently deleted and you will not be able to restore them`
=>
`Les messages dans le dossier Spam seront définitivement supprimé et vous ne pourrez pas les restaurer`

![Capture d'écran 2024-01-23 151128 (1)](https://github.com/linagora/tmail-flutter/assets/6928740/a46c89c2-ef33-4b8b-bf87-2c8b9fa65397)

![Capture d'écran 2024-01-23 151128](https://github.com/linagora/tmail-flutter/assets/6928740/88aa66b9-34b6-4d87-8744-a3fed3b96369)

**Comment by chibenwa** [comment]
cc @hoangdat quick fix expected in a v0.11.4 at least for web, asap.

**Comment by hoangdat** [comment]
https://github.com/linagora/tmail-flutter/pull/2507

**Comment by chibenwa** [comment]
![image](https://github.com/linagora/tmail-flutter/assets/6928740/61c854e3-9173-4d82-9356-9d1c1ad62777)

not fixed!
