### ISSUE TITLE
[Bug] Spellcheck disable on the field for email body writing

### ISSUE THREAD

**Issue by Buffer0117** [linagora/tmail-flutter#2509]
### Description
When writing a new email, none of the spellcheck suggestion are shown.

The property "spellcheck" is currently set to false.
![Capture d'écran 2024-01-23 174758](https://github.com/linagora/tmail-flutter/assets/145337315/301d8ab9-8a19-42fa-9472-8e549e91fe4a)

### Expected result
Underlining the incorrect words according to spellcheck browser settings.

![image](https://github.com/linagora/tmail-flutter/assets/145337315/cfa64539-ed68-42d4-b62b-511a6d220af6)

### Current behavior
The spellcheck property is disabled in the HTML tag

![image](https://github.com/linagora/tmail-flutter/assets/145337315/8284e799-8c5e-49a7-bd9f-324e95539012)

#### Reproduction Steps
1. Open compose view
2. Write some words for the body message
3. Make some mistakes in the words spelling

### Acceptance criteria

As a user, I would like to be notified whenever I make a mistake according to my spellcheck settings.
Delegating the work to my browser for a unified experience is acceptable. (e.g. waved underline of the mistake)

### Context

- Browser
- Android

### Additional information

Everytime

**Comment by hoangdat** [comment]
- [ ] when I tried to change `spellcheck=true`, I also have the problem with checker toolbox 
<img width="1141" alt="Screenshot 2024-01-24 at 17 13 32" src="https://github.com/linagora/tmail-flutter/assets/6462404/6c0c5aad-bfa6-4c24-a36d-65ba3de821cc">

**Comment by Buffer0117** [comment]
> * [ ]  when I tried to change `spellcheck=true`, I also have the problem with checker toolbox

What is "Checker toolbox" a browser plug-in ?

**Comment by Buffer0117** [comment]
> * [ ]  when I tried to change `spellcheck=true`, I also have the problem with checker toolbox
> 
> <img alt="Screenshot 2024-01-24 at 17 13 32" width="1141" src="https://private-user-images.githubusercontent.com/6462404/299277141-6c0c5aad-bfa6-4c24-a36d-65ba3de821cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxMDE5NTgsIm5iZiI6MTcwNjEwMTY1OCwicGF0aCI6Ii82NDYyNDA0LzI5OTI3NzE0MS02YzBjNWFhZC1iZmE2LTRjMjQtYTM2ZC02NWJhM2RlODIxY2MucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjRUMTMwNzM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWY3ODM1ZGMxYzMwNmRkYWVlMzNlN2I5YzIzMGMxNTZlNTBkZmY3NTA1N2M5ZGI1MzdlNGQ5ZjcxZDM5Y2FiNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.NzJ_-P6yC_WLgdz42GO5BkkixbL5fArBE4b1lYBN-yQ">

considering the screenshot I feel like the panel on the right is not drawn at the correct place.
maybe an issue with the zindex and the size of the panel ; the Checker Toolbox tries to align with the window border and not the edit div for the message writing ? :thinking:

**Comment by hoangdat** [comment]
Exactly, not in the correct place. We will take a look more for this. Thanks for your reporting

**Comment by chibenwa** [comment]
Hello.

This is requested by a customer too.

**Comment by chibenwa** [comment]
![signal-2024-01-26-102734](https://github.com/linagora/tmail-flutter/assets/6928740/458f138f-20f3-4408-bf59-d7e9294cd5ba)

Deployed on tmail.linagora.com
