### ISSUE TITLE
[Improvement] After I selected text in subject, I need to click exactly on the subject field to un-select that text 

### ISSUE THREAD

**Issue by dieptran88** [linagora/tmail-flutter#2514]
### Context
 
- Web v0.11.3 
-  https://tmail.linagora.com/

### Reproduction Steps
1. Open an email 
2. Select some text from the subject
3. When I want to unselect the text , I Move the mouse to outside area of subject field and click the mouse => The text is still selected, I need to move the mouse  exactly to the field Subject and click then the text is unselected 

=>> Expectation: When I move the mouse to any other area the text should be un-selected 

### Additional information

[screen-capture (65).webm](https://github.com/linagora/tmail-flutter/assets/68209176/2d6fc5c1-a5a1-49d9-8f35-b5b69955e8d9)

**Comment by HeonHeo23** [comment]
Can I work on this issue?

**Comment by hoangdat** [comment]
> Can I work on this issue?

Yes please. Thank you
