### ISSUE TITLE
[Bug] When I rename a folder with special characters, it does not show error message 

### ISSUE THREAD

**Issue by dieptran88** [linagora/tmail-flutter#2517]
### Context

- Web v0.11.3
- https://tmail.linagora.com/

### Reproduction Steps
Case 1: Rename a folder 
1. Click Rename a folder
2. In rename popup, enter some special characters => Save
3. The folder name is not changed but there is no error message 

=> Expectation: When the folder name is not changed, there should be an error message to explain 

Case 2: Create a new folder
1. Click create a new folder
2. Input folder name with some special characters => Save
3. There is an error message displayed but the message content should be improved

### Additional information
[screen-capture (66).webm](https://github.com/linagora/tmail-flutter/assets/68209176/f710076e-b2b5-4e0d-a2f4-d99bb583fdc0)

**Comment by dab246** [comment]
Related #444
