### ISSUE TITLE
Twake mail CNB can not run in Safari

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#2529]
### Desc:

![Image](https://github.com/linagora/tmail-flutter/assets/6462404/619d53a5-5ead-48bf-8252-5d441e79843d)

### Session request has 401 error 
![Image](https://github.com/linagora/tmail-flutter/assets/6462404/7ad8af14-ed5e-423f-8726-576bbb71a2c1)

**Comment by chibenwa** [comment]
Apisix 302: safari do not send creds when following the redirect.

Solution: Proxy pass instead so that Safari can do this in one request.
