### ISSUE TITLE
User cannot see all recipients list if email have a lot of recipients

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#2531]
### Desc:

![Image](https://github.com/linagora/tmail-flutter/assets/6462404/db7ffdb4-d724-47b9-b190-c18914dd4d47)

- when user has many recipients in each field: `to`, `cc`, `bcc`, user can not see all the list

### DoD:
- [ ] maximum display recipients widget 50% of email view when use try to expand 
- [ ] support scroll on it

**Comment by dab246** [comment]
Duplicated #1927
