### ISSUE TITLE
[Mobile] Add attachments and inline image button also at the app bar of Composer in mobile

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#2532]
### Desc:

<img src="https://github.com/linagora/tmail-flutter/assets/6462404/64b8ae1b-4032-4802-87e7-deb70b5cf9b4"  width="180" >

### DoD:
- [ ] inline button
- [ ] attachment button

**Comment by dab246** [comment]
What do you mean?. On mobile/tablet devices, we now support `attachment/InlineImage` on the `keyboard` toolbar

**Comment by dab246** [comment]
- [ ] Support for mobile/tablet

**Comment by hoangdat** [comment]
- [ ] need to cherry to `v0.11.3-patch4-dev-feature` branch
