### ISSUE TITLE
Random rendering issue with TMail

### ISSUE THREAD

**Issue by Arsnael** [linagora/tmail-flutter#2536]
### Description

This morning TMail web reloaded and I had issues: I only had Inbox visible (not other folders) and I could not send emails.

Other people experienced potentially the same issue these days (like Nhung)

The only way we could solve this was to clear cache and cookies, and reload.

I was on canary, but I think Nhung was on normal tmail.linagora.com.

### Context

TMail-web
Browsers: Firefox (Nhung), Brave (Rene)

### Additional information

![Screenshot from 2024-01-30 11-12-14](https://github.com/linagora/tmail-flutter/assets/9005025/f8cdb566-1bd7-42c0-9c10-a5eae9fa743d)

**Comment by hoangdat** [comment]
#### Reproduced:

<img width="512" alt="image" src="https://github.com/linagora/tmail-flutter/assets/6462404/11928e82-1d11-499a-93d3-d91f19942082">

#### Analysis:
- Context: `MailboxRepository` get the data from local first:
  - if cache hit (have mailbox + cache), `/changes` to update 
  - if cache miss (no mailbox, no state), `/get` to update view
- What happen if cache hit, but not have all the data? yeap, this is the issue.

#### Issue: 
  - (i) open the app when token expired
  - (ii) app need to handle logout + clean data (heavy work)
  - (iii) to go to SSO page
  
in step (ii), the heavy work did not complete, so cache still have some data
- [ ] change the logic to get all mailbox
  - get from the local (support quick response and offline mode) -> yield to UI
  - get `Mailbox/get` from JMAP to update the list of mailbox correctly
- [ ] make sure heavy work completed when logout before do any redirection.
