### ISSUE TITLE
[CNB] Wrong counting unread number when user move unread email to other mailbox and mark it as read or move it to other mailbox again

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#2543]
### ENV: 
- Device: IOS
- Browser: SAFARI / CHROME
- ENV: CNB preprod

### 7- Wrong counting unread number when user move unread email to other mailbox and mark it as read or move it to other mailbox again

**Step:**
1, User select one mail and mark as unread
2, User move it to any mailbox <for example: Archive>
3, User go to Archive and mark that to be read
4, User click on left menu to check the unread counting number

**Actual:** Counting unread number still be 1 even if no unread email inside that mailbox
**Expected:**  Counting unread should be true and updated

**Comment by hoangdat** [comment]
```
{
    "sessionState": "2c9f1b12-b35a-43e6-9af2-0106fb53a943",
    "methodResponses": [
        [
            "Mailbox/changes",
            {
                "accountId": "{}",
                "oldState": "ad00ab10-c0e5-11ee-acfa-dbafe6e9d11b",
                "newState": "a89d6610-c0e7-11ee-9f28-dbafe6e9d11b",
                "hasMoreChanges": false,
                "updatedProperties": [
                    "totalEmails",
                    "unreadEmails",
                    "totalThreads",
                    "unreadThreads"
                ],
                "created": [],
                "updated": [
                    "94c415f0-c0e0-11ee-b667-dbafe6e9d11b"
                ],
                "destroyed": []
            },
            "c0"
        ],
        [
            "Mailbox/get",
            {
                "accountId": "{id}",
                "notFound": [],
                "state": "a89d6610-c0e7-11ee-9f28-dbafe6e9d11b",
                "list": [
                    {
                        "totalThreads": 3,
                        "totalEmails": 3,
                        "unreadThreads": 2,
                        "id": "94c415f0-c0e0-11ee-b667-dbafe6e9d11b",
                        "unreadEmails": 2
                    }
                ]
            },
            "c1"
        ],
        [
            "Mailbox/get",
            {
                "accountId": "{}",
                "notFound": [],
                "state": "a89d6610-c0e7-11ee-9f28-dbafe6e9d11b",
                "list": []
            },
            "c2"
        ]
    ]
}
```

**Comment by hoangdat** [comment]
In Prod. When trying move, nothing in `Mailbox/changes`

<details>
  <summary>Prod</summary>
    
```json
{
    "sessionState": "2c9f1b12-b35a-43e6-9af2-0106fb53a943",
    "methodResponses": [
        [
            "Mailbox/changes",
            {
                "accountId": "ID",
                "oldState": "459771d1-c0e9-11ee-9fdb-5545043554ec",
                "newState": "459771d1-c0e9-11ee-9fdb-5545043554ec",
                "hasMoreChanges": false,
                "updatedProperties": null,
                "created": [],
                "updated": [],
                "destroyed": []
            },
            "c0"
        ],
        [
            "Mailbox/get",
            {
                "accountId": "ID",
                "notFound": [],
                "state": "459771d1-c0e9-11ee-9fdb-5545043554ec",
                "list": []
            },
            "c1"
        ],
        [
            "Mailbox/get",
            {
                "accountId": "ID",
                "notFound": [],
                "state": "459771d1-c0e9-11ee-9fdb-5545043554ec",
                "list": []
            },
            "c2"
        ]
    ]
}
```

</details>

**Comment by chibenwa** [comment]
Ok I think that is is link to delays in overall rabbitMQ processing, that is being done asynchronously.

Cc @Arsnael 

```
uri=amqp://${env:TMAIL_AMQP_USERNAME}:${env:TMAIL_AMQP_PASSWORD}@${env:TMAIL_AMQP_HOST}:${env:TMAIL_AMQP_PORT}/${env:TMAIL_AMQP_VHOST}

vhost=${env:TMAIL_AMQP_VHOST}

management.uri=http://${env:TMAIL_AMQP_HOST}:${env:TMAIL_AMQP_MANAGEMENT_PORT}
management.user=${env:TMAIL_AMQP_USERNAME}
management.password=${env:TMAIL_AMQP_PASSWORD}


mailqueue.view.sliceWindow=1h
mailqueue.view.bucketCount=${env:TMAIL_AMQP_BUCKET_COUNT}
mailqueue.view.updateBrowseStartPace=1000

mailqueue.size.metricsEnabled=false

connection.pool.retries=3
connection.pool.min.delay.ms=50
channel.pool.retries=2
channel.pool.max.delay.ms=100
channel.pool.size=40
```

**Comment by dab246** [comment]
> Ok I think that is is link to delays in overall rabbitMQ processing, that is being done asynchronously.
> 
> Cc [@Arsnael](https://github.com/Arsnael)
> 
> ```
> uri=amqp://${env:TMAIL_AMQP_USERNAME}:${env:TMAIL_AMQP_PASSWORD}@${env:TMAIL_AMQP_HOST}:${env:TMAIL_AMQP_PORT}/${env:TMAIL_AMQP_VHOST}
> 
> vhost=${env:TMAIL_AMQP_VHOST}
> 
> management.uri=http://${env:TMAIL_AMQP_HOST}:${env:TMAIL_AMQP_MANAGEMENT_PORT}
> management.user=${env:TMAIL_AMQP_USERNAME}
> management.password=${env:TMAIL_AMQP_PASSWORD}
> 
> 
> mailqueue.view.sliceWindow=1h
> mailqueue.view.bucketCount=${env:TMAIL_AMQP_BUCKET_COUNT}
> mailqueue.view.updateBrowseStartPace=1000
> 
> mailqueue.size.metricsEnabled=false
> 
> connection.pool.retries=3
> connection.pool.min.delay.ms=50
> channel.pool.retries=2
> channel.pool.max.delay.ms=100
> channel.pool.size=40
> ```
> 
> We do not rely on quorum queues. Maybe the overall size of rabbit / delays in the treatment?
> 
> [@hoangdat](https://github.com/hoangdat) when there is no changes of mbxs after moving a mail, and if we retry say 5 mins after, do we have the correct state?

Yes, it worked correctly after a few minutes. Currently, it is working well on servers pre `CNB`, prod, ...



https://github.com/linagora/tmail-flutter/assets/80730648/74b8f8e2-d52e-41e2-ab8a-710fb7a8b147

**Comment by chibenwa** [comment]
Yes it was a deployment issue
