### ISSUE TITLE
[CNB] Many times I got Connection Error while testing

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#2544]
### ENV: 
- Device: IOS
- Browser: SAFARI / CHROME
- ENV: CNB preprod

### 8- Many times I got Connection Error while testing

**Step:**
1, User access cnb
2, User inactive phone - wait until 3-5 mins
3, User retry again some aciton

**Actual:** 
- User has been logout to SSO login and toast message "connection erro" is displayed
- I cannot reload / reopened it in new window or do anything else to access CNB again

**Expected:**  Working smoothly

https://github.com/linagora/tmail-flutter/assets/124866146/19c80f3e-6b5f-4683-a7a2-acaeb2fccc34

**Reload**

https://github.com/linagora/tmail-flutter/assets/124866146/4b64a882-7ffc-4876-a7fd-8cebe391aaf4

**Reopened in new window**

https://github.com/linagora/tmail-flutter/assets/124866146/c0e07d1c-01d9-4534-a1ee-061cd35ff327

**Comment by hoangdat** [comment]
Still have CORS when request `webfinger`.

**Comment by hoangdat** [comment]
> Still have CORS when request `webfinger`.

fixed. Please re-check this issue. Thanks
