### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#2545]
![Screenshot from 2024-02-02 10-22-14](https://github.com/linagora/tmail-flutter/assets/6928740/ff5f6978-baa4-4897-985c-a5cd994948cd)
![Screenshot from 2024-02-02 10-21-50](https://github.com/linagora/tmail-flutter/assets/6928740/10ecc358-c323-462b-ac6c-63ff2c05fad5)

**Comment by hoangdat** [comment]
please comment the your translation here, I will put to the code directly

**Comment by Arsnael** [comment]
Sorry that website annoys me...

Translation:
- Mark as seen => Marquer comme lu
- Star it => Favori
- Reject it => Rejet
- Add action => Ajouter une action
- If => Si
- of the following conditions are met => des conditions suivantes sont remplies
- All => toutes
- Any => au moins une

**Comment by hoangdat** [comment]
- Pending: 
- Folder "{folderName}" could not be marked as read:
- Folder "{folderName}" could not be marked as read. Due "{reason}": 
- Sending: 
- Mark as Spam:
- Forward to:
- Select action:
- Add forwarding address:
- Add action:
- This action is already added:
- Please select a mailbox to move the message
- Confirm all email here are Spam
- Your identities
- Search for identities
- Sort by
- Most recent
- Oldest
- Relevance
- Sender name: A - Z
- Sender name: Z - A
-

**Comment by hoangdat** [comment]
@Arsnael please help us on translating tmail: French only have 91% https://hosted.weblate.org/projects/linagora/teammail/

**Comment by Arsnael** [comment]
Done...

**Comment by hoangdat** [comment]
DONE in `v0.11.3-patch4-5`
