### ISSUE TITLE
[CNB] User cannot click X icon to close email if he click really fast

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#2559]
### ENV: 
- Device: IOS
- Browser: SAFARI / CHROME
- ENV: CNB prod

### 17- User cannot use enter to go to second rows

**Step:**
1, User access cnb
2, User login success
3, User click open one email
4, User Foward / reply
5, User click X icon immediately

**Actual:** 
- Save drafts toast message is displayed but system not redirect user to previous page

**Expected:**  
- Closed composer
- Saved drafts
- Redirect to previous page

https://github.com/linagora/tmail-flutter/assets/124866146/a20ac22e-3720-49e9-adee-f0ad1378818e

**Comment by dab246** [comment]
Same #2560
