### ISSUE TITLE
[CNB] User Foward email but cannot close it if inactive tab for 5 mins

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#2560]
### ENV: 
- Device: IOS
- Browser: SAFARI / CHROME
- ENV: CNB prod

### 18- User trying foward an email but cannot close it after inactive tab for 5 mins

**Step:**
1, User access cnb
2, User login success
3, User switch to home screen or other app for 5 mins
4, User back to app and click open email
5, User Foward / reply
6, User click X icon immediately

**Actual:** 
- Nothing happen
- Feeling loading and laggy

**Expected:**  
- Working smoothly

**Cannot do any action**

https://github.com/linagora/tmail-flutter/assets/124866146/a41ecdd8-0104-42b0-aa70-f9c9b85e98a1

**Comment by dab246** [comment]
Same #2603
