### ISSUE TITLE
User clean more than 1000 mail in Spam, Spam counter is updated (no empty action) but Thread View still have a lot of email

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#2564]
### Desc:
- Spam have than 1000 emails
- Context menu in MaiboxView -> Delete all Spam Mailbox
- Counter is updated well
- But the ThreadView still have 20 item
### DoD:
- [ ] Spam should be updated well in counter and thread view

**Comment by QuangHoang1210** [comment]
Passed on 0.11.3

**Spam**

https://github.com/linagora/tmail-flutter/assets/124866146/d8e71970-e2c9-446d-b659-a314d75bdb4e


**Trash**

https://github.com/linagora/tmail-flutter/assets/124866146/fe9a52a1-e8ae-4333-a723-b9ca8f87ead3
