### ISSUE TITLE
[WEB] [MOBILE] promote the app

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#2565]
GIVEN I am a user loading tmail web on mobile
THEN the app should prompt me to download the app
     and explain that the experience will be better
     
It embeds a link to the platform application store

I can still close it and use

@dab246 monday priority for CNB

Design to be provided by then

**Comment by DianaPotokina** [comment]
@Bobpodvalnyi Bob, please see this issue. Thanks

**Comment by hoangdat** [comment]
https://www.figma.com/file/XqLqMINlZw09BdEHI8yLb9/Teammail---1.1?type=design&node-id=1708-79121&mode=design

![Screenshot from 2024-02-05 13-40-24](https://github.com/linagora/tmail-flutter/assets/6928740/efd413c7-6300-4dfe-87ae-d574742b2a1a)

**Comment by DianaPotokina** [comment]
Dat, hello! what is it? ))-- 
Diana POTOKINA Chief of software development, Linagora Groupe, FranceGeneral director Linagora RUS, Russia, Vidnoe___________________________________________________+ 7 919 100 20 39 (Россия, WhatsApp)+ 33 643 90 33 06 (France)On February 6, 2024 2:28 AM, from ***@***.***
https://www.figma.com/file/XqLqMINlZw09BdEHI8yLb9/Teammail---1.1?type=design&node-id=1708-79121&mode=design
Screenshot.from.2024-02-05.13-40-24.png (view on web)

**Comment by hoangdat** [comment]
It is new design for suggestion for user to download Twake Mail in case user open app in safari (or any browser) in mobile device
