### ISSUE TITLE
[EPIC] Support web browser

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#257]

**Comment by chibenwa** [comment]
https://github.com/edwardinubuntu/flutter-web-dockerfile next step for WEB

Also I would like to use environment variable to provide the JMAP server URL.

If the environment variable is present then we should use it as the server URL and not add the "server URL" field. 

(I am not aware of a webmail asking for its server URL ;-) )

I have something like this in mind: https://stackoverflow.com/questions/63249638/how-to-use-env-in-flutter-web

Next next step is benches (gatling) to see how well the content is served and evaluate if we get a perf problem. Backend team will handle that. + Deploy TMail front docker container in our Helm charts.
