### ISSUE TITLE
[CNB] [Mobile] [WEBPC] Sometime I cannot save drafts --- displaying red toast "failed saved drafts" -- but sometime it saved draft with empty content

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#2572]
### ENV: 
- Device: IOS / WEB PC
- Browser: SAFARI / CHROME / Firefox
- ENV: CNB prod

### 26- Sometime I cannot save drafts --- displaying red toast "failed saved drafts" -- but sometime it saved draft with empty content

**Reproduce step 1:**
1, User access cnb
2, User login success
3, User click on composer
4, User click X icon

**Actual:** 
- Sometime displaying red toast "failed saved drafts" 
- Sometime it saved draft with empty content

**Expected:**  
- Not save draft if user didn't type any words in composer

-----------------------------
**Reproduce step 2:**
1, User access cnb
2, User login success
3, User click on Draft folder
4, User select one email in draft and remove all content in this email
5, User click X icon or click Saved draft

**Actual:** 
- Displaying red toast "failed saved drafts" 

**Expected:**  
- That email will be removed if empty 

https://github.com/linagora/tmail-flutter/assets/124866146/afc8b6da-c431-4e69-be65-4fb0e335e046

**Additional Information**

```
{
    "sessionState": "2c9f1b12-b35a-43e6-9af2-0106fb53a943",
    "methodResponses": [
        [
            "Email/set",
            {
                "accountId": "51e6371779b54390bf5970559c64c2725da1d3b8a3c548a97ddf98522822ca75",
                "oldState": "560dd910-c1ba-11ee-8a40-15ecabb6ca5b",
                "newState": "560dd910-c1ba-11ee-8a40-15ecabb6ca5b",
                "notCreated": {
                    "2fd64a30-c498-11ee-8b18-334f98175f7e": {
                        "type": "serverFail",
                        "description": "Exception occurred while saving bytearray"
                    }
                }
            },
            "c0"
        ]
    ]
}
```

**Comment by hoangdat** [comment]
- 20 Feb: please verify it again with latest version in tmail.linagora.com `v0.11.3-patch4-4`

**Comment by QuangHoang1210** [comment]
Still happen on 0.3.11 tmail.linagora.com

**Reproduce step:**
1, User open composer
2, User input nqnguyen@linagora.com  at To: field-> select
3, User input nqnguyen
4, User click X icon

**Actual**: 
Red toast error: Failed saved drafts .... and cannot save to drafts

**Expected**: 
Green toast: Saved successfully and can save to drafts same with behaviour when user click on Save Drafts icon

https://github.com/linagora/tmail-flutter/assets/124866146/72d07564-c73b-4888-9f34-2ed389fc2602


```
{
    "sessionState": "2c9f1b12-b35a-43e6-9af2-0106fb53a943",
    "methodResponses": [
        [
            "Email/set",
            {
                "accountId": "912618096e03fb03fe14293a97102272d4875bd9c3d80ad49de32c58bb4b28bd",
                "oldState": "63df4010-d015-11ee-a723-5927d17142a4",
                "newState": "63df4010-d015-11ee-a723-5927d17142a4",
                "notCreated": {
                    "2de15a40-d018-11ee-ac72-734cf2aa6069": {
                        "type": "invalidArguments",
                        "description": "List((/to(1)/email,List(JsonValidationError(List(Out of data at position 1 in 'nqnguyen'),List()))))"
                    }
                }
            },
            "c0"
        ]
    ]
}
```

**Comment by chibenwa** [comment]
Backend bug.

See https://github.com/linagora/james-project/issues/5075
