### ISSUE TITLE
[CNB] [All platform] Lost email when user move email to draft

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#2576]
### ENV: 
- Device: ANDROID / IOS
- Browser: All platform
- ENV: CNB PROD

### 28 - Lost email when user move email to draft

**Precondition:**
1, User go to inbox
2, User tap and hold to select one email
3, User move to Draft

**Actual:** 
- Toast move draft successfully but I didn't see that email in Draft folder.

**Expected:**  
- See email in drafts

**Noted:**  Moving to Other folder is normally

https://github.com/linagora/tmail-flutter/assets/124866146/63cf9475-ecd8-4c9e-9fc4-bdd87c121a22

**Comment by dab246** [comment]
@QuangHoang1210 According to the video, the moved email has a date time of `Jan 29` (`at 6 ​​seconds`). But in the `Drafts` mailbox, it is only loading to the element whose date time is `Sat` (`at 24 seconds`). So this new email is not seen, IMO, we need to load more older times to see it furthermore, I tested it again, and it is working fine (video below).


https://github.com/linagora/tmail-flutter/assets/80730648/dbeb0bae-3fbc-4b05-824d-920891dc03a9
