### ISSUE TITLE
[WEB] [MOBILE] Promoting Apps with Smart App Banners

### ISSUE THREAD

**Issue by nqhhdev** [linagora/tmail-flutter#2579]
### Decs:

- If the user continues to use Twake Mail on mobile web. Create a banner to promote Twake Mail app on the App Store from a website.

![Image](https://github.com/linagora/tmail-flutter/assets/99852347/2b41c5cf-5f88-4249-bcb1-ce30e11e8ce6)

### Doc:
- Apple: https://developer.apple.com/documentation/webkit/promoting_apps_with_smart_app_banners

**Comment by nqhhdev** [comment]
@hoangdat  @dab246

**Comment by chibenwa** [comment]
https://www.figma.com/file/XqLqMINlZw09BdEHI8yLb9/Teammail---1.1?type=design&node-id=1708-79121&mode=design

![Screenshot from 2024-02-05 13-40-24](https://github.com/linagora/tmail-flutter/assets/6928740/efd413c7-6300-4dfe-87ae-d574742b2a1a)

Design FYI
