### ISSUE TITLE
[Story] As a user, I want to view list of mailboxes and emails in browser with responsive 

### ISSUE THREAD

**Issue by dieptran88** [linagora/tmail-flutter#258]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC

* TODO: {link}

## Definition
- Given that I am Tmail user 
- I open Tmail web browser and input URL, then the log-in screen will be opened 
- I input my username and password to log-in.
- After log in to my account successfully, I can see the default view is Inbox mail list.
1.- On the right of screen, I can see:
   - My avatar that when I click on, I can see information: name and email address
2.- On the left of screen, I can see: 
   - A "Search folder" bar
   - The list of all mailboxes :
      - Default Mailboxes: Inbox, Draft, Sent, All mail, Trash, Spam, Template. These default mailboxes will not change.
      - My folders: Include button Create folder and Folders list created by me. These folders may be changed by the user.
      - When i add or remove a folder, I can see the mailboxes list updated instantly.
- The Storage information at the bottom of screen: [Used storage]/[Total]. This information is real-time updated
- When the list of mailboxes are too long, i can scroll up and down to see the full list.
- In each counted mailbox, i can see the counter for unseen message upto 999, when the number of unseen mails is over 999, the app will display 999+, and this counter is updated real-time.
- Counting rules:
   - Draft: Do not count
   - Trash: Do not count
   - Spam: Do not count
   - Templates: Do not count
   - Sent: Do not count
   - Created folder: Count unseen message
   - Inbox: Count unseen message
   - All mail: Count unseen message
3. On the right of screen, I can see the message list of the select mailbox, including:
- A search bar: Search in email at top of screen: This is search of all emailx
- Current folder name: Inbox
- Each row represents an email with information : Sender, Mail title, partial content, Date/time

**Email listing rules**

- The mail list is ordered automatically by latest date-time. This correspond to the Date field of the underlying mime message (sentAt) and defaults to the internal date (receivedAt) of the message.
- The mail list is devided by time frames: Today, Yesterday, This week, Last week, This month, Last month, This year
- The mail list is paginated with default number of items are defined. e.g 50 items 
- The mail list is updated real-time.
- If the email have an attachment, there will be an icon on the mail subject
- Each row will contain a star icon on the right: If the email is marked star, the star is in yellow color. If not, the star's default color is white.
- If an email is forwarded, there will be an forwarding icon.
- If an email is replied, there will be an reply icon.
- When I hover an email row, I can see icons " Mark as read" and "Delete" 
 4. I can see a floating button "Compose", when I click on, the composer will prompt at the bottom right of screen 

**UI requirement: The screen is responsive with different screen sizes.**

[Back to Summary](#summary)

## Design ticket

https://ci.linagora.com/linagora/lgs/design/-/issues/134

[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

**Comment by Kevinle2312** [comment]
Passed on the Production platform.
