### ISSUE TITLE
 When I click on chevron icon next to my email address, nothing happens 

### ISSUE THREAD

**Issue by dieptran88** [linagora/tmail-flutter#2581]
### Context
- Version 0.11.3 
- Android 

### Reproduction Steps
1. Log-in Tmail app on mobile 
2. Click Inbox 
3.  Click on chevron icon next to my avatar + email address => Nothing happens 
4. Click on Manage account  => Click on chevron icon => Nothing happens 

![Frame 179](https://github.com/linagora/tmail-flutter/assets/68209176/7ba59fcf-b35c-440e-838b-26307b6fb781)

### Expected result 

- On step 3, When I click chevron icon => It should redirect me to the Settings screen 
- On step 4, should remove chevron icon

**Comment by hoangdat** [comment]
removed. #2836
