### ISSUE TITLE
[Mobile] Apply correctly the new composer for mobile

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#2584]
### DoD:
- [ ] remove toolbox buttons (style, attachments, inline image) in keyboard header
- [ ] toolbox buttons (style, attachments, inline image) move to the app bar of composer
- [ ] update correct icon for toolbox buttons (style, attachments, inline image)

**Comment by dab246** [comment]
> * [x]  remove toolbox buttons (style, attachments, inline image) in keyboard header
> * [x]  update correct icon for toolbox buttons (style, attachments, inline image)

- Fixed at PR: https://github.com/linagora/tmail-flutter/pull/2795

> * [x]  toolbox buttons (style, attachments, inline image) move to the app bar of composer

- Fixed at PR: https://github.com/linagora/tmail-flutter/pull/2794
