### ISSUE TITLE
Cannot refresh the webmail

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#2587]
Upon some conditions I cannot refresh the webmail.

This button has no effect:

![Screenshot from 2024-02-06 17-54-18](https://github.com/linagora/tmail-flutter/assets/6928740/4c622f79-fca1-495d-90b8-b41415f6d301)

Plateform Prod: https://github.com/linagora/tmail-flutter/commits/v0.11.3-patch4/

I asked the customer to log out and log in again and everything was working, the missing emails were found.

**Comment by hoangdat** [comment]
hi, why your inbox was display so little while it showed (999+)?

**Comment by chibenwa** [comment]
Because of another bug eventually fixed :-P

**Comment by chibenwa** [comment]
And the answer was: because the IMAP pods where not executing the jmap logic under some circumstances the notification were not fire.
