### ISSUE TITLE
[Story] As a user, I want to log-in Tmail web app 

### ISSUE THREAD

**Issue by dieptran88** [linagora/tmail-flutter#259]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC

* TODO: {link}

## Definition

- Given that I am a Tmail user and I had an account 
- I open web browser and input Tmail URL
- I can see log-in screen is displayed 
- I can see 2 fields : User name/password and button Log-in
- I In put my credentials and click button Log-in, system will validate: 
   -  If the username or password is incorrect, there will be an error message
   -  If any field is blank, there will be an error message 
- If username and password are correct, I log-in successfully to Tmai web app. 
- UI requirement: The screen is responsive with different  screen sizes. 

[Back to Summary](#summary)

## Design ticket

https://ci.linagora.com/linagora/lgs/design/-/issues/130

[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

**Comment by Kevinle2312** [comment]
Failed on Production platform. No message appears when I input the wrong password. @hoangdat
