### ISSUE TITLE
Copy and paste rich text in composer leads to overlap

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#2591]
### Description

I copy and pasted text from an ODT document.

I noticed the styling makes no line break, leading to text overlap which is not beautiful.

![image](https://github.com/linagora/tmail-flutter/assets/6928740/f9ab2b05-f810-4ee2-b4d2-0fc9c317e507)

### Expected result

I expect no overlap.

### Current behavior

![Screenshot from 2024-02-08 22-20-11](https://github.com/linagora/tmail-flutter/assets/6928740/7300b651-33b0-4e37-8288-57427bef76da)

![Screenshot from 2024-02-08 22-19-59](https://github.com/linagora/tmail-flutter/assets/6928740/951bbd15-910d-4d6c-b629-e193a0171a99)

#### Reproduction Steps

[bug.eml.txt](https://github.com/linagora/tmail-flutter/files/14214995/bug.eml.txt)

### Context

tmail.linagora.com v0.11.3-patch4-v2

**Comment by chibenwa** [comment]
The display of the email generated by tmail in thunderbird is also fucked up

![image](https://github.com/linagora/tmail-flutter/assets/6928740/b20fa28c-a20f-4bcf-afa6-1b2515721a3d)

So do not change HTML viewing

However if I do the same operation in tb the email generated is actually correctly folded

![image](https://github.com/linagora/tmail-flutter/assets/6928740/9b26a34c-0dd0-440e-9df9-1e2c7f3c7b0b)

So please look in the direction of "copy and pasted text formated by other tools"

If need be I'd even agree to unformat text pasted from external stuff.

**Comment by dab246** [comment]
## Propose

- Change style of html text with property `line-height: 1px;` to `line-height: 100%;`

**Comment by dab246** [comment]
Only on Chrome

**Comment by tddang-linagora** [comment]
### Related issues
https://github.com/summernote/summernote/issues/3983
https://github.com/summernote/summernote/issues/3638

### Solution
Both of the above issues suggest changing the line height to 100% should be the fix. I will be using the suggested method in https://github.com/tneotia/html-editor-enhanced/issues/257 to implement it.
