### ISSUE TITLE
Mail to: invalid with several recipients

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#2596]
### Description

GIVEN I open an event with at least 2 other participants
WHEN I click on 'mail to attendees'
THEN The opened tmail composer is invalid

### Expected result

I expect tmail to open with the list of other attendees.

### Current behavior

https://github.com/linagora/tmail-flutter/assets/6928740/c50ee435-bd50-484a-a46f-1ca9aa95572f

### Context

Firefox, https://openpaas.linagora.com/calendar and https://tmail.linagora.com

### Additional information

The URL callend by openpaas

https://tmail.linagora.com/mailto/?uri=mailto:dphamhoang%40linagora.com%2Cthdtran%40linagora.com%2Cnqnguyen%40linagora.com%2Crcordier%40linagora.com%2Ctprudentova%40linagora.com%2Cdpotokina%40linagora.com%2Cctdo%40linagora.com%3Fsubject%3DPoint TMail

The coma separator between recipients is URL encoded.

### Acceptance criteria

The recipient split should support both coma AND URL encoded coma

**Comment by QuangHoang1210** [comment]
### Passed on firefox & chrome
Not Passed on Safari 

**Firefox**

https://github.com/linagora/tmail-flutter/assets/124866146/38b706ac-f869-4e4c-917e-dcd94143f258

**Chrome**

https://github.com/linagora/tmail-flutter/assets/124866146/add79a57-ca4b-48b8-9422-4f7db9a16b67

**Safari**

https://github.com/linagora/tmail-flutter/assets/124866146/998e77f6-5015-4499-9b62-b20f97d51671

<img width="1284" alt="Screenshot 2024-02-20 at 9 23 08 PM" src="https://github.com/linagora/tmail-flutter/assets/124866146/a7218ad5-61b4-471d-a666-db4982bd5fb3">

**Comment by dab246** [comment]
@QuangHoang1210  Are you successfully able to log in to Twake Mail on Safari?

**Comment by QuangHoang1210** [comment]
> @QuangHoang1210 Are you successfully able to log in to Twake Mail on Safari?

Yes I can login Twake Mail on Safari WEB PC @dab246

**Comment by QuangHoang1210** [comment]
already retest -- PASSED
