### ISSUE TITLE
Notifications for drafts on IOS?

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#2598]
### Description

A customer described received notifications for drafts using the IOS application.

Notes:
 - He described "not receiving notifications straight away". This is because the app will only resynchronise when receiving an email (Email Delivery) and might include drafts.
 
 I'm not having an IOS phone, not able to reproduce. A mission for @QuangHoang1210 
 
 Of course no notification for email in draft / sent mailbox shall be sent.

**Comment by chibenwa** [comment]
Cool

Please backport on patch4-x

**Comment by hoangdat** [comment]
- patch for front-end was deployed
- [ ] missing patch from back-end: `[FCM] Only set alert for the APN message upon EmailDelivery` (on 0.8.2)

**Comment by hoangdat** [comment]
- not work well with linagora (0.8.2)

**Comment by dab246** [comment]
On `v0.11.3-patch4-dev` branch and prod server, BE still returns `alert` of payload in push notification on iOS device when performing `mark as read`, `move` or some other email-related actions.  @hoangdat @quantranhong1999

**Comment by quantranhong1999** [comment]
> On v0.11.3-patch4-dev branch and prod server, BE still returns alert of payload in push notification on iOS device when performing mark as read, move or some other email-related actions. @hoangdat @quantranhong1999

Can you try to check if this is the issue for preprod env? (I do not have access to prod so I am not sure which tmail backend image is running - with the fix or not).

**Comment by hoangdat** [comment]
As I checked, `tmail@linagora` still use back-end image `chibenwa/tmail-backend:distributed-0.8.1-patch-cnb-16`, so it not include commit https://github.com/linagora/tmail-backend/commit/43c49615a06edb850fdd7d4b35fbd05873dfc6af. Please check it again @chibenwa.

@dab246 please verify one more time new iOS app with preprod. Thanks
