### ISSUE TITLE
Notification flood!

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#2599]
### Description

Given I have 13 new emails unseen in my mailbox
When I receive notification 
Then I receive 13 notification
And the notifications are eventually folded

### Expected result

I should receive a single notification saying I have 13 email and allow me to see each mail detail

### Actual result

https://github.com/linagora/tmail-flutter/assets/6928740/b0f68a43-c883-455c-896d-18ac388cae01

### Platform

Android

But apparently that is the same for IOS

**Comment by hoangdat** [comment]
We still not understand the expectation. 
One notification for 13 email details, then how to click on notification to open email? 
It is really common behavior?

Cc @QuangHoang1210 please help us verify the notification for this case of Outlook, Gmail

**Comment by QuangHoang1210** [comment]
- If user have 13 new emails then system will displayed 13 notification = 13 new emails.

**Behaviours:**
A- On Android
Receive new 10 emails -> Notification Center is displayed 10 emails in 1 noti
==> User can click to expand it to view list of new email 
===> User can click each email to go to email details in Twake Mail app

![IMG_4097](https://github.com/linagora/tmail-flutter/assets/124866146/f7402587-8325-4761-ab67-417f9ff582bf)

B- On IOS
Receive new 10 emails -> Notification Center is displayed 10 emails belong to 10 notifications separately
==> User can click to expand it to view list of new email 
===> User can click each email to go to email details in Twake Mail app



-> Twake mail behaviour same with Samsung email / Outlook / Gmail on both IOS and Android


@chibenwa  @hoangdat  @dab246

**Comment by chibenwa** [comment]
Please start grouping messages from 3 new messages.

Given I have 10 new mail at the same time my phone should ring once.

**Comment by hoangdat** [comment]
How to display folded notification?

**Comment by QuangHoang1210** [comment]
### Define notification AC:

**### A- Receiving multiple emails on ANDROID** 

**1- Same time**: Time receiving email : 4:05 PM for example
```
GIVEN User A,B,C are Tmail users
AND C using Android device
WHEN A and B sent an email to C at 4:05 PM
THEN C Android device receive 1 notification sound
AND 2 emails will be collapse in one on Notification Center
AND C can click on arrow to expand separated emails short description
```

**2- Different time receiving email : 4:05 PM - 1 email AND 4:06 - 1 email**
```
GIVEN User A,B,C are Tmail users
AND C using Android device
WHEN A sent an email to C at 4:05 PM
AND B sent an email to C at 4:06 PM
THEN C Android device receive 2 notification sound
AND 2 emails will be separately displayed on Notification Center
```

### **B- Receiving multiple emails in the same time on IOS**
**1- Same time**
```
GIVEN User A,B,C are Tmail users
AND C using IOS device
WHEN A and B sent an email to C at 4:05 PM
THEN C IOS device receive 2 notification sound
AND 2 emails will be separated displaying on Notification Center
```

**2- Different time**
```
GIVEN User A,B,C are Tmail users
AND C using IOS device
WHEN A sent an email to C at 4:05 PM
AND B sent an email to C at 4:06 PM
THEN C IOS device receive 2 notification sound
AND 2 emails will be separately displayed on Notification Center
```

**Comment by chibenwa** [comment]
HELLO Reported again by a customer!

**Comment by hoangdat** [comment]
> HELLO Reported again by a customer!
> 
> 

But what is his expectation?

**Comment by hoangdat** [comment]
> Well like me: not have my phone ring for 10 minutes when I wake up in the morning!
> 
>

You turned off the phone at night, then you turn it on in the next morning, and you have ton of notifications?

**Comment by chibenwa** [comment]
Precisely. Phone rings for 10 minutes without a break

**Comment by chibenwa** [comment]
Related but making notification settings easier to access would make it easier for users to navigate this,

https://github.com/linagora/tmail-flutter/issues/1387

**Comment by hoangdat** [comment]
still have flood from current version @chibenwa ?

**Comment by chibenwa** [comment]
Looks better overall to me yes
