### ISSUE TITLE
[Basic] Read mails

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#26]
Basic requirements to read email with JMAP protocol: 

- [x] Listing mailbox, thread, emails, ...
- [x] Receiving mail,
- [x] Synchronize, refresh, 
- [ ] receiving push notification
- [x] Search email
- [x] Filter email

**Comment by chibenwa** [comment]
`thread` -> no plan support IMO

**Comment by chibenwa** [comment]
`Receiving mail,` -> what do you mean?

**Comment by chibenwa** [comment]
`receiving push notification` -> We said we need a push mechanism, (websocket not enough) it's complex, thus maybe we can qualify this as low priority and remove it from imediate scope.

What do you think?

**Comment by hoangdat** [comment]
No, It is Epic, I create to brainstorm the functions for TMail, We should prioritize it later :). You should to use Zenhub to more visually the workflow for that.

**Comment by chibenwa** [comment]
Yes yes for sure.

I just give you my thoughts ;-)
