### ISSUE TITLE
Fun fact: I did not knew that TMail was a video player

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#2600]
https://github.com/linagora/tmail-flutter/assets/6928740/4dbde71b-6f10-4056-ae0f-fc99b88d29d0

**Comment by hoangdat** [comment]
as video, you did not drop on droppable area, so browser open your video in other tab. it is a common behavior. WDYT?

**Comment by hoangdat** [comment]
- [ ] App should prevent user drop outside drop zone
