### ISSUE TITLE
When I send a mail, sometimes the sending button is loading infinitely and the mail is not sent

### ISSUE THREAD

**Issue by LNGGlago** [linagora/tmail-flutter#2603]
### Description

When I send a mail, sometimes the sending button is loading infinitely and the mail is not sent

### Expected result

The mail is sent and the page of the mail closes

### Current behavior

The "Send" button keeps rotating and the mail is never sent

#### Reproduction Steps

It is random

### Acceptance criteria

The list of acceptance criteria (defined in the corresponding User Story or coming from your functional knowledge of the product)
These acceptance criteria must be met by the corrective implementation done by the developers.

### Context

Chromium, Ubuntu

### Additional information

It happens once for ten mails on my side

I add some logs from my console, but it doesn't seem to be relevant.

I guess the issue is on server side

![image](https://github.com/linagora/tmail-flutter/assets/151856136/ded72ef1-ec81-414b-b6c1-439d2a932f42)

**Comment by chibenwa** [comment]
![image](https://github.com/linagora/tmail-flutter/assets/6928740/b4fbd20c-624e-4ea8-ad3f-6d60e096447c)

Happens all the time when I forward. Reply and send works fine.

**Comment by dab246** [comment]
> ![image](https://private-user-images.githubusercontent.com/6928740/305043087-b4fbd20c-624e-4ea8-ad3f-6d60e096447c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwNTQzMDIsIm5iZiI6MTcwODA1NDAwMiwicGF0aCI6Ii82OTI4NzQwLzMwNTA0MzA4Ny1iNGZiZDIwYy02MjRlLTRlYTgtYWQzZi02ZDYwZTA5NjQ0N2MucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTZUMDMyNjQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODBmNjJlMTgwZGI1OTFiYjQ0Y2JmZDhiYjQwMzRjZTNhMmNlMmU1MmM2MGFiNGE3ZDJkMDkyYjUyYTg1MzhmNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.6i6OqSlCFMXaqRjMAlDnJHzBp2agqLZm2F78rkbw60o)
> 
> Happens all the time when I forward. Reply and send works fine.

@chibenwa Can you have a demo video to help us? We'd like to be more clear about the order of operations you performed to cause this error to appear. Thank you very much.

**Comment by dab246** [comment]
> > ![image](https://private-user-images.githubusercontent.com/6928740/305043087-b4fbd20c-624e-4ea8-ad3f-6d60e096447c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwNTQzMDIsIm5iZiI6MTcwODA1NDAwMiwicGF0aCI6Ii82OTI4NzQwLzMwNTA0MzA4Ny1iNGZiZDIwYy02MjRlLTRlYTgtYWQzZi02ZDYwZTA5NjQ0N2MucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTZUMDMyNjQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODBmNjJlMTgwZGI1OTFiYjQ0Y2JmZDhiYjQwMzRjZTNhMmNlMmU1MmM2MGFiNGE3ZDJkMDkyYjUyYTg1MzhmNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.6i6OqSlCFMXaqRjMAlDnJHzBp2agqLZm2F78rkbw60o)
> > Happens all the time when I forward. Reply and send works fine.
> 
> @chibenwa Can you have a demo video to help us? We'd like to be more clear about the order of operations you performed to cause this error to appear. Thank you very much.

Srr, I reproduced it.
