### ISSUE TITLE
Mail sent from iphone: missing attachments

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#2610]
![Screenshot from 2024-02-17 15-07-38](https://github.com/linagora/tmail-flutter/assets/6928740/c54d0fc9-8705-4b86-8c90-b9bc95324886)

![Screenshot from 2024-02-17 15-07-58](https://github.com/linagora/tmail-flutter/assets/6928740/a01b4e2e-a391-4cef-99e4-e5d15cc8b38c)

![Screenshot from 2024-02-17 15-08-47](https://github.com/linagora/tmail-flutter/assets/6928740/bf9898e8-0479-427c-8567-b290fd7ff50c)

**Comment by QuangHoang1210** [comment]
passed on 0.11.3

<img width="1260" alt="Screenshot 2024-02-25 at 11 11 29 PM" src="https://github.com/linagora/tmail-flutter/assets/124866146/4275719a-a0b0-4422-85a9-da7160c6df48">
