### ISSUE TITLE
Only request FULL Email/get one-by-one

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#2611]
### Desc:
- Request too much `ids` in Email/get at FULL level
- Back-end have limitation for this -> error 

### DoD:
- [ ] GET for maximum 5 latest email in `Email/changes`
- [ ] execute `Email/get` at FULL level one-by-one
- [ ] ADR

**Comment by chibenwa** [comment]
![Screenshot from 2024-02-17 13-18-36](https://github.com/linagora/tmail-flutter/assets/6928740/3c128370-a448-452d-aa5d-47c0f51fb0fb)
