### ISSUE TITLE
Forwards: warn for forwards to other domains

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#2613]
# Summary

GIVEN alice@mydomain.com redirects her mails to alice@evil.com
THEN Alice is prompted with `WARNING: you are redirecting emails to another domain. This could be a secuirty threat or considered illegal data extraction. Do you want to proceed? (Yes | No)`
AND Alice seens on the forward page a warning: `you are redirecting emails to another domain. This could be a secuirty threat or considered illegal data extraction.`

@dieptran88 please provide a design

**Comment by dieptran88** [comment]
![Group 1321315323](https://github.com/linagora/tmail-flutter/assets/68209176/33f934ff-2899-4456-9246-2b42afa8c39f)

**Option 1**:
![Group 1321315324](https://github.com/linagora/tmail-flutter/assets/68209176/54351d8d-20f1-4d69-afaf-24fac1afd83b)

**Option 2:**
![Group 1321315325 (1)](https://github.com/linagora/tmail-flutter/assets/68209176/5c76b9db-75bb-47de-90b6-295b9232ae1b)

**Comment by hoangdat** [comment]
DoD:
- [ ] popup warning whenever user try to add external domain
- [ ] banner warning (same style with vacation/quota/....) 
- [ ] tooltip warning icon beside external email also

**Comment by dieptran88** [comment]
> DoD:
> 
> * [ ]  popup warning whenever user try to add external domain
> * [ ]  banner warning (same style with vacation/quota/....)
> * [ ]  tooltip warning icon beside external email also

Mockups updated
