### ISSUE TITLE
Setting to always require read receipts

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#2615]
### Description

In profiles have a checkbox to `Always send read receipts`

When checked, the composer selects the `Ask for read receipt` option by default, which could be disabled if wanted.

@dieptran88 please provide a design for this.

### Technically

Use JMAP option storage in TMail backend CF https://github.com/linagora/tmail-backend/issues/630

**Comment by hoangdat** [comment]
First design: `Email read recipient`
<img width="734" alt="image" src="https://github.com/linagora/tmail-flutter/assets/6462404/e9aa5d9d-0ccf-4e97-ae1c-5c156f0e8335">

**Comment by dieptran88** [comment]
**Proposal**: 

![Group 1321315322](https://github.com/linagora/tmail-flutter/assets/68209176/1d4b3cdf-5ef8-4ed0-aee9-1bdd436e9283)


**Our current design:**
![image](https://github.com/linagora/tmail-flutter/assets/68209176/19374c7b-57e8-4bf1-991b-5de15ebe3a99)

https://www.figma.com/file/rRVxJpCu1G22D0jqyvK7I9/TeamMail?type=design&node-id=5199-233022&mode=design&t=12ggiN953vraYps1-0

**Comment by chibenwa** [comment]
Work on this is expected by the customer for a delivery in ~2 weeks.

**Comment by hoangdat** [comment]
## Ref

### Docs: https://github.com/linagora/tmail-backend/blob/9af6a6fd5f4b3a90285bb3e702b2de1d74866b3e/docs/modules/ROOT/pages/tmail-backend/jmap-extensions/jmapSettings.adoc

### Contract: https://github.com/linagora/tmail-backend/blob/master/tmail-backend/jmap/extensions/src/test/scala/com/linagora/tmail/james/jmap/settings/JmapSettingsRepositoryContract.scala#L34

**Comment by tddang-linagora** [comment]
Progress:
- [ ] #2677
- [ ] #2678 
- [ ] #2679 
- [ ] #2680 
- [ ] #2681 
- [ ] #2682 
- [ ] #2683
