### ISSUE TITLE
[Mobile WEB] Download promp is missing content when user access Twake Mail

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#2622]
### ENV: 
- Device: IOS / Android
- Browser: SAFARI / CHROME / Firefox
- ENV: canary & prod tmail.linagora.com

### Weird white popup is displayed when user access Twake Mail

**Step:**
1, User access canary url

**Actual:** Weird white popup displayed
**Expected:**  No white popup 

https://github.com/linagora/tmail-flutter/assets/124866146/18931cfe-1f4d-4c9d-badf-77429e11ddd3

**Log**

![Image](https://github.com/linagora/tmail-flutter/assets/124866146/957130cf-4725-4126-be96-96639c12aab3)

![Image](https://github.com/linagora/tmail-flutter/assets/124866146/614aaab2-8fd2-454f-a399-523d7250bd11)

**Comment by hoangdat** [comment]
still in #2565
