### ISSUE TITLE
[WEBPC] [Firefox/Chrome/Safari] It's blink blink when user click on To: field when he trying reply an email with long receipents

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#2623]
### ENV: 
- Device: Laptop
- Browser: SAFARI / CHROME / Firefox
- ENV: canary & prod tmail.linagora.com

### Blink blink and out focus when user immediately click on To: field at the first time when the composer is displaying

**Step:**
1, User A send an email to User B
2, User B reply/foward that email  
3, User click on field To: or CC: immediately when composer is displaying

**Actual:** 
Blink blink - not focus on To: or CC: field when clicking
**Expected:**  
Not blink blink -> Should focus cursor on To: or CC: field

**Long Receipient**

https://github.com/linagora/tmail-flutter/assets/124866146/75e4a393-1913-495e-90f7-5066dc9e5fbb

**Short Receipients**

https://github.com/linagora/tmail-flutter/assets/124866146/b85cf133-0901-4bef-979a-0c84e021eb05

**Comment by dab246** [comment]
@QuangHoang1210 Can we compare it with TB or Gmail?
