### ISSUE TITLE
Display glitch

### ISSUE THREAD

**Issue by Arsnael** [linagora/tmail-flutter#2629]
From https://github.com/linagora/tmail-backend/issues/931 reported by @chibenwa 

CNB prod: linagora/tmail-web:v0.11.3-patch4-3

![306655246-8322da02-1fd9-4149-8fb6-1c5499a27b93](https://github.com/linagora/tmail-flutter/assets/9005025/38fb7f3a-fc87-40d9-be89-6c2a37c90645)

The guy used chome. Waiting for OS and screen settings.

I tried on my side:

![306667816-cf4893b7-333a-484c-8877-24631a6e25d7](https://github.com/linagora/tmail-flutter/assets/9005025/adeb8f52-9301-463d-a668-2bf2ddb5acf7)

Was ok on chromium.

![306659225-794f165c-9c33-447c-ab54-0bc3256d9997](https://github.com/linagora/tmail-flutter/assets/9005025/065af917-a4a6-4e7f-94f2-949db280bc69)

Truncated text.

Set "french" and activate vacation responder.

Chromium on ubuntu

@QuangHoang1210 please have a look.

**Comment by QuangHoang1210** [comment]
Working normal on my side 

<img width="1512" alt="Screenshot 2024-02-22 at 11 48 43 PM" src="https://github.com/linagora/tmail-flutter/assets/124866146/8d46f3b6-e3c4-4b0f-a146-e842df5786e3">

**Comment by chibenwa** [comment]
Have you tried with a chrome on windows?

**Comment by QuangHoang1210** [comment]
@chibenwa I have tried both OS and Windows

**Comment by chibenwa** [comment]
Weird then...

**Comment by chibenwa** [comment]
chrome on tablet maybe?

**Comment by hoangdat** [comment]
We still not reproduce the same as user. But we found that `version name` also truncated. 

![306841179-38fb7f3a-fc87-40d9-be89-6c2a37c90645](https://github.com/linagora/tmail-flutter/assets/6462404/f41c77a6-d4cd-423a-9621-dd3f397138f1)

So, please ask the user on the screen solution and the platform which user use.

**Comment by chibenwa** [comment]
> So, please ask the user on the screen solution and the platform which user use.

Already...

**Comment by hoangdat** [comment]
Fixed truncated, and move down the app version.
