### ISSUE TITLE
I can not paste text in the composer

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#263]
### Description

When I do a long tap in the composer nothing happens

### Expected result

In a text input I would expect being able to paste stuff

**Comment by hoangdat** [comment]
hi @chibenwa, from now, we support the app in a large range of clients: Android, iOS, Browser. Please help us more details in the environment you have the issue.

**Comment by chibenwa** [comment]
Android 11, One UI 3.1 kernel 4.4.177 Knox 3.7
