### ISSUE TITLE
Replies does not handle non ascii chars well

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#264]
### Description

Given a mail with special chars in his topic,

When I click reply

Then the special chars are not well caried over in the text input

### Expected result

I should have the exact same utf8 chả in the subject composer

### Additional information

Please ensure we operate on utf8 for all string charsets

![Screenshot_20220215-212230_Team Mail](https://user-images.githubusercontent.com/6928740/154086469-b843af46-bd8c-441a-8fb4-ef7a5b1adda5.jpg)

![Screenshot_20220215-212224_Team Mail](https://user-images.githubusercontent.com/6928740/154086478-6d08b09d-e314-417c-ad72-cda039c8b4ae.jpg)

**Comment by chibenwa** [comment]
This happens specifically on the subject fiwld

![Screenshot_20220216-215806_Team Mail](https://user-images.githubusercontent.com/6928740/154291983-8d0f1eca-4ff6-4199-b81c-1210c1648cfd.jpg)

**Comment by chibenwa** [comment]
(Note typing is enough, no need reply to...)

**Comment by dab246** [comment]
I cannot reproduce this error. Maybe this bug has been fixed in the current code. Please check again for me. @chibenwa

**Comment by chibenwa** [comment]
Looks like this is fixed yes!
