### ISSUE TITLE
[IOS] [SAFARI] Still having cursor when user open From drop downlist to select signature

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#2640]
### ENV: 
- Device: Mobile IOS
- Browser:  Safari
- ENV: tmail linagora 0.11.3

### Still have cursor when user open From drop down list to select signature

**Step:**
1, User click on composer
2, User tap on body to write email
3, User tap on From to select signature

**Actual:** 
- Dropdown list displayed but cursor still have
- User can typing

**Expected:**  
Don't have cursor when open from list

**Video*

https://github.com/linagora/tmail-flutter/assets/124866146/a5c85fee-23ff-4913-bae0-81b39c72656a

**Comment by hoangdat** [comment]
will be resolved after sprint 24
