### ISSUE TITLE
[IOS/ANDROID] [APP] Weird attachment displaying in composer

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#2641]
### ENV: 
- Device: Mobile IOS/ANDORID APPLICATION 
- ENV: tmail linagora 0.11.3

### Weird attachment displaying in composer application IOS

**Step:**
1, User click on composer
2, User tap on attachment
3, User select attachment

**Actual:** 
- Weird displaying attachment 

**Expected:**  
- Displayed attachment and have expand button

**Video*

**IOS APP**
https://github.com/linagora/tmail-flutter/assets/124866146/a6d4e70e-ad18-495f-a886-b861a68058af

**ANDROID APP**

![Image](https://github.com/linagora/tmail-flutter/assets/124866146/83a8f7bb-b48e-41f1-845d-c142a63be052)

**Comment by hoangdat** [comment]
will be resolved after sprint 24
