### ISSUE TITLE
WARN when sending large Email

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#2644]
### Description

If I attached more that 10MB of files in the composer, display the following warning in yellow:

```
Votre message dépasse la taille généralement acceptée pour un email. 
Si vous confirmez l'envoi il y a un risque que le mail soit rejeté par le système de votre interlocuteur.
```

Which can translate in english:

```
Your message is larger than the size generally accepted by third party email systems.
If you confirm sending this mail, there is a risk that it gets rejected by your recipient system.
```

Cc @pvi-github 

@dieptran88  please provide a design

THis, is a priority

**Comment by hoangdat** [comment]
Some cases we can attach files
- Drag n Drop
- Attach in button

**Comment by dieptran88** [comment]
![Group 1321315331](https://github.com/linagora/tmail-flutter/assets/68209176/860fb8f3-fbfd-4123-99d3-2aa3b0f601f5)
