### ISSUE TITLE
Select all VS select

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#2646]
### Description

Users are confused that select all do only select visible messages 

Proposition: `Select all` -> Select all messages of this page`

**Comment by hoangdat** [comment]
- [ ] constrant maxWidth and add tooltip

**Comment by chibenwa** [comment]
BTW `Select All` - as in all - all is a grouped action even in gmail

I click select all -> only current page is selected

I click -> select really all messages

Then the mails are all selected

I am prompted for less actions

And I need to confirm I want to do this mass action.

![Screenshot from 2024-04-24 16-57-29](https://github.com/linagora/tmail-flutter/assets/6928740/e7e4b730-d7f4-499b-a23b-b34085510248)

![Screenshot from 2024-04-24 16-57-42](https://github.com/linagora/tmail-flutter/assets/6928740/0ddb437
2-257a-4a8e-9a68-0b7f5b0ca44b)

![Screenshot from 2024-04-24 16-57-50](https://github.com/linagora/tmail-flutter/assets/6928740/99c1d450-d1a3-4b04-840a-7ab1d75446da)

If required to do `Select all` I would rather work on mass actions on folders:

![Screenshot from 2024-04-24 17-05-52](https://github.com/linagora/tmail-flutter/assets/6928740/afd4e412-6da3-405f-8df1-7fcbace87697)

(user confirmation needed before any of these actions, as in GMail - if they do it it is that there is a VERY good reason!)

**Comment by dab246** [comment]
## Propose (Only apply for web)

### For UI - UX

1. When select all inside opening mailbox:

- If mailbox has contain more `20 emails` then show `banner` on top email list view with message `All 20 mails on this page are selected. Select all 100  emails in mailbox`.
  
    
<img width="1165" alt="Screenshot 2024-04-25 at 10 12 00" src="https://github.com/linagora/tmail-flutter/assets/80730648/9551c2e8-a180-459a-93ab-4b2872e9a55d">


- If user click `Select all 100  emails in mailbox` label then:
    -  All emails in mailbox are selected
    -  `banner` is displayed with message `All 100 emails in mailbox are selected. Clear selection` 
    - `More action` button displayed

and when the user performs one of the actions (`mark as read`, `move to`, ...), a confirm dialog will appear
    
<img width="509" alt="Screenshot 2024-04-25 at 10 27 46" src="https://github.com/linagora/tmail-flutter/assets/80730648/28495caa-71a8-435c-a1fc-592f2ef37664">

- Else perform actions as soon as the user clicks

- User click `More action` then show popup menu with actions: `Mark all as read`, `Mark all as unread`, `Move all`, `Delete all`


2. When select all inside searching emails:

- Do the same as mailbox but do not display the total number of emails

<img width="1165" alt="Screenshot 2024-04-25 at 10 39 57" src="https://github.com/linagora/tmail-flutter/assets/80730648/2a21ebab-a1a4-4145-ba66-83f8bf6bd597">

<img width="1165" alt="Screenshot 2024-04-25 at 10 40 02" src="https://github.com/linagora/tmail-flutter/assets/80730648/9003ce6f-4ea2-4c1d-93c7-8eb530395d49">

### JMAP Request

1. Mark all as read

**Comment by dab246** [comment]
### Technical

1. For `Mark as all read & unread`

- Run the following 2 `jmap request` loops with `limit=30` until no more parts are found in `Email/query`, then stop.

- Step 1: Make jmap request nested `Email/Query` & `Email/get` to get a list of emails. Get only 2 properties `id` & `receivedAt` in `Email/get`

```json
{
    "using": [
        "urn:ietf:params:jmap:core",
        "urn:ietf:params:jmap:mail",
        "urn:apache:james:params:jmap:mail:shares"
    ],
    "methodCalls": [
        [
            "Email/query",
            {
                "accountId": "{{accountId}}",
                "filter": {
                    "inMailbox": "{{mailboxId}}",
                    "notKeyword": "seen"
                },
                "sort": [
                    {
                        "isAscending": false,
                        "property": "receivedAt"
                    }
                ],
                "limit": 30
            },
            "c0"
        ],
        [
            "Email/get",
            {
                "accountId": "{{accountId}}",
                "#ids": {
                    "resultOf": "c0",
                    "name": "Email/query",
                    "path": "ids/*"
                },
                "properties": [
                    "id",
                    "receivedAt"
                ]
            },
            "c1"
        ]
    ]
}
```

- Step 2: Make a jmap request `Email/set` to update the `keywords` property for each email

```json
{
  "using": [
    "urn:ietf:params:jmap:core",
    "urn:ietf:params:jmap:mail"
  ],
  "methodCalls": [
    [
      "Email/set",
      {
        "accountId": "{{accountId}}",
        "update": {
          "0a674840-0c84-11ec-b57c-2fef1ee78d9e": {
            "keywords/$seen": true
          },
          "dfb1d5a0-15f4-11ec-a759-2fef1ee78d9e": {
            "keywords/$seen": true
          }
        }
      },
      "c0"
    ]
  ]
}
```

2. For `Move emails` & `Delete emails`

- Do it the same way as above

@chibenwa  WDYT about implementing such a jmap request for `select all emails`. Is it optimized for performance? I also thought of a solution using `jmap request nested` between `Email/query`, `Email/get` and `Email/set`. But I can't find a way to get the result ``of `Email/query`

```
"update": {
          "0a674840-0c84-11ec-b57c-2fef1ee78d9e": {
            "keywords/$seen": true
          },
          "dfb1d5a0-15f4-11ec-a759-2fef1ee78d9e": {
            "keywords/$seen": true
          }
        }
```

**Comment by chibenwa** [comment]
>  Delete all emails permanently

Shall be `move to trash` IMO

**Comment by chibenwa** [comment]
> @chibenwa WDYT about implementing such a jmap request for select all emails.

Should be OK for now
