### ISSUE TITLE
Deleted email do not disappear?

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#2647]
### Description

```
MAIL DELETION BUG ON THE TWAKE MAIL APPLICATION ON ANDRIOD (SAMSUNG s9) MAILS ARE NOT DELETED THEY REMAIN ON THE INBOX
```

Please @QuangHoang1210 investigate...

**Comment by QuangHoang1210** [comment]
Working well on my XIAO MI and SAMSUNG GALAXY A51 android 13
-- I've tried with browser / web mobile also

https://github.com/linagora/tmail-flutter/assets/124866146/57ece2f1-8047-408b-aac3-8230f2c18f8e

But I'll take a look for more details
