### ISSUE TITLE
1GB webmail consumption

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#2665]
### Description

![image](https://github.com/linagora/tmail-flutter/assets/6928740/7cf51356-9f83-4fda-a95f-0577a79ce2cb)

Please investigate

**Comment by hoangdat** [comment]
- [ ] release fixed version in canary
- [ ] monitor in one week: memory consumption (screenshot memory every day: at the beginning time - ending time of working day)

**Comment by hoangdat** [comment]
Hi @chibenwa can you share some observation in your browser about memory consumption or memory leak?

**Comment by chibenwa** [comment]
155MB as off today.
This morning I was at 255mb
IMO still small leaks here and there but I do not think this is the complete showstopper it was.
I encourage the teram to adopt a proactive attitude towards fixing and detecting those leaks.

**Comment by hoangdat** [comment]
close this ticket and will add specific ticket for every sprint to detect more and verify no regression in memory leak
