### ISSUE TITLE
Handle parser differencial between front and back

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#2667]
### Description

![Screenshot from 2024-02-29 12-20-25](https://github.com/linagora/tmail-flutter/assets/6928740/988c176f-f718-4549-bbe8-00d1563dc049)

Will lead to

![image](https://github.com/linagora/tmail-flutter/assets/6928740/5c13085b-f61c-48ec-b48f-acc66b38e933)

Because james complains a bit

```
[
            "Email/set",
            {
                "accountId": "51e6371779b54390bf5970559c64c2725da1d3b8a3c548a97ddf98522822ca75",
                "oldState": "13578090-d6f4-11ee-957f-054ab4f0a2dc",
                "newState": "13578090-d6f4-11ee-957f-054ab4f0a2dc",
                "notCreated": {
                    "8b604310-d6f4-11ee-9e21-2b432003de82": {
                        "type": "invalidArguments",
                        "description": "List((/to(0)/email,List(JsonValidationError(List(Domain name cannot begin or end with a hyphen \"-\" at position 18 in 'server-dev@-james.apache.org'),List()))))"
                    }
                }
            },
            "c0"
        ],
```

## Expactation

If sending the mail fails for ANY REASON please reopen the composer

Even better to should the hu

**Comment by hoangdat** [comment]
### Current issue:
Some failed in closing composer:
 - 🔥 Save and close: save draft failed -> lost email (`1`)
 - 🔥 Send: send failed -> lost email (`2`)
 - ✅ Expand View: No issue found (Mem cache)
 - ✅ Minimize View: No issue found (Mem cache)

### Solution:
- Keep composer available until `1` or `2` completed
- Show dialog of execution like `Thunderbird`

![Image](https://github.com/linagora/tmail-flutter/assets/6462404/161770d6-2ddc-4f1c-ba41-a0099fc1273c)

**Comment by hoangdat** [comment]
@chibenwa @dieptran88 please review solution.

**Comment by dieptran88** [comment]
Mockups:
