### ISSUE TITLE
java.lang.IllegalArgumentException: List((/to(0)/email,List(JsonValidationError(List(Out of data at position 1 in ''),List()))))

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#2669]
### Description

The log line `java.lang.IllegalArgumentException: List((/to(0)/email,List(JsonValidationError(List(Out of data at position 1 in ''),List()))))` is quite common.

THis happens when Twake Mail submits an empty string for recipients.

I suggest the front filter out empty strings before submitting to the JMAP server in `to`, `cc`, `bcc` fields.

**Comment by hoangdat** [comment]
We did it. I can reproduce this case, you can have more log? which API have this issue?

<img width="1138" alt="image" src="https://github.com/linagora/tmail-flutter/assets/6462404/e59686b4-fb9c-41df-a220-055f9d36da77">

**Comment by chibenwa** [comment]
There are apparently still some cases this happens. Maybe upon saving draft?

**Comment by hoangdat** [comment]
for the case of draft, what is the best for user? it is weird to force user input email address in case of draft

**Comment by chibenwa** [comment]
Addressed with invalid address fixes in drafts coming from backend team.
