### ISSUE TITLE
Sometime signature disapear

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#2671]
### Description

Reported by gael lago

```
Call for a signature problem that appears randomly when writing an email

I confirm, the signature appears/disappears, it's a display problem.

It doesn't seem like much, but you never know if the signature is added or not. It's a UX problem which also prevents me from working well on the email tool, priority medium
```

Please @QuangHoang1210 have a look for this...

**Comment by QuangHoang1210** [comment]
@chibenwa Yes yes. I have found this issue from 3 March -  but on mobile <IOS and ANDROID> [0.11.3-patch4-6]
FYI @dab246 @hoangdat already working on this issue

Step:
1- User open composer
2- User typing long email <can user Enter to go second line>
3- User attach one image

**Actual**: When email body long enough then click to expand Signature -> A part of it will be cut off
**Expected**: No cut off signature when expand

https://github.com/linagora/tmail-flutter/assets/124866146/25580177-ebf7-482b-9697-51da297e69b8

**Comment by hoangdat** [comment]
always show signature in mobile
