### ISSUE TITLE
Blue bar: cannot copy link, cannot copy text, cannot work with recipients.

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#2684]
### Description

![image](https://github.com/linagora/tmail-flutter/assets/6928740/f426804c-2cc8-4fea-a7e6-cb02cad4939c)

I want to be able to copy the link from the bluebar

Can't select and copy and paste any field.

Also it would be very nice to have a email ship for every attentee mentionned on the event

**Comment by hoangdat** [comment]
### DoD:
- [ ] selectable in blue bar
- [ ] button `Mail to attendees` -> open composer with `to: all attendees`
