### ISSUE TITLE
Email/get full with 0 ids

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#2691]
![Screenshot from 2024-03-06 21-35-11](https://github.com/linagora/tmail-flutter/assets/6928740/f168ff33-a6a1-45c7-bb83-1758e1f0da28)

Calling the server to get 0 ids...

Maybe it is not needed?

Offline mode upon push notifications?

**Comment by hoangdat** [comment]
@chibenwa , you still see this kind of log more and more?

We try to follow all the points we get FULL level in code base:
- Push notification for offline mode
- And Open email
but not see any special things. 

This log for `ids` or `reference `#ids`?

Btw, `ID` always have precheck,
```
class Id with EquatableMixin {
  final RegExp _idCharacterConstraint = RegExp(r'^[a-zA-Z0-9]+[a-zA-Z0-9-_]*$');
  final String value;
  
  Id(this.value) {
    checkArgument(value.isNotEmpty, message: 'invalid length');
    checkArgument(value.length < 255, message: 'invalid length');
    checkArgument(_idCharacterConstraint.hasMatch(value));
  }

  @override
  List<Object?> get props => [value];
}
```

**Comment by chibenwa** [comment]
> This log for ids or reference #ids`?

Ah you are right likely reference. Sorry for being paranoid.
