### ISSUE TITLE
Order is not reset when navigating from search to INBOX

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#2694]
### Description

https://github.com/linagora/tmail-flutter/assets/6928740/39389c62-9caf-4b5d-a923-50820c5bb328

I'd expect the sort order to be by date when I come back to mu INBOX!

**Comment by hoangdat** [comment]
weird problem, can you try to verify @QuangHoang1210

**Comment by chibenwa** [comment]
I do reproduce reliably!

**Comment by hoangdat** [comment]
I dont know you did any steps before issue, but at 0:03, an email from Nov 2023 still in the list. If you can, please try to reproduce again from the begining. As I remember, you raised an issue related to the order of search... IMO, it is related. Hope to see the way to reproduce from the begining, maybe clean cache before reproduce. Thanks

**Comment by chibenwa** [comment]
https://github.com/linagora/tmail-flutter/assets/6928740/41b9a53f-c806-436d-830f-4d6010ba0b68

We can still CLEARLY see that the searching context is not reset when I click on the INBOX folder: results are missing for instance.

**Comment by QuangHoang1210** [comment]
**Reproduce Step:**
1- Access Tmail
2- Click on Advance Search
3- Click Search button
4- Click sort order and select Sort by name A-Z
5- Click on Inbox folder

**Noted:** Happen with Chrome, Safari, Firefox

https://github.com/linagora/tmail-flutter/assets/124866146/1d028908-193e-4c06-970f-409820593a2d

@hoangdat @dab246
