### ISSUE TITLE
[Story] As a user, I want to compose email with simple text in browser 

### ISSUE THREAD

**Issue by dieptran88** [linagora/tmail-flutter#270]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC

* TODO: {link}

## Definition

- Given that I am a Tmail user 
- After log-in to Tmail in browser (desktop/tablet/mobile), in any screen, I can see a floating button that allow me to create new message
- I click on the floating button, an email composer will appears above current screen
- On this composer, i can see :
1.- Header fields include: 
     
   - Title of email: Default is "New message". When the subject is filled, this tittle is changed accordingly
   - "From": My name + email address . I cannot edit this field 
   - "To" : There field is empty, i can input recipient here by email address:
      - When i start input characters in this field, the system will show suggestion emails, I can select from this list or continue input an email address. When I click outside area of this field, the system will validate: 
         - If the email format is correct, that recipient will be added to the field :"To" and the suggested box disappear. 
         - If the email format is not correct, the field will be in error with read border 
      -  I can add several recipients in this field. 
      - I can remove recipient by clicking on button remove in each email 
      - When i click on arrow next to field "To", i can see expanded field CC and BCC. I can add one or several recipients on these fields. 
   -  The Subject: A text field 
2. - Email body: 
   - In the input section, I can write text  in simple mode and click button Send, if there is at least one recipient, the email is sent and the composer is closed. The email  is moved to mailbox Sent 
   - If there is no recipient and i click the button Send, there will be an message popup "Your email should have at least one recipient"
   - If  click icon Delete ,  the email will be removed. 

- I can click buttons in top right of screen to pop out or collapse (minimize) or open the email composer in full  screen mode

3. UI requirement:  The screen is responsive with different screen sizes: desktop/tablet/mobile

[Back to Summary](#summary)

## Screenshots

None

[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

**Comment by Kevinle2312** [comment]
Passed on Production platform.
