### ISSUE TITLE
PREVIEW PDF: cannot download / print

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#2708]
### Description

Given I click a pdf attachment
When I access it from the newly open Tab
THEN I can not print it, I can not download it

https://github.com/linagora/tmail-flutter/assets/6928740/c69e6e89-51ec-4c67-ba33-3e7870b79efe

**Comment by tddang-linagora** [comment]
**Firefox**

https://github.com/linagora/tmail-flutter/assets/160106668/9a796969-ff7e-4edb-9555-9fe7726707a2

**Safari**

https://github.com/linagora/tmail-flutter/assets/160106668/2817b7b2-18ab-4212-918c-6ccb4768c63e

**Chrome**
Debugging
