### ISSUE TITLE
Drag and drop attachment into the file list is not supported

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#2709]
### Description

Only in the text body is supported.

Dropping the attachment into the attachment list do some weird things...

(got tricked)

https://github.com/linagora/tmail-flutter/assets/6928740/9f8fd292-b087-412a-8217-bf570e2ce9a7

**Comment by dab246** [comment]
Fixed at https://github.com/linagora/tmail-flutter/pull/2670#issuecomment-1999817430
