### ISSUE TITLE
[WEBPC Only] [Read receipt] Email content is not translated correctly language on WEBPC

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#2718]
### ENV: 
- Device: Laptop
- Browser:  Chrome / Firefox / Safari
- ENV: tmail.linagora.com **[0.11.3-patch4-9]**

**Step:**
1, User select France/Russian in Manage Setting > Languages
2, User sent an email to other people with Read Receipt Request
3, Check Read Email content when other people already read it

**Actual:** 
-  Email content is translated to correct language on mobile web view but not on WEBPC

**Expected:**  
- Email content should be translated to correct language on WEBPC same as on mobile web view

**WEBPC**

![Image](https://github.com/linagora/tmail-flutter/assets/124866146/061f7a26-0b1d-4ffb-8aec-a807ff290939)

![Image](https://github.com/linagora/tmail-flutter/assets/124866146/0f597519-dfe5-49ed-99c9-0d52e42afe23)

**Mobile**

![Image](https://github.com/linagora/tmail-flutter/assets/124866146/c67b4338-64f8-4fd3-a12d-8a5ac89da403)

![Image](https://github.com/linagora/tmail-flutter/assets/124866146/549720b7-6499-42af-924f-7c50e0b068c9)

![Image](https://github.com/linagora/tmail-flutter/assets/124866146/4e930320-a83d-4fc7-ac9d-acee45c86746)

**Comment by hoangdat** [comment]
Current behavior: Read receipts response uses language of `read reciept sender`

**Comment by QuangHoang1210** [comment]
Precondition:
A- Sender: Using English
B- Receiver: Using Russian

Step:
1- Sender (A) send an email to Receiver (B)
2- Receiver open email and click read option

Actual:
-  Sender (A) receiver an email which be in Russian language even if he used English

Expected:
- The email should be translated base on Sender language


https://github.com/linagora/tmail-flutter/assets/124866146/2976f5df-9af5-46a7-b746-7e88f6485ed3
