### ISSUE TITLE
[Story] As a user, I want to attach files in email in web browser 

### ISSUE THREAD

**Issue by dieptran88** [linagora/tmail-flutter#272]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC

* TODO: {link}

## Definition

- Given that I have logged in successfully to Tmail in web browser 
- I click on floating Create email button, a new composer is opened.
- On this composer, I can see an icon attach file
- When I touch this icon, the file browser will be opened
- I can choose one or multiple files then click button to confirm uploading these files
   - If there is any file with the size larger than limitation provided by server (20MB), there will be an error message, i can not upload this file as attachments
   - Other files will be uploaded successfully
- On the email composer, I can see the list of attached files above the input area.
- Each attachment contains file type icon, file name, file size and a close icon
- I can click on close icon to remove the file 
 - If the list of file is too long, I can scroll up and down to see other part or write the content 
- I input other information of message then touch Send button, the system will check :
   - If the maxsize of the email is larger than limitation, there will be an error message and i cannot send this mail
   - If my Tmail account is out of quota, there will be an error message and i cannot send this mail
- If there is no error, the email will be sent  and it is moved to mailbox Sent 

**UI requirement: The screen is responsive with different screen sizes: desktop/tablet/mobile**

Refer to : https://app.zenhub.com/workspaces/tmail-flutter-60d039db6ef62a0013432c14/issues/linagora/tmail-flutter/57

[Back to Summary](#summary)

## Design ticket
https://ci.linagora.com/linagora/lgs/design/-/issues/136

[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

**Comment by Kevinle2312** [comment]
Passed on the Production platform.
