### ISSUE TITLE
[Direct Chat / Group Chat] “Add” icon button is outside the box leading space

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#2752]
**ENV:** 
- Android / IOS
- Twake v 2.4.22

**Step:**
1- User create direct chat / group chat
2- Focus on Chat composer

**Actual:** 

- “Add” icon button inside the box leading space ≠ trailing space

**Expected:** 

- “Add” icon button outside the box padding the same for leading and trailing

![Image](https://github.com/linagora/tmail-flutter/assets/124866146/c5d8e05f-b4a4-4509-946c-8afcdce665af)

**Comment by dab246** [comment]
@QuangHoang1210 Please move it to Twake Chat
