### ISSUE TITLE
Microsoft EDGE: viewing PDF is broken?

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#2754]
### Description

![download](https://github.com/linagora/tmail-flutter/assets/6928740/b5833ecb-74eb-4b97-87fe-82b0d9fefa24)

Example of the same doc in firefox, chrome:

![Screenshot from 2024-03-29 13-56-00](https://github.com/linagora/tmail-flutter/assets/6928740/24c4eabc-5e65-4881-9321-e926a453b67a)

![Screenshot from 2024-03-29 13-55-31](https://github.com/linagora/tmail-flutter/assets/6928740/e7087d28-cc9b-4e7b-9434-86599cb60e06)

**Comment by QuangHoang1210** [comment]
**On Microsoft Edge:** pdf viewing is displayed a half with scrolling

![CAP_A6FD09D6-1DE9-4D43-B13B-424CFB514742](https://github.com/linagora/tmail-flutter/assets/124866146/e05af90e-3dcf-48b6-9043-c2b98f7d338a)
