### ISSUE TITLE
Chrome: cannot print the PDF

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#2764]
### Description
![image](https://github.com/linagora/tmail-flutter/assets/6928740/b2dd7ba5-a3c0-46fa-8dbc-e09964748e28)

No print button...

**Comment by hoangdat** [comment]
we did the same with Tdrive, no print button in preview mode.

**Comment by chibenwa** [comment]
> (It has some side effect in safari browser)

I am not using safari...

**Comment by hoangdat** [comment]
new kind of viewer
