### ISSUE TITLE
[IOS] There is existed a big empty space between Signature and attachment if user expand / collapse signature before uploading attachment

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#2768]
**ENV:** 
- IOS app
- Tmail v0.11.3411

**Precondition:**
- User already create identity signature
-  User uploading attachment after expand signature

**Step:**
1- User open composer
2- User expand / collapse the signature
3- User upload any attachment

**Actual:**
- Signature and attachment have a big empty space

**Expected:**
- Attachment position should be right bellow Signature

https://github.com/linagora/tmail-flutter/assets/124866146/bf0c2af6-7e34-48af-bae4-0dfe862d5b4f

**Comment by hoangdat** [comment]
We had an improvement for Mobile composer #2717
