### ISSUE TITLE
[IOS] Improve - Should show list email when user changed filter or sort order even user not input any search key

### ISSUE THREAD

**Issue by QuangHoang1210** [linagora/tmail-flutter#2771]
**ENV:** 
- IOS app
- Tmail v0.11.3411

**Precondition:**
- User changed sort order at the first time
- Not input any search key

**Step:**
1- User click advance search
2- User not input any search key
3- User changed sort order 

**Actual:**
- List of email is not displayed

**Expected:**
- List of email will be displayed as searching condition: Search key = emplty AND sort order

https://github.com/linagora/tmail-flutter/assets/124866146/e9293d0d-7acf-4c22-93c7-1350f7fe4e34

**Comment by hoangdat** [comment]
### DoD:
- [ ] integration test for mobile
- [ ] integration test for web
