### ISSUE TITLE
Big image dimension in signatures

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#2774]
### Description

![image](https://github.com/linagora/tmail-flutter/assets/6928740/2c0c9dc2-ae38-4ef7-b2f6-00d60c421aa0)

![download](https://github.com/linagora/tmail-flutter/assets/6928740/c9646ef2-dafa-44ff-954c-b22f4b0280f6)

1. the signature is tooo big

 - Either resize it to reasonable dimension
 - Or reject too large (in terms of pixel) images
 
 2. some receiver were not seeing the signature

**Comment by dab246** [comment]
## Propose

- [ ] - [ ] Set `max-width` of inline image is equal to the width of the editor in IdentityCreator widget
- [ ] Always show scrollbar when content exceeds current frame in preview identity

WDYT about this propose? @hoangdat @chibenwa ?

**Comment by hoangdat** [comment]
Note:
- our html editor also have `resize tool`,
- we should reject image which have the size is too big
