### ISSUE TITLE
On the iOS version, I can't type the email body

### ISSUE THREAD

**Issue by Kevinle2312** [linagora/tmail-flutter#283]
### Description
On the iOS version, I can't type the email body

### Expected result
On the iOS version, I am able to type the email body

### Current behaviour
Can not type anything on the email body

### Context

Devices, OS
iPhone 7 - iOS 13.3.1

### Additional information

https://user-images.githubusercontent.com/32490981/155499369-74a148db-3019-4153-978e-71d16d4be262.mp4

**Comment by hoangdat** [comment]
duplicated with #288
