### ISSUE TITLE
Forwards: add recipient is buggy

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#2830]
### Description

GIVEN I type a recipient name in forward page
AND it do not autocomplete
AND i do not click ENTER
WHEN I click add recipient
THEN I am propted I need to add one recipient

### Expected result

As if I pressed enter to validate the recipient input

### Current behavior

https://github.com/linagora/tmail-flutter/assets/6928740/8117d91a-b6da-4436-b22f-9a5eead16d1b

**Comment by hoangdat** [comment]
- [ ] people click on `+ Add recipients`, account should be add directly
- [ ] still have the read toast in some case (adding demo)
