### ISSUE TITLE
[CNB] [WEB] Custom message for forwards

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#2831]
### Description

Customer wants custom messsage:

![Screenshot from 2024-04-26 15-39-31](https://github.com/linagora/tmail-flutter/assets/6928740/020ad020-e1ee-42c3-a0c5-ab2e4e4d1671)

![Screenshot from 2024-04-26 15-38-14](https://github.com/linagora/tmail-flutter/assets/6928740/9a1d0223-e595-48f0-ba30-425510de62e6)

Let's add entries in `env.file` to customize these 2 messages.

ETA: mid may

Customization needed only for web

**Comment by hoangdat** [comment]
- we will prioritize value in `env.file` (no locale support)
- if no value, fallback is current value (with locale support)

WDYT?

**Comment by chibenwa** [comment]
> WDYT?

Yes exactly this.
