### ISSUE TITLE
French locale: Nettoyer is too big on the side menu

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#2832]
### Description

![Screenshot from 2024-04-26 15-44-36](https://github.com/linagora/tmail-flutter/assets/6928740/c07902b2-d9f5-402c-9344-1611a36e1d73)

Traduire par `Vider` ?

**Comment by dab246** [comment]
Fixed at https://github.com/linagora/tmail-flutter/pull/2833
