### ISSUE TITLE
[Story] As a user, I want to open email on Tmail app from notification on mobile or tablet 

### ISSUE THREAD

**Issue by dieptran88** [linagora/tmail-flutter#284]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC

* TODO: {link}

## Definition

- Given that I am Tmail user and logged-in to the app
- Given that the notification permission is turned on for Tmail app and the app is running in background
- There is a new email and user can see push notification about this new message.
- If user click on notification in Lock screen, then the authentication screen will be opened
   - If I input correct password, the device is unlocked and I am redirected to the Email detail screen and I can see the content of email.
- If user is not in lock-screen , user can see floating/banner notification. User click on this notification and the email content screen will be opened 
- User can also swipe down to see the notification bar, then click on the new email notification, the email content screen will be opened. 
- When an email is opened from notification, that notification  is also cleared on notification center 

[Back to Summary](#summary)

## Screenshots

None

[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

**Comment by hoangdat** [comment]
### DoD:

Open EmailView for mobile/tablet when click in notification
