### ISSUE TITLE
Inlined image broken in GMail

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#2849]
### Description

![image](https://github.com/linagora/tmail-flutter/assets/6928740/25d38772-9271-4b90-a5e3-acbdb59980df)

GMail do not support inlined base64 image.

We somehow have to compose an email and attach the image as an inlined email attachment with CID.

Let's discuss this 06/05 during Twake Mail frontend meeting. If we can find a way to keep the design simple.

**Comment by chibenwa** [comment]
I reached out to modern email folks...

```
Hello Modern email folks!

Today I struggled with one aspect of RFC-8621 JMAP Mail

We were trying to add client support for image in signatures - if possible in an inter-operable way.

The issue is that Identity only defines text and html fields and do not include images in there.

We so far thought about several approach:

Inlining the image directly in an img tag as base64, which can easily be done with the current spec, which we POCed, but is not supported by all MUA, including GMail.
So img tag base64 is a dead-end...
Of course one would like to attach the signature as a separate mime part with multipart/related, cid, content-disposition inlined &al but the RFC do not define such data structure for storage on the server side, thus this would need to live as a vendor specific extension... Emails with the given signature could only be composed from my MUA...
And finally having the signature linking third party http resources. Sure the signature is then not duplicated in each and every mail. Sure any MUA can compose an email. But the edition of the signature (changing the image) can no longer be done in an interoperable fashion (changing the image would require updating / creating a new HTTP third party resource).

How other JMAP players worked around this issue?
```

Tried out what fastmail do:

I see fastmail opted for an HTTP link managed by the user... 

![image](https://github.com/linagora/tmail-flutter/assets/6928740/8789157c-1e30-4d69-bbe5-af8df22346ae)

**Comment by chibenwa** [comment]
I move this back to `story:writing`

 -> We are discussin g a solution. That's not the time yet to implement something...

Also Fastmail solution as is is not user friendly at all. We need to design a system that helps preserve the current UX.

**Comment by chibenwa** [comment]
What I have in mind is a new server extension:

```
POST (auth brearer) jmap.linagora.com/publicAsset [binary payload]
201 + location of the URI to insert in the Identity
403 No space left (need to be managed)

GET  (auth brearer) jmap.linagora.com/publicAsset
{
    "itemCount": 4,
    "spaceUsed": "36542",
    "spaceAllowed": 64000,
    "assets": [
        {
            "url": "https://jmap.linagora.com/publicAssets/xyz",
             "size": "32000"
         },
         ...
    ]
 }
 
 DELETE (auth BEARER) https://jmap.linagora.com/publicAssets/xyz
 200 / 404

GET (no auth) jmap.linagora.com/publicAsset/xyz
```

**Comment by benbucksch** [comment]
Public HTTP URLs in email need to be avoided, because of the tracking problem that they pose. They are basically a read validation for spammers. So, properly implemented email clients **have** to ignore HTTP URLs in email.

**Comment by benbucksch** [comment]
The only way to properly include images in email is data: URLs (discouraged), or multipart/related with cid: URLs.
