### ISSUE TITLE
Cannot load more items on oncommit.linagora.com

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#2861]
### Description

-> I still can on tmail.linagora.com

Uploading loadmore.mp4…

**Comment by hoangdat** [comment]
please upload your video, it works on my site


https://github.com/linagora/tmail-flutter/assets/6462404/48b3134e-d73c-407b-8377-66e56d636d44

**Comment by chibenwa** [comment]
https://github.com/linagora/tmail-flutter/assets/6928740/1dd45023-27a4-4ea6-ba8a-ca2e368bb12e

**Comment by tddang-linagora** [comment]
**Chrome - oncommit-tmail.linagora.com**

https://github.com/linagora/tmail-flutter/assets/160106668/1eb8020a-2bca-4f21-a12b-f8c1bb322fd5

**Firefox - master build**

https://github.com/linagora/tmail-flutter/assets/160106668/1f456976-5662-42c4-a14e-cd3d63175385

Is there any preconditions?

**Comment by chibenwa** [comment]
It looks cache dependant. Now it is OK for me...
