### ISSUE TITLE
Dandling link

### ISSUE THREAD

**Issue by guimard** [linagora/tmail-flutter#2866]
### Description

The page https://github.com/linagora/tmail-flutter/security/policy refers to https://github.com/linagora/tmail-flutter/blob/master/docs/modules/ROOT/pages/security.adoc which isn't available

**Comment by chibenwa** [comment]
Typo? https://github.com/linagora/tmail-backend/blob/master/docs/modules/ROOT/pages/security.adoc

Not sure this is relevant.

**Comment by chibenwa** [comment]
We shall use https://github.com/linagora/tmail-flutter/blob/master/privacy.md instead

**Comment by chibenwa** [comment]
https://github.com/linagora/tmail-flutter/pull/2870
