### ISSUE TITLE
Replies do not preserve line breaks (plain text email, no html)

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#287]
### Description

![Screenshot from 2022-02-25 11-58-38](https://user-images.githubusercontent.com/6928740/155656931-7e9293b1-b822-41c5-be12-8779f83ebaa3.png)
![Screenshot from 2022-02-25 11-58-28](https://user-images.githubusercontent.com/6928740/155656937-a09df716-6b13-4e09-ad35-7658dcd93304.png)

### Expected result

Line breaks preserved in the reply...

**Comment by chibenwa** [comment]
This happens also on chrome, this happens only for messages in plain text (no html)

Also happens on mobile

**Comment by chibenwa** [comment]
![Screenshot_20220228-113325_Team Mail](https://user-images.githubusercontent.com/6928740/155924678-4dcf70e0-f777-484e-b404-b850903797bb.jpg)

**Comment by dab246** [comment]
@chibenwa  please forward it to email `userb@qa.open-paas.org` help me
