### ISSUE TITLE
Create notification toggle UI in Settings screen

### ISSUE THREAD

**Issue by tddang-linagora** [linagora/tmail-flutter#2877]
### Description
~Create new setting UI in Settings screen for notification, including a toggle and a loading widget. Also cache the app's notification state in `SharedPreferences`~
Plan changed. To better inform user of current notification permission, toggle will reflect that permission and redirect user to system's settings when tapped

### Definitions of done
- [x] Create NotificationScreen inside Settings screen for mobile only
- [x] Create toggle inside NotificationScreen
- [x] ~Cache toggle's state whenever changed~

**Comment by hoangdat** [comment]
please do not show it in web app
