### ISSUE TITLE
Handle notification toggle in Flutter for Android

### ISSUE THREAD

**Issue by tddang-linagora** [linagora/tmail-flutter#2878]
### Description
Handle toggle push notification in Flutter side for Android, with the UI created in #2877. The only different between push notification on and off state is no push notification will be shown. Everything else up until that point is kept as is.

### Definitions of done
- [ ] Check the status of app's push notification setting state before calling local push notification

**Comment by hoangdat** [comment]
please define DoD

**Comment by tddang-linagora** [comment]
Close due to changes in implementation of notification toggle. There will be no need for platform specific implement anymore.
