### ISSUE TITLE
Handle notification toggle in Swift for iOS

### ISSUE THREAD

**Issue by tddang-linagora** [linagora/tmail-flutter#2879]
### Description
Handle toggle push notification for iOS in Swift side, ideally with the help of `Keychain`, with the UI created in #2877 

### Definitions of done
- [ ] Add a boolean to `KeychainSharingSession` in both Flutter side and Swift side
- [ ] Update this boolean inside `KeychainSharingManager` every time app's push notification setting changes

**Comment by hoangdat** [comment]
- [ ] need entitlement @hoangdat

**Comment by tddang-linagora** [comment]
> * [ ]  need entitlement @hoangdat

**Clarification**
- https://stackoverflow.com/a/46157854/23727759
- https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_developer_usernotifications_filtering

**Comment by tddang-linagora** [comment]
Close due to changes in implementation of notification toggle. There will be no need for platform specific implement anymore.
