### ISSUE TITLE
On the iOS app, I can not type in my email content

### ISSUE THREAD

**Issue by Kevinle2312** [linagora/tmail-flutter#288]
### Description
On the iOS app, I can not type in my email content.

### Expected result
I can type in my email.

### Current behaviour
On the iOS app, I can not type in my email content

#### Reproduction Steps
1. Sign in on the mobile app (iOS)
2. Click on compose
3. Verify the issue by clicking on the letter body text section

### Context

1. iPhone 7 - iOS 13.3.1

### Additional information

https://user-images.githubusercontent.com/32490981/155680203-b58000d5-499b-4aa2-9ea2-b887d6f93feb.mp4

**Comment by dab246** [comment]
This bug no longer appears in the current version.

**Comment by Kevinle2312** [comment]
PAssed on CI platform.
