### ISSUE TITLE
[COMPOSER] INPUT LOSS

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#2882]
### Description

```
GIVEN sending fails
THEN the composer should be reopened with my input
AND a toast message informs me of the error
```

Already reported this.

How to reproduce: Mail to `"abc@def"@linagora.com` (edge case not supported by javax.mail).
The way to trigger the error backend side is not the thing important here. Error would anyway happen: I can even stop the JMAP server to trigger it.

Our golden rule should be: "Never loose user input".

**Comment by chibenwa** [comment]
https://github.com/linagora/tmail-flutter/assets/6928740/1a3f882e-c606-462e-865a-1e43f9de4fbd

**Comment by hoangdat** [comment]
still in progress it in refactoring branch [v0.11.3-patch4-dev](https://github.com/linagora/tmail-flutter/tree/v0.11.3-patch4-dev) #2807, #2826,

**Comment by tddang-linagora** [comment]
- https://github.com/linagora/tmail-flutter/issues/2901
