### ISSUE TITLE
[Feedback] Loading time for opening email is very long

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#2884]
### Desc:
- time to open email in Fr is almost more than 10s
- Android, Samsung s24

### DoD:
- [ ] what is the problem of loading email
- [ ] how to improve it?
- [ ] new Android API have some restriction in loading in background?

**Comment by hoangdat** [comment]
- [ ] measure time for loading content for some kind of content (rich html, github, multiple reply, ...)
- [ ] measure time for transformation content for some kind of content (rich html, github, multiple reply, ...)
- [ ] ask for more information in feedback (what kind of content, video, ...)

**Comment by dab246** [comment]
## Measure Time when opening email

- Device: `Android Emulator Pixel 8 Pro API 34`
- Network speed: Download: `62.57 Mbps` |  Upload:  `55.78 Mbps`

| **CONTENT**                       | **SERVER**               | **CACHE**            | **TRANSFORMATION**
|:-------------|:---------------:|:-------------:|:-------------:|
| Rich Html                               |     2596 ms         |         96 ms                   |              2638 ms
| Multiple Reply  (11 times)     |      4762 ms        |          65  ms                 |              4770 ms
| Github                                    |      2459 ms        |          14 ms                   |             2466 ms
| Medium                                  |      2905 ms        |          95 ms                  |              3020 ms
| Multiple Inline Image             |      2851 ms        |           87 ms                  |             11244 ms

**Comment by hoangdat** [comment]
so the total time of loading email without cache is `SERVER ` + `TRANSFORMATION`, am I right?

**Comment by dab246** [comment]
> so the total time of loading email without cache is `SERVER ` + `TRANSFORMATION`, am I right?

that's right!
