### ISSUE TITLE
We are canceling the event due to bad weather

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#2890]
### Description

![Screenshot from 2024-05-22 14-26-13](https://github.com/linagora/tmail-flutter/assets/6928740/028ec88f-395d-4713-8807-be255c92c7ff)

And...

```
$ grep 'bad weather' * -R
lib/main/localizations/app_localizations.dart:      '"We are canceling the event due to bad weather."',
lib/l10n/intl_en.arb:  "subMessageEventActionBannerCanceled": "\"We are canceling the event due to bad weather.\"",
lib/l10n/intl_messages.arb:  "subMessageEventActionBannerCanceled": "\"We are canceling the event due to bad weather.\"",
```

While the underlying ICS does no mention of "bad weather".

[meeting .ics.txt](https://github.com/linagora/tmail-flutter/files/15403267/meeting.ics.txt)

**WTF? Why making things up?**

Here I expect a neutral message sticking to what we know: `XYZ cancelled this meeting.`

Please update everything accordingly!

**Comment by tddang-linagora** [comment]
> Here I expect a neutral message sticking to what we know: `XYZ cancelled this meeting`.

That would be duplicated with the message above it. If there's no data suitable for that field from the payload received from BE, should we remove that grey description text altogether?
<img width="574" alt="Screenshot 2024-05-23 at 09 53 14" src="https://github.com/linagora/tmail-flutter/assets/160106668/c6731684-d2f9-45b7-85c7-8d2f0873f53a">

**Comment by chibenwa** [comment]
> If there's no data suitable for that field from the payload received from BE, should we remove that grey description text altogether?

Oh yes, please!
