### ISSUE TITLE
On the android app, I can't sent an email with attachment 

### ISSUE THREAD

**Issue by Kevinle2312** [linagora/tmail-flutter#290]
### Description
On the android app, I can't send an email with an attachment 

### Expected result
I can send a message with an attachment

### Current behaviour
On the android app, I can't send an email with an attachment 

#### Reproduction Steps
1. Sign in to the app on Android
2. Click on compose
3. Verify the issue

### Context

1. Samsung galaxy A51 - Android 11

### Additional information

https://user-images.githubusercontent.com/32490981/155682753-504c7f29-86b7-49db-8f89-a5b7ddd6dfec.mp4

**Comment by hoangdat** [comment]
will be solved in #130.

**Comment by Kevinle2312** [comment]
Tested on the mobile app. Failed on the CI platform. I can not send an email with an attachment.
Reproduce step:  
1. Sign in to the platform: firstname200.surname200@upn.integration-open-paas.org/secret200
2. Send an email with attachments
3. Verify the issue

**Comment by Kevinle2312** [comment]
Failed on CI platform. I can not upload attachments from the Android app. @hoangdat

**Comment by hoangdat** [comment]
> Failed on CI platform. I can not upload attachments from the Android app. @hoangdat

video please

**Comment by hoangdat** [comment]
as the new implementation, you will have a message in the case upload a file have size more than 20mb

**Comment by Kevinle2312** [comment]
Here it is @hoangdat : 

https://user-images.githubusercontent.com/32490981/163346621-427817a5-2048-45ca-b26c-b60fc471267e.mp4

There are two issues in this video:
1. Unable to upload an attachment
2. Somehow, a scroll bar appears con the composer while nothing is on it.

**Comment by hoangdat** [comment]
This is the old version, when you upload a file > 20mb, only a common message (like that), but for the new version, a dedicated error message is showed to indicate user what happen. Please update the app, please please please please.

**Comment by Kevinle2312** [comment]
Passed on CI platfrom.
