### ISSUE TITLE
[CUSTOMER] [IOS] notificiation on IOS for each webmail action

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#2900]
### Description

Customer feedback:

Every time I do an action on the webmail I receive a  notification on my IOS phone

![IMG_0444](https://github.com/linagora/tmail-flutter/assets/6928740/040e856a-4a77-4759-b962-6443a8c3d352)

**Comment by chibenwa** [comment]
v 0.11.3411

**Comment by chibenwa** [comment]
Those notifications are for email sent

**Comment by chibenwa** [comment]
Suggestion: filter out emails in `draft`, `sent` and `outbox`

**Comment by hoangdat** [comment]
can you share the version of backend?

**Comment by chibenwa** [comment]
0.8.2

so old.

**Comment by hoangdat** [comment]
rootcause: `refreshToken` is not well updated in Swift code: https://github.com/linagora/tmail-flutter/pull/2876
