### ISSUE TITLE
[Web] Cached composed email, to resume edit/resend in case token/session expires and cannot refresh

### ISSUE THREAD

**Issue by tddang-linagora** [linagora/tmail-flutter#2901]
**Related Issue**
- #2889

**Case study**
When user finish composing email and decide to send/save the email as draft, the app session expires and:
1. There's no refresh token or
2. Refresh token exists but also expires

Current behavior is pushing the user to log in screen, and when they logged back in, their input on the composer is lost, which is undesired. This raise the need of caching the email temporarily so that user can continue their work later on.

**Save email content and attachments on type/upload**

`Window.sessionStorage` for web.

Cache in session storage should be included `composer|accountId|username`

1. Email content will be cached when
  - have a state variable in dashboard to indicate composer is opening or not 
  - cache only when composer is opening and `gotologin`

2. Cached email will be cleared when
   1. Email send successfully
   2. Email save draft successfully
   3. Email discarded
   4. when open app, then `composer|accountId|username` is not matched
   5. after open composer from session storage 

**Handle send/save draft email when token expires & refresh token also expires OR there's no refresh token**

1. When "send/save draft email" is pressed, check the token's remaining lifetime before the request is made
    1. If more than 1 minute, proceed with the request
    2. Else
        1. Show dialog notice the user to log in again, with only 1 button to go to log in screen
        2. After user log in, check the app's storage for any pending email. If exists, open composer and load pending email

**Feature flow diagram**
https://drive.google.com/file/d/133S7loaoSpePD5WR966bxJQ_gS6RF6KN/view?usp=sharing
    
**TODO**

- [ ] Cache email content on user interaction
- [ ] Check email cache on Mailbox Dashboard Screen loaded. Show composer with cache email content if exist for this `accountId|username`

**Comment by tddang-linagora** [comment]
### For web
The caching mechanism of choice is [Window.sessionStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/sessionStorage)
- The saved data only exists on 1 browser's tab, and will be deleted when that tab is closed
- Data will remain even if that tab's url is redirected
- If user blocks browser's cookie, this method of caching will not work

**Comment by tddang-linagora** [comment]
### For mobile
The caching mechanism of choice is [Hive](https://pub.dev/packages/hive)
- Cached data will persist until app's data or the app itself is deleted
- Can be combined with encryption method for higher security
- Still, might violate GDPR

**Comment by tddang-linagora** [comment]
@chibenwa @hoangdat @dab246 Let's have a discussion. What are your thoughts?

**Comment by dab246** [comment]
> ### For mobile
> The caching mechanism of choice is [Hive](https://pub.dev/packages/hive)
> 
> * Cached data will persist until app's data or the app itself is deleted
> * Can be combined with encryption method for higher security
> * Still, might violate GDPR

Please elaborate more on the implementation flow for mobile. Should we synchronize it with `SendingQueue` like in offline?

**Comment by dab246** [comment]
> ### For web
> The caching mechanism of choice is [Window.sessionStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/sessionStorage)
> 
> * The saved data only exists on 1 browser's tab, and will be deleted when that tab is closed
> * Data will remain even if that tab's url is redirected
> * If user blocks browser's cookie, this method of caching will not work

With the web, we should more clearly describe its storage and management, because currently we have a case of storing data on `Session Storage` which is `reload page` browser.

**Comment by tddang-linagora** [comment]
> > ### For web
> > The caching mechanism of choice is [Window.sessionStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/sessionStorage)
> > 
> > * The saved data only exists on 1 browser's tab, and will be deleted when that tab is closed
> > * Data will remain even if that tab's url is redirected
> > * If user blocks browser's cookie, this method of caching will not work
> 
> With the web, we should more clearly describe its storage and management, because currently we have a case of storing data on `Session Storage` which is `reload page` browser.

I'm planning to use the same `sessionStorage` from when the app's page is reloaded.

**Comment by tddang-linagora** [comment]
> > ### For mobile
> > The caching mechanism of choice is [Hive](https://pub.dev/packages/hive)
> > 
> > * Cached data will persist until app's data or the app itself is deleted
> > * Can be combined with encryption method for higher security
> > * Still, might violate GDPR
> 
> Please elaborate more on the implementation flow for mobile. Should we synchronize it with `SendingQueue` like in offline?

Both implementations for web and mobile are the same. With the only additional difference is that the cache in web only lives in the app's session, and in mobile the cache can live until the app is deleted at the worse case scenario.
