### ISSUE TITLE
Disable yes-no-maybe for events that we cannot reply to

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#2907]
### Description

![image](https://github.com/linagora/tmail-flutter/assets/6928740/ae91b42e-55e4-4746-a606-ed6cc2158d92)

Do NOT prompt for answer yes / maybe / no if the ICS is missing the mandatory fields.

Those fields are:

 - METHOD
 - organizer

**Comment by chibenwa** [comment]
Related to https://github.com/linagora/tmail-backend/issues/1080 and complements it...

**Comment by quantranhong1999** [comment]
There has been a CalendarEvent reply response change to help expose error details in case of rejection.

see https://github.com/linagora/tmail-backend/pull/1081/commits/bb98b53b5dc88ae3f629d1793885083ca7f30682

not included in the current backend release (0.10.1-rc1) yet though.
