### ISSUE TITLE
[WEB] Two scroll bars for medium sized screens

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#292]
### Description

https://user-images.githubusercontent.com/6928740/155917586-2278a50b-2b66-43f3-a047-8075b0210e13.mp4

On firefox 73.0.1 and a screen size of 1368x768 (16:9) I see two scroll bars on email content.

Also spotted for some emails on chrome

**Comment by hoangdat** [comment]
@chibenwa I can not see your video, black screen :(

**Comment by chibenwa** [comment]
Arg, my old computer strike again...

**Comment by chibenwa** [comment]
![Capture d’écran de 2022-02-28 11-49-35](https://user-images.githubusercontent.com/6928740/155925934-e4ca7943-40e3-4687-9ec2-af1e0f7ab10b.png)

Here is the screenshot
