### ISSUE TITLE
Rich text editor doesn't work on android

### ISSUE THREAD

**Issue by X-Ryl669** [linagora/tmail-flutter#2922]
### Description

When trying to use the Android version of Twake Mail, while composing a mail, the rich text editor (Bold / Italic / font, ....) doesn't work correctly.

### Expected result
Clicking on the icons should perform the actions as expected

### Current behavior
Examples to reproduce:
1. Open the rich text bar
2. Click on "B" icon (bold). 
3. Click on the text area and type text. It should be bold, it isn't

or

1. Select some text in the editor
2. Open the rich text bar
3. Click on "B" icon (bold)
4. The text should become bold, it doesn't

or 

1. Select some text
2. In the bar, change the style for the text
3. All the line is modified, not the selected text (sometimes, the line above or below is also modified)

### Context

Xiaomi Mi Mix 2 running on Android 9.

**Comment by hoangdat** [comment]
yes, a known issue. We fixed it in https://github.com/linagora/tmail-flutter/pull/2898, but still have some things to verify before release new version.

**Comment by dab246** [comment]
> yes, a known issue. We fixed it in #2898, but still have some things to verify before release new version.

PR #2898 for web platform, with mobile it's been fixed here in PR #2795, we're waiting to refactor and merge some things

**Comment by X-Ryl669** [comment]
Thanks!

Can you release the new version on the play store? (At least in beta program?) so I can confirm it's fixed?
