### ISSUE TITLE
Change mailbox very quick when refreshing after any mail action make the message list is not showed correctly

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#2925]
### Desc:

https://github.com/linagora/tmail-flutter/assets/6462404/4396b8b5-37c5-4000-9a4b-faa09c1172d2

### DoD:
- [ ] make the message list of a mailbox show correctly

**Comment by chibenwa** [comment]
I am in INBOX
I move a mail to another mailbox
I then immediatly switch into another mailbox
It's loaded...
Then when the initial mail is moved, the INBOX is displayed for few seconds before switching back to the original one.
