### ISSUE TITLE
Memory leak in composer controller

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#2926]
### DoD:
- [x] detect also in mobile/web
- [x] why `dispose` of `composer_controller` is not invoked?
- [x] verify the root cause relate to text input
- [x] `dashboardViewStateWorker` is not init in `composer_controller`

**Comment by tddang-linagora** [comment]
>why dispose of composer_controller is not invoked?

According to 
- https://github.com/jonataslaw/getx/issues/3051#issuecomment-1987601565
>Dispose does nothing.

**Comment by dab246** [comment]
> > why dispose of composer_controller is not invoked?
> 
> According to
> 
> * [GetxController dispose is not working jonataslaw/getx#3051 (comment)](https://github.com/jonataslaw/getx/issues/3051#issuecomment-1987601565)
> 
> > Dispose does nothing.

So, we should create PR to move actions in `dispose` of GetxController to `onClose`

**Comment by tddang-linagora** [comment]
>verify the root cause relate to text input

**Similar issue**
- https://github.com/flutter/flutter/issues/148291

**Fixes**

- https://github.com/flutter/flutter/pull/150661

**Comment by tddang-linagora** [comment]
**Before**

https://github.com/linagora/tmail-flutter/assets/160106668/53e37f48-a6d3-4088-9809-c9b769e9e252

**After**

https://github.com/linagora/tmail-flutter/assets/160106668/2d71cc84-01e7-43e0-81c3-4893f8a1491a

**Comment by dab246** [comment]
> > verify the root cause relate to text input
> 
> **Similar issue**
> 
> * [UndoManager does not release UndoManagerClient causing memory leaks flutter/flutter#148291](https://github.com/flutter/flutter/issues/148291)
> 
> **Fixes**
> 
> * [Fix: Memory leak in UndoHistory widget because it never de-registered itself as global UndoManager client (Resolves #148291) flutter/flutter#150661](https://github.com/flutter/flutter/pull/150661)

## Root cause

- `TextField` widget use `EditableText` widget. `EditableText` widget use `UndoHistory` widget. UndoHistory leak UndoManagerClient

**Comment by chibenwa** [comment]
Should be handled in Definition of done of release. No release without a quick memory leak audit ;-)
