### ISSUE TITLE
Feature : detect loss of connection and suggest to refresh / reconnect

### ISSUE THREAD

**Issue by Facyla** [linagora/tmail-flutter#2928]
### Description
Feature : detect loss of connection on web client and suggest to refresh / reconnect when this happens. 
This typically happens after computer sleep: when waking up the computer, the interface remains, without indicating that it cannot fetch content until one manually refreshes the page. 
It then redirects to the SSO, and finally back to the app (which is an attended behaviour).

### Expected result
Whether display a message indicating that there is a loss of connection (or tokens are expired, or cannot join the server, or whatever happens indeed in that case), and offer the ability to take the appropriate action (ie. resfresh=>reconnect).

### Current behavior
No indicator of the current state of the app. So no notification or warning or update of the mailbox content. However clicking in the interface triggers the login process and redirect to SSO.

### Context
Web app.

**Comment by hoangdat** [comment]
### DoD:
- [ ] separate handling exception for mobile and web
- [ ] [WEB] reload dialog when user try to reload by key-shortcut or click on browser reload
- [ ] [WEB] token expired, user interact any actions
  - token expired, please login again (Designer)
- [ ] [WEB] loss of connection: show toast for network and error toast for every action

**Comment by chibenwa** [comment]
Hello Dat,

> separate handling exception for mobile and web

I am unsure about this one to be honnest. Why would web need to be different than mobile ?

**Comment by hoangdat** [comment]
We should keep it separated to make it easier in maintenance. Mobile supports offline mode in more functions (sending email). 
But for sure, we need to have cross-check to make it less boilerplate.
