### ISSUE TITLE
Vacation banner is truncated in french

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#2929]
### Description

![Screenshot from 2024-06-13 11-42-51](https://github.com/linagora/tmail-flutter/assets/6928740/1d63b369-2510-4ff7-bba8-25a52453b28b)

Should be `Termine maintenant`

**Comment by hoangdat** [comment]
- [ ] padding for buttons
- [ ] eclipsing text
- [ ] adding tooltip
