### ISSUE TITLE
[WEB] Composer crashes

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#293]
### Description

When opening the composer, it imediatly crashes with a `null` value displayed,

Firefox 73.0.0.1, no issues on chrome

https://user-images.githubusercontent.com/6928740/155922680-54c995e3-76bb-422a-95fa-b8c619f8397f.mp4

I saw this error, I don't know if it is related:

```
Error in parsing value for ‘max-width’.  Declaration dropped. toastify.css:14:953
Elements matching selector: .toastify-left, .toastify-right
NodeList []
​
length: 0
​
<prototype>: NodeListPrototype { item: item(), keys: keys(), values: values(), … }
```

**Comment by Arsnael** [comment]
Black screen video again^^'

**Comment by chibenwa** [comment]
![Capture d’écran de 2022-02-28 15-43-15](https://user-images.githubusercontent.com/6928740/155951845-86cbf66b-aa36-4dae-8b76-34de49bdc12c.png)
