### ISSUE TITLE
Release new version for Sprint 24

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#2933]
### DoD:
- [ ] Verify in all platform: Android, iOS, Web (responsive)
- [ ] Translate for all langs
- [x] Tag version
- [x] Communicate CHANGELOG

**Comment by chibenwa** [comment]
Definition of done: Fill completly the non-regression file

[tnr-tmail-v0.11.3-patch4-16.ods](https://github.com/user-attachments/files/15821009/tnr-tmail-v0.11.3-patch4-16.ods)

**Comment by hoangdat** [comment]
- [x] localhost test in Chrome 
[tnr-tmail-v0.11.5001_localhost.ods](https://github.com/user-attachments/files/16108616/tnr-tmail-v0.11.5001_localhost.ods)

**Comment by hoangdat** [comment]
- v0.11.5001 in tmail-canary
- in Close test: iOS, Android
