### ISSUE TITLE
[WEB] [EDGE] Recipient widget UI glitch

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#2935]
### Description

Close button flyover focus is not centered

### Current result

![signal-2024-06-13-143431_003](https://github.com/linagora/tmail-flutter/assets/6928740/895a7fe3-b895-489f-9659-517c33c6513f)

### Expected behavior

![qsfwfw](https://github.com/linagora/tmail-flutter/assets/6928740/4807b8b7-1b24-4bf3-b992-29c7018b6d52)

**Comment by hoangdat** [comment]
When the height of window is small, recipient popup is not showed well
Ex: Safari 
<img width="1273" alt="image" src="https://github.com/linagora/tmail-flutter/assets/6462404/d86700e3-4148-4409-a6e9-7b41c9149f61">
