### ISSUE TITLE
Do non regression tests: v0.11.3-patch4-16 (Safari)

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#2937]
### Description

[tnr-tmail-v0.11.3-patch4-16.ods](https://github.com/user-attachments/files/15821196/tnr-tmail-v0.11.3-patch4-16.ods)

Please help me fill the safari column: I do not have an IOS browser at hand...

**Comment by hoangdat** [comment]
[tnr-tmail-v0.11.3-patch4-16_include_safari.ods](https://github.com/user-attachments/files/15836069/tnr-tmail-v0.11.3-patch4-16_include_safari.ods)

**Comment by chibenwa** [comment]
Thanks a lot
