### ISSUE TITLE
Do non regression tests: v0.11.4003 (safari)

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#2939]
### Description

Complete this document:

[tnr-tmail-v0.11.4003.ods](https://github.com/user-attachments/files/15822513/tnr-tmail-v0.11.4003.ods)

**Comment by hoangdat** [comment]
Hi @chibenwa , what platform we can do it with v0.11.4003?

**Comment by chibenwa** [comment]
tmail.linagora.com

**Comment by hoangdat** [comment]
- [ ] Safari @hoangdat 
- [ ] Edge @hoangdat 
- [ ] Firefox
- [ ] Chrome

**Comment by chibenwa** [comment]
Is https://github.com/linagora/tmail-flutter/issues/2962 a regression?

**Comment by hoangdat** [comment]
> Is https://github.com/linagora/tmail-flutter/issues/2962 a regression?

No not test well on the previous version
