### ISSUE TITLE
Should have copy action to copy own email

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#2946]
### Desc:

![Image](https://github.com/linagora/tmail-flutter/assets/6462404/bc86569b-bbc1-4610-9a96-b85f6af75190)

### DoD:
- [ ] enable selectable for this text

**Comment by chibenwa** [comment]
Why a button>

Can't we keep the UI lean?

There is no "COPY" button on gmail.

I think just being able to "copy text should be enough, no?

**Comment by hoangdat** [comment]
Maybe we should support selection to copy text
