### ISSUE TITLE
Empty view for folder when no message in folder

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#2947]
### Desc:
- When open a folder which does not have any email
- Current

![Image](https://github.com/linagora/tmail-flutter/assets/6462404/3837e2f3-0cad-42a7-a601-d354cb9a24b7)

### DoD:
- [ ] No filter, no search (empty folder) -> empty, create rule
- [ ] have filter, no search -> empty base on filter
- [ ] have search -> empty search result
- [ ] mobile vs web

**Comment by hoangdat** [comment]
@Bobpodvalnyi

**Comment by Bobpodvalnyi** [comment]
@hoangdat change to text: "There's nothing here yet"

**Comment by dieptran88** [comment]
My suggestion: "You do not have any messages here"

**Comment by hoangdat** [comment]
- No filter, no search (empty folder) -> empty, create rule 
- have filter, no search -> empty base on filter
- have filer, have search -> empty search result
- no filter, have search -> empty search result

**Comment by hoangdat** [comment]
Depend on #3073
