### ISSUE TITLE
[WEB] Double scroll bar in chrome composer

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#295]
### Description

```
% chromium -version
Chromium 80.0.3987.122 Arch Linux
```

https://user-images.githubusercontent.com/6928740/155925642-1f648953-8e83-458b-94ba-5f3b924c6111.mp4

### Expected result

I should have only one scroll bar.

**Comment by Arsnael** [comment]
And the black video strikes again!

**Comment by chibenwa** [comment]
![Capture d’écran de 2022-02-28 15-45-08](https://user-images.githubusercontent.com/6928740/155952271-bd4e8b77-d0a5-4ae5-bcaa-c8fae423c9bc.png)

**Comment by Kevinle2312** [comment]
Passed on CI platfrom
![image](https://user-images.githubusercontent.com/32490981/162147223-782cd828-2daf-464b-81ee-813da8147bef.png)
