### ISSUE TITLE
Remove Clean button, "Empty Trash/Spam now" banner and Filters  when there is no email in Spam/Trash folder

### ISSUE THREAD

**Issue by dieptran88** [linagora/tmail-flutter#2951]
### Desc: 
- When there is no email in Trash, Spam folder, remove:
   - Clean button at the folder menu 
   - Empty Trash/Spam now when open the folder
   - Remove/Disable  Filters, Select all message, Recover deleted messages button when open the folder:
  
![image](https://github.com/linagora/tmail-flutter/assets/68209176/a0cf030f-c787-4795-ba27-889da48fc00d)

**Comment by hoangdat** [comment]
- [x] [DONE] Add addition to remove unnecessary UI in #3013

**Comment by hoangdat** [comment]
hi @chibenwa , @Arsnael 
we still have the problem of inconsistency data for `Mailbox/get` `Email/query` and `Email/get`
1. For the case of `Trash`: `Mailbox/get` method response: `totalEmails = 4`


![Image](https://github.com/user-attachments/assets/1cf4ac10-08e8-4f0d-a80f-6f610a580773)


2. `Email/query` also return 4 ids, but `Email/get` responses 4 ids in `notFound`


![Image](https://github.com/user-attachments/assets/faa37ee7-ccf2-48ad-b1c9-9277114061e1)

**Comment by Arsnael** [comment]
Environment? Platform? User? 

Maybe an inconsistency between the email query view and the email table but it's hard to go to check if you don't give us a minimum of details to where we can look :)

**Comment by hoangdat** [comment]
- Environment: Prod of linagora - it happens in @dieptran88 and some QA guys

**Comment by hoangdat** [comment]
hi @Arsnael please help us to take a look on it https://github.com/linagora/tmail-flutter/issues/2951#issuecomment-2232342649
Env: tmail.linagora.com

**Comment by Arsnael** [comment]
Probably a task to run to fix inconsistencies... probably a mix of quota recomputation and emailqueryview

This is prod as well, and running such tasks are heavy on the system. I am not keen on taking such responsibility for a wrong mail counter sorry
