### ISSUE TITLE
[WEB] Mailbox doesn't seem to be refreshed automatically

### ISSUE THREAD

**Issue by Buffer0117** [linagora/tmail-flutter#2963]
### Description

When using the web front, I have to manually click the refresh button in order to fetch new mails.

### Expected result

Current folder, at least, could be refreshed every few minutes (maybe a user setting ?) - or if possible updated by the server upon new mail arrival.

### Current behavior

Have to manually ask for a refresh to fetch new mails.

#### Reproduction Steps

1. Connect on Tmail web
2. Send an email to your address
3. Wait few minutes
4. Click the refresh button

### Acceptance criteria

- Do not click the refresh button to see new mail appearing

### Context

Version 125.0.6422.112 (Official Build) snap (64-bit)
Ubuntu 24.04 lts
Tmail 0.11.4

**Comment by Buffer0117** [comment]
When browser notifications are on there is no issue

**Comment by hoangdat** [comment]
Turned on notification permission. It works well. Don't hesitate to open other tickets if you have with notification or anything else.
