### ISSUE TITLE
Poor network in the train take me to login page

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#2965]
### Description

![image](https://github.com/linagora/tmail-flutter/assets/6928740/e3ffdf69-703b-4f76-a2d2-44c346605996)

Why do I end up in basic auth page?

This server do not offer basic auth.

How to reproduce? Take a train between Lyon and Paris.

Expectations: correct error handling.

**Comment by hoangdat** [comment]
> Why do I end up in basic auth page?

Fallback of error response in `web finger` request

- [ ] prevent redirect to `/login` route in `ConnectionError`

**Comment by hoangdat** [comment]
- [ ] prevent go to `login` route in `Connection Error`

**Comment by chibenwa** [comment]
> We don't know which server have OIDC or not.

It has! It is https://tmail.linagora.com

**Comment by hoangdat** [comment]
- [ ] configuration `auth_type` to prevent `basic auth` view

**Comment by chibenwa** [comment]
Conclusion for now:

 - Handle 404 on webfinger endpoint as "OIDC is not supported, fallback to basic auth"
 - Handle connection issue on the JMAP endpoint thus on webfinger as "Oups, network is unavailable!"
 
 See https://github.com/linagora/tmail-flutter/issues/2966 for possible implications onto the mobile offline mode.

**Comment by hoangdat** [comment]
Fixed with #2928, please deploy it to tmail linagora  to test

**Comment by hoangdat** [comment]
Design: https://www.figma.com/design/XqLqMINlZw09BdEHI8yLb9/Teammail---1.1?node-id=3193-38399&t=0yUaLAgBJugDYXke-4
