### ISSUE TITLE
[Story] As a user, I want to change the language in web mail 

### ISSUE THREAD

**Issue by dieptran88** [linagora/tmail-flutter#297]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC

* TODO: {link}

## Definition

- Given that I am a Tmail user 
- After log-in successfully to the Tmail web, I can see my avatar icon in top right of screen 
- When I click on this icon, I can see options: Log-out and My account 
- When I select option Log-out, I am redirected to log-in screen 
- When I select option My account, the screen My account will be opened 
- In this screen, I can see the field Language. The current language is display
- When I click on this filed, I can see a drop-down list with options: French, Vietnam, Russian, English 
- When I select one language then click button to Save, then the language of the web will be changed to the selected language. 

#### Note: Option 2: After log-in successfully to the Tmail web, user can see a language icon on top right of screen. I click on this icon and see 4 language options. I select one option and the language of the web will be changed to selected language.

EX: 
![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/9608f120-b69e-47d8-8146-630bc2e630c7)
[Back to Summary](#summary)

## Design ticket

https://ci.linagora.com/linagora/lgs/design/-/issues/146

[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

**Comment by hoangdat** [comment]
<img width="704" alt="image" src="https://user-images.githubusercontent.com/6462404/175893516-19c4724c-a4b4-49f0-a53c-154a103d1afa.png">


### DoD:
- only change language

**Comment by dab246** [comment]
2 HD
