### ISSUE TITLE
Changing the layout of main screen in mobile app

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#2975]
### Desc:

<img width="597" alt="image" src="https://github.com/linagora/tmail-flutter/assets/6462404/ab03ffe0-2d07-4a8f-ba64-3cb406d41080">

https://www.figma.com/design/XqLqMINlZw09BdEHI8yLb9/Teammail---1.1?node-id=2265-14436&t=GekEtKBgZZlFUpc0-4

### DoD:
- [ ] update screen with it (not include multiple account function)
- [ ] not include bottom bar navigator (Unsorted, Social, Newletters)

**Comment by hoangdat** [comment]
- pick from branch to our active branch

**Comment by chibenwa** [comment]
We do not have categories "usorted, social media, newsletter" nor is this feature described.

Maybe we shall update the design in order to remove this footer?

Otherwise great job for the design.

**Comment by hoangdat** [comment]
Good catch, we dont have it in function, we not include it in app
Cc @Bobpodvalnyi

**Comment by Bobpodvalnyi** [comment]
ok will update it, is that a blocker for you now?

**Comment by dab246** [comment]
@Bobpodvalnyi  What about `Selection` emails mode. It currently looks like this.



![Image](https://github.com/user-attachments/assets/fff8db4d-bef5-44ad-b8f6-cd8b46914c80)

**Comment by Bobpodvalnyi** [comment]
I made a new design for an e-mail list with selections and multiselects
We've gone over all the details with @hoangdat 
Please discuss with him
