### ISSUE TITLE
Be consistent in attachment size

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#2979]
### Description

![image](https://github.com/linagora/tmail-flutter/assets/6928740/e0e1bbee-d962-4ed6-98c6-96d8e816504d)

1000 for  1KB used in one place VS 1024 in another? Or rounding issue?

Either case it perturbs me to have 2 distinct values...

**Comment by hoangdat** [comment]
- [ ] unit test

**Comment by dab246** [comment]
### This issue only occurs on version `0.11.4`. It is fixed on `0.13.1`.

- Version 0.11.4:

<img width="1437" alt="Screenshot 2024-08-30 at 12 00 33" src="https://github.com/user-attachments/assets/2f9cb9e4-0596-4ad8-a61c-02d28911a019">

- Version 0.13.1:

<img width="1437" alt="Screenshot 2024-08-30 at 12 01 02" src="https://github.com/user-attachments/assets/67c62bcc-6323-4a75-aa9c-ddbec6e2b317">

### Standardize Unit 

- Present: `1MB = 1024KB`
