### ISSUE TITLE
end of mail is truncated

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#298]
### Desc:

When I scroll to the end of mail

<img width="1792" alt="Screen Shot 2022-03-01 at 09 41 53" src="https://user-images.githubusercontent.com/6462404/156094970-c15f42ca-e337-4c55-9b2b-8a9f92178b5e.png">
<img width="1792" alt="Screen Shot 2022-03-01 at 09 42 05" src="https://user-images.githubusercontent.com/6462404/156095040-1742d13c-b308-4d90-a191-83e86d28d237.png">

**Comment by chibenwa** [comment]
I do think this is the double scroll bar: scroll near the top of the mail you will see ;-)
