### ISSUE TITLE
Web -  When I select a folder then refresh, It shows the previous folder's mail list

### ISSUE THREAD

**Issue by dieptran88** [linagora/tmail-flutter#2992]
### Description
1. I select a folder A and see the email list of the folder A
2. I select another folder B and see the mail list of folder B
3. I refresh page = > it goes back to mail list of folder A 
### Expected result
=> When I refresh a folder, it should show the latest email list of that folder 
### Current behavior

[screen-capture - 2024-07-09T140532.932.webm](https://github.com/linagora/tmail-flutter/assets/68209176/6009f642-261c-4b2e-b22c-a16e79b6ad53)

### Context

Devices, OS

### Additional information

frequency, log files,...

**Comment by hoangdat** [comment]
- [ ] URL link is not update well when we switch mailbox

**Comment by hoangdat** [comment]
@hoangdat verify with #3073

**Comment by hoangdat** [comment]
fixed: v0.13.0
