### ISSUE TITLE
CI for Tmail flutter

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#30]
Repo: https://github.com/linagora/tmail-flutter
Flutter 2.x

### Desc:
Config bitrise to run CI for Tmail-flutter with 2 triggers:

- Push to `main` branch

- Pull request to `main` branch

**Comment by chibenwa** [comment]
You will have this done by Tung DevOps?

**Comment by hoangdat** [comment]
yes, I am trying to schedule this task after we re-config the CD for LinShare app

**Comment by tnstung** [comment]
I've got this issue.

**Comment by tnstung** [comment]
@hoangdat please grant me admin rights on the repo https://github.com/linagora/tmail-flutter

**Comment by hoangdat** [comment]
> @hoangdat please grant me admin rights on the repo https://github.com/linagora/tmail-flutter

done

**Comment by tnstung** [comment]
Done
