### ISSUE TITLE
[MU] SMime signature validation

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#3023]
### Description

Have a pas/fail visualization regarding smime signature.

Requested for customer.

SMIME signature is to be validated on the backend side, and accessible to the frontend through the following headers: 

```
X-SMIME-Status: Good signature
X-SMIME-Status: Bad signature
X-SMIME-Status: Not signed
```

 - if `X-SMIME-Status: Not signed` or there is no header do nothing, like today

 - if `X-SMIME-Status: Good signature` when I open the mail a good signature icon is displayed next to the email.
 
 When I hover over it, a flyover messsage reads `The authenticity of this message had been verified with SMime signature` 

![Screenshot from 2024-07-22 10-19-52](https://github.com/user-attachments/assets/46cffc47-6201-4733-aed2-248fa8b7699f)

 - if `X-SMIME-Status: Bad signature` when I open the mail a bad signature icon is displayed next to the email.
 
 When I hover over it, a flyover messsage reads `This message failed SMime signature verification.` 

![Screenshot from 2024-07-22 10-22-51](https://github.com/user-attachments/assets/fc2dabff-678f-4ae5-b27f-c8aaaac625ec)

**Comment by chibenwa** [comment]
@hoangdat please plan work on this next sprint

**Comment by chibenwa** [comment]
CF https://ci.linagora.com/linagora/lgs/twp/mail-gov-mauritius/-/issues/30

**Comment by hoangdat** [comment]
@Bobpodvalnyi please help us on the icon for this function. Thanks

**Comment by hoangdat** [comment]
@Bobpodvalnyi please help us

**Comment by chibenwa** [comment]
After today discussion with @guimard without this feature LNG cannot be paied for the customer projet: it is mandated!

**Comment by Bobpodvalnyi** [comment]
https://www.figma.com/design/XqLqMINlZw09BdEHI8yLb9/Teammail---1.1?node-id=2956-1011&t=rrvBVF6LhV32w9QH-0 @hoangdat @chibenwa

**Comment by chibenwa** [comment]
Simple and efficient. Thanks!

**Comment by hoangdat** [comment]
@Arsnael @chibenwa One question: any problem if man-in-the-middle can change this header?

**Comment by Arsnael** [comment]
This header is set by the backend when it receives the email and treats it. If man in the middle sets it up it would be overriden when treated by the back anyways, and probably would fail because it has been tempered in the first place

**Comment by chibenwa** [comment]
Please document that the header shall be removed as part of the delivery chain.


@Arsnael we can create a tmail backend ticket to remove this header in all default confs, deployments. Can you take care of it?
Thanks!

**Comment by Arsnael** [comment]
> Please document that the header shall be removed as part of the delivery chain.

Well except if you use the smime verify signature mailet in the chain like for MU, correct?

**Comment by chibenwa** [comment]
No we should always unset it now when using tmail front so pkease remove everywhere

**Comment by Arsnael** [comment]
=> https://github.com/linagora/james-project/issues/5239

**Comment by Arsnael** [comment]
FYI work has been done for this on the backend and the smime check signature mailet has been deployed on tmail.linagora.com with the CA cert from MU.

@hoangdat I guess your team can start working on this now, and that you could test this with on-commit env? Or do you need it deployed somewhere else?

**Comment by Arsnael** [comment]
I see your team worked on that but it's not been merged into master branch, thus I can't check with the mail I tested with from MU on the oncommit env

**Comment by Arsnael** [comment]
@hoangdat @chibenwa I tried to do a little recording with tmail front (canary) and smime check signature configured with MU CA on our prod

https://github.com/user-attachments/assets/545a44ed-c775-421c-af5a-22088c593e4a

Would that be enough?

**Comment by chibenwa** [comment]
Yes indeed it is!
