### ISSUE TITLE
[Bug] Cannot attach files or inline images

### ISSUE THREAD

**Issue by tprudentova** [linagora/tmail-flutter#3028]
0.12.1 tested on Android, IOS, Firefox, Opera; mail.stg.lin-saas.com

1. Open composer 
2. Try to attach a file or an image  
3. Error

https://github.com/user-attachments/assets/f60be864-0971-4868-acf5-7131fd75c5b2

https://github.com/user-attachments/assets/66a6a5b6-e307-41b9-940d-6791d0b0d482

**Comment by hoangdat** [comment]
hi @ducnm0711 , please check this problem

<img width="707" alt="image" src="https://github.com/user-attachments/assets/a89898f9-569c-4b88-922c-a64fae4aa8da">

**Comment by chibenwa** [comment]
Likely Twake mail do not have the rights onto the `jmap-upload` bucket.

**Comment by ducnm0711** [comment]
where is the config parameters for it? Can we make it a folder "jmap upload"  inside tmail bucket?

**Comment by chibenwa** [comment]
> Can we make it a folder "jmap upload" inside tmail primary bucket?

Sure we can use bucket prefix for that: https://james.staged.apache.org/james-project/3.9.0/servers/distributed/configure/blobstore.html

objectstorage.bucketPrefix
	

Bucket is a concept in James and similar to Containers in Swift or Buckets in AWS S3. BucketPrefix is the prefix of bucket names in James BlobStore

**Comment by ducnm0711** [comment]
Done. 
```
# blob.properties
objectstorage.namespace=twake-workplace-mail
objectstorage.bucketPrefix=twake-workplace-mail-

$ aws s3 ls
2024-06-07 18:15:22 twake-workplace-chat
2024-06-07 18:15:22 twake-workplace-drive
2024-06-07 18:15:22 twake-workplace-mail
2024-06-07 18:15:22 twake-workplace-mail-jmap-uploads
2024-06-07 18:15:22 twake-workplace-zammad
```
![image](https://github.com/user-attachments/assets/8960b49d-3a87-468c-8892-550299018a18)
