### ISSUE TITLE
[Dev] Support SMime signature validation

### ISSUE THREAD

**Issue by dab246** [linagora/tmail-flutter#3031]
## Descriptions

- Issue: #3023

## DoD

 - [ ] Add a `good/bad` signature icon is displayed next to the email
 - [ ] Show tooltip message when hover icon:

    - If `X-SMIME-Status: Good signature` tooltip message is  `The authenticity of this message had been verified with SMime signature`
    - If `X-SMIME-Status: Bad signature` tooltip message is  `This message failed SMime signature verification.`

- [ ] Check on offline mode

## Technical

- Get `X-SMIME-Status` in `headers` property of email. With `name = X-SMIME-Status`.
- Create enum `SMimeSigantureStatus`:

```dart
enum SMimeSigantureStatus {
   goodSignature,
   badSignature,
   notSigned
}

```
- In `EmailExtension` add:

```dart
static const String smimeSignatureStatusHeaderName = 'X-SMIME-Status';


SMimeSigantureStatus get smimeSignatureStatus {
    final smimeStatus = headers?.firstWhereOrNull((header) => header.name == smimeSignatureStatusHeaderName);
    if (smimeStatus == 'Good signature') {
       return SMimeSigantureStatus.goodSignature;
    } else  if (smimeStatus == 'Bad signature') {
       return SMimeSigantureStatus.badSignature;
    } else {
      return SMimeSigantureStatus.notSigned;
    }
}
```

- Add `good/bad` siganture icon in `InformationSenderAndReceiverBuilder` widget

**Comment by hoangdat** [comment]
- [ ] unit test
- [ ] widget test
