### ISSUE TITLE
[Improvement] Don't suggest saving email to Drafts if it's just been saved

### ISSUE THREAD

**Issue by tprudentova** [linagora/tmail-flutter#3034]
0.12.1 tested on Android, Firefox, Safari, Opera; mail.stg.lin-saas.com

1. Open composer, input some info
2. Click Save as draft
3. Close the composer
4. You see a suggestion to save an email to drafts again

Suggestion: if the email has been manually saved to drafts and no changes have been made after that, we don't show this pop-up

https://github.com/user-attachments/assets/542cf8a2-2573-43b4-a701-208034e24fd0

**Comment by hoangdat** [comment]
Properties: Content, Subject, To, Cc, Bcc, Attachment, Identity, Read Receipt -> hashed 

### Case 1: Open new composer -> Save draft but not close -> close 
Saved -> Email -> hashed 1 (selected properties)
Close -> Email -> hashed 2 

### Case 2: Open Draft 
- Hash if argument have Email 
- Close -> Email -> hashed 2
