### ISSUE TITLE
[Bug] When I save an email to drafts, the "From" field isn't saved

### ISSUE THREAD

**Issue by tprudentova** [linagora/tmail-flutter#3035]
0.12.1 tested on Android, Firefox, Safari, Opera; mail.stg.lin-saas.com

1. Open composer 
2. Change your identity in the field From
3. Save as draft
4. Open the draft 
5. The default identity is used

Expectation: The "From" field is also saved

https://github.com/user-attachments/assets/c4c1b12d-0180-40ac-8a6a-a3ed7899741b

**Comment by chibenwa** [comment]
Good catch, it's actually a "protocol bug" because "from" field in the composer is derived from **identityId**  that is not persisted onto the draft (because there is no field for it.

@hoangdat the best fir for it is to rely on a header `X-JMAP-Identity` to save the identityId onto the draft.

Do not forget to remove `X-JMAP-Identity`  before sending.

**Comment by chibenwa** [comment]
Related too https://github.com/linagora/tmail-flutter/issues/new?assignees=&labels=bug&projects=&template=bug-report.md&title=

**Comment by hoangdat** [comment]
### DoD:

### Save Draft 
- [ ] store identity Id -> `X-JMAP-Identity` whenever save draft
- [ ] remove CSS of signature button when save draft 

### Open Draft 
- [ ] when open draft -> get identity Id -> get content of identity 
  - fill `From`
  - add CSS
  - if `X-JMAP-Identity` null, -> use default identity  
  - if `X-JMAP-Identity` not null but this identity id is not existed, use default identity 
 
### Send Mail 
- [ ] remove `X-JMAP-Identity` before send

**Comment by tddang-linagora** [comment]
>Do not forget to remove `X-JMAP-Identity` before sending.

What if I edit this draft and send email from another mail client, says Thunderbird? This `remove` action is not guaranteed?

**Comment by chibenwa** [comment]
True.

However headers are not directly visible. The id of the identity is leaked which is not ideal but not too bad either.

Imo acceptable.
