### ISSUE TITLE
[Story] Read receipt

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#304]
# Summary

 - As a sender I want to ask the receipient to send me a read receipt.
 - As a receiver I want to send a read receipt when asked by the sender (confirmation button)
 - As a receiver once a read receipt is sent I should not be prompted again
 
# UX

 - Button on the mail to ask for read receipt in the composer (true/false)
 - In email display if a read receipt is asked and not yet sent, then offer the client to send it / ignore it

# Technical details

 - Use RFC-9007 to send MDNs cf https://www.rfc-editor.org/rfc/rfc9007.html
 - Use the `$mdnsent` to know if a read receipt is sent or not
 - `Disposition-Notification-To: Sender <sender@domain.tld>` can be added to sent email to ask to send read receipts
 - If a received email (not in sent mailbox) has `Disposition-Notification-To` header and no `$mdnsent` keyword then prompt to send read receipts

# Common traps

Do not offer to send read receipt for email in my Sent box (NOT like OpenPaaS)

**Comment by chibenwa** [comment]
All

**Comment by dieptran88** [comment]
Is this only applicable for users in same domain @chibenwa  ? 
For e.g  As a Tmail user I sent email to Gmail user with read receipt request but when Gmail user open his email I cannot receive the notification email

**Comment by dab246** [comment]
@chibenwa  
Enable/Disable `Always request read receipts with outgoing messages ` in settings screen is only saved on `client` side. Because I read the documentation about `mdn` in [rfc9007](https://www.rfc-editor.org/rfc/rfc9007.html) but I didn't find any handling on `jmap` or `api` for this change. If possible please send me the document. Thanks!

**Comment by chibenwa** [comment]
There is currently no standard support for this feature, which is a niche use case.

I would not implement it, if already implemented that's perfectly fine to store it in the device.

**Comment by dab246** [comment]
oke. thanks you
