### ISSUE TITLE
[PublicAsset][Dev] Create data handler backbone with PublicAsset methods

### ISSUE THREAD

**Issue by tddang-linagora** [linagora/tmail-flutter#3040]
## Description
This data handler will connect "PublicAsset/get" and "PublicAsset/set" methods from the back-end to Flutter client, in order to further implement public link image in Twake Mail signature.

## API/DataSource/Repository abstraction
```dart
// PublicAsset/get
Future<List<PublicAsset>> getPublicAssetFromIds(List<Id> publicAssetIds);

// PublicAsset/set destroy
Future<void> deletePublicAssets(List<Id> publicAssetIds);

// PublicAsset/set create
Future<void> createPublicAssets(Map<BlobId, List<IdentityId>> blobWithIdentityIds);

// PublicAsset/set update
enum PublicAssetUpdateAction {add, remove}
Future<void> updatePublicAssets(Map<Id, Map<IdentityId, PublicAssetUpdateAction>> publicAssetToUpdate);
```

## DoD

- [x] Implement "PublicAsset/get" and "PublicAsset/set" methods and write unit tests: https://github.com/linagora/jmap-dart-client/pull/91
- [x] Create API, data source & repository classes, and write unit tests: https://github.com/linagora/tmail-flutter/pull/3062
- [ ] ~Create GetPublicAssetInteractor and write unit tests~

**Comment by tddang-linagora** [comment]
Note: In API - create, combine create identity & create public asset into 1 request

**Comment by tddang-linagora** [comment]
Note: In API - create, if user paste public asset from existing identity into creating new identity, create identity & get public asset into 1 request and check for result of get public asset. If pasted public asset exist, call `update` public asset, else call `create` public asset

**Comment by hoangdat** [comment]
- [ ] Describe abstraction of `PublicAssetRepository`

**Comment by hoangdat** [comment]
- [ ] dont touch to old logic of identity
