### ISSUE TITLE
[PublicAsset][Dev] Handle edit existing signature, converting base64 images to public links

### ISSUE THREAD

**Issue by tddang-linagora** [linagora/tmail-flutter#3041]
## Description
Currently, image in signature is of base64 form. When open existing signature and that signature has image, show user a warning dialog, telling them if we can update current image form to public link. 

If they agree, upload all current base64 image to blob and register those image with PublicAsset. If not, warn the user about the incompatibility issue and move on.

## DoD

- [ ] On Identity editor opened, scan signature content for base64 image tags. If none exists, skip all steps below
- [ ] Show dialog warning user about current situation. If user deny action, skip all steps below
- [ ] Upload all base64 images to blob and register to PublicAsset
- [ ] integration test ??? (testcontainer/Patrol: how to provision identity???)

**Comment by hoangdat** [comment]
- `create` PublicAsset with identity id
- `save` identity

**Comment by hoangdat** [comment]
Cc: @Bobpodvalnyi No warning display... Need to find other way to do

**Comment by tddang-linagora** [comment]
>how to upload base64 -> uploadUrl

Currently web upload file using `Uint8List` format. The below code snippet is enough.
```dart
import 'dart:convert';

Uint8List base64ToUint8List(String base64String) {
  return base64.decode(base64String);
}
```

On mobile though, `File` is used, so a temporary `File` must be created.

```dart
import 'dart:convert';
import 'dart:core';
import 'package:path_provider/path_provider.dart';
import 'package:uuid/uuid.dart';

Future<File?> imageResourceDataToFile(String imageResourceData) async {
  // Get image extension
  final mimeType = RegExp("(?<=data:)(.*)(?=;base64,)").stringMatch(imageResourceData);
  if (mimeType == null || !mimeType.contains('image')) return null;
  final imageExtension = mimeType.split('/').last;
  final imageName = const Uuid().v4();

  // Get image bytes
  final base64String = RegExp(r"(?<=;base64,).*$").stringMatch(imageResourceData);
  if (base64String == null) return null;
  final bytes = base64Decode(base64String);
  
  // Create file
  final tempDirectory = await getTemporaryDirectory();
  final filePath = '${tempDirectory.path}/$imageName.$imageExtension';
  final file = File(filePath);
  await file.writeAsBytes(bytes);
  return file;
}
```

**Comment by hoangdat** [comment]
Hi @chibenwa , how we will support user to update the old signature (which have base64 image)? How to notice user about that?
