### ISSUE TITLE
[PublicAsset][Dev]Handle create new and edit newly created signature (no existing base64 image)

### ISSUE THREAD

**Issue by tddang-linagora** [linagora/tmail-flutter#3042]
## Description
When creating new identity and pick image, all images will be registered to PublicAsset and, instead of base64 source, show as a image tag with https url source.

## DoD

- [x] When open existing identity editor, and there's no base64 images, and there's existing PublicAsset images, save PublicAsset id to **OLD** temporary PublicAsset collection (TPC)
- [x] When picking image, after compressed, upload those images to blob, call `PublicAsset/set create` (with current identity if action is "edit identity"), save those PublicAsset id to **NEW** TPC
- [x] When `Cancel` button is tapped, call `PublicAsset/set destroy` on all PublicAsset inside **NEW** TPC
- [x] When `Save` button is tapped, scan all image tags in identity content
  - [x] Create new identity if needed (create identity action, not edit)
  - [x] If any of the PublicAsset inside **OLD** TPC is missing, call `PublicAsset/set update` and remove PublicAsset reference out of current identity
  - [x] If any of the PublicAsset inside **NEW** TPC is missing, call `PublicAsset/set destroy`
  - [x] If any of the PublicAsset doesn't exist in any TPC, meaning user paste that asset from other Identity, call `PublicAsset/set update` with current Identity id
  - [x] Call `PublicAsset/set update` on all PublicAsset inside **NEW** TPC if action is "create new identity"

**Comment by hoangdat** [comment]
- [ ] prevent `back` or `reload` while editing identity

**Comment by tddang-linagora** [comment]
```js
saveIdentity(
  IdentityId? identityId,
  String signatureContent,
  List<Id> oldPublicAssetIds,
  List<Id> newPublicAssetIds,
) {
  if (identityId == null) { // create new identity
    final identity = createIdentityWithEmptyContent();
    identityId = identity.identityId;
  }
  final List<Id> tobeReferenceAdded = [];
  final List<Id> tobeReferenceRemoved = [];
  final List<Id> tobeDestroy = [];

  final List<Id> publicAssetIdsInSignatureContent = getPublicAssetFromContent(signatureContent);

  // Handle OLD assets
  final List<Id> missingOldPublicAssetIds = oldPublicAssetIds.notIncludedIn(publicAssetIdsInSignatureContent);
  if (missingOldPublicAssetIds.isNotEmpty) {
    final List<PublicAsset> publicAssets = getPublicAssetsFromIds(missingOldPublicAssetIds);
    tobeReferenceRemoved.add(publicAssetIdsOtherIdentitiesAreUsing(publicAssets));
    tobeDestroy.add(publicAssetIdsOnlyThisIdentityUse(publicAssets));
  }

  // Handle NEW assets
  final missingNewPublicAssetIds = newPublicAssetIds.notIncludedIn(publicAssetIdsInSignatureContent);
  if (missingNewPublicAssetIds.isNotEmpty) {
    tobeDestroy.add(missingNewPublicAssetIds);
  }

  // Handle Pasted assets
  final pastedPublicAssetIds = publicAssetIdsInSignatureContent.notIncludedInBoth(
    oldPublicAssetIds,
    newPublicAssetIds,
  );
  if (pastedPublicAssetIds.isNotEmpty) {
    tobeReferenceAdded.add(pastedPublicAssetIds);
  }

  // PublicAsset set combine
  updatePublicAssetWithOptions(tobeReferenceAdded, tobeReferenceRemoved, tobeDestroy, identityId);
}
```

**Comment by tddang-linagora** [comment]
Since client is not supposed to call `PublicAsset/set destroy` on existing PublicAsset anymore (see https://github.com/linagora/tmail-flutter/issues/3043#issuecomment-2268621035), the logic is updated.
