### ISSUE TITLE
[Suggestion] Maybe we shouldn't allow creating rules with no actions

### ISSUE THREAD

**Issue by tprudentova** [linagora/tmail-flutter#3051]
Currently the user can create a rule with no actions, but in this case the rule just doesn't do anything, no? Maybe we should make this field mandatory as well

https://github.com/user-attachments/assets/419c4c03-5927-441d-8179-731ddcfb8218

**Comment by chibenwa** [comment]
Adding this into backend to as we can easily implenet this check ourselves too.

**Comment by Arsnael** [comment]
![Image](https://github.com/user-attachments/assets/9c694133-bfeb-40e3-b914-f04b95a93731)

Been checking what the front sent exactly... Technically... the back receive an action object with just MailboxIds list empty and booleans to false... So yes in terms of action it does nothing, but in terms of the backend... the action technically is defined IMO. 

The frontend definitely could do better here.

But sure will ad an extra check on the back, better be safe than sorry?

**Comment by chibenwa** [comment]
No lets keep thid easy imo, and handle front
