### ISSUE TITLE
[Story] As a user, I want to drag and drop file (by mouse) to add attachment when composing email on Tmail web 

### ISSUE THREAD

**Issue by dieptran88** [linagora/tmail-flutter#307]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC

- Given that I have logged in successfully to Tmail in web browser
- I click on floating Create email button, a new email composer is opened.
- Now when I drag a file file from my computer then on the body part of email composer, I can see an overlay saying "Drop files here"
- If I drop file there, it will become an attachment   
- I can drag and drop multiple files to the email composer at once.

## Definition

TODO

[Back to Summary](#summary)

## Screenshots

![Screenshot from 2022-03-04 19-53-22.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/f1d3db7b-fb23-40b6-bdec-fe3fdf0ded24)
![Screenshot from 2022-03-04 19-43-31.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/aefab5ed-6380-4258-8564-825dd5137fd8)

## Design ticket 
https://ci.linagora.com/linagora/lgs/design/-/issues/151

[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

**Comment by hoangdat** [comment]
I haven't seen this design ticket for this story.

**Comment by chibenwa** [comment]
IMO while cool this should be a `nice to have`. I would not make this a critical UX change. It should IMO not be on the critical path.

**Comment by chibenwa** [comment]
@dieptran88 @hoangdat  what do you think about applying Moscow on epic/stories/tickets?

We can create labels `must` `could` `should` `wont` it will help better prioritize stuff IMO...

**Comment by hoangdat** [comment]
duplicated with #2118
