### ISSUE TITLE
[Bug] Cannot mark a folder as "read"

### ISSUE THREAD

**Issue by tprudentova** [linagora/tmail-flutter#3077]
0.12.1 tested on Android; tmail.linagora.com

1. Mark some emails as unread if necessary 
2. Long tap the folder in the folder tree 
3. Select Mark as read 
4. You see a terrifying warning. The folder isn't marked as read 

https://github.com/user-attachments/assets/8a94427b-3ba8-4da5-a633-3f8614e903d7

**Comment by tddang-linagora** [comment]
Will be fixed after this PR https://github.com/linagora/tmail-flutter/pull/3129 is merged

**Comment by dab246** [comment]
## Root cause

- Same with #3129 

## Reproduced



https://github.com/user-attachments/assets/de01ab91-ec72-4fc9-aef4-e94cc85c975b
