### ISSUE TITLE
[Bug] [MOBILE] Need to click Empty trash twice to empty it

### ISSUE THREAD

**Issue by tprudentova** [linagora/tmail-flutter#3080]
0.12.1, tested on Android; mail.stg.lin-saas.com

1. Move an email to Trash, empty Trash
2. Move another email to Trash
3. Go to Trash -> Click Empty trash -> Delete all 
4. Nothing happens. You need to do the same thing again for the Trash to be emptied

https://github.com/user-attachments/assets/bc6180d3-5316-4a5c-b466-ba690e4655bd

**Comment by dab246** [comment]
## Reproduced



https://github.com/user-attachments/assets/0c994ced-f9fc-4e43-a8a7-192668658d16


## Root cause & Resolved

- Same with #3129
