### ISSUE TITLE
[Bug] [MOBILE] No autosuggestions for email addresses in search bar

### ISSUE THREAD

**Issue by tprudentova** [linagora/tmail-flutter#3087]
0.12.1, tested on Android; mail.stg.lin-saas.com

1. Click on the search bar 
2. Enter first 3 letters of an email address with whom you've had history of communication 
3. No suggestions are shown 

Expectation: the way it's done in web 

<img width="1277" alt="Screenshot 2024-08-14 at 16 49 35" src="https://github.com/user-attachments/assets/7227b1a8-b1ac-4528-83a7-6d20f6b11df6">

![photo_2024-08-14_16-50-21](https://github.com/user-attachments/assets/e6fb42c7-1e7d-4439-bfb2-99edd1257aac)

**Comment by dab246** [comment]
- [ ] Apply new design

Web:



![Image](https://github.com/user-attachments/assets/b591489f-805a-4ebf-b9c5-11cc9e84a76f)



Mobile:




![Image](https://github.com/user-attachments/assets/22040101-0e29-43d8-b1bd-7f01004576c8)
