### ISSUE TITLE
[Bug] Search -> Custom date. The ending date isn't included in the search

### ISSUE THREAD

**Issue by tprudentova** [linagora/tmail-flutter#3088]
0.12.0, tested on Android, Safari, Firefox, Opera; mail.stg.lin-saas.com

1. Open advanced search filters 
2. Enter a custom date range "X to Y"
3. Search 
4. Letters from date Y aren't included in the search results 

Expectation: "Date X to Date Y" means Date X...Date Y, Date Y included

https://github.com/user-attachments/assets/e5cd10ca-ae12-4dcf-b0a7-af7c66730571

**Comment by hoangdat** [comment]
- [ ] start: 0h of selected start date local -> convert to UTC 
- [ ] end: 23.59 of selected end date + 1 -> convert to UTC 
- [ ] unit test
