### ISSUE TITLE
find solution to convert text to html

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#309]

**Comment by chibenwa** [comment]
https://github.com/linagora/tmail-flutter/pull/308#discussion_r820359716 

I'd prefer to rely on a library to do text => HTML because now we are vulnerable to HTML injections

:+1: to handle this in a separate issue

**Comment by chibenwa** [comment]
The issue is that if I use tags in my message then that won't display well (sanitized or not)

Consider I send this message

```
Hello bob,

To put things in blod with HTML just use the <b> tag.

Best regard

Your fiend Alice.
```

How will this render? Will bob still be able to read the HTML tag Alice suggest him? Will all the stuff be in bold?

**Comment by chibenwa** [comment]
How to handle this?

Likely on the middle term, it will be OK. Anything allowing to build HTML would be ok.

**Comment by chibenwa** [comment]
Still not.

TMail still renders `text/plain` as `text/html`.

CF 

![Screenshot from 2023-04-05 09-56-23](https://user-images.githubusercontent.com/6928740/229969589-1c914e27-2201-4b4e-b6e5-bd8bf7867062.png)
![Screenshot from 2023-04-05 09-56-20](https://user-images.githubusercontent.com/6928740/229969598-0f26fbf0-dc2e-4cab-984d-85f4c743ca22.png)
