### ISSUE TITLE
[PublicAsset] Handle pasting base64 image to identity editor

### ISSUE THREAD

**Issue by tddang-linagora** [linagora/tmail-flutter#3095]
## Description
With PublicAsset feature up and running, we should stop our support for base64 image type in signature. For any user using Twake Mail that has PublicAsset capability supported, Twake Mail will stop showing any base64 image that is pasted to its signature editor.

## DoDs

- [ ] ~Write a function to verify if the image html's string is of http/https source or of base64 source~
- [ ] Trigger the transform event on paste
- [ ] Bonus: Trigger the transform event on drop text

**Comment by chibenwa** [comment]
We need to:
 - Still show well base64 in existing emails
 - When creating email, pasting base64 we need to upload an inlined attachment
 - When creating signature, pasting base64 we need to upload a public asset and reference it.
