### ISSUE TITLE
Handle public asset upload failure when overquota

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#3096]
### Description

Record a video/screenshot of what happens when I create a public asset but runs out of quota for public assets (too many public assets).

Expecation:
 - Decent error message
 - Remediation
 
 Idem for too big public asset (400MB ?)

Idem think of other possible edge cases.

**Comment by hoangdat** [comment]
- [ ] HEIC photo -> falied 
- [x] 400Mb 
- [ ] ....

**Comment by hoangdat** [comment]
Hi @Arsnael , @chibenwa 
As I understand, if user reach quota exceeded when creating public asset, back-end wil automatically cleanup the old ones then create new public asset. Am I right?

```json
{
  "sessionState": "2c9f1b12-b35a-43e6-9af2-0106fb53a943",
  "methodResponses": [
    [
      "PublicAsset/set",
      {
        "accountId": "4e4eb883b9006e62091bec3830c47b20d4300749898e1b41f98b871028c394ad",
        "oldState": "2c9f1b12-b35a-43e6-9af2-0106fb53a943",
        "newState": "2c9f1b12-b35a-43e6-9af2-0106fb53a943",
        "notCreated": {
          "a79ae4b0-5e9c-11ef-8503-79838c6b4fb5": {
            "type": "invalidArguments",
            "description": "Exceeding public asset quota limit"
          }
        }
      },
      "c0"
    ]
  ]
}
```

**Comment by chibenwa** [comment]
```
          "a79ae4b0-5e9c-11ef-8503-79838c6b4fb5": {
            "type": "invalidArguments",
            "description": "Exceeding public asset quota limit"
          }
```

`overQuota` as a type would feel better?

**Comment by hoangdat** [comment]
> overQuota as a type would feel better?

Yes, if we have specific error type, way better for not only this also for all other APIs :))

**Comment by chibenwa** [comment]
https://github.com/linagora/james-project/issues/5243
