### ISSUE TITLE
Test to Release new version v0.13.0 (sprint #26)

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#3101]
### Manual test 
- [ ] chrome
- [ ] firefox
- [ ] edge
- [ ] safari
- [ ] android
- [ ] ios

[tnr-tmail-sprint26.ods](https://github.com/user-attachments/files/16688957/tnr-tmail-sprint26.ods)

**Comment by hoangdat** [comment]
@hoangdat 
- [ ] firefox
- [ ] android
- [ ] chrome

**Comment by hoangdat** [comment]
@tddang-linagora 
- [ ] edge
- [ ] safari

**Comment by hoangdat** [comment]
@dab246 
- [ ] chrome
- [ ] iOS

**Comment by tddang-linagora** [comment]
Selected Identity does not saved on draft

https://github.com/user-attachments/assets/d04add42-5492-426c-860e-ed7f87ef5a21

**Comment by dab246** [comment]
- [ ] `PublicAsset/set` method always call when close identity creator view


https://github.com/user-attachments/assets/52ffd630-a5ee-448b-8ce7-986d14b5068c



- [ ] Checkbox `Set as default identity` not selected when edit identity

https://github.com/user-attachments/assets/52669977-c159-4e8d-91b3-5090f5ef4b54

- [ ] `PublicAsset/set` throw error `Exceeding public asset quota limit` when perform more times

```
upload multiple images  -> delete all -> upload images
```

**Comment by tddang-linagora** [comment]
>`PublicAsset/set` method always call when close identity creator view

- https://github.com/linagora/tmail-flutter/pull/3105

**Comment by dab246** [comment]
1. Tested IOS:

- [ ] The signature message input box is too big.


https://github.com/user-attachments/assets/3bdfee22-06a0-421a-a3a9-d586acbe0a91

**Comment by tddang-linagora** [comment]
>The signature message input box is too big.

The content contains too many new lines, else I can't reproduce it

**Comment by dab246** [comment]
> > The signature message input box is too big.
> 
> The content contains too many new lines, else I can't reproduce it

It is very easy to reproduce. Please see below video.


https://github.com/user-attachments/assets/dd78f66c-1a6b-45dd-a747-3503a4545e1c
