### ISSUE TITLE
[Bug] [MOBILE] Cannot empty Spam

### ISSUE THREAD

**Issue by tprudentova** [linagora/tmail-flutter#3113]
0.13.0, mail.stg.lin-saas.com, tested on Android

1. Mark an email as spam 
2. Go to Spam  
3. Click Delete spam emails -> Delete all 
4. Error

https://github.com/user-attachments/assets/0b19f282-21b9-46d1-90ac-63d2d875f555

**Comment by ddmytrenko8** [comment]
The same bug is reproducing on Ios
