### ISSUE TITLE
Audit Dev Enviroment for mail.lin-saas.dev

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#3120]
### Desc:
- UPN platform was off
- DevOps team deployed a new platform in: mail.lin-saas.dev 

### DoD:
- verify this environment: mail.lin-saas.dev 
- find the way to keep this platform up-to-date (as UPN before): new BE release, provision data, ...

Cc: @Arsnael

**Comment by Arsnael** [comment]
@ducnm0711 Links and accesses to that env? 

Also regarding data, before we had a heavy provisioning but that was mostly for perf tests (that we keep on upn cluster)

Does tmail on that env points to its own db or does it share data with let's say twp staging for example?

**Comment by ducnm0711** [comment]
mail.lin-saas.dev has everything separated from stg env.

user: testuser01
pass: testuser01

01 --> 99

**Comment by Arsnael** [comment]
@hoangdat does that answer your concerns?
