### ISSUE TITLE
[Improvement] Add a little bit of clarification to the Name field

### ISSUE THREAD

**Issue by tprudentova** [linagora/tmail-flutter#3149]
When creating an identity, you need to add the name of the identity. I think we need to explain to the user that this name will be displayed to the recipients of letters. (Otherwise there's a chance that the user will think this name is visible only to them and might use something like "I hate everyone in this building" :D)

<img width="893" alt="Screenshot 2024-09-16 at 11 17 28" src="https://github.com/user-attachments/assets/97260927-3e0a-42dd-b95e-68fb3fc65216">

**Comment by chibenwa** [comment]
Name (required) => Display name used in From email address of composed emails (required) ?

**Comment by florentos17** [comment]
in [my PR](https://github.com/linagora/tmail-flutter/pull/3216), i put "Name to be displayed to recipients (required)"
i had two approvals so i merged yesterday
what do you think ?
