### ISSUE TITLE
Unicode character is not supported (vietnamese)

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#315]
<img width="267" alt="image" src="https://user-images.githubusercontent.com/6462404/157368900-a1fb8cac-01be-4e84-9880-d3317e8fb25e.png">

### DoD:

why text string is not support Vietnamese. 'Trả lời' - 'Chuyển tiếp'

**Comment by chibenwa** [comment]
I saw that one too...

Can you please share the JMAP requests you used to send the mail?

**Comment by hoangdat** [comment]
> I saw that one too...
> 
> Can you please share the JMAP requests you used to send the mail?

you mention about the cause of undelivered mail?

I mention about the text in Vietnamese "Trả lời" and "Chuyển tiếp"

**Comment by chibenwa** [comment]
I succeed to send myself a mail with text `Trả lời" and "Chuyển tiếp`...

**Comment by chibenwa** [comment]
Up!

Can you please try to share with me the JMAP exchanges that lead to this bug?

**Comment by hoangdat** [comment]
no no, only the problem related to internationalize for non-ascii character. Maybe this kind of issue occurred after applied Web-late

**Comment by chibenwa** [comment]
> no no, only the problem related to internationalize for non-ascii character. Maybe this kind of issue occurred after applied Web-late

Mmhhh what ever the messing up on mobile dise, we did end up trying to send an invalid mail, this means that the JMAP James stack likely have non - complients behavour.

Please enable a debug mode where you log all JMAP requests / responses, so that if it happens to you again you could look at the logs and share with me the exact JMAP requests...

**Comment by dab246** [comment]
This error no longer appears. It is possible that the fonts in use do not support unicode. Currently we only use the only font Inter. 

![Simulator Screen Shot - iPhone 11 Pro Max - 2022-03-30 at 10.58.01.png](https://images.zenhubusercontent.com/605059df174a357c7888640f/2d2d77fd-3d4d-4cd1-8b8b-d9170e1cdac6)

**Comment by chibenwa** [comment]
Unrelated to the mobile app, this is indeed a backend problem: attachments were not encoded in base64 when sent.

See https://github.com/apache/james-project/pull/927

**Comment by hoangdat** [comment]
yes, maybe `Inter` font is better than `SF pro`.

nothing related to back-end :)

**Comment by chibenwa** [comment]
I'm speaking of 

[](https://user-images.githubusercontent.com/6462404/157368900-a1fb8cac-01be-4e84-9880-d3317e8fb25e.png)

Nothing to do with font!
