### ISSUE TITLE
docker with path for reverse proxy https://example.com/somepath/

### ISSUE THREAD

**Issue by chrismaster** [linagora/tmail-flutter#3167]
Is it possible for docker to set a path with docker for a reverse proxy?
Didn't find any environment variables, or env.file to set https://example.com/PATH/

**Comment by chrismaster** [comment]
What works is mount index.html `Volume=%h/tmailDATA/index.html:/usr/share/nginx/html/index.html:Z` (for podman with quadlet)
and edit `<base href="/">` to eg `<base href="/tmail/">`
Maybe not an elegant solution, but it works.
Some environment variables would be a great addition. e.g. path, port, ...
_for changing port i had to mount nginx.conf_  
`Volume=%h/tmailDATA/nginx.conf:/etc/nginx/nginx.conf:Z `
and change `listen 80;` to eg `listen 3000;`
Thx for this cool project....

**Comment by chibenwa** [comment]
@hoangdat is this possible tohave a build parameter for this?

**Comment by tk-nguyen** [comment]
> What works is mount index.html `Volume=%h/tmailDATA/index.html:/usr/share/nginx/html/index.html:Z` (for podman with quadlet) and edit `<base href="/">` to eg `<base href="/tmail/">` Maybe not an elegant solution, but it works. Some environment variables would be a great addition. e.g. path, port, ... _for changing port i had to mount nginx.conf_ `Volume=%h/tmailDATA/nginx.conf:/etc/nginx/nginx.conf:Z ` and change `listen 80;` to eg `listen 3000;` Thx for this cool project....

The base href is set at build time by `flutter build web --base-href=<href>`, see the comments in `index.html` here: https://github.com/linagora/tmail-flutter/blob/9aa438bc007930fd0f46d55c56be9c39c298f302/web/index.html#L14-L17

We can add an `ARG` to customize this.

We're using `nginx.conf` at `https://github.com/linagora/tmail-flutter/blob/master/server/nginx.conf`. This can also be customized by mounting it as template with environment variables, which will be rendered at runtime by the official nginx docker image: https://github.com/docker-library/docs/tree/master/nginx#using-environment-variables-in-nginx-configuration-new-in-119

**Comment by chibenwa** [comment]
> The base href is set at build time by flutter build web --base-href=<href>, see the comments in index.html here: 

Ok this looks fair to me: at least it has an option. (thanks @tk-nguyen !)

@chrismaster this will be a cleaner way to achieve your goals.

As such can we close this ticket?

**Comment by kraftreich** [comment]
Allright, just close.
Going to test the nginx template envsubst configuration and create a PR.

If I get it correctly, for --base-href atm only possible to change during build, but not running/starting container image.

Thx
C

**Comment by tk-nguyen** [comment]
> Allright, just close. Going to test the nginx template envsubst configuration and create a PR.
> 
> If I get it correctly, for --base-href atm only possible to change during build, but not running/starting container image.
> 
> Thx C

Yes, flutter is handling the href configuration and building out a PWA. Note that these are just HTML, JS and CSS files, so you can use any web server.
