### ISSUE TITLE
[BUG] Image not displayed when attached in identity creator view

### ISSUE THREAD

**Issue by dab246** [linagora/tmail-flutter#3174]
### Env: 

- Version: `0.13.2`
- Server: `stg.lin-saas.com`
- Platform: `Edge(Macbook)`

### Steps to reproduce

1. Open `Setting` screen and Select `Profile` tab
2. Click `Create new identity`
3. Click `Insert image` icon or drag image to insert image to signature editor .

## Expectation

- Image is displayed when insert is successful

## Evidence

https://github.com/user-attachments/assets/aa196f3b-9022-44e2-95e9-0391170fa5b7

**Comment by dab246** [comment]
Only happens on `stg.lin-saas.com`. Works fine on `linagora.com`

**Comment by hoangdat** [comment]
hi @Arsnael ,
Can you take a look on this tikcet in `staging of TWP`?
1. We upload image successfully 
```
{
    "accountId": "750b7391d4e9be0de1e251cc3664761fed57bc92be1db6ed4bb2050a98189338",
    "blobId": "uploads-40510320-7a53-11ef-8d10-8befd6b38695",
    "type": "image/png",
    "size": 119759
}
```
2. We request `PublicAsset/set` and success
```
{
    "sessionState": "2c9f1b12-b35a-43e6-9af2-0106fb53a943",
    "methodResponses": [
        [
            "PublicAsset/set",
            {
                "accountId": "750b7391d4e9be0de1e251cc3664761fed57bc92be1db6ed4bb2050a98189338",
                "oldState": "2c9f1b12-b35a-43e6-9af2-0106fb53a943",
                "newState": "2c9f1b12-b35a-43e6-9af2-0106fb53a943",
                "created": {
                    "4080ecc0-7a53-11ef-8ff5-8395bfcf1ff2": {
                        "id": "41112bcf-7a53-11ef-ac7d-c59c58c9a698",
                        "publicURI": "https://jmap.stg.lin-saas.com/publicAsset/datjuly@stg.lin-saas.com/41112bcf-7a53-11ef-ac7d-c59c58c9a698",
                        "size": 119759,
                        "contentType": "image/png"
                    }
                }
            },
            "c0"
        ]
    ]
}
```
3. But can not found: 404 for the publicUri
<img width="657" alt="image" src="https://github.com/user-attachments/assets/35f71789-db53-413e-80ba-d416b3401950">

**Comment by Arsnael** [comment]
Thanks for the details, will try to take a look.

My bet is that likely there is no apisix route defined for that, but let's see

**Comment by Arsnael** [comment]
Yep route does not exist in apisix

Fix here (need to test though) => https://ci.linagora.com/linagora/lrs/saas/tools/helm-charts/tmail-apisix/-/merge_requests/4

need to merge and redeploy

**Comment by Arsnael** [comment]
Done. I can access this link on twp staging now.

@dab246 @hoangdat please checvk on your side, confirm that it works and close this ticket then thanks :)

**Comment by hoangdat** [comment]
it works. Thank you.
