### ISSUE TITLE
Basic authentication issue with TMail Web 0.13.2

### ISSUE THREAD

**Issue by quantranhong1999** [linagora/tmail-flutter#3180]
### Description

When I configure TMail web 0.13.2 to the endpoint `SERVER_URL=https://jmap-sandbox.upn.integration-open-paas.org` (sandbox's basic auth endpoint), the basic auth flow does not work.

![image](https://github.com/user-attachments/assets/0c3f283f-8e51-495a-bc33-066f2290001f)

It happens on both my laptop and my PC (incognito tab, clear cache...)

While it worked with 0.13.1.

### Expected result

I can use the basic auth flow normally (with sandbox basic auth).

### Current behavior

I can not use the basic auth flow normally (with sandbox basic auth).

#### Reproduction Steps

Connect tmail web to sandbox ENV' basic auth endpoint `SERVER_URL=https://jmap-sandbox.upn.integration-open-paas.org`.

**Comment by chrismaster** [comment]
Had the same problem. Give 0.13.4 a try, here it works.
