### ISSUE TITLE
[Improvement] Change icons in the app grid

### ISSUE THREAD

**Issue by tprudentova** [linagora/tmail-flutter#3182]
0.13.2, linagora.com 

Apply the latest icons design to the app grid

<img width="1280" alt="Screenshot 2024-09-30 at 10 48 56" src="https://github.com/user-attachments/assets/0b34e70d-26a5-4920-9eda-b98ed4a9a866">

**Comment by hoangdat** [comment]
hi @ducnm0711 , can you update new icons set for app grid. Thanks

**Comment by ducnm0711** [comment]
@tprudentova hello it's updated. Can you clear cache and try again?
![image](https://github.com/user-attachments/assets/c805f02e-8aa6-4013-ab23-c1bdb58f59b5)
