### ISSUE TITLE
how to run the app

### ISSUE THREAD

**Issue by harryandroiddev** [linagora/tmail-flutter#319]
i have cloned the and run the command for generating code for json serlizable but it still gives the error , how to install the app and run it ?

**Comment by hoangdat** [comment]
Hi, we work well on 
- `Flutter (Channel stable, 2.10.0)`
- and please run the following command:
```
cd core
flutter pub get
            
cd ../model
flutter pub get && flutter pub run build_runner build --delete-conflicting-outputs

cd ..
flutter pub get && flutter pub run intl_generator:extract_to_arb --output-dir=./lib/l10n lib/main/localizations/app_localizations.dart
flutter pub get && flutter pub run intl_generator:generate_from_arb --output-dir=lib/l10n --no-use-deferred-loading lib/main/localizations/app_localizations.dart lib/l10n/intl*.arb
```

**Comment by harryandroiddev** [comment]
app is running but what about credentials for login?

**Comment by hoangdat** [comment]
@harryandroiddev we only have the credentials for development only. If you have any JMAP server, you can use the application with it.

**Comment by harryandroiddev** [comment]
ok thanks

**Comment by harryandroiddev** [comment]
i have logged in with my jmap credentials but after pressing login button it does not go to anywhere, it just go to session and come back to login screen again .?

**Comment by hoangdat** [comment]
can you share the flutter log?, maybe we can detect the root cause.

**Comment by harryandroiddev** [comment]
[GETX] REPLACE ROUTE /login
[GETX] NEW ROUTE /session
[GETX] Instance "SessionController" has been created
[GETX] Instance "GetSessionInteractor" has been created
[GETX] Instance "SessionRepository" has been created
[GETX] Instance "SessionRepositoryImpl" has been created
[GETX] Instance "SessionDataSource" has been created
[GETX] Instance "SessionDataSourceImpl" has been created
[GETX] Instance "DeleteCredentialInteractor" has been created
[GETX] Instance "CredentialRepository" has been created
[GETX] Instance "CredentialRepositoryImpl" has been created
[GETX] Instance "SessionController" has been initialized
flutter: *** Request ***
flutter: uri: https://mail.zaxtom.com/.well-known/jmap
flutter: method: GET
flutter: responseType: ResponseType.json
flutter: followRedirects: true
flutter: connectTimeout: 0
flutter: sendTimeout: 0
flutter: receiveTimeout: 0
flutter: receiveDataWhenStatusError: true
flutter: extra: {}
flutter: headers:
flutter:  accept: application/json;jmapVersion=rfc-8621
flutter:  authorization: Basic aGFyd2luZGVyQHpheHRvbS5jb206OF92NFFKR2VmQ2ZoWg==
flutter: data:
flutter: null
flutter:
[GETX] "AuthenticationDataSourceImpl" deleted from memory
[GETX] "AuthenticationDataSource" deleted from memory
[GETX] "AuthenticationRepositoryImpl" deleted from memory
[GETX] "AuthenticationRepository" deleted from memory
[GETX] "AuthenticationInteractor" deleted from memory
[GETX] "LoginController" onDelete() called
[GETX] "LoginController" deleted from memory
flutter: *** Response ***
flutter: uri: https://mail.zaxtom.com/.well-known/jmap
flutter: statusCode: 200
flutter: headers:
flutter:  connection: keep-alive
flutter:  last-modified: Fri, 11 Mar 2022 07:29:48 GMT
flutter:  date: Wed, 16 Mar 2022 11:49:37 GMT
flutter:  transfer-encoding: chunked
flutter:  content-encoding: gzip
flutter:  etag: W/"622afa6c-cdc"
flutter:  content-type: text/html
flutter:  server: nginx/1.14.2
flutter:
flutter: seesion error  type 'String' is not a subtype of type 'Map<String, dynamic>' //printed this error on error catch
[GETX] REPLACE ROUTE /session
[GETX] NEW ROUTE /login
[GETX] Instance "LoginController" has been created
[GETX] Instance "AuthenticationInteractor" has been created
[GETX] Instance "AuthenticationRepository" has been created
[GETX] Instance "AuthenticationRepositoryImpl" has been created
[GETX] Instance "AuthenticationDataSource" has been created
[GETX] Instance "AuthenticationDataSourceImpl" has been created
[GETX] Instance "LoginController" has been initialized
[GETX] "SessionDataSourceImpl" deleted from memory
[GETX] "SessionDataSource" deleted from memory
[GETX] "SessionRepositoryImpl" deleted from memory
[GETX] "SessionRepository" deleted from memory
[GETX] "GetSessionInteractor" deleted from memory
[GETX] "CredentialRepositoryImpl" deleted from memory
[GETX] "CredentialRepository" deleted from memory
[GETX] "DeleteCredentialInteractor" deleted from memory
[GETX] "SessionController" onDelete() called
[GETX] "SessionController" deleted from memory

**Comment by hoangdat** [comment]
please come to the file `network_bindings.dart` and find the line 
```
Get.find<Dio>().interceptors.add(LogInterceptor(requestBody: true));
``` 

to 

```
Get.find<Dio>().interceptors.add(LogInterceptor(requestBody: true, responseBody: true));
```

and share me the log. (please note, hiding your credentials or private information)
