### ISSUE TITLE
Personnal folders are synced only one-way

### ISSUE THREAD

**Issue by Facyla** [linagora/tmail-flutter#3190]
### Description
I noticed the "Personal folders" on the left on web version, and that it has synced a folder (outside inbox) that i created in my email client (Thunderbird). A new folder added in TB appears quickly on Twake Mail web version (the "Test sous-dossier sync ??"):
![image](https://github.com/user-attachments/assets/14242cac-7e3c-49f8-a685-3919b01bc458)

However, the reverse behaviour doesn't seem to work: a personal folder created in Twake Mail (with an email placed into it) does not appear in Thunderbird - even after mailbox forced sync.
![image](https://github.com/user-attachments/assets/e6f4eb30-af2e-40cf-87ed-ba88861ff81b)

### Expected result
Have the same folders and same folder content both on web client and desktop client.

### Current behavior
Sync is ok TB -> TM
Sync is KO TM -> TB

**Comment by chibenwa** [comment]
Duplicated issue CF @hoangdat

**Comment by chibenwa** [comment]
That's a thunderbird bug.

Close + open tb again works.

Please open the bug onto their backlog, not here.

(but thx for report anyway)
