### ISSUE TITLE
[Bug] Delete mailbox still not success for mailbox which has children

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#320]
### Desc:
 ![image.png](https://images.zenhubusercontent.com/5f7d8ef759d36aecc684e2a4/04d7afdb-bb5c-4b76-a823-42f5901b307f)

### DoD:
- Should split delete sub and parent mailbox in separate method in request.

**Comment by chibenwa** [comment]
Yes we don't order the deletes hierarchically.

You can try:

```
{
   ...
   "methodCalls": [
       [ "Mailbox/set", {"destroy mbx A"}, "#0"],
       [ "Mailbox/set", {"destroy mbx B"}, "#0"],
       [ "Mailbox/set", {"destroy mbx C"}, "#0"],
       [ "Mailbox/set", {"destroy mbx D"}, "#0"]
    }
}
```

Starting with child mailboxes first.
