### ISSUE TITLE
Default Language 0.13.4

### ISSUE THREAD

**Issue by chrismaster** [linagora/tmail-flutter#3209]
0.13.4 was the first release I manage to install, and it just works. Thx.
1)
Is there a way to set the default language for the docker image? Maybe over environment var?
It is always set to french and if you don't have a clue, it is hard to find the settings in the profile.
2)
You have some site, where I can do the german translation?
Thx
Chris

**Comment by chibenwa** [comment]
https://hosted.weblate.org/projects/linagora/teammail/de/

Here you are.

After that, once complete enough we will need to :

 - add the german option in the drop down menu
 - possibly make sure it get's auto-detected from the browser settings.
 
 Contributions are welcome!

**Comment by chibenwa** [comment]
Ideally the language defaults to the user browser settings.

**Comment by chrismaster** [comment]
Ok, seems my default language (german) is missing and the fall back is french. Maybe its a good idea to take english as fall back.
I did the translation to german. Some semantics depend where it is used in the TeamMail. I will iron them when german is in the public docker image, is this ok?

**Comment by chrismaster** [comment]
I added german #3214 #3213 

If the browser language is not, the flutter web takes french not english. Didn't find where this problem comes from, but I think it is supposed to be english. This might be a bug...

**Comment by chibenwa** [comment]
>  This might be a bug...

Not really: our main customers are french...

**Comment by chrismaster** [comment]
fixed...
