### ISSUE TITLE
[mobile] links in html email are not rendered correctly

### ISSUE THREAD

**Issue by rezk2ll** [linagora/tmail-flutter#3210]
### Description
when in mobile:
HTML Emails containing links using anchor tag `<a href='...`  are not rendered correctly, the link will always be displayed after the text.

for example, we send an HTML email
```html
Hello <a href="https://linagora.com">this is a link</a>
 and <a href='https://twake.app'>and this is another one</a>
```
We get an email with the desired link and then the link URL is appended to it.

### Expected result

anchor `<a ` tags should render properly.

![Screenshot from 2024-10-17 17 21 28](https://github.com/user-attachments/assets/f91159b2-a922-4502-ac67-09a4b4d2daad)

### Current behavior

![Screenshot from 2024-10-17 17 24 28](https://github.com/user-attachments/assets/f65ebfea-0e08-4483-9ec7-d96bb783e4b3)

the links are duplicated desired link and then the link URL is appended to it.

#### Reproduction Steps
- send HTML email ( using [send HTML in gmail extension](https://chromewebstore.google.com/detail/send-html-in-gmail/ipaogmomajeofkdpcmmjgilnblolomhb) ).
- open the email in TMAIL mobile client.

### Context

mobile: Android and IOS
version: 0.13.2

**Comment by hoangdat** [comment]
Known issue, and fixed in 0.13.4
