### ISSUE TITLE
[Bug] Can't log into Twake Mail on staging 

### ISSUE THREAD

**Issue by tprudentova** [linagora/tmail-flutter#3218]
mail.stg.lin-saas.com, tested on Safari, Firefox

1. Sign in (success page or other products)
2. Try going to Mail 
3. Connection error 

NB: This could be a cache problem, because it works fine in a private window, but maybe you want to investigate the issue, since I'm not the only one encountering it

https://github.com/user-attachments/assets/b989fc44-528b-45e4-b042-22081d716493

**Comment by hoangdat** [comment]
hi @ducnm0711, @tk-nguyen please check. Maybe related to APISIX plugin

<img width="764" alt="image" src="https://github.com/user-attachments/assets/3423cfcc-0933-4b06-8220-56f881a12c90">

**Comment by quantranhong1999** [comment]
Hi @tprudentova, can you try again?

**Comment by tprudentova** [comment]
Looks good now!
