### ISSUE TITLE
Display Limits of of Email Recovery

### ISSUE THREAD

**Issue by florentos17** [linagora/tmail-flutter#3219]
the JMAP session advertises two limits through its `MessageVaultCapability` object:
- the maximum number of mail that a user can recover at once, eg with one query: `maxEmailRecoveryPerRequest`
- the period during which a user can restore a mail alone after having deleted it: `restorationHorizon`

we would like to **have a yellow banner indicating these limits** in the email recovery window

**Comment by chibenwa** [comment]
Can we link corresponding tmail-backend ticket please?

**Comment by florentos17** [comment]
it is related to [this backend issue](https://github.com/linagora/tmail-backend/issues/1201)
and the corresponding backend pull requests are [this one](https://github.com/linagora/tmail-backend/pull/1224) and [this one](https://github.com/linagora/tmail-backend/pull/1248)

**Comment by hoangdat** [comment]
- [ ] Must have verifying step after user select `Deletion date`. In this case, I choose the time range for the last 1 year.

<img width="717" alt="image" src="https://github.com/user-attachments/assets/ea49862c-0a78-4e24-9595-3419979b5790">
