### ISSUE TITLE
System mailboxes are not sorted

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#322]
INBOX should be first...

**Comment by chibenwa** [comment]
![20220311_175010](https://user-images.githubusercontent.com/6928740/157853376-897936ac-5987-4012-b372-23527d97f0ab.jpg)

**Comment by Arsnael** [comment]
Yes weird I noticed that too and I thought I fixed it a while ago... Regression?

**Comment by hoangdat** [comment]
Yes, I will try more. But don't need to weird, because the data flow of web-mail not similar to the mobile, because web-mail does not use cache.

**Comment by Arsnael** [comment]
Yes I confirm on mobile I still have the correct behavior. Thanks for the explanation @hoangdat

**Comment by hoangdat** [comment]
Sad news, it's my fault when build the tree for default mailbox. But good news, our cache also work in browser :)

> Yes I confirm on mobile I still have the correct behavior. 

your version is outdate :). Maybe at the end of this week, new version will be released

**Comment by chibenwa** [comment]
:+1:
