### ISSUE TITLE
[Bug] No autosuggestions for recipient address

### ISSUE THREAD

**Issue by tprudentova** [linagora/tmail-flutter#3229]
0.13.4, mail.stg.lin-saas.com, tested on Android, Firefox

1. Open composer 
2. Go to the "To" field 
3. Start entering an address with whom you've already had conversation 
4. There are no autosuggestions 

Expectation: when I enter first 3 symbols, I see autosuggestions

https://github.com/user-attachments/assets/a657775b-cfa5-49c2-aaf3-6b9d43daf9c6

https://github.com/user-attachments/assets/b53f79e2-71e2-4a18-9f92-1a4609b3ae55

**Comment by dab246** [comment]
Tested on `stg.lin-saas`. FE did send request to server but response is always empty list. IMO, maybe there is a bug on server side. @quantranhong1999  Can you check this problem for us?

- Request:

```json
{
  "using": [
    "urn:ietf:params:jmap:core",
    "com:linagora:params:jmap:contact:autocomplete"
  ],
  "methodCalls": [
    [
      "TMailContact/autocomplete",
      {
        "accountId": "191956a216f8f579ebfa24a628d02b659935f8a0f619f2a1d3f4b03ce03ac382",
        "limit": 5,
        "filter": {
          "text": "tdvu"
        }
      },
      "c0"
    ]
  ]
}
```

- Response:

```json

{
  "sessionState": "2c9f1b12-b35a-43e6-9af2-0106fb53a943",
  "methodResponses": [
    [
      "TMailContact/autocomplete",
      {
        "accountId": "191956a216f8f579ebfa24a628d02b659935f8a0f619f2a1d3f4b03ce03ac382",
        "list": []
      },
      "c0"
    ]
  ]
}

```

- Reproduced:

https://github.com/user-attachments/assets/4b02d794-8934-43f7-8764-3cc9341035ae

**Comment by quantranhong1999** [comment]
> Can you check this problem for us?

Likely it is just a deployment issue. Can you help add this to Frontend-support of TMail backend board?

**Comment by quantranhong1999** [comment]
Hi @tprudentova,

The auto-complete contacts should be back now. Can you check again?
