### ISSUE TITLE
Several Email filters at the same time

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#324]
### Description

As a user I want to combine Email filters. Eg: `Give me unread email with an attachment`.

Today this is impossible as I can only specify one filter. 

We should allow to combine filters.

Today, I can only apply one filter:

![Screenshot from 2023-04-05 09-10-07](https://user-images.githubusercontent.com/6928740/229963123-edcc20d8-b011-4242-ab2d-a5483926a806.png)

**Comment by hoangdat** [comment]
duplicated #1902
