### ISSUE TITLE
Can not select email subject

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#325]
### Description

I can not select subjects of email (eg to do copy and pastes)

https://user-images.githubusercontent.com/6928740/158091520-f32b5b0e-566e-4e5b-ace7-c15d4600dcee.mp4

I should be able to select them...

### Environment

Chromium.

**Comment by Kevinle2312** [comment]
Passed on CI platform.

https://user-images.githubusercontent.com/32490981/162394067-8a0d6913-bda3-46f9-a954-c8fa329a12f8.mp4
