### ISSUE TITLE
Remove app grid on mobile

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#3258]
### Why?

App grid is hard coded to (private internal) linagora stuff

Yet we are selling it out of Linagora making the app grid very irrelevant and confusing.

Ideally we shall be able to:
 - not point to web but actually apps 
 - and be able to discover it from the back

In the meantime it is better to **remove the app grid**

No app grid is better than a bad one.

This need release on stores ASAP

**Comment by chibenwa** [comment]
cc @hoangdat @guimard

**Comment by guimard** [comment]
@hoangdat : is it possible to deploy the fix this week ?

**Comment by hoangdat** [comment]
yes, only for tmail mobile.

**Comment by guimard** [comment]
> yes, only for tmail mobile.

Sure, web-app works because it uses local appgrid.
Thanks

**Comment by hoangdat** [comment]
v0.13.6 which included removing app grid in mobile available in stores

**Comment by guimard** [comment]
Verified, it's OK now. Thank you
