### ISSUE TITLE
Can not select email bodies when tet/plain

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#326]
### Description

When the email is text/plain, I can not select the email body.

https://user-images.githubusercontent.com/6928740/158091697-3f73a8bc-7c93-45d4-b28d-dc2732f0a791.mp4

I should be able to do this just like I am for HTML emails.

### Context

Chromium

**Comment by Kevinle2312** [comment]
Passed on CI platform.

https://user-images.githubusercontent.com/32490981/162393468-0ba88389-57e2-4745-9d90-3f6a54f182a9.mp4
