### ISSUE TITLE
Composer: cursor on header is buggy

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#327]
### Description

The cursor on header is buggy:

 - It keeps displaying the cursor on subject despite me typing the body
 - I can not select subject when I type the body, I have to select To then subject
 
 

https://user-images.githubusercontent.com/6928740/158092087-e2f98840-ce0b-4f6f-8856-5143b89495ac.mp4

### Expected result

 - See only one cursor, where I type
 - Move the cursor on the field I select, directly...

### Context

Chromium

**Comment by Kevinle2312** [comment]
Passed on CI platform.

https://user-images.githubusercontent.com/32490981/162390092-ffcbca65-a052-40de-8b3f-7bf3466620a4.mp4
