### ISSUE TITLE
Provision data in Patrol environment

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#3272]
### Desc:

We use patrol to do integration test
We should find a better way to provision user, email, mailbox to test 

### DoD: 
- [x] provision data in BE side via CLI 
- [ ] use webAdmin API to create user, mailbox from Patrol side
- [ ] use JMAP Email/set

**Comment by dab246** [comment]
> * [x]  provision data in BE side via CLI
> 
 Already implemented at here https://github.com/linagora/tmail-flutter/pull/3257
