### ISSUE TITLE
Uploads: can not upload files without extensions

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#328]
### Description

Upload fails for files named `JenkinsFile`, `License`.

It succeeds with file with an extension. `pom.xml`

https://user-images.githubusercontent.com/6928740/158092430-a91605ad-3edf-4b85-924c-5cd60e0272b0.mp4

### Expected result

Upload of files without extension should also succeed

### Context

Chromium

**Comment by Kevinle2312** [comment]
Passed on CI platform

https://user-images.githubusercontent.com/32490981/162120350-36893098-8a31-4bac-a57e-87c4c1510d08.mp4
