### ISSUE TITLE
Email view: can no longer scroll long emails on web

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#330]
### Description

Upon a long mail I can't scroll and thus can just read the top...

https://user-images.githubusercontent.com/6928740/158092928-64f82b67-3bda-4dbb-be48-09226dde6f14.mp4

### Expected result

I should be able to read the whole email!

### Context

Chromium

**Comment by Kevinle2312** [comment]
Passed on CI platform.

https://user-images.githubusercontent.com/32490981/162147506-16f2c2c4-8c18-45b9-8e83-236f68571a2f.mp4
