### ISSUE TITLE
Draft: email body is lost

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#331]
### Description

```
GIVEN I type an email body
AND I save it as a draft
WHEN I open it back
THEN it no longer have the body
```

https://user-images.githubusercontent.com/6928740/158093320-2e2bd284-e7ee-4d87-942a-d0de20d44f31.mp4

### Expected result

I should be able to see the exact body I previously typed...

### Additional information

When opening a draft please retrieve the body from the backend

**Comment by hoangdat** [comment]
it still work at the moment: 10.45AM - 24 May 22
