### ISSUE TITLE
Draft: When no changes are made, don't save the draft again

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#332]
### Expected result

```
GIVEN I open and close a draft,
THEN it should not do any JMAP requests
```

as the content did not change.

### Current behavior

https://user-images.githubusercontent.com/6928740/158093642-7378361c-60e5-495b-b75c-2d03c6c4a95d.mp4

**Comment by Kevinle2312** [comment]
@hoangdat I think when nothing is change, tmail still making jmap request:

https://user-images.githubusercontent.com/32490981/174007207-3a00e30b-0388-42a1-9b03-81bbd90505ca.mp4
