### ISSUE TITLE
I should be able to create 2 mailbox with the same name when parents is different

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#333]
### Description

I should be able to create 2 mailbox with the same name when parents is different

### Expected result

Unicity of a mailbox name only applies when the parent is the same

### Current behavior

https://user-images.githubusercontent.com/6928740/158093842-f9216118-2652-4315-8b02-d266f9ce7a53.mp4

**Comment by Kevinle2312** [comment]
Passed on CI platform

https://user-images.githubusercontent.com/32490981/162141462-b204b635-c133-4e73-92e4-ac6481e63be4.mp4
