### ISSUE TITLE
[MU] Composer break in customer

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#3340]
### Desc:
![Image](https://github.com/user-attachments/assets/ceddd6c8-19b4-4d6f-887f-98181095b638)

Browser: Chrome
OS: windows 7

### DoD:

**Comment by hoangdat** [comment]
Also problem in Ubuntu - chrome 103

**Comment by dab246** [comment]
## Related Issue Flutter

- https://github.com/flutter/flutter/issues/146431
- https://github.com/dart-lang/dart-pad/issues/2958

**Comment by dab246** [comment]
> Also problem in Ubuntu - chrome 103

Try to upgrade version `Chrome` to 131. Issue fixed.
