### ISSUE TITLE
Email detail view: Open links in another tab

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#335]
### Description

```
GIVEN I read a mail
WHEN I click on a link
THEN it opens it in the email body (and fails)
```

### Expected result

It should open the link in another tab....

### Current behavior

https://user-images.githubusercontent.com/6928740/158094498-de195c61-88eb-47ce-8a46-b893848991b6.mp4

### Context

Chromium

**Comment by Kevinle2312** [comment]
Passed on CI platform. The link is opened in another tab.

https://user-images.githubusercontent.com/32490981/162393040-e9bc28b4-3a49-4838-b4cc-d6b3ba82618e.mp4
