### ISSUE TITLE
Email detailed view full screen

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#337]
### Description

Currently in web the email is displayed in half of the screen. I currently have no way to go "full screen".

Generally webmails allows to see a mail without seeing the mail-list. Here is how it looks in Roundcube:

https://user-images.githubusercontent.com/6928740/158096461-f670a250-d10a-4742-b96b-1c92ab3ea248.mp4

### Expected result

Have a way to read a single email in webmail.

**Comment by hoangdat** [comment]
it is in v0.2.2
