### ISSUE TITLE
Web: Email detailed view flyover for links

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#341]
### Description

When I put the mouse above a link it would be nice to have a little flyover for links (without clicking)

To get link infos today I need to click then drag...

https://user-images.githubusercontent.com/6928740/158097831-0490b840-d64b-4a22-8a9a-756aa72fd625.mp4

### Context

Chromium

**Comment by Kevinle2312** [comment]
Passed on the Production platform.
