### ISSUE TITLE
TMail should handle mailto link

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#342]
### Description

Given a mailto link clicked, TMail should open a composer (with that address on the to field)

(This should also be the case for mobile)

### Current behavior

Today it's the system that handles those mail to links, and does that with thunderbird.

https://user-images.githubusercontent.com/6928740/158098093-02731bdb-433a-440e-8cde-9b5615e45220.mp4

### Expected behaviour

EG OpenPaaS

https://user-images.githubusercontent.com/6928740/158098196-85010e18-2591-41e7-a03e-4d90b1e50268.mp4

**Comment by hoangdat** [comment]
@dieptran88 please help us on the story to open composer when user click on mailto link in mobile, tablet (from other app also)?
in web-mail, when click on mail to link in our app only?

**Comment by hoangdat** [comment]
implemented in v0.3.1

**Comment by Kevinle2312** [comment]
Passed on the Production platform.
