### ISSUE TITLE
Infinite email-list scroll not sorted well

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#343]
### Description

When I do an infinite scroll, if I scroll deep enough, I will see some not well sorted entries.

https://user-images.githubusercontent.com/6928740/158101971-672a2d4c-ef54-43ae-80cb-fbdf4671b98f.mp4

### Expected result

I expect the infinite scroll to be well sorted.

### Context

Chromium, but I also saw this on mobile some time ago.

**Comment by Kevinle2312** [comment]
Passed on CI platform.

https://user-images.githubusercontent.com/32490981/162146175-fce3ff5e-9aac-4c99-bd5f-da8ed895a75d.mp4
