### ISSUE TITLE
Composer: too much place taken on web for attachments

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#344]
### Description

 - Place dedicated for attachments is likely too big
 - When I have no attachments do we really need to show it?

https://user-images.githubusercontent.com/6928740/158102943-876c1a87-9714-4b28-919a-7dfd017d8745.mp4

### Context

Chromium

**Comment by hoangdat** [comment]
for all composer issue, I will keep all the thing in queue until we have the final design for composer

**Comment by chibenwa** [comment]
> for all composer issue, I will keep all the thing in queue until we have the final design for composer

No problem.

I just took the time to check current status of the app, regarding the best tactical decisions so as what to solve first, and how to solve things, you for sure are more competent than me.

Don't hesitate to create a `composer` tag too.

**Comment by Kevinle2312** [comment]
Passed on CI platform.

https://user-images.githubusercontent.com/32490981/162392267-476003e3-ce6e-46a3-9f3c-3d522982440c.mp4
