### ISSUE TITLE
Composer: replying a long email I do not see attachments I upload

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#345]
### Description

https://user-images.githubusercontent.com/6928740/158103381-42efeaee-c98a-4ccc-afdc-1e21b17956a0.mp4

Still on chromium...

**Comment by Kevinle2312** [comment]
Passed on CI platform.

https://user-images.githubusercontent.com/32490981/162391934-0f9db9e9-bd56-42f4-b4a6-cb3ce4a65d6f.mp4
