### ISSUE TITLE
Unread email counter not updating dynamically on flutter web

### ISSUE THREAD

**Issue by Arsnael** [linagora/tmail-flutter#348]
### Description

On the web version, after reading multiple emails, the email counter does not update. For example, if I go to INBOX, i have 20 unread emails. I read 3 mails, I still have shown 20 unread emails.

I need to refresh the browser to see the update.

### Expected result

Correct number of unread emails shown in the mailbox (I have 20 unreads, I read 3, I should see 17)

### Current behavior

Does not update 

#### Reproduction Steps

* Go on tmail flutter web
* Select a mailbox with unread messages
* Read some messages
* Unread counter is still the same

### Context

Tmail web

**Comment by chibenwa** [comment]
On mobile it's ok?

Maybe the mailbox are refreshed when panel folds / unfold?

**Comment by Arsnael** [comment]
Looks okish on mobile yeah

**Comment by Arsnael** [comment]
Ok I see this on iOS now since the new update. If I want my counters updated, I need to kill the app and restart it to have a full refresh... if not the number of unread messages on a mailbox never seem to change, even after I read of move a bunch of them

**Comment by hoangdat** [comment]
hmm, maybe my fault again when refactor the menu tree :(

**Comment by Kevinle2312** [comment]
Passed on CI platform.

https://user-images.githubusercontent.com/32490981/162395424-9e7b1020-4f00-4f3f-b3d4-f4ee8d08df3e.mp4
