### ISSUE TITLE
UX: lists should show selected items

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#349]
### Description

(Requested by @phamtuanchip )

Here is the current TMail screen:

![Screenshot from 2022-03-16 09-44-33](https://user-images.githubusercontent.com/6928740/158506566-38d6bde6-787c-4f8e-8d07-635ae4980322.png)

In the mailbox list and email list it would be good to have a light purple background to show selected items. Currently we just do not know.

**Comment by chibenwa** [comment]
![image](https://user-images.githubusercontent.com/6928740/158521260-1372808b-22a6-4ce3-ac72-a2a81124f7ce.jpg)

Tuan PHAM proposal

**Comment by hoangdat** [comment]
not occurred in v0.2.2 because in new design, ThreadView and EmailView stay in different screens
