### ISSUE TITLE
WEB EmailAddress pop-over can not be closed

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#350]
### Description

Clicking the cross of the email address popover have no effect....

![Screenshot from 2022-03-16 09-48-58](https://user-images.githubusercontent.com/6928740/158507154-a60d97eb-00c1-470b-8678-61c8bd145599.png)

For the button below clicking it yields no effect...

![Screenshot from 2022-03-16 09-49-00](https://user-images.githubusercontent.com/6928740/158507224-140f5b7f-700c-47f0-9853-113610e78705.png)

You need to click exactly the text. Clicking outside it has no effect.

Finally clicking the email address or button text works.

![Screenshot from 2022-03-16 09-49-04](https://user-images.githubusercontent.com/6928740/158507344-6c265904-2a9e-4867-a72d-b1fe391dd35b.png)

**Comment by hoangdat** [comment]
cool for you to detect that, it is the known issue in flutter. @dab246 said, the below `htmlView` stole the focus of this dialog :)

**Comment by dab246** [comment]
This bug no longer exists on the current version.
