### ISSUE TITLE
Today I cannot open the composer

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#351]
https://user-images.githubusercontent.com/6928740/158510704-b6f99143-56e7-42e8-8ef3-564f873f5af6.mp4

CTRL + F5 and this was working!

No details in error console.

**Comment by hoangdat** [comment]
> No details in error console.

maybe `tmail.linagora.com` is built in release mode, so no log are dumped. I will test more.

**Comment by chibenwa** [comment]
> maybe tmail.linagora.com is built in release mode, so no log are dumped. I will test more.

Can we switch the build to have testing output on by default?

**Comment by hoangdat** [comment]
@Arsnael , please read the docs: https://docs.flutter.dev/testing/build-modes and update the `docker file`. I still stuck in some critical bugs :(

At a glance: only change to `flutter build web --debug`

**Comment by Arsnael** [comment]
@hoangdat : seems not :D => https://github.com/flutter/flutter/issues/96283

The web part is far being as mature as the mobile...

Will check a bit more to see if there is alternatives

**Comment by Arsnael** [comment]
@hoangdat the best I could find: https://stackoverflow.com/questions/59710360/how-to-build-flutter-web-app-in-debug-mode

```
flutter build web --profile --dart-define=Dart2jsOptimization=O0
```
Not exactly as good as debug as people seem saying, but the closest you could get? Might give you error traces from what I can read...

Wanna give it a shot? :)

**Comment by hoangdat** [comment]
`--profile` is ok. 
But `--dart-define=Dart2jsOptimization=O0` for what?

**Comment by Arsnael** [comment]
@hoangdat you know my flutter knowledge is highly limited, not even sure what profile is for... You are the expert :D 

But with a quick search: https://dart.dev/tools/dart2js

that defines pretty much the degree of optimization when flutter converts dart to js. With O0 you disable most optimization, maybe suitable the time to debug? (O1 being the default that I guess we have currently?)

**Comment by chibenwa** [comment]
Mmh I'm not fan of not running the same stuff in prod and tests.

I'd prefer not downgrading the optimisation level.

**Comment by Arsnael** [comment]
> Mmh I'm not fan of not running the same stuff in prod and tests.

Ah cause we have a testing machine now for flutter web? I didn't know :o (yes I'm being sarcastic)

**Comment by Arsnael** [comment]
Well let's start with profile then...

**Comment by chibenwa** [comment]
> Ah cause we have a testing machine now for flutter web? I didn't know :o (yes I'm being sarcastic)

The day you package it in a HELM chart and put it on preprod, dude: https://github.com/linagora/james-project-private/issues/353

**Comment by chibenwa** [comment]
>  a testing machine now for flutter web

To be fair we don't need a testing machine dedicated to tmail web, it's just a tiny tiny NGinx container.

> (yes I'm being sarcastic)

You should not.

**Comment by Arsnael** [comment]
@hoangdat https://github.com/linagora/tmail-flutter/pull/365

**Comment by Kevinle2312** [comment]
Passed on CI platform.

https://user-images.githubusercontent.com/32490981/162148462-8730ebbc-22d7-4e55-805f-455d28e664f2.mp4
