### ISSUE TITLE
[Web] The box shadow of the “+” button is overlap and hidden a bit on the left and bottom

### ISSUE THREAD

**Issue by tuanlc** [linagora/tmail-flutter#353]
### Description
Hello Tmail team,

Please see the issue in the screenshot

### Expected result
Should have more space for the box shadow

### Current behavior
![image](https://user-images.githubusercontent.com/7950991/158523927-521d49b9-cf48-4e46-8fd4-cca58b133cd0.png)
#### Reproduction Steps
- Login to app
- Hover the mouse to the "+" button as the screenshot
- Reproduce the issue

### Devices, OS
- Firefox / Desktop / Web

**Comment by huy-ta** [comment]
Related: The “X” button in the mail composer has a way too big ripple effect, so it looks cropped.

![image](https://user-images.githubusercontent.com/24670327/158733380-527fdc1a-4d91-43dd-8472-23c8b9098caf.png)

**Comment by hoangdat** [comment]
fixed in the latest version
