### ISSUE TITLE
[Web - Enhancement] Creating mailbox feature: The red error message should not display if I haven't touch to the input

### ISSUE THREAD

**Issue by tuanlc** [linagora/tmail-flutter#354]
### Description
-  When the popup opens to create a new mailbox, the red error message is already there without any interact from users. This isn't a friendly UX
![image](https://user-images.githubusercontent.com/7950991/158524509-942bef56-b4a3-4c7e-a3e1-29c1c807782a.png)

### Expectation
- The red error message should display if I already focus on the input and leave it empty

**Comment by Kevinle2312** [comment]
PAssed on Pre-production and Production platform.
