### ISSUE TITLE
[Web - Enhancement] The empty mailbox message isn't correct when filtering

### ISSUE THREAD

**Issue by tuanlc** [linagora/tmail-flutter#355]
### Context
- When I use the filtering feature on a mailbox. If there is no email satisfies the criteria, the message says "No email in this mailbox". It is incorrect since there are emails in the mailbox.

![image](https://user-images.githubusercontent.com/7950991/158525154-4e01293c-ae98-4aa5-92e9-f8fece49506a.png)

### Expectation
- Having a better message when filtering to avoid confusing meaning

**Comment by chibenwa** [comment]
Exemple of better message: `No emails in this mailbox matches your current filters.`

**Comment by hknguyen91** [comment]
https://www.figma.com/file/rRVxJpCu1G22D0jqyvK7I9/TeamMail?node-id=5128%3A230972
