### ISSUE TITLE
Avoid loading so many fonts!

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#357]
### Description

![Screenshot from 2022-03-16 13-09-56](https://user-images.githubusercontent.com/6928740/158527475-b41fb967-d9fd-43c9-a216-2fa76fda2cf0.png)

Appart from the dart main, all heavy assets are fonts totalling 5.4 MBs.

I do not think we need so much fonts. Can't we rely on some standard ones?

Getting this solved will handle way quicker loading times!

**Comment by hoangdat** [comment]
As the confirmation, we only use `Inter` font

**Comment by chibenwa** [comment]
So... Where does these fonts come from? Some flutter defaults?

**Comment by chibenwa** [comment]
Quick google search and I think `SF pro` font is used by flutter internally.

**Comment by Kevinle2312** [comment]
PAssed on Production platform.
