### ISSUE TITLE
flutter build web --analyse-size

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#358]
### Description

Understand why the dart main is 3.5 MBs and what we can do about it.

![Screenshot from 2022-03-16 13-09-56](https://user-images.githubusercontent.com/6928740/158528164-bed4f5d5-7f1d-42f5-b07e-91069374e5c9.png)

**Comment by hoangdat** [comment]
Hi @chibenwa, @dab246 implemented lazy-loading for web-mail, but he also suggests us to enable gzip compresion on web-server. WDYT?

**Comment by Arsnael** [comment]
if you can do some compression I personally think it's good yes :)

**Comment by chibenwa** [comment]
Yes it's a must have, that's some easy NGinx tuning.

Also out of my head upon more stable deployments we should set up cache headers (1 day ?).
