### ISSUE TITLE
[Story] As a user, I want to open a link in email (mobie + tablet+browser)

### ISSUE THREAD

**Issue by dieptran88** [linagora/tmail-flutter#359]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC

* TODO: {link}

### UC1. Open a link which is a web address

- Given that I am a Tmail user 
- I logged-in successfully and open an email that contains a link to a web address (URL)

**1. In the mobile/tablet app**

   - When I click in the link, depending on the device setting, it will open the web address automatically on the default browser or open the dialog that asking me what browser I want to use to open the link
   - I can select a browser from the list, then it will open the web address in selected browser 

**2. In the Tmail web app**
   - When I click the URL link in TMail web app, it will open the web address in the new tab 

### UC2. Open a link which is a mailto link

- Given that I am a Tmail user 
- I logged-in successfully and open an email that contains a link to a mailto link (an email address)

**1. In the mobile/tablet app (inside app)**
   - When I click on the mailto link, the Tmail app will open a new composer, in which the field "To" is filled automatically with the email address from the mailto link.
**2. In the Tmail web app**
   - When I click on the mailto link, a new composer will be opened automatically on the current screen, and the field:"To" is filled automatically with the mail address from mailto link.

### UC3. Open mailto link outside the Tmail app in mobile/tablet. 

-  When I click a mailto link outside the Tmail app, depending on the device setting, it will automatically open a new composer of the default mail app, or display a dialog that asking me which mail app is used to open the mailto link.
- I can see Tmail  app icon as one of the options in the list and I select Tmail app
- If I am already logged-in, a new browser is opened  in which the field :"To" is filled  automatically with the mail address from mailto link.
- If I have not logged-in, the log-in screen of Tmail app will be opened. After logged in successfully, a new browser is opened in which the field :"To" is filled  automatically with the mail address from mailto link.

### UC4. Set Tmail as a default app in my device

- Given that I am Tmail app user
- I have installed Tmail app in my mobile/tablet
- When I I open screen Setting default email of system, I can see the list of all mail apps which are installed in my device and I can see option Tmail 
- After I select Tmail as default mail app, If I click on a mailto link outside of Tmail, then Tmail is automatically used to opened this mailto link

[Back to Summary](#summary)

## Screenshots

![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/1a116bec-fed6-49d4-8614-3d5decf8e33e) 
 ![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/4d33d89a-985c-4fec-a802-1a12669c0d17)
![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/f901e6b4-8ca0-4a48-aaea-b8bac7e3f843)

[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

**Comment by dieptran88** [comment]
@hoangdat Do you think we need design for this story ?

**Comment by hoangdat** [comment]
IMO, no :)

**Comment by Kevinle2312** [comment]
Passed on the Production platform.
