### ISSUE TITLE
[Web] The chips in the “From” and “To” fields are properly vertically aligned

### ISSUE THREAD

**Issue by huy-ta** [linagora/tmail-flutter#360]
### Current behavior

The chips in the “From” and “To” fields are properly vertically aligned.

![image](https://user-images.githubusercontent.com/24670327/158733806-eb275211-82f3-4c38-b8dc-59398378796e.png)

### Expected behaviour

They should be properly vertically aligned.

### Devices, OS

- Chrome / Ubuntu Desktop / Web

**Comment by chibenwa** [comment]
@hoangdat still relevant with new composer UX ?

**Comment by hoangdat** [comment]
<img width="824" alt="image" src="https://user-images.githubusercontent.com/6462404/158737926-18bdaa8c-d1fb-4a9b-bef6-075f4a335a51.png">

yes.

**Comment by hoangdat** [comment]
But for the Design, many changes will be occurred. At the moment, it is still ok.
