### ISSUE TITLE
[Web] Switching back and forth quickly between mailboxes sometimes displays the previously selected mailbox, but not the current one

### ISSUE THREAD

**Issue by huy-ta** [linagora/tmail-flutter#361]
### Reproduction steps

1. Switch to INBOX
2. **Quickly** switch to Outbox
3. **Quickly** switch back to INBOX

### Current behavior

- The content of Outbox will be displayed instead of INBOX. Also there's UI flashes when switching back & forth.

### Expected result

- The content of INBOX should be displayed.

### Devices, OS

- Chrome / Ubuntu Desktop / Web

### Reproduction video

https://user-images.githubusercontent.com/24670327/158734658-774d3885-9fe1-4ac7-ac4b-b3b2862c14e6.mp4

**Comment by hoangdat** [comment]
issue will be resolved in #356

**Comment by chibenwa** [comment]
Mmmh maybe we need QA validation before closing issues. Can we have a QA pipeline in ZenHub?

**Comment by hoangdat** [comment]
oh, it is closed when i merge the PR :), yes, we have

**Comment by Kevinle2312** [comment]
Passed on CI platform.

https://user-images.githubusercontent.com/32490981/162144961-0ca5a6a6-f926-4af6-b135-f356bc0ff0ea.mp4
