### ISSUE TITLE
On the composer, I have to leave the pointer to stay focused on the field and press enter button for the email to be accepted

### ISSUE THREAD

**Issue by Kevinle2312** [linagora/tmail-flutter#368]
### Description
On the composer, I have to focus the pointer on the To field and press enter button for the email to be accepted.

### Expected result
I don't have to focus the pointer on the To field to complete the email.

### Current behaviour
I have to focus the pointer on the To field and press enter button for the email to be accepted.

### Context

Devices, OS
tmail.linagora.com

### Additional information

frequency, log files,...

**Comment by chibenwa** [comment]
Duplicates https://github.com/linagora/tmail-flutter/issues/338 

Relates to https://github.com/linagora/tmail-flutter/issues/327

**Comment by chibenwa** [comment]
And **please** take screenshot, record video and remove unrelevant parts from issue template.
