### ISSUE TITLE
[WEB] very small screen: download closes EMail

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#369]
### Description

https://user-images.githubusercontent.com/6928740/158928574-0e4ff779-8450-4fbb-9354-b2a78c012d56.mp4

Question: does this also happens on mobile?

**Comment by dab246** [comment]
I do not understand what you mean? Please be more specific.

**Comment by chibenwa** [comment]
Look what happens at second 04: I click download attachment and it closed the email...

Still happens today BTW

**Comment by Kevinle2312** [comment]
Passed on CI platform.

https://user-images.githubusercontent.com/32490981/162138790-50aa2977-8aaa-4a7f-8528-e2399bdd9b36.mp4
