### ISSUE TITLE
Looks like drafts no longer works with the new composer....

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#370]
### Description

https://user-images.githubusercontent.com/6928740/158929099-7eb86138-c588-4bb9-afe7-2fb0b18a64d6.mp4

**Comment by chibenwa** [comment]
Fun fact: draft are saved when sending emails!

Fun fact: the draft is completly unusable...


https://user-images.githubusercontent.com/6928740/158930039-6e06efc6-94e3-4b7e-befe-cb1ae739aefb.mp4

**Comment by Kevinle2312** [comment]
Failed on CI platform. I can't save a draft when clicking the "Save fraft" button.

https://user-images.githubusercontent.com/32490981/162387209-9105358d-8197-49c0-8244-78b60087b59a.mp4

**Comment by dab246** [comment]
Related [#475](https://app.zenhub.com/workspaces/tmail-flutter-60d039db6ef62a0013432c14/issues/linagora/tmail-flutter/475)

**Comment by hoangdat** [comment]
confirmed draft is not work when click `Save to draft`

**Comment by Kevinle2312** [comment]
Passed on Pre-production and Production platform.
