### ISSUE TITLE
[Move folder] - I can not move emails from the parent folder to the child sub-folder

### ISSUE THREAD

**Issue by Kevinle2312** [linagora/tmail-flutter#371]
### Description
I have a parent folder A. I create a child subfolder B. I can move emails to A but I can not move emails to B.

### Expected result
I can move emails to a subfolder.

### Current behaviour
I can only move emails to a parent folder.

#### Reproduction Steps
1. Sign in to the mailbox
2. Choose emails
3. Click move and choose the destination
4. Verify the issue

### Context

tmail.linagora.com

### Additional information

frequency, log files,...

**Comment by chibenwa** [comment]
Please record videos for your bug reports! That's not PO/DEV roles to gather information after the initial reports.

I cannot reproduce BTW


https://user-images.githubusercontent.com/6928740/158937117-f53f0eed-0edf-4c10-95b9-aa96c942f76c.mp4

**Comment by Kevinle2312** [comment]
@chibenwa I have just re-verified, it is OK now. I will close the issue here.
