### ISSUE TITLE
[Delete mailbox]- After deleted a mailbox, tmail does not refresh and update the result

### ISSUE THREAD

**Issue by Kevinle2312** [linagora/tmail-flutter#372]
### Description
I create folder A. I add some emails in A. I click into the A folder to display its content. After that, I delete  A and all emails inside A is still displayed. It was not until I refresh tmail manually, the result is updated: All emails inside folder A is gone)

### Expected result
After deleting, tmail page is refreshed or updated, all email inside that folder should not be displayed.

### Current behaviour
All the email in side the deleted folder is displayed after deleting.

#### Reproduction Steps
1. Sign in to tmail
2. Create a folder and move some emails in
3. Click into that folder to display the folder content
4. Delete the folder and verify the issue

### Context

tmail.linagora.com

### Additional information

https://user-images.githubusercontent.com/32490981/158938759-da486c5d-eaa1-4c60-8699-0205f3d9c446.mp4

**Comment by chibenwa** [comment]
Yes this one qualifies :-)

> After deleting, tmail page is refreshed or updated, all email inside that folder should not be displayed.

After deleting currently selected mailbox / email switch back to INBOX?

**Comment by Kevinle2312** [comment]
Passed on CI platform.

https://user-images.githubusercontent.com/32490981/162396264-72d967d6-51bc-48e5-ad82-86f414b45373.mp4
