### ISSUE TITLE
[Mailbox] - Remove the real time validate of the mailbox name field 

### ISSUE THREAD

**Issue by Kevinle2312** [linagora/tmail-flutter#377]
### Description
Upon opening the folder creation form, the field "Enter mailbox name" immediately turns red. 

### Expected result
Change to validation upon clicking the "Done " button

### Current behaviour
Upon opening the folder creation form, the field "Enter mailbox name" immediately turns red. 

#### Reproduction Steps
1. Sign in to tmail
2. Click on "+" button
3. Verify the issue

### Context

tmail.linagora.com

### Additional information

![image](https://user-images.githubusercontent.com/32490981/158989089-16f158ba-9a44-42a6-a7f7-6a368018d424.png)

**Comment by chibenwa** [comment]
Duplicates https://github.com/linagora/tmail-flutter/issues/354
