### ISSUE TITLE
[tmail]- After refreshing, tmail displays only the loading screen

### ISSUE THREAD

**Issue by Kevinle2312** [linagora/tmail-flutter#380]
### Description
After refreshing, tmail only displays a loading screen. I have to delete this part out of the URL ; "/#/mailboxDashBoard" and refresh it again to make it works.  

### Expected result
I can refresh the tmail page.

### Current behaviour
After refreshing, tmail only displays a loading screen

#### Reproduction Steps
1. Sign in to tmail
2. Refresh tmail
3. Verify the issue

### Context

tmail.linagora.com

### Additional information

https://user-images.githubusercontent.com/32490981/158995357-5b736aac-3faa-4dec-a0f1-8c71d9360b08.mp4

**Comment by chibenwa** [comment]
Duplicate
