### ISSUE TITLE
Jmap-perl proxy backend

### ISSUE THREAD

**Issue by SurajDadral** [linagora/tmail-flutter#383]
Hi There,

Can you please confirm if this app works fine with [jmap-proxy server](https://github.com/jmapio/jmap-perl).
I am facing same issue as in: https://github.com/linagora/tmail-flutter/issues/319#issuecomment-1068981543

Thanks,

**Comment by hoangdat** [comment]
Can you share to me a credential to access your server?

**Comment by chibenwa** [comment]
Hello @SurajDadral 

Currently we only support https://github.com/linagora/tmail-backend as a backend.

We of course plan to work on inter-operability in the near future. Contributions in that direction are furthermore very welcome.

Regards.

**Comment by SurajDadral** [comment]
Thanks @chibenwa for confirmation.

**Comment by SurajDadral** [comment]
> Can you share to me a credential to access your server?

Hi @hoangdat 

Unfortunately not because I hosted that in local environment.

Thanks,

**Comment by chibenwa** [comment]
> Thanks @chibenwa for confirmation.

One of the goals that I have in mind is support for FastMail. This would then ensure us inter-operability.

Regarding the team priority:
 - Finish implementing vital, essential features and polish them (currently in progress)
 - Support for the JMAP PUSH through a PUSH gateway.
 - Then we will add support for OIDC 
 - Then inter-operability with FastMail
 
 I expect it takes a few more month to get there.
 
 In the meantime, if contributors feels like adding such support we would happily welcome the contributions!
