### ISSUE TITLE
Reply/forward: Display information of recipients is not carried other

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#384]
### Description

I receive an email. It has display information:

![01](https://user-images.githubusercontent.com/6928740/159241115-5eb07655-692a-4db0-9fd5-5c52f3bd39c5.png)

I reply to it...

![02](https://user-images.githubusercontent.com/6928740/159241146-93137334-94ef-421f-8c73-b84776854df2.png)

Then we do not carry over the display information (email address only)

I send the email.

![03](https://user-images.githubusercontent.com/6928740/159241256-fad6e17e-a4b7-4251-8634-8f9e70c8006a.png)

The receiver of the forwarded email should see the display information, but currently only see the email address.

### Expected behaviour

Replies / forward should preserve display information when available.

**Comment by hoangdat** [comment]
I still not understand this issue

**Comment by chibenwa** [comment]
Nevermind OpenPaaS is not doing it either, let's make our life simpler and not do it just yet.
