### ISSUE TITLE
[iOS] Empty body when opening a mail

### ISSUE THREAD

**Issue by Arsnael** [linagora/tmail-flutter#385]
### Description

Sometimes when I open a mail, the body is empty (and i know it should not).

### Expected result

It should show the body

### Current behavior

It doesn't...

#### Reproduction Steps

Open mails until you can experience it... Honestly it seems absolutely random. I saw it twice this morning and then when I thought ok I will take a screenshot on the next one, I spent 10 minutes opening mails but could not reproduce anymore T_T or maybe with my network IDK...

### Context

Iphone 11, iOS 15.4

**Comment by chibenwa** [comment]
Share the EML please :-P

**Comment by chibenwa** [comment]
And screenshots

**Comment by Arsnael** [comment]
as I said I could not reproduce it after unfortunately... it's like very random :( next time I see it though I will

**Comment by Kevinle2312** [comment]
I have not experienced this issue. I will close the issue here and re-open it if this happens to me. @chibenwa @Arsnael
