### ISSUE TITLE
UX : Rework the select items in a message list in edit mode

### ISSUE THREAD

**Issue by Arsnael** [linagora/tmail-flutter#386]
I'm surprised I didn't see a ticket yet regarding this... Honestly I keep being very frustrated with that, on mobile (iOS and android) because I have big fingers, on tmail-web because well I like to click and select my items quickly...

![tmail-web](https://user-images.githubusercontent.com/9005025/159399435-4783ead4-19dd-4c0a-b5e0-9197a723eebd.png)

As shown on the above picture, when in edit mode on a message list, only the circle (filled in green) is valid for selection. If you click a bit outside of it (and it's the same on mobile), it opens the message instead and you loose the edit mode and all your selection and you have to restart right away. And... I'm very frustrated to have to do it many times before accepting to go slow enough because you have to be super precise TBH

I would expect at least all the blue area rectangle in edit mode to be clickable for selection. I would even go further (but that's opened to discussion) to say the all item area (red rectangle) should be clickable for selection in edit mode. If we choose explicitly edit mode, it's because we want to perform on operation on a batch of selected mails, not opening one in the middle and dropping the current selection. So I don't think this behavior makes sense here.

WDYT?

**Comment by Kevinle2312** [comment]
1. I checked the web version and all circle is clickable. 
2. The issue when the user clicks a bit outside of the selection zone still persists. Should we close the issue here? @chibenwa @hoangdat

**Comment by chibenwa** [comment]
A quick win could be to make the selectable round bigger.

I think extending a bit the focus around the round itself could be acceptable.
