### ISSUE TITLE
Attach files in iOS app, but can not open attachments in web-mail app

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#387]
### Desc:

Attach files in iOS app, but can not open the attachments in web-mail app

### Reproduce:

- open the app in iOS
- compose a mail
- attach some images
- send to some userB
- userB uses web-mail to open the received email
- download attachments
- Can not open

### Context: 
- Chrome
- v0.2.1 in both platforms

**Comment by Kevinle2312** [comment]
@hoangdat I tested on tmail.linagora.com today and found out that all attachments send from tmail all have this issue (from web and app)

**Comment by dab246** [comment]
@chibenwa  Can you send me sample example for email sending api with attachment? I want to test my api again.

**Comment by dab246** [comment]
Is it correct to request API send email with attachment like this?

````
{
    "using": [
        "urn:ietf:params:jmap:submission",
        "urn:ietf:params:jmap:mail",
        "urn:ietf:params:jmap:core"
    ],
    "methodCalls": [
        [
            "Email/set",
            {
                "accountId": "3ce33c876a726662c627746eb9537a1d13c2338193ef27bd051a3ce5c0fe5b12",
                "create": {
                    "dab1234": {
                        "id": "dab1234",
                        "mailboxIds": {
                            "5dfb3290-0a14-11ec-b57c-2fef1ee78d9e": true
                        },
                        "subject": "test send email",
                        "from": [
                            {
                                "name": "userB",
                                "email": "userb@qa.open-paas.org"
                            }
                        ],
                        "to": [
                            {
                                "name": "DatX",
                                "email": "datx1995@gmail.com"
                            }
                        ],
                        "attachments": [
                            {
                                "blobId": "uploads-64b52d70-ab63-11ec-90ba-e169393c493e", 
                                "size": 2967966, 
                                "name": "IMG_0019.PNG", 
                                "type": "image/png", 
                                "disposition": "attachment"}
                        ],
                        "htmlBody": [
                            {
                                "partId": "mmm",
                                "blobId": "aaaa",
                                "type": "text/html"
                            }
                        ],
                        "bodyValues": {
                            "mmm": {
                                "value": "<!DOCTYPE html> <html> <body> <p><b>Hello test send 2</b></p><br><br></body> </html>",
                                "isEncodingProblem": false,
                                "isTruncated": false
                            }
                        },
                        "header:User-Agent:asText": "Android/XXX TeamMail/1.0"
                    }
                },
                "destroy": ["f5ec8c60-92e1-11ec-984e-e3f8b83572b4"]
            },
            "c0"
        ],
        [
            "EmailSubmission/set",
            {
                "accountId": "3ce33c876a726662c627746eb9537a1d13c2338193ef27bd051a3ce5c0fe5b12",
                "create": {
                    "a1234": {
                        "emailId": "#dab1234",
                        "envelope": {
                            "mailFrom": {
                                "email": "userb@qa.open-paas.org"
                            },
                            "rcptTo": [
                                {
                                    "email": "datx1995@gmail.com"
                                }
                            ]
                        }
                    }
                },
                "onSuccessUpdateEmail": {
                    "#a1234": {
                        "mailboxIds": {
                            "5dfb3290-0a14-11ec-b57c-2fef1ee78d9e": true
                        }
                    }
                }
            },
            "c1"
        ]
    ]
}
````

**Comment by hoangdat** [comment]
@chibenwa please take a look on it, this kind of issue was occurred some month ago. We really want to kill it before alpha@linagora

**Comment by chibenwa** [comment]
I would say you might not need to specify the size of attachments in `Email/set`:

```
["Email/set", {
      "accountId": "$ACCOUNT_ID",
      "create": {
        "aaaaaa": {
          "mailboxIds": {
             "${mailboxId.serialize}": true
          },
          "subject": "World domination",
          "attachments": [
            {
              "blobId": "$blobId",
              "type":"text/plain",
              "charset":"UTF-8",
              "disposition": "attachment"
            }
          ]
        }
      }
    }, "c1"]
```

(From james test suite).

We can get rid of it IMO.

Also, this might be related to the missing `Content-Transfer-Encoding` header. In which case it would be a James bug. (99% sure of this)

@Kevinle2312 please share the EML of the message!

**Comment by Kevinle2312** [comment]
@BenoitTallandier Here you go: https://wetransfer.com/downloads/4682cf5f155d633a093ce64d3d311fba20220328023554/470046

**Comment by chibenwa** [comment]
It's @chibenwa . Benoit Tallendier is the twake PO

**Comment by chibenwa** [comment]
BTW I confirm this is fucked up without transfer encoding.

![Screenshot from 2022-03-28 10-29-27](https://user-images.githubusercontent.com/6928740/160321748-92d49311-a11b-4223-b4ab-839410e528ce.png)

@Kevinle2312 can you confirm this is not just an IOS bug but that you can't open the sent attachment whatever the platform? (Android, tmail.linagora.com ) ?

**Comment by Kevinle2312** [comment]
@BenoitTallandier No. It is on all platforms (iOS, Android, tmail.linagora.com). As I said, I tested 3 cases, all of them have this issue:  
- Case 1: from webmail to webmail
- Case 2: from app( bother iOS and Android) to webmail
- Case 3: from app to app

**Comment by Arsnael** [comment]
Stop tagging the wrong Benoit ahah

**Comment by Kevinle2312** [comment]
> Stop tagging the wrong Benoit ahah

SOrry m bad :(( . I fixed it.

**Comment by chibenwa** [comment]
Ok I confirm this is https://github.com/apache/james-project/pull/927 ...

**Comment by Kevinle2312** [comment]
Passed on CI platform.

**Comment by hoangdat** [comment]
@Kevinle2312 please read the comment: https://github.com/linagora/tmail-flutter/issues/387#issuecomment-1080203238

**Comment by Kevinle2312** [comment]
@chibenwa This morning, I test the following case: 
1. Upload a video as an attachment on the iOS app
2. Send the email from the iOS app to a Gmail account
3. Download the video on the Gmail site and the video file is corrupted.

**Comment by hoangdat** [comment]
@Kevinle2312 please add more information: what environment?. It is important, we have a ton of environment. Hard to give the diagnosis without it.

**Comment by Kevinle2312** [comment]
I tested it on 2 environments today: 
- On tmail.upn.integration-open-paas.org: I have this problem
- On openpaas.upn.integration-open-paas.org: This problème does not happen.

@chibenwa @hoangdat

**Comment by hoangdat** [comment]
> apache/james-project#927

Any update from your site @chibenwa, what environment we have the fix?

**Comment by Kevinle2312** [comment]
> what did you test on `openpaas.upn.integration-open-paas.org`? Why we need to care about that here?

I try to send an email from that platform to a gmail account. When I received the attachment on gmail site, the file is fine.

**Comment by hoangdat** [comment]
working well with v0.3.6 in Preprod
