### ISSUE TITLE
Can not see the attachment in EmailView although we can see attachment icon in the ThreadView

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#389]
<img width="1792" alt="Screen Shot 2022-03-23 at 07 39 49" src="https://user-images.githubusercontent.com/6462404/159599518-99f1e26c-251a-48a0-acce-b9571e443d2d.png">

### Context: 
- v0.2.1
- issue in both mobile and web

**Comment by chibenwa** [comment]
JMAP `Email/get` request?

**Comment by hoangdat** [comment]
I see almost the attachment sent from `my client mail app (Apple mail - macOS)` have the same problem. @chibenwa please help me check the `eml` for the details information

[Re_ Authorization for PIT finalization 2021.eml.zip](https://github.com/linagora/tmail-flutter/files/8337789/Re_.Authorization.for.PIT.finalization.2021.eml.zip)

**Comment by chibenwa** [comment]
Well working with mime is shitty.

Here are the headers:

```
Content-Disposition: inline;
	filename*0="DatPHAM - Linagora - Authorization l etter for PIT finalization ";
	filename*1="(V)+(E).docx.pdf"
Content-Type: application/pdf;
	x-unix-mode=0644;
	name="DatPHAM - Linagora - Authorization l etter for PIT finalization (V)+(E).docx.pdf"
Content-Transfer-Encoding: base64
```

Inlined but no CID -> Should be displayed as an attachment in EmailDetailedView.

James should return it as part of `attachments` email property.

**Comment by Kevinle2312** [comment]
@hoangdat I can't see the attachment file on the Threadview but I can see the attachment on the Emailview.
![image](https://user-images.githubusercontent.com/32490981/162394606-deae779a-6caf-4c00-977c-6e1d90de72e9.png)

**Comment by hoangdat** [comment]
please show the screenshot for the `threadView` also

**Comment by Kevinle2312** [comment]
> please show the screenshot for the `threadView` also

![image](https://user-images.githubusercontent.com/32490981/162400114-7cfd89ae-98ac-4fcc-9d78-a5d82f5f1502.png)

**Comment by hoangdat** [comment]
is it here? 

![image](https://user-images.githubusercontent.com/6462404/162400988-b3192b18-b3c3-45b2-ae87-3a895e967f16.png)

**Comment by Kevinle2312** [comment]
> is it here?
> 
> ![image](https://user-images.githubusercontent.com/6462404/162400988-b3192b18-b3c3-45b2-ae87-3a895e967f16.png)

Got it, It only shows the icon when an email has attachments.
