### ISSUE TITLE
[WEB] Lost message when change size in Reply email

### ISSUE THREAD

**Issue by ducnm0711** [linagora/tmail-flutter#391]
### Description

Reply any emails, and toogle the size of the Reply box (Minimize, Fullscreen)

![chrome-capture-2022-2-23](https://user-images.githubusercontent.com/59911858/159616351-1468e18f-a203-42e8-a4ec-bf3ba43bef3c.gif)

**Comment by Kevinle2312** [comment]
PAssed on staging platfrom.
