### ISSUE TITLE
[Tmail-web] Calendar mail invites are not appearing in message list

### ISSUE THREAD

**Issue by Arsnael** [linagora/tmail-flutter#392]
### Description

In Tmail-web version, the emails with invites from calendar don't appear at all in the message list (while it does in iOS for example).

### Expected result

I can see the mail invite in my message list and open it

### Current behavior

Not appearing at all

#### Reproduction Steps

- Create an event in the calendar for the user
- check in mobile client for example the mail for the event is received
- check tmail-web -> absent!

### Context

tmail-web

**Comment by hoangdat** [comment]
> check in mobile client for example the mail for the event is received

you mean, `Alice` create event to `Bob`, then `Bob` check the email for the event but `Bob` can not see the email? Am I right?

**Comment by chibenwa** [comment]
Please take screenshots

**Comment by Arsnael** [comment]
> Please take screenshots

Screenshot of what? something that just does not show up? The reproducing steps described are clear enough as well IMO

> you mean, `Alice` create event to `Bob`, then `Bob` check the email for the event but `Bob` can not see the email? Am I right?

Pretty much yes... I could see that mail on the mobile app, but not the web version

**Comment by Arsnael** [comment]
> Please take screenshots

A  screenshot of what? the mail being there in the list in the mobile app and not the web app? Is that really relevant?

> you mean, Alice create event to Bob, then Bob check the email for the event but Bob can not see the email? Am I right?

Should have double checked sorry... After checking again and going backwards in the calendar events I got, it seems some others are showing. Maybe that one missing is not calendar related but something else...

Anyway here its eml:
[eml_missing_mail.txt](https://github.com/linagora/tmail-flutter/files/8338161/eml_missing_mail.txt)
