### ISSUE TITLE
[bug] ThreadView auto scroll up to the top after reading email

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#393]
https://user-images.githubusercontent.com/6462404/159828461-0cd311da-a4d0-459c-92c4-63ba91c69cfe.mov

### Context:
- chrome
- version > v0.2.1

### Expected:

`ThreadView` still keep the list position after comeback from `EmailView`

**Comment by Kevinle2312** [comment]
PAssed on CI platform.

https://user-images.githubusercontent.com/32490981/162399402-b1689d93-1233-49bf-a030-4f147b53e2bc.mp4
