### ISSUE TITLE
Double scrollbar is back

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#395]
![Screenshot from 2022-03-24 11-30-37](https://user-images.githubusercontent.com/6928740/159842623-c67d4608-e284-4516-84b0-2119f9f85f7a.png)

Chromium

**Comment by hoangdat** [comment]
https://user-images.githubusercontent.com/6462404/159843643-77d72295-9a4f-4ded-bbf2-f13858b7864d.mov

hmm, quite disturb with this kind of issue :(

**Comment by chibenwa** [comment]
$ chromium -version
Chromium 99.0.4844.82 snap

**Comment by hoangdat** [comment]
Firefox: 98.0.1 (64-bit) - macOS

double scroll bar at the beginning of loading mail, but when scroll, no problem

https://user-images.githubusercontent.com/6462404/159844457-510bc795-082c-4400-98e8-7c4959608316.mov

**Comment by hoangdat** [comment]
@chibenwa please update the next version, if no problem at all, we will add the improvement for this issue. We were hardworking on this problem. We don't want to spend more time on it for a specific browser.

**Comment by Kevinle2312** [comment]
Passed on Pre-production platform.
