### ISSUE TITLE
In email detailed view clicking mailboxes side panel is buggy

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#396]
### Description

In Email detailed view clicking the mailbox side panels navigates to a blanck page

### Expected result

Navigate to that mailbox email list view

### Current behavior

https://user-images.githubusercontent.com/6928740/159842897-b2e642c9-7a7c-404e-8e85-40bc3ac5a43f.mp4

### Context

Chromium

**Comment by Kevinle2312** [comment]
Passed on CI platform.

https://user-images.githubusercontent.com/32490981/162399887-279ec0d5-04e7-4e36-942b-30d4755a295c.mp4
