### ISSUE TITLE
Select all selects nothing

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#397]
### Description

https://user-images.githubusercontent.com/6928740/159843214-aa1eab65-eade-4470-9b7c-55dbd89d6fd5.mp4

### Expected result

Rename `Select all` to `Select several items` ?

**Comment by Arsnael** [comment]
Why I don't see those at all? I have a completely different UI than you on tmail.linagora.com
![web_ui_rene](https://user-images.githubusercontent.com/9005025/159846706-25f1e955-7ce8-4f2e-a30d-b854157c3476.png)

I'm dying to use that select all messages option

**Comment by Arsnael** [comment]
Ok chromium... how is the UI completely different between FF and chromium? :o

**Comment by hoangdat** [comment]
in firefox, maybe we still not reach the breakpoint to reach largest design. we will check it again.

**Comment by Arsnael** [comment]
I did open an issue though... https://github.com/linagora/tmail-flutter/issues/398

IDK what we can do about it but I find it concerning that the UI looks so different between two browsers

**Comment by Kevinle2312** [comment]
Passed on CI platform.
