### ISSUE TITLE
UI : Completely different UI between FF and chromium for tmail-web

### ISSUE THREAD

**Issue by Arsnael** [linagora/tmail-flutter#398]
### Description

FF:
![web_ui_rene](https://user-images.githubusercontent.com/9005025/159847423-df885175-e924-4f72-a62a-8f4b56e5f8f7.png)

Chromium:
![chromium_flutter](https://user-images.githubusercontent.com/9005025/159847545-61086d7a-170a-4036-b22f-af467c1a19bb.png)

### Expected result

Maybe something similar in terms of UI???

### Current behavior

Quite different IMO. Is this something we can work around or Google, because it's their framework, decided to do pretty much a big screw you on browsers not running the chrome engine like FF?

### Context

FF and chromium

**Comment by Arsnael** [comment]
You don't even see the compose button anymore on FF (how do I write a mail) neither the logo

**Comment by dab246** [comment]
> You don't even see the compose button anymore on FF (how do I write a mail) neither the logo

You are in selection mode so the compose button is hidden. You can click the back button to exit selection mode.

**Comment by Arsnael** [comment]
Fair enough, you were right!

Still the view is in mobile mode for some reason in FF, even when I'm using my big screen at home

**Comment by hoangdat** [comment]
> Fair enough, you were right!
> 
> Still the view is in mobile mode for some reason in FF, even when I'm using my big screen at home

yes, this issue is prioritized :)

**Comment by chibenwa** [comment]
IMO we could mark this as a FF issue and lower its priority. IMO good chrome support first is more important.

(Of course if someone already started working on this, then do it ^^)

**Comment by Kevinle2312** [comment]
PAssed on CI platform.
