### ISSUE TITLE
[Mailbox] - I can not mark all email as read. 

### ISSUE THREAD

**Issue by Kevinle2312** [linagora/tmail-flutter#401]
### Description
On thread view,  I can not  mark all email as read. I can only mark all email I see on the screen as read. When I scroll down, I have to mark it as read agian.

### Expected result
I can mark ALL email as read.

### Current behaviour
I can only mark all email I see on the screen as read.

### Context

tmail.linagora.com

### Additional information

https://user-images.githubusercontent.com/32490981/159865305-6a4509ad-a563-4241-928a-b46472315e72.mp4

**Comment by chibenwa** [comment]
Ok, this can be an improvment I believe.

Agree with this statement: 

 - Mark the cache as read then Email/query to get a new batch of unread + email/set until done.

**Comment by Kevinle2312** [comment]
I tested on the production today, It works fine. except for the case where over 1k emails I need to be mark as read. @hoangdat has already worked on a progress bar, so I will close it here.
