### ISSUE TITLE
[Mobile app] - Some emails do not fully displayed on the mobile version of tmail

### ISSUE THREAD

**Issue by Kevinle2312** [linagora/tmail-flutter#407]
### Description
Some emails do not fully display on the mobile version of tmail.

### Expected result
The title and sending address of an email should be fully displayed.

### Current behaviour
The first 5 emails are displayed with no address and title. 

#### Reproduction Steps
1. Sign in to the app
2. Open the tmail application on mobile
3. Verify the issue

### Context

iOS: test flight
Android: Preproduction platform

### Additional information

![image](https://user-images.githubusercontent.com/32490981/160312381-cc4b580f-7b3c-4f36-aeb3-f3ef4c16162e.png)

**Comment by chibenwa** [comment]
Duplicates https://github.com/linagora/tmail-flutter/issues/339
