### ISSUE TITLE
[Story] As a user, I want to refresh Tmail when I am in web browser

### ISSUE THREAD

**Issue by dieptran88** [linagora/tmail-flutter#408]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC

* TODO: {link}

## Definition
**UC1. Refesh in thread-view**
- Given that I am a Tmail user 
- I logged in Web app and see the thread view
- I can refresh page in several ways:
   - Click button  Refresh of the browser
   - Click button Ctr+F5
   - Click button Refresh at the top of thread-view  screen
- The current page will be re-loaded to sync all changes from server.
- In Loading-time I can see an loading icon that will be disappear after the refresh finished.

**UC2. Refesh when composing en email**

- Given that I am in a thread-view and click button Compose
- A new composer is displayed at default mode and  I start to input some fields 
-  Now I click button Refresh in one of 3 ways above, after loading, the composer is still kept as before with fields I have inputted 

[Back to Summary](#summary)

## Screenshots

None

[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

**Comment by ManhNTX** [comment]
PR : https://github.com/linagora/tmail-flutter/pull/704
