### ISSUE TITLE
Can't click calendar links....

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#411]
![Screenshot from 2022-03-28 16-28-42](https://user-images.githubusercontent.com/6928740/160369931-e97ba640-1380-44d0-96b0-c888d101eb7f.png)

**Comment by chibenwa** [comment]
Even the blue link `See in calendar` cannot be opened...

**Comment by hoangdat** [comment]
will be resolve with https://github.com/linagora/tmail-flutter/issues/335

**Comment by Kevinle2312** [comment]
@hoangdat @chibenwa Please deploy the fix on the Staging platform and I will re-test this issue on the Staging platform.

**Comment by chibenwa** [comment]
https://tmail.upn.integration-open-paas.org/

**Comment by Kevinle2312** [comment]
Passed on Pre-production platform
