### ISSUE TITLE
Offset upon copy-and-paste in plaint/text email body

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#414]
### Description

I select `defgh` copy, then paste it in a third party app and get `ghijk`.

https://user-images.githubusercontent.com/6928740/160379961-b75b83fd-1cab-4786-a940-9a6def8a0017.mp4

This is for text/plain email.

**Comment by dab246** [comment]
This error no longer appears at the latest version. Please check again @chibenwa

**Comment by chibenwa** [comment]
Still happens, but for emails in plain text.

You tried with an email in text/HTML.

**Comment by dab246** [comment]
Please watch the full demo video. I tried in text/plain text. 
Please try again carefully. !!!!!!!

**Comment by chibenwa** [comment]
OK I will try again tomorrow, changes are likely not deployed yet.

**Comment by Kevinle2312** [comment]
Passed on CI platform.

https://user-images.githubusercontent.com/32490981/162349850-26a59878-6b92-4864-bd19-8687a7dc07ec.mp4
