### ISSUE TITLE
Verify that all strings are registered for translation

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#415]
### Description

```
A quick remark: Please pay attention to use English/French words. Please choose between them but not both at the same time. Example "EDIT" then you have "Annuler"
```

Credit: Yazid Benazzouz

**Comment by chibenwa** [comment]
@Kevinle2312 can you please do a review of what is translated, and not translated and list it in the ticket?

**Comment by hoangdat** [comment]
@chibenwa that mean: `Edit` show when user chooses French?

**Comment by chibenwa** [comment]
Yes

**Comment by chibenwa** [comment]
We IMO need a review of what's not registered for translation.

**Comment by hoangdat** [comment]
okie, let me check. I will standalize the way we work with Weblate

**Comment by Kevinle2312** [comment]
> 

Yes I will do it.

**Comment by hoangdat** [comment]
> > 
> 
> Yes I will do it.

no need to action. I fixed this with new configuration in Weblate.

Root cause: `Edit` and some later string are not registered to translate.

I will close this issue and wait contribution in `weblate` to have it in production.
