### ISSUE TITLE
[Delete draft email] there is no button allowing me to delete draft mails

### ISSUE THREAD

**Issue by haftus98** [linagora/tmail-flutter#421]
### Description
I want to delete draft mails but there is no button allowing me to delete those.
### Acceptance criteria

The list of acceptance criteria (defined in the corresponding User Story or coming from your functional knowledge of the product)
These acceptance criteria must be met by the corrective implementation done by the developers.

### Context

Devices, OS

### Additional information

frequency, log files,...

**Comment by chibenwa** [comment]
Please cleanup the default template to ease readability.

+1 we need a `delete` (permanently) action in draft, and trash mailbox

For other mailboxes we need a "move to tash" button.

**Comment by hoangdat** [comment]
### Desc:

Permanent Delete interactor

**Comment by dab246** [comment]
### DoD
- Change tooltip name button delete to `Delete permanently` in `Trash` and `Draft` mailbox
- Change color button to red
![Screen Shot 2022-09-05 at 10.41.57.png](https://images.zenhubusercontent.com/605059df174a357c7888640f/f1dadc69-8db5-411e-b115-9c04fafa23ec)

**Comment by dab246** [comment]
1 HD

**Comment by haftus98** [comment]
verified on web + mobile
