### ISSUE TITLE
Unable to search recipient in composer

### ISSUE THREAD

**Issue by hantt12** [linagora/tmail-flutter#423]
### Description
When composing an email, user should be able to search recipient that is in his company or those who used to send to/receive emails from

### Current behavior
Unable to search

#### Reproduction Steps

Open email composer
Try to search ctlle

Expected: ctlle@linagora.com should be shown for selection

https://user-images.githubusercontent.com/53081477/160569216-a2a56555-01f0-4b9e-8b23-7dfadd0078de.mp4

**Comment by hoangdat** [comment]
Auto-suggestion not in the core capability of JMAP, will be added in extension.

**Comment by chibenwa** [comment]
Yes, known and correlated to the work of the backend team. Closing...
