### ISSUE TITLE
The margin between email header and body is too big

### ISSUE THREAD

**Issue by hantt12** [linagora/tmail-flutter#424]
### Description
when sending email from Tmail and recipient opens it in Tmail too, the margin is too big

### Current behavior
![image](https://user-images.githubusercontent.com/53081477/160571290-77ca07b8-e8fc-42ae-9e11-236ea6facb01.png)

#### Reproduction Steps
1. User A sends user B an email from Tmail
2. User B opens that email in Tmail

**Comment by Kevinle2312** [comment]
Passed on CI platform
![image](https://user-images.githubusercontent.com/32490981/162115902-4e53f16b-cffd-4b9b-a08c-42f599a861d5.png)
