### ISSUE TITLE
When sending email from Tmail and check email from other email client, it's automatically added <end> at the end of the email preview

### ISSUE THREAD

**Issue by hantt12** [linagora/tmail-flutter#426]
This does not happen if user sends email from Openpaas

![image](https://user-images.githubusercontent.com/53081477/160572832-3125a412-59b5-4826-a28f-4ed7c80b2fdf.png)

**Comment by chibenwa** [comment]
Share the EML please?

**Comment by hantt12** [comment]
Return-Path: <mtha@linagora.com>
Delivered-To: tthnguyen@linagora.com
Received: from 172.17.0.1 (EHLO incoming.linagora.com) ([172.17.0.1])
          by incoming.linagora.com (JAMES SMTP Server ) with ESMTP ID -1905049619
          for <tthnguyen@linagora.com>;
          Tue, 29 Mar 2022 08:45:11 +0000 (UTC)
Received: from smtp.linagora.com (smtp.linagora.com [54.36.8.78])
	by incoming.linagora.com (Postfix) with ESMTPS id 787769C621
	for <tthnguyen@linagora.com>; Tue, 29 Mar 2022 08:45:11 +0000 (UTC)
Received: from ?Open?PaaS?SMTP?server?for?Linagora? (unknown [51.83.109.124])
	(using TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits))
	(No client certificate requested)
	by smtp.linagora.com (Postfix) with ESMTPSA id 704CF40D4D;
	Tue, 29 Mar 2022 10:45:11 +0200 (CEST)
DKIM-Signature: a=rsa-sha256; b=eDpir5sj3jJ96nH+hcnZQoiwv5dB1iDK4CHhqjFrAL+bfHpa3EOGjiQ2xrNuoU6X/r0D9XgriPJko39el12CVo5/EDoux3HBCUiliuoO9wzkENO/QrLxEOeyqBjqpBFRhTo9F5uF1wSmn0C3ngpeWDLdLmV7uTDOpgv2P1XwPOgN1kxCnQpJj7WJP6O54Py8bb+1Zjrfl+/KKEoRmPU2iuyMjiV7Sxw/3Fm8pWtJFHkEZNAq9BNSrodI/vUhwObQIK4loH66Nlk23OgEFJU1+Z7MwdCiKlCxPmSOjJ95UmF3KjVUknvmOz1D7r2gWHSP9xWbghNSmD22uuDvOLMCFA==; s=smtpoutjames; d=linagora.com; v=1; bh=iVykouYX3AnAg9m9zKupYJuhLJzBA7iIdMMS2KWvB5Q=; h=from : reply-to : subject : date : to : cc : resent-date : resent-from : resent-sender : resent-to : resent-cc : in-reply-to : references : list-id : list-help : list-unsubscribe : list-subscribe : list-post : list-owner : list-archive;
Date: Tue, 29 Mar 2022 08:45:11 +0000 (UTC)
Message-ID: <1772693742.142.1648543511017@128593e93459>
MIME-Version: 1.0
Subject: =?UTF-8?Q?t=C3=BA_=C4=91=C3=A2y_budsbgurdg_r?=
 =?UTF-8?Q?dugbfudbgudfuobfdvbdf?=
X-LINAGORA-Copy-Delivery-Done: 1
From: mtha@linagora.com
To: tthnguyen@linagora.com
Cc: haminhtu@yopmail.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36
 (KHTML, like Gecko) Chrome/99.0.4844.82 Safari/537.36
Content-Type: multipart/alternative;
 boundary="-=Part.1f0.feb5115d92ce2427.17fd4d9af62.ca2dbf637f867732=-"

---=Part.1f0.feb5115d92ce2427.17fd4d9af62.ca2dbf637f867732=-
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: quoted-printable

ch=E1=BB=8B H=C3=A0 oiiiiiiiiiiiiiiii
---=Part.1f0.feb5115d92ce2427.17fd4d9af62.ca2dbf637f867732=-
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: quoted-printable

ch=E1=BB=8B H=C3=A0 oiiiiiiiiiiiiiiii
---=Part.1f0.feb5115d92ce2427.17fd4d9af62.ca2dbf637f867732=---

**Comment by chibenwa** [comment]
![Screenshot from 2022-03-30 10-38-53](https://user-images.githubusercontent.com/6928740/160746682-85f7bb6b-5757-43b9-8376-353df1ae0d0d.png)

Will result in the following EML:

```
Return-Path: <xxx@linagora.com>
Date: Wed, 30 Mar 2022 03:34:59 +0000 (UTC)
Message-ID: <2106884402.175.1648611299519@128593e93459>
MIME-Version: 1.0
Subject: Test
From: xxx@linagora.com
To: xxx@linagora.com
Content-Type: multipart/alternative;
 boundary="-=Part.249.bd9511f63e653445.17fd8e4080a.31fdeae67258b9ed=-"

---=Part.249.bd9511f63e653445.17fd8e4080a.31fdeae67258b9ed=-
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: quoted-printable

Toto test
---=Part.249.bd9511f63e653445.17fd8e4080a.31fdeae67258b9ed=-
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: quoted-printable

Toto test
---=Part.249.bd9511f63e653445.17fd8e4080a.31fdeae67258b9ed=---
```

The openpaas one looks like:

```
Return-Path: <xxx@linagora.com>
Delivered-To: xxx@linagora.com
MIME-Version: 1.0
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: quoted-printable
From: Benoit TELLIER <btellier@linagora.com>
Sender: Benoit TELLIER <btellier@linagora.com>
Reply-To: xxx@linagora.com
To: =?ISO-8859-1?Q?Beno=EEt_TELLIER?= <xxx@linagora.com>
Subject: Test
Message-ID: <Mime4j.24a.a0b31da9eb577623.17fd8e5d1a1@linagora.com>
Date: Wed, 30 Mar 2022 03:36:54 +0000

Toto test<br>
```

Several observtion:

 - We are missing the `Reply-To` header... CF https://github.com/linagora/tmail-flutter/issues/430
 - OpenPaaS adds a `<br>` in the HTML message, I believes this causes the difference in the rendering...

**Comment by Kevinle2312** [comment]
Failed on CI platform:
![image](https://user-images.githubusercontent.com/32490981/163313732-c23b7b23-cc6e-43ff-82e2-5aac499e11ff.png)
