### ISSUE TITLE
[Dev] Handle `StateChange` of mailbox

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#437]
### Desc:
- receive `StateChange`
- request `Mailbox/changes` with debounce
- update the cache
- refresh the UI

### DoD:
- UI is updated in the foreground
- No notification needed
- in the case of background, cache is up-to-date with new changes

**Comment by chibenwa** [comment]
Please add a debounce on `request Mailbox/changes` namely:

 - if another state change event was received less than 2 seconds ago then wait for up to those 2 seconds before the `request Mailbox/changes`
 
 IE we should not try to resynchronize ourselves more than once every 2 seconds.

**Comment by chibenwa** [comment]
- Register that UI should be updated on next load when we are in background

**Comment by hoangdat** [comment]
### DoD:
- [ ] Handle Mailbox `/changes` in foreground
- [ ] Handle Mailbox `/changes` in background/terminated

**Comment by hoangdat** [comment]
2HD
