### ISSUE TITLE
[Dev] Handle StateChanges for email

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#438]
### Desc:
- received message from Firebase 
- Decode message to StateChange 
- debounce call to `Email/changes` to get the detail (2000ms)
- show notification in the case of app in background and terminated

Background:
- only get change with old state of EmailDelivery (add state of EmailDelivery in cache)
- don't synchronize anything
- test with the case app in stack of recent app.

### DoD:
- notification as design in the case app in background/terminated
- UI update in the case app in foreground

**Comment by chibenwa** [comment]
Please add a debounce on `request Email/changes` namely:

 - if another state change event was received less than 2 seconds ago then wait for up to those 2 seconds before the `request Email/changes`
 
 IE we should not try to resynchronize ourselves more than once every 2 seconds.

**Comment by chibenwa** [comment]
- Register that UI should be updated on next load when we are in background

**Comment by hoangdat** [comment]
1HD

**Comment by hoangdat** [comment]
2HD

**Comment by hoangdat** [comment]
2HD
