### ISSUE TITLE
[Dev] Handle FCM token 

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#439]
### Desc:
If FCM is enabled, 
- [ ] if no token is registered, client should register `FirebaseRegistration/set`
- [ ] if token is registered, client should check the expired date (`tE`), if today is (`tE - 3 = t0`), extends the expired date to (`t0 + 7`)
- [ ] if FCM generate new token, make a request to (i) delete old token and (ii) register new one

### 
- Create `Stream<String> fcmTokenStream` in FCMService
- invoke getToken in FCMReceiver, push to `fcmTokenStream`
- register `onTokenRefresh`, push to `fcmTokenStream`
- FCMController will listen `fcmTokenStream`, handle it in FCMTokenHandler
- hash `token` to `deviceId`, 
- whenever have a token, hash it to `deviceId`, get from the back-end to check expiracy. handle it.
- store `deviceId`

```
class FCMTokenHandler {
  handle(String token) {
   
  }
}
```

**Comment by Arsnael** [comment]
Expiration time => You can always update the expiration time before it expires with the set method, to keep the subscription alive (up to the server-set limit)

If it's already expired you need to recreate a new subscription.

**Comment by dab246** [comment]
2 HD
