### ISSUE TITLE
[Story] As an user, I can compose an simple text email and send to someone

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#44]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC

[[Basic] Write emails](https://app.zenhub.com/workspaces/tmail-flutter-60d039db6ef62a0013432c14/issues/linagora/tmail-flutter/27)

### UC1: Compose and send an email with simple text
- Given that i am in one of the mail list
- I click on Create button, a new composer is opened. 
- On this composer, i can see :
   - Header fields include:
      - "From": My name + email address . I cannot edit this field 
      - "To" : There field is empty, i can input recipient here by email address:
         - When i start input character in this field, there will be a box below which reflects the inputted characters. If i click on this box, the system will check: 
            - If the email format is correct, that recipient will be added to the field :"To" and the suggested box disappear. 
            - If the email format is not correct, there will be an message: "Please add a valid email address".
         -  I can add several recipients in this field. 
         - I can remove recipient by using pointer cursor and button "Back" in keyboard
      - When i click on arrow next to field "To", i can see expanded field CC and BCC. I can add one or several recipients on these fields. 
      -  The Subject: A text field 
  - Email body: 
      - In the input section, I can write text  in simple mode and click button Send, if there is at least one recipient, the email is sent and the composer is closed. The email  is moved to mailbox Sent 
- If there is no recipient and i click the button Send, there will be an message popup "Your email should have at least one recipient"
- If  click button Cancel ,  the email will be removed. 

### UC2: Add recipient with auto-completion from local storage  

- when i sent an email successfully to a new recipient, then his email address will be saved to my local storage 
-  Given that i am opening a new composer 
-  In email address fields (To/CC/BCC), when i start to type some characters e.g "bob" then the system will search in local storage any email address that contains "bob". The matches will be displayed as a suggestion list, and i can select an recipient from this list.
- If there is no suggestion from local storage, the reflecting inputted character box will be appeared as UC1

[Back to Summary](#summary)

## Screenshots
![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/66d9da71-e0d5-493c-8eac-ad73da0c9354)  ![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/3902bc37-4991-47d3-b8b0-4003d71d8ccc)

![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/7a2ee179-2da3-484e-a070-5883349a3edf)  ![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/a938e702-d7eb-4afe-9f1e-71260647567c)

![image](https://user-images.githubusercontent.com/68209176/133421969-db144c25-03ec-4414-a1e5-9bcc224ef676.png) ![image](https://user-images.githubusercontent.com/68209176/133422217-ab1bab83-1867-400f-a9ca-10793312710d.png)

![image](https://user-images.githubusercontent.com/68209176/133422263-0f558e65-76ce-4152-8a17-9cb689d0ba5d.png)

![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/0d131c1f-d1c4-4e3f-ae07-99b5e0db1fd1)  ![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/65fb6792-56f6-471b-af3c-1b5ce9ff4f71)
![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/8f162bc9-8838-4eba-9546-5501e6a25923)

None

[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

**Comment by chibenwa** [comment]
We can split this story by options of the composer, I guess...

**Comment by hoangdat** [comment]
> We can split this story by options of the composer, I guess...

Can you suggest me some options?

**Comment by chibenwa** [comment]
Sure:

 - Step 1: Send text, no style
 - Step 2: Send some simple HTML (the composer allows some HTML options- bold, etc...)
 - Step 3: Send an email with attachments

**Comment by hoangdat** [comment]
@dieptran88 
UC1: please separate the constraint for UC1 to new use-case, and the save to draft to other new use-case. 

UC2: How about if no suggestion matched?

**Comment by dieptran88** [comment]
UC1. Ok i will seperate 
UC2. It can be same as UC1 : a reflecting inputted characters box will be appear as UC1. How do you think ?

**Comment by hoangdat** [comment]
> UC2. It can be same as UC1 : a reflecting inputted characters box will be appear as UC1. How do you think ?

not understand you, but please describe it in mockup

**Comment by dieptran88** [comment]
> > UC2. It can be same as UC1 : a reflecting inputted characters box will be appear as UC1. How do you think ?
> 
> not understand you, but please describe it in mockup

mockup updated.
