### ISSUE TITLE
[Folder-creation] - On thunderbird, I can name a folder after a special character

### ISSUE THREAD

**Issue by Kevinle2312** [linagora/tmail-flutter#444]
### Description
 On thunderbird, I use specials characters to name a folder.

### Expected result
I can not use specials characters to name a folder.

### Current behaviour
 On thunderbird, I use specials characters to name a folder.

### Context

Thunderbird

### Additional information

![image](https://user-images.githubusercontent.com/32490981/161189486-0dca7189-e2b9-449e-baed-7dee3524a2dc.png)

https://user-images.githubusercontent.com/32490981/161189505-bb9d2f61-6c67-4ce5-845c-9f48db2808d7.mp4

**Comment by Kevinle2312** [comment]
@chibenwa I tested with many special characters. I found that some characters are blocked by the system and I can not name the folder after it (# or /) while others (! or @) can.

**Comment by hoangdat** [comment]
can not understand the issue

**Comment by chibenwa** [comment]
> can not understand the issue

Me neither. Please @Kevinle2312  express yourself better.

**Comment by Kevinle2312** [comment]
> > can not understand the issue
> 
> Me neither. Please @Kevinle2312 express yourself better.

I have updated the issue

**Comment by hoangdat** [comment]
@Kevinle2312 please use the `user personas` template to describe the issue.

`“As a [persona], I [want to], [so that].”`

**Comment by Kevinle2312** [comment]
> @Kevinle2312 please use the `user personas` template to describe the issue.
> 
> `“As a [persona], I [want to], [so that].”`

GOt it. I will do it next time.

**Comment by chibenwa** [comment]
I still don't understand.

Please fill `Reproduction Steps` part.

**Comment by dab246** [comment]
@hoangdat  Do we need to support special characters in the name `mailbox`?. Currently the `TMail` application is set up to prevent special characters in the name `mailbox`
