### ISSUE TITLE
[EPIC] Sender Identity

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#447]

**Comment by chibenwa** [comment]
https://jmap.io/spec-mail.html#identities

**Comment by hoangdat** [comment]
@chibenwa can you show us the request to create/edit identity, we try with `/set` but it is not successfully

**Comment by chibenwa** [comment]
```
{
	"using": ["urn:ietf:params:jmap:core", "urn:ietf:params:jmap:submission"],
	"methodCalls": [
		[
			"Identity/set",
			{
				"accountId": "29883977c13473ae7cb7678ef767cbfbaffc8a44a6e463d971d23a65c1dc4af6",
				"create": {
					"4f29": {
						"name": "Bob",
						"email": "bob@domain.tld",
						"replyTo": [{
							"name": "Alice",
							"email": "alice@domain.tld"
						}],
						"bcc": [{
							"name": "David",
							"email": "david@domain.tld"
						}],
						"textSignature": "Some text signature",
						"htmlSignature": "<p>Some html signature</p>"
					}
				}
			},
			"c1"
		],
		["Identity/get",
			{
				"accountId": "29883977c13473ae7cb7678ef767cbfbaffc8a44a6e463d971d23a65c1dc4af6",
				"ids": null
			}, "c2"
		]

	]
}
```

For instance. Please note that the email needs to be the mail address of the user or a valid alias. Valid aliases can be obtained by Identity/get .

> we try with /set but it is not successfully

If possible share your errors...

**Comment by dab246** [comment]
@chibenwa . I'm doing the edit identity feature. I use SetMethod but get this error

<img width="1008" alt="Screen Shot 2022-05-06 at 12 49 32" src="https://user-images.githubusercontent.com/80730648/167075436-3189f021-fd5a-4598-8ddb-9036944ee130.png">.

**Comment by dab246** [comment]
Don't know if this bug has been fixed yet @chibenwa. I still get this error when I execute

**Comment by chibenwa** [comment]
> Don't know if this bug has been fixed yet @chibenwa. I still get this error when I execute

Yes, merged but not deployed yet. Hang on...

**Comment by chibenwa** [comment]
I deployed the fix on preprod

**Comment by chibenwa** [comment]
Wait tmail backend 0.6.0 to be released for openpaas.linagpra.com
