### ISSUE TITLE
enable gzip compression for webMail

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#450]

**Comment by chibenwa** [comment]
Can easily be done by the backend team.

**Comment by hoangdat** [comment]
> Can easily be done by the backend team.

if yes, please help us on back-end size. We are not deep on this topic, not to know any other config needed

**Comment by chibenwa** [comment]
Yes I created a task to do some easy NGINX config regarding this: https://github.com/linagora/james-project/issues/4509
