### ISSUE TITLE
[Web] Search boxes should be collapsed automatically if there is no keyword to search when search inputs lost focus

### ISSUE THREAD

**Issue by tuanlc** [linagora/tmail-flutter#452]
### Label
- Enhancement
- UI

### Context
- There are 2 search boxes on the UI: 
  - search mailbox
  - search email

- We can focus and leave inputs empty and there is no mailbox and email display as the screenshot

![image](https://user-images.githubusercontent.com/7950991/161697729-4ade802c-05e1-4e9b-a79f-c0a41ee85e36.png)

### Expectation
It would be nice if search boxes is collapsed automatically if I leave them empty and I blur them. Then all the mailboxes and emails appear when I don't search anything

**Comment by hoangdat** [comment]
1HD
