### ISSUE TITLE
[Story] As a user, I want to list all my identities

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#453]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC

* TODO: {link}

## Definition

- Given that I am a Tmail user 
- After log-in successfully to the Tmail web, I can see my avatar icon in top right of screen 
- When I click on this icon, I can see options: Log-out and Settings
- When I select option Settings, the screen Settings will be opened 
- In this screen, I can see the tab or menu with many settings item: but now Language and Identifies
- When I select Identifies, all of my identifies will be showed in brief: Name and Email

## Design ticket

https://ci.linagora.com/linagora/lgs/design/-/issues/172

[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

## Prototype

<img width="739" alt="image" src="https://user-images.githubusercontent.com/6462404/161735318-1270874d-b4da-460f-aef1-6c05db42e4a2.png">

**Comment by Kevinle2312** [comment]
PAssed on Pre-production and Production platform.

![image](https://user-images.githubusercontent.com/32490981/175855299-fa4e5c68-1e71-4190-88f7-d2f3aad0a7d4.png)
