### ISSUE TITLE
[Story] As a user, I want to set the default identity

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#454]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC

* TODO: {link}

## Definition

- Given that I am a Tmail user 
- After log-in successfully to the Tmail web, I can see my avatar icon in top right of screen 
- When I click on this icon, I can see options: Log-out and Settings
- When I select option Settings, the screen Settings will be opened 
- I select Identities tab, the list of my current identities will be displayed .
- There is only one default identity, which I can recognize  with the  text "Default" on the tittle of the identity
- There are 2 ways to set an identity as default: 
1. I click on three-dot button of an identity:
   - If the selected identity is not default identity, I can see options: "Edit","Set as default", "Remove"
   - If the selected identity is default identity, I can only see option "Edit"
- I select option "Set as default", there will be a confirmation popup. I select Yes, then that identity is set as default and  the previous default identity becomes normal identity
2. I click on three-dot button of an identity, then select "Edit"
- On screen "Edit identity":
   - If the identity is already default identity, I will not see checkbox " Default identity"
   - If the identity is not default identity, I will the checkbox 
- I tick the checkbox "Default identity" then click button Save
- If there is no error, the select identity will be set as default identity and the previous default identity becomes normal identity

- When I compose an email, the default identity will be selected automatically in the field "From"

## Secreeshots

![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/fdda171c-860b-4799-99be-fc7a4bcd7970)

## Design ticket

https://ci.linagora.com/linagora/lgs/design/-/issues/184

[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

**Comment by haftus98** [comment]
There is no option for setting as default

![image.png](https://images.zenhubusercontent.com/632aca085051fb7959dab94b/4d712a82-0f4c-44c5-ae19-9e4753b68f83)

![image.png](https://images.zenhubusercontent.com/632aca085051fb7959dab94b/7418cbfb-0e5d-4907-8bb7-260934e3c07f)

![image.png](https://images.zenhubusercontent.com/632aca085051fb7959dab94b/0ba8172c-02da-4eac-8bc0-97aacc34efaf)

**Comment by dab246** [comment]
@chibenwa 
How can `Set as default` identity be implemented in `jmap`. I tried making the request in the `Identity/set` . method
```json
{
    "using": [
        "urn:ietf:params:jmap:core",
        "urn:ietf:params:jmap:submission"
    ],
    "methodCalls": [
        [
            "Identity/set",
            {
                "accountId": "dab123",
                "update": {
                    "128687472": {
                        "bcc": null,
                        "htmlSignature": "",
                        "name": "identity new",
                        "mayDelete": false,
                        "textSignature": "Hello"
                    },
            },
            "c0"
        ]
    ]
}
```
And always get the results returned from the server like this.
```json
{
    "methodResponses": [
        [
            "Identity/set",
            {
                "newState": null,
                "accountId": "dab123",
                "updated": {},
                "created": {},
                "destroyed": [],
                "notUpdated": {
                    "128687472": {
                        "type": "forbidden",
                        "description": "Field 'mayDelete' in 'identity' cannot be updated"
                    }
                },
                "oldState": null
            },
            "c0"
        ]
    ],
    "latestClientVersion": "6d01c790b3-e724b72e07e8c245",
    "sessionState": "cyrus-0;p-2ac989942b"
}
```
If possible please check for me. Thanks

**Comment by dab246** [comment]
1 HD

**Comment by chibenwa** [comment]
I do think there is two issues here...

**Issue 1** is a bug when updating a default identity that has mayDelete. If mayDelete is specified to the same value than the stored value then the JMAP server is supposed to accept it. Today we do not do this check and blindly reject it....

This can be worked around VERY easily by not specifying the `mayDelete` Parameter (that is server-set) in the update -> it will work like a charm

Try:

```
{
    "using": [
        "urn:ietf:params:jmap:core",
        "urn:ietf:params:jmap:submission"
    ],
    "methodCalls": [
        [
            "Identity/set",
            {
                "accountId": "dab123",
                "update": {
                    "128687472": {
                        "bcc": null,
                        "htmlSignature": "",
                        "name": "identity new",
                        "textSignature": "Hello"
                    },
            },
            "c0"
        ]
    ]
}
```

Instead Dat VU

**Comment by chibenwa** [comment]
**Issue 2** is that JMAP MAIL RFC-8621 do not have any logic to order identities.

This is a problem with the spec, so:

 - We need to raise the topic on the IETF mailing list
 - Rene will present 01 slide about it in the next IETF meeting
 - We will write a little JMAP spec to add a **sortOrder** property on the Identity object. This will live first as a James specific extension (so TMail will need to work without it)
 - Longer term we should have an errata, if not a revision of RFC-8621

**Comment by chibenwa** [comment]
Specification proposal https://github.com/apache/james-project/pull/1228

Would this suite your needs?
