### ISSUE TITLE
[Story] As a user, I want to create a new identity

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#455]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC

* TODO: {link}

## Definition

- Given that I am a Tmail user 
- After log-in successfully to the Tmail web, I can see my avatar icon in top right of screen 
- When I click on this icon, I can see options: Log-out and Settings
- When I select option Settings, the screen Settings will be opened 
- I select Identities tab, the list of my current identities will be displayed 
- I click on button :"Create", the popover "Create a new identity" will be displayed.
- In the new view, I can input fields:
   - Default identity: A checkbox
   - Description: A text field, mandatory
   - Name: A text field, mandatory: This field will be used in "From" when I compose email using this identity. 
   - Email: I can select from the drop-down list. This field will be used in "From" when I compose email using this identity 
   - Reply to address: I can select from the drop-down list. Option "None" is default selected. This field will be used as "Reply to" value when I compose email using this identity. When receiver replies to the email with this identity, the field "To" will be filled automatically with this field value.
   - Signature:  I can input the signature with html options. This will be displayed as signature when I compose email using this identity. 
- When I click button Create, system will validate:
   -  If any mandatory field is blank, there will be an error message at that field.
   - If there is no error, the new identity is created successfully and appears in identities list 

## Secreeshots

![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/727bc386-af95-41f5-8c00-df67123c1bac)

## Design ticket

https://ci.linagora.com/linagora/lgs/design/-/issues/182

[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

**Comment by hoangdat** [comment]
<img width="715" alt="image" src="https://user-images.githubusercontent.com/6462404/162117743-ca925f3b-8b5b-49a1-bbbc-3030bc7aa0aa.png">

**Comment by Kevinle2312** [comment]
PAssed on Pre-production and Production platform.
