### ISSUE TITLE
[Story] As a user, I want to select an identity when composing/replying/forwarding an email

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#456]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC

* TODO: {link}

## Definition

- Given that I am a Tmail user 
- After log-in successfully to the Tmail,
- I compose/reply/foward email
- I can choose between my identifies via `From` field as a drop-down list

<img width="635" alt="image" src="https://user-images.githubusercontent.com/6462404/161737133-98154929-dc04-43df-873f-fcd5d575f888.png">

[Back to Summary](#summary)

## Design ticket

https://ci.linagora.com/linagora/lgs/design/-/issues/173

[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

**Comment by Kevinle2312** [comment]
Passed on the Production platform.
