### ISSUE TITLE
[Story] As a user, I want to see my signature in the composer when I composing email

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#457]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC

* TODO: {link}

## Definition

- Given that I am a Tmail user 
- After log-in successfully to the Tmail web, tablet (only see signature on web and tablet, mobile don't display signature, but signature will be appended when sending email)
- I compose/reply/foward email
- I can choose between my identifies via `From` field as a drop-down list
- After I choose an identifier, all the related fields are update base on the identifier
- Signature also be updated
- Bcc also add item `bcc` of selected Identifier

https://user-images.githubusercontent.com/6462404/161738795-8984ee97-d0da-4727-a990-b02f6e11a802.mov

[Back to Summary](#summary)

## Design ticket

https://ci.linagora.com/linagora/lgs/design/-/issues/174

[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

**Comment by Kevinle2312** [comment]
Passed on the Production platform.
