### ISSUE TITLE
[Story] As a user, I want to edit my identities

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#458]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC

* TODO: {link}

## Definition

- Given that I am a Tmail user 
- After log-in successfully to the Tmail web, I can see my avatar icon in top right of screen 
- When I click on this icon, I can see options: Log-out and Settings
- When I select option Settings, the screen Settings will be opened 
- I select Identities tab, the list of my current identities will be displayed 
- I click on three-dot button of an identity:
   - If the identity is default identity, I can only see option "Edit"
   - If the identity is not default identity, I can see options "Edit" and "Remove"
- I select option Edit, the screen "Edit identity" will be opened: 
- I can edit all fields in the screen:
   - Default identity: A checkbox. If the identity is already default identity, I will not see this field
   - Description: A text field, mandatory
   - Name: A text field, mandatory: This field will be used in "From" when I compose email using this identity. 
   - Email: I can select from the drop-down list. This field will be used in "From" when I compose email using this identity 
   - Reply to address: I can select from the drop-down list. Option "None" is default selected. This field will be used as "Reply to" value when I compose email using this identity. When receiver replies to the email with this identity, the field "To" will be filled automatically with this field value.
   - Signature:  I can input the signature with html options. This will be displayed as signature when I compose email using this identity. 
- When I click button Save, system will validate:
   -  If any mandatory field is blank, there will be an error message at that field.
   -  If there is no error, identity is updated successfully.

## Secreeshots

![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/da37c8ae-f93e-48b0-b890-b4e853a37422)

## Design ticket

https://ci.linagora.com/linagora/lgs/design/-/issues/183
[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

**Comment by Kevinle2312** [comment]
PAssed on Production platform.
