### ISSUE TITLE
[Story] As a user, I want to delete my identities

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#459]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC

* TODO: {link}

## Definition

- Given that I am a Tmail user 
- After log-in successfully to the Tmail web, I can see my avatar icon in top right of screen 
- When I click on this icon, I can see options: Log-out and Settings
- When I select option Settings, the screen Settings will be opened 
- I select Identities tab, the list of my current identities will be displayed 
- I click on three-dot button of an identity:
   - If the identity is default identity, I can only see option "Edit"
   - If the identity is not default identity, I can see options "Edit" and "Remove"
- I I select option Delete, there will be a confirmation message
- If I confirm deletion, the identity will be removed out of the identities list 

## Secreeshots

![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/089261f9-2c15-4e77-9e4e-4ea6123520a4)

## Design ticket

https://ci.linagora.com/linagora/lgs/design/-/issues/185

[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

**Comment by Kevinle2312** [comment]
Passed on the Production platform.
