### ISSUE TITLE
[Dev] Composer widget

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#46]
### Story:

#43

### Desc:
Try to generalize composer:
- Input: `Email` or `null`
- Output: A composer with some inserted data (From/To, Thread content) or empty

### DoD:

A Composer widget:
- From: From: Hard code user identifier to the email address specified upon the login
- To: with `expand icon` for Cc and Bcc
- Subject: 
- Body: 
{input area}
{thread content if have} - editable 

Prototype base on `OpenPaas`. Please keep as simple as possible, we will change the UI for the composer after some weeks.
![prototype_composer.png](https://images.zenhubusercontent.com/5f7d8ef759d36aecc684e2a4/db519cb6-9b91-49ee-9681-5dffff8064fa)

**Comment by chibenwa** [comment]
From: Hard code user identifier **to the email address specified upon the login**
