### ISSUE TITLE
[Story] As a user, I want to Go to Settings

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#460]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC

* TODO: {link}

## Definition

- Given that I am a Tmail user 
- After log-in successfully to the Tmail web, I can see my avatar icon in top right of screen 
- When I click on this icon, I can see options: Log-out and Settings
- When I select option Log-out, I am redirected to log-in screen 
- When I select option Settings, the screen Settings will be opened 
- In this screen, I can see the tab or menu with many settings item: but now Language and Identifies

## Design ticket

https://ci.linagora.com/linagora/lgs/design/-/issues/171

[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

**Comment by Kevinle2312** [comment]
PAssed on Production platform.
