### ISSUE TITLE
Not able to login Tmail in mobile web

### ISSUE THREAD

**Issue by hantt12** [linagora/tmail-flutter#468]
### Description
User should be able to login and use Tmail in mobile web

### Current behavior
Unable to  login. There is no error message

#### Reproduction Steps
1. Go to Tmail.lingora.com in mobile web browser
2. Input valid username and password and tap login buton

**Comment by chibenwa** [comment]
Specific app/version of mobile web browser?

**Comment by hantt12** [comment]
Device 1: iphone 7 plus, ios 15.4.1, Google Chrome
Device 2: iphone 11, ios 15.3.1, Safari

**Comment by hoangdat** [comment]
still not connect. Need more debug with chrome mobile

**Comment by dab246** [comment]
2 HD

**Comment by dab246** [comment]
- `Android`: Login successful on Chrome
- `iOS`: Error getting session on Safari
```json
{
     "type": "about:blank",
     "status": 401,
     "detail": "No valid authentication methods provided"
}
```

![Screen Shot 2022-07-07 at 18.28.32.png](https://images.zenhubusercontent.com/605059df174a357c7888640f/78fcc6e5-e992-4352-927a-7dee5673f127)

**Comment by chibenwa** [comment]
My feeling is maybe a missing space after ';' in the accept header?

I am in vacations cc @Arsnael

**Comment by dab246** [comment]
@chibenwa  Oh, sorry to bother you now. I'll check this out more until you come back.

**Comment by Arsnael** [comment]
I just managed to login successfully on my iphone with safari browser on my account in https://tmail.linagora.com so... 

Are you sure you did not put the wrong password or sth? Cause it works without issue for me.

Iphone 11, ios 15.5

**Comment by dab246** [comment]
@Arsnael  
- I make sure I entered it correctly. Because I have successfully logged in on my android device.
- I think maybe it's because I'm testing on an iOS Simulator that it blocks like that.
- If you have successfully signed in on your device then I think this error should be fixed.

**Comment by Arsnael** [comment]
@dab246 Maybe because you are on an emulator... Honestly I know very little regarding ios dev... Can't you see with QA to get your hand on one of the iphone devices at the office to check with a real one and do a comparison?
