### ISSUE TITLE
Data in cache not show correctly after logout and then login with other user

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#474]
### Reproduce:

1. Login with user A
2. open `Sent mailbox`
3. scroll down and check some mails
4. logout 
5. login with user B
6. open `Sent mailbox`
7. all metadata of mails in `Sent mailbox` of user A is showed in Sent of user B

<img width="1058" alt="image" src="https://user-images.githubusercontent.com/6462404/162398066-5e818170-2a43-482d-af32-4ec97a990d53.png">

After delete the cache

<img width="1062" alt="image" src="https://user-images.githubusercontent.com/6462404/162398308-9309cb19-e5cb-4a14-9eb7-0d17ab2c25dc.png">

### DoD: 

- Show correctly emails of each user

**Comment by Kevinle2312** [comment]
Failed on CI platform. @hoangdat

**Comment by Kevinle2312** [comment]
https://user-images.githubusercontent.com/32490981/167061310-287f5afd-e357-4ac9-9627-de74e7f96dab.mp4

**Comment by hoangdat** [comment]
@dab246 this is not resolved. Please re-check it.

**Comment by Kevinle2312** [comment]
Passed on CI platform.
