### ISSUE TITLE
[CI platform] [Draft email] - Unable to save a draft email or modify draft email on CI platform

### ISSUE THREAD

**Issue by Kevinle2312** [linagora/tmail-flutter#475]
### Description
Unable to save a draft email or modify a draft email on CI platform.

### Expected result
I can save and edit a draft email.

### Current behaviour
Unable to save a draft email or modify a draft email on CI platform.

### Context

[tmail CI platform](https://tmail.upn.integration-open-paas.org/#/mailboxDashBoard)

### Additional information

1. Unable to save draft

https://user-images.githubusercontent.com/32490981/162406610-df18023d-9fe9-469f-ab4f-3cdda99deadd.mp4

2. Unable to modify draft

https://user-images.githubusercontent.com/32490981/162406690-149a3042-55b3-4814-bf86-963ad4c6e1ad.mp4

**Comment by dab246** [comment]
- I have retested this feature on `jmap.linagora.com` and `dev.open-paas.org` but do not see this error occur.
- Result 

https://images.zenhubusercontent.com/378835363/67b485e2-3d34-4a55-a8fa-bdcabf090d44/screen_recording_2022_05_16_at_15_26_08.mov

https://images.zenhubusercontent.com/378835363/b91eee65-24ef-4f75-a866-9bc34c908faa/screen_recording_2022_05_16_at_15_28_28__online_video_cutter_com_.mp4

**Comment by chibenwa** [comment]
For me this still occurs on tmail.linagora.com

https://images.zenhubusercontent.com/378835363/35f36d14-e1ef-43bb-87d7-4a19bd4932bb/draft2_2022_05_16_15_50_42.mp4

**Comment by chibenwa** [comment]
For me this still occurs on tmail.linagora.com

https://images.zenhubusercontent.com/378835363/35f36d14-e1ef-43bb-87d7-4a19bd4932bb/draft2_2022_05_16_15_50_42.mp4

**Comment by hoangdat** [comment]
it still works at the moment: 10.45AM - 24 May 22
Env:

- version 0.3.4
- tmail.linagora.com
- dev.open-paas.com

**Comment by hoangdat** [comment]
it maybe still happen, so magically

**Comment by Kevinle2312** [comment]
> it maybe still happen only in tmail.linagora.com, so magically

It happens on both Pre-production and production platform.

**Comment by Kevinle2312** [comment]
PAssed on pre-production and production platform
