### ISSUE TITLE
[Dev mode turn off] - The tmail page is either blank or deformed after dev mode turns off

### ISSUE THREAD

**Issue by Kevinle2312** [linagora/tmail-flutter#477]
### Description
The tmail page is either blank or deformed after dev mode turns off.

### Expected result
Tmail page should be the same.

### Current behaviour
The tmail page is either blank or deformed after dev mode turns off.

### Context

[Tmail CI platfrom](https://tmail.upn.integration-open-paas.org/#/mailboxDashBoard)

### Additional information

https://user-images.githubusercontent.com/32490981/162408580-84e27ed9-2900-48b0-a845-4c0b2b3e1aa3.mp4

**Comment by Kevinle2312** [comment]
Failed on pre-production platform @hoangdat

https://user-images.githubusercontent.com/32490981/172760032-e876b10c-3a7a-4de0-b1bd-72a9ede8bb7a.mp4

**Comment by dab246** [comment]
I checked again in Dev-mode and it's still working fine. Please test again.

https://user-images.githubusercontent.com/80730648/174752558-b639e19f-b6da-4553-b071-4d70697c4671.mov

**Comment by hoangdat** [comment]
1HD
