### ISSUE TITLE
[Story] As a user, I want to search emails with Advanced options

### ISSUE THREAD

**Issue by dieptran88** [linagora/tmail-flutter#478]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Definition

- Given that I am a Tmail user 
- I logged-in successfully to Tmail app/browser 
- I can see a Search bar at top of thread-view screen 
- I click on the chevron icon of Search bar, the Advanced Search options screen will be displayed.
- I can see the advanced options:
   - From: 
      - I can input multiple email addresses or texts to this field. It will search for emails which have sender's email address/name matching with one of inputted email/text in this field. 
      - When I input text, the system will search and display any email that contains inputted text in name/email in a suggestion list and I can select one email from the list.
      - If there is no matching email, I can still input any email/text to this field. 
      - I can remove/edit any email/text in this field before clicking button Search 
   - To:
      - I can input multiple email addresses or texts to this field. It will search for emails which have "To"' email address/name matching with one of inputted email/text in this field. 
      - When I input some text, the system will search and display any email that contains inputted text in name/email in a suggestion list and I can select one email from the list.
      - If there is no matching email,  I can still input any email/text to this field. 
      - I can remove/edit any email/text in this field before clicking button Search 
   - Subject: 
      - I can input text to this field. It will search emails with subject field matching with inputted text.
   - Contains:
      - I can input text to this field. It will search emails with any part matching with inputted text.
   - Does not have:
      - I can input text to this field. It will exclude emails with any part matching with inputted text.
   - Mailbox: 
      - Default value is "All mail"
      - When I click on this field, I can see a Pick mailbox screen listing all the current mailboxes 
      - I select a mailbox then the screen will be closed and system will search in selected mailbox 
   - Has attachment:
      - A checkbox: Default value is uncheck
      - If the checkbox is ticked, the system will search emails which contain attachments
   - Period:
      - Default value s "All time"
      - When  I click on this field, I can see a new view that contains options list: All times/Past 7 days/Past 30 days/Past 6 months/Custom range
      - If I select any option except "Custom range", the option list will be closed and the selected option is displayed in the field 
      - If I select option "Custom range", another view will be displayed that allow me to select time frame "From", "To".
- I can click button "Clear" to remove all current inputted search options. 
- After filling advanced search fields, I click button Search, then the system will execute searching emails and displayed result. 
- In Search bar, I can see some search criteria. If there are multiple search criteria, I need to click on chevron icon to open full Advanced Search screen.

[Back to Summary](#summary)

## Screenshots

![Group 86.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/91471f40-fed1-4a44-bfe1-cff0fe1aad7c) ![Group 87.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/92a0040a-652b-4237-8964-d3c5c48ae5b2)

![Group 88 (1).png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/8b342eaf-5c49-41f7-ab32-0807c2648b17) ![Group 89.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/9d5d4be0-18f2-407e-ae70-e9e882f4df09)

[Back to Summary](#summary)

## Design ticket

https://ci.linagora.com/linagora/lgs/design/-/issues/176

## Misc

None

[Back to Summary](#summary)

**Comment by ManhNTX** [comment]
@dieptran88 when I check Figma design, I see `Doesn’t have` field has not been described in the story. Can you add it to the story? Thank

**Comment by dieptran88** [comment]
> @dieptran88 when I check Figma design, I see `Doesn’t have` field has not been described in the story. Can you add it to the story? Thank

Ok, I will update story
