### ISSUE TITLE
Hover in email, checkbox is available to select email in ThreadView

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#483]
### Desc: 

As the user's feedback: Long press is not a friendly UX in browser, we also have design for the hover

<img width="597" alt="image" src="https://user-images.githubusercontent.com/6462404/163098784-bc41949f-84b4-4255-96bc-2ec7b126e3fb.png">

https://www.figma.com/file/rRVxJpCu1G22D0jqyvK7I9/TeamMail?node-id=1115%3A112296

**Comment by Kevinle2312** [comment]
PAssed on Pre-production and Production platform.
