### ISSUE TITLE
Email have link show multi-line for the link

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#486]
### Tmail: 

<img width="879" alt="image" src="https://user-images.githubusercontent.com/6462404/163289926-61d943af-7d96-411f-9755-06d062e11116.png">

### other mail client:

<img width="928" alt="image" src="https://user-images.githubusercontent.com/6462404/163290167-a3c148da-a333-48b6-a4c7-b1f70ec9ff2d.png">

**Comment by Kevinle2312** [comment]
PAssed on CI platform.
