### ISSUE TITLE
TeamMail not in the list of selectable Mail app to be Default mail app in iOS 

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#501]

**Comment by hoangdat** [comment]
I tested but it is not success, app still not in list

**Comment by hoangdat** [comment]
Test with #768

**Comment by hoangdat** [comment]
still not show Tmail in Default Mail app

![image](https://user-images.githubusercontent.com/6462404/185113935-d9b35352-331a-4e1f-a487-9e730cd1faea.png)

**Comment by ManhNTX** [comment]
PR : https://github.com/linagora/tmail-flutter/pull/893

**Comment by ManhNTX** [comment]
@hoangdat https://developer.apple.com/forums/thread/650300
send an email to default-app-requests@apple.com to have them review your app and grant you the entitlement
https://developer.apple.com/documentation/xcode/preparing-your-app-to-be-the-default-browser-or-email-client
