### ISSUE TITLE
 [Story] As a user, I want to log-in Tmail using SSO (OIDC)

### ISSUE THREAD

**Issue by dieptran88** [linagora/tmail-flutter#506]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC

* TODO: {link}

## Definition

- Given that I am a Tmail user 
- When I open Tmail app on mobile/tablet or access Tmail through web browser, I can see a Log-in screen 
- I can see an option: Sign-in with my SSO account and select this option
- For Mobile/Tablet, I need to input the URL then click button to continue. 
- The system will validate URL link:
   - If the URL is valid, the browser will be opened with OIDC log-in screen
   - If the URL is invalid, system will display error message and the field URL is highlighted in red border. I cannot go to next step until I input the correct URL.
- On OIDC provider screen, I input my SSO account credentials, then the OIDC provider will validate.
- If the information is valid, I will log-in successfully to the Tmail app.Web browser 
- Note: For web browser, User does not need step input URL.

[Back to Summary](#summary)

## Screenshots

None

[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

**Comment by dieptran88** [comment]
@hoangdat   Do we keep both ways to log-in: User name pw authentication and OIDC ?

**Comment by hoangdat** [comment]
hi @chibenwa , we should support OIDC and basic auth or only OIDC (after implement OIDC)?
