### ISSUE TITLE
Can not log-in to TeamMail in Incognito browser

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#508]
![image](https://user-images.githubusercontent.com/6462404/164485475-938ae6d0-e655-4425-8988-3dd7a3bbc4a6.png)

![image](https://user-images.githubusercontent.com/6462404/164485533-ca251597-ae54-4eec-b23a-c379ffe21106.png)

**Comment by dab246** [comment]
I still successfully login in debug mode. IMO we should consider when deploying to web server

**Comment by hoangdat** [comment]
Hi @chibenwa, can you take a look for this, from your site.

**Comment by hoangdat** [comment]
@tnstung can you help me to detect why the env is not loaded to the application. we checked in the code, but not see the problem, maybe it related to the step in deployment.

**Comment by chibenwa** [comment]
No idea to be honnest....

**Comment by hoangdat** [comment]
@Arsnael please help me check the content of `env.file` in `tmail.linagora.com`.

And, can you guide me how you config that in production.

Thanks and BRs

**Comment by hoangdat** [comment]
in firefox: 

<img width="959" alt="image" src="https://user-images.githubusercontent.com/6462404/171167071-65459b7e-021f-422d-95cd-28fbe0613e96.png">

**Comment by hoangdat** [comment]
in igconito Chrome:

<img width="669" alt="image" src="https://user-images.githubusercontent.com/6462404/171167888-4ee4c8c9-3d3e-4955-8883-01eec781c89e.png">

**Comment by haftus98** [comment]
![image.png](https://images.zenhubusercontent.com/632aca085051fb7959dab94b/f603771d-7c40-4187-90ed-40ff7dd77d35)

I can't load the web Firefox in cognito

**Comment by dab246** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1320796

**Comment by hoangdat** [comment]
By default, the `index.html` file generated by the `flutter create` command contains a script tag

https://github.com/linagora/tmail-flutter/blob/1fcac735b4aadba83519680d594b4fc077114146/web/index.html#L39-L102

**Comment by hoangdat** [comment]
And base on: https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API

<img width="775" alt="image" src="https://user-images.githubusercontent.com/6462404/199619853-4d8bb7be-9d8a-4d1c-8ccf-2f6d242c302f.png">

**Comment by dab246** [comment]
1 HD
