### ISSUE TITLE
[Story] As a user, I can to see Tmail as an option when I want to share a file from my device (mobile/tablet) 

### ISSUE THREAD

**Issue by dieptran88** [linagora/tmail-flutter#523]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC

* TODO: {link}

## Definition

- Given that I am a TMail user 
- Given that I have installed Tmail app in my device (mobile/tablet)
- I am browsing file on the device then click button "Share with" 
- The system will display a list of apps that can be used to share the selected files and I can see Tmail icon as one of options
- When  I select Tmail icon: 
   - If I have logged in to Tmail app, the app will be opened and the composer is opened automatically, and the selected files are uploaded as attachments in this new email.
   - If I have not logged in to Tmail app, the log-in screen will be displayed. After input log-in credentials correctly, I can see a the composer is opened with selected files as attachment of this new email.
- If the selected file is an image, after the image is uploaded to the composer, I can see the image's thumbnail and name, size of the image
- If the selected file is a video, after the file is uploaded to the composer, I can see video player icon and name, size of the video 
- If the selected file is a document, after the file is uploaded to the composer, I can see the document's format icon with its name and size 
- When there are many selected files, I can expand or collapse the list of files 
- In each file, I can see a Delete button that when I click on, the file will be removed.

[Back to Summary](#summary)

## Screenshots

None

[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

**Comment by haftus98** [comment]
https://user-images.githubusercontent.com/97084773/192258427-7a8ba1b0-06b2-40e8-843e-f897f2a19764.mp4
=> Cant upload video

https://user-images.githubusercontent.com/97084773/192258484-0d392202-c2db-4a0f-91ae-fd10008e6780.mp4

=> cant upload file

**Comment by hoangdat** [comment]
How about other kind of files? pdf, word, .... @haftus98

**Comment by haftus98** [comment]
pdf and word couldn't be uploaded too @hoangdat

**Comment by hoangdat** [comment]
yes, I know, because image a special case (inline), so we support these kinds of type first, other file will be support then :)

**Comment by hoangdat** [comment]
@haftus98 please update the status when you test with image for this case. Thanks

**Comment by dab246** [comment]
### DoD
-  Support share files 
- Check condition file `size`

**Comment by dab246** [comment]
2 HD
