### ISSUE TITLE
Apply Quick Search as New Design

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#524]
### Desc:

All the screen related to Normal search in Design: 
https://www.figma.com/file/rRVxJpCu1G22D0jqyvK7I9/TeamMail?node-id=1881%3A132217

### DoD: 
- Store recent search in hive database.
- Drop down list recent search.
- Limit the recent search to 10.
- Filter search result by selected mailbox.
- Debounce on search 500 milliseconds

**Comment by Kevinle2312** [comment]
PAssed on Production platform.
