### ISSUE TITLE
Delete button is overlapped by compose floating button

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#531]
![image](https://user-images.githubusercontent.com/6462404/166083012-486342c0-3c87-4994-be73-06d15a75fa1e.png)

**Comment by johnnguyenit39** [comment]
Reproduce: Long press into the email item.

**Comment by hoangdat** [comment]
resolved in v0.3.4

**Comment by Kevinle2312** [comment]
Passed on Pre-production and Production platform.
