### ISSUE TITLE
[Story] As a user, I want to restore emails from folder Trash

### ISSUE THREAD

**Issue by dieptran88** [linagora/tmail-flutter#533]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC

* TODO: {link}

## Definition

- Given that I am a Tmail user
- After logged in successfully, I go to Trash folder
- The Restore action is only available in Trash folder
- I can restore an email from Trash folder in 2 ways:
**UC1.** 
- I open an email, then I click on icon Restore on the top right, then the email is moved back to the original mailbox. 
- I am navigated back to thread-view and see a toast message: "Restored successfully" with button Undo
- I click button Undo, the email is reverted to Trash folder again
**UC 2.** 
- On the thread-view, i can long-press on the avatar to select one or multiple emails, then there will be an action bar displayed on the top.
- I can touch the icon "Restore " then selected email will be moved back to the original folder, or i can click on three-dots button then there will be a context menu that contain actions. I select option "Restore",  then selected emails will be moved back to the original folders
-  I can see a toast message: "Restored successfully" with button Undo
- I click button Undo, the email is reverted to Trash folder again

[Back to Summary](#summary)

## Screenshots

None

[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

**Comment by hoangdat** [comment]
only support `Move`. Not support `Restore`
