### ISSUE TITLE
[Signature] - The Signature added on openpass does not appear on tmail

### ISSUE THREAD

**Issue by Kevinle2312** [linagora/tmail-flutter#540]
### Description
The Signature added on openpass does not appear on tmail.

### Expected result
The Signature added on openpass should appear on tmail.

### Current behavior
The Signature added on openpass does not appear on tmail.

#### Reproduction Steps
1.On openpaas side, add a signature by Clicking to the Your account -> Profile -> Identities
2. On tmail side verify it

### Context

Production site: tmail.linagora.com

### Additional information
On openpaas site:
![image](https://user-images.githubusercontent.com/32490981/167090826-a9abf968-09b0-47ab-871d-f6b0d2091f4b.png)

On tmail site:
![image](https://user-images.githubusercontent.com/32490981/167090979-a140e3d6-8d86-4724-9d7c-0a01fbcffc30.png)

**Comment by chibenwa** [comment]
Invalid.

Those uses different mechanisms, it is expected and normal that TMail do not show the OpenPaaS signatures.
