### ISSUE TITLE
Mailbox scrollbar jumps, resizes

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#551]
### Description

When I gentally scroll down the mailbox list, the scroll bar resizes and jumps.

### Expected result

I would expect it to also move gently, constant size.

### Current behavior

https://user-images.githubusercontent.com/6928740/167391126-2f6ea01b-a7bb-43dd-953b-371774c7f025.mp4

### Acceptance criteria

The list of acceptance criteria (defined in the corresponding User Story or coming from your functional knowledge of the product)
These acceptance criteria must be met by the corrective implementation done by the developers.

### Context

openpaas.linagora.com 

$ chromium -version
Chromium 101.0.4951.54 snap

**Comment by hoangdat** [comment]
1HD

**Comment by haftus98** [comment]
verified on V0.3.17
