### ISSUE TITLE
[Story] As a user, I want to enable biometric authentication in Tmail app 

### ISSUE THREAD

**Issue by dieptran88** [linagora/tmail-flutter#552]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC

* TODO: {link}

## Definition

- Given that i am a Tmail app user
- I logged-in successfully to Tmail app
-  I open Account Detail screen and see a new section: Biomeric authentication 
- If the device supports biometric authentication, section "Biometric authentication" will be shown. If not, this section will be hidden.
- I click the option Biometric authentication, the app will check:
-  If I click toggle button and device fingerprint/Face ID is enabled, there will be popup asking me to input finger touch/Face ID to enable biometric authentication:
   -  If the fingerprint/Face ID is correct, Biometric authentication will be enabled 
   - If the fingerprint/Face ID is incorrect, I can try finger touch again or cancel
- If the device's fingerprint/Face ID is disabled, system will display an error message: "Touch ID or Face ID must be enabled to turn on biometric authentication" 
- The time-out will be set to 5 seconds automatically. If I click on this field, I can see a drop-down list with options: 5 seconds, 10 seconds, 30 seconds, 1 minute, 2 minutes, 3 minutes. I can select one option in this list
- When the biometric authentication is disabled, the field "Time out" will be disabled. 
- After the biometric is enabled, when I close then open app >   the "time out" period, I need to use Face ID/ Finger touch to  authenticate. 
- When I open an email from notification or sharing file from outside app, or click on mailto link outside app, the biometric authentication rule is also applied. 

[Back to Summary](#summary)

## Screenshots

![Group 94 (3).png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/c17ee973-0846-420a-b43e-6698ce6ac053)  ![Group 95 (3).png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/ee46d135-f24b-4d59-bc4b-6b4d27aaea96)

![Bio (5).png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/71ee9d04-38d5-41ac-bf3a-63b0a48ca47c)  ![Bio (6).png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/0f7837d9-5d51-4662-9402-d23fd567354b)

![Group 96 (3).png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/d4eb97b5-5eda-4905-b66b-4fcfe354d640)  ![Group 102 (4).png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/d6827012-038f-4966-b6e8-2c1d8238e879)

![Bio (7).png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/61dcdb41-ffdc-4472-bdc5-2262a5af64b6)

[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

**Comment by chibenwa** [comment]
Isit something done in Twake? LinShare?
