### ISSUE TITLE
[Story] As a user, I want to disable biometric authentication in Tmail app 

### ISSUE THREAD

**Issue by dieptran88** [linagora/tmail-flutter#553]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC

* TODO: {link}

## Definition
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC

* TODO: {link}

## Definition

- Given that I am a Tmail app user and I enabled Biometric authentication before.
- I logged-in successfully to Tmail app
- There are 2 ways to disable biometric authentication: 

1. - From menu, I go to Account Detail screen
- I click the option Biometric authentication and see the toggle button  is enabled
- I click toggle button, there will be popup asking me to authenticate by finger tough/Face ID 
- If biometric is valid, the toggle button will be disabled.
- If the biometric is invalid, i can retry or cancel 

2. I go to Account detail screen and click button to log-out the app 
- When I logged-out, the biometric authentication is also disabled.

[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

[Back to Summary](#summary)

## Screenshots

None

[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

**Comment by chibenwa** [comment]
Isit something done in Twake? LinShare?
