### ISSUE TITLE
[Story] As a user, I want to authenticate Tmail app with biometric authentication

### ISSUE THREAD

**Issue by dieptran88** [linagora/tmail-flutter#554]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC

* TODO: {link}

- Given that I am a Tmail app user
- Given that I enabled biometric authentication for my Tmail account.
-  I logged-in succcessfully to Tmail  app then I close app
-  Now when I open app again, system will check:
   - If Device Fingerprint or Face ID is enabled, a popup will be displayed asking me user Fingerprint /Face ID to log-in:
      - If Biometric is valid, I authenticate successfully and continue using app.
      -  If Biometric is invalid, an error message will be displayed. I can try again or click button Sign-in
         - When i click button Sign-in, the Log-in Screen will be opened. After log-in as normal with user name and password, I can see the Biometric authentication is disabled.
    - If device's biometric is disabled, system will display message to inform me or I can click button Sign-in.

TODO

[Back to Summary](#summary)

## Screenshots

None

[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

**Comment by chibenwa** [comment]
Isit something done in Twake? LinShare?

**Comment by hoangdat** [comment]
> Isit something done in Twake? LinShare?

Yes, for LinShare. But is it impact to this product?

**Comment by chibenwa** [comment]
I have no idea what biometric authentication mean.

**Comment by dieptran88** [comment]
> I have no idea what biometric authentication mean.

It allow user to authenticate app using fingerprint or face id

**Comment by chibenwa** [comment]
Is this a feature from the OIDC provider?

**Comment by dieptran88** [comment]
I don' think so, it is using biometric authentication from the device
