### ISSUE TITLE
[Story] As a user I want to attach files to emails

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#57]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC
https://app.zenhub.com/workspaces/tmail-flutter-60d039db6ef62a0013432c14/issues/linagora/tmail-flutter/27

## Definition

- Given that i am in one of the mail list
- I click on Create button, a new composer is opened.
- On this composer, i can see an icon attach file
- when I touch this icon, the file browser will be opened
- I can choose one or multiple files then click button to confirm uploading these files
   - If there is any file with the size larger than limitation provided by server (20MB), there will be an error message, i can not upload this file as attachments
   - Other files will be uploaded successfullty
- On the email composer, i can see the list of attached files above the input area.
- Each attachment contains file type icon, file name, file size and a close icon
- I can click on close icon to remove the file 
 - If the list of file is too long, I can scroll up and down to see other part or write the content 
- I input other information of message then touch Send button, the system will check :
   - If the maxsize of the email is larger than limitation, there will be an error message and i cannot send this mail
   - If my Tmail account is out of quota, there will be an error message and i cannot send this mail
- If there is no error, the email will be sent  and it is moved to mailbox Sent 

[Back to Summary](#summary)
### Mobile
![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/63affb32-b7ce-4171-87f0-c3aafcc8d6c6)
![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/6cc16d8b-3196-4e8e-861f-40d87d873656)

### Tab
![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/4b7e6417-6607-4fb6-9fb5-f832a5c2d426)
![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/b4872461-a12e-4153-bc8e-4912bb154bcc)
![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/7424feed-5034-47fa-a092-f1a6944e6339)

[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

**Comment by dieptran88** [comment]
@hoangdat Is there a limit for total files size of an message ?

**Comment by hoangdat** [comment]
> @hoangdat Is there a limit for total files size of an message ?

yes, it is depend on the server, we will have the constraint for each session, please address the constraint to this ticket and compose, reply, ... ticket also

**Comment by chibenwa** [comment]
Yes James have configurable limits. The session object should be used to expose those.

**Comment by hoangdat** [comment]
limitation for attachment in #130

**Comment by Kevinle2312** [comment]
Passed on the Production platform.
