### ISSUE TITLE
[Story] As a user, I want to be able to forward my emails to others

### ISSUE THREAD

**Issue by Arsnael** [linagora/tmail-flutter#574]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC

* TODO: {link}

## Definition

* Given that I am a Tmail app user
* Given that I need for some reason (like going on vacation) to forward my emails to an other mail address
* I go on `Forwardings` in configuration menu
* Where I can 
  * set up one or many mail addresses to forward my mails to
  * decide to keep a local copy of each forwarded mail or not

[Back to Summary](#summary)

## Screenshots

Screenshot from existing feature in OpenPaas:

![forwardings_esn](https://user-images.githubusercontent.com/9005025/168986228-3a21c0f6-af22-428c-869e-7d827497aac6.png)

[Back to Summary](#summary)

## Misc

- JMAP forwards for TMail backend documentation (not merged yet): https://github.com/linagora/tmail-backend/pull/429

[Back to Summary](#summary)

**Comment by dab246** [comment]
Test with related topic forwarding
