### ISSUE TITLE
[Bug] When pull-to-refresh mailbox, selected mailbox jump to Inbox

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#58]
### Description
When pull-to-refresh mailbox, selected mailbox jump to Inbox

### Expected result
When pull-to-refresh mailbox, 
- mailbox list is updated
- selected mailbox is not changed

### Current behavior
When pull-to-refresh mailbox, selected mailbox jump to Inbox

### Acceptance criteria

The list of acceptance criteria (defined in the corresponding User Story or coming from your functional knowledge of the product)
These acceptance criteria must be met by the corrective implementation done by the developers.

### Context

iPad

### Additional information

frequency, log files,...

**Comment by chibenwa** [comment]
This bug no longer happens.

Do you confirm?

Can we close?

**Comment by dab246** [comment]
No more errors.

**Comment by hoangdat** [comment]
> No more errors.

please check in tablet

**Comment by dab246** [comment]
Not found error all device

**Comment by hoangdat** [comment]
https://user-images.githubusercontent.com/6462404/135220713-5c1072fe-6a67-4369-9249-faf5b73d1dbe.mp4

**Comment by hoangdat** [comment]
confirmed
