### ISSUE TITLE
Weird scroll bar in identity input text

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#582]
https://user-images.githubusercontent.com/6928740/169949350-0c36dd2a-6d64-462a-be40-9419c11d82e8.mp4

Android version 0.3.3

**Comment by hoangdat** [comment]
@dab246 do it with #584

**Comment by Kevinle2312** [comment]
Failed on PRe-production platform (both Android and iOS)
https://user-images.githubusercontent.com/32490981/172766748-0e0254fe-7ab9-4de2-bb89-1484c9bf1bcb.mp4
