### ISSUE TITLE
Weird scroll bar in email view

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#583]
https://user-images.githubusercontent.com/6928740/169949610-1f729788-986e-4a9a-9159-d3a52c2c4a09.mp4

Samsung TMail v 0.3.3

**Comment by Kevinle2312** [comment]
I check on the mobile app, that scroll still pop-up when opening an email:

https://user-images.githubusercontent.com/32490981/172795043-5e90da6a-7124-4211-a16d-e6862c150daf.mp4
