### ISSUE TITLE
Identity: text input is hidden by the text composer

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#584]
https://user-images.githubusercontent.com/6928740/169949835-47f8d2b5-99d7-4e33-9124-f705d257c962.mp4

Samsung, tmail v 0.3.3

**Comment by Kevinle2312** [comment]
Passed on Pre-production platform and PRoduction platform.

**Comment by Kevinle2312** [comment]
On the mobile version, the edit identity feature does not work, so I can not verify this bug.

**Comment by hoangdat** [comment]
please wait to v0.3.6
