### ISSUE TITLE
Identity: no reason to restrict BCC field

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#585]
### Description

BCC field is intended to target other people example your boss.

### Expected result

I expect a free text email input field/

### Current behavior

I can only choose my aliases.

https://user-images.githubusercontent.com/6928740/169950067-eca05900-2665-424b-9359-74c595febabf.mp4

**Comment by Kevinle2312** [comment]
Failed on Pre-production and Produciton platform. I can not type in an email address on the BCC field.

**Comment by hoangdat** [comment]
please wait to verify in v0.3.6. we are under reviewing in Play store. iOS is ready to test now
