### ISSUE TITLE
Identity: only show identities created by the user?

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#586]
### Description

Our boss complains to have 1000+ identities.

That's because he have many aliases exposed as identities.

### Expected result

Have an option to only show identities written by the user. `Do not show default identities`.

This would apply both in the composer and the identity page.

We could use the `mayDelete` parameter to only keep identities created by the user.

**Comment by hoangdat** [comment]
you mean we only filter identities with `mayDelete = true`? Am I right?
