### ISSUE TITLE
Settings: search email bar does nothing

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#587]
### Description

![Screenshot from 2022-05-24 11-42-31](https://user-images.githubusercontent.com/6928740/169950747-2db520cc-4412-4729-9642-0fa2b6f2c21b.png)

Clicking this does nothing, that's frustrating...

### Expected result

I expect this search bar to be removed: it makes no sens here!

### Current behavior

Nothing.

### Context

Android, tmail v 0.3.3

**Comment by Kevinle2312** [comment]
On the mobile version and the web version, no search bar is founded.
