### ISSUE TITLE
[Dev] Compose email with suggestion user for To/Cc/Bcc

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#59]
### Story:
#44

### DoD:
- Get users from back-end
- Suggestion when user typing more than 2 character
- When user select an email, should add a `chip` widget to the list

**Comment by hoangdat** [comment]
@chibenwa please help us the API for get `/autocomplete`. Thanks

**Comment by chibenwa** [comment]
There is no backend API for this.

I think a first version could rely on local device storage.
