### ISSUE TITLE
[BUG] Template html signature is lost in Identity creator view

### ISSUE THREAD

**Issue by dab246** [linagora/tmail-flutter#597]
### Description
-  Template html signature is lost in Identity creator view
-  Cannot update `null` value for identity `bcc` and `replyTo` address

### Expected result
- Identity creation and editing works fine

![Screen Shot 2022-05-27 at 18.39.42.png](https://images.zenhubusercontent.com/605059df174a357c7888640f/99ad15d4-392d-4588-a2ab-65e9dbf9b5d7)

**Comment by Kevinle2312** [comment]
PAssed on the Production platform. I can edit an identity.
