### ISSUE TITLE
[Story] As an user, i want to choose a mailbox and see mail list inside

### ISSUE THREAD

**Issue by dieptran88** [linagora/tmail-flutter#6]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Technical issues](#technical-issues)
* [Misc](#misc)

## Definition

- Given that i am a Tmail user and i already had an account (John Doe).
- Given that i log-in successfully to the Tmail app.
- I can see the default view  is Inbox mail list.
- I click on Inbox title, the list of mailboxes screen will be opened. 
- I can select another mailbox and the list of mail inside that mailbox will be opened.

   - For "Draft" mailbox: The mail listing rule is as same as Inbox #9 except that on each email i can see a label "Draft" 
   - For "Sent:The mail listing rule is as same as Inbox #9   
   - For "Trash": The mail listing rule is as same as Inbox #9   
   - For "Spam": The mail listing rule is as same as Inbox #9   
   - For Created mailboxes : The mail listing rule is as same as Inbox #9   

- When an mailbox is opened, the folder's name will be displayed on top of screen. If that mailbox has a counter for unseen message, the number will be displayed next to Folder's name.
- The email list should be refreshed real time: When an email is deleted or added, it will be reflected instantly on listing mail screen. 

[Back to Summary](#summary)

#### Final design
![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/3b6baff8-62be-43c1-9046-9a805b025f04)

[Back to Summary](#summary)

## Technical issues

[Back to Summary](#summary)

## Misc

[Back to Summary](#summary)

**Comment by hoangdat** [comment]
@chibenwa Can you help us to write the Jmap call for this story?

**Comment by chibenwa** [comment]
Sure. Let me 5 minutes ;-)

**Comment by chibenwa** [comment]
In short, chain:

 - `Mailbox/query` to get the mailbox id - not needed when browising the mailbox list but useful to do single request page load <3
 - `Email/query` to the the email list - `inMailbox` filter supports backreference
 - `Email/get` to retrieve display information - be carefull not to specify something expensive in the properties!

**Comment by chibenwa** [comment]
## When the user clicks on a mailbox of the mailbox view

You already have the mailbox id so we just do `Email/query` and `Email/get`.

Example:

```
{
  "using": ["urn:ietf:params:jmap:core", "urn:ietf:params:jmap:mail"],
  "methodCalls": [[
    "Email/query",
    {
      "accountId": "29883977c13473ae7cb7678ef767cbfbaffc8a44a6e463d971d23a65c1dc4af6",
      "limit": 20,
      "filter": {
        "inMailbox": "36"
      },
      "sort": [{
        "property":"sentAt",
        "isAscending": false
      }]
    },
    "c2"], [
     "Email/get",
     {
       "accountId": "29883977c13473ae7cb7678ef767cbfbaffc8a44a6e463d971d23a65c1dc4af6",
       "properties": ["id", "subject", "from", "to", "cc", "bcc", "keywords", "size", "receivedAt", "sentAt", "replyTo", "preview", "hasAttachment"],
       "#ids": {
         "resultOf":"c2",
         "name":"Email/query",
         "path":"ids/*"
       }
     },
     "c3"]]
}
```

Will return:

```
TODO
```

## You want to load the content of INBOX upon app opening in a single request!

Here we need to add `Mailbox/query` to the mix:

```
{
  "using": ["urn:ietf:params:jmap:core", "urn:ietf:params:jmap:mail"],
  "methodCalls": [[
    "Mailbox/query",
    {
      "accountId": "29883977c13473ae7cb7678ef767cbfbaffc8a44a6e463d971d23a65c1dc4af6",
      "filter": {"role":"Inbox"}
    },
    "c1"],[
    "Email/query",
    {
      "accountId": "29883977c13473ae7cb7678ef767cbfbaffc8a44a6e463d971d23a65c1dc4af6",
      "limit": 20,
      "filter": {
        "#inMailbox": {
         "resultOf":"c1",
         "name":"Mailbox/query",
         "path":"ids[0]"
       }
      },
      "sort": [{
        "property":"sentAt",
        "isAscending": false
      }]
    },
    "c2"], [
     "Email/get",
     {
       "accountId": "29883977c13473ae7cb7678ef767cbfbaffc8a44a6e463d971d23a65c1dc4af6",
       "properties": ["id", "subject", "from", "to", "cc", "bcc", "keywords", "size", "receivedAt", "sentAt", "replyTo", "preview", "hasAttachment"],
       "#ids": {
         "resultOf":"c2",
         "name":"Email/query",
         "path":"ids/*"
       }
     },
     "c3"]]
}
```

Will return:

```
TODO
```

**Comment by hoangdat** [comment]
@chibenwa why we not set the arguments `collapseThreads = true` in the query method?

**Comment by chibenwa** [comment]
collapseThreads is not supported by James

**Comment by hoangdat** [comment]
After user scroll all the `limit` how to get more?

**Comment by chibenwa** [comment]
Use position + limi

Request one:
 - position 0 limit 20
 Request 2:
 - position 20 limit 20
 Etc...

**Comment by hoangdat** [comment]
Perfect. Srr, I only glance read the specs 🙏

**Comment by chibenwa** [comment]
No problem, I'm here or that!

**Comment by hoangdat** [comment]
@chibenwa 
I requested
```json
{
    "using": [
        "urn:ietf:params:jmap:core",
        "urn:ietf:params:jmap:mail"
    ],
    "methodCalls": [
        [
            "Email/query",
            {
                "accountId": "{{accountId}}",
                "limit": 20,
                "filter": {
                    "inMailbox": "aba7e8d0-18d9-11eb-a677-2990b970028d"
                },
                "sort": [{
                  "property":"sentAt",
                  "isAscending": false
                }],
                "position": 0
            },
            "c2"
        ],
        [
            "Email/get",
            {
                "accountId": "{{accountId}}",
                "properties": [
                    "subject",
                    "from",
                    "receivedAt",
                    "sentAt",
                    "preview",
                    "hasAttachment"
                ],
                "#ids": {
                    "resultOf": "c2",
                    "name": "Email/query",
                    "path": "ids/*"
                }
            },
            "c3"
        ]
    ]
}
```
But the list in `c3` is not follow the order of `ids` from `c2` response.

**Comment by hoangdat** [comment]
> Use position + limit
> 
> Request one:
> 
> * position 0 limit 20
>   Request 2:
> * position 20 limit 20
>   Etc...

It quite not success:
```
{
    "using": [
        "urn:ietf:params:jmap:core",
        "urn:ietf:params:jmap:mail"
    ],
    "methodCalls": [
        [
            "Email/query",
            {
                "accountId": "{{accountId}}",
                "limit": 20,
                "filter": {
                    "inMailbox": "aba7e8d0-18d9-11eb-a677-2990b970028d"
                },
                "sort": [{
                  "property":"sentAt",
                  "isAscending": false
                }],
                "position": 20
            },
            "c2"
        ],
        [
            "Email/get",
            {
                "accountId": "{{accountId}}",
                "properties": [
                    "id",
                    "subject",
                    "from",
                    "receivedAt",
                    "sentAt",
                    "preview",
                    "hasAttachment"
                ],
                "#ids": {
                    "resultOf": "c2",
                    "name": "Email/query",
                    "path": "ids/*"
                }
            },
            "c3"
        ]
    ]
}
```
response:
```
{
    "sessionState": "2c9f1b12-b35a-43e6-9af2-0106fb53a943",
    "methodResponses": [
        [
            "Email/query",
            {
                "accountId": "3ce33c876a726662c627746eb9537a1d13c2338193ef27bd051a3ce5c0fe5b12",
                "queryState": "00000000",
                "canCalculateChanges": false,
                "ids": [],
                "position": 20
            },
            "c2"
        ],
        [
            "Email/get",
            {
                "accountId": "3ce33c876a726662c627746eb9537a1d13c2338193ef27bd051a3ce5c0fe5b12",
                "notFound": [],
                "state": "ceb36d20-ff3f-11eb-a9c2-2fef1ee78d9e",
                "list": []
            },
            "c3"
        ]
    ]
}
```
and the specs said:
![image](https://user-images.githubusercontent.com/6462404/129703800-9340ebb2-20bd-4540-b4b6-021f3df28a14.png)

**Comment by chibenwa** [comment]
Let me have a look

**Comment by chibenwa** [comment]
> 

https://jmap.io/spec-core.html#get

```
list: [...]  The results MAY be in a different order to the ids in the request arguments. 
```

To be spec compliant @hoangdat you need to sort them yourself (more precisely manually enforce the order returned by `/query` )

**Comment by Arsnael** [comment]
I know it sounds like a stupid question but... how many mails in your mailbox? The specs saying that if your position is higher than the number of mails then you get an empty list and it's not an error. 

I could double check but can you confirm if it's the case or not @hoangdat ?

**Comment by hoangdat** [comment]
haha. Yes, that the problem. 

We want to `paging` the request, so we set limit is 20, position = 0. It is ok for the first request. But then, we need to get more, limit = 20, position = 20. It is empty :(

So the question now is, `How to get support paging request?`

**Comment by Arsnael** [comment]
Ok @hoangdat I just reproduced it on preprod, I got the same as you bug confirmed! 

Also played around, it seems something is wrong with param `limit`. If I put it at 20 with position 20, 0 ids, limit at 30 and position 20, I get 10 ids, limit at 40 and position 20 and I get the 20 wanted ids. It seems limit always starts from 0 for some reasons... Will fix :)

**Comment by chibenwa** [comment]
Ok, got the bug,

@hoangdat  which environment ?

When using email query view, we request only `limit` messages before doing manually the filtering. Hence the bug.

You should not encounter this issue using the local memory image. Correct?

**Comment by hoangdat** [comment]
> which environment ?

https://dev.open-paas.org

@dab246 Did you have the same issue in Memory docker?

**Comment by Arsnael** [comment]
https://github.com/linagora/james-project/issues/4375

**Comment by chibenwa** [comment]
@Arsnael can you disable EmailQueryView on the DEV environment to unlock the mobile team?

**Comment by Arsnael** [comment]
> @Arsnael can you disable EmailQueryView on the DEV environment to unlock the mobile team?

First thing in the morning

**Comment by chibenwa** [comment]
The integration test reproducing the defect and the fix (with <3) https://github.com/apache/james-project/pull/603

**Comment by Arsnael** [comment]
> > @Arsnael can you disable EmailQueryView on the DEV environment to unlock the mobile team?
> 
> First thing in the morning

Done

**Comment by chibenwa** [comment]
@dab246 @hoangdat  can you confirm this fixed the issue?

**Comment by hoangdat** [comment]
Confirmed. It works. Many thanks
