### ISSUE TITLE
Move / delete emails emptys the view, explicit refresh needed...

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#600]
### Description

https://user-images.githubusercontent.com/6928740/170959689-87b99415-61d8-4457-a30c-0b852fc4ac7f.mp4

I delete / move emails, emptying the view.

It would be nice to "refill" the current view on the go without the need of explicit refresh.

Env: tmail.linagora.com, v 0.3.4 , chromium.

**Comment by hoangdat** [comment]
@chibenwa please recheck in your side at v0.3.6, I can not reproduce in all versions
