### ISSUE TITLE
[Story] As a user, I want to see list of filter email rules 

### ISSUE THREAD

**Issue by dieptran88** [linagora/tmail-flutter#610]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC

* TODO: {link}

## Definition

- Given that I am a Tmail user 
- After log-in successfully to Tmail, I go to setting screen
- On this setting screen, I can see a new tab: Filters 
- I can see the list of all current filters 
- On that list, I can see each rule with name and condition and action of rule

[Back to Summary](#summary)

## Screenshots

![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/25a08790-3e95-4f11-b841-f9079ffed000)

## Design ticket

https://ci.linagora.com/linagora/lgs/design/-/issues/229

[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

**Comment by hoangdat** [comment]
## Dev 

### Desc
1. Create `filter` module in `tmail-flutter` for `com:linagora:params:jmap:filter`

**Comment by hoangdat** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Tmail-Flutter-60d039db6ef62a0013432c14/issues/linagora/tmail-flutter/610?planning-poker) with ZenHub @dab246 @ManhNTX

**Comment by dab246** [comment]
2 HD

**Comment by dab246** [comment]
2 HD

**Comment by dab246** [comment]
2 HD
