### ISSUE TITLE
[Story] As a user, I want to create a new filter email rule 

### ISSUE THREAD

**Issue by dieptran88** [linagora/tmail-flutter#611]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC

* TODO: {link}

## Definition

- Given that I am a Tmail user
- After log-in successfully, I go to Setting page
- I select Tab "Filters" and see the list of current filters
- I can see a button "Create new filter"
- When I click on this button, A new screen will be displayed
- On this screen, I can see fields:
1. - Filter name: This is a text field and mandatory
2. - Conditions: A drop-down list with options: 
      - is from
      - is addressed to 
      - is cc to
      - is addressed or cc to
      - has subject containing 
- If I select one of above conditions except for "has subject containing", then I need to input email addresses to the text field below:
   - When I input some character, I can see the suggestion list of emails and I can select 
   - When the email address is invalid, there will be an error message 
- If I select the condition:"has subject containing", then I need to input text in the field below 
3. Action
- Currently, there is only 1 action : move to the destination folder
- When I click on the drop-down list, I can see the list of all current mailbox. I can select one mailbox as the destination folder 

- After Input all fields, I click button Create, the system will validate:
   - If any of above fields is blank, there will be an error message
   - If not, the filter is created successfully and is displayed on the listing rule screen 
- After a filter email rule is saved successfully, it will be applied for the new coming emails. 
- The order to applied filtering rules is from the latest created date to the earliest created date of filters. 

[Back to Summary](#summary)

## Screenshots

![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/52e6c948-6ced-41c1-bd2a-2431e6c19587)

## Design ticket

https://ci.linagora.com/linagora/lgs/design/-/issues/230

## Misc

None

[Back to Summary](#summary)

**Comment by hoangdat** [comment]
https://github.com/linagora/tmail-backend/blob/master/docs/modules/ROOT/pages/tmail-backend/jmap-extensions/jmapFilters.adoc

**Comment by hoangdat** [comment]
### Dev:
- value must be non-empty

**Comment by hoangdat** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Tmail-Flutter-60d039db6ef62a0013432c14/issues/linagora/tmail-flutter/611?planning-poker) with ZenHub @dab246 @ManhNTX

**Comment by dab246** [comment]
2 HD
