### ISSUE TITLE
[Srory] As a user, I want to edit a filter email rule 

### ISSUE THREAD

**Issue by dieptran88** [linagora/tmail-flutter#612]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC

* TODO: {link}

## Definition

- Given that I am a Tmail user
- After log-in successfully, I go to Setting page
- I select Tab "Filters" and see the list of current filters
- I click on a filter and the detail screen of that email filter will be opened 
- On this screen, I can edit fields: Name,  Condition, and destination folder 
- After editing the filter, I can click button Save
- If there is no error, the filter is updated successfully and there will be a notification message 

[Back to Summary](#summary)

## Screenshots

![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/86d0176e-914a-455e-8193-f8c90f5a1186)

## Design ticket 

https://ci.linagora.com/linagora/lgs/design/-/issues/231

[Back to Summary](#summary)

## Misc

None

[Back to Summay](#summary)

**Comment by dab246** [comment]
1 HD
