### ISSUE TITLE
[Story] As a user, I wan to delete a filter email rule 

### ISSUE THREAD

**Issue by dieptran88** [linagora/tmail-flutter#613]
![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/99cb6ca2-a4fd-47eb-a1a9-7bf96eb2df23)# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC

* TODO: {link}

## Definition

**UC1. Delete an email filter**
- There are 2 ways to delete a email filter: 
1. On the filters list, I click on a filter, and the detail screen of that filter will be displayed 
- I click on button Delete
- There will be confirmation popup, I click Yes to confirm
- The filter will be deleted successfully with a toast message
2. On the filter list, When I hover a filter, there will be a Delete icon 
- I click on this Delete icon
-  There will be confirmation popup, I click Yes to confirm
- The filter will be deleted successfully with a toast message

**UC2. Delete multiple email filters**
- On the email filter list, I can select multiple filters by clicking the checkbox in each filter
- There will e a button Delete, which will be appeared when I select checkbox
- I click on Delete button
- There will be a confirmation popup and I choose Yes to confirm
- The filters will be deleted successfully with a toast message
- After a filter is deleted successfully, it will disappear on the filter list and the new coming emails will not be applied by the rule.

[Back to Summary](#summary)

## Screenshots

![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/e7589179-5a11-4380-8a48-33d36cf6c295)

## Design ticket

https://ci.linagora.com/linagora/lgs/design/-/issues/232

[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

**Comment by dab246** [comment]
2 HD

**Comment by dab246** [comment]
1 HD
