### ISSUE TITLE
Firefox: tmail.linagora.com env.file might return localhost as JMAP URI

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#615]
### Description

Cannot login in Firefox.

![Screenshot from 2022-06-02 10-39-06](https://user-images.githubusercontent.com/6928740/171549012-853576fa-2c1f-4a2f-a115-caab0cba8519.png)

The browser requests the env file to discover the URI of the JMAP server backing the web mail.

However here the response is decoded as:

```
U0VSVkVSX1VSTD1odHRwOi8vbG9jYWxob3N0 

->

SERVER_URL=http://localhost
```

On chrome this works fine!

![Screenshot from 2022-06-02 10-48-26](https://user-images.githubusercontent.com/6928740/171549287-10d456fa-6dee-415d-bec8-39d6a8b2a060.png)

Doing curl manually this works fine:

```
$ curl -XGET https://tmail.linagora.com/assets/env.file
SERVER_URL=https://jmap.linagora.com
```

On the server static configuration is right...

```
$ cat linagora-openpaas-setup/tmail-web/env.file 
SERVER_URL=https://jmap.linagora.com
```

### Expected result

`SERVER_URL=https://jmap.linagora.com` on firefox too

**Comment by hoangdat** [comment]
same with #508

**Comment by hoangdat** [comment]
I debug and found something new.
1. I pulled the image `tmail-web` container base on the guide in: https://hub.docker.com/r/linagora/tmail-web
2. I configured `env.dev.file` in my current folder
<img width="602" alt="Screen Shot 2022-06-13 at 22 28 04" src="https://user-images.githubusercontent.com/6462404/173391661-68932250-7729-4b84-a9fd-85fcace70cb7.png">
3. I run the container

```
  docker run -d -ti -p 8080:80 --mount type=bind,source="$(pwd)"/env.dev.file,target=/usr/share/nginx/html/assets/env.file --name web linagora/tmail-web:master
```

4. And I found that: we have 2 `env.file` and `env.file.gz` in `assets` folder
<img width="566" alt="Screen Shot 2022-06-13 at 22 33 01" src="https://user-images.githubusercontent.com/6462404/173392242-586ffdc1-3d05-4ca9-99c1-21313a67c65d.png">

5. Content of 2 files here:

<img width="448" alt="Screen Shot 2022-06-13 at 22 36 15" src="https://user-images.githubusercontent.com/6462404/173392462-0dbf2b5d-ba24-4038-ad7d-7e57cabb8cdc.png">

**Comment by chibenwa** [comment]
Good catch....

**Comment by chibenwa** [comment]
We need to mon=unt also the .zipped version

**Comment by hoangdat** [comment]
https://github.com/linagora/james-project-private/issues/419

**Comment by hoangdat** [comment]
+1HD
