### ISSUE TITLE
[Story] As an user, i want to open and view a thread

### ISSUE THREAD

**Issue by dieptran88** [linagora/tmail-flutter#62]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Technical issues](#technical-issues)
* [Misc](#misc)

## Definition

- Given that i am a Tmail user and i already had an account (John Doe).
- Given that i log-in successfully to the Tmail app.
- I can see the default view  is Inbox mail list.
- I click on Inbox title, the list of mailboxes screen will be opened. 
- I  select a mailbox and the list of mail inside that mailbox will be opened.
- Ịn this email list, Replies are grouped together with the original message to form a Thread. 
- In a thread, emails are ordered automatically by latest date-time

[Back to Summary](#summary)

#### Final design

[Back to Summary](#summary)

## Technical issues

[Back to Summary](#summary)

## Misc

[Back to Summary](#summary)

**Comment by chibenwa** [comment]
> Ịn this email list, Replies are grouped together with the original message to form a Thread. 

This is not a priority.

We today only have support for `Thread/get` but not yet support refreshes (Thread/changes and events). Also the collapseThread option on `Email/query` would force clients to implement paging thenselves (requesting groups of messages and removing duplicates themselves.)

As this is not mature on backend side (nor in my opinion an absolute UX obligation) we can delay this for now.

**Comment by dieptran88** [comment]
but we still can display replies in quote ?
![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/747ac7ee-fddc-49e9-ad06-84ecd7f73643)

**Comment by chibenwa** [comment]
This is not what we can a message thread.

You show a specific email body quoting previous emails of a thread, this is different from the threading feature.

First you need to understand threading happens on a mail list view.

https://www.mail-archive.com/server-dev@james.apache.org/ see thread / date.

**Comment by chibenwa** [comment]
See https://support.mozilla.org/en-US/kb/message-threading-thunderbird

**Comment by dieptran88** [comment]
Thank you, is is helpful

**Comment by dieptran88** [comment]
@hoangdat Since the thread has not supported yet, should i write a story to view a  replied email ?

**Comment by hoangdat** [comment]
Not priority

**Comment by hoangdat** [comment]
not supported
