### ISSUE TITLE
Study jmap spec and write unit test for Email/query

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#625]
### Use-case:
- [x] Search emails from some one
- [x] Search emails in `Inbox` which have the string `report`
- [x] Search emails from someone in last 30 days
- [x] Search emails from someone which have the string `report` and `receviedAt` from `23 Jan 2022` to `23 Apr 2022`

### Desc:
- Spec: jmap.io
- Resource: Email
- Method: `/changes`, `Email/changes`, `Email/get`

### DoD:
- Execute `postman` for these cases
- Write unit-tests for these cases in [jmap-dart-client](https://github.com/linagora/jmap-dart-client)

**Comment by chibenwa** [comment]
What are you looking for?

You want sample requests?

**Comment by hoangdat** [comment]
> What are you looking for?
> 
> You want sample requests?

A task to help newcomer understand about jmap spec and how to work with jmap-dart-client.

**Comment by hoangdat** [comment]
+2HD
