### ISSUE TITLE
Implement Advanced Search for email

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#627]
### Story:

#478 

### Design:

https://www.figma.com/file/rRVxJpCu1G22D0jqyvK7I9/TeamMail?node-id=2632%3A159883

<img width="1127" alt="image" src="https://user-images.githubusercontent.com/6462404/172294314-7a638252-0284-46ad-929d-55fe70a02724.png">

### Desc:

- Interactor: `SearchEmailInteractor`
- Repository: `ThreadRepository`

### DoD:
- Can filter the emails which matched the criterias 
- UI as design: mobile/tablet/browser

**Comment by hoangdat** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Tmail-Flutter-60d039db6ef62a0013432c14/issues/linagora/tmail-flutter/627?planning-poker) with ZenHub @dab246

**Comment by hoangdat** [comment]
+1HD

**Comment by hoangdat** [comment]
2HD

**Comment by hoangdat** [comment]
2HD

**Comment by hoangdat** [comment]
2HD

**Comment by hoangdat** [comment]
1HD - off

**Comment by hoangdat** [comment]
2HD

**Comment by ManhNTX** [comment]
[](url)When i using Email\query method has error like below. Please check this.
Request:
<img width="1032" alt="Screen Shot 2022-06-21 at 12 52 12" src="https://user-images.githubusercontent.com/107173849/174739563-c979ae0d-f33f-46d9-8f0e-1ce80f4f178b.png">
Response:
<img width="640" alt="Screen Shot 2022-06-21 at 12 52 20" src="https://user-images.githubusercontent.com/107173849/174739665-88713919-8806-4c95-9e55-85196a2ff23d.png">

**Comment by chibenwa** [comment]
Yes @ManhNTX Remove the AND:

```
"filter": { "conditions": [ { "inMailbox" ...} , {"operator": "AND", "conditions": [] } 
```

The inMailboxFilter need to be at the top level to be supported by James.

In practice this is powerful enough to express all JMAP queries

Other products like Cyrus are subject to similar limitations.

**Comment by ManhNTX** [comment]
I follow step by like your comment but still error:
Request:
<img width="758" alt="Screen Shot 2022-06-21 at 14 51 28" src="https://user-images.githubusercontent.com/107173849/174747339-6b38aba5-c986-454f-9a62-44636233d324.png">
Response:
<img width="765" alt="Screen Shot 2022-06-21 at 14 51 37" src="https://user-images.githubusercontent.com/107173849/174747259-aadaccc9-f979-4591-9d05-1035802e5141.png">

**Comment by chibenwa** [comment]
```
"conditions": [
    {"inMailbox":xyz,
      "hasAttachment": true}
]
```

???

**Comment by chibenwa** [comment]
For your information I also relaxed the assumptions James does on the filter structure.

Now one inMailbox* condition can be put in a AND. No nesting, no double inMailbox criterion.

https://github.com/apache/james-project/pull/1060

**Comment by hoangdat** [comment]
2HD

**Comment by hoangdat** [comment]
2HD

**Comment by hoangdat** [comment]
2HD

**Comment by hoangdat** [comment]
Remaining:
- [ ] auto complete email
- [ ] docs ADR

**Comment by hoangdat** [comment]
2HD

**Comment by hoangdat** [comment]
2HD

**Comment by hoangdat** [comment]
1HD
