### ISSUE TITLE
[Story] As an user, i want to compose an email with rich text and media content

### ISSUE THREAD

**Issue by dieptran88** [linagora/tmail-flutter#63]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

### UC1: Compose an email with rich text format 

- Given that I am a Tmail user and I Logged-in the app 
- When I create/reply/forward an email, the composer view is opened 
- On the email body part, I can see a chevron icon
- When I touch that icon, I can see a format bar with HTML options: 
   - Style: When I select this option, a drop-down list will be displayed, I can select one type from the list, the drop-down list is closed and When i start writing the email content, the new font style will be applied:  `Quote`, `Code`,  `Header`, "Normal"
   - Font: When I select this option, a drop-down list will be displayed, I can select one type from the list, the drop-down list is closed and When i start writing the email content, the new font will be applied. There will be a default font. 
   - Font size: I can select font size from a drop-down list, then when I start to type, the new font size will be applied. There will be a default font size. 
   - Text color/Text background color: When I select this option, a drop-down list will be displayed. I select one color and the drop-down list is closed. When i start writing the email content, the new color will be applied.  
   - Bold/Italic/Underline/Strikethrough : I can tough the icon to select/un-select these options. When i start typing after select one option, it will be applied until I unselect it. 
   - Bullet/Numbering: I can onlly select one between these 2 options
   - Align: When I select this option, there will be a drop-down list with options: Left, Right, Center. Default value is Align Left
   - Indent/Outdent: I can click to add and remove an amount of space at the beginning of a line of text. 
   - Insert table: When I select this option, there will be a table displayed that allows me to select number of rows and columns of the inserted table. 
      - When I click on the table, I can see options: Add row below, Add row above, Add column left, Add column right, Delete table.
   - Line height: When I click this option, there will be a drop-down list which allow me to select one . Default line height is 1 
   - Undo/Redo: This option will allow user to undo/redo the last change. 
   - Clear formatting: When I select this option, it will clear all the current formatting to the default.  

### UC2 rich text format on mobile app 

- On mobile app, when I compose some text, and long-press to blacked out the text, a format tool bar will be displayed with options:
   - Bold
   - Underline
   - Italic 
   - Text color 
   - Background color
- I can apply the format options to the selected text or clear the format easily. 

### UC3: Compose an email with media content 
- Given that I am in Composer view 
- I am typing in the email content
- I can see the option Insert image in Format bar
- When I select this option, the File browser will be opened and I can select images from device
- The image will be displayed inline in the email content at the position that I left the cursor before opening file browser
- I can use the character remove on the keyboard to remove the image.
- Then I can continue composing the email and send it. 

[Back to Summary](#summary)

### Mobile
![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/a63054ce-d3b8-4fb6-a37d-01b0d24d9960) ![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/c2d8a6a4-5c95-415f-916d-96950fcab823)

![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/9c4ba2f7-6bb4-4b7e-955c-31ca04c4b19c) ![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/c02ad8b9-3778-4613-a4fe-dd27fee3efcb)

![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/bfb286cd-c121-4d7e-a74a-7d13f96660ad)

### Tab
![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/ef69c1e2-f33a-40d0-96cf-2e16c2e7a036)
![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/3ab2f68d-8639-4daf-89d1-69e2ce461387)

[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

**Comment by hoangdat** [comment]
@dieptran88 please prioritize to complete this story

**Comment by hoangdat** [comment]
### UX
 
#### mobile
- only support **B** _I_ <u>U</u>

**Comment by hknguyen91** [comment]
Screens updated is here: https://www.figma.com/file/rRVxJpCu1G22D0jqyvK7I9/TeamMail?node-id=4716%3A226759
