### ISSUE TITLE
Can not see the identity when composing email

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#633]
![image](https://user-images.githubusercontent.com/6462404/172390494-69cc1d0b-30f6-4850-b35e-5cbcf918fda0.png)

**Comment by dab246** [comment]
- If currently the identity list (with `mayDelete=true`) is empty, the identity will not be displayed in `composer` and `settings`
- In this case `send email` with `from` is the email of `user`
Watch demo video for more details

https://images.zenhubusercontent.com/378835363/17cfc7fd-71dd-49a0-a7aa-aea46bec6cb6/screen_recording_2022_06_17_at_12_21_25.mov

**Comment by Kevinle2312** [comment]
PAssed on Production platform.
