### ISSUE TITLE
Image attachment send from TeamMail can not open in gmail

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#634]
![image](https://user-images.githubusercontent.com/6462404/172392250-fda4335c-eecd-4101-a8c1-0fefa532b61a.png)

**Comment by chibenwa** [comment]
Can you share the eml?

**Comment by chibenwa** [comment]
Plateform: prod, right? Do you reproduce on preprod?

**Comment by chibenwa** [comment]
OK I bet TMail backend 0.6.0 solves this....

**Comment by hoangdat** [comment]
yes, Production. I will test more on preprod today.

**Comment by chibenwa** [comment]
Fixed ?

**Comment by hoangdat** [comment]
Tested. Confirmed
