### ISSUE TITLE
On the mobile version, some emails are difficult to scroll in vertical

### ISSUE THREAD

**Issue by Kevinle2312** [linagora/tmail-flutter#639]
### Description
On the mobile version, some emails are difficult to scroll

### Expected result
On the mobile version, all email is scrolable vertical as well as horizontal 

### Current behaviour
On the mobile version, some emails are difficult to scroll in vertical 

### Context

Android - v0.3.6
Pre-production, Production platform.

### Additional information

![image](https://user-images.githubusercontent.com/32490981/172796131-2b14edf4-146e-48aa-989d-8cc6028e93ac.png)

**Comment by hoangdat** [comment]
1HD

**Comment by haftus98** [comment]
https://user-images.githubusercontent.com/97084773/202359325-36ce7e0c-58ba-46c4-a32d-d70f48164277.mp4

still can not view the mail horizontally. V0.4.1

**Comment by hoangdat** [comment]
> still can not view the mail horizontally. V0.4.1

Horizontal is different from vertical. Horizontal will be fixed in #1203
