### ISSUE TITLE
[Web - Tmail] The tmail session is corrupted when reopen tmail after a while

### ISSUE THREAD

**Issue by Kevinle2312** [linagora/tmail-flutter#640]
### Description
On the browser, The tmail session is corrupted when reopen tmail after a while.

### Expected result
Tmail should automatic sign out or keep session after xx min of inactive. 

### Current behavior
On the browser, The tmail session is corrupted when reopen tmail after a while.

#### Reproduction Steps
1. Sign in to tmail
2. Let the computer sleep
3. Open the machine and refresh tmail
4. Verify the issue

### Context

Production platform tmail.linagora.com - version v.0.3.6
Windowws 10 - Google Chrome

**Comment by hoangdat** [comment]
without OIDC

**Comment by dab246** [comment]
I tried again on both `with OIDC` and `without OIDC`. But still can't reproduce such error. Please give me more information. @Kevinle2312

**Comment by Kevinle2312** [comment]
> I tried again on both `with OIDC` and `without OIDC`. But still can't reproduce such error. Please give me more information. @Kevinle2312

Have you let the machine in sleep mode and then re-open it again yet?.

**Comment by Kevinle2312** [comment]
Passed on the Production platform.
