### ISSUE TITLE
version of flutter

### ISSUE THREAD

**Issue by webtech09** [linagora/tmail-flutter#642]
Hi,

what version of flutter compatible for this app? im trying to pub get the app its saying"
Because every version of flutter_test from sdk depends on collection 1.16.0 and tmail_ui_user depends on collection 1.15.0, flutter_test from sdk is forbidden.
So, because tmail_ui_user depends on flutter_test from sdk, version solving failed.
pub get failed (1; So, because tmail_ui_user depends on flutter_test from sdk, version solving failed.)"

**Comment by hoangdat** [comment]
Hi @webtech09, it is useful for you? 
I will close this, don't hesitate to ask more. Thanks
