### ISSUE TITLE
Show the progress of download attachment in app

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#654]
### Desc:

At the moment, when we download an attachment in browser, it takes some delay (downloading bytes of attachment) before show in bottom of browser.

### DoD:
- [ ] Designer: design the view to indicate user downloading attachment progress
- [ ] Dev: implement progress in web-app

**Comment by hoangdat** [comment]
@chibenwa please let us more related information

**Comment by chibenwa** [comment]
The dowload response should have a content length header allowing you to know the size of what you need to download.

Then you just need to count the downloaded bytes.

> => I don't know if the server side currently supports getting downloadUrl public so we can do that?

Thats off spec...

**Comment by hoangdat** [comment]
so you mean, we can not transfer the download task to browser like `openpaas`. We need to show the progress our-self. Am I right?

**Comment by chibenwa** [comment]
Right.

**Comment by hoangdat** [comment]
- Progress in toast

**Comment by dab246** [comment]
1 HD
