### ISSUE TITLE
[Story] As a sender, I want to ask the Recipient to send me a read receipt.

### ISSUE THREAD

**Issue by dieptran88** [linagora/tmail-flutter#656]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC

* TODO: {link}

## Definition

- Given that I am a Tmail user
- After logged-in successfully, I click button to create a new email 
- On the composer, I can see an option: Request a read receipt 
- I can select or un-select this option
- If I enable the setting: "Always request read receipts with outgoing messages", then the option Request a read receipt is selected by default for any new message 
- If I disabled that setting, the option equest a read receipt is un-selected by default for any new message.
- I can continue composing email as normally then click button Send
- The read receipt request is sent to the receiver with the email. Depending on the mail system the receiver uses, the request can be displayed with the email content. 

[Back to Summary](#summary)

## Screenshots

![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/04e2820b-c219-4d45-b9e9-2c0e92eca84d) 

[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

**Comment by dab246** [comment]
### Dev
- Add `Disposition-Notification-To: Sender <sender@domain.tld>` to `header` of email before sent email.
- Example:
```json
[
  [
    "Email/set",
    {
      "accountId": "ue150411c",
      "create": {
        "k2657": {
          "mailboxIds": {
            "2ea1ca41b38e": true
          },
          "keywords": {
            "$seen": true,
            "$draft": true
          },
          "from": [
            {
              "name": "Joe Bloggs",
              "email": "joe@example.com"
            }
          ],
          "to": [
            {
              "name": "John",
              "email": "john@example.com"
            }
          ],
          "header:Disposition-Notification-To:asText": "joe@example.com",
          "subject": "World domination"
        }
      }
    },
    "0"
  ]
]

### Refers
- Docs [RFC9007](https://www.rfc-editor.org/rfc/rfc9007.html#name-mdn-parse)
```

**Comment by dab246** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Tmail-Flutter-60d039db6ef62a0013432c14/issues/linagora/tmail-flutter/656?planning-poker) with Zenhub @hoangdat @ManhNTX

**Comment by dab246** [comment]
1 HD

**Comment by dab246** [comment]
2 HD
