### ISSUE TITLE
[Story] As a receiver, I want to send a read receipt when asked by the sender (confirmation button)

### ISSUE THREAD

**Issue by dieptran88** [linagora/tmail-flutter#657]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC

* TODO: {link}

## Definition

- Given that I am a Tmail user and I received an email that request a read receipt
- After logged-in successfully, I go to Inbox 
- I open that email and see a popup message: "[Sender] has asked to be notified when you read this message" with 2 buttons "Send receipt" and "Ignore request"
- I select option "Send receipt", then an notification email will be sent to the sender. When I open this email the next time, the popup will not prompt again.
- If I select option "Ignore", then the popup is closed. When I open this email the next time, the popup will prompt again. 

[Back to Summary](#summary)

## Screenshots

![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/6b651820-a2cb-4c2c-b9f3-93c68e43e135)

[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

**Comment by dab246** [comment]
### Dev
- If a received email `(not in sent mailbox)` has `Disposition-Notification-To` header and no `$mdnsent` keyword then show popup message

**Comment by dab246** [comment]
2 HD

**Comment by dab246** [comment]
1 HD
