### ISSUE TITLE
[Story] As a user, I want to enable/disable option :" Always request read receipts with outgoing messages"

### ISSUE THREAD

**Issue by dieptran88** [linagora/tmail-flutter#660]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC

* TODO: {link}

## Definition

- Given that I am a Tmail user 
- After logged-in successfully, I go to setting screen
- On this setting screen, I can see a new tab: Receipts 
- I can see a toggle button :"Always request read receipts with outgoing messages ?"
- I can turn on/of this toggle and click button Save:
   - If the toggle is switched on, then when I compose a new email, the option "Request  a read receipt" is selected by default 
   - If the toggle is switched off, that option will not be selected by default.

[Back to Summary](#summary)

## Screenshots

![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/ec317f44-d485-4f35-8f15-5fbef185d5cf)

[Back to Summary](#summary)

## Misc

None

[Back to Smary](#summary)

**Comment by dab246** [comment]
### Dev

- Figma: [https://www.figma.com/file/rRVxJpCu1G22D0jqyvK7I9/TeamMail?node-id=5199%3A232926](https://www.figma.com/file/rRVxJpCu1G22D0jqyvK7I9/TeamMail?node-id=5199%3A232926)

**Comment by hoangdat** [comment]
Not need settings for this function
