### ISSUE TITLE
Fix deployment for teammail preprod

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#663]
### Desc:

- platform: https://tmail.upn.integration-open-paas.org/
- env file still missing some variable: 

  - `DOMAIN_REDIRECT_URL`: domain url of app
  - `WEB_OIDC_CLIENT_ID`: clientId of OIDC 

### DoD:
```
SERVER_URL=https://jmap.upn.integration-open-paas.org
DOMAIN_REDIRECT_URL=https://tmail.upn.integration-open-paas.org/
WEB_OIDC_CLIENT_ID=teammail-web
```

**Comment by chibenwa** [comment]
Question: What are DOMAIN_REDIRECT_URL + WEB_OIDC_CLIENT_ID used for ?

**Comment by hoangdat** [comment]
- `DOMAIN_REDIRECT_URL`: domain url of app

to setup `redirect_url` for login and logout in `PKCE` flow

- `WEB_OIDC_CLIENT_ID`: `oidc client id` which your app use to connect with OIDC

**Comment by ducnm0711** [comment]
Fixed, can close.

Details of the fix:
https://gitlab.com/linagora_private/saas/tmail/ticketing/-/issues/1

**Comment by hoangdat** [comment]
we have a trouble with CORS

<img width="855" alt="image" src="https://user-images.githubusercontent.com/6462404/174023266-4529d1ee-889a-4f03-bf83-ff1631ac0c5f.png">

**Comment by hoangdat** [comment]
@ducnm0711 please help me on it :(

**Comment by hoangdat** [comment]
fixed in auth-dev: https://www.czetsuyatech.com/2019/12/keycloak-cors-policy-error-no-access-control-allow-origin-header.html
