### ISSUE TITLE
[Story] As an user, I want to move a message to folder

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#67]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC

* TODO: {link}

## Definition
**UC1. Move a message to another folder**
- Given that i am Tmail user and logged-in to the app 
- I opened a mailbox and see the thread view of that mailbox
- I can move message from mailboxes: All mail, Inbox, Sent, Trash, Spam, Templates and my created folders 
- I can move one message to another mailbox in 2 ways:
1. - I open the mail then click on icon Move file, then the Pick destination screen will be opened
2.  - On the thread-view, i can long-press on the avatar icon to select that email, then there will be an action bar displayed on the top.
     - I click on three-dots button then there will be a context menu that contain actions. I select option "Move to mailbox", then the Pick destination screen will be opened
- On Pick-destination screen, i can see the list of mailbox: Inbox, Sent, Trash, Spam, Templates and my created mailboxes
- If the mailbox has child folder, I can touch the arrow icon to expand the parent folders to the last child folder. 
- When I touch a folder on the list, the message will be moved to that selected folder 
- The Pick destination screen is disappear, the message is no longer in the original mailbox and moved to destination mailbox 
- A message in "All mail" is simultaneously belongs to an original mailbox (e.g: Inbox). If I move a message from "All mail" to another mailbox, it is also moved from the original mailbox. 

**UC2. Search destination mailbox**
- Given that I am in Pick destination screen of moving message
- I can see a search box 
- I touch the search box, the keyboard will appear
- when I start typing in the search bar, the app will display result under search bar
- The result will updated instantly when i am typing
- The search result contains folders in ALL level of folder tree.
- If a mailbox of ANY level contains the search pattern then it should be displayed with its parent.
- I can choose a mailbox from the result screen as destination mailbox 

**UC3. Undo the moving message**
- After moving a message from a mailbox to another mailbox successfully, the moving screen will be closed, and the previous screen is shown
- There will be an successful toast message:"Moved to [destination mailbox's path]" and a button Undo
- When I touch this button, the moved message will be returned to the original mailbox. 

[Back to Summary](#summary)

### Mobile
![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/a156283b-179b-43a7-8bd5-00dc19800a64) ![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/052b518e-7d30-4440-820c-8aea133aa423)  
![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/15ceff84-78be-47c6-9bde-e857099b1330)

![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/2eb3e994-ec8a-466f-93ae-67f44927cd0d) ![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/e489a406-5a9a-4e71-b18c-510a9c4a9a41)
### Tab
![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/84ca0ccc-86a3-481c-9dbd-aa24bfb30ba4)
![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/fa6a7dc1-2aa6-4853-952f-fd06534e90ac)
![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/47977582-dd41-4662-bc1a-cf49cb840ab8)
![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/0ea99bc4-991e-474b-ad69-7cea3f73da24)
![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/4520459b-f1dc-43d2-849d-7d2e55793951)

[Back to Summary](#summary)

## Design ticket

https://ci.linagora.com/linagora/lgs/design/-/issues/152

## Misc

None

[Back to Summary](#summary)

**Comment by hoangdat** [comment]
@dieptran88 Please write this US. And mockup the destination picker ASAP.

**Comment by hoangdat** [comment]
@dieptran88 it is not design, so I repopen it to get the design and re-implement it in UI layer

**Comment by hoangdat** [comment]
@dieptran88 let create the design ticket for browser

**Comment by dieptran88** [comment]
> @dieptran88 let create the design ticket for browser

https://ci.linagora.com/linagora/lgs/design/-/issues/175 
here it is

**Comment by Kevinle2312** [comment]
Passed on Pre-production and Production platform.
