### ISSUE TITLE
Can not login in Staging platform

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#671]
### Desc:
- staging: https://tmail.upn.integration-open-paas.org/
- after get token, request session face the problem

<img width="589" alt="image" src="https://user-images.githubusercontent.com/6462404/174565292-7463680a-039b-4acf-bfbf-2654fd81802d.png">

### DoD:
- [ ] Can login in staging platform

**Comment by hoangdat** [comment]
- explaination here: https://github.com/linagora/tmail-flutter/issues/472#issuecomment-1168326078
- new error: 500 `during fix`
<img width="453" alt="image" src="https://user-images.githubusercontent.com/6462404/176128598-edbf90aa-578c-4827-a328-734aa9bc6bf7.png">

**Comment by chibenwa** [comment]
Yes @Arsnael is on it...

**Comment by Arsnael** [comment]
https://github.com/apache/james-project/pull/1068

**Comment by Arsnael** [comment]
Fix deployed. I could login with oidc on staging successfully, good job guys :)
