### ISSUE TITLE
Upload multiple attachments in multiple time have problem

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#675]
### Reproduce:
- Upload file 1: 10 Mb 
- while file 1 is uploading, upload file 2
- Upload file 2
- Observe the attachment after progress icon is disappeared, only file 2 is showed

### DoD:
- Apply isolate
- all files are attached 
- apply the UI from designer: progress in item, icon of file

**Comment by dab246** [comment]
1 HD

**Comment by dab246** [comment]
2 HD
