### ISSUE TITLE
[Dev] Compose email with text style for mobile

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#677]
### Story

#630 

### Desc:

- Support style `bold`, `italic`, `underline`, and `default (no select any option)`

### DoD:

- Add tool box as the design for composer in mobile/tablet: can enable/disable it by programming
- can apply `bold`, `italic`, `underline` in the composer in:
    long press on selected text/paragraph -> option show `B I U` -> apply it to selected text

**Comment by ManhNTX** [comment]
PR: https://github.com/linagora/tmail-flutter/pull/724
