### ISSUE TITLE
[Trash folder] - the deleted folder should not count messages

### ISSUE THREAD

**Issue by Kevinle2312** [linagora/tmail-flutter#688]
### Description
The trash folder is counting messages.

### Expected result
The trash folder should not count messages.

### Current behaviour
The trash folder is counting messages.

### Acceptance criteria

https://github.com/linagora/tmail-flutter/issues/258

`Trash: Do not count
Spam: Do not count`

### Context

Production platform

### Additional information

![image](https://user-images.githubusercontent.com/32490981/176088785-aebe622b-5e89-4ae5-9013-233bb2f73e10.png)

**Comment by haftus98** [comment]
verified
