### ISSUE TITLE
Advanced search improvement

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#691]
- [ ] web: change input filed by `Tab`
- [ ] need option to apply advanced search in all mailbox
- [ ] title of destination picker in advanced search should be changed
- [ ] test and fix more :)

**Comment by hoangdat** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Tmail-Flutter-60d039db6ef62a0013432c14/issues/linagora/tmail-flutter/691?planning-poker) with ZenHub @dab246 @ManhNTX

**Comment by dab246** [comment]
2 HD
