### ISSUE TITLE
[ Feedback] When  I click on the field "subject" on composer, I cannot input text but I have to click outside the text "Subject" 

### ISSUE THREAD

**Issue by dieptran88** [linagora/tmail-flutter#703]
### 1. 
-  When  I click on the field "subject" on composer, I cannot input text but I have to click outside the text "Subject" 
- When I click the button "+" on the field "To", nothing happens
- It is on both mobile app and web

## Screenshot

![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/4365dfc3-87bd-4c20-ac2f-95db3e71741b)

### 2.

-  when my device's network is not connected, I open Log-in screen and input log-in credentials, there is no network error message => I cannot know what error I am facing 

### 3.
- The system do not eliminate duplicated email address in the field recipients 

![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/7fe7b24b-d4f1-4368-b9d5-b80bbee3cd42)

### 4. I should not be able to select all email and actions in View email content screen 

![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/ccaf6c9b-187c-492c-a641-328323cfcf29)

### 5. I cannot see the link in email content 

![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/3508ca01-b12f-4958-b342-c806e79c920a)

![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/8af074a9-0dc3-4c4b-82a8-600620878b90)

### 6. Search advance

- There is no date picker
- Currently the default mailbox is INBOX, and there is no option "All mailboxes" 
- The screen mailboxes picker is different in comparison with design

**Comment by hoangdat** [comment]
- Please re-test 1.
- 2. `Unknown error` showed
-> Fix: dedicated error showed
 - research `ActionOnline/Offline`
- 3. check duplicated email, show tag error, prevent send email
- 4. [web] observe `routePath` and disable/enable 
- 5. request Diep to send this email again
- 6. #691

**Comment by dieptran88** [comment]
> @dieptran88 Please re-test 1.
> 
> 5. Please download the eml or re-send us the email with openpaas
> 6. [Advanced search improvement #691](https://github.com/linagora/tmail-flutter/issues/691)

About 1: It is not an error, It is just my experience: 
- The text "subject" is like a placeholder text, that should be disappear when I start to write, or the text color should be black so I know it is non-editable.
- when I click button "To", the cursor should be appear on this field

5. my emai is thdtran@linagora.com
