### ISSUE TITLE
[Web] Can not remove email in Bcc filed of Edit identity

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#711]
### Reproduce

https://user-images.githubusercontent.com/6462404/178409751-4e3e5e4c-18f7-4339-88fb-6d45e0eaae5e.mov

### Expected
- [ ] Can edit any fields when edit Identity

**Comment by hoangdat** [comment]
The same problem in Pre-prod: https://gateway.upn.integration-open-paas.org/jmap

**Comment by hoangdat** [comment]
Hi @Arsnael when we have the back-end fixed will release? I saw a PR is merged :) Thanks

**Comment by Arsnael** [comment]
Pretty sure it's been merged back to TMail...

Been a while we didn't redeploy things though. Remind me tomorrow and I could check for staging env

However on LNG you gonna have to wait for the next release

**Comment by haftus98** [comment]
verified on IOS Andoid Web browser V0.3.17
