### ISSUE TITLE
[Bug] When typing address, input @ will be delete all previous input

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#72]
### Acceptance criteria

The list of acceptance criteria (defined in the corresponding User Story or coming from your functional knowledge of the product)
These acceptance criteria must be met by the corrective implementation done by the developers.

### Context

Devices, OS

### Additional information

frequency, log files,...

**Comment by dab246** [comment]
- Fixed bug in`flutter_chip_input` library at https://github.com/dab246/flutter_chips_input/commit/1ae43c0129d380bb800d5d774b1efee58649d040

https://images.zenhubusercontent.com/378835363/828b4b41-9641-4a6b-9c0f-e7cb6864772c/test.mp4

**Comment by chibenwa** [comment]
Did you open a bug report upstream nd proposed these changes as a pull request upstream?

Can you link the PR / issues?
