### ISSUE TITLE
[Android]Html content is big after rendering

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#729]
### Desc:
- only in Android
- v0.3.8

![Screenshot_20220718-112557](https://user-images.githubusercontent.com/6462404/179445364-6f979075-4543-4083-80a1-a53ebe0b37c8.png)

**Comment by hoangdat** [comment]
- Nokia Android One (8.x): show
- Samsung Galaxy A5: (Android 12) : crash app

**Comment by ManhNTX** [comment]
PR: https://github.com/linagora/tmail-flutter/pull/741
