### ISSUE TITLE
Email attachment is not showed in TeamMail app (all platform) 

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#730]
### Desc:
- Email is sent from Openpaas 
- EML: 
[Report weekly.eml.zip](https://github.com/linagora/tmail-flutter/files/9130485/Report.weekly.eml.zip)

- Reported: v0.3.8 Prod

TeamMail:
![image](https://user-images.githubusercontent.com/6462404/179472667-46e58507-bde0-44b2-b5ab-0f53791fae6f.png)

Openpaas: (and other email client) work well
![image](https://user-images.githubusercontent.com/6462404/179472762-3c162ebd-4278-4aa8-b49c-3e28d001cb73.png)

**Comment by dab246** [comment]
I cannot reproduce this error. Please check back and provide more information

**Comment by hoangdat** [comment]
> I cannot reproduce this error. Please check back and provide more information

yes, maybe this email with `eml` above have the problem. Please check the eml for more details

**Comment by dab246** [comment]
The above `eml` file is completely normal. I didn't notice any problems. Please test again on the faulty devices to see if this problem occurs.
