### ISSUE TITLE
Some email can not change the `read` state after read it

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#732]
https://user-images.githubusercontent.com/6462404/179491424-a7d99b39-4912-45d5-8d1e-d03510235625.mov

**Comment by hoangdat** [comment]
Hi @chibenwa 
I found a weird. I request to `mark as read` for an email, but the `oldState` and `newState` are the same in response. Is it a problem?

Request:
```
{
  "using": [
    "urn:ietf:params:jmap:mail",
    "urn:ietf:params:jmap:core"
  ],
  "methodCalls": [
    [
      "Email/set",
      {
        "accountId": "{{accountId}}",
        "update": {
          "4b88b1b0-1949-11ed-9540-2f771fdb2d55": {
            "keywords/$seen": "true"
          }
        }
      },
      "c0"
    ],
    [
      "Email/get",
      {
        "accountId": "{{accountId}}",
        "ids": [
          "4b88b1b0-1949-11ed-9540-2f771fdb2d55"
        ],
        "properties": [
          "keywords"
        ]
      },
      "c1"
    ]
  ]
}
```

Response:
```
{
  "sessionState": "2c9f1b12-b35a-43e6-9af2-0106fb53a943",
  "methodResponses": [
    [
      "Email/set",
      {
        "accountId": "{{accountId}}",
        "oldState": "49221850-1951-11ed-9540-2f771fdb2d55",
        "newState": "49221850-1951-11ed-9540-2f771fdb2d55",
        "updated": {
          "4b88b1b0-1949-11ed-9540-2f771fdb2d55": null
        }
      },
      "c0"
    ],
    [
      "Email/get",
      {
        "accountId": "{{accountId}}",
        "notFound": [],
        "state": "49221850-1951-11ed-9540-2f771fdb2d55",
        "list": [
          {
            "id": "4b88b1b0-1949-11ed-9540-2f771fdb2d55",
            "keywords": {
              "$seen": true
            }
          }
        ]
      },
      "c1"
    ]
  ]
}
```

**Comment by hoangdat** [comment]
It is a sometime-issue. Hard to reproduce. Can you take a look on my comment: https://github.com/linagora/tmail-flutter/issues/732#issuecomment-1211841321. Thank @chibenwa

**Comment by hoangdat** [comment]
<img width="733" alt="image" src="https://user-images.githubusercontent.com/6462404/184158580-9bdeaa0f-5db3-45ba-a824-42962d2e36a5.png">

One more question about `ifInState`. Can you explain more to me? @chibenwa

**Comment by chibenwa** [comment]
> One more question about ifInState. Can you explain more to me? 

This is not supported by James. The update is then applied only if the mail did not change.

> I request to mark as read for an email, but the oldState and newState are the same in response. Is it a problem?

No. It is known. Should not be an issue. Worst case that is extra query upon resynch.

To explain it: state update is asynchronous, thus might not be completed by the end of the update.
