### ISSUE TITLE
Search mail

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#76]
### Description: 

Search mail UX for different devices: Mobile, Tablet, ...

**Comment by chibenwa** [comment]
https://www.figma.com/proto/of2CfuDyhYPFFu4D1hrKzP/Mailbox?node-id=146%3A118

**Comment by hoangdat** [comment]
It is too complex for mobile UX, we will try to figure out the best UX for mobile, and tablet also.
First, @dieptran88  will compare to the other competitor application.

**Comment by chibenwa** [comment]
IMO you could have a simplified UX with only few fields and have a way to move to a more advanced search,

**Comment by hoangdat** [comment]
please help me the simplest request for search with text pattern, all the email which have subject, content include this text will be return?

**Comment by chibenwa** [comment]
> please help me the simplest request for search with text pattern, all the email which have subject, content include this text will be return? (same with the current UX of Gmail)

Looks legitimate to me.

**Comment by chibenwa** [comment]
Maybe also flagged (star)

**Comment by hoangdat** [comment]
> please help me the simplest request for search with text pattern, all the email which have subject, content include this text will be return? (same with the current UX of Gmail)

@chibenwa please help me the request for the search.

**Comment by chibenwa** [comment]
```
{
  "using": ["urn:ietf:params:jmap:core", "urn:ietf:params:jmap:mail"],
  "methodCalls": [[
    "Email/query",
    {
      "accountId": "29883977c13473ae7cb7678ef767cbfbaffc8a44a6e463d971d23a65c1dc4af6",
      "filter": {"text": "banana"}
    },
    "c1"]]
}
```

Will search the body, cc, bcc, to, from and subject.

**Comment by hoangdat** [comment]
With `query` we should add `Email/get` also to show preview in the result. Am I right?

Why not use `searchSnippet/get`? It seems simpler than `query + get`?

**Comment by chibenwa** [comment]
> With query we should add Email/get also to show preview in the result. Am I right?

Right.

`searchSnippet` are not implemented in James.

(And it is actually Email/query + SearchSnipset/get + Email/get)
