### ISSUE TITLE
Inline images are not saved and shown successfully in Draft

### ISSUE THREAD

**Issue by hantt12** [linagora/tmail-flutter#764]
https://images.zenhubusercontent.com/378835363/30931634-3c8f-438c-8788-0c115b97d092/2022_07_27_10_33_11.mp4

**Comment by hoangdat** [comment]
@hantt12 you paste image to editor?

**Comment by hoangdat** [comment]
@ManhNTX please provide video to prove we don't have problem with draft? (in the case pick inline image)

**Comment by ManhNTX** [comment]
@hantt12 I don't see step choosing an image in your video. Can you tell me how you put that picture in the composer editor?

**Comment by hantt12** [comment]
Hi I just copy image from other image editor (snagit, snipping tool) and paste to composer 

https://user-images.githubusercontent.com/53081477/181426725-7bbb589d-9028-4fdf-ab64-34ae38ee8317.mp4

**Comment by hoangdat** [comment]
### DoD: 

- [ ] Support Copy/Paste for only Image to Composer

**Comment by hoangdat** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Tmail-Flutter-60d039db6ef62a0013432c14/issues/linagora/tmail-flutter/764?planning-poker) with ZenHub @dab246 @ManhNTX

**Comment by dab246** [comment]
1 HD

**Comment by haftus98** [comment]
verified
