### ISSUE TITLE
[Tablet/Mobile] Share image with TeamMail app

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#768]
### Desc: 
```
As a user, I pick the color in the phone, and I want to send this image though TeamMail
```

### DoD: 
- [x] TeamMail is listed in `Share with ...` when user want to share images
- [x] Open composer with the images are inline image
- [x] Images need be verified with the limitation

**Comment by dab246** [comment]
- Stuck in iOS

**Comment by dab246** [comment]
2 HD

**Comment by haftus98** [comment]
verified on 0.3.17 android and IOS
