### ISSUE TITLE
[Mobile/Tablet] Take a picture in composer

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#769]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC

* TODO: {link}

## Definition

**UC1. Take a photo in composer**
- Given that I am a Tmail user
- After log-in successfully to the Tmail, I open a new composer
- On the composer screen, I can see a new option: Take a photo or video
- When I select this option, the system will check:
   - If the app is not yet granted permission to access Camera, there will be a confirmation popup/instruction. After I confirm the permission, the camera will be opened. I can take a photo as normally, then I can select options: Use photo or Retake.
- If I select option Use photo, the picture will be inserted to the email body as an inline image. The image is shown in preview mode.
- If I select option Retake, the photo will be discarded and I can take another photo.
- In camera screen, I can click cancel to close the camera and back to the composer screen. 

**UC2. Take a video in composer**

- Given that I am a Tmail user
- After log-in successfully to the Tmail, I open a new composer
- On the composer screen, I can see a new option: Take a photo or video
- When I select this option, the system will check:
   - If the app is not yet granted permission to access Camera, there will be a confirmation popup/instruction. After I confirm the permission, the camera will be opened.
- I can see 2 modes: Photo or Video, the default is photo, I ca swipe screen to change to Video mode.
- In video mode, I can start to record the video
- After stop recording, I can see 2 options: Use video or Retake.
- If I select option Use video, the picture will be attached to the email as an attachment.
- If I select option Retake, the recorded video will be discarded and I can take another video.

[Back to Summary](#summary)

## Design ticket

[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

**Comment by hoangdat** [comment]
@dieptran88 please help me about the story for this ticket

**Comment by chibenwa** [comment]
Not supported in GMail on Android.

Is this needed @hoangdat @dieptran88 ?

If yes please reopen.

**Comment by hoangdat** [comment]
Agree
