### ISSUE TITLE
Sender email is not display fully when there is hyphen character

### ISSUE THREAD

**Issue by tuanlc** [linagora/tmail-flutter#778]
### Description
- In the list of emails, if my email contains hyphen character (eg: dev-noreply@twake.app), then the sender info is displayed only `dev-` but not full of the sender email

### Expected result
- the sender info should be `dev-noreply@twake.app`

#### Reproduction Steps

https://user-images.githubusercontent.com/7950991/182066886-42d6ddde-650e-4764-928e-18d16a63569f.mp4

### Context

Devices: Desktop , Web
OS: Archlinux

**Comment by dab246** [comment]
2 HD
