### ISSUE TITLE
Update settings with new design `Universal Settings`

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#788]

**Comment by hoangdat** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Tmail-Flutter-60d039db6ef62a0013432c14/issues/linagora/tmail-flutter/788?planning-poker) with ZenHub @dab246 @ManhNTX

**Comment by dab246** [comment]
2 HD

**Comment by dab246** [comment]
2 HD

**Comment by dab246** [comment]
2 HD
