### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#794]
### Description

When I turn on French some stuff is displayed in English.

### Expected result

Should all be in French...

### Current behavior

![Screenshot from 2022-08-03 08-46-13](https://user-images.githubusercontent.com/6928740/182506795-29370fe0-5a7f-4793-853f-c11e23e857a9.png)

![Screenshot from 2022-08-03 08-44-10](https://user-images.githubusercontent.com/6928740/182506813-952daec3-cec3-4967-adb5-ab0c489bc13b.png)

![Screenshot from 2022-08-03 08-45-33](https://user-images.githubusercontent.com/6928740/182506800-84763c68-fcda-4c2c-ae06-3fa6599053f4.png)

![Screenshot from 2022-08-03 08-45-17](https://user-images.githubusercontent.com/6928740/182506805-afe4d7fd-7d85-4014-a91b-5de93f752c44.png)

![Screenshot from 2022-08-03 08-44-42](https://user-images.githubusercontent.com/6928740/182506809-d2832e7e-45df-492c-8ca8-f0a83e70a155.png)

### Context

openpaas.linagora.com

**Comment by hoangdat** [comment]
Hi @chibenwa, it is nice if we have a French contributor for the localization. Our localization are open for contribute in https://hosted.weblate.org/projects/linagora/teammail/

**Comment by chibenwa** [comment]
Ok I contributed the missing french translations.

BTW I am sure we can improve the VN translation...

![Screenshot from 2022-08-03 15-15-05](https://user-images.githubusercontent.com/6928740/182558952-19280a00-7806-410b-9baa-593e627a39da.png)

**Comment by hoangdat** [comment]
sure
