### ISSUE TITLE
 [Story] As a user, I want to enable my vacation responder 

### ISSUE THREAD

**Issue by dieptran88** [linagora/tmail-flutter#801]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC

* TODO: {link}

### UC1. Enable Vacation responder setting
- Given that I am a Tmail user 
- After logged in successfully, I click on my avatar and select option Settings, the setting screen will be opened.
- In Setting screen, there will be a new section: Vacation setting.
- In Vacation setting screen, I can see information: 
   - Vacation responder toggle
   - Start date: I need to select date and time of the start date of vacation. There will be a date picker and a time picker. 
   - End date:  I need to select date and time of the start date of vacation. The end date need to be greater than start date. 
   - Message body: This is the content in the boby of the email which will be replied automatically when my vacation responder is activated. This field cannot be blank. 
- When I click button Save, if thers is no error, there will be a confirmation message: "Vacation settings saved"
- If the vacation responder toggle is enabled, there will be a float messgage "Your vacation responder is enabled." in every screen.

### UC2. Send responder automatically on vacation 
- Given that I enabled vacation responer
- Between the Start date and End date time of the vacation, when an email is sent to my Tmail account, the sender will receive an auto-reply email , with the message body in my vacation setting. 

#### UC3. Edit vacation setting
- When the vacation responder is enabled, I can edit its setting screen 
- I can edit Start Date/Time and End Date/Time of the vaction
- I can edit the message content field 
- When I click button Save, the system will validate: 
   - If the End date < Start date, there will be an error message
   - If the field "Message body" is blank, there will be an error message
- If there is no error, the setting is updated successfully with a notification message. 
- The new updates will be applied.

[Back to Summary](#summary)

## Screenshots
![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/961b8fe4-abd6-4540-a3b9-0d5854b87d8b)
None

[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

**Comment by dab246** [comment]
## Dev 

### Desc

1. Create `VacationResponse` in `jmap_dart_client` project
    - Add `VacationResponse` object
    - Extent `GetMethod` and `SetMethod` to implement `VacationResponse/get` and `VacationResponse/set`
    - Implement Vacation API with `VacationResponse/get` and `VacationResponse/set`

2. Integrate to `feature` in `tmail-flutter`
    - Add `Vacation Response` page in `Settings`
    -  In Vacation setting screen, add field:
 + Vacation responder toggle
 + Start date:
 + End date: 
 + Message body

### DoD:
- [x] Display Vacation responder setting

### Reference:
- [Docs](https://jmap.io/spec-mail.html#vacation-response)

**Comment by hoangdat** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Tmail-Flutter-60d039db6ef62a0013432c14/issues/linagora/tmail-flutter/801?planning-poker) with ZenHub @dab246 @ManhNTX

**Comment by dab246** [comment]
2 HD
