### ISSUE TITLE
[Story] As a user, I want to disable my vacation responder

### ISSUE THREAD

**Issue by dieptran88** [linagora/tmail-flutter#802]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC

* TODO: {link}

## Definition

- Given that I am a Tmail user and I enabled my Vacation responder before. 

#### UC1. Disable vacation responder manually

- After logged in successfully, I can see a float message: "Your vacation responder is enabled" in any screen. I click button Disable on the message, the vacation responser is turn off with a notification message: "You vacation responder is disabled successfully" and a Undo button. If I click Undo, the vacation responder is enabled again. 
- Or I click on my avatar and select option Settings, then select the section: Vacation setting. I disable the toggle :"Vacation responder", then click button Save, the vacation responder will be disabled with a confirmation message
- When the vacation responder is disabled, I can not edit any fields in screen Vacation setting. 

#### UC2. Disable vacation responder automatically
- On the End date and time of the Vacation responder, the vacation responder will be deactivated automatically by the system
- when I open the vacation setting screen, I will see a message: "Your vacation responder stopped on [End date + Time]. 

[Back to Summary](#summary)

## Screenshots

![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/82ce4977-9309-4315-aaef-102bbe2c4900)

[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

**Comment by dab246** [comment]
2 HD
