### ISSUE TITLE
[Story] As an user, i want to download attachments in a message

### ISSUE THREAD

**Issue by dieptran88** [linagora/tmail-flutter#81]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC

* TODO: {link}

## Definition
- Given that My local storage has enough space
- Given that i am a Tmail user and i already had an account (John Doe) and I log-in successfully to the Tmail app
- I open an message that contains attachments 
- I can see the total number of attachments, the total size of and list of attachment above the email body part:
- If the number of attachments is > 2 files, only 2 first files are shown by default and the remaining files are collapsed when opening email.
-  I can click on the number on attachment  to see the full list of files 
- If the number of file is </= 2, they are both displayed when opening the email and the expand/collapse icon is disabled. 
- I can scroll to see every attachment and the email body below 
- Each attached file will contain information: File name, file size, file icon and an download button 

 1. If the device is Android:
- When I touch the download button of an attachment : The download manager will conduct the download in the background
- When the download is completed i can touch the notification on the notification bar of the device to open the local folder that contains downloaded file 
2. If the device is iOS:
- When I touch the download button of an attachment , the selected file is started to be downloaded, i can see a popup showing Downloading progress
- After app downloaded file successfully, the [Pick destination] screen will be shown
- I can select a folder to save the downloaded file.

[Back to Summary](#summary)

## Screenshots

![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/987e56ac-855b-454c-85c2-f592673b2d80) ![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/a341b098-e724-4207-9ec5-1cb0dfa18297)

### iOS
![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/6203f1df-d9c8-4893-936a-9d49671139a8) ![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/34e40961-9c8b-4c8d-b4a5-3e7527be94a7)
[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

**Comment by chibenwa** [comment]
![9cee87b7-8de8-4d3e-91aa-c5f885956e06.png](https://images.zenhubusercontent.com/5ef2aee69879df3417738ce4/c8b2b069-6c8b-4900-b3f9-cf53e95a9e5c)

This screenshot is misleading: If you read fast you can really think there is only 2 attachments.

We could have a `...` displayed next to the two first rendered attachment. Visually it would be clear to the user that there is more...

OR we could decide to not render any attachments when there are two much, and just display `9 attachments (9MB) >> `

**Comment by dieptran88** [comment]
Do you think the space is quite small for both attachment and a three-dot button, and also when user see a three-dot button, he expects to touch that to open more 
![image](https://user-images.githubusercontent.com/68209176/133723604-ffcc6f6f-8e82-402e-8f75-ae31e86815f1.png)
 How about this
![image](https://user-images.githubusercontent.com/68209176/133724200-6467ef65-6da0-4e1a-a9d6-2777609cb841.png)
 @hoangdat WDYT

**Comment by chibenwa** [comment]
I'm OK with the show all proposal however when folded this should look  like: `>> Show all`

(in your exemple the arraws are pointing down wihile attachments are partly folded.)

**Comment by hoangdat** [comment]
My idea, no need too much information (text, label...)
![image](https://user-images.githubusercontent.com/6462404/133725378-9067474b-3c43-47ba-a03b-69c7e8ca7cff.png)

**Comment by chibenwa** [comment]
I fully agree with @hoangdat proposal
