### ISSUE TITLE
Autocomplete doesn't suggest correctly when searching recipients

### ISSUE THREAD

**Issue by tuanlc** [linagora/tmail-flutter#811]
### Description
When composing a new email, and enter recipient's email, the suggestions from the app are not correct

### Expected result
Suggest the results that close with the search terms

#### Reproduction Steps

https://user-images.githubusercontent.com/7950991/183332948-0ae29c94-9574-4db6-890c-f5ea21760528.mp4

### Context

- Devices: Desktop
- OS: Arch linux
- Browser: Firefox 102.0.1 (64-bit)

**Comment by chibenwa** [comment]
Configuration issue, 

Also we might consider n-graming only the local part?

**Comment by hoangdat** [comment]
What is `n-gramming`?

**Comment by chibenwa** [comment]
Basically for search we cut `vnhr@linagora.com` in 3-grams (ie 3 letters) (so `vnh` `nhr` hr@` .... `com`) and index those (build a reverse index & search.

**Comment by hoangdat** [comment]
You mean: 
- Client should cut the input text to `n-gram` to make `autocomplete/get` request?

**Comment by tuanlc** [comment]
@chibenwa 

> Also we might consider n-graming only the local part?

It's good to start and see the feedback from users

**Comment by tuanlc** [comment]
The issue isn't fixed and it seems even worse. The autocomplete feature doesn't work now :cry:

**Comment by hoangdat** [comment]
Hi @chibenwa any update for this ticket and #812 also

**Comment by chibenwa** [comment]
Not a (code) bug but more a configuration limitation.

I do not have LDAP schemas details, hence cannot help on this.

**Comment by hoangdat** [comment]
okie, so I open this ticket to keep it on radar.
