### ISSUE TITLE
When input name of recipient, autocomplete does not suggest any email

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#812]
### Desc:
- When I input the name of the recipient, no email is suggested.

https://user-images.githubusercontent.com/6462404/183339170-08e7777d-bfc9-4b4f-aaab-65557b7a881d.mov

@Arsnael as I listened right, `Giám đốc` had the same feedback in CoSoft?, Can you confirm?

**Comment by hoangdat** [comment]
@chibenwa @Arsnael please help me on this ticket also

**Comment by Arsnael** [comment]
Hm as I can see on your video it seems that firtsname lastname and email all have the same entry (email) thus why you can't search by name... Not sure why though... maybe the way we indexed the ldap entries?

**Comment by Arsnael** [comment]
@hoangdat is it something custom you run locally? Cause I don't see any jmap requests being made actually on tmail.linagora.com when I try to input a name when composing a message?

**Comment by chibenwa** [comment]
Ok, so on OpenPaaS.linagora.com aka TMail the LDAP does not follow the `InetOrgPerson` schema which means we do not have the standard fields for first/last name so we simply don't support these fields on this deployment.

It is a configuration issue and not a code issue.

**Comment by chibenwa** [comment]
Cc @quantranhong1999

**Comment by quantranhong1999** [comment]
As I asked @ducnm0711 before, we could run some LDAP commands (if we have access to the LDAP) to probe the schema, then we can adapt accordingly.
