### ISSUE TITLE
[Story] As a user, I want to see my list of forwarding recipients 

### ISSUE THREAD

**Issue by dieptran88** [linagora/tmail-flutter#816]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC

* TODO: {link}

## Definition

- Given that I am a Tmail user 
- After logged in successfully, I click on my avatar and select option Settings, the setting screen will be opened.
- In Setting screen, there will be a new section: Forwardings
- In this screen, I can see the list of recipients of forwarding: When a new email is sent to my email address, it will be forwarded to these email addresses
- Each item in the recipient list includes: Avatar, email address and a Delete button 
- In the top of the list, I can see a toggle: Keep local copy: 
   - If the toggle is enabled, when there is a new email, it will be in my Inbox and forwarded to the recipient lis.
   - If the toggle is disabled, when there is a new email, it will be forwarded to the recipient list and not kept in my Inbox.
- I can enable/disable this toggle and click button Save, then the above rule will be applied immediately.

[Back to Summary](#summary)

## Screenshots

![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/2ab014b0-7f1a-46b9-8f3b-dcd5926af1e5)

[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

**Comment by dab246** [comment]
## Dev 

### Desc

1. Create `Forward` module in `tmail-flutter` for `com:linagora:params:jmap:forward`
    - Add `Forward` object
    - Extent `GetMethod` to implement `Forward/get`
    - Implement Forward API with `Forward/get`

2. Integrate to `features` in `tmail-flutter`
    - If `Session` not include `com:linagora:params:jmap:forward`, `Forward` function is disabled and otherwise
    - Add `Forwarding` page in `Settings`
    - List all recipients of forwarding in the page

### DoD:

- [x] List all recipients of forwarding

### References:

- [Documents-Forwards](https://github.com/linagora/tmail-backend/blob/master/docs/modules/ROOT/pages/tmail-backend/jmap-extensions/forwards.adoc)
- [ForwardGetMethod-backend](https://github.com/linagora/tmail-backend/blob/master/tmail-backend/jmap/extensions/src/main/scala/com/linagora/tmail/james/jmap/method/ForwardGetMethod.scala)
-  [Integration Tests-backend](https://github.com/linagora/tmail-backend/blob/master/tmail-backend/integration-tests/jmap/jmap-integration-tests-common/src/main/scala/com/linagora/tmail/james/common/LinagoraForwardGetMethodContract.scala)

**Comment by dab246** [comment]
1 HD

**Comment by dab246** [comment]
2 HD

**Comment by dieptran88** [comment]
https://ci.linagora.com/linagora/lgs/design/-/issues/279
