### ISSUE TITLE
[Story] As an user, I want to save an email as draft

### ISSUE THREAD

**Issue by dieptran88** [linagora/tmail-flutter#82]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC

* TODO: {link}

## Definition
**UC1. Create a draft**
- Given that I am Tmail user and I logged-in the app
1.  I open composer to create an email 
- I can input some fields or not
- Then I click button Close or click button Back of Device
- The message will be saved automatically to the Draft mailbox 
- There will be a toast message  message: "Draft saved" with  a button Discard 
- If I select Discard, that email will be deleted. 
2. I open an email in thread-view 
- I click on button Reply or Forward
- The corresponding Composer will be opened 
- I can input some content or not 
- Then I click button Close click button Back of Device
- The message will be saved automatically to the Draft mailbox 
- There will be a toast message  message: "Draft saved" with  a button Discard 
- If I select Discard, that email will be deleted. 

**UC2. Edit a draft**
- When I open the folder Draft,  I can see the list of messages in the Thread-view
- I click on one email in the list, the composer will be opened and I can see the content that I left before 
- I can continue editing the fields in composer 
- If I click button Send and there is no error, the email is sent successfully and and moved to mailbox Sent , no longer in Draft mailbox
- If I click button Close or click button Back of Device, the message is saved as a new draft with the updated content 
- The old draft is removed when I open it.

[Back to Summary](#summary)

### Mobile
![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/30ed5df9-5ef4-4c66-9388-79f80ddd53c8) ![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/1ffb0304-4264-4968-ae39-ce4b9745b14c)
### Tab
![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/000e33ab-f427-43db-b4af-6b941f7c7985)
![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/380ee175-2a30-4f6d-a997-b2f5d71b657a)

## Design ticket
https://ci.linagora.com/linagora/lgs/design/-/issues/100

[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

**Comment by chibenwa** [comment]
And I want to reopen a draft to modify it and eventually send it.

And I should be able to create a draft (creates a new draft, deletes the old one)

BTW draft comes after user actions (star, move email) in my opinion

**Comment by dieptran88** [comment]
yes i just create the story tittle so i dont forget it, i will add details later

**Comment by hoangdat** [comment]
one more case for Draft:
```
I am composing an email,
I receive the call and jump to call app (video call or something like that)
I want my current email is in draft with latest writing
```

in technical site, how we can do that @chibenwa ?

**Comment by chibenwa** [comment]
> in technical site, how we can do that @chibenwa ?

We should do a `Email/set create` targetting the draft mailbox.

The call is exactly the same one than when sending email except:

  - you set `$Draft: true` in the keywords
  - you should not do the `EmailSubmission/setcreate` call as you do not want to send the email just yet.
  
Is that enough?

**Comment by hoangdat** [comment]
ah yes. simple :)

**Comment by chibenwa** [comment]
> ah yes. simple :)

`Email/set create + Email/set destroy` when updating a draft by the way.
