### ISSUE TITLE
[Story] As a user, I want to download email as `.eml` file

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#825]
Add an email action (web): `Download message as EML`

Can reuse OpenPaaS icon:

![Screenshot from 2023-04-05 10-04-10](https://user-images.githubusercontent.com/6928740/229971057-e6ee47ae-9244-4c69-9b4e-592937de7de4.png)

**Comment by hoangdat** [comment]
@dieptran88 please help me on this business case :)

**Comment by chibenwa** [comment]
Is it strictly needed?

I mean Ok this is useful for DEV but does GMail like services offers similar feature?

Does this makes sense on mobile or (if we implement it) we could implement it only for web?

**Comment by hoangdat** [comment]
I think it is useful, and I see it in many mail-client.
Gmail: yes
<img width="391" alt="image" src="https://user-images.githubusercontent.com/6462404/183841628-f110c2a1-4e76-491b-848e-3375d76ba100.png">

**Comment by hoangdat** [comment]
hi @chibenwa @Arsnael how to download `eml` file in JMAP?

**Comment by Arsnael** [comment]
Never looked into it tbh, not sure if you can do it on the front by just getting the email or if we need to do something on our side as well.

Not a priority anyways right now, both our teams are hella busy with customer issues

**Comment by chibenwa** [comment]
Just download the `blobId` associated with the email.
