### ISSUE TITLE
Missing content when rendering email detail

### ISSUE THREAD

**Issue by tuanlc** [linagora/tmail-flutter#826]
### Description
- I updated an calendar event, and then the event attendees will receive an email about the change. There is an attendee that left us and his mailbox was deleted. So, I received an email says: Undelivered Mail Returned to Sender
- The issue is when I open the email on Tmail app, the failed recipient address is missing.
- Then I use Thunderbird to check and the recipient address is displayed.

### Expected result
This is what I see when reading the email by Thunderbird
![image](https://user-images.githubusercontent.com/7950991/183853495-6d12ed34-6b0e-4a1f-ace4-91a076052bda.png)

At least the failed email should be displayed in the reason line:

```
qhta@linagora.com: mailbox does not exist
```

### Current behavior
Missing content, especially email address in the reason line as the screenshot

```
: mailbox does not exist
```

![image](https://user-images.githubusercontent.com/7950991/183852002-c6c6abee-3f51-4dce-a2f6-cd50d1be68c6.png)

#### Reproduction Steps
- Send an email to a mailbox that does not existing in Linagora. For example, left account: qhta@linagora.com
- You will receive an email about `Undelivered Mail Returned to Sender` 

### Context

- Devices: Desktop
- OS: Arch Linux
- Browser: Firefox

### Additional information
- EML:  
[emlfile.zip](https://github.com/linagora/tmail-flutter/files/9298249/emlfile.zip)

**Comment by hoangdat** [comment]
Hi Team, please re-check this issue, IMO, it is fixed in version > `v0.3.10`

**Comment by ManhNTX** [comment]
@tuanlc can you forward this email content you checked to tmnguyen@linagora.com ?
Thank for help.

**Comment by tuanlc** [comment]
I attached the eml file in the ticket. You can open the file by an email client to have the email content @ManhNTX

**Comment by haftus98** [comment]
I sent mail to qhta@linagora.com from Tmail. Then I received the auto mail at Outlook, Openpaas but Tmail

![image.png](https://images.zenhubusercontent.com/632aca085051fb7959dab94b/89f62cf3-0491-48dc-9664-004bf77a34f1)
