### ISSUE TITLE
[Story] As an user, i want to see constraints when sending a message

### ISSUE THREAD

**Issue by dieptran88** [linagora/tmail-flutter#83]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Definition
- Given that I am on Composer view
- After filling Recipient, Subject, email content, I click button Send
- The app will validate:
   - If the maxsize of the email is larger than limitation, there will be an error message and i cannot send this mail
   - If my Tmail account is out of quota, there will be an error message and i cannot send this mail
- If there is no error, the email will be sent  and it is moved to mailbox Sent 

[Back to Summary](#summary)

### Mobile
![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/b2e8afca-cdfa-44ef-bbf3-dfe285a06d22) ![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/1e7a3e97-d7a4-4e60-ac8a-6aa75d8700ae)
### Tab
![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/55ba4167-4399-4d84-91bd-e52153e87fb7)
![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/320aea7f-a174-4f98-a85d-519f704573e3)
[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

**Comment by chibenwa** [comment]
Which constraints are we speaking of?

Can't this be displayed as information in user account details?

In the composer I think we should only handle cases when these limits are exceeded.

**Comment by dieptran88** [comment]
Yes this story is for handling the constraints when sending email and these limits are exceeded. I will update soon

**Comment by hoangdat** [comment]
@dieptran88 please help me add the mockup for this story

**Comment by hoangdat** [comment]
@chibenwa `maxSizeAttachmentsPerEmail` is for each attachment file or for all attachments files in email?

```
GIVEN maxSizeAttachmentsPerEmail = 20Mb
```
file1 = 15Mb
file2 = 21 Mb
file3 = 6 Mb

Which file is valid?

**Comment by chibenwa** [comment]
`for all attachments files in email`

**Comment by hoangdat** [comment]
> `for all attachments files in email`

It means the total size in an email must less than `maxSizeAttachmentsPerEmail`. 
```
file1 + file2 + file3 = totalsize;
totalsize <= maxSizeAttachmentsPerEmail ? true : false;
```

**Comment by Kevinle2312** [comment]
Passed on the Production platform.
