### ISSUE TITLE
in replied email, `on` is miss the date

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#834]
<img width="459" alt="Screen Shot 2022-08-12 at 17 54 45" src="https://user-images.githubusercontent.com/6462404/184340564-b3487a1e-825d-482b-a0de-0773bfdcad85.png">

Reproduce:
1. Compose email 
2. Send
3. Open `Sent` folder -> open recent sent email 
4. Reply all 
5. observe the problem

**Comment by dab246** [comment]
1 HD

**Comment by haftus98** [comment]
verified
