### ISSUE TITLE
Refactor `RefreshChange` to sync `State`

### ISSUE THREAD

**Issue by dab246** [linagora/tmail-flutter#838]
### Desc:

- `State` of `Email`
- `State` of `Mailbox`

**Comment by hoangdat** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Tmail-Flutter-60d039db6ef62a0013432c14/issues/linagora/tmail-flutter/838?planning-poker) with ZenHub @dab246 @ManhNTX

**Comment by dab246** [comment]
2 HD
