### ISSUE TITLE
[iOS] Share image with TMail app but nothing happen

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#851]
https://user-images.githubusercontent.com/6462404/185113130-b9b95817-8553-4919-96e4-54452a64ef36.MOV

**Comment by dab246** [comment]
2 HD

**Comment by dab246** [comment]
Find the same log in empty trash:
```
Invalid argument(s): Illegal argument in isolate message: (object extends NativeWrapper - Library:'dart:io' Class: _SecureFilterImpl@13069316)
```

[https://github.com/dart-lang/sdk/issues/38964](https://github.com/dart-lang/sdk/issues/38964)

**Comment by ManhNTX** [comment]
PR : https://github.com/linagora/tmail-flutter/pull/893

**Comment by haftus98** [comment]
verified on IOS and android
