### ISSUE TITLE
Can't pop back on Web when reload

### ISSUE THREAD

**Issue by ManhNTX** [linagora/tmail-flutter#866]
https://images.zenhubusercontent.com/378835363/b3b637c8-683a-41f4-8f71-d54e8566cd99/screen_recording_2022_08_22_at_09_52_50.mov

**Comment by dab246** [comment]
### DoD
- Apply for rule screen, identity

**Comment by dab246** [comment]
1 HD

**Comment by dab246** [comment]
2 HD

**Comment by dab246** [comment]
1 HD

**Comment by dab246** [comment]
2 HD

**Comment by dab246** [comment]
2 HD
