### ISSUE TITLE
[Android] Share image with TeamMail app but image is not add to inline image

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#867]
### Reproduce:
1. Open Gallery app 
2. open an image
3. share 
4. Select TeamMail 
5. Team Mail app is open, but image is not inserted as an Inline Image.

### Expectation:
- [x] MULTIPLE images should be inserted as inline images
### Environment: 
Android 12 Galaxy A51

**Comment by dab246** [comment]
2 HD

**Comment by dab246** [comment]
2 HD
