### ISSUE TITLE
Unread/new emails are not loaded when opening folder

### ISSUE THREAD

**Issue by tuanlc** [linagora/tmail-flutter#868]
### Description
- I have a filter that direct emails from Gitlab.com to my `Gitlab` folder
- As you can see in the demo, the unread indicator is 7 for the folder but there is no unread/new emails in the list even I refresh the page
  
https://user-images.githubusercontent.com/7950991/185837959-ad156c4d-d27e-4232-a89f-88a6c818da7b.mp4

- I used Thunderbird to check and they are there
![image](https://user-images.githubusercontent.com/7950991/185838111-cf029a31-d68f-4d3d-a018-e85a3a7fb716.png)

- When using filter to list only unread messages, they are displayed

https://user-images.githubusercontent.com/7950991/185838360-597b232a-a716-47e6-9d0e-a4a341eb4ec4.mp4

### Expected result
- The unread messages should be displayed in the list
- The number of unread (indicator) should be consistent with the list

### Context

- Devices: Desktop (web)
- Browser: Firefox

**Comment by hoangdat** [comment]
Hi @tuanlc, that filter (which move email to Gitlab) is set up when? or someday ago?

**Comment by dab246** [comment]
1 HD

**Comment by dab246** [comment]
@tuanlc  
- Temporarily you can clear `cache` then `logout` and log back in to see if the same happens?
- Currently I can't reproduce to find your error. But I think it's because of saving the new `state`.

**Comment by dab246** [comment]
1 HD

**Comment by dab246** [comment]
2 HD

**Comment by hoangdat** [comment]
Reproduce (MAYBE) another case related to state in v0.3.13. 
Frequently: Always
Reason: Wrong logic in `ThreadRepository::getAllEmail` in the case caches email (>20) for one mailbox are filtered last time

https://user-images.githubusercontent.com/6462404/186950080-3f4843f7-c883-4573-8ba9-d24593c3ee86.mov

**Comment by dab246** [comment]
1 HD

**Comment by dab246** [comment]
2 HD

**Comment by dab246** [comment]
1 HD

**Comment by dab246** [comment]
1 HD

**Comment by dab246** [comment]
1 HD

**Comment by dab246** [comment]
1 HD
