### ISSUE TITLE
[Android] Cursor pointer indicator in composer is wrong color

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#874]
![Screenshot_20220822-173426_Team Mail](https://user-images.githubusercontent.com/6462404/185903479-24fed8b9-607c-4d4e-a13c-2c90c1bcb313.jpg)

**Comment by haftus98** [comment]
green still visible

**Comment by hoangdat** [comment]
please provide more information, App version? Android?, ....

**Comment by dab246** [comment]
It still work fine. @haftus98  Please send us more information about the device you are testing, current app version. 

![Screen Shot 2022-09-28 at 16.00.18.png](https://images.zenhubusercontent.com/605059df174a357c7888640f/e9850e57-596e-4141-afaf-7257dbb3de6d)

**Comment by haftus98** [comment]
@dab246 I'm checking  v 0.3.15, device galaxy a51

**Comment by haftus98** [comment]
https://images.zenhubusercontent.com/378835363/a488f9d3-4e03-4fb6-87db-e364bea76e69/4558209866958558593.mp4

Still green going on Android, I'm checking v 0.3.15, device galaxy a51

**Comment by chibenwa** [comment]
@haftus98 update on this?

**Comment by haftus98** [comment]
https://user-images.githubusercontent.com/97084773/206981049-c2a8f8fa-8e20-4795-97c7-c56a052f91ca.mp4

It's still green cursor
Android, v0.3.20 production and preproduction, device galaxy a51 and LG
