### ISSUE TITLE
[Dev] Add `MDN/send` and `MDN/parse` in `jmap_dart_client`

### ISSUE THREAD

**Issue by dab246** [linagora/tmail-flutter#878]
### DoD
- Add capability `urn:ietf:params:jmap:mdn` to use `MDN`
- Create object `MDN`
- Add method/response for `MDN/send` and `MDN/parse`
- Write unit-test

### Refers
- Docs [RFC9007](https://www.rfc-editor.org/rfc/rfc9007.html)

**Comment by dab246** [comment]
1 HD

**Comment by chibenwa** [comment]
What's the use case for `MDN/parse` ? 

IMO not needed...

**Comment by dab246** [comment]
1 HD

**Comment by dab246** [comment]
https://github.com/linagora/jmap-dart-client/pull/43
