### ISSUE TITLE
[Dev] Apply new design for rich text on mobile on new repository Linagora

### ISSUE THREAD

**Issue by dab246** [linagora/tmail-flutter#880]
### DoD
- Create new repository on Linagora with name `Rich-Text-Composer`
- Figma: [https://www.figma.com/file/rRVxJpCu1G22D0jqyvK7I9/TeamMail?node-id=5221%3A250131](https://www.figma.com/file/rRVxJpCu1G22D0jqyvK7I9/TeamMail?node-id=5221%3A250131)
- Show list button on keyboard for Mobile
![Screen Shot 2022-09-05 at 10.29.33.png](https://images.zenhubusercontent.com/605059df174a357c7888640f/ee7dac84-5f88-4ce1-84f3-06eec4fb08c7)
- Apply new design for `Format` popup menu
![Screen Shot 2022-09-05 at 10.35.52.png](https://images.zenhubusercontent.com/605059df174a357c7888640f/93404a4f-482c-46cb-9e0d-84a949f1e760)

**Comment by dab246** [comment]
1 HD

**Comment by dab246** [comment]
1 HD

**Comment by dab246** [comment]
2 HD

**Comment by hoangdat** [comment]
@ManhNTX please note that, stop the ticket after success 
```
Show list button on keyboard for Mobile
```
with function: `image`, `attachment` (style will be applied in other ticket)
for both android/iOS, and tablet. 
**Note:** No

**Comment by dab246** [comment]
2 HD

**Comment by dab246** [comment]
2 HD

**Comment by dab246** [comment]
2 HD

**Comment by dab246** [comment]
2 HD

**Comment by dab246** [comment]
2 HD

**Comment by dab246** [comment]
2 HD

**Comment by dab246** [comment]
Use https://github.com/linagora/rich-text-composer/pull/4
