### ISSUE TITLE
[Security] [Web] Password leaks

### ISSUE THREAD

**Issue by tuanlc** [linagora/tmail-flutter#886]
### Description
On web version, the user password is stored in plain text in Local Storage

![image](https://user-images.githubusercontent.com/7950991/186602119-9501bb49-3f39-4d0d-b975-3452f7bfcdd2.png)

#### Reproduction Steps
1. Login to the app
2. Open browser's Dev tool
3. Go to Application tab
4. Expand local storage item

### Context

- Devices, OS: Web - Desktop

**Comment by dab246** [comment]
@chibenwa Do you have any idea for  `tmail.linagora.com`?

**Comment by chibenwa** [comment]
IMO not really an issue as `plain auth` is not a target production deployement and we provide OIDC support.

We may consider `session store` for those creds in order to limit exposition?

**Comment by hoangdat** [comment]
> We may consider session store for those creds in order to limit exposition?

We are considering IndexedDB with encoded. We will do it before call LNG people use/test Tmail app.

**Comment by dab246** [comment]
- Use `Hive` database

**Comment by dab246** [comment]
1 HD

**Comment by dab246** [comment]
1 HD

**Comment by tuanlc** [comment]
I've tested on the Web version, the plain password is not stored in the local storage anymore. But your solution to use hive DB (aka Index DB on web) does not fix completely the security issue. The data can be read with some extra steps.

If you target to use OIDC, then it's OK with this. However, if Tmail is deployed on-premise, a mechanism to use temporary access token like JWT is necessary.

**Comment by haftus98** [comment]
Still visible on application tab
