### ISSUE TITLE
[Dev] Apply new design for Vacation

### ISSUE THREAD

**Issue by dab246** [linagora/tmail-flutter#888]
### DoD
- Figma: https://www.figma.com/file/rRVxJpCu1G22D0jqyvK7I9/TeamMail?node-id=5284%3A256990

**Comment by dab246** [comment]
### DoD
- Only apply new design have not support rich text
-  New design
![Screen Shot 2022-09-05 at 10.12.24.png](https://images.zenhubusercontent.com/605059df174a357c7888640f/040e148f-fb4b-4058-861d-a9db152ffa40)

**Comment by dab246** [comment]
2 HD

**Comment by haftus98** [comment]
Verified
