### ISSUE TITLE
[Feedback] Search results not show some new emails

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#895]

**Comment by chibenwa** [comment]
Please keep me in touch, this might very well come from limitations of our ElasticSearch search engine.

**Comment by hoangdat** [comment]
### DoD:
Given an email with bob@domain.tld

-> bob@domain.tld matches
-> bob (localpart) matches
-> domain.tld (domain) matches
-> domain (part of the domain) do not match. (and it should).

I think we could easily propose a better 'search experience' by improving indexing and searches for domains.

Traps to avoid:

Given bob@domain.tld search we should not return results of other addresses of domain.tld domain.

Given domain.tld search we should not return unrelated search results from the tld top-domain.

migration strategy will be aturaly covered upon the OpenSearch migration.

### Refs:
- Back-end: https://github.com/apache/james-project/pull/1212
