### ISSUE TITLE
  [Story] As a user, I want to create filtering rule in email detail dialog

### ISSUE THREAD

**Issue by dieptran88** [linagora/tmail-flutter#898]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC

* TODO: {link}

## Definition

- Given that I am a Tmail user
- After logged-in successfully, I open an email 
- When I click on three-dot button on the top right, I can see a drop-down list of options. I can see a new option "Create rule"
- Or when I click on an email address in the fields  "From", "To", the email detail dialog will be opened. On this dialog, I can see a button "Create rule"
- When I click on this button, the Create filter screen will be opened and the condition "From" is selected automatically, the value is the email address of the selected email in previous dialog/screen.
- I can continue input other fields :"Name", "Action" and create the filter as normally. 

[Back to Summary](#summary)

## Screenshots

![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/8d6043b9-9445-4dc7-8bde-73ece6c9f9ef)

## Design ticket

https://ci.linagora.com/linagora/lgs/design/-/issues/274

[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

**Comment by dab246** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Tmail-Flutter-60d039db6ef62a0013432c14/issues/linagora/tmail-flutter/898?planning-poker) with Zenhub @hoangdat @ManhNTX @sherlockvn

**Comment by dab246** [comment]
### DoD
- https://www.figma.com/file/rRVxJpCu1G22D0jqyvK7I9/TeamMail?node-id=2%3A12

**Comment by dab246** [comment]
- Toast message after click create rule
