### ISSUE TITLE
[Story] As a user, I want to create mailbox in Destination picker screen

### ISSUE THREAD

**Issue by dieptran88** [linagora/tmail-flutter#899]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC

* TODO: {link}

## Definition

- Given that I am a Tmail user
- When I am in Mailbox destination picker screen ( When I move a message/ Create rule...), I can see a button "Create"
- When I select this button, the screen Create new mailbox will be displayed.
-  I can input mailbox name and select mailbox location then click button Done as normal 
- After the new mailbox is created, I am redirected back to Mailbox destination picker screen
- Now the newly created mailbox is selected as the destination.

[Back to Summary](#summary)

## Screenshots

![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/cc6d9c41-57ab-4097-9fe8-fd2876dcbebf)

## Design ticket

https://ci.linagora.com/linagora/lgs/design/-/issues/273

[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

**Comment by dab246** [comment]
### DoD
- https://www.figma.com/file/rRVxJpCu1G22D0jqyvK7I9/TeamMail?node-id=2%3A13

**Comment by dab246** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Tmail-Flutter-60d039db6ef62a0013432c14/issues/linagora/tmail-flutter/899?planning-poker) with Zenhub @hoangdat @ManhNTX @sherlockvn

**Comment by hoangdat** [comment]
removed  it
