### ISSUE TITLE
Renaming repo

### ISSUE THREAD

**Issue by tanandy** [linagora/tmail-flutter#9]
hi team, couldnt we choose something more cool like tmail-flutter ?

**Comment by chibenwa** [comment]
I'm more in favor of feature oriented names instead of tech oriented names.

I would be in favour of 'tmail-mobile'

**Comment by tanandy** [comment]
yes, so we agree that we could change ui-user

**Comment by hoangdat** [comment]
because we can deploy this source code for desktop or browser in the future, so I choose `ui-user`. Not only `mobile`.

**Comment by hoangdat** [comment]
I voted for `tmail-flutter`:
- we use flutter
- we can have other tmail front-end

**Comment by hoangdat** [comment]
`tmail-flutter`
