### ISSUE TITLE
[Web] Not correct search result when close search box

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#900]
https://user-images.githubusercontent.com/6462404/188352117-4f506de9-18c7-4e63-a326-218ac191008f.mov

**Comment by hoangdat** [comment]
- [ ] change `hasKeyword` to use `text` in Advanced search

**Comment by dab246** [comment]
1 HD

**Comment by dab246** [comment]
2 HD

**Comment by haftus98** [comment]
[Uploading... Untitled_ Oct 11,2022 4_29 PM.webm]

Step 1: search sth
Step 2: remove the keyword then click enter => For now it's supposed to return the list of all mail but the result is the same as in filter applied result
Step3: Open the advanced search then click Search, now it returns the correct number

**Comment by haftus98** [comment]
still bug on web browser google chrome Version 106.0.5249.119 V0.3.17
@hoangdat

**Comment by dab246** [comment]
2 HD
