### ISSUE TITLE
[Web] Marked as read email is highlighted as unread email

### ISSUE THREAD

**Issue by tuanlc** [linagora/tmail-flutter#915]
### Description

In the email list, I've tried mark as read an email (with many ways as the demo) but it is still highlighted as unread email.

### Expected result

It should be remove highlighted.

#### Reproduction Steps

https://user-images.githubusercontent.com/7950991/188544398-243ba6b9-d04b-4d39-9918-530f3794e598.mp4

### Context

- Devices: Desktop
- Browser: Chromium

**Comment by dab246** [comment]
Fixed at #924

**Comment by haftus98** [comment]
Verified on Chrome, IOS, android, Outlook and thunderbird
