### ISSUE TITLE
[EPIC] Interoperate with Fastmail 

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#916]

**Comment by hoangdat** [comment]
Interoperation To-do list:
- [ ] handle `webfinger` error: 
   - [ ] handle httpCode:302
- [ ]

**Comment by hoangdat** [comment]
Hi @chibenwa, as I checked in https://www.iana.org/assignments/imap-mailbox-name-attributes/imap-mailbox-name-attributes.xhtml, no `outbox` role is defined. So, how to interoperate with Fastmail (As you know, we are send email failed because Fastmail does not have `outbox`)?
1. Auto generate `outbox` in tmail application? or
2. Support send email without `outbox` beside the current way of `tmail`?

What do you prefer? 1 or 2?

**Comment by chibenwa** [comment]
I think instead of relying on a mailbox with role outbox, we could instead use a mailbox named `Outbox` and create it if it do not exists. WDYT ?
