### ISSUE TITLE
Right click + open in a new tab should be nice for TMail web

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#934]
Right click + open in a new tab should be nice for TMail web.

https://user-images.githubusercontent.com/6928740/189344371-105b929d-5001-47de-9de5-0ab5871c9d92.mp4

Reported by Raoul Delpech.

Cc @hoangdat

**Comment by hoangdat** [comment]
### Desc:
- each email have id
- we can use `route path` to open an email in EmailView 

### DoD:
- [ ] separate route path for each email
- [ ] right-click in each item in ThreadView -> open in new tab
- [ ] can paste the route of this email -> run in new tab

**Comment by dab246** [comment]
2 HD

**Comment by dab246** [comment]
2 HD

**Comment by dab246** [comment]
1. Task done
- [x] Separate route path for each email
- [x] Can paste the route of this email -> run in new tab
2. Task waiting
- [ ] Right-click in each item in ThreadView -> open in new tab
3. Cause
- We are using `Link` widget of [url_launcher](https://pub.dev/packages/url_launcher) to support `right mouse click`. But now it affects the drag and drop of the widget.
- We will wait for further fix from `url_launcher` side (follow here https://github.com/flutter/plugins/pull/6282). Or research more solutions to create a separate popup menu when `right mouse click`. It will be implemented in another ticket.
