### ISSUE TITLE
 [Story] As a user, I want to jump to the mailbox that contains the selected email. 

### ISSUE THREAD

**Issue by dieptran88** [linagora/tmail-flutter#948]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC

* TODO: {link}

## Definition
**UC1. Jump to the mailbox from the search result screen**
- Given that I am a Tmail user
- After logged-in successfully, I open search email screen, input some criteria then click button Search, the result screen will be displayed.
- On the result screen, I can see the mailbox name of the email in reach row.
- When I click on the mailbox name, I am redirected to that mailbox view.

**UC2. Jump to the mailbox from the email content**
- I opened an email and see the email content view 
- On the top of screen, I can see the mailbox that contains current email
- When I hover this mailbox name, I can see a helper message: "Jump to this mailbox"
- When I click on this mailbox name, I am redirected to that mailbox view. 

[Back to Summary](#summary)

## Design ticket

https://ci.linagora.com/linagora/lgs/design/-/issues/281

[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

**Comment by dieptran88** [comment]
https://ci.linagora.com/linagora/lgs/design/-/issues/281

**Comment by chibenwa** [comment]
Is this really needed?

IMO no...
