### ISSUE TITLE
Can not download attachment of this email

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#949]
[Fwd_ Flutter Dev - 2 CV.eml.zip](https://github.com/linagora/tmail-flutter/files/9573520/Fwd_.Flutter.Dev.-.2.CV.eml.zip)

I also send this email to all the developer :)

**Comment by haftus98** [comment]
![image.png](https://images.zenhubusercontent.com/632aca085051fb7959dab94b/43966741-6632-478c-8a36-c606cfa2b929)

I can't download the attachment

**Comment by haftus98** [comment]
Can't download from 0.3.14 to 0.3.15 unless I clear cache

**Comment by hoangdat** [comment]
Broadcast information to user. if you can download, we will close and open the new one in further case
