### ISSUE TITLE
[Story] As a user, I want to open email in a new tab 

### ISSUE THREAD

**Issue by dieptran88** [linagora/tmail-flutter#954]
# Summary

* [Related EPIC](#related-epic)
* [Definition](#definition)
* [Screenshots](#screenshots)
* [Misc](#misc)

## Related EPIC

* TODO: {link}

## Definition

- Given that I am a Tmail user
- After log-in successfully in the web browser, I go to a mailbox and see the list of emails
- I right-click on an email iem and see default browser's menu, including:
   - Open link in new tab
   - Open link in new window
   - Open link in incognito window
   - Save link as
   - Copy link address
...
- The default browser's menu can be different between browsers.

[Back to Summary](#summary)

## Screenshots

**Chrome:**

![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/868a60dc-3641-4acc-a7ba-c8a00e5ba2c3)

**Firefox:**

![20220919_092737.jpg](https://images.zenhubusercontent.com/5ef2aee69879df3417738ce4/9d0b96f8-2f53-44f3-a426-186f7a965995)

[Back to Summary](#summary)

## Misc

None

[Back to Summary](#summary)

**Comment by chibenwa** [comment]
```
I right-click on an email iem and see a list of options:

    Reply
    Reply all
    Forward
    Mark as read/unread
    Move
    Star/unstar
    Delete
    Open in a new tab
```

No I do not think we need email related options upon right click, just classical web browser link stuff is OK

![20220919_092737.jpg](https://images.zenhubusercontent.com/5ef2aee69879df3417738ce4/9d0b96f8-2f53-44f3-a426-186f7a965995)

**Comment by hoangdat** [comment]
#934

**Comment by hoangdat** [comment]
28 Nov 2022: v0.4.3: only support open in new tab by button in Email item, still have problem with native support from browser.

**Comment by chibenwa** [comment]
I suggest opening a new issue (`UX` tag) for opening a mail in a new tab with right click and close this.

**Comment by chibenwa** [comment]
New issue https://github.com/linagora/tmail-flutter/issues/1723
