### ISSUE TITLE
[Feedback] - In log-in screen If I input wrong information, I dont know what field was wrong 

### ISSUE THREAD

**Issue by dieptran88** [linagora/tmail-flutter#961]
### Description

- In Log-in screen for Tmail web, when I input wrong email/password, there is only 1 general message "Unauthorized" and this toast message only appears 1 second, and hard to see before it disappear

## Expectation

- The system detects exactly what field was wrong with a detail highlighted error message
- Keep the correct field so that I dont have to input it again 

## Screenshot

![image.png](https://images.zenhubusercontent.com/5fe051fa8d2c764dc30ad13b/86380ad0-3d77-4709-b35b-a19468ce9c63)

**Comment by dieptran88** [comment]
@hoangdat

**Comment by hoangdat** [comment]
yes, with the current version, we should not respond anything else. This problem will not here in the future with OIDC. Close :)
