### ISSUE TITLE
[Sub folder] Can't create level 3 folder

### ISSUE THREAD

**Issue by haftus98** [linagora/tmail-flutter#973]
[Untitled_ Sep 23,2022 2_42 PM.webm](https://user-images.githubusercontent.com/97084773/191914520-a8dbdbe1-32fe-43a1-933c-f9c290e0683f.webm)

**Current BH**
I added a sub folder to a subfolder (level 3) the system prompted "create failure"

**Expected**
I can create n level sub folder

**Testing environment**
production / chrome

**Comment by hoangdat** [comment]
oh, so weird, I still create a lot to test. let me check

**Comment by dab246** [comment]
@haftus98 @hoangdat 
This error is caused by you entering a name containing a special character `.`

**Comment by chibenwa** [comment]
`.` is the mailbox delimiter used in James. I guess you have a JMAP error regarding this... Correct?

**Comment by chibenwa** [comment]
![Screenshot from 2022-09-27 17-23-12](https://user-images.githubusercontent.com/6928740/192501536-c1791750-1635-46a1-8596-59ac8460073d.png)

Please manage the error correctly (better than OpenPaaS...) and let's move on.

**Comment by dab246** [comment]
@chibenwa Exactly. We will proceed to handle and report the exact error to the user.

**Comment by chibenwa** [comment]
Stupid suggestion: replace `.` by `·` ? XD

CF 

![Screenshot from 2022-09-27 17-48-40](https://user-images.githubusercontent.com/6928740/192506589-aaf40d22-3c77-4d2c-a1e1-7323b7a74bc0.png)

A bit dirty but this MIGHT just be enough to solve this x)
