### ISSUE TITLE
My INBOX is not fully displayed

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#978]
https://user-images.githubusercontent.com/6928740/192088251-e07e6d02-b021-42f0-8614-5001cce8c388.mp4

**Comment by dab246** [comment]
@hoangdat I think this issue has been resolved by us on ticket #868 . Please release version 0.3.15 to apply it.

**Comment by hoangdat** [comment]
@chibenwa please verify it in v0.3.15

**Comment by chibenwa** [comment]
Fixed
