### ISSUE TITLE
Allign identity cards ?

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#979]
### Description

Bottom of identity cards are not necessarily alligned...

![Screenshot from 2022-09-24 15-23-43](https://user-images.githubusercontent.com/6928740/192088385-7e6bfbcb-f044-47bf-b0e3-eae7839370ea.png)

**Comment by hknguyen91** [comment]
It depends on what users fill on the input, how much information was required

**Comment by chibenwa** [comment]
So what is the decision here?

**Comment by hknguyen91** [comment]
Just keep it flexible by its contents. Anyway, I asked Diep to create a new ticket, then I'll improve this function, I see some things that can improve

**Comment by chibenwa** [comment]
Like... `Default - Default` and `Demo - Demo`?

**Comment by hoangdat** [comment]
> Default - Default and Demo - Demo

yeah, the duplicated info

**Comment by hknguyen91** [comment]
@chibenwa In my design, these are aliases and depend on what users name it, not the same like our demo anyway  
![image](https://user-images.githubusercontent.com/95336527/195243162-7916d0c0-4a51-45ed-9f1c-39092a906afb.png)

**Comment by hoangdat** [comment]
okie let improve the design then we discuss more

**Comment by chibenwa** [comment]
Cool.

Once we are at it, can we display signature text too?

**Comment by chibenwa** [comment]
![Screenshot from 2023-04-05 10-12-19](https://user-images.githubusercontent.com/6928740/229972038-2c68e33b-050d-4b9b-b9ab-9b26a42653d2.png)

Fixed
