### ISSUE TITLE
I need to open identity to see the text signature

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#980]
### Description

![Screenshot from 2022-09-24 15-26-09](https://user-images.githubusercontent.com/6928740/192088415-ad3481bb-87f8-49ad-aed2-e44e39708f0a.png)

![Screenshot from 2022-09-24 15-26-15](https://user-images.githubusercontent.com/6928740/192088417-10f9b976-ff64-481b-a663-e9c107a50799.png)

I would expect either:
 - To get an option to view identity
 - To get everything display in the card

**Comment by hknguyen91** [comment]
@dieptran88 please create the design ticket for this feedback
