### ISSUE TITLE
Composer background color is broken

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#981]
### Description

https://user-images.githubusercontent.com/6928740/192088606-197c6176-2d6b-443c-a900-f1b82e8c983c.mp4

Either fix it.

Or remove it.

**Comment by dab246** [comment]
@chibenwa  
Please try to help me on the latest version `0.3.15`. 
I tried and didn't get the same error as yours. Watch the demo video below.

**Comment by dab246** [comment]
@chibenwa  
Please try to help me on the latest version `0.3.15`. 
I tried and didn't get the same error as yours. Watch the demo video below.

**Comment by chibenwa** [comment]
```
firefox -v
Mozilla Firefox 104.0
```


https://user-images.githubusercontent.com/6928740/192667551-4171832a-df10-4923-99f0-d279ccc5a6cf.mp4
