### ISSUE TITLE
Empty to when reply to self

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#982]
### Description

https://user-images.githubusercontent.com/6928740/192088765-97e48467-1dd0-4282-b9e7-cf76a0154c58.mp4

**Comment by dab246** [comment]
what are you happen?

**Comment by chibenwa** [comment]
I can propose what Thunderbird does:

 - When the email hass no recipients (self replies, forwards, blank composer) select the To field for input
 - When the email has reciepients and subject select the body for input
 
 

https://user-images.githubusercontent.com/6928740/198938913-2aa821a8-92d6-4261-b967-562709f3ba2b.mp4

WDYT?

**Comment by dab246** [comment]
### DoD
- Case 1: Only replay for myself then show dialog when send email with error no recipients.
- Case 2: More than myself in recipients then send as normal.

**Comment by chibenwa** [comment]
https://github.com/linagora/tmail-flutter/issues/1152 better specifies expected behaviour.
