### ISSUE TITLE
Move mailbox search up

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#983]
### Description

![Screenshot from 2022-09-24 15-34-48](https://user-images.githubusercontent.com/6928740/192088859-d6c074e4-aa4f-48bf-83e8-31b2b538aa21.png)

![Screenshot from 2022-09-24 15-34-51](https://user-images.githubusercontent.com/6928740/192088867-9723021e-b209-415e-a495-e05f96adea05.png)

Retionnals: this is only helpful when I have a looot of mailbox, but when I truely need it, this item is hard to reach

**Comment by dab246** [comment]
- Always show `My folders` title
- Search mailbox bar display below `My folders` title
