### ISSUE TITLE
Move to pannel: delimiter between default mailboxes and other mailboxes

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#984]
### Description

![Screenshot from 2022-09-24 15-39-15](https://user-images.githubusercontent.com/6928740/192088989-1dfdb5d8-b3b4-4470-ae74-1254515619c4.png)

**Comment by dab246** [comment]
2 HD

**Comment by dab246** [comment]
1 HD

**Comment by haftus98** [comment]
![image.png](https://images.zenhubusercontent.com/632aca085051fb7959dab94b/89d2d624-15f2-43dc-895d-8f39aac53161)


![5d23c6a44ee597bbcef4.jpg](https://images.zenhubusercontent.com/632aca085051fb7959dab94b/4b1d59a7-df8d-4b45-ad30-375f3342e20c)

No delimiter yet on web browser and mobile app

**Comment by hoangdat** [comment]
yes, no apply, please verify it with figma.
