### ISSUE TITLE
[WEB] Do not hide recipients infos

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#985]
### Description
![Screenshot from 2022-09-24 21-46-50](https://user-images.githubusercontent.com/6928740/192104515-7d21790c-0311-4a26-9b84-f6574bd594cb.png)

![Screenshot from 2022-09-24 21-48-55](https://user-images.githubusercontent.com/6928740/192104524-75a66ba2-468a-46e3-a47e-58ed65d26b92.png)

**Comment by hoangdat** [comment]
<img width="993" alt="image" src="https://user-images.githubusercontent.com/6462404/194267638-f7b35906-904c-4bfd-8b61-bb9a4fa767a4.png">

Please apply as the view

**Comment by hoangdat** [comment]
### DoD:
- each email should be show `name` if have it, fallback is `mail`
- when hover the mouse, each email should be clickable

**Comment by dab246** [comment]
2 HD

**Comment by dab246** [comment]
2 HD
