### ISSUE TITLE
Slightly re-arrange mailbox menu

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#986]
### Description
![Screenshot from 2022-09-24 21-46-48](https://user-images.githubusercontent.com/6928740/192104562-08f0d3da-54d8-4ab6-9e0e-6dfd61b4130d.png)

`Exchange` brings no meening. There's no use case IMO for folding system mailboxes. I propose to just remove `> Exchange`

Also `Folders` can become `My Folders` IMO

**Comment by dab246** [comment]
`#983`

**Comment by dab246** [comment]
1 HD
