### ISSUE TITLE
Identity, html template: use the rich text composer

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#988]
### Description

Today I need to manually type HTML within my signature. 

I'd expect:
 - To have rich text, with the rich text composer
 
 
![Screenshot from 2022-09-24 22-16-52](https://user-images.githubusercontent.com/6928740/192105819-703e10b8-bc1b-4679-ac99-cd1f93792310.png)

![Screenshot from 2022-09-24 22-16-38](https://user-images.githubusercontent.com/6928740/192105821-b63d9fc6-2681-42b6-8c2d-dc3b06a057d9.png)

**Comment by hoangdat** [comment]
same with #912
