### ISSUE TITLE
Mailbox: clicking ... for system mailboxes without emails have no effects

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#990]
### Description

In a system mailbox with no unread email (like my outbox) the `...` button have no action and clicking on it have no effects

https://user-images.githubusercontent.com/6928740/192106357-ae848314-17ee-4cb7-9880-d3319e9b327c.mp4

When that's the case, we would be better not displaying `...` in the first place.

**Comment by dab246** [comment]
Same #976
