### ISSUE TITLE
[STORY] Previous / Next message of a mailbox

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#996]
# Summary

- Given that I am a Tmail user and I have logged-in successfully 
- I am in mailbox view
- When I open a single email 
- I am able to navigate previous/next emails of this mailbox:
   - In web browser, I can click on chevron icon to navigate back and front 
   - In mobile app, I can swipe left and right to move to previous/next message

## Related EPIC

* TODO: {link}

## Definition

TODO

[Back to Summary](#summary)

## Screenshots

![Screenshot from 2022-09-26 17-00-33](https://user-images.githubusercontent.com/6928740/192253664-76e6a8d6-6539-4ab3-9f70-17be2fa9377e.png)

[Back to Summary](#summary)

## Design ticket

https://ci.linagora.com/linagora/lgs/design/-/issues/291

[Back to Summary](#summary)

**Comment by hoangdat** [comment]
@dieptran88 please create the design ticket and update this story

**Comment by dab246** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Tmail-Flutter-60d039db6ef62a0013432c14/issues/linagora/tmail-flutter/996?planning-poker) with Zenhub @hoangdat @ManhNTX @sherlockvn

**Comment by dab246** [comment]
### DoD
- Each call `next/previous` button will call api  get email with filter only contain `receiveTime` property in `EmailFilter` object. Ex:
+ Next button: `after`
+ Previous button: `before`

**Comment by dab246** [comment]
2 HD

**Comment by dab246** [comment]
2 HD
