### ISSUE TITLE
Custom date ranges in search

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#997]
# Summary

Today I have the following options in advanced search:

```
All Time (default)
Last 7 days
Last 30 days
Last 6 months
```

Please add a `custom range` option.

Promts an input for date from / date to.

**Comment by hoangdat** [comment]
Apply date range 

![image](https://user-images.githubusercontent.com/6462404/192429435-17204e65-f82a-4115-a295-01f1265f0cc2.png)

**Comment by dab246** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Tmail-Flutter-60d039db6ef62a0013432c14/issues/linagora/tmail-flutter/997?planning-poker) with Zenhub @hoangdat @ManhNTX

**Comment by dab246** [comment]
-  Create new  project on `Linagora` with name `Date Picker`

**Comment by dab246** [comment]
2 HD

**Comment by dab246** [comment]
2 HD

**Comment by haftus98** [comment]
https://user-images.githubusercontent.com/97084773/203107398-3debf17e-0bcd-4d36-8028-276a84b4057c.mp4

**Description**
When I selected custom range from mobile, there is no date picker for me to select. I can only select from web browser.

**Environment**
v0.4.2, IOS, Android
